import { allProducts, getProduct, type Product } from "@/lib/plans";
import { NARRATIVES, getNarrative } from "@/lib/narratives";
import { MEMBERSHIP_CONTENT, type MembershipBenefit } from "@/lib/membership-content";
import { FIELD_PRODUCT_COPY } from "@/lib/mini/field-product-copy";

export type MiniCatalogItem = {
  skuId: string;
  productId: string;
  name: string;
  nameEn: string;
  priceFen: number;
  accessType: Product["type"];
  days: number | null;
  category: "report" | "practice" | "membership" | "narrative";
  note: string;
  /** Public web product route. Report entry pages stay the single source of truth across web and Mini Program. */
  webPath?: string;
  /** Server-delivered intake hint. Native clients need no upload for copy/flow changes. */
  assessmentKind?: "life-map" | "relationship" | "daily-tide" | "birth" | "resilience" | "romance" | "wealth" | "archetype";
  assessmentIntro?: string;
  assessmentDescription?: string;
  assessmentDescriptionEn?: string;
  assessmentCta?: string;
  assessmentCtaEn?: string;
  knowledgeNodes?: string[];
  knowledgeNodesEn?: string[];
  field?: string;
  fieldLayer?: "field" | "convergence";
  detailDescription?: string;
  benefits?: MembershipBenefit[];
  closing?: string;
  cta?: string;
  autoGenerated?: boolean;
};

const FIXED_SKUS: Record<string, string> = {
  "life-map-report": "rpt_lifemap",
  "relationship-resonance": "rpt_relation",
  "qian-reading": "rpt_qian",
  "tarot-reading": "rpt_mirror",
  "resilience-report": "rpt_resilience",
  "romance-report": "rpt_romance",
  "daily-tide-report": "rpt_tide",
  "wealth-report": "rpt_wealth",
  "life-archetype": "rpt_archetype",
  breath: "pr_breath",
  intuition: "pr_intuition",
  "heart-reset": "pr_heart",
  "ascending-heart": "pr_ascending",
  day: "sub_manifest_1d",
  month: "sub_manifest_30d",
  year: "sub_manifest_365d",
  "narrative-all": "sub_narrative_365",
  everything: "sub_all_365",
};

const REPORT_IDS = new Set([
  "life-map-report",
  "relationship-resonance",
  "qian-reading",
  "tarot-reading",
  "resilience-report",
  "romance-report",
  "daily-tide-report",
  "wealth-report",
  "life-archetype",
]);

const REPORT_WEB_PATHS: Record<string, string> = {
  "life-map-report": "/life-map",
  "relationship-resonance": "/relationship",
  "qian-reading": "/qian",
  "tarot-reading": "/tarot",
  "resilience-report": "/resilience",
  "romance-report": "/romance",
  "daily-tide-report": "/daily",
  "wealth-report": "/wealth",
  "life-archetype": "/archetype",
};
const PRACTICE_IDS = new Set(["breath", "intuition", "heart-reset", "ascending-heart"]);
const MEMBERSHIP_IDS = new Set(["day", "month", "year", "narrative-all", "everything"]);
const UNAVAILABLE_NARRATIVE_IDS = new Set(
  NARRATIVES.filter((item) => item.status === "soon").map((item) => item.slug)
);

const ASSESSMENT_KIND: Record<string, NonNullable<MiniCatalogItem["assessmentKind"]>> = {
  "life-map-report": "life-map", "relationship-resonance": "relationship", "daily-tide-report": "daily-tide",
  "qian-reading": "birth", "tarot-reading": "birth", "resilience-report": "resilience",
  "romance-report": "romance", "wealth-report": "wealth", "life-archetype": "archetype",
};

const REPORT_INTAKE = Object.fromEntries(Object.entries(FIELD_PRODUCT_COPY).map(([productId, copy]) => [productId, {
  assessmentKind: ASSESSMENT_KIND[productId],
  assessmentIntro: copy.overviewZh.join("\n\n"),
  assessmentDescription: copy.cardDefinitionZh,
  assessmentCta: copy.ctaZh,
  knowledgeNodes: copy.keywordsZh,
}])) as Record<string, Pick<MiniCatalogItem, "assessmentKind" | "assessmentIntro" | "assessmentDescription" | "assessmentCta" | "knowledgeNodes">>;

const REPORT_DISPLAY_NAMES = Object.fromEntries(Object.entries(FIELD_PRODUCT_COPY).map(([productId, copy]) => [productId, { zh: copy.nameZh, en: copy.nameEn }])) as Record<string, { zh: string; en: string }>;

function categoryFor(productId: string): MiniCatalogItem["category"] {
  if (REPORT_IDS.has(productId)) return "report";
  if (PRACTICE_IDS.has(productId)) return "practice";
  if (MEMBERSHIP_IDS.has(productId)) return "membership";
  return "narrative";
}

// 微信道具 ID 仅允许英文字母、数字、下划线且最长 20 位。
// 叙事按价格共用道具；具体交付对象由已校验的 productId 与服务端订单绑定。
// 这样新增文章无需为每篇内容重复创建微信道具，同时不会混淆用户权益。
export function miniSkuForProduct(productId: string): string {
  if (productId === "life-archetype") return "";
  const fixed = FIXED_SKUS[productId];
  if (fixed) return fixed;
  const product = getProduct(productId);
  if (!product || UNAVAILABLE_NARRATIVE_IDS.has(productId)) return "";
  return `nar_${Math.round(product.priceRmb * 100)}`;
}

export function productForMiniPurchase(skuId: string, productId: string): Product | undefined {
  const product = getProduct(productId);
  if (!product || UNAVAILABLE_NARRATIVE_IDS.has(productId)) return undefined;
  return miniSkuForProduct(product.id) === skuId ? product : undefined;
}

export function getMiniCatalog(): MiniCatalogItem[] {
  return allProducts.filter((product) => !UNAVAILABLE_NARRATIVE_IDS.has(product.id)).map((product) => {
    const membershipContent = MEMBERSHIP_CONTENT[product.id];
    return ({
    skuId: miniSkuForProduct(product.id),
    productId: product.id,
    name: REPORT_DISPLAY_NAMES[product.id]?.zh ?? product.name,
    nameEn: REPORT_DISPLAY_NAMES[product.id]?.en ?? product.nameEn,
    priceFen: Math.round(product.priceRmb * 100),
    accessType: product.type,
    days: product.days ?? null,
    category: categoryFor(product.id),
    webPath: REPORT_WEB_PATHS[product.id],
    note: membershipContent?.description ?? (categoryFor(product.id) === "narrative" ? getNarrative(product.id)?.teaser ?? product.note : product.note),
    detailDescription: membershipContent?.description,
    benefits: membershipContent?.benefits,
    closing: membershipContent?.closing,
    cta: membershipContent?.cta,
    field: FIELD_PRODUCT_COPY[product.id]?.field,
    fieldLayer: FIELD_PRODUCT_COPY[product.id]?.layer,
    autoGenerated: product.id === "life-archetype",
    assessmentDescriptionEn: FIELD_PRODUCT_COPY[product.id]?.cardDefinitionEn,
    assessmentCtaEn: FIELD_PRODUCT_COPY[product.id]?.ctaEn,
    knowledgeNodesEn: FIELD_PRODUCT_COPY[product.id]?.keywordsEn,
    ...REPORT_INTAKE[product.id],
    });
  });
}
