import { type Product } from "@/lib/plans";
import { type MembershipBenefit } from "@/lib/membership-content";

export type MiniCatalogItem = {
  skuId: string;
  productId: string;
  name: string;
  nameEn: string;
  priceFen: number;
  accessType: Product["type"];
  days: number | null;
  category: "report" | "practice" | "membership" | "narrative";
  note: string;
  noteEn: string;
  webPath?: string;
  assessmentKind?: string;
  assessmentIntro?: string;
  assessmentDescription?: string;
  assessmentDescriptionEn?: string;
  assessmentCta?: string;
  assessmentCtaEn?: string;
  knowledgeNodes?: string[];
  knowledgeNodesEn?: string[];
  field?: string;
  fieldLayer?: "field" | "convergence";
  detailDescription?: string;
  detailDescriptionEn?: string;
  benefits?: MembershipBenefit[];
  closing?: string;
  closingEn?: string;
  cta?: string;
  ctaEn?: string;
  autoGenerated?: boolean;
};

// Native purchases stay closed until current-product SKUs pass payment acceptance.
export function miniSkuForProduct(_productId: string): string { return ""; }
export function productForMiniPurchase(_skuId: string, _productId: string): Product | undefined { return undefined; }
export function getMiniCatalog(): MiniCatalogItem[] { return []; }
