import { compileLivingChapter } from "@/lib/report-v340/living-report-compiler";
import { LIVING_REPORT_SPECS } from "@/lib/report-v340/product-chapter-registry";
import type { CrossEvidencePattern, EvidenceLeafV340, LivingNode, ReportProductKey } from "@/lib/report-v340/types";

export type ReportSignal={id:string;zh:string;en:string;score:number;meaningZh:string;meaningEn:string;actionZh:string;actionEn:string};
export type DendriteReportEntry={id:string;chapterId:string;chapterZh:string;chapterEn:string;titleZh:string;titleEn:string;briefZh:string;evidenceNodeIds:string[];confidence:"clear"|"developing"|"open";structureZh:string;structureEn:string;mechanismZh:string;mechanismEn:string;realityZh:string;realityEn:string;costZh?:string;costEn?:string;strengthZh?:string;strengthEn?:string;actionZh:string;actionEn:string;observationZh:string;observationEn:string};
export type ReportEvidenceLeaf={sourceProductId?:string;sourceRelationshipType?:"deep"|"business"|"other";questionId:string;evidenceDimension:string;promptZh:string;promptEn:string;answerId:string;answerZh:string;answerEn:string;answerSemantic:string;polarity:"support";nodeIds:string[];counterNodeIds:string[];strength:number;responseKind?:"preset"|"custom";matchConfidence?:number};
export type ReadingSlot={zh:string;en:string};

const PRODUCT_KEY:Record<string,ReportProductKey>={"life-map-report":"life-map","relationship-resonance:deep":"relationship-deep","relationship-resonance:business":"relationship-business","relationship-resonance:other":"relationship-other","resilience-report":"resilience","romance-report":"romance","wealth-report":"wealth","daily-tide-report":"daily-tide","tarot-reading":"life-mirror","qian-reading":"life-oracle"};
const EN_TITLES:Record<ReportProductKey,string[]>={
  "life-map":"Life Ground|Origin Drive|Perceptual Gate|Judgment Formation|Action Current|Inner Outer Drift|Vessel of Capacity|Latent Capacity|Life Tension|Present Pivot|Second Path".split("|"),
  "relationship-deep":"Reason for Meeting|Way of Approach|Attachment Rhythm|Hidden Needs|Expression Drift|Boundary Structure|Conflict Origin|Repair Capacity|The Unsaid|Relational Cost|Relational Direction".split("|"),
  "relationship-business":"Alliance Ground|Shared Interest|Rights and Duties|Decision Lead|Risk Bearing|Resource Exchange|Trust Formation|Interest Conflict|Position in Crisis|Long-term Cost|Continue Rebuild Exit".split("|"),
  "relationship-other":"Relational Origin|Role Position|Natural Distance|Giving and Receiving|Source of Expectation|Boundary Friction|Unfinished Words|Relational Inertia|Real Entanglement|Repairable Point|Fitting Distance".split("|"),
  resilience:"Source of Resilience|First Stress Response|Order of Imbalance|Recovery Gate|Crisis Mobilization|Adaptation to Change|Long Endurance|Stable Capacity|Cost of Rebound|Fragile Point|Regenerative Path".split("|"),
  romance:"Source of Attraction|What Is Seen|Hidden Magnetism|Initiative and Receptivity|Threshold of Approach|Selection Pattern|Repeated Attraction|Ambiguity Structure|Source of Mismatch|Conditions for Bond|Magnetic Pivot".split("|"),
  wealth:"Source of Wealth|Value Emergence|Creation Mode|Opportunity Sense|Resource Orchestration|Exchange Capacity|Receiving Capacity|Risk Pattern|Leakage Point|Scaling Lever|Next Wealth Path".split("|"),
  "daily-tide":"Main Tide|Morning Current|Perceptual Window|Decision Window|Action Window|Relational Tide|Wealth Tide|Pressure Tide|Advance|Pause|Return".split("|"),
  "life-mirror":"Matter in the Mirror|Visible Question|Hidden Pull|Cause of Repetition|Neglected Fact|What Emotion Protects|Relational Projection|Real Contradiction|Unseen Path|What to Return|Door Beyond Mirror".split("|"),
  "life-oracle":"Heart of the Question|Present Image|Present Position|Following the Current|Against the Current|What Is Feared|What Obstructs|Unseen Opening|Near Change|Possible Action|After the Oracle".split("|"),
};

function reportKey(productId:string,relationshipType:"deep"|"business"|"other"|undefined){return productId==="relationship-resonance"?`${productId}:${relationshipType??"deep"}`:productId;}
export function readingSlotsFor(productId:string,relationshipType:"deep"|"business"|"other"|undefined){const key=reportKey(productId,relationshipType);const product=PRODUCT_KEY[key];if(!product)return{key,slots:[] as ReadingSlot[]};return{key,slots:LIVING_REPORT_SPECS[product].map((spec,index)=>({zh:spec.titleZh,en:EN_TITLES[product][index]}))};}

function sentence(value:string){const clean=value.trim().replace(/[。；！？]+$/u,"");return clean?`${clean}。`:"";}
function distinctLeaves(leaves:ReportEvidenceLeaf[],index:number){if(!leaves.length)return[];const rotated=[...leaves.slice(index),...leaves.slice(0,index)];const dimensions=new Set<string>();const picked:ReportEvidenceLeaf[]=[];for(const leaf of rotated){if(dimensions.has(leaf.evidenceDimension))continue;dimensions.add(leaf.evidenceDimension);picked.push(leaf);if(picked.length===4)break;}return picked.length>=2?picked:[...new Map(rotated.slice(0,4).map(leaf=>[leaf.questionId,leaf])).values()];}
function selectedSignals(ordered:ReportSignal[],picked:ReportEvidenceLeaf[],index:number){const ids=[...new Set(picked.flatMap(leaf=>[...leaf.nodeIds,...leaf.counterNodeIds]))];const signaled=ids.map(id=>ordered.find(node=>node.id===id)).filter((node):node is ReportSignal=>Boolean(node));const fallback=[ordered[index%ordered.length],ordered[(index*3+1)%ordered.length],ordered[(ordered.length-1-index+ordered.length)%ordered.length]];const chosen=[...signaled,...fallback].filter((node,i,all)=>node&&all.findIndex(candidate=>candidate.id===node.id)===i);return{primary:chosen[0],support:chosen[1]??null,counter:chosen[2]??null};}
function livingNode(product:ReportProductKey,signal:ReportSignal,specQuestion:string,picked:ReportEvidenceLeaf[],role:"primary"|"support"|"counter"):LivingNode{const scenes=picked.filter(leaf=>leaf.nodeIds.includes(signal.id)||leaf.counterNodeIds.includes(signal.id)).map(leaf=>`${leaf.promptZh}——所应为「${leaf.answerZh.slice(0,90)}」`).slice(0,3);return{id:`${product}-${signal.id}`,product,titleZh:signal.zh,userPain:specQuestion,coreTruth:sentence(signal.meaningZh),requiresAny:[signal.id],strengthWhenActive:`${signal.zh}得其位，${sentence(signal.meaningZh)}`,costWhenOverused:`若${signal.zh}独任而无他力承接，长处亦会转为反复、迟滞或暗耗`,suppressedForm:`此力被压时，常非消失，乃改作迟疑、顺从或事后反悔`,livedScenes:scenes.length?scenes:[`回看近三次同类事件，辨${signal.zh}在何时先发、何时退场`],falsifiers:[`若近三次同类事件中，${signal.zh}从未先发，且改变它也不改变结果，则此断不立`],classicalLexicon:role==="counter"?["反观","受制"]:["见于","得其位"],modernEvidenceLexicon:picked.map(leaf=>leaf.evidenceDimension)};}
function v340Leaves(product:ReportProductKey,picked:ReportEvidenceLeaf[]):EvidenceLeafV340[]{return picked.map(leaf=>({id:leaf.questionId,product,dimension:leaf.evidenceDimension,context:leaf.evidenceDimension,answerSemantic:leaf.answerSemantic,strength:leaf.strength,confidence:leaf.matchConfidence??.82,supports:leaf.nodeIds,challenges:leaf.counterNodeIds,realityTags:[leaf.responseKind??"preset"]}));}
function confidence(level:string):DendriteReportEntry["confidence"]{return level==="已成主轴"||level==="证据清晰"?"clear":level==="正在形成"||level==="因境而异"?"developing":"open";}

export function buildReportEntries(productId:string,relationshipType:"deep"|"business"|"other"|undefined,ordered:ReportSignal[],leaves:ReportEvidenceLeaf[]=[]):DendriteReportEntry[]{const key=reportKey(productId,relationshipType);const product=PRODUCT_KEY[key];if(!product||ordered.length<3)return[];return LIVING_REPORT_SPECS[product].map((spec,index)=>{const picked=distinctLeaves(leaves,index);const{primary,support,counter}=selectedSignals(ordered,picked,index);const p=livingNode(product,primary,spec.question,picked,"primary");const s=support?livingNode(product,support,spec.question,picked,"support"):null;const c=counter?livingNode(product,counter,spec.question,picked,"counter"):null;const contradictions=picked.filter(leaf=>counter&&leaf.counterNodeIds.includes(counter.id)).map(leaf=>v340Leaves(product,[leaf])[0]);const pattern:CrossEvidencePattern={primary:p,support:s,counter:c,leaves:v340Leaves(product,picked),contradictions,confidence:picked.length>=4?"clear":picked.length>=3?"strong":picked.length>=2?"forming":"open"};const chapter=compileLivingChapter(spec,pattern);const custom=picked.find(leaf=>leaf.responseKind==="custom");return{id:spec.id,chapterId:spec.id,chapterZh:spec.titleZh,chapterEn:EN_TITLES[product][index],titleZh:spec.titleZh,titleEn:EN_TITLES[product][index],briefZh:`${spec.question} ${spec.resolves}`,evidenceNodeIds:[...new Set([primary.id,support?.id,counter?.id,...picked.flatMap(leaf=>leaf.nodeIds)].filter((id):id is string=>Boolean(id)))],confidence:confidence(chapter.evidenceLevelZh),structureZh:chapter.verdictZh,structureEn:`${primary.en} is the leading signal; ${support?.en??"supporting evidence"} determines whether it can hold in reality.`,mechanismZh:chapter.bodyZh,mechanismEn:`Independent contexts connect ${primary.en} with ${support?.en??"a second signal"}. Strength and cost are read together.`,realityZh:`所问：${spec.question}${custom?` 本人另述：「${custom.answerZh.slice(0,96)}」。此语独立入证，不改作预设答案。`:""}`,realityEn:`Question: ${spec.question} ${custom?"A self-authored response remains an independent evidence leaf.":""}`,strengthZh:`所得：${p.strengthWhenActive}`,strengthEn:`Strength: ${primary.meaningEn}`,costZh:`所费：${p.costWhenOverused}${counter?`；尤须察「${counter.zh}」长期未得其位之处。`:"。"}`,costEn:`Cost: when ${primary.en} acts alone, the weaker ${counter?.en??"counter-signal"} can become the hidden cost.`,actionZh:`行法：${sentence(primary.actionZh)}只取一处可见结果，不以自我感觉代替现实反馈。`,actionEn:`Action: ${primary.actionEn} Record one observable result.`,observationZh:chapter.verificationZh,observationEn:"Review three comparable events. If the sequence does not repeat, lower this reading rather than forcing a match."};});}
