import {PALACE_BEARING,directionLabel,sector} from "./compass";
import {sourceRule} from "./sources";
import type {AncientProviders,AncientTraceResult,QimenChart,RuleTrace,StellarAncientInput} from "./types";
function tr(id:"QM-XR-NM-001"|"QM-FQ-XR-002"|"QM-OBJECT-001"|"QM-ANIMAL-001"|"MOD-PALACE-DEG-001",inputs:RuleTrace["inputs"],outputZh:string):RuleTrace{const r=sourceRule(id);return{ruleId:r.id,system:"qimen",sourceTitle:r.sourceTitle,sourceChapter:r.sourceChapter,sourceUrl:r.sourceUrl,sourceNoteZh:r.sourceNoteZh,confidence:r.confidence,inputs,outputZh}}
export async function runQimen(input:StellarAncientInput,provider?:AncientProviders["qimen"]):Promise<AncientTraceResult>{
 if(!provider)return{system:"qimen",status:"unsupported",coverage:0,direction:null,distance:null,motion:null,environmentZh:[],evidence:[],warningsZh:["仓库尚未接入完整奇门起局器；拒绝用姓名哈希、行星角度或用户已知方向伪造落宫。"]};
 const chart:QimenChart|null=await provider(input);if(!chart)return{system:"qimen",status:"missing-input",coverage:0,direction:null,distance:null,motion:null,environmentZh:[],evidence:[],warningsZh:["奇门起局器未形成可审计局盘。"]};
 const b=PALACE_BEARING[chart.lifePalace];if(b==null)return{system:"qimen",status:"partial",coverage:.45,direction:null,distance:null,motion:null,environmentZh:[],evidence:[tr("QM-XR-NM-001",{lifeStem:chart.lifeStem,lifeBranch:chart.lifeBranch,lifePalace:chart.lifePalace},"年命落中宫；中宫不强行归一为地平方位。")],warningsZh:["中宫不得强行映射为任意八方。"]};
 const star=chart.starByPalace?.[chart.lifePalace]??null;const distance=star==="天蓬"?{normalizedBand:"very_far" as const,ancientUnit:"千里外（原典层级）",calibratedKm:null}:star==="天芮"?{normalizedBand:"near" as const,ancientUnit:"千里内（原典层级）",calibratedKm:null}:{normalizedBand:"unknown" as const,calibratedKm:null};
 const door=chart.doorByPalace?.[chart.lifePalace]??null;const environmentByDoor:Record<string,string[]>={休:["静处","休憩处","近水之象"],生:["出入口","生发之处"],伤:["道路","器械附近"],杜:["闭塞处","柜体或遮挡后"],景:["明亮处","可见标识附近"],死:["低处","久置处","封闭处"],惊:["声响处","门窗或移动边缘"],开:["开放处","通道或入口"]};const environmentZh=door?environmentByDoor[door]??[]:[];
 const motion=door==="杜"||door==="死"?{state:"blocked" as const,noteZh:`临${door}门，动静象偏闭塞或受阻。`}:door==="休"?{state:"stationary" as const,noteZh:"临休门，动静象偏静止或停留。"}:door?{state:"unknown" as const,noteZh:`临${door}门，只保留门象，不据此断定现实移动。`}:{state:"unknown" as const,noteZh:"门象未成，动静不强断。"};
 const ruleId=chart.targetRuleId??"QM-XR-NM-001";const targetLabel=input.targetKind==="object"?"甲子戊":input.targetKind==="animal"?"六畜用神":"年命";
 return{system:"qimen",status:"ok",coverage:.78,direction:{centerDeg:b,sector:sector(b,22.5),labelZh:directionLabel(b)},distance,motion,environmentZh,evidence:[tr(ruleId,{targetKind:input.targetKind??"person",targetSubtype:input.targetSubtype??null,lifeStem:chart.lifeStem,lifeBranch:chart.lifeBranch,lifePalace:chart.lifePalace,star,door,dun:chart.dun??null,ju:chart.ju??null},`${targetLabel}落${chart.lifePalace}宫，临${door??"门象未定"}、${star??"星象未定"}，原典层取得${directionLabel(b)}方位；远近仅保留原典等级。`),tr("MOD-PALACE-DEG-001",{palace:chart.lifePalace,normalizedBearing:b},`${chart.lifePalace}宫在现代归一层记为${b}°。`)],warningsZh:["未完成历史盲测校准前，不把古法远近层换算为公里。"],debug:chart.debug};
}
