"use client";
import { useState } from "react";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {toolUiText} from "@/lib/tool-ui-i18n";
import {workbenchCopy} from "@/lib/tools/workbench-i18n-v1473";
async function canvas(file:File,maxW:number,quality:number,type:string){const b=await createImageBitmap(file);let w=b.width,h=b.height;if(maxW>0&&w>maxW){h=Math.round(h*maxW/w);w=maxW;}const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d")!;if(type==="image/jpeg"){x.fillStyle="#fff";x.fillRect(0,0,w,h);}x.drawImage(b,0,0,w,h);b.close?.();return await new Promise<Blob>((res,rej)=>c.toBlob(v=>v?res(v):rej(new Error("EXPORT_FAILED")),type,quality));}
export default function BatchImageWorkbench(){
 const{lang}=useLingxiLang();const t=(zh:string,en:string)=>toolUiText(lang,zh,en);
 const [files,setFiles]=useState<File[]>([]);const [maxW,setMaxW]=useState(1920);const [quality,setQuality]=useState(.82);const [type,setType]=useState("image/jpeg");const [busy,setBusy]=useState(false);const [stage,setStage]=useState("");
 async function run(){setBusy(true);setStage(t("正在处理…","Processing…"));try{const JSZip=(await import("jszip")).default;const zip=new JSZip();let i=0;for(const f of files){i++;setStage(`${t("正在处理…","Processing…")} ${i}/${files.length} · ${f.name}`);const b=await canvas(f,maxW,quality,type);const ext=type==="image/png"?"png":type==="image/webp"?"webp":"jpg";zip.file(f.name.replace(/\.[^.]+$/,"")+"."+ext,b);}setStage(t("正在生成 ZIP…","Creating ZIP…"));const z=await zip.generateAsync({type:"blob"});const u=URL.createObjectURL(z),a=document.createElement("a");a.href=u;a.download="lingxifield-images.zip";a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);setStage(t("完成","Done"));}finally{setBusy(false);}}
 return <div className="space-y-4"><label onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFiles(Array.from(e.dataTransfer.files).filter(f=>f.type.startsWith("image/")))}} className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><input type="file" accept="image/*" multiple className="hidden" onChange={e=>setFiles([...(e.target.files||[])])}/><b>{t("一次选择多张图片","Select multiple images at once")}</b><p className="mt-1 text-sm text-slate-500">{workbenchCopy(lang,"batchImageLead")}</p></label><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">{t("最大宽度 px","Max width px")}<input type="number" value={maxW} onChange={e=>setMaxW(Number(e.target.value)||0)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"/></label><label className="text-sm">{t("质量 0.4–0.95","Quality 0.4–0.95")}<input type="number" min=".4" max=".95" step=".05" value={quality} onChange={e=>setQuality(Number(e.target.value)||.82)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"/></label><label className="text-sm">{t("输出格式","Output format")}<select value={type} onChange={e=>setType(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></label></div>{files.length>0&&<p className="text-sm text-slate-500">{lang==="zh"?`已选 ${files.length} 张`:`${files.length} ${files.length===1?"image":"images"} selected`}</p>}<button disabled={!files.length||busy} onClick={run} className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white disabled:opacity-40">{busy?t("处理中…","Working…"):t("批量处理并下载 ZIP","Process batch & download ZIP")}</button>{stage&&<p className="text-sm text-slate-500">{stage}</p>}</div>;
}
