"use client";
import {useEffect,useState} from "react";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {privacyText} from "@/lib/privacy-tools-i18n";
function bytes(s:string){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s);return Uint8Array.from(b,c=>c.charCodeAt(0))}
export default function BurnAfterReadReveal({id}:{id:string}){
 const{lang}=useLingxiLang();const t=(k:string)=>privacyText(lang,k);const[value,setValue]=useState(""),[status,setStatus]=useState<"idle"|"busy"|"shown"|"gone"|"error">("idle"),[seconds,setSeconds]=useState<number|null>(null);
 async function reveal(){const keyPart=new URLSearchParams(location.hash.slice(1)).get("k");if(!keyPart){setStatus("error");return}setStatus("busy");try{const r=await fetch("/api/tools/burn-after-read/consume",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id})});const d=await r.json().catch(()=>({}));if(r.status===410){setStatus("gone");return}if(!r.ok)throw new Error();const key=await crypto.subtle.importKey("raw",bytes(keyPart),{name:"AES-GCM"},false,["decrypt"]);const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:bytes(d.iv)},key,bytes(d.ciphertext));setValue(new TextDecoder().decode(plain));setSeconds(d.view_duration_seconds??null);history.replaceState({},document.title,location.pathname);setStatus("shown")}catch{setStatus("error")}}
 useEffect(()=>{if(status!=="shown"||seconds==null)return;if(seconds<=0){setValue("");setStatus("gone");return}const x=setTimeout(()=>setSeconds(v=>v==null?null:v-1),1000);return()=>clearTimeout(x)},[status,seconds]);
 return <div className="mx-auto max-w-2xl rounded-3xl border border-slate-200 bg-white p-6"><h1 className="text-2xl font-semibold text-slate-950">{t("recipient")}</h1>{status==="idle"&&<><p className="mt-3 text-sm leading-6 text-slate-600">{t("recipientD")}</p><button onClick={reveal} style={{background:"#111827",color:"#fff"}} className="mt-5 rounded-full px-5 py-3 text-sm font-medium">{t("open")}</button></>}{status==="busy"&&<p className="mt-5 text-sm text-slate-500">{t("opening")}</p>}{status==="shown"&&<div className="mt-5 rounded-2xl bg-slate-50 p-5">{seconds!=null&&<div className="mb-3 text-sm font-semibold text-rose-600">{seconds}s · {t("left")}</div>}<p className="mb-3 text-xs text-slate-500">{t("handled")}</p><pre className="whitespace-pre-wrap break-words text-sm leading-6 text-slate-900">{value}</pre></div>}{status==="gone"&&<p className="mt-5 text-sm text-slate-500">{t("gone")}</p>}{status==="error"&&<p className="mt-5 text-sm text-rose-600">{t("openErr")}</p>}</div>
}
