"use client";
import { useState } from "react";
import { PDFDocument } from "pdf-lib";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {toolUiText} from "@/lib/tool-ui-i18n";
function read(f:File){return new Promise<HTMLImageElement>((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=URL.createObjectURL(f);});}
export default function DocumentCopyLayoutWorkbench(){
 const{lang}=useLingxiLang();const t=(zh:string,en:string)=>toolUiText(lang,zh,en);
 const [front,setFront]=useState<File|null>(null),[back,setBack]=useState<File|null>(null),[purpose,setPurpose]=useState("仅用于本次业务办理"),[busy,setBusy]=useState(false);
 async function run(){if(!front)return;setBusy(true);try{const c=document.createElement("canvas");c.width=1240;c.height=1754;const x=c.getContext("2d")!;x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);const imgs=[await read(front),...(back?[await read(back)]:[])];imgs.forEach((im,i)=>{const maxW=760,maxH=430,scale=Math.min(maxW/im.naturalWidth,maxH/im.naturalHeight);const w=im.naturalWidth*scale,h=im.naturalHeight*scale;x.drawImage(im,(c.width-w)/2,220+i*560,w,h);});x.save();x.translate(c.width/2,c.height/2);x.rotate(-Math.PI/8);x.fillStyle="rgba(185,28,28,.18)";x.font="bold 48px sans-serif";x.textAlign="center";for(let yy=-600;yy<=600;yy+=170)for(let xx=-700;xx<=700;xx+=560)x.fillText(purpose,xx,yy);x.restore();const jpg=await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error(t("导出失败","Export failed"))),"image/jpeg",.94));const pdf=await PDFDocument.create();const img=await pdf.embedJpg(await jpg.arrayBuffer());const p=pdf.addPage([595.28,841.89]);p.drawImage(img,{x:0,y:0,width:595.28,height:841.89});const bytes=await pdf.save();const cp=new Uint8Array(bytes.length);cp.set(bytes);const u=URL.createObjectURL(new Blob([cp.buffer],{type:"application/pdf"}));const a=document.createElement("a");a.href=u;a.download="lingxifield-document-copy.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}finally{setBusy(false);}}
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><input type="file" accept="image/*" className="hidden" onChange={e=>setFront(e.target.files?.[0]||null)}/><b>{t("上传正面","Upload front")}</b><div className="mt-1 text-xs text-slate-500">{front?.name||t("身份证 / 护照 / 银行卡等","ID / passport / bank card, etc.")}</div></label><label className="cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><input type="file" accept="image/*" className="hidden" onChange={e=>setBack(e.target.files?.[0]||null)}/><b>{t("上传反面（可选）","Upload back (optional)")}</b><div className="mt-1 text-xs text-slate-500">{back?.name||t("需要双面时上传","Upload if the document has two sides")}</div></label></div><label className="block text-sm">{t("用途文字","Purpose text")}<input value={purpose} onChange={e=>setPurpose(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><button disabled={!front||busy} onClick={run} className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white disabled:opacity-40">{busy?t("生成中…","Generating…"):t("生成 A4 PDF","Generate A4 PDF")}</button><p className="text-xs leading-5 text-slate-500">{t("当前版本完成 A4 排版与用途水印；自动裁边/透视矫正需在下一步接入真实边缘检测后才会标记为完成。","This version provides A4 layout and a purpose watermark. Auto-cropping and perspective correction will only be marked complete after real edge detection is integrated.")}</p></div>;
}
