"use client";
import {useMemo,useState} from "react";import {PDFDocument} from "pdf-lib";import FileDropzone from "@/components/tools/FileDropzone";import ResultPanel from "@/components/tools/ResultPanel";import {useLingxiLang,type LingxiLang} from "@/lib/lingxi-i18n";import type {ToolResultFile} from "@/lib/tools/types";import {renderDocumentCopyImage,type CopyTone} from "@/lib/tools/document/image-preparation";
type C={front:string;back:string;purpose:string;purposeDefault:string;purposeToggle:string;tone:string;bw:string;gray:string;color:string;run:string;busy:string;ready:string;lead:string;error:string};
const Z:C={front:"上传正面",back:"上传反面（可选）",purpose:"用途文字",purposeDefault:"仅用于本次业务办理",purposeToggle:"添加用途文字",tone:"复印效果",bw:"黑白复印",gray:"灰度复印",color:"原彩",run:"生成 A4 PDF",busy:"正在生成…",ready:"A4 复印件已经生成。",lead:"保持证件比例，不拉伸。默认黑白复印；用途文字默认关闭，需要时再打开。",error:"文档复印件生成没有完成"};
const E:C={front:"Upload front",back:"Upload back (optional)",purpose:"Purpose text",purposeDefault:"For this transaction only",purposeToggle:"Add purpose text",tone:"Copy style",bw:"Black & white",gray:"Grayscale",color:"Original color",run:"Create A4 PDF",busy:"Creating…",ready:"The A4 copy is ready.",lead:"Preserves document aspect ratio without stretching. Black-and-white is the default; purpose text is opt-in.",error:"Document copy creation did not finish"};
const D:Record<LingxiLang,C>={
 zh:Z,en:E,
 ja:{front:"表面をアップロード",back:"裏面をアップロード（任意）",purpose:"用途文字",purposeDefault:"今回の手続きにのみ使用",purposeToggle:"用途文字を追加",tone:"コピー仕上げ",bw:"白黒コピー",gray:"グレースケール",color:"原色",run:"A4 PDF を生成",busy:"生成中…",ready:"A4 コピーを生成しました。",lead:"証明書の縦横比を保ち、引き伸ばしません。初期設定は白黒で、用途文字は必要なときだけ追加します。",error:"文書コピーを生成できませんでした"},
 ko:{front:"앞면 업로드",back:"뒷면 업로드 (선택)",purpose:"용도 문구",purposeDefault:"이번 업무 처리에만 사용",purposeToggle:"용도 문구 추가",tone:"복사 효과",bw:"흑백 복사",gray:"회색조",color:"원본 색상",run:"A4 PDF 생성",busy:"생성 중…",ready:"A4 사본이 완성되었습니다.",lead:"문서 비율을 유지하며 늘이거나 찌그러뜨리지 않습니다. 기본은 흑백이며 용도 문구는 선택 사항입니다.",error:"문서 사본 생성을 완료하지 못했습니다"},
 fr:{front:"Importer le recto",back:"Importer le verso (facultatif)",purpose:"Texte d’usage",purposeDefault:"Uniquement pour cette démarche",purposeToggle:"Ajouter un texte d’usage",tone:"Rendu de copie",bw:"Noir et blanc",gray:"Niveaux de gris",color:"Couleur d’origine",run:"Créer le PDF A4",busy:"Création…",ready:"La copie A4 est prête.",lead:"Conserve les proportions du document sans déformation. Le noir et blanc est sélectionné par défaut ; le texte d’usage est facultatif.",error:"La copie du document n’a pas pu être créée"},
 de:{front:"Vorderseite hochladen",back:"Rückseite hochladen (optional)",purpose:"Verwendungszweck",purposeDefault:"Nur für diesen Vorgang",purposeToggle:"Verwendungszweck hinzufügen",tone:"Kopierstil",bw:"Schwarzweiß",gray:"Graustufen",color:"Originalfarbe",run:"A4-PDF erstellen",busy:"Erstellung…",ready:"Die A4-Kopie ist fertig.",lead:"Das Seitenverhältnis bleibt erhalten, ohne Verzerrung. Schwarzweiß ist voreingestellt; der Verwendungszweck ist optional.",error:"Dokumentkopie konnte nicht erstellt werden"},
 es:{front:"Subir anverso",back:"Subir reverso (opcional)",purpose:"Texto de uso",purposeDefault:"Solo para este trámite",purposeToggle:"Añadir texto de uso",tone:"Estilo de copia",bw:"Blanco y negro",gray:"Escala de grises",color:"Color original",run:"Crear PDF A4",busy:"Creando…",ready:"La copia A4 está lista.",lead:"Conserva la proporción del documento sin deformarlo. Blanco y negro es el modo predeterminado y el texto de uso es opcional.",error:"No se pudo crear la copia"},
 pt:{front:"Enviar frente",back:"Enviar verso (opcional)",purpose:"Texto de finalidade",purposeDefault:"Somente para este procedimento",purposeToggle:"Adicionar texto de finalidade",tone:"Estilo da cópia",bw:"Preto e branco",gray:"Tons de cinza",color:"Cor original",run:"Criar PDF A4",busy:"Criando…",ready:"A cópia A4 está pronta.",lead:"Mantém a proporção do documento sem distorção. Preto e branco é o padrão; o texto de finalidade é opcional.",error:"Não foi possível criar a cópia"},
 ar:{front:"رفع الوجه الأمامي",back:"رفع الوجه الخلفي (اختياري)",purpose:"نص الغرض",purposeDefault:"للاستخدام في هذه المعاملة فقط",purposeToggle:"إضافة نص الغرض",tone:"شكل النسخة",bw:"أبيض وأسود",gray:"تدرج رمادي",color:"الألوان الأصلية",run:"إنشاء PDF بحجم A4",busy:"جارٍ الإنشاء…",ready:"نسخة A4 جاهزة.",lead:"يحافظ على نسبة أبعاد المستند من دون تمديد أو تشويه. الوضع الافتراضي أبيض وأسود، ونص الغرض اختياري.",error:"تعذر إنشاء نسخة المستند"}
};
export default function DocumentCopyLayoutWorkbench(){const{lang}=useLingxiLang();const c=D[lang]??E;const[front,setFront]=useState<File[]>([]),[back,setBack]=useState<File[]>([]),[purpose,setPurpose]=useState(c.purposeDefault),[withPurpose,setWithPurpose]=useState(false),[tone,setTone]=useState<CopyTone>("bw"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<ToolResultFile[]>([]);const frontFile=front[0]||null,backFile=back[0]||null;
 async function run(){if(!frontFile)return;setBusy(true);setError("");setResult([]);try{const canvas=document.createElement("canvas");canvas.width=1240;canvas.height=1754;const ctx=canvas.getContext("2d")!;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);const imgs=[await renderDocumentCopyImage(frontFile,tone),...(backFile?[await renderDocumentCopyImage(backFile,tone)]:[])];imgs.forEach((im,i)=>{const maxW=780,maxH=455,scale=Math.min(maxW/im.width,maxH/im.height),w=im.width*scale,h=im.height*scale;ctx.drawImage(im,(canvas.width-w)/2,210+i*570,w,h)});if(withPurpose&&purpose.trim()){ctx.save();ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(-Math.PI/8);ctx.fillStyle="rgba(185,28,28,.18)";ctx.font="bold 48px sans-serif";ctx.textAlign="center";for(let yy=-600;yy<=600;yy+=170)for(let xx=-700;xx<=700;xx+=560)ctx.fillText(purpose.trim(),xx,yy);ctx.restore()}const jpg=await new Promise<Blob>((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("EXPORT_FAILED")),"image/jpeg",.94));const pdf=await PDFDocument.create(),img=await pdf.embedJpg(await jpg.arrayBuffer()),page=pdf.addPage([595.28,841.89]);page.drawImage(img,{x:0,y:0,width:595.28,height:841.89});const bytes=await pdf.save(),copy=new Uint8Array(bytes.length);copy.set(bytes);const blob=new Blob([copy.buffer],{type:"application/pdf"});setResult([{name:"lingxifield-document-copy.pdf",blob,mime:"application/pdf",size:blob.size}]);canvas.width=1;canvas.height=1}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const details=useMemo(()=>({sides:backFile?2:1,tone,purpose:withPurpose}),[backFile,tone,withPurpose]);return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div><p className="mb-2 text-sm">{c.front}</p><FileDropzone accept="image/*" files={front} onChange={f=>{setFront(f);setResult([])}} disabled={busy} kind="image" maxSizeMB={30}/></div><div><p className="mb-2 text-sm">{c.back}</p><FileDropzone accept="image/*" files={back} onChange={f=>{setBack(f);setResult([])}} disabled={busy} kind="image" maxSizeMB={30}/></div></div><fieldset className="rounded-xl border p-4"><legend className="px-2 text-sm">{c.tone}</legend><div className="flex flex-wrap gap-4">{([["bw",c.bw],["gray",c.gray],["color",c.color]] as const).map(([v,l])=><label key={v} className="flex items-center gap-2"><input type="radio" data-testid={`document-copy-tone-${v}`} checked={tone===v} onChange={()=>setTone(v)}/>{l}</label>)}</div></fieldset><label className="flex items-center gap-2 text-sm"><input type="checkbox" data-testid="document-copy-purpose-toggle" checked={withPurpose} onChange={e=>setWithPurpose(e.target.checked)}/>{c.purposeToggle}</label>{withPurpose&&<label className="block text-sm">{c.purpose}<input value={purpose} onChange={e=>setPurpose(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2.5"/></label>}<button disabled={!frontFile||busy} onClick={run} className="rounded-xl bg-[var(--lx-ink)] px-5 py-2.5 text-sm text-[var(--lx-bg)] disabled:opacity-40">{busy?c.busy:c.run}</button><p className="text-xs text-[var(--lx-muted)]">{c.lead}</p>{!!result.length&&<ResultPanel files={result} messageZh={c.ready} messageEn={c.ready} details={details}/>} {error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{c.error} · {error}</p>}</div>}
