"use client";
import {useState} from "react";
import FileDropzone from "@/components/tools/FileDropzone";
import PaidActionButton from "@/components/tools/PaidActionButton";
type FoodResult={items?:Array<any>;totals?:{caloriesMin?:number;caloriesMax?:number;proteinG?:number;carbsG?:number;fatG?:number};uncertainty?:string[];note?:string;raw?:string};
export default function FoodCalorieWorkbench(){
 const[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[results,setResults]=useState<Array<{name:string;data:FoodResult}>>([]);
 async function analyze(quoteId:string){setBusy(true);setError("");setResults([]);try{const out=[] as Array<{name:string;data:FoodResult}>;for(let i=0;i<files.length;i++){const form=new FormData();form.set("file",files[i]);form.set("quote_id",quoteId);form.set("item_key",`meal-${i}`);const res=await fetch("/api/ai/food-analyze",{method:"POST",body:form});const data=await res.json();if(!res.ok)throw new Error(data.error==="OPENAI_NOT_CONFIGURED"?"AI 视觉服务尚未配置。":(data.error||"分析失败"));out.push({name:files[i].name,data})}setResults(out)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="space-y-4"><FileDropzone accept="image/*" multiple maxFiles={10} maxSizeMB={10} files={files} onChange={setFiles} disabled={busy}/><p className="text-sm leading-6 text-slate-500">可一次上传多餐照片。每张照片独立计费、独立分析；付款确认前不会发送给 AI。</p>{busy?<button disabled className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white opacity-50">正在分析 {files.length} 张照片…</button>:files.length?<PaidActionButton toolId="food-calorie" quantity={files.length} metadata={{images:files.length}} onPaid={analyze} label="查看本次分析价格"/>:null}{error&&<p className="text-sm text-rose-600">{error}</p>}{results.map((r,idx)=><div key={r.name+idx} className="rounded-2xl border border-slate-200 p-5"><div className="text-sm font-medium text-slate-800">{r.name}</div>{r.data.totals&&<div className="mt-3 rounded-2xl bg-blue-50 p-4"><div className="text-sm text-blue-700">这餐大约</div><div className="mt-1 text-3xl font-semibold text-blue-900">{r.data.totals.caloriesMin??"?"}–{r.data.totals.caloriesMax??"?"} kcal</div><div className="mt-2 text-sm text-blue-900/80">蛋白质 {r.data.totals.proteinG??"?"}g · 碳水 {r.data.totals.carbsG??"?"}g · 脂肪 {r.data.totals.fatG??"?"}g</div></div>}{r.data.items?.map((x:any,i:number)=><div key={i} className="mt-2 rounded-xl bg-slate-50 p-3 text-sm"><b>{x.name||`食物 ${i+1}`}</b> · {x.caloriesMin??"?"}–{x.caloriesMax??"?"} kcal</div>)}</div>)}</div>
}
