"use client";
import {useEffect,useMemo,useState} from "react";
import PaidActionButton from "@/components/tools/PaidActionButton";
import {useLingxiLang,type LingxiLang} from "@/lib/lingxi-i18n";
import {recognizeFoodImage,type FoodVisionPrediction} from "@/lib/tools/food/image-recognition-local";
import {foodLabel} from "@/lib/tools/food/vision-labels";
import {canonicalQuery} from "@/lib/tools/food/canonical";
type SearchItem={food_id:number;name_zh:string;name_en?:string|null;category?:string|null};
type Selected={food:SearchItem;grams:number};
type Result={items:any[];total:any;sources?:string[]};
const C:any={
 zh:{upload:"上传图片",batch:"批量上传图片",custom:"自定义名称",drop:"选择或拖入食物图片",drop2:"支持常见图片格式 · 图片只用于本次识别",checking:"正在识别…",found:"识别到的内容",confirm:"确认食物",name:"输入食物名称",search:"搜索",portion:"份量",ready:"已确认",view:"查看分析结果",free:"今日首次识别免费",used:"确认后即可查看完整结果",pay:"查看分析结果",result:"识别结果",nutrition:"营养成分",source:"数据来源",retry:"识别不准确？可搜索并替换食物名称",empty:"没有找到合适结果，请换个名称试试。",batchTitle:"一次选择多张图片",batchLead:"每张图片单独识别，确认后统一查看结果。"},
 en:{upload:"Upload image",batch:"Upload multiple images",custom:"Custom name",drop:"Choose or drop a food image",drop2:"Common image formats supported",checking:"Recognizing…",found:"Detected",confirm:"Confirm food",name:"Enter food name",search:"Search",portion:"Portion",ready:"Confirmed",view:"View analysis",free:"Your first scan today is free",used:"Confirm the food to continue",pay:"View analysis",result:"Result",nutrition:"Nutrition",source:"Sources",retry:"Not right? Search and replace the food name.",empty:"No close match. Try another name.",batchTitle:"Choose multiple images",batchLead:"Each image is recognized separately, then reviewed together."}
};const t=(l:LingxiLang,k:string)=>(C[l]||C.en)[k]||C.en[k]||k;
const name=(x:SearchItem,l:LingxiLang)=>l==="zh"?x.name_zh:(x.name_en||x.name_zh);
async function search(q:string){const r=await fetch(`/api/tools/food/search?q=${encodeURIComponent(canonicalQuery(q))}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));return r.ok&&Array.isArray(d.items)?d.items as SearchItem[]:[]}
function N({v,u}:{v:any,u:string}){return <div className="rounded-2xl bg-[var(--lx-soft)] p-4"><b className="text-xl">{v==null?"—":Number(v).toFixed(u==="kcal"?0:1)}</b><span className="ml-1 text-xs text-[var(--lx-muted)]">{u}</span></div>}
export default function FoodCalorieWorkbench(){
 const{lang}=useLingxiLang();const[mode,setMode]=useState<"single"|"batch"|"custom">("single"),[files,setFiles]=useState<File[]>([]);
 return <div className="overflow-hidden rounded-[28px] bg-[var(--lx-panel)]" data-food-version="v15">
  <section className="relative overflow-hidden rounded-[28px] border border-[var(--lx-line)] bg-[var(--lx-soft)] p-6 sm:p-8">
   <div className="absolute -right-10 -top-12 h-44 w-44 rounded-full border-[26px] border-current opacity-[.035]"/><div className="absolute right-16 top-12 h-20 w-20 rounded-full border-[16px] border-current opacity-[.04]"/>
   <div className="relative max-w-xl"><span className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--lx-ink)] text-2xl text-[var(--lx-bg)]">◉</span><h2 className="mt-5 text-2xl font-semibold sm:text-3xl">{lang==="zh"?"卡路里识别":"Calorie Scan"}</h2><p className="mt-2 text-sm leading-6 text-[var(--lx-muted)]">{lang==="zh"?"上传食物图片，确认识别内容后查看热量与营养成分。":"Upload a food image, confirm what was detected, then view calories and nutrition."}</p></div>
  </section>
  <nav className="mt-4 grid grid-cols-3 gap-2">{[["single","upload"],["batch","batch"],["custom","custom"]].map(([m,k])=><button key={m} onClick={()=>{setMode(m as any);setFiles([])}} className={`rounded-2xl px-3 py-3 text-sm font-medium transition ${mode===m?"bg-[var(--lx-ink)] text-[var(--lx-bg)]":"border border-[var(--lx-line)] hover:bg-[var(--lx-soft)]"}`}>{t(lang,k)}</button>)}</nav>
  <div className="mt-4">{mode==="custom"?<FoodConfirm lang={lang} initial=""/>:<Uploader lang={lang} multiple={mode==="batch"} files={files} setFiles={setFiles}/>}</div>
 </div>
}
function Uploader({lang,multiple,files,setFiles}:{lang:LingxiLang;multiple:boolean;files:File[];setFiles:(x:File[])=>void}){
 return <section className="rounded-[28px] border border-dashed border-[var(--lx-line)] p-5 sm:p-7">
  <label className="flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-2xl bg-[var(--lx-soft)] p-6 text-center"><span className="text-4xl">＋</span><b className="mt-3">{multiple?t(lang,"batchTitle"):t(lang,"drop")}</b><span className="mt-2 text-xs text-[var(--lx-muted)]">{multiple?t(lang,"batchLead"):t(lang,"drop2")}</span><input className="hidden" type="file" accept="image/*" multiple={multiple} onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,multiple?20:1))}/></label>
  {files.length>0&&(multiple?<Batch lang={lang} files={files}/>:<Single lang={lang} file={files[0]}/>)}
 </section>
}
function Single({lang,file}:{lang:LingxiLang;file:File}){
 const[preview,setPreview]=useState(""),[preds,setPreds]=useState<FoodVisionPrediction[]>([]),[busy,setBusy]=useState(true),[pick,setPick]=useState("");
 useEffect(()=>{const u=URL.createObjectURL(file);setPreview(u);setBusy(true);setPick("");void recognizeFoodImage(file).then(x=>{const a=x.filter(v=>v.score>=.12).slice(0,5);setPreds(a);if(a[0])setPick(a[0].label)}).finally(()=>setBusy(false));return()=>URL.revokeObjectURL(u)},[file]);
 return <div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="overflow-hidden rounded-2xl bg-[var(--lx-soft)]"><img src={preview} alt="" className="aspect-square h-full w-full object-cover"/></div><div className="rounded-2xl border border-[var(--lx-line)] p-5">{busy?<p>{t(lang,"checking")}</p>:<><b>{t(lang,"found")}</b><div className="mt-3 flex flex-wrap gap-2">{preds.map(p=><button key={p.label} onClick={()=>setPick(p.label)} className={`rounded-full px-3 py-2 text-sm ${pick===p.label?"bg-[var(--lx-ink)] text-[var(--lx-bg)]":"bg-[var(--lx-soft)]"}`}>{foodLabel(p.label,lang)}</button>)}</div><p className="mt-4 text-xs text-[var(--lx-muted)]">{t(lang,"retry")}</p><FoodConfirm lang={lang} initial={pick}/></>}</div></div>
}
function FoodConfirm({lang,initial}:{lang:LingxiLang;initial:string}){
 const[q,setQ]=useState(initial),[grams,setGrams]=useState(100),[hits,setHits]=useState<SearchItem[]>([]),[selected,setSelected]=useState<Selected[]>([]),[result,setResult]=useState<Result|null>(null),[free,setFree]=useState<boolean|null>(null),[msg,setMsg]=useState("");
 useEffect(()=>{setQ(initial);if(initial)void doSearch(initial)},[initial]);
 useEffect(()=>{void fetch("/api/tools/food/free-status",{cache:"no-store"}).then(r=>r.json()).then(d=>setFree(Boolean(d.available))).catch(()=>setFree(false))},[]);
 async function doSearch(v=q){if(!v.trim())return;const x=await search(v);setHits(x);setMsg(x.length?"":t(lang,"empty"))}
 function add(x:SearchItem){setSelected([{food:x,grams}]);setHits([]);setQ(name(x,lang));setResult(null)}
 async function freeCalc(){setMsg("");const r=await fetch("/api/tools/food/free-calculate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({items:selected.map(x=>({food_id:x.food.food_id,grams:x.grams}))})});const d=await r.json().catch(()=>({}));if(r.ok){setResult(d);setFree(false)}else if(d.freeUsed){setFree(false);setMsg(lang==="zh"?"今日免费识别已使用，请继续完成本次分析。":"Today's free scan has been used.")}else setMsg(String(d.error||""))}
 async function paid(id:string){const r=await fetch("/api/tools/food/calculate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({quoteId:id,photoCount:1,items:selected.map(x=>({food_id:x.food.food_id,grams:x.grams}))})});const d=await r.json().catch(()=>({}));if(r.ok)setResult(d);else setMsg(lang==="zh"?"这次没有算完，请再试一次。":"Please try again.")}
 return <div className="mt-4">
  <div className="grid gap-2 sm:grid-cols-[1fr_110px_auto]"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void doSearch()} placeholder={t(lang,"name")} className="rounded-xl border border-[var(--lx-line)] bg-[var(--lx-bg)] px-4 py-3"/><input type="number" min={1} max={10000} value={grams} onChange={e=>setGrams(Math.max(1,Number(e.target.value)||1))} aria-label={t(lang,"portion")} className="rounded-xl border border-[var(--lx-line)] bg-[var(--lx-bg)] px-3 py-3"/><button onClick={()=>void doSearch()} className="rounded-xl border border-[var(--lx-line)] px-4 py-3">{t(lang,"search")}</button></div>
  {hits.length>0&&<div className="mt-2 max-h-64 overflow-auto rounded-xl border border-[var(--lx-line)]">{hits.slice(0,10).map(x=><button key={x.food_id} onClick={()=>add(x)} className="flex w-full items-center justify-between border-b border-[var(--lx-line)] px-4 py-3 text-left last:border-0"><span>{name(x,lang)}</span><span>＋</span></button>)}</div>}
  {selected.length>0&&!result&&<div className="mt-4 rounded-2xl bg-[var(--lx-soft)] p-4"><div className="flex justify-between"><b>{name(selected[0].food,lang)}</b><span>{selected[0].grams} g</span></div><div className="mt-4">{free===true?<button onClick={()=>void freeCalc()} className="rounded-xl bg-[var(--lx-ink)] px-5 py-3 text-sm font-medium text-[var(--lx-bg)]">{t(lang,"view")} · {t(lang,"free")}</button>:free===false?<PaidActionButton toolId="food-calorie" quantity={1} metadata={{mode:"photo"}} onPaid={paid} label={t(lang,"pay")}/>:<span className="text-sm text-[var(--lx-muted)]">…</span>}</div></div>}
  {msg&&<p className="mt-3 text-sm text-[var(--lx-muted)]">{msg}</p>}{result&&<ResultCard lang={lang} result={result}/>}
 </div>
}
function Batch({lang,files}:{lang:LingxiLang;files:File[]}){
 const[rows,setRows]=useState<Array<{file:File;preview:string;label:string;food?:SearchItem}>>([]),[busy,setBusy]=useState(true),[result,setResult]=useState<Result|null>(null),[msg,setMsg]=useState("");
 useEffect(()=>{let live=true;const urls=files.map(f=>URL.createObjectURL(f));setBusy(true);void Promise.all(files.map(async(file,i)=>{const p=(await recognizeFoodImage(file)).filter(x=>x.score>=.12)[0];const label=p?.label||"";const hits=label?await search(label):[];return{file,preview:urls[i],label,food:hits[0]}})).then(x=>live&&setRows(x)).finally(()=>live&&setBusy(false));return()=>{live=false;urls.forEach(URL.revokeObjectURL)}},[files]);
 const ready=rows.length===files.length&&rows.every(x=>x.food);
 async function paid(id:string){const r=await fetch("/api/tools/food/calculate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({quoteId:id,photoCount:files.length,items:rows.filter(x=>x.food).map(x=>({food_id:x.food!.food_id,grams:100}))})});const d=await r.json().catch(()=>({}));if(r.ok)setResult(d);else setMsg(lang==="zh"?"这次没有算完，请再试一次。":"Please try again.")}
 return <div className="mt-5">{busy?<p>{t(lang,"checking")}</p>:<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map((x,i)=><article key={i} className="overflow-hidden rounded-2xl border border-[var(--lx-line)]"><img src={x.preview} alt="" className="aspect-video w-full object-cover"/><div className="p-3 text-sm">{x.food?name(x.food,lang):(lang==="zh"?"请使用自定义名称确认":"Please confirm manually")}</div></article>)}</div>{ready&&!result&&<div className="mt-5"><PaidActionButton toolId="food-calorie" quantity={files.length} metadata={{mode:"batch"}} onPaid={paid} label={t(lang,"view")}/></div>}{!ready&&<p className="mt-4 text-sm text-[var(--lx-muted)]">{lang==="zh"?"有图片暂时无法可靠确认，请分开上传或使用自定义名称。":"Some images need manual confirmation."}</p>}</>}{msg&&<p className="mt-3 text-sm">{msg}</p>}{result&&<ResultCard lang={lang} result={result}/>}</div>
}
function ResultCard({lang,result}:{lang:LingxiLang;result:Result}){const x=result.total||{};return <section className="mt-5 rounded-[28px] border border-[var(--lx-line)] p-5 sm:p-6"><span className="text-sm text-[var(--lx-muted)]">{t(lang,"result")}</span><div className="mt-2 text-4xl font-semibold">{x.kcal==null?"—":Number(x.kcal).toFixed(0)} <small className="text-base font-normal">kcal</small></div><h3 className="mt-6 font-semibold">{t(lang,"nutrition")}</h3><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3"><N v={x.protein_g} u="g"/><N v={x.carbs_g} u="g"/><N v={x.fat_g} u="g"/><N v={x.fiber_g} u="g"/><N v={x.sugar_g} u="g"/><N v={x.sodium_mg} u="mg"/></div><details className="mt-5 rounded-2xl bg-[var(--lx-soft)] p-4"><summary className="cursor-pointer text-sm font-medium">{t(lang,"source")}</summary><p className="mt-2 text-xs text-[var(--lx-muted)]">{(result.sources||["USDA FoodData Central"]).join(" · ")}</p></details></section>}
