"use client";
import{useEffect,useState}from"react";import FileDropzone from"@/components/tools/FileDropzone";import{saveBlob}from"@/lib/tools/autonomous/download-local";import{ID_PHOTO_PRESETS,presetById}from"@/lib/tools/id-photo/presets";import{processIdPhoto}from"@/lib/tools/id-photo/browser-processor";
type R={url:string;blob:Blob;width:number;height:number;faceDetected:boolean;mattingApplied:boolean;quality:string};
export default function IdPhotoAiWorkbench(){const[files,setFiles]=useState<File[]>([]),[preset,setPreset]=useState("cn-1inch"),[background,setBackground]=useState("white"),[zoom,setZoom]=useState(1.15),[x,setX]=useState(0),[y,setY]=useState(0),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[result,setResult]=useState<R|null>(null),[error,setError]=useState("");
useEffect(()=>()=>{if(result)URL.revokeObjectURL(result.url)},[result]);
async function run(){if(!files[0])return;setBusy(true);setError("");setProgress("正在识别人像并处理发丝边缘…");try{if(result)URL.revokeObjectURL(result.url);const r=await processIdPhoto(files[0],{background,preset:presetById(preset),zoom,offsetX:x,offsetY:y,matting:true});setResult({...r,url:URL.createObjectURL(r.blob)});setProgress("")}catch(e:any){setProgress("");setError(e?.message?.includes("model")?"人像处理模型没有加载成功，请刷新后重试。":`处理没有完成：${e?.message||"请换一张照片再试"}`)}finally{setBusy(false)}}
return <div className="space-y-5"><FileDropzone accept="image/*" multiple={false} maxFiles={1} maxSizeMB={15} files={files} onChange={z=>{setFiles(z.slice(0,1));setResult(null)}} disabled={busy} kind="image"/>
<div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-sm">尺寸<select value={preset} onChange={e=>setPreset(e.target.value)} className="w-full rounded-xl border border-[var(--lx-line)] bg-transparent p-3">{ID_PHOTO_PRESETS.map(z=><option key={z.id} value={z.id}>{z.label}</option>)}</select></label><label className="space-y-1 text-sm">人物大小<input type="range" min=".85" max="1.8" step=".03" value={zoom} onChange={e=>setZoom(Number(e.target.value))} className="w-full"/></label><label className="space-y-1 text-sm">左右位置<input type="range" min="-1" max="1" step=".02" value={x} onChange={e=>setX(Number(e.target.value))} className="w-full"/></label><label className="space-y-1 text-sm">上下位置<input type="range" min="-1" max="1" step=".02" value={y} onChange={e=>setY(Number(e.target.value))} className="w-full"/></label></div>
<div className="flex flex-wrap gap-2">{[["white","白底"],["blue","蓝底"],["red","红底"],["gray","灰底"]].map(([v,n])=><button type="button" key={v} onClick={()=>setBackground(v)} className={`rounded-full px-4 py-2 text-sm ${background===v?"bg-[var(--lx-ink)] text-[var(--lx-bg)]":"border border-[var(--lx-line)]"}`}>{n}</button>)}</div>
{files[0]&&<button type="button" onClick={run} disabled={busy} className="rounded-xl bg-[var(--lx-ink)] px-5 py-2.5 text-sm font-medium text-[var(--lx-bg)]">{busy?"正在制作…":"生成人像证件照"}</button>}
{progress&&<p className="text-sm text-[var(--lx-faint)]">{progress} 首次使用需要加载本地人像模型，之后浏览器会缓存。</p>}{error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{error}</p>}
{result&&<div className="rounded-2xl border border-[var(--lx-line)] p-4"><img src={result.url} alt="证件照结果" className="mx-auto max-h-[560px] rounded-xl"/><div className="mt-3 text-sm">输出 {result.width} × {result.height}px · {result.mattingApplied?"已进行人像抠图与背景合成":"未完成人像抠图"} · {result.faceDetected?"已辅助定位":"可用位置滑杆微调"}</div><div className="mt-3 flex gap-2"><button onClick={()=>saveBlob(result.blob,"lingxifield-id-photo.png")} className="rounded-xl bg-[var(--lx-ink)] px-4 py-2 text-sm text-[var(--lx-bg)]">保存 PNG</button><button onClick={()=>setResult(null)} className="rounded-xl border border-[var(--lx-line)] px-4 py-2 text-sm">重新调整</button></div></div>}
<p className="text-xs leading-5 text-[var(--lx-faint)]">照片在浏览器本地处理。工具负责抠图、背景与尺寸构图，不改变五官身份特征；正式证件提交前请以目标机构最新要求为准。</p></div>}
