"use client";
import { useEffect,useState } from "react";
import PaidActionButton from "@/components/tools/PaidActionButton";
export default function IdPhotoAiWorkbench(){
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[bg,setBg]=useState("white"),[busy,setBusy]=useState(false),[result,setResult]=useState(""),[error,setError]=useState("");
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 async function run(q:string){if(!file)return;setBusy(true);setError("");try{const fd=new FormData();fd.set("file",file);fd.set("quote_id",q);fd.set("item_key","id-photo-0");fd.set("background",bg);const r=await fetch("/api/ai/id-photo",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"ID photo failed");setResult(d.b64?`data:image/png;base64,${d.b64}`:d.url||"")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="space-y-4"><label className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(preview)URL.revokeObjectURL(preview);setPreview(f?URL.createObjectURL(f):"");setResult("")}}/><b>上传人像</b><p className="mt-1 text-sm text-slate-500">AI 更换背景和证件照构图，尽量保持人物身份与五官不变。</p></label>{preview&&<img src={preview} alt="" className="mx-auto max-h-[420px] rounded-2xl"/>}<div className="flex flex-wrap gap-2">{[["white","白底"],["light blue","蓝底"],["red","红底"],["light gray","灰底"]].map(([v,n])=><button key={v} onClick={()=>setBg(v)} className={`rounded-full px-4 py-2 text-sm ${bg===v?"bg-blue-600 text-white":"border"}`}>{n}</button>)}</div>{busy?<button disabled className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white opacity-50">正在生成…</button>:file?<PaidActionButton toolId="id-photo-ai" quantity={1} onPaid={run} label="查看证件照价格"/>:null}<div className="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900">AI 生成结果不等于官方证件照合规认证。提交护照、签证、考试报名等前仍需核对尺寸、头部比例和主管机构规则。</div>{result&&<div><img src={result} alt="AI ID photo" className="mx-auto max-h-[520px] rounded-2xl"/><a href={result} download="lingxifield-id-photo.png" className="mt-3 inline-flex rounded-full bg-emerald-600 px-5 py-2.5 text-sm text-white">下载</a></div>}{error&&<p className="text-sm text-rose-600">{error}</p>}</div>
}
