"use client";
import{useEffect,useState}from"react";import FileDropzone from"@/components/tools/FileDropzone";import PaidExportButton from"@/components/tools/PaidExportButton";import{saveBlob}from"@/lib/tools/autonomous/download-local";import{ID_PHOTO_PRESETS,presetById}from"@/lib/tools/id-photo/presets";import{processIdPhoto}from"@/lib/tools/id-photo/browser-processor";import{deletePaidTaskDraft,loadPaidTaskDraft,newPaidTaskDraftId,savePaidTaskDraft}from"@/lib/tools/workspace/paid-task-draft";
import {deliveryText} from "@/lib/tools/commerce/delivery-copy";
import {useLingxiLang} from "@/lib/lingxi-i18n";
type R={url:string;hdUrl:string;blob:Blob;hdBlob:Blob;width:number;height:number;hdWidth:number;hdHeight:number;faceDetected:boolean;mattingApplied:boolean;quality:string;warnings:string[];rotation:number};
export default function IdPhotoAiWorkbench(){
 const {lang}=useLingxiLang();const [delivered,setDelivered]=useState<Blob|null>(null);
 const[files,setFiles]=useState<File[]>([]),[preset,setPreset]=useState("cn-1inch"),[background,setBackground]=useState("white"),[zoom,setZoom]=useState(1.15),[x,setX]=useState(0),[y,setY]=useState(0),[busy,setBusy]=useState(false),[result,setResult]=useState<R|null>(null),[error,setError]=useState(""),[draftId,setDraftId]=useState("");
 useEffect(()=>()=>{if(result){URL.revokeObjectURL(result.url);URL.revokeObjectURL(result.hdUrl)}},[result]);
 async function build(file:File,opts={preset,background,zoom,x,y}){const r=await processIdPhoto(file,{background:opts.background,preset:presetById(opts.preset),zoom:opts.zoom,offsetX:opts.x,offsetY:opts.y,matting:true});setResult({...r,url:URL.createObjectURL(r.blob),hdUrl:URL.createObjectURL(r.hdBlob)});return r}
 async function run(){if(!files[0])return;setBusy(true);setError("");try{if(result){URL.revokeObjectURL(result.url);URL.revokeObjectURL(result.hdUrl)}const id=draftId||newPaidTaskDraftId();setDraftId(id);const r=await build(files[0]);await savePaidTaskDraft({id,toolId:"id-photo-ai",file:files[0],fileName:files[0].name,fileType:files[0].type,state:{preset,background,zoom,x,y}})}catch(e:any){const c=String(e?.message||"");setError(c.includes("PHOTO_TOO_SMALL")?"照片分辨率太低，建议换一张更清晰的原图。":c.includes("FACE_ANGLE_TOO_LARGE")?"头部倾斜较大，建议换一张面向镜头、头部更端正的照片。":"这张照片暂时没有处理完成，请换一张清晰的正面照片再试。")}finally{setBusy(false)}}
 useEffect(()=>{const id=new URLSearchParams(location.search).get("resumeDraft")||"";if(!id)return;void(async()=>{const d=await loadPaidTaskDraft<any>(id);if(!d?.file)return;const file=new File([d.file],d.fileName||"photo",{type:d.fileType||"image/png"}),st=d.state||{};setDraftId(id);setFiles([file]);setPreset(st.preset||"cn-1inch");setBackground(st.background||"white");setZoom(Number(st.zoom||1.15));setX(Number(st.x||0));setY(Number(st.y||0));setBusy(true);try{await build(file,{preset:st.preset||"cn-1inch",background:st.background||"white",zoom:Number(st.zoom||1.15),x:Number(st.x||0),y:Number(st.y||0)})}finally{setBusy(false)}})()},[]);
 async function paidSave(){if(!result)throw new Error("PHOTO_RESULT_MISSING");setDelivered(result.hdBlob);await saveBlob(result.hdBlob,"lingxifield-id-photo-hd.png")} async function finishPaidSave(){const old=draftId;if(result){URL.revokeObjectURL(result.url);URL.revokeObjectURL(result.hdUrl)}setFiles([]);setResult(null);setDraftId("");if(old)await deletePaidTaskDraft(old)}
 return <div className="space-y-5">{delivered&&<section role="status" className="rounded-2xl border p-4 space-y-3"><p>{deliveryText(lang,"ready")}</p><button className="rounded-xl border px-4 py-3" onClick={()=>void saveBlob(delivered,"lingxifield-id-photo-hd.png").catch(()=>setError(deliveryText(lang,"failed")))}>{deliveryText(lang,"download")}</button><button className="rounded-xl border px-4 py-3" onClick={()=>setDelivered(null)}>{deliveryText(lang,"fresh")}</button></section>}<div className="rounded-2xl bg-[var(--lx-soft)] px-4 py-3 text-sm leading-6 text-[var(--lx-muted)]">生成、换底色、尺寸和位置调整可以先免费预览；确认满意后再导出高清照片。</div>
  <FileDropzone accept="image/*" multiple={false} maxFiles={1} maxSizeMB={15} files={files} onChange={z=>{setFiles(z.slice(0,1));setResult(null);setDraftId("")}} disabled={busy} kind="image"/>
  <div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1 text-sm">尺寸<select value={preset} onChange={e=>setPreset(e.target.value)} className="w-full rounded-xl border border-[var(--lx-line)] bg-transparent p-3">{ID_PHOTO_PRESETS.map(z=><option key={z.id} value={z.id}>{z.label}</option>)}</select></label><label className="space-y-1 text-sm">人物大小<input type="range" min=".85" max="1.8" step=".03" value={zoom} onChange={e=>setZoom(Number(e.target.value))} className="w-full"/></label><label className="space-y-1 text-sm">左右位置<input type="range" min="-1" max="1" step=".02" value={x} onChange={e=>setX(Number(e.target.value))} className="w-full"/></label><label className="space-y-1 text-sm">上下位置<input type="range" min="-1" max="1" step=".02" value={y} onChange={e=>setY(Number(e.target.value))} className="w-full"/></label></div>
  <div className="flex flex-wrap gap-2">{[["white","白底"],["blue","蓝底"],["red","红底"],["gray","灰底"]].map(([v,n])=><button type="button" key={v} onClick={()=>setBackground(v)} className={`rounded-full px-4 py-2 text-sm ${background===v?"bg-[var(--lx-ink)] text-[var(--lx-bg)]":"border border-[var(--lx-line)]"}`}>{n}</button>)}</div>
  {files[0]&&<button type="button" onClick={run} disabled={busy} className="rounded-xl border border-[var(--lx-line)] px-5 py-2.5 text-sm font-medium">{busy?"正在整理照片…":"免费生成预览"}</button>}
  {error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{error}</p>}
  {result&&<div className="rounded-2xl border border-[var(--lx-line)] p-4"><img src={result.url} alt="证件照结果" className="mx-auto max-h-[560px] rounded-xl"/><div className="mt-3"><b className="text-sm">证件照预览已生成</b><p className="mt-1 text-sm text-[var(--lx-muted)]">需要的话继续调整；付款后会自动恢复当前编辑，不需要重新制作。</p></div><div className="mt-3"><PaidExportButton toolId="id-photo-ai" quantity={1} draftId={draftId} metadata={{kind:"id-photo-hd"}} onUnlocked={paidSave} onCompleted={finishPaidSave} label="确认价格并保存高清照片"/></div></div>}
  <p className="text-xs leading-5 text-[var(--lx-faint)]">照片在浏览器中处理。正式提交前，请确认尺寸与照片要求符合目标机构的最新规定。</p></div>
}
