"use client";
import { useState } from "react";
import { PDFDocument, degrees } from "pdf-lib";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {toolUiText} from "@/lib/tool-ui-i18n";
function blob(bytes:Uint8Array){const c=new Uint8Array(bytes.length);c.set(bytes);return new Blob([c.buffer],{type:"application/pdf"});}
function dl(b:Blob,n:string){const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);}
function parsePages(v:string,max:number){const set=new Set<number>();for(const part of v.split(",")){const p=part.trim();if(!p)continue;if(p.includes("-")){const [a,b]=p.split("-").map(Number);for(let i=Math.max(1,a);i<=Math.min(max,b);i++)set.add(i-1);}else{const n=Number(p);if(n>=1&&n<=max)set.add(n-1);}}return [...set].sort((a,b)=>a-b);}
export default function PdfBasicWorkbench(){
 const{lang}=useLingxiLang();const t=(zh:string,en:string)=>toolUiText(lang,zh,en);
 const [files,setFiles]=useState<File[]>([]);const [pages,setPages]=useState(0);const [range,setRange]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function loadFirst(f:File){const d=await PDFDocument.load(await f.arrayBuffer());setPages(d.getPageCount());}
 async function merge(){setBusy(true);setError("");try{const out=await PDFDocument.create();for(const f of files){const s=await PDFDocument.load(await f.arrayBuffer());for(const p of await out.copyPages(s,s.getPageIndices()))out.addPage(p);}dl(blob(await out.save()),"lingxifield-merged.pdf");}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function extract(){if(!files[0])return;setBusy(true);setError("");try{const s=await PDFDocument.load(await files[0].arrayBuffer());const ids=parsePages(range,s.getPageCount());if(!ids.length)throw new Error(t("请输入要导出的页码，如 1-3,5","Enter pages to export, e.g. 1-3,5"));const out=await PDFDocument.create();for(const p of await out.copyPages(s,ids))out.addPage(p);dl(blob(await out.save()),"lingxifield-pages.pdf");}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function rotate(){if(!files[0])return;setBusy(true);try{const d=await PDFDocument.load(await files[0].arrayBuffer());const ids=parsePages(range||`1-${d.getPageCount()}`,d.getPageCount());for(const i of ids){const p=d.getPage(i);p.setRotation(degrees((p.getRotation().angle+90)%360));}dl(blob(await d.save()),"lingxifield-rotated.pdf");}finally{setBusy(false);}}
 return <div className="space-y-5"><label className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><input type="file" accept="application/pdf" multiple className="hidden" onChange={async e=>{const a=[...(e.target.files||[])];setFiles(a);if(a[0])await loadFirst(a[0]);}}/><b>{t("选择一个或多个 PDF","Choose one or more PDFs")}</b><p className="mt-1 text-sm text-slate-500">{t("合并可多选；拆分、提取、旋转使用第一个文件。","Select multiple files to merge; split, extract and rotate use the first file.")}</p></label>{files.length>0&&<div className="rounded-2xl bg-slate-50 p-3 text-sm text-slate-600">{files.map(f=><div key={f.name}>{f.name}</div>)}{pages>0&&<div className="mt-1 text-blue-700">{lang==="zh"?`第一个文件：${pages} 页`:`${pages} pages in first file`}</div>}</div>}<label className="block text-sm text-slate-600">{t("页码范围（提取/旋转）","Page range (extract/rotate)")}<input value={range} onChange={e=>setRange(e.target.value)} placeholder="1-3,5,8-10" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-blue-400"/></label><div className="flex flex-wrap gap-3"><button disabled={files.length<2||busy} onClick={merge} className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white disabled:opacity-40">{t("合并 PDF","Merge PDFs")}</button><button disabled={!files[0]||busy} onClick={extract} className="rounded-full border border-slate-300 px-5 py-2.5 text-sm disabled:opacity-40">{t("提取这些页","Extract these pages")}</button><button disabled={!files[0]||busy} onClick={rotate} className="rounded-full border border-slate-300 px-5 py-2.5 text-sm disabled:opacity-40">{t("选中页旋转 90°","Rotate selected pages 90°")}</button></div>{error&&<p className="text-sm text-rose-600">{error}</p>}</div>;
}
