"use client";
import { useEffect,useMemo,useState } from "react";
import { PDFDocument, rgb, degrees } from "pdf-lib";
import { pdfExportPrice } from "@/lib/tools/export-pricing";
import PaidExportButton from "@/components/tools/PaidExportButton";
type Overlay={id:number;kind:"text"|"cover"|"image";page:number;x:number;y:number;w:number;h:number;text?:string;size?:number;data?:string};
function readData(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});}
function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200);}
async function textPng(text:string,size=28){const c=document.createElement("canvas"),ctx=c.getContext("2d")!;ctx.font=`${size}px Inter, Noto Sans SC, Microsoft YaHei, sans-serif`;const m=ctx.measureText(text);c.width=Math.max(32,Math.ceil(m.width+16));c.height=Math.max(40,Math.ceil(size*1.6));const x=c.getContext("2d")!;x.font=ctx.font;x.fillStyle="#142033";x.textBaseline="middle";x.fillText(text,8,c.height/2);return await new Promise<Uint8Array>((res,rej)=>c.toBlob(async b=>b?res(new Uint8Array(await b.arrayBuffer())):rej(new Error("文字渲染失败")),"image/png"));}
function pagesFrom(s:string,max:number){if(!s.trim())return Array.from({length:max},(_,i)=>i+1);const out=new Set<number>();for(const part of s.split(",")){if(part.includes("-")){const [a,b]=part.split("-").map(Number);for(let i=Math.max(1,a);i<=Math.min(max,b);i++)out.add(i);}else{const n=Number(part);if(n>=1&&n<=max)out.add(n);}}return [...out].sort((a,b)=>a-b);}
async function transparentWhite(data:string){const im=await new Promise<HTMLImageElement>((res,rej)=>{const x=new Image();x.onload=()=>res(x);x.onerror=rej;x.src=data});const c=document.createElement("canvas");c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext("2d")!;x.drawImage(im,0,0);const d=x.getImageData(0,0,c.width,c.height);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2];if(r>235&&g>235&&b>235)d.data[i+3]=0;}x.putImageData(d,0,0);return c.toDataURL("image/png");}
export default function PdfEditorWorkbench({signingOnly=false}:{signingOnly?:boolean}){
 const [file,setFile]=useState<File|null>(null),[pages,setPages]=useState(0),[overlays,setOverlays]=useState<Overlay[]>([]),[selectedPage,setSelectedPage]=useState(1),[text,setText]=useState(""),[busy,setBusy]=useState(false),[preview,setPreview]=useState(""),[stamp,setStamp]=useState(""),[error,setError]=useState(""),[pageRange,setPageRange]=useState(""),[seamSide,setSeamSide]=useState<"right"|"left"|"top"|"bottom">("right");
 const exportPages=pagesFrom(pageRange,pages).length||pages;const price=useMemo(()=>pdfExportPrice(Math.max(1,exportPages)),[exportPages]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 async function load(f:File){setFile(f);setOverlays([]);setError("");const d=await PDFDocument.load(await f.arrayBuffer());setPages(d.getPageCount());setSelectedPage(1);setPageRange(`1-${d.getPageCount()}`);}
 function patch(id:number,k:Partial<Overlay>){setOverlays(v=>v.map(o=>o.id===id?{...o,...k}:o));}
 function addText(){if(text.trim())setOverlays(v=>[...v,{id:Date.now(),kind:"text",page:selectedPage,x:10,y:12,w:45,h:8,text:text.trim(),size:14}]);setText("");}
 function addCover(){setOverlays(v=>[...v,{id:Date.now(),kind:"cover",page:selectedPage,x:10,y:12,w:35,h:8}]);}
 async function addImage(f:File,asStamp=false){let data=await readData(f);if(asStamp)data=await transparentWhite(data);if(asStamp)setStamp(data);setOverlays(v=>[...v,{id:Date.now(),kind:"image",page:selectedPage,x:70,y:65,w:18,h:18,data}]);}
 async function seam(){if(!stamp)return;const selected=pagesFrom(pageRange,pages);if(!selected.length)return;const img=await new Promise<HTMLImageElement>((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=stamp});const pieces:string[]=[];const horizontal=seamSide==="top"||seamSide==="bottom";for(let i=0;i<selected.length;i++){const c=document.createElement("canvas");if(horizontal){const sy=Math.floor(img.naturalHeight*i/selected.length),ey=Math.floor(img.naturalHeight*(i+1)/selected.length),sh=Math.max(1,ey-sy);c.width=img.naturalWidth;c.height=sh;c.getContext("2d")!.drawImage(img,0,sy,img.naturalWidth,sh,0,0,img.naturalWidth,sh);}else{const sx=Math.floor(img.naturalWidth*i/selected.length),ex=Math.floor(img.naturalWidth*(i+1)/selected.length),sw=Math.max(1,ex-sx);c.width=sw;c.height=img.naturalHeight;c.getContext("2d")!.drawImage(img,sx,0,sw,img.naturalHeight,0,0,sw,img.naturalHeight);}pieces.push(c.toDataURL("image/png"));}setOverlays(v=>[...v,...pieces.map((data,i)=>({id:Date.now()+i,kind:"image" as const,page:selected[i],x:seamSide==="right"?95:seamSide==="left"?0:25,y:seamSide==="bottom"?95:seamSide==="top"?0:22,w:horizontal?50:5,h:horizontal?5:56,data}))]);}
 async function build(){if(!file)throw new Error("请先上传 PDF");const doc=await PDFDocument.load(await file.arrayBuffer());for(const o of overlays){const p=doc.getPage(o.page-1);if(!p)continue;const W=p.getWidth(),H=p.getHeight(),x=W*o.x/100,y=H-(H*o.y/100)-(H*o.h/100),w=W*o.w/100,h=H*o.h/100;if(o.kind==="cover")p.drawRectangle({x,y,width:w,height:h,color:rgb(1,1,1)});else if(o.kind==="text"){const png=await doc.embedPng(await textPng(o.text||"",Math.max(18,(o.size||14)*2))),r=png.width/png.height,dh=Math.min(h,Math.max(10,w/r));p.drawImage(png,{x,y:y+(h-dh)/2,width:Math.min(w,dh*r),height:dh});}else if(o.kind==="image"&&o.data){const bytes=Uint8Array.from(atob(o.data.split(",")[1]),c=>c.charCodeAt(0)),img=o.data.startsWith("data:image/png")?await doc.embedPng(bytes):await doc.embedJpg(bytes);p.drawImage(img,{x,y,width:w,height:h});}}
 const ids=pagesFrom(pageRange,doc.getPageCount()).map(n=>n-1);if(ids.length!==doc.getPageCount()){const out=await PDFDocument.create();for(const p of await out.copyPages(doc,ids))out.addPage(p);return out.save();}return doc.save();}
 async function previewNow(){setBusy(true);setError("");try{const bytes=await build(),c=new Uint8Array(bytes.length);c.set(bytes);if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(new Blob([c.buffer],{type:"application/pdf"})));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function exportNow(){setBusy(true);try{const bytes=await build(),c=new Uint8Array(bytes.length);c.set(bytes);download(new Blob([c.buffer],{type:"application/pdf"}),`lingxifield-${file?.name||"edited.pdf"}`);}finally{setBusy(false);}}
 async function rotateCurrent(){if(!file)return;const d=await PDFDocument.load(await file.arrayBuffer());const p=d.getPage(selectedPage-1);p.setRotation(degrees((p.getRotation().angle+90)%360));const bytes=await d.save(),c=new Uint8Array(bytes.length);c.set(bytes);const nf=new File([c.buffer],file.name,{type:"application/pdf"});await load(nf);}
 return <div className="space-y-5">
  <label onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files?.[0];if(f)load(f)}} className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><input type="file" accept="application/pdf" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)load(f)}}/><b>上传 PDF</b><p className="mt-1 text-sm text-slate-500">编辑和预览免费；正式支付接线后，导出按本次实际导出页数计费。</p></label>
  {file&&<><div className="flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-slate-100 px-3 py-2">{pages} 页</span><label className="rounded-full border border-slate-200 px-3 py-2">编辑第 <input type="number" min={1} max={pages} value={selectedPage} onChange={e=>setSelectedPage(Math.min(pages,Math.max(1,Number(e.target.value)||1)))} className="w-12 bg-transparent text-center"/> 页</label><button onClick={rotateCurrent} className="rounded-full border border-slate-200 px-3 py-2">当前页旋转 90°</button></div>
   <label className="block text-sm text-slate-600">本次导出页码<input value={pageRange} onChange={e=>setPageRange(e.target.value)} placeholder="1-10,12" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"/><span className="mt-1 block text-xs text-slate-400">实际导出 {exportPages} 页 · 当前估价 ¥{price}</span></label>
   {!signingOnly&&<div className="grid gap-3 rounded-2xl border border-slate-200 p-4 md:grid-cols-[1fr_auto_auto]"><input value={text} onChange={e=>setText(e.target.value)} placeholder="输入要添加/覆盖后的文字" className="rounded-xl border border-slate-200 px-3 py-2.5"/><button onClick={addText} className="rounded-full bg-blue-600 px-4 py-2 text-sm text-white">加文字</button><button onClick={addCover} className="rounded-full border border-slate-200 px-4 py-2 text-sm">遮盖区域</button></div>}
   <div className="grid gap-3 sm:grid-cols-3"><label onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files?.[0];if(f)addImage(f)}} className="cursor-pointer rounded-2xl border border-slate-200 p-4 text-sm"><input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)addImage(f)}}/><b>添加图片</b><p className="mt-1 text-slate-500">照片、Logo、二维码</p></label><label onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files?.[0];if(f)addImage(f,true)}} className="cursor-pointer rounded-2xl border border-slate-200 p-4 text-sm"><input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)addImage(f,true)}}/><b>上传签名 / 印章</b><p className="mt-1 text-slate-500">自动尝试去白底</p></label><button onClick={()=>setOverlays([])} className="rounded-2xl border border-slate-200 p-4 text-left text-sm"><b>清空编辑层</b><p className="mt-1 text-slate-500">原 PDF 不变</p></button></div>
   {stamp&&<div className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-center gap-3"><b className="text-sm">骑缝章</b><select value={seamSide} onChange={e=>setSeamSide(e.target.value as any)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="right">右侧</option><option value="left">左侧</option><option value="top">顶部</option><option value="bottom">底部</option></select><button onClick={seam} className="rounded-full bg-blue-600 px-4 py-2 text-sm text-white">按导出页范围切片盖章</button></div></div>}
   {overlays.length>0&&<div className="space-y-2"><h3 className="text-sm font-semibold">编辑元素 · 可自由调整位置和尺寸</h3>{overlays.map(o=><div key={o.id} className="grid gap-2 rounded-2xl border border-slate-200 p-3 text-xs sm:grid-cols-[70px_repeat(4,1fr)_auto]"><span>{o.kind} · P{o.page}</span>{(["x","y","w","h"] as const).map(k=><label key={k}>{k.toUpperCase()}%<input type="number" min={0} max={100} value={o[k]} onChange={e=>patch(o.id,{[k]:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-slate-200 px-2 py-1"/></label>)}<button onClick={()=>setOverlays(v=>v.filter(x=>x.id!==o.id))} className="text-rose-600">删除</button></div>)}</div>}
   <div className="flex flex-wrap gap-3"><button onClick={previewNow} disabled={busy} className="rounded-full border border-slate-300 px-5 py-2.5 text-sm">{busy?"处理中…":"免费生成预览"}</button><PaidExportButton toolId={signingOnly ? "e-sign-pdf" : "pdf-editor"} quantity={Math.max(1,exportPages)} onUnlocked={exportNow} label={`支付并导出 · ${exportPages} 页`} /></div>
   <p className="text-xs leading-5 text-slate-500">此版本已经按“实际导出页数”计算费用并支持自由坐标调整；线上导出已接真实支付订单；付款成功后才会调用最终导出。视觉签章不等于数字证书签名。</p>
   {preview&&<iframe src={preview} title="PDF 预览" className="h-[620px] w-full rounded-2xl border border-slate-200"/>}{error&&<p className="text-sm text-rose-600">{error}</p>}</>}
 </div>;
}
