"use client";

import {useMemo,useState} from "react";
import {PDFDocument,PDFName,StandardFonts,rgb} from "pdf-lib";
import FileDropzone from "@/components/tools/FileDropzone";
import ResultPanel from "@/components/tools/ResultPanel";
import {useLingxiLang,type LingxiLang} from "@/lib/lingxi-i18n";
import type {ToolResultFile} from "@/lib/tools/types";

export type PdfFinishingMode="overlay"|"header-footer"|"bates"|"viewer-preferences";
type Copy={local:string;pickPdf:string;pickOverlay:string;run:string;working:string;done:string;free:string;header:string;footer:string;pageNo:string;prefix:string;suffix:string;start:string;digits:string;layout:string;mode:string;fit:string;title:string;toolbar:string;menubar:string;rtl:string;firstOverlay:string;matchOverlay:string;overlayRule:string;privacy:string;invalid:string;};
const C:Record<LingxiLang,Copy>={
zh:{local:"免费 · 文件只在浏览器里处理。",pickPdf:"选择 PDF",pickOverlay:"选择要叠加的 PDF",run:"开始处理",working:"正在处理…",done:"处理完成",free:"免费",header:"页眉文字",footer:"页脚文字",pageNo:"同时添加页码",prefix:"编号前缀",suffix:"编号后缀",start:"起始编号",digits:"编号位数",layout:"页面显示方式",mode:"打开时显示",fit:"适合窗口",title:"显示文档标题",toolbar:"隐藏工具栏",menubar:"隐藏菜单栏",rtl:"从右向左阅读",firstOverlay:"用叠加文件的第一页覆盖全部页面",matchOverlay:"按页对应叠加，多出的页面重复最后一页",overlayRule:"叠加内容会铺满原页面，适合信纸、抬头纸、背景章或统一底图。",privacy:"不上传文件，不调用在线服务。",invalid:"这个 PDF 暂时无法处理，请换一个文件再试。"},
en:{local:"Free · Files stay in your browser.",pickPdf:"Choose PDF",pickOverlay:"Choose overlay PDF",run:"Process",working:"Processing…",done:"Done",free:"Free",header:"Header text",footer:"Footer text",pageNo:"Add page numbers",prefix:"Number prefix",suffix:"Number suffix",start:"Starting number",digits:"Number digits",layout:"Page layout",mode:"Open with",fit:"Fit window",title:"Show document title",toolbar:"Hide toolbar",menubar:"Hide menu bar",rtl:"Right-to-left reading",firstOverlay:"Use the first overlay page on every page",matchOverlay:"Match pages; repeat the last overlay page when needed",overlayRule:"The overlay is fitted to each page. Useful for letterhead, backgrounds, stamps or branded sheets.",privacy:"No upload and no online processing.",invalid:"This PDF could not be processed. Try another file."},
ja:{local:"無料 · ファイルはブラウザ内だけで処理されます。",pickPdf:"PDFを選択",pickOverlay:"重ねるPDFを選択",run:"処理する",working:"処理中…",done:"完了",free:"無料",header:"ヘッダー文字",footer:"フッター文字",pageNo:"ページ番号も追加",prefix:"番号の前置き",suffix:"番号の後置き",start:"開始番号",digits:"桁数",layout:"ページ表示",mode:"開いたとき",fit:"ウィンドウに合わせる",title:"文書タイトルを表示",toolbar:"ツールバーを隠す",menubar:"メニューを隠す",rtl:"右から左に読む",firstOverlay:"重ねるPDFの1ページ目をすべてに使用",matchOverlay:"ページごとに対応し、不足分は最後のページを繰り返す",overlayRule:"レターヘッド、背景、印影、統一背景に使えます。",privacy:"アップロードせず、オンライン処理も使いません。",invalid:"このPDFは処理できませんでした。別のファイルをお試しください。"},
ko:{local:"무료 · 파일은 브라우저 안에서만 처리됩니다.",pickPdf:"PDF 선택",pickOverlay:"겹칠 PDF 선택",run:"처리",working:"처리 중…",done:"완료",free:"무료",header:"머리글",footer:"바닥글",pageNo:"페이지 번호도 추가",prefix:"번호 앞글자",suffix:"번호 뒷글자",start:"시작 번호",digits:"번호 자리수",layout:"페이지 배치",mode:"열 때 표시",fit:"창에 맞춤",title:"문서 제목 표시",toolbar:"도구 모음 숨기기",menubar:"메뉴 숨기기",rtl:"오른쪽에서 왼쪽 읽기",firstOverlay:"겹침 PDF의 첫 페이지를 모든 페이지에 사용",matchOverlay:"페이지별 대응, 부족하면 마지막 페이지 반복",overlayRule:"레터헤드, 배경, 도장, 공통 서식에 적합합니다.",privacy:"업로드하거나 온라인 서비스를 사용하지 않습니다.",invalid:"이 PDF를 처리할 수 없습니다. 다른 파일을 사용해 보세요."},
fr:{local:"Gratuit · Les fichiers restent dans votre navigateur.",pickPdf:"Choisir un PDF",pickOverlay:"Choisir le PDF à superposer",run:"Traiter",working:"Traitement…",done:"Terminé",free:"Gratuit",header:"Texte d’en-tête",footer:"Texte de pied de page",pageNo:"Ajouter aussi les numéros de page",prefix:"Préfixe",suffix:"Suffixe",start:"Numéro de départ",digits:"Nombre de chiffres",layout:"Disposition",mode:"À l’ouverture",fit:"Ajuster à la fenêtre",title:"Afficher le titre",toolbar:"Masquer la barre d’outils",menubar:"Masquer le menu",rtl:"Lecture de droite à gauche",firstOverlay:"Utiliser la première page de superposition partout",matchOverlay:"Faire correspondre les pages, puis répéter la dernière",overlayRule:"Pratique pour papier à en-tête, fond, cachet ou modèle commun.",privacy:"Aucun envoi ni traitement en ligne.",invalid:"Ce PDF n’a pas pu être traité. Essayez un autre fichier."},
de:{local:"Kostenlos · Dateien bleiben im Browser.",pickPdf:"PDF wählen",pickOverlay:"Overlay-PDF wählen",run:"Verarbeiten",working:"Wird verarbeitet…",done:"Fertig",free:"Kostenlos",header:"Kopfzeile",footer:"Fußzeile",pageNo:"Seitennummern hinzufügen",prefix:"Präfix",suffix:"Suffix",start:"Startnummer",digits:"Stellen",layout:"Seitenlayout",mode:"Beim Öffnen",fit:"Fenster anpassen",title:"Dokumenttitel anzeigen",toolbar:"Werkzeugleiste ausblenden",menubar:"Menü ausblenden",rtl:"Von rechts nach links lesen",firstOverlay:"Erste Overlay-Seite auf allen Seiten verwenden",matchOverlay:"Seiten zuordnen, letzte Seite bei Bedarf wiederholen",overlayRule:"Geeignet für Briefpapier, Hintergründe, Stempel oder Vorlagen.",privacy:"Keine Uploads und keine Online-Verarbeitung.",invalid:"Dieses PDF konnte nicht verarbeitet werden. Bitte eine andere Datei versuchen."},
es:{local:"Gratis · Los archivos permanecen en tu navegador.",pickPdf:"Elegir PDF",pickOverlay:"Elegir PDF para superponer",run:"Procesar",working:"Procesando…",done:"Listo",free:"Gratis",header:"Texto de encabezado",footer:"Texto de pie",pageNo:"Añadir números de página",prefix:"Prefijo",suffix:"Sufijo",start:"Número inicial",digits:"Dígitos",layout:"Diseño de página",mode:"Al abrir",fit:"Ajustar a ventana",title:"Mostrar título",toolbar:"Ocultar barra de herramientas",menubar:"Ocultar menú",rtl:"Lectura de derecha a izquierda",firstOverlay:"Usar la primera página de superposición en todas",matchOverlay:"Emparejar páginas y repetir la última si hace falta",overlayRule:"Útil para membretes, fondos, sellos o plantillas comunes.",privacy:"Sin cargas ni procesamiento online.",invalid:"No se pudo procesar este PDF. Prueba con otro archivo."},
pt:{local:"Grátis · Os ficheiros ficam no navegador.",pickPdf:"Escolher PDF",pickOverlay:"Escolher PDF de sobreposição",run:"Processar",working:"A processar…",done:"Concluído",free:"Grátis",header:"Texto do cabeçalho",footer:"Texto do rodapé",pageNo:"Adicionar números de página",prefix:"Prefixo",suffix:"Sufixo",start:"Número inicial",digits:"Dígitos",layout:"Layout da página",mode:"Ao abrir",fit:"Ajustar à janela",title:"Mostrar título",toolbar:"Ocultar barra de ferramentas",menubar:"Ocultar menu",rtl:"Leitura da direita para a esquerda",firstOverlay:"Usar a primeira página de sobreposição em todas",matchOverlay:"Corresponder páginas e repetir a última quando necessário",overlayRule:"Útil para papel timbrado, fundos, carimbos ou modelos comuns.",privacy:"Sem upload nem processamento online.",invalid:"Não foi possível processar este PDF. Tente outro ficheiro."},
ar:{local:"مجاني · تبقى الملفات داخل المتصفح.",pickPdf:"اختر PDF",pickOverlay:"اختر PDF للتراكب",run:"ابدأ المعالجة",working:"جارٍ المعالجة…",done:"اكتمل",free:"مجاني",header:"نص الرأس",footer:"نص التذييل",pageNo:"إضافة أرقام الصفحات",prefix:"بادئة الرقم",suffix:"لاحقة الرقم",start:"رقم البداية",digits:"عدد الخانات",layout:"تخطيط الصفحات",mode:"عند الفتح",fit:"ملاءمة النافذة",title:"إظهار عنوان المستند",toolbar:"إخفاء شريط الأدوات",menubar:"إخفاء القائمة",rtl:"القراءة من اليمين إلى اليسار",firstOverlay:"استخدام الصفحة الأولى من ملف التراكب على جميع الصفحات",matchOverlay:"مطابقة الصفحات وتكرار الصفحة الأخيرة عند الحاجة",overlayRule:"مناسب للترويسة والخلفية والختم والقوالب الموحدة.",privacy:"لا يتم رفع الملفات ولا استخدام معالجة عبر الإنترنت.",invalid:"تعذر معالجة ملف PDF هذا. جرّب ملفاً آخر."}
};
function result(name:string,bytes:Uint8Array):ToolResultFile{const copy=new Uint8Array(bytes.byteLength);copy.set(bytes);const blob=new Blob([copy.buffer],{type:"application/pdf"});return{name,blob,mime:"application/pdf",size:blob.size}}
function safeName(name:string,tag:string){return name.replace(/\.pdf$/i,"")+`-${tag}.pdf`}

export default function PdfFinishingWorkbench({mode}:{mode:PdfFinishingMode}){
  const {lang}=useLingxiLang(); const t=C[lang];
  const [files,setFiles]=useState<File[]>([]),[overlayFiles,setOverlayFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[out,setOut]=useState<ToolResultFile[]>([]);
  const [overlayRule,setOverlayRule]=useState<"first"|"match">("first"),[header,setHeader]=useState(""),[footer,setFooter]=useState(""),[pageNo,setPageNo]=useState(true);
  const [prefix,setPrefix]=useState("LX-"),[suffix,setSuffix]=useState(""),[start,setStart]=useState(1),[digits,setDigits]=useState(6);
  const [layout,setLayout]=useState("SinglePage"),[pageMode,setPageMode]=useState("UseNone"),[fit,setFit]=useState(true),[showTitle,setShowTitle]=useState(true),[hideToolbar,setHideToolbar]=useState(false),[hideMenubar,setHideMenubar]=useState(false),[readingRtl,setReadingRtl]=useState(false);
  const ready=useMemo(()=>files.length===1&&!busy&&(mode!=="overlay"||overlayFiles.length===1),[files,overlayFiles,busy,mode]);
  async function run(){if(!ready)return;setBusy(true);setError("");setOut([]);try{
    const source=files[0]; const doc=await PDFDocument.load(await source.arrayBuffer(),{ignoreEncryption:false});
    if(mode==="overlay"){
      const ov=await PDFDocument.load(await overlayFiles[0].arrayBuffer(),{ignoreEncryption:false}); const ovCount=ov.getPageCount(); if(!ovCount)throw new Error("EMPTY_OVERLAY");
      for(let i=0;i<doc.getPageCount();i++){const oi=overlayRule==="first"?0:Math.min(i,ovCount-1);const embedded=await doc.embedPage(ov.getPage(oi));const p=doc.getPage(i);const {width,height}=p.getSize();p.drawPage(embedded,{x:0,y:0,width,height});}
    }else if(mode==="header-footer"){
      const font=await doc.embedFont(StandardFonts.Helvetica);const count=doc.getPageCount();for(let i=0;i<count;i++){const p=doc.getPage(i);const {width,height}=p.getSize();if(header.trim())p.drawText(header.trim().slice(0,120),{x:36,y:height-28,size:9,font,color:rgb(.25,.25,.25)});let bottom=footer.trim().slice(0,120);if(pageNo)bottom+=(bottom?"   ":"")+`${i+1} / ${count}`;if(bottom)p.drawText(bottom,{x:36,y:18,size:9,font,color:rgb(.25,.25,.25)});}
    }else if(mode==="bates"){
      const font=await doc.embedFont(StandardFonts.Helvetica);for(let i=0;i<doc.getPageCount();i++){const p=doc.getPage(i);const label=`${prefix}${String(Math.max(0,start)+i).padStart(Math.max(1,Math.min(12,digits)),"0")}${suffix}`.slice(0,120);const size=9;const w=font.widthOfTextAtSize(label,size);p.drawText(label,{x:Math.max(24,p.getWidth()-w-28),y:18,size,font,color:rgb(.2,.2,.2)});}
    }else{
      doc.catalog.set(PDFName.of("PageLayout"),PDFName.of(layout));doc.catalog.set(PDFName.of("PageMode"),PDFName.of(pageMode));
      const prefs=doc.context.obj({FitWindow:fit,DisplayDocTitle:showTitle,HideToolbar:hideToolbar,HideMenubar:hideMenubar,Direction:PDFName.of(readingRtl?"R2L":"L2R")});doc.catalog.set(PDFName.of("ViewerPreferences"),prefs);
    }
    const bytes=await doc.save({useObjectStreams:true});setOut([result(safeName(source.name,mode==="overlay"?"overlay":mode==="header-footer"?"header-footer":mode==="bates"?"bates":"view"),bytes)]);
  }catch{setError(t.invalid)}finally{setBusy(false)}}
  return <div dir={lang==="ar"?"rtl":"ltr"} className="space-y-5"><div className="rounded-xl border border-[var(--lx-line)] bg-[var(--lx-soft)] p-3 text-xs text-[var(--lx-muted)]">{t.local} {t.privacy}</div><FileDropzone accept="application/pdf,.pdf" maxFiles={1} files={files} onChange={n=>{setFiles(n.slice(0,1));setOut([]);setError("")}} disabled={busy} kind="pdf"/>
  {mode==="overlay"&&<><FileDropzone accept="application/pdf,.pdf" maxFiles={1} files={overlayFiles} onChange={n=>{setOverlayFiles(n.slice(0,1));setOut([])}} disabled={busy} kind="pdf"/><div className="space-y-2 rounded-xl border border-[var(--lx-line)] p-4 text-sm"><label className="flex gap-2"><input type="radio" checked={overlayRule==="first"} onChange={()=>setOverlayRule("first")}/>{t.firstOverlay}</label><label className="flex gap-2"><input type="radio" checked={overlayRule==="match"} onChange={()=>setOverlayRule("match")}/>{t.matchOverlay}</label><p className="text-xs text-[var(--lx-muted)]">{t.overlayRule}</p></div></>}
  {mode==="header-footer"&&<div className="grid gap-3 md:grid-cols-2"><label className="text-sm">{t.header}<input value={header} onChange={e=>setHeader(e.target.value)} maxLength={120} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"/></label><label className="text-sm">{t.footer}<input value={footer} onChange={e=>setFooter(e.target.value)} maxLength={120} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={pageNo} onChange={e=>setPageNo(e.target.checked)}/>{t.pageNo}</label></div>}
  {mode==="bates"&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm">{t.prefix}<input value={prefix} onChange={e=>setPrefix(e.target.value)} maxLength={30} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm">{t.suffix}<input value={suffix} onChange={e=>setSuffix(e.target.value)} maxLength={30} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm">{t.start}<input type="number" min={0} value={start} onChange={e=>setStart(Number(e.target.value)||0)} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm">{t.digits}<input type="number" min={1} max={12} value={digits} onChange={e=>setDigits(Math.max(1,Math.min(12,Number(e.target.value)||1)))} className="mt-2 w-full rounded-xl border p-3"/></label></div>}
  {mode==="viewer-preferences"&&<div className="grid gap-3 md:grid-cols-2"><label className="text-sm">{t.layout}<select value={layout} onChange={e=>setLayout(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="SinglePage">Single page</option><option value="OneColumn">Continuous</option><option value="TwoColumnLeft">Two columns</option><option value="TwoPageLeft">Two pages</option></select></label><label className="text-sm">{t.mode}<select value={pageMode} onChange={e=>setPageMode(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="UseNone">Document</option><option value="UseOutlines">Bookmarks</option><option value="UseThumbs">Thumbnails</option><option value="FullScreen">Full screen</option></select></label>{[[t.fit,fit,setFit],[t.title,showTitle,setShowTitle],[t.toolbar,hideToolbar,setHideToolbar],[t.menubar,hideMenubar,setHideMenubar],[t.rtl,readingRtl,setReadingRtl]].map(([label,val,setter],i)=><label key={i} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(val)} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/>{String(label)}</label>)}</div>}
  {ready&&<button type="button" onClick={run} className="rounded-xl bg-[var(--lx-ink)] px-5 py-3 text-sm font-medium text-[var(--lx-bg)]">{busy?t.working:t.run}</button>}{busy&&<p className="text-sm text-[var(--lx-muted)]">{t.working}</p>}{error&&<p className="text-sm text-[var(--lx-danger)]">{error}</p>}{out.length>0&&<ResultPanel sourceSlug={`pdf-${mode}`} files={out} messageZh="处理完成，可直接下载。" messageEn="Done. Your PDF is ready to download."/>}</div>
}
