"use client";
import {plainText,plainMessage} from "@/lib/tools/plain-copy";

import {useState} from "react";import {PDFDocument,degrees} from "pdf-lib";import ResultPanel from "@/components/tools/ResultPanel";import FileDropzone from "@/components/tools/FileDropzone";import {useLingxiLang} from "@/lib/lingxi-i18n";import type {ToolResultFile} from "@/lib/tools/types";
type Item={source:number;rotation:number};
export default function PdfPageManagerWorkbench(){const{lang}=useLingxiLang();const[files,setFiles]=useState<File[]>([]),[items,setItems]=useState<Item[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<ToolResultFile[]>([]);const file=files[0]||null;
 async function choose(next:File[]){setFiles(next);setResult([]);setError("");if(!next[0]){setItems([]);return}try{const d=await PDFDocument.load(await next[0].arrayBuffer());setItems(Array.from({length:d.getPageCount()},(_,i)=>({source:i,rotation:0})))}catch(e){setItems([]);setError(plainText(lang,"pdfError"))}}
 function move(i:number,delta:number){setItems(v=>{const n=[...v],j=i+delta;if(j<0||j>=n.length)return v;[n[i],n[j]]=[n[j],n[i]];return n})}
 async function exportPdf(){if(!file||!items.length)return;setBusy(true);setError("");setResult([]);try{const src=await PDFDocument.load(await file.arrayBuffer()),out=await PDFDocument.create();for(const it of items){const[p]=await out.copyPages(src,[it.source]);p.setRotation(degrees(((p.getRotation().angle+it.rotation)%360+360)%360));out.addPage(p)}const bytes=await out.save({useObjectStreams:true}),blob=new Blob([new Uint8Array(bytes)],{type:"application/pdf"});setResult([{name:`pages-${file.name}`,blob,mime:"application/pdf",size:blob.size}])}catch(e){setError(plainText(lang,"pdfError"))}finally{setBusy(false)}}
 return <div className="space-y-4"><FileDropzone accept="application/pdf,.pdf" files={files} onChange={f=>void choose(f)} disabled={busy} kind="pdf" maxSizeMB={200}/>{items.length>0&&<><div className="flex items-center justify-between gap-3"><p className="text-sm text-[var(--lx-muted)]">{plainText(lang,"pageCount",{count:items.length})+" · "+plainText(lang,"reorder")}</p><button onClick={()=>setItems([])} className="text-xs text-[var(--lx-faint)] hover:text-[var(--lx-ink)]">{plainText(lang,"clearPages")}</button></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map((it,i)=><div key={`${it.source}-${i}`} className="flex items-center gap-2 rounded-xl border border-[var(--lx-line)] bg-[var(--lx-soft)] p-3 text-sm"><b className="mr-auto text-[var(--lx-ink)]">{plainText(lang,"page",{count:it.source+1})}</b><button disabled={i===0} onClick={()=>move(i,-1)} className="rounded-lg border border-[var(--lx-line)] px-2 py-1 disabled:opacity-30" aria-label={plainText(lang,"up")}>↑</button><button disabled={i===items.length-1} onClick={()=>move(i,1)} className="rounded-lg border border-[var(--lx-line)] px-2 py-1 disabled:opacity-30" aria-label={plainText(lang,"down")}>↓</button><button onClick={()=>setItems(v=>v.map((x,j)=>j===i?{...x,rotation:(x.rotation+90)%360}:x))} className="rounded-lg border border-[var(--lx-line)] px-2 py-1" aria-label={plainText(lang,"rotate")}>↻{it.rotation?` ${it.rotation}°`:""}</button><button onClick={()=>setItems(v=>v.filter((_,j)=>j!==i))} className="rounded-lg border border-[var(--lx-line)] px-2 py-1 text-[var(--lx-danger)]">{plainText(lang,"delete")}</button></div>)}</div></>}<button disabled={!items.length||busy} onClick={exportPdf} className="rounded-xl bg-[var(--lx-ink)] px-5 py-2.5 text-sm font-medium text-[var(--lx-bg)] disabled:opacity-40">{busy?plainText(lang,"working"):plainText(lang,"preview")}</button>{result.length>0&&<ResultPanel files={result} messageZh={plainText(lang,"ready")} messageEn={plainText(lang,"ready")} details={{pages:items.length}}/>}{error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{plainMessage(lang,error)}</p>}</div>}
