"use client";

import {useMemo,useState} from "react";
import FileDropzone from "@/components/tools/FileDropzone";
import ResultPanel from "@/components/tools/ResultPanel";
import {useLingxiLang,type LingxiLang} from "@/lib/lingxi-i18n";
import type {ToolResultFile} from "@/lib/tools/types";

export type PdfStructuralMode="protect"|"unlock"|"permissions"|"linearize";
type Copy={local:string;run:string;working:string;invalid:string;password:string;owner:string;confirm:string;print:string;modify:string;copy:string;openPassword:string;ownerHint:string;protectHint:string;unlockHint:string;permissionsHint:string;linearizeHint:string;passwordMismatch:string;passwordRequired:string;ownerRequired:string;badPassword:string;full:string;low:string;none:string;all:string;annotate:string;form:string;assembly:string;ready:string;};
const C:Record<LingxiLang,Copy>={
zh:{local:"免费 · 文件只在浏览器里处理，不上传。",run:"开始处理",working:"正在处理…",invalid:"这个 PDF 暂时无法处理，请换一个文件再试。",password:"打开密码",owner:"管理密码",confirm:"再次输入打开密码",print:"允许打印",modify:"允许修改",copy:"允许复制文字和图片",openPassword:"当前密码",ownerHint:"管理密码用于以后解除限制，请妥善保存。",protectHint:"给 PDF 加密码，并可同时限制打印、修改和复制。",unlockHint:"输入你已知的 PDF 密码，生成一个不再需要密码的副本。",permissionsHint:"设置 PDF 的打印、修改和复制权限。文件可以不设打开密码。",linearizeHint:"优化 PDF 的网页打开结构，让第一页更快显示。内容不会被重新压缩成图片。",passwordMismatch:"两次输入的打开密码不一致。",passwordRequired:"请输入打开密码。",ownerRequired:"请输入管理密码。",badPassword:"密码不正确，或这个 PDF 无法解除保护。",full:"完整打印",low:"低质量打印",none:"不允许",all:"允许全部修改",annotate:"只允许批注",form:"只允许填写表单",assembly:"只允许页面整理",ready:"处理完成，可直接下载。"},
en:{local:"Free · Files stay in your browser and are not uploaded.",run:"Process",working:"Processing…",invalid:"This PDF could not be processed. Try another file.",password:"Open password",owner:"Owner password",confirm:"Confirm open password",print:"Allow printing",modify:"Allow changes",copy:"Allow copying text and images",openPassword:"Current password",ownerHint:"Keep the owner password safe. It is needed to remove restrictions later.",protectHint:"Password-protect a PDF and optionally limit printing, editing and copying.",unlockHint:"Enter a password you already know to create an unlocked copy.",permissionsHint:"Set printing, editing and copying permissions. An open password is optional.",linearizeHint:"Optimize the PDF structure for faster first-page display on the web without turning pages into images.",passwordMismatch:"The two open passwords do not match.",passwordRequired:"Enter an open password.",ownerRequired:"Enter an owner password.",badPassword:"The password is incorrect, or this PDF could not be unlocked.",full:"Full printing",low:"Low-quality printing",none:"Not allowed",all:"Allow all changes",annotate:"Annotations only",form:"Form filling only",assembly:"Page assembly only",ready:"Done. Your PDF is ready to download."},
ja:{local:"無料 · ファイルはブラウザ内だけで処理され、アップロードされません。",run:"処理する",working:"処理中…",invalid:"このPDFは処理できませんでした。別のファイルをお試しください。",password:"開くパスワード",owner:"管理パスワード",confirm:"開くパスワードを再入力",print:"印刷を許可",modify:"変更を許可",copy:"文字と画像のコピーを許可",openPassword:"現在のパスワード",ownerHint:"管理パスワードは制限解除に必要です。安全に保管してください。",protectHint:"PDFにパスワードを設定し、印刷・編集・コピーも制限できます。",unlockHint:"既知のPDFパスワードを入力して、パスワード不要のコピーを作成します。",permissionsHint:"印刷・編集・コピー権限を設定します。開くパスワードは任意です。",linearizeHint:"PDFのWeb表示構造を最適化し、最初のページをより早く表示します。",passwordMismatch:"開くパスワードが一致しません。",passwordRequired:"開くパスワードを入力してください。",ownerRequired:"管理パスワードを入力してください。",badPassword:"パスワードが正しくないか、このPDFの保護を解除できませんでした。",full:"高品質印刷",low:"低品質印刷",none:"許可しない",all:"すべての変更を許可",annotate:"注釈のみ",form:"フォーム入力のみ",assembly:"ページ整理のみ",ready:"完了しました。PDFをダウンロードできます。"},
ko:{local:"무료 · 파일은 브라우저 안에서만 처리되며 업로드되지 않습니다.",run:"처리",working:"처리 중…",invalid:"이 PDF를 처리할 수 없습니다. 다른 파일을 사용해 보세요.",password:"열기 비밀번호",owner:"관리 비밀번호",confirm:"열기 비밀번호 확인",print:"인쇄 허용",modify:"수정 허용",copy:"텍스트와 이미지 복사 허용",openPassword:"현재 비밀번호",ownerHint:"관리 비밀번호는 나중에 제한을 해제할 때 필요합니다.",protectHint:"PDF에 비밀번호를 추가하고 인쇄, 수정, 복사를 제한할 수 있습니다.",unlockHint:"알고 있는 PDF 비밀번호를 입력해 비밀번호 없는 사본을 만듭니다.",permissionsHint:"인쇄, 수정, 복사 권한을 설정합니다. 열기 비밀번호는 선택 사항입니다.",linearizeHint:"웹에서 첫 페이지가 더 빨리 보이도록 PDF 구조를 최적화합니다.",passwordMismatch:"열기 비밀번호가 서로 다릅니다.",passwordRequired:"열기 비밀번호를 입력하세요.",ownerRequired:"관리 비밀번호를 입력하세요.",badPassword:"비밀번호가 올바르지 않거나 이 PDF의 보호를 해제할 수 없습니다.",full:"전체 인쇄",low:"저화질 인쇄",none:"허용 안 함",all:"모든 수정 허용",annotate:"주석만",form:"양식 입력만",assembly:"페이지 정리만",ready:"완료되었습니다. PDF를 다운로드할 수 있습니다."},
fr:{local:"Gratuit · Les fichiers restent dans votre navigateur et ne sont pas envoyés.",run:"Traiter",working:"Traitement…",invalid:"Ce PDF n’a pas pu être traité. Essayez un autre fichier.",password:"Mot de passe d’ouverture",owner:"Mot de passe propriétaire",confirm:"Confirmer le mot de passe",print:"Autoriser l’impression",modify:"Autoriser les modifications",copy:"Autoriser la copie du texte et des images",openPassword:"Mot de passe actuel",ownerHint:"Conservez le mot de passe propriétaire : il sera nécessaire pour retirer les restrictions.",protectHint:"Protégez le PDF par mot de passe et limitez si besoin l’impression, la modification et la copie.",unlockHint:"Entrez un mot de passe que vous connaissez pour créer une copie déverrouillée.",permissionsHint:"Définissez les droits d’impression, de modification et de copie. Le mot de passe d’ouverture est facultatif.",linearizeHint:"Optimise la structure du PDF pour afficher plus vite la première page sur le Web.",passwordMismatch:"Les deux mots de passe ne correspondent pas.",passwordRequired:"Saisissez un mot de passe d’ouverture.",ownerRequired:"Saisissez un mot de passe propriétaire.",badPassword:"Le mot de passe est incorrect ou ce PDF n’a pas pu être déverrouillé.",full:"Impression complète",low:"Impression basse qualité",none:"Non autorisé",all:"Toutes les modifications",annotate:"Annotations uniquement",form:"Formulaires uniquement",assembly:"Organisation des pages uniquement",ready:"Terminé. Votre PDF est prêt à télécharger."},
de:{local:"Kostenlos · Dateien bleiben im Browser und werden nicht hochgeladen.",run:"Verarbeiten",working:"Wird verarbeitet…",invalid:"Dieses PDF konnte nicht verarbeitet werden. Bitte eine andere Datei versuchen.",password:"Öffnungspasswort",owner:"Besitzerpasswort",confirm:"Öffnungspasswort bestätigen",print:"Drucken erlauben",modify:"Änderungen erlauben",copy:"Text und Bilder kopieren erlauben",openPassword:"Aktuelles Passwort",ownerHint:"Das Besitzerpasswort wird später zum Aufheben der Einschränkungen benötigt.",protectHint:"PDF mit Passwort schützen und Drucken, Bearbeiten oder Kopieren einschränken.",unlockHint:"Ein bekanntes PDF-Passwort eingeben und eine ungeschützte Kopie erstellen.",permissionsHint:"Druck-, Änderungs- und Kopierrechte festlegen. Ein Öffnungspasswort ist optional.",linearizeHint:"Optimiert die PDF-Struktur für eine schnellere erste Seite im Web.",passwordMismatch:"Die beiden Öffnungspasswörter stimmen nicht überein.",passwordRequired:"Bitte ein Öffnungspasswort eingeben.",ownerRequired:"Bitte ein Besitzerpasswort eingeben.",badPassword:"Das Passwort ist falsch oder das PDF konnte nicht entsperrt werden.",full:"Vollständiger Druck",low:"Druck in niedriger Qualität",none:"Nicht erlaubt",all:"Alle Änderungen erlauben",annotate:"Nur Anmerkungen",form:"Nur Formulare",assembly:"Nur Seitenorganisation",ready:"Fertig. Das PDF kann heruntergeladen werden."},
es:{local:"Gratis · Los archivos permanecen en tu navegador y no se suben.",run:"Procesar",working:"Procesando…",invalid:"No se pudo procesar este PDF. Prueba con otro archivo.",password:"Contraseña de apertura",owner:"Contraseña de propietario",confirm:"Confirmar contraseña",print:"Permitir impresión",modify:"Permitir cambios",copy:"Permitir copiar texto e imágenes",openPassword:"Contraseña actual",ownerHint:"Guarda la contraseña de propietario: será necesaria para quitar las restricciones.",protectHint:"Protege el PDF con contraseña y limita opcionalmente impresión, edición y copia.",unlockHint:"Introduce una contraseña conocida para crear una copia desbloqueada.",permissionsHint:"Configura permisos de impresión, edición y copia. La contraseña de apertura es opcional.",linearizeHint:"Optimiza la estructura del PDF para mostrar antes la primera página en la web.",passwordMismatch:"Las contraseñas no coinciden.",passwordRequired:"Introduce una contraseña de apertura.",ownerRequired:"Introduce una contraseña de propietario.",badPassword:"La contraseña es incorrecta o no se pudo desbloquear este PDF.",full:"Impresión completa",low:"Impresión de baja calidad",none:"No permitido",all:"Permitir todos los cambios",annotate:"Solo anotaciones",form:"Solo formularios",assembly:"Solo organización de páginas",ready:"Listo. El PDF está preparado para descargar."},
pt:{local:"Grátis · Os ficheiros ficam no navegador e não são enviados.",run:"Processar",working:"A processar…",invalid:"Não foi possível processar este PDF. Tente outro ficheiro.",password:"Palavra-passe de abertura",owner:"Palavra-passe de proprietário",confirm:"Confirmar palavra-passe",print:"Permitir impressão",modify:"Permitir alterações",copy:"Permitir copiar texto e imagens",openPassword:"Palavra-passe atual",ownerHint:"Guarde a palavra-passe de proprietário; será necessária para remover restrições.",protectHint:"Proteja o PDF com palavra-passe e limite impressão, edição e cópia se quiser.",unlockHint:"Introduza uma palavra-passe conhecida para criar uma cópia desbloqueada.",permissionsHint:"Defina permissões de impressão, edição e cópia. A palavra-passe de abertura é opcional.",linearizeHint:"Otimiza a estrutura do PDF para mostrar a primeira página mais depressa na Web.",passwordMismatch:"As palavras-passe não coincidem.",passwordRequired:"Introduza uma palavra-passe de abertura.",ownerRequired:"Introduza uma palavra-passe de proprietário.",badPassword:"A palavra-passe está incorreta ou não foi possível desbloquear este PDF.",full:"Impressão completa",low:"Impressão de baixa qualidade",none:"Não permitido",all:"Permitir todas as alterações",annotate:"Apenas anotações",form:"Apenas formulários",assembly:"Apenas organização de páginas",ready:"Concluído. O PDF está pronto para descarregar."},
ar:{local:"مجاني · تبقى الملفات داخل المتصفح ولا يتم رفعها.",run:"ابدأ المعالجة",working:"جارٍ المعالجة…",invalid:"تعذر معالجة ملف PDF هذا. جرّب ملفاً آخر.",password:"كلمة مرور الفتح",owner:"كلمة مرور المالك",confirm:"تأكيد كلمة مرور الفتح",print:"السماح بالطباعة",modify:"السماح بالتعديل",copy:"السماح بنسخ النصوص والصور",openPassword:"كلمة المرور الحالية",ownerHint:"احتفظ بكلمة مرور المالك لأنها مطلوبة لاحقاً لإزالة القيود.",protectHint:"أضف كلمة مرور إلى PDF ويمكنك تقييد الطباعة والتعديل والنسخ.",unlockHint:"أدخل كلمة مرور تعرفها لإنشاء نسخة بدون حماية.",permissionsHint:"اضبط صلاحيات الطباعة والتعديل والنسخ. كلمة مرور الفتح اختيارية.",linearizeHint:"يحسن بنية PDF لعرض الصفحة الأولى بسرعة أكبر على الويب.",passwordMismatch:"كلمتا مرور الفتح غير متطابقتين.",passwordRequired:"أدخل كلمة مرور الفتح.",ownerRequired:"أدخل كلمة مرور المالك.",badPassword:"كلمة المرور غير صحيحة أو تعذر فتح هذا PDF.",full:"طباعة كاملة",low:"طباعة منخفضة الجودة",none:"غير مسموح",all:"السماح بكل التعديلات",annotate:"التعليقات فقط",form:"النماذج فقط",assembly:"ترتيب الصفحات فقط",ready:"اكتمل. ملف PDF جاهز للتنزيل."}
};

type QpdfRunner={runOne:(o:{input:Uint8Array|ArrayBuffer;inputName:string;outputName:string;args:string[]})=>Promise<Uint8Array>;destroy:()=>Promise<void>|void};
let toolkitPromise:Promise<QpdfRunner>|null=null;
async function getToolkit():Promise<QpdfRunner>{
 if(!toolkitPromise)toolkitPromise=import("qpdf-run").then(async m=>{
   const workerUrl=new URL("qpdf-run/worker",import.meta.url).href;
   const qpdfJsUrl=new URL("qpdf-run/qpdf.js",import.meta.url).href;
   const wasmUrl=new URL("qpdf-run/qpdf.wasm",import.meta.url).href;
   return m.createQpdfRunner({workerUrl,qpdfJsUrl,wasmUrl});
 });
 return toolkitPromise;
}
async function runQpdf(file:File,args:string[],tag:string){
 const pdf=await getToolkit();
 const input=new Uint8Array(await file.arrayBuffer());
 return pdf.runOne({input,inputName:"input.pdf",outputName:`${tag}.pdf`,args});
}
function encryptArgs(userPassword:string,ownerPassword:string,print:string,modify:string,extract:boolean){
 return ["input.pdf","output.pdf","--encrypt",`--user-password=${userPassword}`,`--owner-password=${ownerPassword}`,"--bits=256",`--print=${print}`,`--modify=${modify}`,`--extract=${extract?"y":"n"}`,"--"];
}
function outFile(name:string,bytes:Uint8Array):ToolResultFile{const copy=new Uint8Array(bytes.byteLength);copy.set(bytes);const blob=new Blob([copy.buffer],{type:"application/pdf"});return{name,blob,mime:"application/pdf",size:blob.size};}
function tagged(name:string,tag:string){return `${name.replace(/\.pdf$/i,"")}-${tag}.pdf`;}

export default function PdfStructuralWorkbench({mode}:{mode:PdfStructuralMode}){
 const{lang}=useLingxiLang();const t=C[lang];const[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<ToolResultFile[]>([]);
 const[userPassword,setUserPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[ownerPassword,setOwnerPassword]=useState(""),[currentPassword,setCurrentPassword]=useState("");
 const[print,setPrint]=useState<"full"|"low"|"none">("full"),[modify,setModify]=useState<"all"|"annotate"|"form"|"assembly"|"none">("all"),[extract,setExtract]=useState(true);
 const file=files[0]||null;const ready=useMemo(()=>Boolean(file)&&!busy,[file,busy]);
 async function run(){if(!file||busy)return;setError("");setResult([]);if(mode==="protect"&&(!userPassword||userPassword!==confirmPassword)){setError(!userPassword?t.passwordRequired:t.passwordMismatch);return}if(mode==="permissions"&&!ownerPassword){setError(t.ownerRequired);return}if(mode==="unlock"&&!currentPassword){setError(t.passwordRequired);return}setBusy(true);try{let bytes:Uint8Array;const tag=mode==="protect"?"protected":mode==="unlock"?"unlocked":mode==="permissions"?"permissions":"web-optimized";if(mode==="protect")bytes=await runQpdf(file,encryptArgs(userPassword,ownerPassword||userPassword,print,modify,extract),tag);else if(mode==="unlock")bytes=await runQpdf(file,[`--password=${currentPassword}`,"--decrypt","--","input.pdf","output.pdf"],tag);else if(mode==="permissions")bytes=await runQpdf(file,encryptArgs("",ownerPassword,print,modify,extract),tag);else bytes=await runQpdf(file,["--linearize","--","input.pdf","output.pdf"],tag);setResult([outFile(tagged(file.name,tag),bytes)]);}catch(e){console.error(e);const name=String((e as any)?.name||"");setError(mode==="unlock"&&name.includes("Password")?t.badPassword:t.invalid)}finally{setBusy(false)}}
 return <div className="space-y-4"><p className="text-sm text-[var(--lx-muted)]">{t.local}</p><FileDropzone accept="application/pdf,.pdf" maxFiles={1} maxSizeMB={100} files={files} onChange={n=>{setFiles(n.slice(0,1));setResult([]);setError("")}} disabled={busy} kind="pdf"/>
 {mode==="protect"&&<><p className="rounded-xl border border-[var(--lx-line)] p-4 text-sm text-[var(--lx-muted)]">{t.protectHint}</p><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">{t.password}<input type="password" autoComplete="new-password" value={userPassword} onChange={e=>setUserPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"/></label><label className="text-sm">{t.confirm}<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"/></label><label className="text-sm md:col-span-2">{t.owner}<input type="password" autoComplete="new-password" value={ownerPassword} onChange={e=>setOwnerPassword(e.target.value)} placeholder={t.ownerHint} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"/></label></div></>}
 {mode==="unlock"&&<><p className="rounded-xl border border-[var(--lx-line)] p-4 text-sm text-[var(--lx-muted)]">{t.unlockHint}</p><label className="block text-sm">{t.openPassword}<input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"/></label></>}
 {mode==="permissions"&&<><p className="rounded-xl border border-[var(--lx-line)] p-4 text-sm text-[var(--lx-muted)]">{t.permissionsHint}</p><label className="block text-sm">{t.owner}<input type="password" autoComplete="new-password" value={ownerPassword} onChange={e=>setOwnerPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"/><span className="mt-1 block text-xs text-[var(--lx-muted)]">{t.ownerHint}</span></label></>}
 {(mode==="protect"||mode==="permissions")&&<div className="grid gap-3 md:grid-cols-3"><label className="text-sm">{t.print}<select value={print} onChange={e=>setPrint(e.target.value as any)} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"><option value="full">{t.full}</option><option value="low">{t.low}</option><option value="none">{t.none}</option></select></label><label className="text-sm">{t.modify}<select value={modify} onChange={e=>setModify(e.target.value as any)} className="mt-2 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"><option value="all">{t.all}</option><option value="annotate">{t.annotate}</option><option value="form">{t.form}</option><option value="assembly">{t.assembly}</option><option value="none">{t.none}</option></select></label><label className="flex items-end gap-2 rounded-xl border border-[var(--lx-line)] p-3 text-sm"><input type="checkbox" checked={extract} onChange={e=>setExtract(e.target.checked)}/>{t.copy}</label></div>}
 {mode==="linearize"&&<p className="rounded-xl border border-[var(--lx-line)] p-4 text-sm text-[var(--lx-muted)]">{t.linearizeHint}</p>}
 {ready&&<button type="button" onClick={run} className="rounded-xl bg-[var(--lx-ink)] px-5 py-3 text-sm font-medium text-[var(--lx-bg)]">{busy?t.working:t.run}</button>}{busy&&<p className="text-sm text-[var(--lx-muted)]">{t.working}</p>}{error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{error}</p>}{result.length>0&&<ResultPanel sourceSlug={`pdf-${mode}`} files={result} messageZh="处理完成，可直接下载。" messageEn="Done. Your PDF is ready to download."/>}</div>;
}
