"use client";
import {useMemo,useState} from "react";
import {PDFDocument} from "pdf-lib";
import FileDropzone from "@/components/tools/FileDropzone";
import ResultPanel from "@/components/tools/ResultPanel";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import type {ToolResultFile} from "@/lib/tools/types";
type Scan={name:string;kind:string;risks:string[]};
async function scanOne(file:File):Promise<Scan>{if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")){const d=await PDFDocument.load(await file.arrayBuffer());const risks:string[]=[];if(d.getTitle())risks.push("Title");if(d.getAuthor())risks.push("Author");if(d.getSubject())risks.push("Subject");if(d.getKeywords())risks.push("Keywords");if(d.getCreator())risks.push("Creator");if(d.getProducer())risks.push("Producer");return{name:file.name,kind:"PDF",risks}}if(file.type.startsWith("image/"))return{name:file.name,kind:"Image",risks:["EXIF / GPS / device metadata may exist; browser re-encode removes common metadata"]};return{name:file.name,kind:"Unsupported",risks:["Unsupported file type"]}}
async function cleanOne(file:File){if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")){const d=await PDFDocument.load(await file.arrayBuffer());d.setTitle("");d.setAuthor("");d.setSubject("");d.setKeywords([]);d.setProducer("Lingxifield");d.setCreator("Lingxifield");const bytes=await d.save(),copy=new Uint8Array(bytes.length);copy.set(bytes);return new Blob([copy.buffer],{type:"application/pdf"})}if(file.type.startsWith("image/")){const bmp=await createImageBitmap(file),c=document.createElement("canvas");c.width=bmp.width;c.height=bmp.height;const x=c.getContext("2d")!;if(file.type==="image/jpeg"){x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height)}x.drawImage(bmp,0,0);bmp.close?.();return await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error("EXPORT_FAILED")),file.type==="image/png"?"image/png":"image/jpeg",.95))}throw new Error("UNSUPPORTED_FILE")}
export default function PrivacyCleanerWorkbench(){const{lang}=useLingxiLang(),zh=lang==="zh";const[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[scans,setScans]=useState<Scan[]>([]),[results,setResults]=useState<ToolResultFile[]>([]);
 async function scan(){setBusy(true);setError("");try{const out=[] as Scan[];for(const f of files)out.push(await scanOne(f));setScans(out)}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function clean(){setBusy(true);setError("");setResults([]);try{const out:ToolResultFile[]=[];for(const f of files){const blob=await cleanOne(f);out.push({name:"clean-"+f.name,blob,mime:blob.type||"application/octet-stream",size:blob.size})}setResults(out)}catch(e){setError(String(e))}finally{setBusy(false)}}
 const total=useMemo(()=>results.reduce((n,x)=>n+x.size,0),[results]);return <div className="space-y-4"><FileDropzone accept="image/*,application/pdf,.pdf" multiple maxFiles={50} maxSizeMB={50} files={files} onChange={f=>{setFiles(f);setResults([]);setScans([]);setError("")}} disabled={busy}/><p className="text-sm leading-6 text-[var(--lx-muted)]">{zh?"先扫描风险，再决定是否清理。图片通过重新编码去除常见 EXIF/GPS；PDF 清除标题、作者、主题、关键词、Creator/Producer 等属性。":"Scan first, then clean. Images are re-encoded to remove common EXIF/GPS data; PDF document metadata is cleared."}</p><div className="flex gap-2"><button disabled={!files.length||busy} onClick={scan} className="rounded-xl border border-[var(--lx-line)] px-5 py-2.5 text-sm disabled:opacity-40">{zh?"扫描隐私信息":"Scan metadata"}</button><button disabled={!files.length||busy} onClick={clean} className="rounded-xl bg-[var(--lx-ink)] px-5 py-2.5 text-sm text-[var(--lx-bg)] disabled:opacity-40">{zh?"清除并导出":"Clean & export"}</button></div>{scans.length>0&&<div className="space-y-2">{scans.map(s=><div key={s.name} className="rounded-xl border border-[var(--lx-line)] p-3 text-sm"><b>{s.name}</b><span className="ml-2 text-xs text-[var(--lx-faint)]">{s.kind}</span><p className="mt-1 text-xs leading-5 text-[var(--lx-muted)]">{s.risks.length?s.risks.join(" · "):(zh?"未发现常见文档属性风险":"No common document-metadata risk found")}</p></div>)}</div>}{!!results.length&&<ResultPanel files={results} messageZh="隐私信息清理完成，可以核对结果再下载。" messageEn="Privacy cleanup finished. Review before downloading." details={{files:results.length,resultKB:Number((total/1024).toFixed(1))}}/>}{error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{error}</p>}</div>}
