"use client";
import { PointerEvent,useEffect,useRef,useState } from "react";
import { downloadBlob } from "@/lib/tools/pdf-render-client";
type Box={x:number;y:number;w:number;h:number;mode:"blur"|"black"};
export default function ScreenshotRedactWorkbench(){
 const [file,setFile]=useState<File|null>(null),[src,setSrc]=useState(""),[boxes,setBoxes]=useState<Box[]>([]),[mode,setMode]=useState<"blur"|"black">("blur"),wrap=useRef<HTMLDivElement>(null),start=useRef<{x:number;y:number}|null>(null),current=useRef<Box|null>(null);
 useEffect(()=>()=>{if(src)URL.revokeObjectURL(src)},[src]);
 function choose(f:File){if(src)URL.revokeObjectURL(src);setFile(f);setSrc(URL.createObjectURL(f));setBoxes([])}
 function pt(e:PointerEvent){const r=wrap.current!.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
 async function exportImg(){if(!file)return;const bmp=await createImageBitmap(file),c=document.createElement("canvas");c.width=bmp.width;c.height=bmp.height;const x=c.getContext("2d")!;x.drawImage(bmp,0,0);for(const b of boxes){const X=Math.round(b.x*c.width),Y=Math.round(b.y*c.height),W=Math.round(b.w*c.width),H=Math.round(b.h*c.height);if(b.mode==="black"){x.fillStyle="#000";x.fillRect(X,Y,W,H)}else{const pad=20,sx=Math.max(0,X-pad),sy=Math.max(0,Y-pad),sw=Math.min(c.width-sx,W+pad*2),sh=Math.min(c.height-sy,H+pad*2),tmp=document.createElement("canvas");tmp.width=sw;tmp.height=sh;tmp.getContext("2d")!.drawImage(c,sx,sy,sw,sh,0,0,sw,sh);x.save();x.filter="blur(18px)";x.drawImage(tmp,sx,sy,sw,sh);x.restore()}}bmp.close?.();const out=await new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error("Export failed")),"image/png"));downloadBlob(out,"redacted-"+file.name.replace(/\.[^.]+$/,"")+".png")}
 return <div className="space-y-4"><label className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)choose(f)}}/><b>Upload screenshot</b><p className="mt-1 text-sm text-slate-500">Draw boxes over names, IDs, addresses, chats or account numbers.</p></label><div className="flex gap-2"><button onClick={()=>setMode("blur")} className={`rounded-full px-4 py-2 text-sm ${mode==="blur"?"bg-blue-600 text-white":"border"}`}>Blur</button><button onClick={()=>setMode("black")} className={`rounded-full px-4 py-2 text-sm ${mode==="black"?"bg-blue-600 text-white":"border"}`}>Black redact</button><button onClick={()=>setBoxes([])} className="rounded-full border px-4 py-2 text-sm">Clear</button></div>{src&&<div ref={wrap} className="relative mx-auto w-fit max-w-full touch-none overflow-hidden rounded-xl border" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const p=pt(e);start.current=p;current.current={x:p.x,y:p.y,w:0,h:0,mode};setBoxes(v=>[...v,current.current!])}} onPointerMove={e=>{if(!start.current||!current.current)return;const p=pt(e),s=start.current,b={x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y),mode} as Box;current.current=b;setBoxes(v=>[...v.slice(0,-1),b])}} onPointerUp={()=>{start.current=null;current.current=null}}><img src={src} alt="" className="block max-h-[680px] max-w-full select-none"/>{boxes.map((b,i)=><div key={i} className={`pointer-events-none absolute ${b.mode==="black"?"bg-black":"backdrop-blur-md bg-white/10"} border border-blue-500`} style={{left:`${b.x*100}%`,top:`${b.y*100}%`,width:`${b.w*100}%`,height:`${b.h*100}%`}}/>)}</div>}<button disabled={!file||!boxes.length} onClick={exportImg} className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white disabled:opacity-40">Export privacy-safe screenshot</button></div>
}
