"use client";
import NextImage from "next/image";
import {PointerEvent,useEffect,useRef,useState} from "react";
import FileDropzone from "@/components/tools/FileDropzone";
import ResultPanel from "@/components/tools/ResultPanel";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import type {ToolResultFile} from "@/lib/tools/types";
type Mode="blur"|"black"|"pixelate";type Box={x:number;y:number;w:number;h:number;mode:Mode};
export default function ScreenshotRedactWorkbench(){const{lang}=useLingxiLang();const zh=lang==="zh";const[files,setFiles]=useState<File[]>([]),[src,setSrc]=useState(""),[boxes,setBoxes]=useState<Box[]>([]),[mode,setMode]=useState<Mode>("blur"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<ToolResultFile[]>([]);const wrap=useRef<HTMLDivElement>(null),start=useRef<{x:number;y:number}|null>(null),current=useRef<Box|null>(null),file=files[0]||null;
 useEffect(()=>()=>{if(src)URL.revokeObjectURL(src)},[src]);function choose(next:File[]){if(src)URL.revokeObjectURL(src);setFiles(next);setBoxes([]);setResult([]);setError("");setSrc(next[0]?URL.createObjectURL(next[0]):"")}function pt(e:PointerEvent){const r=wrap.current!.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
 async function exportImg(){if(!file)return;setBusy(true);setError("");setResult([]);let bmp:ImageBitmap|null=null;try{bmp=await createImageBitmap(file);const cv=document.createElement("canvas");cv.width=bmp.width;cv.height=bmp.height;const ctx=cv.getContext("2d")!;ctx.drawImage(bmp,0,0);for(const b of boxes){const X=Math.round(b.x*cv.width),Y=Math.round(b.y*cv.height),W=Math.max(1,Math.round(b.w*cv.width)),H=Math.max(1,Math.round(b.h*cv.height));if(b.mode==="black"){ctx.fillStyle="#000";ctx.fillRect(X,Y,W,H)}else if(b.mode==="pixelate"){const block=Math.max(6,Math.min(30,Math.round(Math.min(W,H)/12))),tmp=document.createElement("canvas");tmp.width=Math.max(1,Math.ceil(W/block));tmp.height=Math.max(1,Math.ceil(H/block));tmp.getContext("2d")!.drawImage(cv,X,Y,W,H,0,0,tmp.width,tmp.height);ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,0,0,tmp.width,tmp.height,X,Y,W,H);ctx.restore()}else{const pad=20,sx=Math.max(0,X-pad),sy=Math.max(0,Y-pad),sw=Math.min(cv.width-sx,W+pad*2),sh=Math.min(cv.height-sy,H+pad*2),tmp=document.createElement("canvas");tmp.width=sw;tmp.height=sh;tmp.getContext("2d")!.drawImage(cv,sx,sy,sw,sh,0,0,sw,sh);ctx.save();ctx.filter="blur(18px)";ctx.drawImage(tmp,sx,sy,sw,sh);ctx.restore()}}const out=await new Promise<Blob>((res,rej)=>cv.toBlob(b=>b?res(b):rej(new Error("EXPORT_FAILED")),"image/png"));setResult([{name:"redacted-"+file.name.replace(/\.[^.]+$/,"")+".png",blob:out,mime:"image/png",size:out.size}]);cv.width=cv.height=1}catch(e){setError(e instanceof Error?e.message:String(e))}finally{bmp?.close?.();setBusy(false)}}
 const label=(z:string,e:string)=>zh?z:e;return <div className="space-y-4"><FileDropzone accept="image/*" files={files} onChange={choose} disabled={busy} kind="image" maxSizeMB={30}/><p className="text-sm text-[var(--lx-muted)]">{label("拖框遮住姓名、地址、证件号、聊天内容或账号信息；导出后遮挡会永久写入图片。","Draw boxes over sensitive content; redaction is permanently baked into the exported image.")}</p><div className="flex flex-wrap gap-2">{([["blur",label("模糊","Blur")],["pixelate",label("像素化","Pixelate")],["black",label("黑块","Black")]] as const).map(([v,n])=><button key={v} onClick={()=>setMode(v)} className={`rounded-full px-4 py-2 text-sm ${mode===v?"bg-[var(--lx-ink)] text-[var(--lx-bg)]":"border border-[var(--lx-line)]"}`}>{n}</button>)}<button disabled={!boxes.length} onClick={()=>setBoxes(v=>v.slice(0,-1))} className="rounded-full border border-[var(--lx-line)] px-4 py-2 text-sm disabled:opacity-40">{label("撤销上一框","Undo last")}</button><button onClick={()=>setBoxes([])} className="rounded-full border border-[var(--lx-line)] px-4 py-2 text-sm">{label("清空","Clear")}</button></div>
 {src&&<div ref={wrap} className="relative mx-auto w-fit max-w-full touch-none overflow-hidden rounded-xl border border-[var(--lx-line)]" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const p=pt(e);start.current=p;current.current={x:p.x,y:p.y,w:0,h:0,mode};setBoxes(v=>[...v,current.current!])}} onPointerMove={e=>{if(!start.current||!current.current)return;const p=pt(e),s=start.current,b={x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),w:Math.abs(p.x-s.x),h:Math.abs(p.y-s.y),mode} as Box;current.current=b;setBoxes(v=>[...v.slice(0,-1),b])}} onPointerUp={()=>{start.current=null;current.current=null}}><NextImage src={src} alt="" className="block max-h-[680px] max-w-full select-none" width={1600} height={1200} unoptimized/>{boxes.map((b,i)=><button type="button" title={label("点击删除这个框","Click to remove")} onClick={e=>{e.stopPropagation();setBoxes(v=>v.filter((_,j)=>j!==i))}} key={i} className={`absolute border-2 border-[var(--lx-line-strong)] ${b.mode==="black"?"bg-black":b.mode==="pixelate"?"bg-black/30":"backdrop-blur-md bg-white/10"}`} style={{left:`${b.x*100}%`,top:`${b.y*100}%`,width:`${b.w*100}%`,height:`${b.h*100}%`}}/>)}</div>}
 <button disabled={!file||!boxes.length||busy} onClick={exportImg} className="rounded-xl bg-[var(--lx-ink)] px-5 py-2.5 text-sm text-[var(--lx-bg)] disabled:opacity-40">{busy?label("正在生成…","Creating…"):label("生成隐私截图","Export redacted image")}</button>{!!result.length&&<ResultPanel files={result} messageZh="隐私截图已生成，可以核对后下载。" messageEn="Redacted image is ready for review."/>}{error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{error}</p>}</div>}
