"use client";
import { useState } from "react";
import PaidActionButton from "@/components/tools/PaidActionButton";
import { downloadBlob } from "@/lib/tools/pdf-render-client";
export default function SubtitleTranslateWorkbench(){
 const [text,setText]=useState(""),[target,setTarget]=useState("Simplified Chinese"),[busy,setBusy]=useState(false),[out,setOut]=useState(""),[error,setError]=useState("");
 async function run(q:string){setBusy(true);setError("");try{const r=await fetch("/api/ai/subtitle-translate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({quoteId:q,itemKey:"subtitle-0",targetLanguage:target,text})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Translation failed");setOut(d.text||"")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="space-y-4"><label className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><input type="file" accept=".srt,.vtt,text/plain" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(f)setText(await f.text())}}/><b>载入 SRT / VTT</b><p className="mt-1 text-sm text-slate-500">时间轴保持不变，只翻译字幕正文。</p></label><textarea value={text} onChange={e=>setText(e.target.value)} rows={12} className="w-full rounded-2xl border p-4 font-mono text-sm"/><label className="block text-sm">翻译成 <select value={target} onChange={e=>setTarget(e.target.value)} className="ml-2 rounded border px-3 py-2"><option>Simplified Chinese</option><option>Traditional Chinese</option><option>English</option><option>Japanese</option><option>Korean</option><option>Spanish</option><option>French</option><option>German</option></select></label>{busy?<button disabled className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white opacity-50">正在翻译…</button>:text.trim()?<PaidActionButton toolId="subtitle-translate" quantity={1} onPaid={run} label="查看本次翻译价格"/>:null}{out&&<><textarea value={out} readOnly rows={14} className="w-full rounded-2xl border p-4 font-mono text-sm"/><button onClick={()=>downloadBlob(new Blob([out],{type:"text/plain;charset=utf-8"}),"translated-subtitles.srt")} className="rounded-full bg-emerald-600 px-4 py-2 text-sm text-white">下载翻译字幕</button></>}{error&&<p className="text-sm text-rose-600">{error}</p>}</div>
}
