"use client";
import {useMemo,useState} from "react";
import ResultPanel from "@/components/tools/ResultPanel";
import {useLingxiLang,type LingxiLang} from "@/lib/lingxi-i18n";
import type {ToolResultFile} from "@/lib/tools/types";
type Cue={start:string;end:string;text:string};type C={load:string;paste:string;shift:string;prepare:string;ready:string;error:string};
const D:Record<LingxiLang,C>={zh:{load:"载入 SRT / VTT",paste:"也可以直接粘贴字幕文本。",shift:"整体时间偏移（毫秒）",prepare:"生成 SRT / VTT / TXT",ready:"字幕已经校正并生成三种导出格式。",error:"字幕处理没有完成"},en:{load:"Load SRT / VTT",paste:"You can also paste subtitle text.",shift:"Global shift (ms)",prepare:"Create SRT / VTT / TXT",ready:"Subtitle timeline corrected and export files are ready.",error:"Subtitle processing failed"},ja:{load:"SRT / VTT を読み込む",paste:"字幕を直接貼り付けできます。",shift:"全体オフセット（ms）",prepare:"SRT / VTT / TXT を生成",ready:"字幕を校正しました。",error:"字幕処理失敗"},ko:{load:"SRT / VTT 불러오기",paste:"자막을 붙여넣을 수 있습니다.",shift:"전체 이동(ms)",prepare:"SRT / VTT / TXT 생성",ready:"자막이 보정되었습니다.",error:"자막 처리 실패"},fr:{load:"Charger SRT / VTT",paste:"Vous pouvez coller le texte.",shift:"Décalage global (ms)",prepare:"Créer SRT / VTT / TXT",ready:"Sous-titres corrigés.",error:"Échec"},de:{load:"SRT / VTT laden",paste:"Text kann eingefügt werden.",shift:"Globale Verschiebung (ms)",prepare:"SRT / VTT / TXT",ready:"Untertitel korrigiert.",error:"Fehler"},es:{load:"Cargar SRT / VTT",paste:"También puedes pegar texto.",shift:"Desplazamiento global (ms)",prepare:"Crear SRT / VTT / TXT",ready:"Subtítulos corregidos.",error:"Error"},pt:{load:"Carregar SRT / VTT",paste:"Também pode colar texto.",shift:"Deslocamento global (ms)",prepare:"Criar SRT / VTT / TXT",ready:"Legendas corrigidas.",error:"Erro"},ar:{load:"تحميل SRT / VTT",paste:"يمكن لصق النص.",shift:"إزاحة عامة (ms)",prepare:"إنشاء SRT / VTT / TXT",ready:"تم تصحيح الترجمة.",error:"خطأ"}};
function parseTime(s:string){const p=s.trim().replace(",",".").split(":").map(Number);if(p.some(x=>!Number.isFinite(x)))return NaN;return p.length===3?p[0]*3600+p[1]*60+p[2]:p.length===2?p[0]*60+p[1]:NaN}
function fmt(sec:number,vtt=false){sec=Math.max(0,sec);const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=(sec%60).toFixed(3).padStart(6,"0");return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${s.replace(".",vtt?".":",")}`}
function parse(raw:string):Cue[]{const n=raw.replace(/^\uFEFF/,"").replace(/\r/g,"").replace(/^WEBVTT[^\n]*\n+/i,"").trim();if(!n)return[];return n.split(/\n\s*\n/).map(b=>{const l=b.split("\n").filter(Boolean),i=l.findIndex(x=>x.includes("-->"));if(i<0)return null;const p=l[i].split("-->");if(p.length!==2)return null;const a=p[0].trim().split(/\s+/)[0],z=p[1].trim().split(/\s+/)[0],text=l.slice(i+1).join("\n").trim(),x=parseTime(a),y=parseTime(z);return text&&Number.isFinite(x)&&Number.isFinite(y)&&y>=x?{start:a,end:z,text}:null}).filter(Boolean) as Cue[]}
export default function SubtitleWorkbench(){const{lang}=useLingxiLang(),c=D[lang]??D.en;const[raw,setRaw]=useState(""),[shift,setShift]=useState(0),[scale,setScale]=useState(1),[fromFps,setFromFps]=useState(0),[toFps,setToFps]=useState(0),[trimLines,setTrimLines]=useState(true),[error,setError]=useState(""),[results,setResults]=useState<ToolResultFile[]>([]);
 function prepare(){try{setError("");const cues=parse(raw);if(!cues.length)throw new Error("INVALID_SUBTITLE");const fpsFactor=fromFps>0&&toFps>0?fromFps/toFps:1,timingFactor=Math.max(.1,Math.min(10,scale))*fpsFactor;const moved=cues.map(x=>({startSec:parseTime(x.start)*timingFactor+shift/1000,endSec:parseTime(x.end)*timingFactor+shift/1000,text:trimLines?x.text.split("\n").map(v=>v.trim()).filter(Boolean).join("\n"):x.text})).filter(x=>x.text&&x.endSec>=x.startSec);const srt=moved.map((x,n)=>`${n+1}\n${fmt(x.startSec)} --> ${fmt(x.endSec)}\n${x.text}`).join("\n\n"),vtt="WEBVTT\n\n"+moved.map(x=>`${fmt(x.startSec,true)} --> ${fmt(x.endSec,true)}\n${x.text}`).join("\n\n"),txt=moved.map(x=>x.text).join("\n"),build=(name:string,text:string,mime:string):ToolResultFile=>{const blob=new Blob([text],{type:mime});return{name,blob,mime,size:blob.size}};setResults([build("subtitle.srt",srt,"application/x-subrip;charset=utf-8"),build("subtitle.vtt",vtt,"text/vtt;charset=utf-8"),build("subtitle.txt",txt,"text/plain;charset=utf-8")])}catch(e){setResults([]);setError(e instanceof Error?e.message:String(e))}}
 const count=useMemo(()=>parse(raw).length,[raw]);return <div className="space-y-4"><label onDragOver={e=>e.preventDefault()} onDrop={async e=>{e.preventDefault();const f=e.dataTransfer.files?.[0];if(f){setRaw(await f.text());setResults([])}}} className="block cursor-pointer rounded-2xl border border-dashed border-[var(--lx-line)] bg-[var(--lx-soft)] p-7 text-center"><input type="file" accept=".srt,.vtt,text/plain,text/vtt" className="hidden" onChange={async e=>{const f=e.target.files?.[0];if(f){setRaw(await f.text());setResults([])}}}/><b>{c.load}</b><p className="mt-1 text-sm text-[var(--lx-muted)]">{c.paste}</p></label><textarea rows={14} value={raw} onChange={e=>{setRaw(e.target.value);setResults([])}} className="w-full rounded-2xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-4 font-mono text-sm"/>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm text-[var(--lx-muted)]">{c.shift}<input type="number" value={shift} onChange={e=>setShift(Number(e.target.value)||0)} className="mt-1 w-full rounded-lg border border-[var(--lx-line)] bg-[var(--lx-panel)] px-3 py-2"/></label><label className="text-sm text-[var(--lx-muted)]">时间缩放 ×<input type="number" min=".1" max="10" step=".001" value={scale} onChange={e=>setScale(Number(e.target.value)||1)} className="mt-1 w-full rounded-lg border border-[var(--lx-line)] bg-[var(--lx-panel)] px-3 py-2"/></label><label className="text-sm text-[var(--lx-muted)]">原 FPS<input type="number" min="0" step=".001" value={fromFps} onChange={e=>setFromFps(Number(e.target.value)||0)} className="mt-1 w-full rounded-lg border border-[var(--lx-line)] bg-[var(--lx-panel)] px-3 py-2"/></label><label className="text-sm text-[var(--lx-muted)]">目标 FPS<input type="number" min="0" step=".001" value={toFps} onChange={e=>setToFps(Number(e.target.value)||0)} className="mt-1 w-full rounded-lg border border-[var(--lx-line)] bg-[var(--lx-panel)] px-3 py-2"/></label></div>
 <label className="flex items-center gap-2 text-sm text-[var(--lx-muted)]"><input type="checkbox" checked={trimLines} onChange={e=>setTrimLines(e.target.checked)}/>清理每条字幕首尾空格与空行</label>
 <button disabled={!raw.trim()} onClick={prepare} className="rounded-xl bg-[var(--lx-ink)] px-4 py-2.5 text-sm text-[var(--lx-bg)] disabled:opacity-40">{c.prepare}{count?` · ${count}`:""}</button>{!!results.length&&<ResultPanel files={results} messageZh={c.ready} messageEn={c.ready}/>} {error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{c.error} · {error}</p>}</div>}
