"use client";
import { useState } from "react";
import { transformText } from "@/lib/tools/shared/text";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {toolUiText} from "@/lib/tool-ui-i18n";
export default function TextWorkbench({ slug }: { slug: string }) {
 const{lang}=useLingxiLang();const t=(zh:string,en:string)=>toolUiText(lang,zh,en);
 const [input,setInput]=useState("");const [output,setOutput]=useState("");const [reverse,setReverse]=useState(false);const [notice,setNotice]=useState("");const encoding=slug.endsWith("encode-decode");
 function run(){try{setOutput(transformText(slug,input,reverse));setNotice(t("处理完成，原始输入仍保留。","Processing complete; the original input is preserved."));}catch{setOutput("");setNotice(t("无法处理：请检查编码是否完整、Base64是否为UTF-8文本，以及输入是否超过50万字符。","Could not process. Check that the encoding is complete, Base64 contains UTF-8 text, and input is under 500,000 characters."));}}
 return <div className="space-y-5"><p className="text-sm leading-7">{t("在浏览器本地处理，不上传文本。","Processed locally in your browser; text is not uploaded.")} {encoding?t("编码不等于加密；解码内容仅显示为文本，不会执行。","Encoding is not encryption; decoded content is displayed as text and never executed."):t("处理后先核对结果，再复制使用。","Review the result before copying or using it.")}</p><label className="block">{t("输入文本","Input text")}<textarea className="mt-2 min-h-48 w-full rounded-xl border bg-transparent p-4" value={input} maxLength={500001} onChange={event=>{setInput(event.target.value);setOutput("");setNotice("");}}/></label>{encoding&&<label className="block">{t("处理方向","Direction")}<select className="ml-3 rounded-lg border bg-transparent p-2" value={reverse?"decode":"encode"} onChange={event=>{setReverse(event.target.value==="decode");setOutput("");}}><option value="encode">{t("编码","Encode")}</option><option value="decode">{t("解码","Decode")}</option></select></label>}<button className="rounded-xl border px-5 py-3" onClick={run}>{t("开始处理","Start processing")}</button><label className="block">{t("处理结果","Result")}<textarea className="mt-2 min-h-40 w-full rounded-xl border bg-transparent p-4" value={output} readOnly/></label><button className="rounded-xl border px-5 py-3 disabled:opacity-50" disabled={!output} onClick={async()=>{try{await navigator.clipboard.writeText(output);setNotice(t("已复制结果。","Result copied."));}catch{setNotice(t("浏览器未允许复制，可选中结果手动复制。","The browser did not allow clipboard access. Select the result and copy it manually."));}}}>{t("复制结果","Copy result")}</button><p role="status">{notice}</p></div>;
}
