"use client";
import { useState } from "react";
import PaidActionButton from "@/components/tools/PaidActionButton";
import { downloadBlob } from "@/lib/tools/pdf-render-client";

function durationOf(file:File){return new Promise<number>((resolve,reject)=>{const el=document.createElement(file.type.startsWith("video/")?"video":"audio"),u=URL.createObjectURL(file),t=setTimeout(()=>{URL.revokeObjectURL(u);reject(new Error("Cannot read media duration."))},15000);el.preload="metadata";el.onloadedmetadata=()=>{clearTimeout(t);const d=el.duration;URL.revokeObjectURL(u);Number.isFinite(d)&&d>0?resolve(d):reject(new Error("Cannot read duration."))};el.onerror=()=>{clearTimeout(t);URL.revokeObjectURL(u);reject(new Error("Unsupported media format."))};el.src=u})}
export default function TranscriptionWorkbench({video=false}:{video?:boolean}){
 const [file,setFile]=useState<File|null>(null),[duration,setDuration]=useState(0),[lang,setLang]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState("");
 const minutes=duration?Math.max(1,Math.ceil(duration/60)):0,toolId=video?"video-transcription":"audio-transcription";
 async function choose(f:File){setFile(f);setDuration(0);setResult(null);setError("");try{setDuration(await durationOf(f))}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function run(quoteId:string){if(!file)return;setBusy(true);setError("");try{const fd=new FormData();fd.set("file",file,file.name);fd.set("quote_id",quoteId);fd.set("item_key","transcribe-0");fd.set("paid_minutes",String(minutes));fd.set("tool_id",toolId);if(lang)fd.set("language",lang);const r=await fetch("/api/ai/transcribe",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||"Transcription failed");setResult(d)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function dl(text:string,ext:string){downloadBlob(new Blob([text],{type:"text/plain;charset=utf-8"}),`${file?.name.replace(/\.[^.]+$/,"")||"transcript"}.${ext}`)}
 return <div className="space-y-4"><label className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><input type="file" accept={video?"video/*,audio/*":"audio/*"} className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)choose(f)}}/><b>{video?"上传视频 / 音频":"上传音频"}</b><p className="mt-1 text-sm text-slate-500">先在本地读取时长，付款确认后才上传到转写服务。</p></label>{duration>0&&<div className="rounded-xl bg-blue-50 p-3 text-sm text-blue-900">{Math.floor(duration/60)}分 {Math.round(duration%60)}秒 · 本次按 <b>{minutes} 分钟</b>计费</div>}<label className="block text-sm">语言提示（可选）<select value={lang} onChange={e=>setLang(e.target.value)} className="ml-2 rounded border px-3 py-2"><option value="">自动检测</option><option value="zh">中文</option><option value="en">英语</option><option value="ja">日语</option><option value="ko">韩语</option><option value="es">西班牙语</option><option value="fr">法语</option></select></label>{busy?<button disabled className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white opacity-50">正在转写…</button>:minutes>0?<PaidActionButton toolId={toolId} quantity={minutes} onPaid={run} label="查看本次转写价格"/>:null}<p className="text-xs text-slate-500">当前单次上传限制 25MB；大视频先用灵犀场视频工具提取或压缩音频。</p>{result&&<div className="space-y-3"><textarea rows={14} value={result.text||""} readOnly className="w-full rounded-2xl border p-4 text-sm"/><div className="flex flex-wrap gap-3"><button onClick={()=>dl(result.text||"","txt")} className="rounded-full border px-4 py-2 text-sm">TXT</button>{result.srt&&<button onClick={()=>dl(result.srt,"srt")} className="rounded-full border px-4 py-2 text-sm">SRT</button>}{result.vtt&&<button onClick={()=>dl(result.vtt,"vtt")} className="rounded-full border px-4 py-2 text-sm">VTT</button>}</div></div>}{error&&<p className="text-sm text-rose-600">{error}</p>}</div>
}
