"use client";
import { useRef, useState } from "react";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {toolUiText} from "@/lib/tool-ui-i18n";
export default function VideoToolkitWorkbench(){
 const{lang}=useLingxiLang();const t=(zh:string,en:string)=>toolUiText(lang,zh,en);
 const [file,setFile]=useState<File|null>(null);const [mode,setMode]=useState<"compress"|"audio"|"trim">("compress");const [start,setStart]=useState(0);const [duration,setDuration]=useState(30);const [busy,setBusy]=useState(false);const [stage,setStage]=useState("");const [url,setUrl]=useState("");const ff=useRef<any>(null);
 async function run(){if(!file)return;setBusy(true);setStage(t("正在加载本地媒体引擎…","Loading local media engine…"));try{const [{FFmpeg},{fetchFile,toBlobURL}]=await Promise.all([import("@ffmpeg/ffmpeg"),import("@ffmpeg/util")]);const f=new FFmpeg();ff.current=f;f.on("progress",({progress}:{progress:number})=>setStage(`${t("处理中…","Working…")} ${Math.round(progress*100)}%`));await f.load({coreURL:await toBlobURL("/media/ffmpeg-0.12.10/ffmpeg-core.js","text/javascript"),wasmURL:await toBlobURL("/media/ffmpeg-0.12.10/ffmpeg-core.wasm","application/wasm")});const ext=file.name.split(".").pop()||"mp4",input=`input.${ext}`;await f.writeFile(input,await fetchFile(file));let out="output.mp4",args:string[]=[];if(mode==="compress")args=["-i",input,"-c:v","libx264","-preset","veryfast","-crf","28","-c:a","aac","-b:a","128k",out];if(mode==="audio"){out="output.mp3";args=["-i",input,"-vn","-c:a","libmp3lame","-b:a","192k",out];}if(mode==="trim")args=["-ss",String(start),"-i",input,"-t",String(duration),"-c:v","libx264","-preset","veryfast","-c:a","aac",out];await f.exec(args);const data=await f.readFile(out);const bytes=data instanceof Uint8Array?data:new TextEncoder().encode(String(data));const c=new Uint8Array(bytes.length);c.set(bytes);if(url)URL.revokeObjectURL(url);setUrl(URL.createObjectURL(new Blob([c.buffer],{type:mode==="audio"?"audio/mpeg":"video/mp4"})));setStage(t("处理完成","Processing complete"));f.terminate();ff.current=null;}finally{setBusy(false);}}
 function cancel(){try{ff.current?.terminate();}catch{}ff.current=null;setBusy(false);setStage(t("已取消处理","Processing cancelled"));}
 const modes=[["compress",t("压缩视频","Compress video")],["audio",t("提取 MP3","Extract MP3")],["trim",t("截取片段","Trim clip")]] as const;
 return <div className="space-y-4"><label className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><input type="file" accept="video/*,audio/*" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{t("上传视频或音频","Upload video or audio")}</b><p className="mt-1 text-sm text-slate-500">{t("较大文件会占用较多内存，建议先从 500MB 以下开始。","Large files use more memory; start with files under 500 MB.")}</p></label><div className="flex flex-wrap gap-2">{modes.map(([v,n])=><button key={v} onClick={()=>setMode(v)} className={`rounded-full px-4 py-2 text-sm ${mode===v?"bg-blue-600 text-white":"border border-slate-200"}`}>{n}</button>)}</div>{mode==="trim"&&<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">{t("开始秒数","Start second")}<input type="number" value={start} onChange={e=>setStart(Number(e.target.value)||0)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"/></label><label className="text-sm">{t("截取时长（秒）","Duration (seconds)")}<input type="number" value={duration} onChange={e=>setDuration(Number(e.target.value)||1)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2"/></label></div>}<div className="flex gap-3"><button disabled={!file||busy} onClick={run} className="rounded-full bg-blue-600 px-5 py-2.5 text-sm text-white disabled:opacity-40">{t("开始处理","Start processing")}</button>{busy&&<button onClick={cancel} className="rounded-full border border-rose-200 px-5 py-2.5 text-sm text-rose-600">{t("取消","Cancel")}</button>}</div>{stage&&<p className="text-sm text-slate-500">{stage}</p>}{url&&<a href={url} download={mode==="audio"?"lingxifield-audio.mp3":"lingxifield-video.mp4"} className="inline-flex rounded-full bg-emerald-600 px-5 py-2.5 text-sm text-white">{t("下载结果","Download result")}</a>}</div>;
}
