"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import FileDropzone from "@/components/tools/FileDropzone";
import PaidActionButton from "@/components/tools/PaidActionButton";
import RemoteMediaImporter from "@/components/tools/RemoteMediaImporter";
import {useLingxiLang,type LingxiLang} from "@/lib/lingxi-i18n";

type MediaItem={file:File;duration:number;width:number;height:number;key:string};
type Box={x:number;y:number;w:number;h:number};
type Output={name:string;url:string};
type Failure={name:string;reason:string};
type FfmpegHandle={terminate:()=>void};
type C={hero:string;lead:string;rights:string;x:string;y:string;w:string;h:string;billing:string;working:string;cancel:string;price:string;done:string;download:string;truth:string;metaFail:string;formatFail:string;partial:string};
const D:Record<LingxiLang,C>={
 zh:{hero:"上传视频，框出固定水印区域，付款后在浏览器本地处理",lead:"支持单个或批量视频，同一批默认使用同一水印位置。视频本体由浏览器本地 FFmpeg 处理；支付只解锁本次处理额度。",rights:"请使用你拥有权利的原始视频、平台官方导出文件或直接媒体链接。本工具不会绕过平台访问控制。",x:"左侧 X",y:"顶部 Y",w:"宽度",h:"高度",billing:"合计计费分钟",working:"正在处理…",cancel:"取消当前处理",price:"查看本次去水印价格",done:"处理完成",download:"下载",truth:"适用于固定位置的文字、贴纸或水印区域。移动水印、穿过人物面部或复杂动态遮挡需要逐帧视频修复模型，本工具不会把固定区域滤镜伪装成 AI 无痕修复。",metaFail:"无法读取视频信息",formatFail:"当前浏览器无法读取该视频格式",partial:"部分视频失败，已保留成功结果"},
 en:{hero:"Upload a video, mark a fixed watermark area, then process locally after payment",lead:"Single or batch video is supported. One batch uses the same area by default. Video bytes stay in browser-local FFmpeg; payment only unlocks this processing allowance.",rights:"Use original videos, official platform exports or direct media URLs that you have rights to use. This tool does not bypass platform access controls.",x:"Left X",y:"Top Y",w:"Width",h:"Height",billing:"Billable minutes",working:"Processing…",cancel:"Cancel current process",price:"See watermark-removal price",done:"Processing finished",download:"Download",truth:"Designed for fixed-position text, stickers or watermark regions. Moving watermarks and complex occlusion require frame-by-frame restoration; this tool does not present a fixed-area filter as AI seamless restoration.",metaFail:"Could not read video metadata",formatFail:"This browser cannot read the video format",partial:"Some videos failed. Successful results were kept."},
 ja:{hero:"動画をアップロードし固定水印領域を指定、支払い後にブラウザ内で処理",lead:"単体・一括に対応。同じバッチは同じ領域を使います。動画本体はブラウザ内 FFmpeg で処理します。",rights:"権利のある原本、公式書き出し、直接メディア URL を使用してください。アクセス制御は回避しません。",x:"左 X",y:"上 Y",w:"幅",h:"高さ",billing:"課金分数",working:"処理中…",cancel:"現在の処理をキャンセル",price:"料金を見る",done:"処理完了",download:"ダウンロード",truth:"固定位置の文字・ステッカー・水印向けです。移動水印や複雑な遮蔽はフレーム単位の修復が必要です。",metaFail:"動画情報を読み取れません",formatFail:"このブラウザでは動画形式を読めません",partial:"一部の動画に失敗しました。成功結果は保持されています。"},
 ko:{hero:"영상을 업로드하고 고정 워터마크 영역을 지정한 뒤 결제 후 브라우저에서 처리",lead:"단일/일괄 영상을 지원합니다. 같은 일괄 작업은 같은 영역을 사용합니다. 영상은 브라우저 FFmpeg에서 처리됩니다.",rights:"사용 권한이 있는 원본, 공식 내보내기 또는 직접 미디어 URL을 사용하세요. 접근 제어를 우회하지 않습니다.",x:"왼쪽 X",y:"위 Y",w:"너비",h:"높이",billing:"과금 분",working:"처리 중…",cancel:"현재 처리 취소",price:"가격 보기",done:"처리 완료",download:"다운로드",truth:"고정 위치의 텍스트·스티커·워터마크에 적합합니다. 이동 워터마크나 복잡한 가림은 프레임 단위 복원이 필요합니다.",metaFail:"영상 정보를 읽을 수 없습니다",formatFail:"브라우저가 영상 형식을 읽을 수 없습니다",partial:"일부 영상이 실패했습니다. 성공 결과는 유지했습니다."},
 fr:{hero:"Importez la vidéo, marquez une zone fixe puis traitez localement après paiement",lead:"Vidéo unique ou lot. Une même zone est utilisée par défaut pour le lot. La vidéo est traitée dans FFmpeg local au navigateur.",rights:"Utilisez des vidéos dont vous détenez les droits, des exports officiels ou des URL média directes. Aucun contrôle d’accès n’est contourné.",x:"Gauche X",y:"Haut Y",w:"Largeur",h:"Hauteur",billing:"Minutes facturées",working:"Traitement…",cancel:"Annuler le traitement",price:"Voir le prix",done:"Traitement terminé",download:"Télécharger",truth:"Adapté aux textes, autocollants ou filigranes fixes. Les filigranes mobiles et occultations complexes demandent une restauration image par image.",metaFail:"Impossible de lire les informations vidéo",formatFail:"Ce navigateur ne peut pas lire ce format vidéo",partial:"Certaines vidéos ont échoué. Les résultats réussis sont conservés."},
 de:{hero:"Video hochladen, festen Wasserzeichenbereich markieren und nach Zahlung lokal verarbeiten",lead:"Einzel- und Stapelvideos werden unterstützt. Ein Stapel nutzt standardmäßig denselben Bereich. Die Verarbeitung läuft in Browser-FFmpeg.",rights:"Nur eigene Videos, offizielle Exporte oder direkte Medien-URLs verwenden. Zugriffskontrollen werden nicht umgangen.",x:"Links X",y:"Oben Y",w:"Breite",h:"Höhe",billing:"Abrechenbare Minuten",working:"Verarbeitung…",cancel:"Aktuelle Verarbeitung abbrechen",price:"Preis anzeigen",done:"Verarbeitung abgeschlossen",download:"Herunterladen",truth:"Für fest positionierte Texte, Sticker oder Wasserzeichen. Bewegte Wasserzeichen und komplexe Überdeckungen brauchen Frame-für-Frame-Restaurierung.",metaFail:"Videoinformationen konnten nicht gelesen werden",formatFail:"Browser kann dieses Videoformat nicht lesen",partial:"Einige Videos sind fehlgeschlagen. Erfolgreiche Ergebnisse bleiben erhalten."},
 es:{hero:"Sube el vídeo, marca una zona fija y procesa localmente tras pagar",lead:"Admite uno o varios vídeos. Un lote usa la misma zona por defecto. El vídeo se procesa con FFmpeg dentro del navegador.",rights:"Usa vídeos propios, exportaciones oficiales o URLs directas con derechos de uso. No se evitan controles de acceso.",x:"Izquierda X",y:"Arriba Y",w:"Ancho",h:"Alto",billing:"Minutos facturables",working:"Procesando…",cancel:"Cancelar proceso",price:"Ver precio",done:"Proceso terminado",download:"Descargar",truth:"Pensado para texto, pegatinas o marcas fijas. Marcas móviles y oclusiones complejas requieren restauración cuadro a cuadro.",metaFail:"No se pudo leer la información del vídeo",formatFail:"El navegador no puede leer este formato",partial:"Algunos vídeos fallaron. Se conservaron los resultados correctos."},
 pt:{hero:"Envie o vídeo, marque uma área fixa e processe localmente após o pagamento",lead:"Suporta vídeo único ou lote. Um lote usa a mesma área por padrão. O vídeo é processado no FFmpeg do navegador.",rights:"Use vídeos próprios, exportações oficiais ou URLs diretas com direito de uso. O acesso da plataforma não é contornado.",x:"Esquerda X",y:"Topo Y",w:"Largura",h:"Altura",billing:"Minutos cobrados",working:"Processando…",cancel:"Cancelar processamento",price:"Ver preço",done:"Processamento concluído",download:"Baixar",truth:"Indicado para textos, adesivos ou marcas fixas. Marcas móveis e oclusões complexas exigem restauração quadro a quadro.",metaFail:"Não foi possível ler as informações do vídeo",formatFail:"O navegador não consegue ler este formato",partial:"Alguns vídeos falharam. Os resultados concluídos foram preservados."},
 ar:{hero:"ارفع الفيديو وحدد منطقة علامة مائية ثابتة ثم عالج محليًا بعد الدفع",lead:"يدعم فيديو واحدًا أو دفعة. تستخدم الدفعة المنطقة نفسها افتراضيًا. تتم المعالجة عبر FFmpeg داخل المتصفح.",rights:"استخدم فيديوهات تملك حقوقها أو صادرات رسمية أو روابط وسائط مباشرة. لا يتم تجاوز قيود الوصول.",x:"يسار X",y:"أعلى Y",w:"العرض",h:"الارتفاع",billing:"الدقائق المحسوبة",working:"جارٍ المعالجة…",cancel:"إلغاء المعالجة الحالية",price:"عرض السعر",done:"اكتملت المعالجة",download:"تنزيل",truth:"مناسب للنصوص أو الملصقات أو العلامات الثابتة. العلامات المتحركة والحجب المعقد يحتاجان إلى ترميم إطار بإطار.",metaFail:"تعذر قراءة معلومات الفيديو",formatFail:"لا يستطيع المتصفح قراءة هذا التنسيق",partial:"فشلت بعض الفيديوهات وتم الاحتفاظ بالنتائج الناجحة."}
};
function mediaMetaOf(file:File,msg:string,formatMsg:string){return new Promise<{duration:number;width:number;height:number}>((resolve,reject)=>{const el=document.createElement("video"),u=URL.createObjectURL(file),cleanup=()=>{clearTimeout(timer);URL.revokeObjectURL(u);el.removeAttribute("src");el.load()},timer=setTimeout(()=>{cleanup();reject(new Error(msg))},15000);el.preload="metadata";el.onloadedmetadata=()=>{const duration=el.duration,width=el.videoWidth,height=el.videoHeight;cleanup();Number.isFinite(duration)&&duration>0&&width>0&&height>0?resolve({duration,width,height}):reject(new Error(msg))};el.onerror=()=>{cleanup();reject(new Error(formatMsg))};el.src=u})}
export default function VideoWatermarkWorkbench(){
 const{lang}=useLingxiLang();const c=D[lang]??D.en;
 const[items,setItems]=useState<MediaItem[]>([]),[preview,setPreview]=useState(""),[box,setBox]=useState<Box>({x:72,y:78,w:24,h:14}),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[results,setResults]=useState<Output[]>([]),[failures,setFailures]=useState<Failure[]>([]),[error,setError]=useState("");
 const ff=useRef<FfmpegHandle|null>(null),resultUrls=useRef<string[]>([]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);for(const u of resultUrls.current)URL.revokeObjectURL(u);try{ff.current?.terminate()}catch{}},[preview]);
 function clearResults(){for(const u of resultUrls.current)URL.revokeObjectURL(u);resultUrls.current=[];setResults([]);setFailures([])}
 async function hydrate(files:File[]){setError("");const next:MediaItem[]=[];for(const file of files.slice(0,10)){try{const m=await mediaMetaOf(file,c.metaFail,c.formatFail);next.push({file,duration:m.duration,width:m.width,height:m.height,key:`${file.name}-${file.size}-${file.lastModified}`})}catch(e){setError(e instanceof Error?e.message:String(e))}}setItems(next);clearResults();if(preview)URL.revokeObjectURL(preview);setPreview(next[0]?URL.createObjectURL(next[0].file):"")}
 async function addRemote(file:File){await hydrate([...items.map(x=>x.file),file])}
 const units=useMemo(()=>items.reduce((n,x)=>n+Math.max(1,Math.ceil(x.duration/60)),0),[items]);
 async function startLocalPaid(quoteId:string,item:MediaItem,index:number){const r=await fetch("/api/tools/local-paid/job",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"start",quoteId,toolId:"video-watermark-remover",itemKey:`video-${index}`,units:Math.max(1,Math.ceil(item.duration/60))})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"PAID_JOB_START_FAILED");return String(d.jobId)}
 async function finish(jobId:string,result:Record<string,unknown>){await fetch("/api/tools/local-paid/job",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",jobId,result})})}
 async function fail(jobId:string,reason:string){await fetch("/api/tools/local-paid/job",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"fail",jobId,error:reason})}).catch(()=>{})}
 async function processOne(item:MediaItem,index:number,quoteId:string){
  const jobId=await startLocalPaid(quoteId,item,index);let f:InstanceType<(typeof import("@ffmpeg/ffmpeg"))["FFmpeg"]>|null=null;
  try{
   const [{FFmpeg},{fetchFile,toBlobURL}]=await Promise.all([import("@ffmpeg/ffmpeg"),import("@ffmpeg/util")]);f=new FFmpeg();ff.current=f;f.on("progress",({progress}:{progress:number})=>setProgress(`${index+1}/${items.length} · ${Math.round(progress*100)}%`));
   await f.load({coreURL:await toBlobURL("/media/ffmpeg-0.12.10/ffmpeg-core.js","text/javascript"),wasmURL:await toBlobURL("/media/ffmpeg-0.12.10/ffmpeg-core.wasm","application/wasm")});
   const ext=item.file.name.split(".").pop()||"mp4",input=`input-${index}.${ext}`,output=`output-${index}.mp4`;await f.writeFile(input,await fetchFile(item.file));
   const w=item.width,h=item.height,px=Math.round(w*box.x/100),py=Math.round(h*box.y/100),pw=Math.max(8,Math.round(w*box.w/100)),ph=Math.max(8,Math.round(h*box.h/100));
   const code=await f.exec(["-i",input,"-vf",`delogo=x=${px}:y=${py}:w=${pw}:h=${ph}:show=0`,"-c:v","libx264","-preset","veryfast","-crf","20","-c:a","aac","-b:a","160k",output]);
   if(code!==0)throw new Error(`FFMPEG_EXIT_${code}`);
   const data=await f.readFile(output),bytes=data instanceof Uint8Array?data:new TextEncoder().encode(String(data)),copy=new Uint8Array(bytes.length);copy.set(bytes);if(copy.byteLength===0)throw new Error("EMPTY_VIDEO_RESULT");
   const url=URL.createObjectURL(new Blob([copy.buffer],{type:"video/mp4"}));resultUrls.current.push(url);await finish(jobId,{outputBytes:copy.byteLength,durationSeconds:item.duration,localProcessing:true});return{name:item.file.name,url};
  }catch(e){await fail(jobId,e instanceof Error?e.message:String(e));throw e}
  finally{try{f?.terminate()}catch{}if(ff.current===f)ff.current=null}
 }
 async function run(quoteId:string){
  if(!items.length)return;setBusy(true);setError("");setProgress(c.working);clearResults();const out:Output[]=[],bad:Failure[]=[];
  try{
   for(let i=0;i<items.length;i++){try{const r=await processOne(items[i],i,quoteId);out.push(r);setResults([...out])}catch(e){bad.push({name:items[i].file.name,reason:e instanceof Error?e.message:String(e)});setFailures([...bad])}}
   setProgress(c.done);if(bad.length)setError(c.partial);
  }finally{setBusy(false)}
 }
 function cancel(){try{ff.current?.terminate()}catch{}ff.current=null;setBusy(false);setProgress(c.cancel)}
 return <div className="space-y-5">
  <div className="rounded-2xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-5"><div className="text-lg font-semibold text-[var(--lx-ink)]">{c.hero}</div><p className="mt-2 text-sm leading-6 text-[var(--lx-muted)]">{c.lead}</p></div>
  <FileDropzone accept="video/*,.mp4,.mov,.m4v,.webm,.mkv" multiple maxFiles={10} maxSizeMB={500} files={items.map(x=>x.file)} onChange={hydrate} disabled={busy} kind="media"/>
  <RemoteMediaImporter acceptKind="video" onImported={addRemote} disabled={busy}/>
  <p className="text-xs leading-5 text-[var(--lx-muted)]">{c.rights}</p>
  {preview&&<div className="relative mx-auto max-w-3xl overflow-hidden rounded-2xl bg-black"><video src={preview} controls className="w-full"/><div className="pointer-events-none absolute border-2 border-white/70 bg-white/10" style={{left:`${box.x}%`,top:`${box.y}%`,width:`${box.w}%`,height:`${box.h}%`}}/></div>}
  {items.length>0&&<><div className="grid gap-3 sm:grid-cols-4">{([[c.x,"x"],[c.y,"y"],[c.w,"w"],[c.h,"h"]] as const).map(([name,key])=><label key={key} className="text-sm text-[var(--lx-muted)]">{name} %<input type="range" min={0} max={key==="w"||key==="h"?50:95} value={box[key]} onChange={e=>setBox(v=>({...v,[key]:Number(e.target.value)}))} className="mt-2 w-full"/><span className="text-xs text-[var(--lx-faint)]">{box[key]}%</span></label>)}</div><div className="rounded-xl border border-[var(--lx-line)] bg-[var(--lx-soft)] p-4 text-sm text-[var(--lx-muted)]">{items.length} · {c.billing}: <b className="text-[var(--lx-ink)]">{units}</b></div></>}
  <div className="flex flex-wrap gap-3">{busy?<><button disabled className="rounded-xl bg-[var(--lx-ink)] px-5 py-2.5 text-sm text-[var(--lx-bg)] opacity-50">{c.working}</button><button onClick={cancel} className="rounded-xl border border-[var(--lx-danger)] px-5 py-2.5 text-sm text-[var(--lx-danger)]">{c.cancel}</button></>:units>0?<PaidActionButton toolId="video-watermark-remover" quantity={units} metadata={{videos:items.length}} onPaid={run} label={c.price}/>:null}</div>
  {progress&&<p className="text-sm text-[var(--lx-muted)]">{progress}</p>}
  {results.length>0&&<div className="grid gap-4 sm:grid-cols-2">{results.map(r=><div key={r.url} className="rounded-2xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3"><video src={r.url} controls className="w-full rounded-xl"/><div className="mt-3 flex items-center justify-between gap-2"><span className="truncate text-sm text-[var(--lx-muted)]">{r.name}</span><a href={r.url} download={`clean-${r.name.replace(/\.[^.]+$/,".mp4")}`} className="shrink-0 rounded-xl bg-[var(--lx-ink)] px-4 py-2 text-sm text-[var(--lx-bg)]">{c.download}</a></div></div>)}</div>}
  {failures.length>0&&<div className="rounded-xl border border-[var(--lx-danger)] bg-[var(--lx-panel)] p-3 text-xs text-[var(--lx-danger)]">{failures.map(x=><div key={x.name}>{x.name} · {x.reason}</div>)}</div>}
  {error&&<p role="alert" className="text-sm text-[var(--lx-danger)]">{error}</p>}
  <div className="rounded-xl border border-[var(--lx-line)] bg-[var(--lx-soft)] p-3 text-xs leading-5 text-[var(--lx-muted)]">{c.truth}</div>
 </div>;
}
