"use client";

import {useState} from "react";
import {fetchFile} from "@ffmpeg/util";
import FileDropzone from "@/components/tools/FileDropzone";
import ResultPanel from "@/components/tools/ResultPanel";
import type {ToolResultFile} from "@/lib/tools/types";
import {createFfmpegRuntime} from "@/lib/tools/media/runtime";
import {useLingxiLang,type LingxiLang} from "@/lib/lingxi-i18n";

export type VideoEffectMode="reverse"|"loop"|"stop-motion";
type C={speed:string;mute:string;loops:string;interval:string;fps:string;boomerang:string;privacy:string;run:string;working:string;done:string;error:string;seconds:string};
const D:Record<LingxiLang,C>={
 zh:{speed:"倒放速度",mute:"静音输出",loops:"循环次数",interval:"每隔多少秒取一帧",fps:"播放帧率",boomerang:"加上倒放，做成往返效果",privacy:"免费。本地处理，视频不会上传。",run:"开始处理",working:"正在处理…",done:"处理完成",error:"这个视频暂时没处理成功，请换一个文件或稍后再试。",seconds:"秒"},
 en:{speed:"Reverse speed",mute:"Mute output",loops:"Loop count",interval:"Take one frame every",fps:"Playback rate",boomerang:"Add a reverse pass for a back-and-forth effect",privacy:"Free. Processed on your device; the video is not uploaded.",run:"Start",working:"Processing…",done:"Done",error:"This video could not be processed. Try another file or try again later.",seconds:"sec"},
 ja:{speed:"逆再生速度",mute:"音声なし",loops:"ループ回数",interval:"フレーム間隔",fps:"再生フレームレート",boomerang:"逆再生を追加して往復再生にする",privacy:"無料。端末内で処理し、動画はアップロードしません。",run:"処理を開始",working:"処理中…",done:"完了",error:"この動画を処理できませんでした。別のファイルでお試しください。",seconds:"秒"},
 ko:{speed:"역재생 속도",mute:"음소거",loops:"반복 횟수",interval:"프레임 추출 간격",fps:"재생 프레임률",boomerang:"역재생을 이어 붙여 왕복 효과 만들기",privacy:"무료입니다. 기기에서 처리하며 영상은 업로드되지 않습니다.",run:"처리 시작",working:"처리 중…",done:"완료",error:"이 영상을 처리하지 못했습니다. 다른 파일로 다시 시도해 주세요.",seconds:"초"},
 fr:{speed:"Vitesse inversée",mute:"Couper le son",loops:"Nombre de boucles",interval:"Prendre une image toutes les",fps:"Fréquence de lecture",boomerang:"Ajouter le retour inversé",privacy:"Gratuit. Traitement sur votre appareil, sans envoi de la vidéo.",run:"Commencer",working:"Traitement…",done:"Terminé",error:"Cette vidéo n’a pas pu être traitée. Essayez un autre fichier.",seconds:"s"},
 de:{speed:"Rückwärtsgeschwindigkeit",mute:"Ohne Ton",loops:"Wiederholungen",interval:"Ein Bild alle",fps:"Bildrate",boomerang:"Rücklauf für Hin-und-zurück-Effekt anhängen",privacy:"Kostenlos. Verarbeitung auf deinem Gerät; das Video wird nicht hochgeladen.",run:"Starten",working:"Wird verarbeitet…",done:"Fertig",error:"Dieses Video konnte nicht verarbeitet werden. Versuche eine andere Datei.",seconds:"Sek."},
 es:{speed:"Velocidad inversa",mute:"Silenciar",loops:"Número de repeticiones",interval:"Tomar un fotograma cada",fps:"Fotogramas por segundo",boomerang:"Añadir retorno inverso",privacy:"Gratis. Se procesa en tu dispositivo y el vídeo no se sube.",run:"Empezar",working:"Procesando…",done:"Listo",error:"No se pudo procesar este vídeo. Prueba con otro archivo.",seconds:"s"},
 pt:{speed:"Velocidade reversa",mute:"Sem áudio",loops:"Número de repetições",interval:"Capturar um quadro a cada",fps:"Taxa de reprodução",boomerang:"Adicionar retorno reverso",privacy:"Grátis. Processado no seu dispositivo; o vídeo não é enviado.",run:"Começar",working:"Processando…",done:"Concluído",error:"Não foi possível processar este vídeo. Tente outro arquivo.",seconds:"s"},
 ar:{speed:"سرعة التشغيل العكسي",mute:"بدون صوت",loops:"عدد التكرارات",interval:"التقاط إطار كل",fps:"معدل التشغيل",boomerang:"إضافة رجوع عكسي لتأثير ذهاب وإياب",privacy:"مجاني. تتم المعالجة على جهازك ولا يتم رفع الفيديو.",run:"ابدأ المعالجة",working:"جارٍ المعالجة…",done:"تم",error:"تعذر معالجة هذا الفيديو. جرّب ملفاً آخر.",seconds:"ث"}
};
function copyBytes(data:Uint8Array|string){const b=data instanceof Uint8Array?data:new TextEncoder().encode(String(data));const c=new Uint8Array(b.byteLength);c.set(b);return c}
export default function VideoEffectsWorkbench({mode}:{mode:VideoEffectMode}){
 const{lang}=useLingxiLang();const c=D[lang]??D.en;
 const[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[stage,setStage]=useState(""),[error,setError]=useState(""),[results,setResults]=useState<ToolResultFile[]>([]);
 const[mute,setMute]=useState(false),[reverseSpeed,setReverseSpeed]=useState(1),[loops,setLoops]=useState(2),[frameInterval,setFrameInterval]=useState(.4),[playbackFps,setPlaybackFps]=useState(12),[boomerang,setBoomerang]=useState(false);
 async function run(){if(!files.length||busy)return;setBusy(true);setError("");setResults([]);try{const output:ToolResultFile[]=[];for(let index=0;index<files.length;index++){const file=files[index];setStage(`${index+1}/${files.length}`);const ffmpeg=await createFfmpegRuntime(p=>setStage(`${index+1}/${files.length} · ${Math.round(p*100)}%`));try{const ext=file.name.split(".").pop()||"mp4",input=`input-${index}.${ext}`,out=`output-${index}.mp4`;await ffmpeg.writeFile(input,await fetchFile(file));let args:string[]=[];if(mode==="reverse"){const speed=Math.max(.5,Math.min(2,reverseSpeed)),vf=speed===1?"reverse":`reverse,setpts=${(1/speed).toFixed(4)}*PTS`;args=mute?["-i",input,"-vf",vf,"-an","-c:v","libx264","-preset","veryfast","-crf","21","-movflags","+faststart",out]:["-i",input,"-vf",vf,"-af",speed===1?"areverse":`areverse,atempo=${speed.toFixed(3)}`,"-c:v","libx264","-preset","veryfast","-crf","21","-c:a","aac","-b:a","160k","-movflags","+faststart",out]}
 if(mode==="loop"){const count=Math.max(2,Math.min(20,loops));args=["-stream_loop",String(count-1),"-i",input,"-c:v","libx264","-preset","veryfast","-crf","21","-c:a","aac","-b:a","160k","-movflags","+faststart",out]}
 if(mode==="stop-motion"){const interval=Math.max(.1,Math.min(5,frameInterval)),fps=Math.max(2,Math.min(30,playbackFps)),sample=`fps=1/${interval},setpts=N/(${fps}*TB)`;args=boomerang?["-i",input,"-filter_complex",`[0:v]${sample},split[v1][v2];[v2]reverse[v2r];[v1][v2r]concat=n=2:v=1:a=0[v]`,"-map","[v]","-an","-r",String(fps),"-c:v","libx264","-preset","veryfast","-crf","21","-pix_fmt","yuv420p","-movflags","+faststart",out]:["-i",input,"-vf",sample,"-an","-r",String(fps),"-c:v","libx264","-preset","veryfast","-crf","21","-pix_fmt","yuv420p","-movflags","+faststart",out]}
 const code=await ffmpeg.exec(args);if(code!==0)throw new Error("VIDEO_PROCESS_FAILED");const data=copyBytes(await ffmpeg.readFile(out)),blob=new Blob([data.buffer],{type:"video/mp4"});output.push({name:file.name.replace(/\.[^.]+$/,"")+`-${mode}.mp4`,blob,mime:"video/mp4",size:blob.size})}finally{try{ffmpeg.terminate()}catch{}}}setResults(output);setStage(c.done)}catch{setStage("");setError(c.error)}finally{setBusy(false)}}
 return <div dir={lang==='ar'?'rtl':'ltr'} className="space-y-4"><FileDropzone accept="video/*" multiple append maxFiles={10} maxSizeMB={500} files={files} onChange={n=>{setFiles(n);setResults([]);setError("")}} disabled={busy} kind="media"/>
 {mode==="reverse"&&<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">{c.speed} {reverseSpeed.toFixed(2)}×<input type="range" min={.5} max={2} step={.05} value={reverseSpeed} onChange={e=>setReverseSpeed(Number(e.target.value))} className="mt-2 w-full"/></label><label className="mt-6 flex items-center gap-2 text-sm"><input type="checkbox" checked={mute} onChange={e=>setMute(e.target.checked)}/>{c.mute}</label></div>}
 {mode==="loop"&&<label className="block text-sm">{c.loops}<input type="number" min={2} max={20} value={loops} onChange={e=>setLoops(Number(e.target.value)||2)} className="mt-1 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-2"/></label>}
 {mode==="stop-motion"&&<div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">{c.interval}<select value={frameInterval} onChange={e=>setFrameInterval(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-2">{[.2,.4,.6,.8,1,1.5,2,3].map(v=><option key={v} value={v}>{v} {c.seconds}</option>)}</select></label><label className="text-sm">{c.fps}<select value={playbackFps} onChange={e=>setPlaybackFps(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-2">{[6,8,10,12,15,20,24].map(v=><option key={v} value={v}>{v} fps</option>)}</select></label><label className="mt-7 flex items-center gap-2 text-sm"><input type="checkbox" checked={boomerang} onChange={e=>setBoomerang(e.target.checked)}/>{c.boomerang}</label></div>}
 <p className="text-xs leading-5 text-[var(--lx-muted)]">{c.privacy}</p>{files.length>0&&!busy&&<button type="button" onClick={run} className="rounded-xl bg-[var(--lx-ink)] px-5 py-3 text-sm font-medium text-[var(--lx-bg)]">{c.run}</button>}{busy&&<p className="text-sm text-[var(--lx-muted)]">{stage||c.working}</p>}{!busy&&stage&&<p className="text-sm text-[var(--lx-muted)]">{stage}</p>}{results.length>0&&<ResultPanel files={results}/>} {error&&<p className="text-sm text-[var(--lx-danger)]">{error}</p>}</div>
}
