import type {LingxiLang} from '@/lib/lingxi-i18n';
const langs=['zh','en','ja','ko','fr','de','es','pt','ar'];
const rows:Record<string,string[]>={
moneyAdmin:["管理后台","Admin dashboard","管理画面","관리자 대시보드","Tableau de bord admin","Admin-Dashboard","Panel de administración","Painel administrativo","لوحة الإدارة"],
waitingConfirm:["待确认退款","Awaiting confirmation","返金の確認待ち","환불 확인 대기","En attente de confirmation","Bestätigung ausstehend","Pendiente de confirmación","Aguardando confirmação","بانتظار التأكيد"],
cancelWithdrawal:["取消提现","Cancel withdrawal","払い戻しを取り消す","인출 취소","Annuler le retrait","Auszahlung stornieren","Cancelar retiro","Cancelar saque","إلغاء السحب"],
cancelRefund:["取消退款","Cancel refund","返金を取り消す","환불 취소","Annuler le remboursement","Erstattung stornieren","Cancelar reembolso","Cancelar reembolso","إلغاء الاسترداد"],
cancelConfirm:["取消这笔申请并将金额恢复到余额？","Cancel this request and return the amount to your balance?","申請を取り消して金額を残高に戻しますか？","신청을 취소하고 금액을 잔액으로 돌릴까요?","Annuler cette demande et restituer le montant au solde ?","Antrag stornieren und Betrag zum Guthaben zurückgeben?","¿Cancelar la solicitud y devolver el importe al saldo?","Cancelar a solicitação e devolver o valor ao saldo?","هل تريد إلغاء الطلب وإعادة المبلغ إلى رصيدك؟"],
cancelled:["已取消，金额已恢复到余额。","Cancelled. The amount is back in your balance.","取り消しました。金額は残高に戻りました。","취소되었습니다. 금액이 잔액으로 돌아왔습니다.","Annulé. Le montant a été restitué au solde.","Storniert. Der Betrag ist wieder im Guthaben.","Cancelado. El importe volvió a tu saldo.","Cancelado. O valor voltou ao saldo.","تم الإلغاء وإعادة المبلغ إلى رصيدك."],
confirmSubmit:["确认退款","Confirm refund","返金を確定","환불 확인","Confirmer le remboursement","Erstattung bestätigen","Confirmar reembolso","Confirmar reembolso","تأكيد الاسترداد"],
tooLate:["申请已提交或状态已改变，无法取消。请刷新记录查看最新进度。","The request was submitted or its status changed and cannot be cancelled. Refresh your history.","申請は送信済みか状態が変わったため取り消せません。履歴を更新してください。","신청이 제출되었거나 상태가 변경되어 취소할 수 없습니다. 내역을 새로고침하세요.","La demande a été envoyée ou a changé de statut ; elle ne peut plus être annulée. Actualisez l’historique.","Der Antrag wurde übermittelt oder geändert und kann nicht storniert werden. Verlauf aktualisieren.","La solicitud se envió o cambió de estado y no se puede cancelar. Actualiza el historial.","A solicitação foi enviada ou mudou de estado e não pode ser cancelada. Atualize o histórico.","أُرسل الطلب أو تغيرت حالته ولا يمكن إلغاؤه. حدّث السجل."],
 withdrawal:['提现进度','Withdrawal progress','払い戻しの進捗','인출 진행 상황','Suivi du retrait','Auszahlungsstatus','Estado del retiro','Status do saque','حالة السحب'],
 refund:['退款进度','Refund progress','返金の進捗','환불 진행 상황','Suivi du remboursement','Erstattungsstatus','Estado del reembolso','Status do reembolso','حالة الاسترداد'],
 topup:['充值已到账','Top-up received','チャージ完了','충전 완료','Recharge reçue','Aufladung eingegangen','Recarga recibida','Recarga recebida','تم استلام الشحن'],
 payment:['支付成功','Payment confirmed','支払い確認済み','결제 확인됨','Paiement confirmé','Zahlung bestätigt','Pago confirmado','Pagamento confirmado','تم تأكيد الدفع'],
 requested:["申请已保存，尚未提交支付渠道。请核对金额后确认退款，也可以取消。","Request saved and not submitted to the provider. Check the amount, then confirm or cancel.","申請を保存しました。決済サービスには未送信です。金額を確認して確定するか、取り消してください。","신청이 저장되었으며 아직 결제수단에 제출되지 않았습니다. 금액을 확인하고 확정하거나 취소하세요.","Demande enregistrée, non envoyée au prestataire. Vérifiez le montant, puis confirmez ou annulez.","Antrag gespeichert und noch nicht übermittelt. Betrag prüfen und bestätigen oder stornieren.","Solicitud guardada y no enviada al proveedor. Revisa el importe y confirma o cancela.","Solicitação salva e ainda não enviada ao provedor. Confira o valor e confirme ou cancele.","تم حفظ الطلب ولم يُرسل إلى مزود الدفع. تحقق من المبلغ ثم أكد الطلب أو ألغِه."],
 providerFunds:["商户退款资金不足，款项尚未退回。申请金额仍保留，请联系支持；商户补足资金后将按原单重试。","Merchant refund funds are insufficient; the refund has not been sent. Your amount remains on hold. Contact support; the same request will retry once funds are replenished.","加盟店の返金資金が不足しており、まだ返金されていません。金額は確保されています。サポートに連絡してください。入金後、同じ申請を再試行します。","판매자의 환불 자금이 부족하여 아직 환불되지 않았습니다. 신청 금액은 보류 중입니다. 지원팀에 문의하세요. 자금 보충 후 같은 신청을 재시도합니다.","Les fonds du marchand sont insuffisants ; le remboursement n’a pas été envoyé. Le montant reste réservé. Contactez l’assistance ; la même demande sera réessayée après réapprovisionnement.","Die Erstattungsmittel des Händlers reichen nicht aus; die Erstattung wurde noch nicht ausgezahlt. Der Betrag bleibt reserviert. Kontaktieren Sie den Support. Nach Auffüllung wird derselbe Antrag erneut versucht.","El comercio no tiene fondos suficientes para el reembolso y aún no se ha enviado. El importe sigue reservado. Contacta con soporte; se reintentará la misma solicitud al reponer los fondos.","O comerciante não tem fundos suficientes para o reembolso, que ainda não foi enviado. O valor permanece reservado. Contate o suporte; a mesma solicitação será tentada após a reposição dos fundos.","أموال التاجر المخصصة للاسترداد غير كافية ولم يُرسل المبلغ بعد. يبقى مبلغك محجوزًا. تواصل مع الدعم؛ ستُعاد محاولة الطلب نفسه بعد إضافة الأموال."],
 providerAction:["这笔退款需要人工处理，款项尚未退回。请联系支持并提供申请编号，无需重复申请。","This refund needs manual review and has not been sent. Contact support with the request reference; do not submit another request.","この返金には担当者の確認が必要で、まだ返金されていません。申請番号を添えてサポートに連絡してください。再申請は不要です。","이 환불은 담당자 확인이 필요하며 아직 완료되지 않았습니다. 신청 번호와 함께 지원팀에 문의하세요. 다시 신청하지 마세요.","Ce remboursement nécessite une intervention et n’a pas été envoyé. Contactez l’assistance avec la référence ; ne renvoyez pas la demande.","Diese Erstattung erfordert eine manuelle Prüfung und wurde noch nicht ausgezahlt. Kontaktieren Sie den Support mit der Antragsnummer; stellen Sie keinen neuen Antrag.","Este reembolso requiere revisión manual y aún no se ha enviado. Contacta con soporte e indica la referencia; no repitas la solicitud.","Este reembolso precisa de análise manual e ainda não foi enviado. Contate o suporte com a referência; não repita a solicitação.","يتطلب هذا الاسترداد مراجعة يدوية ولم يُرسل بعد. تواصل مع الدعم وأرسل رقم الطلب؛ لا تقدم طلبًا آخر."],
 processing:['正在与原支付渠道确认结果。申请金额暂时冻结，请勿重复申请。','Confirming with the original provider. The requested amount is on hold; do not submit again.','元の決済サービスに確認中です。申請額は確保されています。重複申請は不要です。','원 결제수단에 확인 중입니다. 신청 금액은 보류되어 있으므로 중복 신청하지 마세요.','Confirmation auprès du prestataire. Le montant est réservé ; ne renvoyez pas la demande.','Bestätigung beim Anbieter läuft. Betrag ist reserviert; bitte nicht erneut beantragen.','Confirmando con el proveedor. El importe está reservado; no repitas la solicitud.','Confirmando com o provedor. O valor está reservado; não repita a solicitação.','جارٍ التأكيد مع المزود. المبلغ محجوز مؤقتًا؛ لا ترسل طلبًا مكررًا.'],
 completed:['支付渠道已确认退款完成，请查阅原支付账户的入账记录。','The provider confirmed the refund. Check the original payment account for settlement.','決済サービスが返金完了を確認しました。元の支払口座を確認してください。','결제수단에서 환불 완료를 확인했습니다. 원 결제 계좌 내역을 확인하세요.','Le prestataire a confirmé le remboursement. Vérifiez le compte de paiement d’origine.','Anbieter bestätigt die Erstattung. Bitte ursprüngliches Zahlungskonto prüfen.','El proveedor confirmó el reembolso. Comprueba la cuenta de pago original.','O provedor confirmou o reembolso. Confira a conta de pagamento original.','أكد المزود الاسترداد. تحقق من سجل حساب الدفع الأصلي.'],
 failed:['本次申请未完成。请查看余额和申请记录后重试，或联系支持。','This request was not completed. Check your balance and history before retrying, or contact support.','申請は完了していません。残高と履歴を確認するかサポートへご連絡ください。','신청이 완료되지 않았습니다. 잔액과 내역을 확인하거나 지원팀에 문의하세요.','Demande non aboutie. Vérifiez solde et historique ou contactez l’assistance.','Antrag nicht abgeschlossen. Guthaben und Verlauf prüfen oder Support kontaktieren.','Solicitud no completada. Revisa saldo e historial o contacta con soporte.','Solicitação não concluída. Confira saldo e histórico ou contate o suporte.','لم يكتمل الطلب. تحقق من الرصيد والسجل أو تواصل مع الدعم.'],
 legacy:['旧退款申请仍在等待处理，金额保留在退款冻结余额中。可从详情继续原路退款。','This earlier refund is still pending; its amount remains on hold. Continue the original-payment refund from the details.','以前の返金申請は保留中です。金額は確保されています。詳細から返金を続行できます。','이전 환불 신청이 대기 중이며 금액은 보류 중입니다. 상세에서 환불을 이어가세요.','Cette ancienne demande reste en attente et son montant est réservé. Continuez depuis le détail.','Der frühere Antrag wartet noch; der Betrag ist reserviert. Über die Details fortsetzen.','La solicitud anterior sigue pendiente y el importe está reservado. Continúa desde los detalles.','A solicitação anterior está pendente e o valor reservado. Continue pelos detalhes.','طلب الاسترداد السابق قيد الانتظار والمبلغ محجوز. تابع من التفاصيل.'],
 notSaved:['申请未保存成功，余额未因本次操作冻结。请稍后重新申请。','The request could not be saved. No funds were held for this attempt. Please try again later.','申請を保存できませんでした。今回の操作で残高は確保されていません。後でもう一度お試しください。','신청을 저장하지 못했습니다. 이번 시도로 잔액은 보류되지 않았습니다. 잠시 후 다시 신청하세요.','La demande n’a pas pu être enregistrée. Aucun montant n’a été réservé pour cet essai. Réessayez plus tard.','Der Antrag konnte nicht gespeichert werden. Für diesen Versuch wurde kein Guthaben reserviert. Bitte später erneut versuchen.','No se pudo guardar la solicitud. No se retuvo saldo por este intento. Inténtalo más tarde.','Não foi possível salvar a solicitação. Nenhum saldo foi reservado nesta tentativa. Tente novamente mais tarde.','تعذر حفظ الطلب. لم يُحجز رصيد لهذه المحاولة. يرجى المحاولة لاحقًا.'],
 unavailable:['暂时无法完成，请稍后重试。你可以在记录中核对是否已提交。','Temporarily unavailable. Check your history before retrying.','一時的に利用できません。履歴を確認してから再試行してください。','일시적으로 이용할 수 없습니다. 재시도 전 내역을 확인하세요.','Indisponible temporairement. Vérifiez l’historique avant de réessayer.','Vorübergehend nicht verfügbar. Vor erneutem Versuch Verlauf prüfen.','No disponible temporalmente. Revisa el historial antes de reintentar.','Indisponível no momento. Confira o histórico antes de tentar novamente.','غير متاح مؤقتًا. تحقق من السجل قبل إعادة المحاولة.'],
 all:['查看全部通知','View all notifications','すべての通知','모든 알림 보기','Toutes les notifications','Alle Mitteilungen','Ver todas las notificaciones','Ver todas as notificações','عرض كل الإشعارات'],
 details:['查看进度','View progress','進捗を見る','진행 상황 보기','Voir le suivi','Status ansehen','Ver progreso','Ver progresso','عرض التقدم'],
 refresh:['刷新进度','Refresh progress','進捗を更新','진행 상황 새로고침','Actualiser','Status aktualisieren','Actualizar','Atualizar','تحديث الحالة'],
 legacyTitle:['此前的退款申请','Earlier refund requests','以前の返金申請','이전 환불 신청','Demandes antérieures','Frühere Erstattungsanträge','Solicitudes anteriores','Solicitações anteriores','طلبات الاسترداد السابقة'],
 migrate:['继续原路退款','Continue refund','返金を続行','환불 계속하기','Poursuivre le remboursement','Erstattung fortsetzen','Continuar reembolso','Continuar reembolso','متابعة الاسترداد'],
 confirm:['确认将这笔申请继续退回原支付方式？不会重复冻结金额。','Continue this refund to the original payment method? The amount will not be held twice.','元の支払い方法への返金を続行しますか？二重に確保されません。','원 결제수단으로 환불을 계속할까요? 금액은 이중으로 보류되지 않습니다.','Poursuivre vers le moyen d’origine ? Le montant ne sera pas réservé deux fois.','Erstattung fortsetzen? Der Betrag wird nicht doppelt reserviert.','¿Continuar al método original? No se reservará el importe dos veces.','Continuar ao método original? O valor não será reservado duas vezes.','متابعة الاسترداد للوسيلة الأصلية؟ لن يُحجز المبلغ مرتين.'],
 reference:['申请编号','Request reference','申請番号','신청 번호','Référence','Antragsnummer','Referencia','Referência','رقم الطلب'],
 empty:['暂无通知','No notifications','通知はありません','알림 없음','Aucune notification','Keine Mitteilungen','Sin notificaciones','Sem notificações','لا توجد إشعارات'],
 loading:['正在读取…','Loading…','読み込み中…','불러오는 중…','Chargement…','Wird geladen…','Cargando…','Carregando…','جارٍ التحميل…'],
 read:['标为已读','Mark as read','既読にする','읽음으로 표시','Marquer comme lu','Als gelesen markieren','Marcar como leído','Marcar como lido','تحديد كمقروء'],
 login:['请先登录后查看','Sign in to view','ログインして表示','로그인 후 확인','Connectez-vous','Bitte anmelden','Inicia sesión','Entre na conta','سجل الدخول للعرض'],
 insufficient:['金额超过当前可退本金，请刷新余额后重试。','Amount exceeds current refundable principal. Refresh and try again.','現在の返金可能元本を超えています。更新してください。','현재 환불 가능 원금을 초과합니다. 새로고침하세요.','Montant supérieur au principal remboursable. Actualisez.','Betrag übersteigt verfügbares Kapital. Bitte aktualisieren.','Supera el principal reembolsable. Actualiza.','Valor acima do principal reembolsável. Atualize.','المبلغ يتجاوز الأصل القابل للاسترداد. حدّث الرصيد.'],
};
export function moneyText(lang:string,key:string){return rows[key]?.[Math.max(0,langs.indexOf(lang))]||rows.unavailable[Math.max(0,langs.indexOf(lang))];}
export function moneyError(lang:string,code:string){return moneyText(lang,code==='WITHDRAWAL_SAVE_FAILED'?'notSaved':code==='CANCELLATION_NOT_AVAILABLE'||code==='WITHDRAWAL_CLOSED'?'tooLate':code==='LOGIN_REQUIRED'?'login':/INSUFFICIENT|LIMIT|INVALID.*AMOUNT/.test(code)?'insufficient':code==='ACTIVE_REQUEST_EXISTS'?'processing':'unavailable');}
export function moneyNotice(lang:string,kind:'withdrawal'|'refund'|'payment'|'topup',status:string,currency:string,minor:number,legacy=false){
 const amount=new Intl.NumberFormat(langs.includes(lang)?lang:'en',{style:'currency',currency:currency==='USD'?'USD':'CNY'}).format(minor/100);
 const state=status==='cancelled'?'cancelled':legacy&&['requested','approved'].includes(status)?'legacy':status==='completed'?'completed':['failed','rejected','released','cancelled'].includes(status)?'failed':status==='processing'?'processing':'requested';
 return {title:`${moneyText(lang,kind)} · ${amount}`,body:kind==='payment'||kind==='topup'?amount:moneyText(lang,state)};
}
