import type {LingxiLang} from '@/lib/lingxi-i18n';
const langs=['zh','en','ja','ko','fr','de','es','pt','ar'];
const rows:Record<string,string[]>={
 withdrawal:['提现进度','Withdrawal progress','払い戻しの進捗','인출 진행 상황','Suivi du retrait','Auszahlungsstatus','Estado del retiro','Status do saque','حالة السحب'],
 refund:['退款进度','Refund progress','返金の進捗','환불 진행 상황','Suivi du remboursement','Erstattungsstatus','Estado del reembolso','Status do reembolso','حالة الاسترداد'],
 topup:['充值已到账','Top-up received','チャージ完了','충전 완료','Recharge reçue','Aufladung eingegangen','Recarga recibida','Recarga recebida','تم استلام الشحن'],
 payment:['支付成功','Payment confirmed','支払い確認済み','결제 확인됨','Paiement confirmé','Zahlung bestätigt','Pago confirmado','Pagamento confirmado','تم تأكيد الدفع'],
 requested:['申请已保存，等待向原支付渠道提交。','Request saved; awaiting submission to the original payment provider.','申請を保存しました。元の決済サービスへの送信を待っています。','신청이 저장되었으며 원 결제수단으로 전송을 기다립니다.','Demande enregistrée, en attente d’envoi au prestataire d’origine.','Antrag gespeichert; Übermittlung an den ursprünglichen Zahlungsanbieter steht aus.','Solicitud guardada, pendiente de envío al proveedor original.','Solicitação salva, aguardando envio ao provedor original.','تم حفظ الطلب وبانتظار إرساله لمزود الدفع الأصلي.'],
 providerFunds:['支付渠道当前无法完成退款，申请金额仍安全保留；系统会在条件恢复后继续原单重试。','The payment provider cannot complete the refund right now. The amount remains safely on hold and the same refund will retry when conditions recover.','決済サービスが現在返金を完了できません。金額は安全に確保され、条件回復後に同じ返金を再試行します。','결제 제공자가 현재 환불을 완료할 수 없습니다. 금액은 안전하게 보류되며 조건이 회복되면 동일 환불을 재시도합니다.','Le prestataire ne peut pas terminer le remboursement pour le moment. Le montant reste réservé et la même demande sera réessayée lorsque la situation sera rétablie.','Der Zahlungsanbieter kann die Erstattung derzeit nicht abschließen. Der Betrag bleibt sicher reserviert und derselbe Vorgang wird später erneut versucht.','El proveedor no puede completar el reembolso ahora. El importe permanece reservado y se reintentará la misma solicitud cuando se restablezcan las condiciones.','O provedor não consegue concluir o reembolso agora. O valor permanece reservado e a mesma solicitação será tentada novamente quando as condições forem restabelecidas.','يتعذر على مزود الدفع إكمال الاسترداد حاليًا. يبقى المبلغ محجوزًا بأمان وستتم إعادة محاولة الطلب نفسه عند استعادة الظروف المناسبة.'],
 processing:['正在与原支付渠道确认结果。申请金额暂时冻结，请勿重复申请。','Confirming with the original provider. The requested amount is on hold; do not submit again.','元の決済サービスに確認中です。申請額は確保されています。重複申請は不要です。','원 결제수단에 확인 중입니다. 신청 금액은 보류되어 있으므로 중복 신청하지 마세요.','Confirmation auprès du prestataire. Le montant est réservé ; ne renvoyez pas la demande.','Bestätigung beim Anbieter läuft. Betrag ist reserviert; bitte nicht erneut beantragen.','Confirmando con el proveedor. El importe está reservado; no repitas la solicitud.','Confirmando com o provedor. O valor está reservado; não repita a solicitação.','جارٍ التأكيد مع المزود. المبلغ محجوز مؤقتًا؛ لا ترسل طلبًا مكررًا.'],
 completed:['支付渠道已确认退款完成，请查阅原支付账户的入账记录。','The provider confirmed the refund. Check the original payment account for settlement.','決済サービスが返金完了を確認しました。元の支払口座を確認してください。','결제수단에서 환불 완료를 확인했습니다. 원 결제 계좌 내역을 확인하세요.','Le prestataire a confirmé le remboursement. Vérifiez le compte de paiement d’origine.','Anbieter bestätigt die Erstattung. Bitte ursprüngliches Zahlungskonto prüfen.','El proveedor confirmó el reembolso. Comprueba la cuenta de pago original.','O provedor confirmou o reembolso. Confira a conta de pagamento original.','أكد المزود الاسترداد. تحقق من سجل حساب الدفع الأصلي.'],
 failed:['本次申请未完成。请查看余额和申请记录后重试，或联系支持。','This request was not completed. Check your balance and history before retrying, or contact support.','申請は完了していません。残高と履歴を確認するかサポートへご連絡ください。','신청이 완료되지 않았습니다. 잔액과 내역을 확인하거나 지원팀에 문의하세요.','Demande non aboutie. Vérifiez solde et historique ou contactez l’assistance.','Antrag nicht abgeschlossen. Guthaben und Verlauf prüfen oder Support kontaktieren.','Solicitud no completada. Revisa saldo e historial o contacta con soporte.','Solicitação não concluída. Confira saldo e histórico ou contate o suporte.','لم يكتمل الطلب. تحقق من الرصيد والسجل أو تواصل مع الدعم.'],
 legacy:['旧退款申请仍在等待处理，金额保留在退款冻结余额中。可从详情继续原路退款。','This earlier refund is still pending; its amount remains on hold. Continue the original-payment refund from the details.','以前の返金申請は保留中です。金額は確保されています。詳細から返金を続行できます。','이전 환불 신청이 대기 중이며 금액은 보류 중입니다. 상세에서 환불을 이어가세요.','Cette ancienne demande reste en attente et son montant est réservé. Continuez depuis le détail.','Der frühere Antrag wartet noch; der Betrag ist reserviert. Über die Details fortsetzen.','La solicitud anterior sigue pendiente y el importe está reservado. Continúa desde los detalles.','A solicitação anterior está pendente e o valor reservado. Continue pelos detalhes.','طلب الاسترداد السابق قيد الانتظار والمبلغ محجوز. تابع من التفاصيل.'],
 unavailable:['暂时无法完成，请稍后重试。你可以在记录中核对是否已提交。','Temporarily unavailable. Check your history before retrying.','一時的に利用できません。履歴を確認してから再試行してください。','일시적으로 이용할 수 없습니다. 재시도 전 내역을 확인하세요.','Indisponible temporairement. Vérifiez l’historique avant de réessayer.','Vorübergehend nicht verfügbar. Vor erneutem Versuch Verlauf prüfen.','No disponible temporalmente. Revisa el historial antes de reintentar.','Indisponível no momento. Confira o histórico antes de tentar novamente.','غير متاح مؤقتًا. تحقق من السجل قبل إعادة المحاولة.'],
 all:['查看全部通知','View all notifications','すべての通知','모든 알림 보기','Toutes les notifications','Alle Mitteilungen','Ver todas las notificaciones','Ver todas as notificações','عرض كل الإشعارات'],
 details:['查看进度','View progress','進捗を見る','진행 상황 보기','Voir le suivi','Status ansehen','Ver progreso','Ver progresso','عرض التقدم'],
 refresh:['刷新进度','Refresh progress','進捗を更新','진행 상황 새로고침','Actualiser','Status aktualisieren','Actualizar','Atualizar','تحديث الحالة'],
 legacyTitle:['此前的退款申请','Earlier refund requests','以前の返金申請','이전 환불 신청','Demandes antérieures','Frühere Erstattungsanträge','Solicitudes anteriores','Solicitações anteriores','طلبات الاسترداد السابقة'],
 migrate:['继续原路退款','Continue refund','返金を続行','환불 계속하기','Poursuivre le remboursement','Erstattung fortsetzen','Continuar reembolso','Continuar reembolso','متابعة الاسترداد'],
 confirm:['确认将这笔申请继续退回原支付方式？不会重复冻结金额。','Continue this refund to the original payment method? The amount will not be held twice.','元の支払い方法への返金を続行しますか？二重に確保されません。','원 결제수단으로 환불을 계속할까요? 금액은 이중으로 보류되지 않습니다.','Poursuivre vers le moyen d’origine ? Le montant ne sera pas réservé deux fois.','Erstattung fortsetzen? Der Betrag wird nicht doppelt reserviert.','¿Continuar al método original? No se reservará el importe dos veces.','Continuar ao método original? O valor não será reservado duas vezes.','متابعة الاسترداد للوسيلة الأصلية؟ لن يُحجز المبلغ مرتين.'],
 reference:['申请编号','Request reference','申請番号','신청 번호','Référence','Antragsnummer','Referencia','Referência','رقم الطلب'],
 empty:['暂无通知','No notifications','通知はありません','알림 없음','Aucune notification','Keine Mitteilungen','Sin notificaciones','Sem notificações','لا توجد إشعارات'],
 loading:['正在读取…','Loading…','読み込み中…','불러오는 중…','Chargement…','Wird geladen…','Cargando…','Carregando…','جارٍ التحميل…'],
 read:['标为已读','Mark as read','既読にする','읽음으로 표시','Marquer comme lu','Als gelesen markieren','Marcar como leído','Marcar como lido','تحديد كمقروء'],
 login:['请先登录后查看','Sign in to view','ログインして表示','로그인 후 확인','Connectez-vous','Bitte anmelden','Inicia sesión','Entre na conta','سجل الدخول للعرض'],
 insufficient:['金额超过当前可退本金，请刷新余额后重试。','Amount exceeds current refundable principal. Refresh and try again.','現在の返金可能元本を超えています。更新してください。','현재 환불 가능 원금을 초과합니다. 새로고침하세요.','Montant supérieur au principal remboursable. Actualisez.','Betrag übersteigt verfügbares Kapital. Bitte aktualisieren.','Supera el principal reembolsable. Actualiza.','Valor acima do principal reembolsável. Atualize.','المبلغ يتجاوز الأصل القابل للاسترداد. حدّث الرصيد.'],
};
export function moneyText(lang:string,key:string){return rows[key]?.[Math.max(0,langs.indexOf(lang))]||rows.unavailable[Math.max(0,langs.indexOf(lang))];}
export function moneyError(lang:string,code:string){return moneyText(lang,code==='LOGIN_REQUIRED'?'login':/INSUFFICIENT|LIMIT|INVALID.*AMOUNT/.test(code)?'insufficient':code==='ACTIVE_REQUEST_EXISTS'?'processing':'unavailable');}
export function moneyNotice(lang:string,kind:'withdrawal'|'refund'|'payment'|'topup',status:string,currency:string,minor:number,legacy=false){
 const amount=new Intl.NumberFormat(langs.includes(lang)?lang:'en',{style:'currency',currency:currency==='USD'?'USD':'CNY'}).format(minor/100);
 const state=legacy&&['requested','approved'].includes(status)?'legacy':status==='completed'?'completed':['failed','rejected','released','cancelled'].includes(status)?'failed':status==='processing'?'processing':'requested';
 return {title:`${moneyText(lang,kind)} · ${amount}`,body:kind==='payment'||kind==='topup'?amount:moneyText(lang,state)};
}
