import type {Metadata} from "next";
import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import {usdBalanceProducts} from "@/lib/usd-products";
import LxText from "@/components/LxText";
export const metadata:Metadata={title:"PayPal｜灵犀场余额",description:"Use PayPal to top up the LINGXIFIELD SASI USD balance. USD remains USD and is not converted into CNY."};
export default function Page(){const packs=usdBalanceProducts.slice(0,6);return <><Nav/><main className="mx-auto max-w-5xl px-6 py-24">
 <p className="text-sm text-[var(--lx-faint)]">PayPal · USD</p>
 <h1 className="mt-3 text-3xl font-semibold"><LxText zh="充值灵犀场余额" en="Top up your LINGXIFIELD balance" ja="LINGXIFIELD残高をチャージ" ko="LINGXIFIELD 잔액 충전" fr="Recharger le solde LINGXIFIELD" de="LINGXIFIELD-Guthaben aufladen" es="Recargar saldo LINGXIFIELD" pt="Recarregar saldo LINGXIFIELD" ar="اشحن رصيد LINGXIFIELD"/></h1>
 <p className="mt-4 text-sm leading-7 text-[var(--lx-muted)]"><LxText zh="一个余额可用于全部 SASI。美元充值按原值进入 USD 余额，不换算成人民币；你连接的智能服务费用由对应服务商直接收取。" en="One balance works across all SASI. USD top-ups are credited at face value and are not converted into CNY. Connected intelligence services bill you directly." ja="1つの残高をすべてのSASIで利用できます。USDは同額でUSD残高に反映され、CNYには換算されません。接続した知能サービスの料金は各サービス事業者から直接請求されます。" ko="하나의 잔액을 모든 SASI에서 사용할 수 있습니다. USD 충전은 그대로 USD 잔액에 반영되며 CNY로 환산되지 않습니다. 연결한 지능형 서비스 요금은 해당 서비스 제공업체가 직접 청구합니다." fr="Un seul solde fonctionne pour tous les SASI. Les recharges USD sont créditées à leur valeur nominale, sans conversion en CNY. Les services intelligents connectés vous facturent directement." de="Ein Guthaben gilt für alle SASI. USD-Aufladungen werden zum Nennwert gutgeschrieben und nicht in CNY umgerechnet. Verbundene Intelligenzdienste rechnen direkt mit Ihnen ab." es="Un solo saldo funciona para todos los SASI. Las recargas en USD se acreditan por su valor nominal y no se convierten a CNY. Los servicios inteligentes conectados te cobran directamente." pt="Um único saldo funciona em todos os SASI. As recargas em USD são creditadas pelo valor nominal e não são convertidas em CNY. Os serviços inteligentes ligados cobram diretamente ao utilizador." ar="رصيد واحد يعمل عبر جميع خدمات SASI. تُضاف شحنات USD بقيمتها الاسمية ولا تُحوّل إلى CNY، وتقوم خدمات الذكاء المتصلة بالفوترة مباشرة."/></p>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{packs.map(p=><Link key={p.id} href={`/checkout-usd?productId=${p.id}`} className="rounded-2xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-5"><b className="text-2xl">${p.amountUsd}</b><span className="mt-2 block text-sm text-[var(--lx-muted)]">USD balance</span></Link>)}</div>
 </main><Footer/></>}
