import type {LingxiLang} from '@/lib/lingxi-i18n';
const langs: LingxiLang[]=['zh','en','ja','ko','fr','de','es','pt','ar'];
const copy={
 draftSaveFailed:["无法保存当前文件和编辑，请释放设备存储空间后重试。尚未打开支付。","Your file and edits could not be saved. Free up device storage and try again. Payment has not opened.","ファイルと編集内容を保存できません。空き容量を確認してください。支払いは開始していません。","파일과 편집 내용을 저장하지 못했습니다. 저장 공간을 확보하세요. 결제는 시작되지 않았습니다.","Impossible de sauvegarder. Libérez de l’espace et réessayez. Le paiement n’a pas été ouvert.","Speichern fehlgeschlagen. Speicherplatz freigeben und erneut versuchen. Zahlung nicht geöffnet.","No se pudieron guardar los cambios. Libera espacio e inténtalo de nuevo. El pago no se ha abierto.","Não foi possível salvar. Libere espaço e tente novamente. O pagamento não foi aberto.","تعذر حفظ الملف والتعديلات. أفرغ مساحة تخزين ثم أعد المحاولة. لم يتم فتح الدفع."],
 complete:['本次任务已完成','Task complete','完了しました','작업 완료','Tâche terminée','Aufgabe abgeschlossen','Tarea completada','Tarefa concluída','اكتملت المهمة'],
 ready:['文件已生成，已请求浏览器下载。若没有看到文件，请再次下载；不会再次付款。','Your file is ready and a download was requested. If it is missing, download it again without paying.','ファイルを作成し、ダウンロードを開始しました。見つからない場合は無料で再ダウンロードできます。','파일이 생성되어 다운로드를 요청했습니다. 파일이 없으면 추가 결제 없이 다시 다운로드하세요.','Fichier prêt, téléchargement demandé. Vous pouvez le télécharger à nouveau sans payer.','Datei erstellt, Download angefordert. Bei Bedarf ohne erneute Zahlung herunterladen.','Archivo listo y descarga solicitada. Puedes descargarlo de nuevo sin pagar.','Arquivo pronto e download solicitado. Você pode baixá-lo novamente sem pagar.','الملف جاهز وطُلب تنزيله. يمكنك تنزيله مجددًا دون دفع.'],
 download:['再次下载','Download again','再ダウンロード','다시 다운로드','Télécharger à nouveau','Erneut herunterladen','Descargar de nuevo','Baixar novamente','تنزيل مجددًا'],
 fresh:['清空并处理新文件','Clear & start a new file','クリアして新しいファイルへ','비우고 새 파일 시작','Effacer et traiter un nouveau fichier','Leeren und neue Datei starten','Limpiar y empezar otro archivo','Limpar e iniciar outro arquivo','مسح وبدء ملف جديد'],
 generating:['支付已确认，正在生成结果…','Payment confirmed. Preparing your result…','支払い確認済み。結果を作成中…','결제 확인됨. 결과 준비 중…','Paiement confirmé. Préparation du résultat…','Zahlung bestätigt. Ergebnis wird erstellt…','Pago confirmado. Preparando el resultado…','Pagamento confirmado. Preparando o resultado…','تم تأكيد الدفع. جارٍ إعداد النتيجة…'],
 retry:['继续已付款任务','Resume paid task','支払い済みの作業を再開','결제한 작업 계속','Reprendre la tâche payée','Bezahlte Aufgabe fortsetzen','Continuar tarea pagada','Retomar tarefa paga','استئناف المهمة المدفوعة'],
 failed:['结果尚未完成，请继续原任务，无需重复付款。','The result is not complete. Resume the same task without paying again.','未完了です。再払いせず同じ作業を再開してください。','결과가 미완료입니다. 추가 결제 없이 계속하세요.','Résultat incomplet. Reprenez sans payer à nouveau.','Ergebnis unvollständig. Ohne erneute Zahlung fortsetzen.','Resultado incompleto. Continúa sin volver a pagar.','Resultado incompleto. Continue sem pagar novamente.','النتيجة غير مكتملة. استأنف دون دفع مجددًا.'],
 existing:['此订单已完成，不会再次扣费或自动下载。','This order is complete. No new charge or automatic download.','この注文は完了済みです。再課金や自動ダウンロードはありません。','완료된 주문입니다. 재결제나 자동 다운로드는 없습니다.','Commande terminée. Aucun nouveau paiement ni téléchargement automatique.','Bestellung abgeschlossen. Keine erneute Zahlung oder automatischer Download.','Pedido completado. Sin nuevos cargos ni descargas automáticas.','Pedido concluído. Sem nova cobrança ou download automático.','هذا الطلب مكتمل. لا دفع جديد أو تنزيل تلقائي.'],
 pricing:['正在确认价格…','Confirming price…','価格確認中…','가격 확인 중…','Confirmation du prix…','Preis wird bestätigt…','Confirmando precio…','Confirmando preço…','جارٍ تأكيد السعر…'],
 confirm:['确认价格并导出','Confirm price & export','価格を確認して出力','가격 확인 및 내보내기','Confirmer le prix et exporter','Preis bestätigen und exportieren','Confirmar precio y exportar','Confirmar preço e exportar','تأكيد السعر والتصدير'],
 waiting:['支付窗口已打开，文件和编辑保留在当前页面。','Payment opened. Your files and edits stay on this page.','支払い画面を開きました。ファイルと編集は保持されます。','결제 창이 열렸습니다. 파일과 편집은 유지됩니다.','Paiement ouvert. Vos fichiers et modifications sont conservés.','Zahlung geöffnet. Dateien und Änderungen bleiben erhalten.','Pago abierto. Se conservan tus archivos y cambios.','Pagamento aberto. Arquivos e alterações preservados.','فُتح الدفع. تبقى الملفات والتعديلات في هذه الصفحة.'],
 popup:['请允许支付窗口，或稍后从订单继续。','Allow the payment window, or resume from Orders later.','支払いウィンドウを許可するか、注文から再開してください。','결제 창을 허용하거나 주문에서 계속하세요.','Autorisez la fenêtre de paiement ou reprenez depuis les commandes.','Zahlungsfenster erlauben oder über Bestellungen fortsetzen.','Permite la ventana de pago o continúa desde Pedidos.','Permita a janela de pagamento ou retome em Pedidos.','اسمح لنافذة الدفع أو استأنف من الطلبات.'],
 tier:['按所选导出页数计阶梯总价，付款前显示本次金额。同一结果再次下载不收费。','Tiered total based on selected export pages, shown before payment. Downloading the same result again is free.','選択した出力ページ数に応じた段階料金を支払い前に表示します。同じ結果の再ダウンロードは無料です。','선택한 내보내기 페이지 수에 따른 총액을 결제 전에 표시합니다. 동일 결과 재다운로드는 무료입니다.','Total par palier selon les pages exportées, affiché avant paiement. Retéléchargement gratuit du même résultat.','Staffelgesamtpreis nach Exportseiten, vor Zahlung angezeigt. Dasselbe Ergebnis erneut herunterzuladen ist kostenlos.','Total por tramos según páginas exportadas, visible antes de pagar. Volver a descargar el mismo resultado es gratis.','Total por faixa de páginas exportadas, exibido antes do pagamento. Baixar o mesmo resultado novamente é grátis.','سعر إجمالي حسب عدد الصفحات المحددة يُعرض قبل الدفع. إعادة تنزيل النتيجة نفسها مجانية.'],
 copied:['链接已复制','Link copied','コピーしました','링크 복사됨','Lien copié','Link kopiert','Enlace copiado','Link copiado','تم نسخ الرابط'],
 manualCopy:['无法自动复制，请选择下方链接手动复制。','Select the link below and copy it manually.','下のリンクを選択してコピーしてください。','아래 링크를 선택해 직접 복사하세요.','Sélectionnez le lien ci-dessous et copiez-le.','Link unten auswählen und manuell kopieren.','Selecciona el enlace y cópialo manualmente.','Selecione o link e copie manualmente.','حدد الرابط أدناه وانسخه يدويًا.'],
 privateShare:['只分享工具链接，不包含你的文件、订单或编辑内容。','Only the tool link is shared, never your files, orders or edits.','共有されるのはツールのリンクのみです。ファイルや注文、編集内容は含みません。','도구 링크만 공유됩니다. 파일, 주문, 편집 내용은 포함되지 않습니다.','Seul le lien de l’outil est partagé, sans fichiers, commandes ni modifications.','Nur der Tool-Link wird geteilt, keine Dateien, Bestellungen oder Änderungen.','Solo se comparte el enlace, sin archivos, pedidos ni cambios.','Apenas o link é compartilhado, sem arquivos, pedidos ou alterações.','تُشارك وصلة الأداة فقط، دون ملفاتك أو طلباتك أو تعديلاتك.']
} as const;
export function deliveryText(lang:string,key:keyof typeof copy){return copy[key][Math.max(0,langs.indexOf(lang as LingxiLang))]||copy[key][1]}
