"use client";
import Image from"next/image";import{useEffect,useState}from"react";import Nav from"@/components/Nav";import Footer from"@/components/Footer";import{createClient}from"@/lib/supabase/client";
const STEPS=["已收到","已查看","处理中","已完成"];
function stepOf(s:string){return s==="fixed"||s==="closed"?3:s==="reviewing"?2:s==="received"?0:0}
export default function Page(){const[items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(true);
useEffect(()=>{(async()=>{const s=createClient(),{data:{session}}=await s.auth.getSession();if(!session){location.href="/account?next=/account/support";return}const r=await fetch("/api/support/tickets",{headers:{authorization:`Bearer ${session.access_token}`},cache:"no-store"});if(r.ok)setItems((await r.json()).items||[]);setLoading(false)})()},[]);
return <><Nav/><main className="lx11-page"><section className="mx-auto max-w-3xl px-6 py-16"><p className="text-xs uppercase tracking-[.18em] opacity-45">LINGXIFIELD CARE</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">我的问题</h1><p className="mt-3 text-sm leading-6 opacity-60">查看你提交的问题、截图和处理进度。完成后的产品更新会通过灵犀场公告发布。</p></div><button className="rounded-xl border px-4 py-2 text-sm" onClick={()=>window.dispatchEvent(new Event("lingxifield:feedback"))}>告诉我们</button></div>
<div className="mt-8 grid gap-4">{loading?<div className="rounded-2xl border p-6 text-sm opacity-60">正在读取…</div>:items.length?items.map(x=>{const at=stepOf(x.status);return <article key={x.id} className="rounded-2xl border border-black/10 p-5"><div className="flex flex-wrap justify-between gap-3"><div><b className="text-base">{x.title||"使用问题"}</b><div className="mt-1 text-xs opacity-45">编号 {String(x.id).slice(0,8)} · {new Date(x.created_at).toLocaleString()}</div></div><span className="rounded-full bg-black/5 px-3 py-1 text-xs">{STEPS[at]}</span></div>
<div className="mt-5 grid grid-cols-4 gap-2">{STEPS.map((n,i)=><div key={n}><div className={`h-1.5 rounded-full ${i<=at?"bg-black":"bg-black/10"}`}/><div className={`mt-2 text-xs ${i<=at?"opacity-80":"opacity-35"}`}>{n}</div></div>)}</div>
<p className="mt-5 whitespace-pre-wrap text-sm leading-6 opacity-75">{x.message}</p>{x.contact&&<p className="mt-3 text-xs opacity-50">联系邮箱：{x.contact}</p>}
{x.attachmentUrls?.length>0&&<div className="mt-4 grid grid-cols-4 gap-2">{x.attachmentUrls.map((url:string,i:number)=><a href={url} target="_blank" rel="noreferrer" key={url} className="relative aspect-square overflow-hidden rounded-xl bg-black/5"><Image src={url} alt={`问题截图 ${i+1}`} fill unoptimized className="object-cover"/></a>)}</div>}
{at===3&&<div className="mt-5 rounded-xl bg-black/[.035] p-4 text-sm leading-6">谢谢你把问题告诉我们。你的反馈帮助灵犀场把真实使用中的问题修得更好。相关改进正式上线时，我们会在公告中说明。</div>}</article>}):<div className="rounded-2xl border p-8 text-sm opacity-60">目前没有问题记录。</div>}</div></section></main><Footer/></>}
