"use client";

import { useRef, useState } from "react";
import Bi from "@/components/Bi";
import BirthDateGuidance, { BirthTimeOptionalCopy, type CalendarType } from "@/components/BirthDateGuidance";
import { calculateWebArchetype, type WebArchetypeMember, type WebArchetypeResult } from "@/lib/web-archetype";
import type { LifeMapFacts } from "@/lib/lifemap-calc";

const ROLE = {
  core:{zh:"核心原型",en:"Core Archetype"}, support:{zh:"支撑原型",en:"Supporting Archetype"},
  conditional:{zh:"条件原型",en:"Conditional Archetype"}, tension:{zh:"张力原型",en:"Tension Archetype"},
};

function ReportPage({ index, eyebrow, title, image, children }: { index:number; eyebrow:string; title:React.ReactNode; image?:string; children?:React.ReactNode }) {
  return <section className="lx-pdf-page relative mx-auto aspect-[210/297] w-full max-w-[794px] overflow-hidden border border-amber/20 bg-[#0a1230] p-7 sm:p-12">{image&&<><img src={image} alt="" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-b from-[#09122d]/55 via-[#09122d]/76 to-[#09122d]"/></>}<div className="relative z-10 flex h-full flex-col"><div className="flex justify-between gap-4 text-[10px] tracking-[.25em] text-amber/80"><span>{eyebrow}</span><span>{String(index).padStart(2,"0")} / 20</span></div><h3 className="mt-5 font-display text-2xl font-light text-bone sm:text-4xl">{title}</h3><div className="mt-7 min-h-0 flex-1">{children}</div><div className="mt-5 flex justify-between border-t border-white/10 pt-3 text-[9px] tracking-[.18em] text-bone-mute"><span>WEB · ASTRONOMICAL ARCHETYPE STRUCTURE</span><span>lingxifield.com</span></div></div></section>;
}
const Paragraph = ({children}:{children:React.ReactNode}) => <p className="text-sm leading-7 text-bone-soft sm:text-base sm:leading-9">{children}</p>;
const imageFor = (member:WebArchetypeMember) => `/images/qian/${String(member.index).padStart(2,"0")}.jpg`;

function WebArchetypeReport({ name, result }: { name:string; result:WebArchetypeResult }) {
  const reportRef=useRef<HTMLDivElement>(null); const [downloading,setDownloading]=useState(false); const [error,setError]=useState("");
  const [core,support,conditional,tension]=result.matrix;
  const download=async()=>{if(!reportRef.current||downloading)return;setDownloading(true);setError("");try{const{exportSimplePdf}=await import("@/lib/pdf-export");await exportSimplePdf({containerRef:reportRef.current,fileName:"生命原型-官网天文结构版-20页.pdf",bgColorRgb:[9,18,45],bgColorHex:"#09122d"})}catch{setError("PDF 生成未完成，请稍后重试；当前网页报告仍可继续阅读。") }finally{setDownloading(false)}};
  const rolePage=(member:WebArchetypeMember,index:number,body:string)=><ReportPage key={member.role} index={index} eyebrow={`ORIGIN ARCHETYPE MATRIX · ${member.role.toUpperCase()}`} title={<Bi zh={ROLE[member.role].zh} en={ROLE[member.role].en}/>} image={imageFor(member)}><div className="mt-auto rounded-sm border border-amber/25 bg-[#09122d]/85 p-6"><p className="font-display text-3xl text-amber">{String(member.index+1).padStart(2,"0")} · <Bi zh={member.nameZh} en={member.nameEn}/></p><p className="mt-3 text-sm leading-7 text-bone-soft"><Bi zh={member.keywordsZh} en={member.keywordsEn}/></p><p className="mt-4 text-sm leading-8 text-bone-dim">{body}</p></div></ReportPage>;
  return <><div ref={reportRef} className="mt-12 space-y-7">
    <ReportPage index={1} eyebrow="FIELD 09 · ORIGIN ARCHETYPE MATRIX" title={<Bi zh="生命原型 · 本源原型矩阵" en="Life Archetype · Origin Matrix"/>} image={imageFor(core)}><div className="flex h-full flex-col justify-end"><p className="text-xs tracking-[.2em] text-amber">档案主体 · {name||"未命名生命档案"}</p><p className="mt-5 font-display text-4xl text-bone sm:text-6xl">{String(core.index+1).padStart(2,"0")} · <Bi zh={core.nameZh} en={core.nameEn}/></p><p className="mt-5 max-w-xl text-sm leading-8 text-bone-soft"><Bi zh={core.meaningZh} en={core.meaningEn}/></p></div></ReportPage>
    <ReportPage index={2} eyebrow="ASTRONOMICAL ARCHETYPE PRELUDE" title={<Bi zh="从时间坐标进入" en="Entering Through Time Coordinates"/>}><div className="space-y-5"><Paragraph>官网生命原型读取相对稳定的底层结构。它从出生日期、具体时刻、历法转换、天文位置与既有结构演算进入，不读取小程序八流进度，也不等待八项精测完成。</Paragraph><Paragraph>同一生命中往往不止一种力量：有些长期处于核心，有些持续提供支撑，有些只在特定条件出现，也有些与核心保持长期张力。</Paragraph><p className="font-display text-2xl text-amber">这是一幅本源原型矩阵，不是未来判定。</p></div></ReportPage>
    {rolePage(core,3,core.meaningZh)}
    <ReportPage index={4} eyebrow="ARCHETYPE SOURCE POINT" title={<Bi zh="原型源点" en="Archetype Source Point"/>}>{result.sourceZh.map((source,index)=><div key={source} className="mb-4 border-l border-amber/45 bg-white/[.035] p-4"><p className="text-xs text-bone-mute">结构证据 {String(index+1).padStart(2,"0")}</p><p className="mt-2 font-display text-xl text-amber">{source}</p></div>)}<Paragraph>多组时间与天文信号共同指向核心位置。前台不把公式伪装成命中率；显示的是可复核数据来源、结构重复与时间信息完整度。</Paragraph></ReportPage>
    <ReportPage index={5} eyebrow="ARCHETYPE CONSTELLATION" title={<Bi zh="本源原型矩阵 · 原型星座图" en="Origin Matrix · Archetype Constellation"/>}><div className="relative mx-auto mt-7 aspect-square max-w-[500px] rounded-full border border-amber/25"><div className="absolute inset-[31%] flex items-center justify-center rounded-full border border-amber/60 bg-amber/10 text-center font-display text-lg text-amber">{core.nameZh}</div>{result.matrix.slice(1).map((member,index)=>{const angle=-Math.PI/2+index*Math.PI*2/3;return <div key={member.role} className="absolute w-28 -translate-x-1/2 -translate-y-1/2 text-center" style={{left:`${50+42*Math.cos(angle)}%`,top:`${50+42*Math.sin(angle)}%`}}><span className="mx-auto block h-2 w-2 rounded-full bg-amber"/><p className="mt-2 text-xs text-bone-soft">{ROLE[member.role].zh}</p><p className="text-[10px] text-amber">{member.nameZh}</p></div>})}</div></ReportPage>
    <ReportPage index={6} eyebrow="HOW THE CORE OPERATES" title={<Bi zh="核心原型怎样运行" en="How the Core Archetype Operates"/>}>{result.operation.map(item=><article key={item.id} className="mb-3 grid grid-cols-[64px_1fr] gap-4 border-b border-white/10 pb-3"><p className="text-sm text-amber"><Bi zh={item.titleZh} en={item.titleEn}/></p><p className="text-xs leading-6 text-bone-soft sm:text-sm"><Bi zh={item.bodyZh} en={item.bodyEn}/></p></article>)}</ReportPage>
    {rolePage(support,7,`「${support.nameZh}」持续为「${core.nameZh}」提供结构支持。核心决定长期方向，支撑原型决定这股力量能否被现实稳定承接。`)}
    {rolePage(conditional,8,`「${conditional.nameZh}」并非持续占据前景；当旧路径失效、现实条件允许转换时，它更容易被唤起。这里描述触发条件，不预测事件发生时间。`)}
    {rolePage(tension,9,`「${core.nameZh}」与「${tension.nameZh}」形成长期牵引。真正需要维护的不是二选一，而是让核心结构为差异、自由与更新保留接口。`)}
    <ReportPage index={10} eyebrow="ARCHETYPE SYNERGY" title={<Bi zh="原型协同关系" en="Archetype Synergy"/>}><div className="space-y-5"><article className="border border-amber/25 bg-amber/[.04] p-6"><p className="font-display text-2xl text-amber">{core.nameZh} × {support.nameZh}</p><Paragraph>核心负责确定长期方向，支撑负责筛选哪些结构值得保留。两者协同时，比单纯增加速度更容易形成可持续成果。</Paragraph></article><article className="border border-white/12 bg-white/[.03] p-6"><p className="font-display text-2xl text-bone">{conditional.nameZh} × {tension.nameZh}</p><Paragraph>条件力量负责转向，张力力量负责保留必要边界。两者共同决定何时改变，以及改变后怎样不失去结构完整性。</Paragraph></article></div></ReportPage>
    <ReportPage index={11} eyebrow="OVERUSE PATTERN" title={<Bi zh="原型过度使用面" en="Archetype Overuse Pattern"/>} image={imageFor(core)}><div className="mt-auto rounded-sm border border-white/15 bg-[#09122d]/86 p-6"><Paragraph>当「{core.nameZh}」被过度调用，原本的力量可能变成不断重复“{core.keywordsZh}”，却迟迟不允许现实反馈进入。过度面不是缺点，而是同一种能力超过当前承接容量后的结构偏移。</Paragraph></div></ReportPage>
    <ReportPage index={12} eyebrow="ABSENT CAPACITY" title={<Bi zh="原型缺席面" en="Archetype Absence Pattern"/>} image={imageFor(tension)}><div className="mt-auto rounded-sm border border-white/15 bg-[#09122d]/86 p-6"><Paragraph>当「{tension.nameZh}」长期没有位置，核心结构会失去必要的反证与更新接口。需要补回的不是另一种人格，而是一种能让现有力量更完整运行的条件。</Paragraph></div></ReportPage>
    <ReportPage index={13} eyebrow="ARCHETYPE IN RELATIONSHIP" title={<Bi zh="关系中的原型表达" en="Archetype Expression in Relationship"/>}><Paragraph>在重要关系中，「{core.nameZh}」倾向以自身最熟悉的方式表达在意；「{support.nameZh}」负责维持连续回应。需要留意的是：不要把关系也完全变成需要整理或解决的结构，真实差异应由「{tension.nameZh}」保留。</Paragraph></ReportPage>
    <ReportPage index={14} eyebrow="ARCHETYPE IN CREATION" title={<Bi zh="创造中的原型表达" en="Archetype Expression in Creation"/>}><Paragraph>创造从「{core.nameZh}」的核心力量启动，经由「{support.nameZh}」形成方法与连续性；当环境出现转折，「{conditional.nameZh}」负责打开新路径。价值不在想法数量，而在这条链路能否进入现实完成。</Paragraph></ReportPage>
    <ReportPage index={15} eyebrow="ARCHETYPE IN ACTION" title={<Bi zh="行动中的原型表达" en="Archetype Expression in Action"/>}>{result.operation.filter(item=>["action","completion"].includes(item.id)).map(item=><article key={item.id} className="mb-5 border-l border-amber/50 bg-white/[.035] p-5"><p className="font-display text-xl text-amber"><Bi zh={item.titleZh} en={item.titleEn}/></p><p className="mt-3 text-sm leading-8 text-bone-soft"><Bi zh={item.bodyZh} en={item.bodyEn}/></p></article>)}</ReportPage>
    <ReportPage index={16} eyebrow="ARCHETYPE PATH" title={<Bi zh="原型生命路径" en="Archetype Life Path"/>}><div className="mt-8 flex flex-col items-center">{result.pathZh.map((step,index)=><div key={step} className="text-center"><div className="border border-amber/35 bg-amber/[.05] px-10 py-4 font-display text-xl text-amber">{step}<span className="ml-3 text-xs text-bone-mute">{result.pathEn[index]}</span></div>{index<result.pathZh.length-1&&<div className="mx-auto h-10 w-px bg-amber/35"/>}</div>)}</div></ReportPage>
    <ReportPage index={17} eyebrow="ARCHETYPE STABILITY" title={<Bi zh="原型稳定度" en="Archetype Stability"/>}><div className="border border-amber/30 bg-amber/[.04] p-7"><p className="font-display text-3xl text-amber">{result.stability==="core-stable"?"核心稳定":"明显稳定"}</p><Paragraph>稳定度描述证据结构，不是“命中率”。当前矩阵由多套时间、天文与历法信号共同支持；它允许多原型并行，也允许边界位置保持开放。</Paragraph></div></ReportPage>
    <ReportPage index={18} eyebrow="TIME CALIBRATION" title={<Bi zh="时间结构说明" en="Time Structure Notes"/>}><div className="space-y-4">{result.sourceZh.map((source,index)=><div key={source} className="flex gap-4 border-b border-white/10 pb-4"><span className="text-xs text-amber">{String(index+1).padStart(2,"0")}</span><p className="text-sm text-bone-soft">{source}</p></div>)}<Paragraph>精确出生时刻能够提高层级关系、边界节点与细部连接的结构分辨率；未提供时刻并不等于结果无效，系统会诚实地让相关边界保持开放。</Paragraph></div></ReportPage>
    <ReportPage index={19} eyebrow="OBSERVATION GUIDE" title={<Bi zh="原型观察指南" en="Archetype Observation Guide"/>}><div className="space-y-5"><Paragraph>未来七天，分别记录一次「{core.nameZh}」自然出现的时刻、一次「{support.nameZh}」提供支撑的时刻，以及一次「{tension.nameZh}」提醒你保留边界的时刻。</Paragraph><Paragraph>不要急着证明报告正确。只观察这些结构是否在关系、创造、行动与完成中重复出现；真实记录比认同感更有价值。</Paragraph></div></ReportPage>
    <ReportPage index={20} eyebrow="LINGXIFIELD ORIGINAL ARCHIVE" title={<Bi zh="从时间坐标，看见长期结构" en="See Enduring Structure Through Time Coordinates"/>} image={imageFor(core)}><div className="flex h-full flex-col justify-end"><Paragraph>官网与小程序可以出现不同原型，并不冲突。官网回答“什么长期构成生命”；小程序回答“此刻什么正在来到前景”。两条路径彼此独立，也可以彼此映照。</Paragraph><p className="mt-7 text-xs tracking-[.2em] text-amber">用于个人探索与反思体验，不构成医疗、金融、法律等专业建议。</p></div></ReportPage>
  </div><div className="mx-auto mt-7 max-w-[794px]"><button onClick={download} disabled={downloading} className="w-full border border-amber/50 bg-amber/10 py-4 text-sm tracking-[.2em] text-amber">{downloading?"正在生成 20 页 PDF…":"下载官网 20 页 PDF · DOWNLOAD"}</button>{error&&<p className="mt-3 text-center text-xs text-rose-300">{error}</p>}</div></>;
}

export default function WebArchetypeExperience(){
  const [name,setName]=useState(""); const [year,setYear]=useState(""); const [month,setMonth]=useState(""); const [day,setDay]=useState(""); const [calendarType,setCalendarType]=useState<CalendarType>("solar"); const [hasTime,setHasTime]=useState(false); const [hour,setHour]=useState("12"); const [minute,setMinute]=useState("0"); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<WebArchetypeResult|null>(null);
  const calculate=async()=>{if(!year||!month||!day||loading)return;setLoading(true);setError("");try{const response=await fetch("/api/lifemap/calc",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({year:Number(year),month:Number(month),day:Number(day),hour:Number(hour),minute:Number(minute),hasTime,calendarType})});const facts=await response.json() as LifeMapFacts&{error?:string};if(!response.ok)throw new Error(facts.error||"计算失败");setResult(calculateWebArchetype(facts));setTimeout(()=>document.getElementById("web-archetype-result")?.scrollIntoView({behavior:"smooth"}),30)}catch(cause){setError(cause instanceof Error?cause.message:"计算失败，请检查出生信息。") }finally{setLoading(false)}};
  return <section className="mx-auto mt-10 max-w-4xl"><div className="lx-glass border border-amber/20 p-6 sm:p-9"><p className="text-xs uppercase tracking-[.28em] text-amber">WEB · ASTRONOMICAL ARCHETYPE STRUCTURE</p><h2 className="mt-4 font-display text-2xl text-bone sm:text-3xl"><Bi zh="建立我的本源原型矩阵" en="Build My Origin Archetype Matrix"/></h2><p className="mt-4 text-sm leading-7 text-bone-dim"><Bi zh="出生时刻可选；填写后可提高矩阵层级与边界节点的分辨率。官网计算完全独立于小程序八流进度。" en="Birth time is optional; adding it improves matrix hierarchy and boundary resolution. This website calculation is independent from Mini Program convergence."/></p><div className="mt-6"><label className="text-xs text-bone-dim">称呼（选填） · NAME</label><input value={name} onChange={event=>setName(event.target.value)} className="mt-2 w-full border border-white/15 bg-[#07102c] px-4 py-3 text-bone outline-none focus:border-amber/50"/></div><BirthDateGuidance value={calendarType} onChange={setCalendarType} context="qian" className="mt-5"/><div className="mt-3 grid grid-cols-3 gap-3"><input value={year} onChange={e=>setYear(e.target.value)} placeholder="年 / YEAR" className="border border-white/15 bg-[#07102c] px-3 py-3 text-bone"/><input value={month} onChange={e=>setMonth(e.target.value)} placeholder="月" className="border border-white/15 bg-[#07102c] px-3 py-3 text-bone"/><input value={day} onChange={e=>setDay(e.target.value)} placeholder="日" className="border border-white/15 bg-[#07102c] px-3 py-3 text-bone"/></div><label className="mt-4 flex items-center gap-2 text-xs text-bone-dim"><input type="checkbox" checked={hasTime} onChange={e=>setHasTime(e.target.checked)}/><BirthTimeOptionalCopy/></label>{hasTime&&<div className="mt-3 grid grid-cols-2 gap-3"><input value={hour} onChange={e=>setHour(e.target.value)} placeholder="时 0-23" className="border border-white/15 bg-[#07102c] px-3 py-3 text-bone"/><input value={minute} onChange={e=>setMinute(e.target.value)} placeholder="分" className="border border-white/15 bg-[#07102c] px-3 py-3 text-bone"/></div>}<button onClick={calculate} disabled={!year||!month||!day||loading} className="mt-6 w-full border border-amber/50 bg-amber/10 py-4 text-sm tracking-[.2em] text-amber disabled:opacity-40">{loading?"正在建立天文原型矩阵…":"展开我的生命原型 · REVEAL"}</button>{error&&<p className="mt-4 text-sm text-rose-300">{error}</p>}</div>{result&&<div id="web-archetype-result"><WebArchetypeReport name={name} result={result}/></div>}</section>;
}
