"use client";
import {Suspense,useEffect,useRef,useState} from "react";
import {useSearchParams} from "next/navigation";
import QRCode from "qrcode";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {accountText} from "@/lib/account-experience-i18n";
function Inner(){
 const{lang}=useLingxiLang(),t=(k:string)=>accountText(lang,k),sp=useSearchParams()??new URLSearchParams(),quoteId=sp.get("quoteId")||"";
 const[q,setQ]=useState<any>(null),[err,setErr]=useState(""),[busy,setBusy]=useState(false),[qr,setQr]=useState(""),[paid,setPaid]=useState(false),[providers,setProviders]=useState({wechat:false,alipay:false,paypal:false});
 const timer=useRef<ReturnType<typeof setInterval>|null>(null),isWechat=typeof navigator!=="undefined"&&/MicroMessenger/i.test(navigator.userAgent),code=sp.get("code")||undefined,state=sp.get("state")||undefined;
 async function refresh(){const r=await fetch(`/api/tools/pay/status?quoteId=${encodeURIComponent(quoteId)}`,{cache:"no-store"});if(r.ok){const d=await r.json();if(d.paid){setPaid(true);if(timer.current)clearInterval(timer.current)}}}
 useEffect(()=>{if(!quoteId)return;fetch(`/api/tools/quote?id=${encodeURIComponent(quoteId)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>d.error?setErr(d.error):setQ(d));fetch("/api/pay/providers",{cache:"no-store"}).then(r=>r.json()).then(d=>setProviders({wechat:Boolean(d.wechat),alipay:Boolean(d.alipay),paypal:Boolean(d.paypal)})).catch(()=>{});void refresh();timer.current=setInterval(refresh,2500);return()=>{if(timer.current)clearInterval(timer.current)}},[quoteId]);
 useEffect(()=>{if(code&&state&&q&&!paid)void pay("wechat")},[code,state,!!q]);
 function invoke(jsapi:any){const w=window as any;const run=()=>w.WeixinJSBridge.invoke("getBrandWCPayRequest",jsapi,(res:any)=>{if(res.err_msg==="get_brand_wcpay_request:ok")void refresh();else setErr(res.err_msg||"PAYMENT_NOT_COMPLETED")});if(!w.WeixinJSBridge)document.addEventListener("WeixinJSBridgeReady",run,{once:true} as any);else run()}
 async function pay(provider:"wechat"|"alipay"|"paypal"){if(!(providers as any)[provider])return;setBusy(true);setErr("");try{if(provider==="wechat"&&isWechat&&!code){const u=new URL(window.location.href);u.protocol="https:";u.hostname="lingxifield.com";u.port="";const r=await fetch(`/api/pay/wechat/oauth-url?redirectUri=${encodeURIComponent(u.toString())}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"WECHAT_OAUTH_FAILED");window.location.href=d.url;return}const r=await fetch("/api/tools/pay/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({quoteId,provider,code,state})});const d=await r.json();if(!r.ok)throw new Error(d.error||"PAYMENT_INIT_FAILED");if(d.paid){setPaid(true);return}if(d.url){window.location.href=d.url;return}if(d.codeUrl){setQr(await QRCode.toDataURL(d.codeUrl,{width:256,margin:1,errorCorrectionLevel:"M"}));return}if(d.jsapi){invoke(d.jsapi);return}}catch(e){setErr(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 useEffect(()=>{if(!paid||!quoteId)return;try{window.opener?.postMessage({type:"LINGXIFIELD_TOOL_PAYMENT_CONFIRMED",quoteId},window.location.origin)}catch{}},[paid,quoteId]);
 if(paid)return <div className="mx-auto max-w-xl px-6 py-24 text-center"><div className="text-5xl">✓</div><h1 className="mt-5 text-2xl font-semibold">{t("payConfirmed")}</h1><p className="mt-3 text-slate-500">{t("payConfirmedBody")}</p><button onClick={()=>window.close()} className="mt-7 rounded-full bg-blue-600 px-6 py-3 text-white">{t("close")}</button></div>;
 return <div className="mx-auto max-w-xl px-6 py-20"><h1 className="text-3xl font-semibold">{t("payTitle")}</h1>{q&&<div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6"><div className="text-sm text-slate-500">{t("actualQty")}：{q.quantity} {q.unit_name}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><button disabled={busy||!providers.wechat} onClick={()=>pay("wechat")} className="rounded-xl border p-4 disabled:opacity-40"><b>{t("wechat")}</b><span className="mt-1 block">¥{Number(q.amount_rmb).toFixed(2)}</span></button><button disabled={busy||!providers.alipay} onClick={()=>pay("alipay")} className="rounded-xl border p-4 disabled:opacity-40"><b>{t("alipay")}</b><span className="mt-1 block">¥{Number(q.amount_rmb).toFixed(2)}</span></button><button disabled={busy||!providers.paypal} onClick={()=>pay("paypal")} className="rounded-xl border border-[#0070ba]/30 p-4 disabled:opacity-40"><b>PayPal</b><span className="mt-1 block">${Number(q.amount_usd).toFixed(2)} USD</span></button></div></div>}{qr&&<div className="mt-6 text-center"><img src={qr} alt="WeChat Pay QR" className="mx-auto h-64 w-64 rounded-xl bg-white p-2"/></div>}{err&&<p className="mt-5 text-sm text-rose-600">{err}</p>}</div>
}
export default function Page(){return <main className="min-h-screen bg-[#fbfcfe]"><Suspense fallback={<div className="p-20 text-center">…</div>}><Inner/></Suspense></main>}
