"use client";

import { useRef, useState } from "react";
import Bi from "@/components/Bi";
import ReportReturnBar from "./ReportReturnBar";
import { PublicationCopy, PublicationLabel, PublicationPage } from "./PublicationPage";
import { selectPdfArt, WEB_ARCHETYPE_PDF_ART_POOL } from "@/lib/report-art-registry";
import type { DendriteResult } from "@/lib/mini/dendrite-engine";

const FIELD_LABELS:Record<string,string>={"life-map-report":"生命图谱","relationship-resonance":"关系共振","resilience-report":"生命韧性","romance-report":"桃花磁场","wealth-report":"财富创造地图","daily-tide-report":"今日潮汐","tarot-reading":"生命镜像","qian-reading":"生命灵签"};
type Module={eyebrow:string;titleZh:string;titleEn:string;bodyZh:string;bodyEn:string;accent?:string};

export default function MiniLifeArchetypeReport({reportId,subjectName,createdAt,result}:{reportId:string;subjectName:string;createdAt:string;result:DendriteResult}) {
  const reportRef=useRef<HTMLDivElement>(null); const[downloading,setDownloading]=useState(false); const[error,setError]=useState("");
  const art=(page:number)=>selectPdfArt(WEB_ARCHETYPE_PDF_ART_POOL,reportId,page).src;
  const primary=result.dominant[0]; const support=result.dominant[1]??primary; const adaptive=result.dominant[2]??support; const quiet=[...result.nodes].sort((a,b)=>a.score-b.score)[0]??primary;
  const relations=result.structuralRelations??[]; const tensions=result.tensions??[]; const tributaries=result.tributaryDetails??[];
  const topNames=`${primary?.zh} × ${support?.zh} × ${adaptive?.zh}`; const topNamesEn=`${primary?.en} × ${support?.en} × ${adaptive?.en}`;
  const modules:Module[]=[
    {eyebrow:"REPORT PROVENANCE",titleZh:"档案来源与主体边界",titleEn:"Provenance and Subject Boundary",bodyZh:`本档案只调用“${subjectName}”在同一账户下、365 天有效窗口内完成并解锁的八类报告。系统按稳定主体标识与姓名核对，不把替他人完成的报告、关系对象或不同姓名的档案混入。`,bodyEn:`This archive uses only the eight completed and unlocked reports belonging to ${subjectName} within one 365-day window. Stable subject identity and exact name matching prevent reports created for other people or relationship partners from being mixed in.`},
    {eyebrow:"CURRENT ARCHETYPE",titleZh:"当前生命原型",titleEn:"Current Life Archetype",bodyZh:`当前原型不是一枚人格标签，而是“${primary?.zh}”承担方向、“${support?.zh}”形成现实接口、“${adaptive?.zh}”调节行动强度的三层运行结构。`,bodyEn:`The current archetype is not a personality label. ${primary?.en} carries direction, ${support?.en} forms the real-world interface, and ${adaptive?.en} regulates intensity.`,accent:topNames},
    {eyebrow:"ARCHETYPE SOURCE",titleZh:"原型源点",titleEn:"Archetype Source",bodyZh:`源点来自八个独立场域中重复出现的节点，而不是某一道题。${primary?.zh}在不同情境中持续保持较高激活，说明它能够跨越状态变化，承担当前结构的组织中心。`,bodyEn:`The source is repeated activation across eight independent fields, not one answer. ${primary?.en} remains active across changing contexts and therefore organizes the present structure.`},
    {eyebrow:"PRIMARY AXES",titleZh:"三条主轴",titleEn:"Three Primary Axes",bodyZh:`方向轴由${primary?.zh}提供，承接轴由${support?.zh}建立，校准轴由${adaptive?.zh}维持。三者的价值不在同时变强，而在于形成明确顺序：先辨认方向，再建立现实接口，最后调整投入强度。`,bodyEn:`${primary?.en} provides direction, ${support?.en} creates capacity, and ${adaptive?.en} calibrates intensity. Their value lies in sequence rather than simultaneous force.`},
    {eyebrow:"STABLE STRUCTURE",titleZh:"长期稳定结构",titleEn:"Stable Structure",bodyZh:`跨域重复说明${primary?.zh}不是近期偶发状态。它更像一条稳定底层路径：先注意关键差异，再组织复杂信息，最后寻找能够进入现实的结构。`,bodyEn:`Cross-field repetition shows that ${primary?.en} is not a temporary state. It acts as a stable path from noticing key differences to organizing complexity and building a real-world form.`},
    {eyebrow:"HIDDEN STRUCTURE",titleZh:"隐性结构",titleEn:"Hidden Structure",bodyZh:`${quiet?.zh}并未消失，只是当前现实承接不足。它更可能在低压力、拥有空间或无需立即证明结果时出现。隐性结构不是缺点，而是尚未获得合适入口的能力。`,bodyEn:`${quiet?.en} has not disappeared; it currently lacks capacity and an appropriate entry. It is more likely to appear with space, lower pressure, and no demand for immediate proof.`},
    {eyebrow:"SCENE SWITCHING",titleZh:"场景切换机制",titleEn:"Scene-switching Mechanism",bodyZh:`当环境要求快速决定时，${adaptive?.zh}会进入前景；当任务要求长期承接时，${support?.zh}接管结构；只有在方向仍然开放时，${primary?.zh}才最容易发挥完整作用。`,bodyEn:`${adaptive?.en} moves forward under decision pressure, ${support?.en} takes over for long-term capacity, and ${primary?.en} works most fully while direction remains open.`},
    {eyebrow:"RELATIONSHIP EXPRESSION",titleZh:"关系中的原型表达",titleEn:"Archetype in Relationship",bodyZh:`关系中的核心课题不是匹配率，而是${primary?.zh}如何被他人接收、${support?.zh}如何建立安全接口，以及${adaptive?.zh}在分歧出现时是否仍保留回应空间。`,bodyEn:`The relationship question is not compatibility. It is how ${primary?.en} is received, how ${support?.en} creates safety, and whether ${adaptive?.en} preserves response space during difference.`},
    {eyebrow:"CREATION AND VALUE",titleZh:"创造与价值路径",titleEn:"Creation and Value Path",bodyZh:`创造从${primary?.zh}发现方向开始，经${support?.zh}转成可承接结构，再由${adaptive?.zh}通过行动和反馈校准。真正的断点通常不在想法，而在价值能否被命名、交付并进入交换。`,bodyEn:`Creation begins as ${primary?.en} finds direction, becomes a viable structure through ${support?.en}, and is calibrated through action and feedback by ${adaptive?.en}.`},
    {eyebrow:"PRESSURE RESPONSE",titleZh:"压力下的原型变化",titleEn:"Archetype Under Pressure",bodyZh:`压力升高时，主轴可能被过度调用：${primary?.zh}变成持续判断，${support?.zh}变成过度承接，${adaptive?.zh}变成频繁调整。报告把这些视为使用过量后的结构偏移，而不是性格缺陷。`,bodyEn:`Under pressure the axes can be overused: ${primary?.en} becomes constant judgment, ${support?.en} over-carries, and ${adaptive?.en} over-adjusts. These are structural drifts, not character flaws.`},
    {eyebrow:"SECONDARY STRUCTURE",titleZh:"第二结构与适应层",titleEn:"Secondary and Adaptive Structure",bodyZh:`第二结构不是弱化版主原型，而是现实条件改变时负责维持系统运行的替代路径。${support?.zh}与${adaptive?.zh}共同构成这一层，让方向在资源不足时仍能被保存。`,bodyEn:`The secondary structure is not a weaker primary archetype. ${support?.en} and ${adaptive?.en} preserve operation when conditions change or resources narrow.`},
    {eyebrow:"AMPLIFICATION LOOP",titleZh:"跨域增强回路",titleEn:"Cross-field Amplification Loop",bodyZh:`${topNames}在多个互不依赖的产品中共同进入前景，因此形成增强回路。它不把八份报告压缩成摘要，而是读取哪些节点跨域共现、彼此支持并改变现实行动。`,bodyEn:`${topNamesEn} recur across independent products and form an amplification loop. The engine reads cross-field co-activation instead of summarizing eight reports.`,accent:topNames},
    {eyebrow:"ACTIVE TENSIONS",titleZh:"结构张力",titleEn:"Structural Tensions",bodyZh:tensions[0]?.bodyZh??`${primary?.zh}要求推进，而${quiet?.zh}要求保留承接空间。真正需要维护的是两者的先后与接口，不是二选一。`,bodyEn:tensions[0]?.bodyEn??`${primary?.en} asks for movement while ${quiet?.en} asks for capacity. The work is to maintain sequence and interface, not choose one side.`},
    {eyebrow:"INHIBITED CAPACITY",titleZh:"被抑制的力量",titleEn:"Inhibited Capacity",bodyZh:`当前被抑制的是${quiet?.zh}所代表的能力。相关信号已经存在，但缺少时间、资源或安全边界来进入前景。先建立承接条件，比要求它立即表现更有效。`,bodyEn:`The capacity represented by ${quiet?.en} is present but inhibited by limited time, resources, or safety. Building capacity is more useful than demanding immediate expression.`},
    {eyebrow:"DENDRITIC GRAPH",titleZh:"树突连接图谱",titleEn:"Dendritic Connection Graph",bodyZh:`系统在八组节点之间建立增强、桥接与张力三类连接。当前记录到 ${relations.length} 条高解释力关系；每条关系都要求至少两个独立证据源，并保留相反信号作为校准。`,bodyEn:`The engine builds reinforcement, bridge, and tension links across eight node systems. ${relations.length} high-explanatory relationships are retained, each requiring independent evidence and counter-signals.`},
    {eyebrow:"BLIND SPOT",titleZh:"当前盲区",titleEn:"Current Blind Spot",bodyZh:`当${primary?.zh}过度承担方向判断时，系统容易低估${quiet?.zh}所代表的承接限制。盲区不是“看不见一切”，而是某类证据在当前决策中持续获得较低权重。`,bodyEn:`When ${primary?.en} over-carries direction, the system may underweight the capacity limits represented by ${quiet?.en}. A blind spot is persistently low evidence weight, not total unawareness.`},
    {eyebrow:"UNDERESTIMATED CAPACITY",titleZh:"被低估的能力",titleEn:"Underestimated Capacity",bodyZh:`${quiet?.zh}值得被重新观察。它可能不以高强度、快速产出或外部可见的方式出现，却能在长期稳定、恢复与边界维护中提供关键价值。`,bodyEn:`${quiet?.en} deserves renewed observation. It may not appear through intensity or visible output, yet it can contribute to long-term stability, recovery, and boundary maintenance.`},
    {eyebrow:"CAPACITY CONDITION",titleZh:"现实承接条件",titleEn:"Conditions for Capacity",bodyZh:`主原型要稳定落地，需要三个条件：明确的现实对象、足够的时间边界、可返回的反馈回路。缺少其中任何一个，原型力量都可能变成内部消耗。`,bodyEn:`Stable embodiment requires a real object, sufficient time boundaries, and a returnable feedback loop. Without any one of these, archetypal force can become internal depletion.`},
    {eyebrow:"REALITY ENTRANCE",titleZh:"现实验证入口",titleEn:"Reality Verification Entry",bodyZh:result.realityEntry?.actionZh??primary?.actionZh??"选择一个七天内能够完成、同时触及方向与承接的现实动作，并记录反馈。",bodyEn:result.realityEntry?.actionEn??primary?.actionEn??"Choose one seven-day action that touches both direction and capacity, then record the feedback."},
    {eyebrow:"EIGHT-STREAM TIMELINE",titleZh:"八流时间轨迹",titleEn:"Eight-stream Timeline",bodyZh:`八条支流依次留下证据：${tributaries.map((stream)=>FIELD_LABELS[stream.productId]).join("、")}。时间先后不会决定价值高低，但会帮助区分长期重复与近期增强。`,bodyEn:`Eight streams leave evidence across time. Sequence does not determine value; it helps distinguish long-term repetition from recent amplification.`},
    {eyebrow:"EVIDENCE STANDARD",titleZh:"证据与置信边界",titleEn:"Evidence and Confidence Boundary",bodyZh:`本报告交叉读取 192 次有效选择、八组知识节点及其跨域连接。单题不直接决定原型；缺失信息不被想象补全；不同场域的分歧被保留为张力。`,bodyEn:`This report cross-reads 192 valid choices, eight node systems, and their links. No single answer determines the archetype, missing data is not invented, and disagreements remain as tension.`},
    {eyebrow:"CONTINUOUS OBSERVATION",titleZh:"持续观察协议",titleEn:"Continuous Observation Protocol",bodyZh:`未来任一支流形成新的完整记录后，系统比较新旧节点强度、跨域连接与现实验证。只有结构出现实质变化，原型才更新；单次情绪波动不会改写档案。`,bodyEn:`When a stream produces a new complete record, the engine compares node strength, cross-field links, and real verification. The archetype updates only after material structural change.`},
    {eyebrow:"CLOSING FIELD",titleZh:"八流汇聚，原型自现",titleEn:"Eight Streams Converge",bodyZh:`生命原型不是八份结论的叠加，而是关系、韧性、创造、状态与生命结构彼此交汇后显现的整体轮廓。让它成为下一次真实行动的坐标，而不是替你作出决定的答案。`,bodyEn:`Life Archetype is not eight conclusions stacked together. It is the whole contour revealed where relationship, resilience, creation, state, and life structure meet. Use it as a coordinate for action, not a decision made for you.`},
  ];
  const total=24;
  const download=async()=>{if(!reportRef.current||downloading)return;setDownloading(true);setError("");try{const{exportPublicationPagesPdf}=await import("@/lib/pdf-export");await exportPublicationPagesPdf({containerRef:reportRef.current,fileName:"生命原型-八流归一-24页完整档案.pdf"});}catch(error){console.error(error);setError("PDF 未能完整生成。系统已阻止空图或残缺页面下载，请稍后重试。");}finally{setDownloading(false);}};
  return <main className="min-h-screen bg-[radial-gradient(circle_at_12%_8%,rgba(127,91,180,.34),transparent_30%),radial-gradient(circle_at_88%_24%,rgba(43,156,168,.28),transparent_35%),#07102c] text-bone"><ReportReturnBar miniLabel="返回八流进度"/><div ref={reportRef} className="space-y-7 px-3 py-8 sm:px-6">
    <PublicationPage index={1} total={total} eyebrow="FIELD 09 · EIGHT-STREAM CONVERGENCE" title={<Bi zh="生命原型 · 八流归一" en="Life Archetype · Eight Streams Converged"/>} art={art(1)} layout="cover"><PublicationLabel><Bi zh={`档案主体 · ${subjectName}`} en={`Archive subject · ${subjectName}`}/></PublicationLabel><p className="mt-3 text-xs opacity-70">{new Date(createdAt).toLocaleString("zh-CN")}</p><p className="mt-6 font-display text-3xl text-[#bff8ec]">{topNames}</p><PublicationCopy><Bi zh="八条生命支流进入同一座场域；系统读取共同增强、现实承接、结构张力与被抑制的力量，形成一份独立的生命原型档案。" en="Eight life streams enter one field. The system reads reinforcement, real-world capacity, structural tension, and inhibited forces to form an independent Life Archetype archive."/></PublicationCopy></PublicationPage>
    {modules.map((module,index)=><PublicationPage key={module.eyebrow} index={index+2} total={total} eyebrow={module.eyebrow} title={<Bi zh={module.titleZh} en={module.titleEn}/>} art={art(index+2)} layout={index===modules.length-1?"full":"split"}>{module.accent&&<p className="mb-5 font-display text-2xl text-[#bff8ec]">{module.accent}</p>}<PublicationCopy><Bi zh={module.bodyZh} en={module.bodyEn}/></PublicationCopy>{index===14&&<div className="mt-5 grid gap-2">{relations.map((relation,relationIndex)=><div key={relationIndex} className="flex justify-between border-b border-white/20 pb-2 text-[13px] leading-6"><span>{result.nodes.find((node)=>node.id===relation.from)?.zh} → {result.nodes.find((node)=>node.id===relation.to)?.zh}</span><span className="text-[#9cf3df]">{{reinforce:"增强",bridge:"桥接",tension:"张力"}[relation.kind]} · {relation.strength}</span></div>)}</div>}{index===19&&<div className="mt-5 grid grid-cols-2 gap-2">{tributaries.map((stream)=><div key={stream.productId} className="border border-white/25 bg-[#071128]/25 p-3 text-[13px]"><span>{FIELD_LABELS[stream.productId]}</span><span className="float-right text-[#9cf3df]">{stream.score}</span></div>)}</div>}</PublicationPage>)}
  </div><div className="mx-auto max-w-[794px] px-3 pb-16 sm:px-6"><button onClick={download} disabled={downloading} className="w-full border border-lattice/50 bg-lattice/10 py-4 text-sm tracking-widest2 text-lattice">{downloading?"正在生成 24 页固定 A4 PDF…":"下载 24 页完整生命原型 PDF"}</button>{error&&<p className="mt-3 text-center text-xs text-rose-300">{error}</p>}</div></main>;
}
