"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import ReportReturnBar from "./ReportReturnBar";
import {PublicationCopy,PublicationLabel,PublicationPage} from "./PublicationPage";
import {selectPdfArt,WEB_ARCHETYPE_PDF_ART_POOL} from "@/lib/report-art-registry";
import type {DendriteResult,LifeArchetypeEvidenceLevel} from "@/lib/mini/dendrite-engine";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {miniLocale,miniText} from "@/lib/mini-report-i18n";
import {localizeReportItemsChunked} from "@/lib/report-localize-client";

const FIELD_ZH:Record<string,string>={"life-map-report":"生命图谱","relationship-resonance":"关系共振","resilience-report":"生命韧性","romance-report":"桃花磁场","wealth-report":"财富创造地图","daily-tide-report":"今日潮汐","tarot-reading":"生命镜像","qian-reading":"生命灵签"};
const LEVEL_ZH:Record<LifeArchetypeEvidenceLevel,string>={established:"已立",strong:"强证",developing:"生长中",conditional:"有条件",insufficient:"证未足"};
const LEVEL_EN:Record<LifeArchetypeEvidenceLevel,string>={established:"Established",strong:"Strong evidence",developing:"Developing",conditional:"Conditional",insufficient:"Insufficient evidence"};

export default function MiniLifeArchetypeReport({reportId,subjectName,createdAt,result}:{reportId:string;subjectName:string;createdAt:string;result:DendriteResult}){
 const{lang}=useLingxiLang();const t=(zh:string,en:string)=>miniText(lang,zh,en);
 const reportRef=useRef<HTMLDivElement>(null);const[downloading,setDownloading]=useState(false);const[error,setError]=useState("");
 const[translated,setTranslated]=useState<Record<string,string>>({});const[translationState,setTranslationState]=useState<"idle"|"loading"|"ready"|"error">("idle");
 const art=(page:number)=>selectPdfArt(WEB_ARCHETYPE_PDF_ART_POOL,reportId,page).src;const readings=result.archetypeReadings??[];const coverage=result.archetypeCoverage;const total=readings.length+1;
 const date=(value?:string)=>value?new Date(value).toLocaleDateString(miniLocale(lang)):t("未记录","Not recorded");

 const pairs=useMemo(()=>{const x:{key:string;value:string}[]=[];readings.forEach((r,i)=>{x.push({key:`r${i}.title`,value:r.titleZh},{key:`r${i}.brief`,value:r.briefZh},{key:`r${i}.classical`,value:r.classicalZh},{key:`r${i}.evidence`,value:r.evidenceZh},{key:`r${i}.verification`,value:r.verificationZh})});return x;},[readings]);
 useEffect(()=>{let dead=false;if(lang==="zh"){setTranslated({});setTranslationState("ready");return()=>{dead=true};}setTranslationState("loading");setTranslated({});void localizeReportItemsChunked({reportKey:`mini-report:${reportId}`,targetLang:lang,items:pairs.map(p=>p.value),translateEnglish:true}).then(r=>{if(dead)return;if(!r.translated){setTranslationState("error");return;}const m:Record<string,string>={};pairs.forEach((p,i)=>m[p.key]=r.items[i]);setTranslated(m);setTranslationState("ready")}).catch(()=>!dead&&setTranslationState("error"));return()=>{dead=true};},[lang,reportId,pairs]);
 const pick=(key:string,zh:string)=>lang==="zh"?zh:(translated[key]||zh);const ready=lang==="zh"||translationState==="ready";

 const download=async()=>{if(!reportRef.current||downloading||!ready)return;setDownloading(true);setError("");try{const{exportPublicationPagesPdf}=await import("@/lib/pdf-export");await exportPublicationPagesPdf({containerRef:reportRef.current,fileName:`LINGXIFIELD-life-archetype-v6-${lang}.pdf`});}catch(error){console.error(error);setError(t("PDF 未能完整生成。系统已阻止空图或残缺页面下载，请稍后重试；网页档案仍已保存。","The PDF could not be generated completely. Empty or incomplete pages were blocked; try again later. The web archive remains saved."));}finally{setDownloading(false);}};

 if(!coverage||coverage.engineVersion!=="v6"||coverage.identityVerified!==true||readings.length!==24)return <main className="min-h-screen bg-[#07102c] px-5 py-24 text-bone"><section className="mx-auto max-w-2xl border border-amber/30 bg-white/[.04] p-8"><p className="text-xs tracking-[.28em] text-amber">ARCHIVE HELD</p><h1 className="mt-4 font-display text-3xl">{t("此卷尚未通过 V6 证据核验","This archive has not passed V6 evidence verification")}</h1><p className="mt-5 leading-8 text-bone-dim">{t("旧档案、不同姓名档案或缺少底层证据的支流不会被补写成生命原型。请返回八流进度，按同一姓名重新核验。","Old archives, archives under a different name, or streams lacking source evidence are not rewritten into a Life Archetype. Return to Eight Streams and verify again under the same name.")}</p><a href="/archetype" className="mt-7 inline-block border border-lattice/50 px-5 py-3 text-lattice">{t("返回八流进度","Back to Eight Streams")}</a></section></main>;

 return <main className="min-h-screen bg-[radial-gradient(circle_at_12%_8%,rgba(127,91,180,.34),transparent_30%),radial-gradient(circle_at_88%_24%,rgba(43,156,168,.28),transparent_35%),#07102c] text-bone"><ReportReturnBar miniLabel="返回八流进度" miniLabelEn="Back to Eight Streams"/>
 <div className="sticky top-0 z-20 border-b border-lattice/20 bg-white/95 p-3 text-center"><button onClick={download} disabled={downloading||!ready} className="rounded-full border border-lattice/40 px-5 py-2 text-sm text-[#286a78] disabled:opacity-40">{downloading?t("正在生成完整档案…","Generating complete archive…"):translationState==="loading"?t("正在准备当前语言…","Preparing current language…"):t("下载完整 PDF ↓","Download full PDF ↓")}</button>{translationState==="error"&&<p role="alert" className="mt-2 text-sm text-rose-600">{t("当前语言生成失败，请稍后重试。为避免语言不一致，PDF 下载已暂时关闭。","Could not prepare the current language. Please try again later. PDF download is disabled to avoid a language mismatch.")}</p>}{error&&<p role="alert" className="mt-2 text-sm text-rose-600">{error}</p>}</div>
 <div ref={reportRef} className="space-y-7 px-3 py-8 sm:px-6">
  <PublicationPage index={1} total={total} eyebrow="LIFE ARCHETYPE V6 · EIGHT-STREAM CONVERGENCE" title={t("生命原型 · 八流归一","Life Archetype · Eight Streams Converged")} art={art(1)} layout="cover">
   <div className="flex items-start justify-between gap-5"><div><PublicationLabel>{t("档案主体","Archive subject")} · {subjectName}</PublicationLabel><p className="mt-2 text-xs leading-6 opacity-65">{t("同账户 · 姓名完全核验 · 365 天窗口","Same account · exact name verified · 365-day window")}</p></div><p className="font-display text-3xl text-[#557f79]">8 / 8</p></div>
   <div className="mt-6 grid grid-cols-2 gap-3 text-[12px] text-[#454151] sm:grid-cols-4"><div className="border border-[#4c4966]/15 bg-white/30 p-3"><span className="block text-[10px] tracking-[.16em] opacity-60">ENGINE</span>V6</div><div className="border border-[#4c4966]/15 bg-white/30 p-3"><span className="block text-[10px] tracking-[.16em] opacity-60">SOURCE REPORTS</span>{coverage.sourceReports}</div><div className="border border-[#4c4966]/15 bg-white/30 p-3"><span className="block text-[10px] tracking-[.16em] opacity-60">EVIDENCE LEAVES</span>{coverage.evidenceLeaves}</div><div className="border border-[#4c4966]/15 bg-white/30 p-3"><span className="block text-[10px] tracking-[.16em] opacity-60">IDENTITY</span>{t("已核验","Verified")}</div></div>
   <p className="mt-4 text-xs leading-6 opacity-65">{t("取证期","Evidence window")}：{date(coverage.windowStart)} — {date(coverage.windowEnd)} · {t("成卷","Compiled")}：{new Date(createdAt).toLocaleString(miniLocale(lang))}</p>
   <div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-2">{coverage.streamEvidence.map(stream=><div key={stream.productId} className="border-b border-[#4c4966]/15 pb-2 text-[12px] text-[#454151]"><span className="mr-2 text-[#557f79]">●</span>{t(FIELD_ZH[stream.productId]||stream.productId,stream.productId)}<span className="float-right opacity-60">{stream.evidenceCount} · {stream.readingCount}</span></div>)}</div>
   <PublicationCopy>{lang==="zh"?"八流各守其证，交会而不相吞；同象相扶，异象留隙。今据其反复、相逆、所承与未发，成二十四问，以见此人当下之全局。":"Eight streams retain their own evidence while converging. Repetition, contradiction, capacity and latent force are recomposed into twenty-four readings of the present whole."}</PublicationCopy>
  </PublicationPage>
  {readings.map((reading,index)=><PublicationPage key={reading.id} index={index+2} total={total} eyebrow={`LIFE ARCHETYPE V6 · ${reading.id.toUpperCase()}`} title={pick(`r${index}.title`,reading.titleZh)} art={art(index+2)} layout={index===readings.length-1?"full":"split"}><p className="mb-5 border-l-2 border-[#557f79]/55 pl-4 font-display text-lg leading-8 text-[#557f79]">{pick(`r${index}.brief`,reading.briefZh)}</p><PublicationCopy>{pick(`r${index}.classical`,reading.classicalZh)}</PublicationCopy><div className="mt-6 border-t border-[#4c4966]/15 pt-5 text-[12px] leading-6 text-[#454151]/80"><p>{pick(`r${index}.evidence`,reading.evidenceZh)}</p><p className="mt-3">{pick(`r${index}.verification`,reading.verificationZh)}</p></div><div className="mt-5 flex flex-wrap items-center gap-2 text-[10px] tracking-[.1em] text-[#557f79]"><span className="border border-[#557f79]/30 px-2 py-1">{lang==="zh"?LEVEL_ZH[reading.evidenceLevel]:t(LEVEL_ZH[reading.evidenceLevel],LEVEL_EN[reading.evidenceLevel])}</span>{reading.supportStreams.map(id=><span key={id} className="border border-[#4c4966]/15 bg-white/25 px-2 py-1">{t(FIELD_ZH[id]||id,id)}</span>)}</div></PublicationPage>)}
 </div><div className="mx-auto max-w-[794px] px-3 pb-16 sm:px-6"><button onClick={download} disabled={downloading||!ready} className="w-full border border-lattice/50 bg-lattice/10 py-4 text-sm tracking-widest2 text-lattice disabled:opacity-40">{downloading?t("正在生成完整档案…","Generating complete archive…"):translationState==="loading"?t("正在准备当前语言…","Preparing current language…"):t("下载生命原型 V6 完整 PDF","Download complete Life Archetype V6 PDF")}</button>{error&&<p className="mt-3 text-center text-xs text-rose-300">{error}</p>}</div></main>;
}
