"use client";
import {useRef,useState} from "react";
import Bi from "@/components/Bi";
import ReportReturnBar from "./ReportReturnBar";
import {PublicationCopy,PublicationLabel,PublicationPage} from "./PublicationPage";
import {PDF_ASSET_REGISTRY,productArtKey,selectPdfArt} from "@/lib/report-art-registry";
import type {DendriteReportEntry,ReportEvidenceLeaf} from "@/lib/mini/report-entry-library";
type Node={id:string;zh:string;en:string;score:number;actionZh?:string;actionEn?:string};
type Result={titleZh:string;titleEn:string;insightZh:string;insightEn:string;nodes:Node[];dominant:Node[];evidence?:{answered:number;total:number;historyProducts:number;sourceZh:string;sourceEn:string};evidenceLeaves?:ReportEvidenceLeaf[];structuralRelations?:Array<{from:string;to:string;kind:"reinforce"|"bridge"|"tension";strength:number}>;reportEntries?:DendriteReportEntry[]};
const confidenceLabel={clear:"证据清晰",developing:"正在形成",open:"留待复验"} as const;
export default function MiniDendriteReport({reportId,relationshipType,productId,productName,subjectName,createdAt,result}:{reportId:string;relationshipType?:string;productId:string;productName:string;subjectName:string;createdAt:string;result:Result}){
 const reportRef=useRef<HTMLDivElement>(null);const[downloading,setDownloading]=useState(false);const[downloaded,setDownloaded]=useState(false);const[downloadError,setDownloadError]=useState("");
 const artPool=PDF_ASSET_REGISTRY[productArtKey(productId,relationshipType)];const art=(page:number)=>selectPdfArt(artPool,reportId,page).src;const entries=(result.reportEntries??[]).slice(0,11);const leaves=result.evidenceLeaves??[];const nodeById=new Map(result.nodes.map(n=>[n.id,n.zh]));const total=18;
 const download=async()=>{if(!reportRef.current||downloading)return;setDownloading(true);setDownloadError("");try{const{exportPublicationPagesPdf}=await import("@/lib/pdf-export");await exportPublicationPagesPdf({containerRef:reportRef.current,fileName:`${productName}-完整场域档案.pdf`});setDownloaded(true)}catch(error){console.error(error);setDownloadError("PDF 未能完整生成。系统已阻止空图或残缺页面下载，请稍后重试；网页档案仍已保存。")}finally{setDownloading(false)}};
 return <main className="min-h-screen bg-[radial-gradient(circle_at_12%_8%,rgba(127,91,180,.34),transparent_30%),radial-gradient(circle_at_88%_24%,rgba(43,156,168,.28),transparent_35%),#0a1330] text-bone"><ReportReturnBar miniLabel="返回我的场域"/><div ref={reportRef} className="space-y-7 px-3 py-8 sm:px-6">
 <PublicationPage index={1} total={total} eyebrow="LINGXIFIELD DENDRITIC ARCHIVE" title={productName} art={art(1)} layout="cover"><PublicationLabel>档案主体 · {subjectName}</PublicationLabel><p className="mt-3 text-xs opacity-70">{new Date(createdAt).toLocaleString("zh-CN")}</p><p className="mt-6 font-display text-2xl text-[#557f79]"><Bi zh={result.titleZh} en={result.titleEn}/></p><PublicationCopy><Bi zh={result.insightZh} en={result.insightEn}/></PublicationCopy></PublicationPage>
 <PublicationPage index={2} total={total} eyebrow="全卷总断 · SYNTHESIS" title="先见其轴，再阅其流" art={art(2)}><p className="font-display text-xl leading-[1.9] text-[#343043]">诸答不逐题裁断，惟观其复现、相扶与相逆。今以「{result.dominant[0]?.zh}」为首，「{result.dominant[1]?.zh}」为承，「{result.dominant[2]?.zh}」为变；十一篇各问一事，共成此卷。</p><PublicationCopy>现代验证：阅读时只标记与你最近三个月真实经历相符之处；不符者保留为空，不必勉强认领。报告价值不在句句悦耳，而在能否指出一个可移动、可复验的现实结构。</PublicationCopy></PublicationPage>
 {entries.map((entry,i)=><PublicationPage key={entry.id} index={i+3} total={total} eyebrow={`第 ${String(i+1).padStart(2,"0")} 篇 · ${entry.chapterEn.toUpperCase()}`} title={entry.titleZh} art={art(i+3)}><article className="p-5 sm:p-7"><div className="flex justify-end"><span className="text-[11px] text-[#557f79]">{confidenceLabel[entry.confidence]}</span></div><p className="mt-3 font-display text-[18px] leading-[2] text-[#343043] sm:text-[20px]">{entry.structureZh}</p><p className="mt-4 text-[15px] leading-[1.9] sm:text-[17px]">{entry.mechanismZh}</p><p className="mt-4 border-l border-[#78b8b7] pl-4 text-[15px] leading-[1.9] sm:text-[17px]">{entry.realityZh}</p>{entry.strengthZh&&<p className="mt-3 text-[14px] leading-[1.8] text-[#557f79]">{entry.strengthZh}</p>}{entry.costZh&&<p className="mt-3 text-[14px] leading-[1.8] text-[#6d4891]">{entry.costZh}</p>}<p className="mt-4 text-[15px] leading-[1.9] sm:text-[17px]">{entry.actionZh}</p><p className="mt-4 text-[13px] leading-[1.8] text-[#696473]">{entry.observationZh}</p></article></PublicationPage>)}
 <PublicationPage index={14} total={total} eyebrow="势之相生 · STRUCTURAL RELATIONS" title="增强、桥接与张力" art={art(14)}><div className="grid gap-4">{(result.structuralRelations??[]).slice(0,5).map((r,i)=><article key={i} className="border-l border-[#78b8b7] p-4"><PublicationLabel>{{reinforce:"相扶",bridge:"相接",tension:"相牵"}[r.kind]} · {r.strength}</PublicationLabel><p className="mt-2 font-display text-xl">{nodeById.get(r.from)} × {nodeById.get(r.to)}</p><PublicationCopy muted>二力同现，不等于二者永远同强。再遇同类情境，察其先后与现实承接；一证相反，便留其隙。</PublicationCopy></article>)}</div></PublicationPage>
 {[0,1,2].map(group=><PublicationPage key={group} index={15+group} total={total} eyebrow="证据追溯 · EVIDENCE TRACE" title={`本卷取证 ${group*8+1}—${Math.min(group*8+8,leaves.length||24)}`} art={art(15+group)}><div className="grid gap-3">{leaves.slice(group*8,group*8+8).map((leaf,i)=><article key={leaf.questionId} className="border-b border-[#4c4966]/15 pb-3"><PublicationLabel>{String(group*8+i+1).padStart(2,"0")} · {leaf.evidenceDimension}</PublicationLabel><p className="mt-1 text-[13px] leading-6 text-[#4b4654]">{leaf.promptZh}</p><p className="mt-1 font-display text-[14px] leading-6 text-[#557f79]">所取：{leaf.answerZh}</p></article>)}</div><PublicationCopy muted>此处只供追溯，不逐题定人。正式判断来自多题复现、相互支持、冲突与反证。</PublicationCopy></PublicationPage>)}
 <PublicationPage index={18} total={total} eyebrow="LINGXIFIELD ORIGINAL FIELD" title="言止于证，行验于实" art={art(18)} layout="full"><PublicationCopy>辞贵简，义贵实；有据则言，无据则止。势有反复，明其所因；力有未发，辨其所蔽。十一篇所见，须落于日用；所行之事，须由现实反馈复验。</PublicationCopy><p className="mt-6 font-display text-2xl text-[#557f79]">证成其势 · 势见其隙 · 行验其真</p><p className="mt-6 text-[11px] leading-6 opacity-75">用于个人探索与反思体验，不构成医疗、金融、法律或其他专业建议。</p></PublicationPage>
 </div><div className="mx-auto max-w-[794px] px-3 pb-16 sm:px-6"><button onClick={download} disabled={downloading} className="w-full border border-lattice/50 bg-lattice/10 py-4 text-sm tracking-widest2 text-lattice">{downloading?"正在生成固定 A4 PDF…":"下载 18 页完整 PDF · DOWNLOAD"}</button>{downloaded&&<p className="mt-3 text-center text-xs text-lattice">18 页完整档案已生成；十一篇主论与二十四证据均已收录。</p>}{downloadError&&<p className="mt-3 text-center text-xs text-rose-300">{downloadError}</p>}</div></main>;
}
