"use client";
import {useRef,useState} from "react";
import ReportReturnBar from "./ReportReturnBar";
import {PublicationCopy,PublicationLabel,PublicationPage} from "./PublicationPage";
import {PDF_ASSET_REGISTRY,productArtKey,selectPdfArt} from "@/lib/report-art-registry";
import type {DendriteReportEntry,ReportEvidenceLeaf} from "@/lib/mini/report-entry-library";

type Node={id:string;zh:string;en:string;score:number;actionZh?:string;actionEn?:string};
type Result={titleZh:string;titleEn:string;insightZh:string;insightEn:string;nodes:Node[];dominant:Node[];evidence?:{answered:number;total:number;historyProducts:number;sourceZh:string;sourceEn:string};evidenceLeaves?:ReportEvidenceLeaf[];reportEntries?:DendriteReportEntry[]};
const confidenceLabel={clear:"象已明",developing:"象渐成",open:"尚留白"} as const;
const cleanLegacyAnswer=(value:string)=>value.replace(/^在「[^」]+」这一情境里，我更接近「([^」]+)」[：:]\s*/u,"$1 · ");

export default function MiniDendriteReport({reportId,relationshipType,productId,productName,subjectName,createdAt,result}:{reportId:string;relationshipType?:string;productId:string;productName:string;subjectName:string;createdAt:string;result:Result}){
 const reportRef=useRef<HTMLDivElement>(null);const[downloading,setDownloading]=useState(false);const[downloaded,setDownloaded]=useState(false);const[downloadError,setDownloadError]=useState("");
 const artPool=PDF_ASSET_REGISTRY[productArtKey(productId,relationshipType)];const art=(page:number)=>selectPdfArt(artPool,reportId,page).src;const entries=(result.reportEntries??[]).slice(0,11);const leaves=result.evidenceLeaves??[];const total=16;
 const download=async()=>{if(!reportRef.current||downloading)return;setDownloading(true);setDownloadError("");try{const{exportPublicationPagesPdf}=await import("@/lib/pdf-export");await exportPublicationPagesPdf({containerRef:reportRef.current,fileName:`${productName}-完整场域档案.pdf`});setDownloaded(true)}catch(error){console.error(error);setDownloadError("PDF 未能完整生成。系统已阻止空图或残缺页面下载，请稍后重试；网页档案仍已保存。")}finally{setDownloading(false)}};
 return <main className="min-h-screen bg-[radial-gradient(circle_at_12%_8%,rgba(127,91,180,.34),transparent_30%),radial-gradient(circle_at_88%_24%,rgba(43,156,168,.28),transparent_35%),#0a1330] text-bone"><ReportReturnBar miniLabel="返回我的场域"/><div ref={reportRef} className="space-y-7 px-3 py-8 sm:px-6">
 <PublicationPage index={1} total={total} eyebrow="LINGXIFIELD DENDRITIC ARCHIVE" title={productName} art={art(1)} layout="cover"><PublicationLabel>档案主体 · {subjectName}</PublicationLabel><p className="mt-3 text-xs opacity-70">{new Date(createdAt).toLocaleString("zh-CN")}</p><p className="mt-7 max-w-xl font-display text-[22px] leading-[2] text-[#4c4a5b]">二十四问各留一叶；十一篇各立一题。相扶者见其势，相逆者见其隙，未有现实承接者不强作定论。</p><PublicationCopy>此卷不逐题评判，也不以三个标签代替一个人。每篇只照见一处结构，并给出可在日用中验证的一步。</PublicationCopy></PublicationPage>
 {entries.map((entry,i)=><PublicationPage key={entry.id} index={i+2} total={total} eyebrow={`第 ${String(i+1).padStart(2,"0")} 篇 · ${entry.chapterEn.toUpperCase()}`} title={entry.titleZh} art={art(i+2)}><article className="p-5 sm:p-7"><div className="flex items-start justify-between gap-5 border-b border-[#4c4966]/15 pb-4"><p className="max-w-[78%] font-display text-[15px] leading-7 text-[#557f79] sm:text-[17px]">{entry.briefZh}</p><span className="shrink-0 pt-1 text-[11px] tracking-[.18em] text-[#6a7884]">{confidenceLabel[entry.confidence]}</span></div><p className="mt-5 font-display text-[18px] leading-[2] text-[#343043] sm:text-[20px]">{entry.structureZh}</p><p className="mt-4 text-[15px] leading-[1.9] sm:text-[17px]">{entry.mechanismZh}</p><p className="mt-4 border-l border-[#78b8b7] pl-4 text-[15px] leading-[1.9] sm:text-[17px]">{entry.realityZh}</p>{entry.strengthZh&&<p className="mt-3 text-[14px] leading-[1.8] text-[#557f79]">{entry.strengthZh}</p>}{entry.costZh&&<p className="mt-3 text-[14px] leading-[1.8] text-[#6d4891]">{entry.costZh}</p>}<p className="mt-4 text-[15px] leading-[1.9] sm:text-[17px]">{entry.actionZh}</p><p className="mt-4 text-[13px] leading-[1.8] text-[#696473]">{entry.observationZh}</p></article></PublicationPage>)}
 {[0,1,2].map(group=><PublicationPage key={group} index={13+group} total={total} eyebrow="二十四问 · ORIGINAL ECHOES" title={`来处印记 ${String(group*8+1).padStart(2,"0")}—${String(Math.min(group*8+8,leaves.length||24)).padStart(2,"0")}`} art={art(13+group)}><div className="grid gap-3">{leaves.slice(group*8,group*8+8).map((leaf,i)=><article key={leaf.questionId} className="border-b border-[#4c4966]/15 pb-3"><PublicationLabel>{String(group*8+i+1).padStart(2,"0")} · 原始回声</PublicationLabel><p className="mt-1 text-[13px] leading-6 text-[#4b4654]">{leaf.promptZh}</p><p className="mt-1 font-display text-[14px] leading-6 text-[#557f79]">所应：{cleanLegacyAnswer(leaf.answerZh)}</p></article>)}</div><PublicationCopy muted>此页只留初始选择之来处。十一篇正文由复现、相扶、相逆与现实承接重新生长，不以单题定人。</PublicationCopy></PublicationPage>)}
 <PublicationPage index={16} total={total} eyebrow="LINGXIFIELD ORIGINAL FIELD" title="言止于证，行验于实" art={art(16)} layout="full"><PublicationCopy>辞贵简，义贵实；有据则言，无据则止。势有反复，明其所因；力有未发，辨其所蔽。十一篇所见，须落于日用；所行之事，须由现实反馈复验。</PublicationCopy><p className="mt-6 font-display text-2xl text-[#557f79]">见其所起 · 明其所蔽 · 行验其真</p><p className="mt-6 text-[11px] leading-6 opacity-75">用于个人探索与反思体验，不构成医疗、金融、法律或其他专业建议。</p></PublicationPage>
 </div><div className="mx-auto max-w-[794px] px-3 pb-16 sm:px-6"><button onClick={download} disabled={downloading} className="w-full border border-lattice/50 bg-lattice/10 py-4 text-sm tracking-widest2 text-lattice">{downloading?"正在生成固定 A4 PDF…":"下载 16 页完整 PDF · DOWNLOAD"}</button>{downloaded&&<p className="mt-3 text-center text-xs text-lattice">16 页完整档案已生成；十一篇主论与二十四道原始回声均已收录。</p>}{downloadError&&<p className="mt-3 text-center text-xs text-rose-300">{downloadError}</p>}</div></main>;
}
