"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import ReportReturnBar from "./ReportReturnBar";
import {PublicationCopy,PublicationLabel,PublicationPage} from "./PublicationPage";
import {PDF_ASSET_REGISTRY,productArtKey,selectPdfArt} from "@/lib/report-art-registry";
import type {DendriteReportEntry,ReportEvidenceLeaf} from "@/lib/mini/report-entry-library";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import {miniLocale,miniText} from "@/lib/mini-report-i18n";
import {localizeReportItemsChunked} from "@/lib/report-localize-client";

type Node={id:string;zh:string;en:string;score:number;actionZh?:string;actionEn?:string};
type Result={titleZh:string;titleEn:string;insightZh:string;insightEn:string;nodes:Node[];dominant:Node[];evidence?:{answered:number;total:number;historyProducts:number;sourceZh:string;sourceEn:string};evidenceLeaves?:ReportEvidenceLeaf[];reportEntries?:DendriteReportEntry[]};
const confidenceZh={clear:"象已明",developing:"象渐成",open:"尚留白"} as const;
const confidenceEn={clear:"Clear signal",developing:"Developing signal",open:"Open"} as const;
const cleanLegacyAnswer=(value:string)=>value.replace(/^在「[^」]+」这一情境里，我更接近「([^」]+)」[：:]\s*/u,"$1 · ");

export default function MiniDendriteReport({reportId,relationshipType,productId,productName,subjectName,createdAt,result}:{reportId:string;relationshipType?:string;productId:string;productName:string;subjectName:string;createdAt:string;result:Result}){
 const{lang}=useLingxiLang();const t=(zh:string,en:string)=>miniText(lang,zh,en);
 const reportRef=useRef<HTMLDivElement>(null);const[downloading,setDownloading]=useState(false);const[downloaded,setDownloaded]=useState(false);const[downloadError,setDownloadError]=useState("");
 const[translated,setTranslated]=useState<Record<string,string>>({});const[translationState,setTranslationState]=useState<"idle"|"loading"|"ready"|"error">("idle");
 const artPool=PDF_ASSET_REGISTRY[productArtKey(productId,relationshipType)];const art=(page:number)=>selectPdfArt(artPool,reportId,page).src;const entries=(result.reportEntries??[]).slice(0,11);const leaves=result.evidenceLeaves??[];const total=16;

 const pairs=useMemo(()=>{const x:{key:string;value:string}[]=[];entries.forEach((e,i)=>[
  ["title",e.titleEn],["brief",e.briefZh?e.briefEn:""],["structure",e.structureEn],["mechanism",e.mechanismEn],["reality",e.realityEn],["strength",e.strengthEn||""],["cost",e.costEn||""],["action",e.actionEn],["observation",e.observationEn]
 ].forEach(([k,v])=>{if(v)x.push({key:`e${i}.${k}`,value:v})}));leaves.forEach((l,i)=>{x.push({key:`l${i}.prompt`,value:l.promptEn});x.push({key:`l${i}.answer`,value:l.answerEn})});return x;},[entries,leaves]);

 useEffect(()=>{let dead=false;if(lang==="zh"||lang==="en"){setTranslated({});setTranslationState("ready");return()=>{dead=true};}setTranslationState("loading");setTranslated({});void localizeReportItemsChunked({reportKey:`mini-report:${reportId}`,targetLang:lang,items:pairs.map(p=>p.value)}).then(r=>{if(dead)return;if(!r.translated){setTranslationState("error");return;}const m:Record<string,string>={};pairs.forEach((p,i)=>m[p.key]=r.items[i]);setTranslated(m);setTranslationState("ready")}).catch(()=>!dead&&setTranslationState("error"));return()=>{dead=true};},[lang,reportId,pairs]);

 const pick=(key:string,zh:string,en:string)=>lang==="zh"?zh:lang==="en"?en:(translated[key]||en);
 const ready=lang==="zh"||lang==="en"||translationState==="ready";
 const download=async()=>{if(!reportRef.current||downloading||!ready)return;setDownloading(true);setDownloadError("");try{const{exportPublicationPagesPdf}=await import("@/lib/pdf-export");await exportPublicationPagesPdf({containerRef:reportRef.current,fileName:`LINGXIFIELD-${productId}-${lang}.pdf`});setDownloaded(true)}catch(error){console.error(error);setDownloadError(t("PDF 未能完整生成。系统已阻止空图或残缺页面下载，请稍后重试；网页档案仍已保存。","The PDF could not be generated completely. Empty or incomplete pages were blocked; try again later. The web archive remains saved."));}finally{setDownloading(false)}};

 return <main className="min-h-screen bg-[radial-gradient(circle_at_12%_8%,rgba(127,91,180,.34),transparent_30%),radial-gradient(circle_at_88%_24%,rgba(43,156,168,.28),transparent_35%),#0a1330] text-bone"><ReportReturnBar miniLabel="返回我的场域" miniLabelEn="Back to My Field"/>
 {lang!=="zh"&&lang!=="en"&&translationState==="loading"&&<p className="mx-auto max-w-[794px] px-4 pt-4 text-center text-xs text-lattice">{t("正在准备当前语言…","Preparing current language…")}</p>}
 {translationState==="error"&&<p className="mx-auto max-w-[794px] px-4 pt-4 text-center text-xs text-rose-300">{t("当前语言生成失败，请稍后重试。为避免语言不一致，PDF 下载已暂时关闭。","Could not prepare the current language. Please try again later. PDF download is disabled to avoid a language mismatch.")}</p>}
 <div ref={reportRef} className="space-y-7 px-3 py-8 sm:px-6">
 <PublicationPage index={1} total={total} eyebrow="LINGXIFIELD DENDRITIC ARCHIVE" title={productName} art={art(1)} layout="cover"><PublicationLabel>{t("档案主体","Archive subject")} · {subjectName}</PublicationLabel><p className="mt-3 text-xs opacity-70">{new Date(createdAt).toLocaleString(miniLocale(lang))}</p><p className="mt-7 max-w-xl font-display text-[22px] leading-[2] text-[#4c4a5b]">{lang==="zh"?"二十四问各留一叶；十一篇各立一题。相扶者见其势，相逆者见其隙，未有现实承接者不强作定论。":"Twenty-four questions leave twenty-four evidence leaves; eleven chapters each hold one question. Supporting patterns show momentum, contradictions preserve gaps, and no conclusion is forced without real-world support."}</p><PublicationCopy>{lang==="zh"?"此卷不逐题评判，也不以三个标签代替一个人。每篇只照见一处结构，并给出可在日用中验证的一步。":"This archive does not judge question by question or reduce a person to labels. Each chapter illuminates one structure and offers one step that can be checked in daily life."}</PublicationCopy></PublicationPage>
 {entries.map((entry,i)=><PublicationPage key={entry.id} index={i+2} total={total} eyebrow={`${lang==="zh"?`第 ${String(i+1).padStart(2,"0")} 篇`:`CHAPTER ${String(i+1).padStart(2,"0")}`} · ${entry.chapterEn.toUpperCase()}`} title={pick(`e${i}.title`,entry.titleZh,entry.titleEn)} art={art(i+2)}><article className="p-5 sm:p-7"><div className="flex items-start justify-between gap-5 border-b border-[#4c4966]/15 pb-4"><p className="max-w-[78%] font-display text-[15px] leading-7 text-[#557f79] sm:text-[17px]">{pick(`e${i}.brief`,entry.briefZh,entry.briefEn)}</p><span className="shrink-0 pt-1 text-[11px] tracking-[.18em] text-[#6a7884]">{lang==="zh"?confidenceZh[entry.confidence]:confidenceEn[entry.confidence]}</span></div><p className="mt-5 font-display text-[18px] leading-[2] text-[#343043] sm:text-[20px]">{pick(`e${i}.structure`,entry.structureZh,entry.structureEn)}</p><p className="mt-4 text-[15px] leading-[1.9] sm:text-[17px]">{pick(`e${i}.mechanism`,entry.mechanismZh,entry.mechanismEn)}</p><p className="mt-4 border-l border-[#78b8b7] pl-4 text-[15px] leading-[1.9] sm:text-[17px]">{pick(`e${i}.reality`,entry.realityZh,entry.realityEn)}</p>{(entry.strengthZh||entry.strengthEn)&&<p className="mt-3 text-[14px] leading-[1.8] text-[#557f79]">{pick(`e${i}.strength`,entry.strengthZh||"",entry.strengthEn||"")}</p>}{(entry.costZh||entry.costEn)&&<p className="mt-3 text-[14px] leading-[1.8] text-[#6d4891]">{pick(`e${i}.cost`,entry.costZh||"",entry.costEn||"")}</p>}<p className="mt-4 text-[15px] leading-[1.9] sm:text-[17px]">{pick(`e${i}.action`,entry.actionZh,entry.actionEn)}</p><p className="mt-4 text-[13px] leading-[1.8] text-[#696473]">{pick(`e${i}.observation`,entry.observationZh,entry.observationEn)}</p></article></PublicationPage>)}
 {[0,1,2].map(group=><PublicationPage key={group} index={13+group} total={total} eyebrow={t("二十四问 · 原始回声","Twenty-four questions · Original echoes")} title={`${lang==="zh"?"来处印记":"Source marks"} ${String(group*8+1).padStart(2,"0")}—${String(Math.min(group*8+8,leaves.length||24)).padStart(2,"0")}`} art={art(13+group)}><div className="grid gap-3">{leaves.slice(group*8,group*8+8).map((leaf,i)=>{const gi=group*8+i;return <article key={leaf.questionId} className="border-b border-[#4c4966]/15 pb-3"><PublicationLabel>{String(gi+1).padStart(2,"0")} · {t("原始回声","Original echo")}</PublicationLabel><p className="mt-1 text-[13px] leading-6 text-[#4b4654]">{pick(`l${gi}.prompt`,leaf.promptZh,leaf.promptEn)}</p><p className="mt-1 font-display text-[14px] leading-6 text-[#557f79]">{t("所应","Response")}：{lang==="zh"?cleanLegacyAnswer(leaf.answerZh):pick(`l${gi}.answer`,leaf.answerZh,leaf.answerEn)}</p></article>})}</div><PublicationCopy muted>{lang==="zh"?"此页只留初始选择之来处。十一篇正文由复现、相扶、相逆与现实承接重新生长，不以单题定人。":"This page preserves the source of the initial choices. The eleven chapters are rebuilt from recurrence, support, contradiction and real-world uptake rather than defining a person by any single answer."}</PublicationCopy></PublicationPage>)}
 <PublicationPage index={16} total={total} eyebrow="LINGXIFIELD ORIGINAL FIELD" title={lang==="zh"?"言止于证，行验于实":"Claims stop where evidence stops"} art={art(16)} layout="full"><PublicationCopy>{lang==="zh"?"辞贵简，义贵实；有据则言，无据则止。势有反复，明其所因；力有未发，辨其所蔽。十一篇所见，须落于日用；所行之事，须由现实反馈复验。":"Keep language concise and meaning grounded: speak where evidence exists and stop where it does not. Recurring patterns require causes; latent capacity requires its constraints to be seen. The eleven readings must return to daily life and be checked against real feedback."}</PublicationCopy><p className="mt-6 font-display text-2xl text-[#557f79]">{lang==="zh"?"见其所起 · 明其所蔽 · 行验其真":"See the source · name the constraint · test in reality"}</p><p className="mt-6 text-[11px] leading-6 opacity-75">{lang==="zh"?"用于个人探索与反思体验，不构成医疗、金融、法律或其他专业建议。":"For personal exploration and reflection only; not medical, financial, legal or other professional advice."}</p></PublicationPage>
 </div><div className="mx-auto max-w-[794px] px-3 pb-16 sm:px-6"><button onClick={download} disabled={downloading||!ready} className="w-full border border-lattice/50 bg-lattice/10 py-4 text-sm tracking-widest2 text-lattice disabled:opacity-40">{downloading?t("正在生成固定 A4 PDF…","Generating fixed A4 PDF…"):translationState==="loading"?t("正在准备当前语言…","Preparing current language…"):t("下载 16 页完整 PDF","Download complete 16-page PDF")}</button>{downloaded&&<p className="mt-3 text-center text-xs text-lattice">{t("完整档案已生成。","Complete archive generated.")}</p>}{downloadError&&<p className="mt-3 text-center text-xs text-rose-300">{downloadError}</p>}</div></main>;
}
