import type{LingxiLang}from"@/lib/lingxi-i18n";
import{SASI_SKILLS}from"./catalog";
import type{SasiMode,SasiSkillId}from"./types";

type Copy={label:string;description:string};
type Local=Record<LingxiLang,Copy>;
const V=(zh:Copy,en:Copy,ja:Copy,ko:Copy,fr:Copy,de:Copy,es:Copy,pt:Copy,ar:Copy):Local=>({zh,en,ja,ko,fr,de,es,pt,ar});
const C:Record<SasiSkillId,Local>={
"drama-script":{"zh":{"label":"剧本与节奏","description":"剧本与节奏"},"en":{"label":"Script and pacing","description":"Script and pacing"},"ja":{"label":"脚本とテンポ","description":"脚本とテンポ"},"ko":{"label":"대본과 흐름","description":"대본과 흐름"},"fr":{"label":"Scénario et rythme","description":"Scénario et rythme"},"de":{"label":"Drehbuch und Tempo","description":"Drehbuch und Tempo"},"es":{"label":"Guion y ritmo","description":"Guion y ritmo"},"pt":{"label":"Roteiro e ritmo","description":"Roteiro e ritmo"},"ar":{"label":"السيناريو والإيقاع","description":"السيناريو والإيقاع"}},
"drama-storyboard":{"zh":{"label":"电影分镜","description":"电影分镜"},"en":{"label":"Shot planning","description":"Shot planning"},"ja":{"label":"絵コンテ","description":"絵コンテ"},"ko":{"label":"장면 구성","description":"장면 구성"},"fr":{"label":"Découpage des plans","description":"Découpage des plans"},"de":{"label":"Szenenplanung","description":"Szenenplanung"},"es":{"label":"Planificar escenas","description":"Planificar escenas"},"pt":{"label":"Planejar cenas","description":"Planejar cenas"},"ar":{"label":"تخطيط اللقطات","description":"تخطيط اللقطات"}},
"drama-visual":{"zh":{"label":"角色视觉与关键帧","description":"角色视觉与关键帧"},"en":{"label":"Characters and keyframes","description":"Characters and keyframes"},"ja":{"label":"人物デザインとキーフレーム","description":"人物デザインとキーフレーム"},"ko":{"label":"인물 디자인과 키프레임","description":"인물 디자인과 키프레임"},"fr":{"label":"Personnages et images clés","description":"Personnages et images clés"},"de":{"label":"Figuren und Schlüsselbilder","description":"Figuren und Schlüsselbilder"},"es":{"label":"Personajes y fotogramas clave","description":"Personajes y fotogramas clave"},"pt":{"label":"Personagens e quadros-chave","description":"Personagens e quadros-chave"},"ar":{"label":"الشخصيات والإطارات الرئيسية","description":"الشخصيات والإطارات الرئيسية"}},
"drama-sound":{"zh":{"label":"配音与声音设计","description":"配音与声音设计"},"en":{"label":"Voice and sound planning","description":"Voice and sound planning"},"ja":{"label":"声と音の設計","description":"声と音の設計"},"ko":{"label":"대사와 사운드 설계","description":"대사와 사운드 설계"},"fr":{"label":"Voix et conception sonore","description":"Voix et conception sonore"},"de":{"label":"Stimme und Klangplanung","description":"Stimme und Klangplanung"},"es":{"label":"Voz y diseño de sonido","description":"Voz y diseño de sonido"},"pt":{"label":"Voz e desenho sonoro","description":"Voz e desenho sonoro"},"ar":{"label":"تخطيط الصوت والتعليق","description":"تخطيط الصوت والتعليق"}},
"teaching-practice":{"zh":{"label":"讲解与练习","description":"讲解与练习"},"en":{"label":"Examples and practice","description":"Examples and practice"},"ja":{"label":"解説と練習","description":"解説と練習"},"ko":{"label":"설명과 연습","description":"설명과 연습"},"fr":{"label":"Explications et exercices","description":"Explications et exercices"},"de":{"label":"Erklärungen und Übungen","description":"Erklärungen und Übungen"},"es":{"label":"Explicaciones y ejercicios","description":"Explicaciones y ejercicios"},"pt":{"label":"Explicações e exercícios","description":"Explicações e exercícios"},"ar":{"label":"الشرح والتدريب","description":"الشرح والتدريب"}},
"source-comparison":{"zh":{"label":"观点对照","description":"观点对照"},"en":{"label":"Compare viewpoints","description":"Compare viewpoints"},"ja":{"label":"見解を比較","description":"見解を比較"},"ko":{"label":"관점 비교","description":"관점 비교"},"fr":{"label":"Comparer les points de vue","description":"Comparer les points de vue"},"de":{"label":"Standpunkte vergleichen","description":"Standpunkte vergleichen"},"es":{"label":"Comparar perspectivas","description":"Comparar perspectivas"},"pt":{"label":"Comparar perspectivas","description":"Comparar perspectivas"},"ar":{"label":"مقارنة الآراء","description":"مقارنة الآراء"}},
 "agent-skill-discovery":V({label:"自动匹配能力",description:"只启用当前任务真正需要的能力"},{label:"Automatic skill matching",description:"Enable only capabilities relevant to this task"},{label:"能力を自動選択",description:"このタスクに必要な機能だけを有効化"},{label:"기능 자동 선택",description:"현재 작업에 필요한 기능만 활성화"},{label:"Sélection automatique",description:"Activer seulement les capacités utiles à cette tâche"},{label:"Fähigkeiten automatisch wählen",description:"Nur für diese Aufgabe relevante Fähigkeiten aktivieren"},{label:"Selección automática",description:"Activar solo las capacidades relevantes para esta tarea"},{label:"Seleção automática",description:"Ativar apenas capacidades relevantes para esta tarefa"},{label:"اختيار القدرات تلقائيًا",description:"تفعيل القدرات اللازمة لهذه المهمة فقط"}),
 "document-understanding":V({label:"理解文档",description:"读懂 PDF、Word、PPT、表格与电子书的结构和内容"},{label:"Understand documents",description:"Read structure and content from documents and spreadsheets"},{label:"文書を理解",description:"文書や表の構造と内容を読み取る"},{label:"문서 이해",description:"문서와 표의 구조와 내용을 이해"},{label:"Comprendre les documents",description:"Lire la structure et le contenu des documents"},{label:"Dokumente verstehen",description:"Struktur und Inhalt von Dokumenten erfassen"},{label:"Comprender documentos",description:"Leer estructura y contenido de documentos"},{label:"Entender documentos",description:"Ler estrutura e conteúdo de documentos"},{label:"فهم المستندات",description:"قراءة بنية ومحتوى المستندات والجداول"}),
 "semantic-retrieval":V({label:"查找相关原文",description:"从资料中优先找到真正相关的段落"},{label:"Find relevant passages",description:"Find the most relevant passages in your sources"},{label:"関連する原文を探す",description:"資料から本当に関連する箇所を優先して探す"},{label:"관련 원문 찾기",description:"자료에서 가장 관련 있는 부분을 우선 찾기"},{label:"Trouver des passages",description:"Trouver les passages les plus pertinents dans vos sources"},{label:"Passende Textstellen finden",description:"Die relevantesten Stellen in Quellen finden"},{label:"Buscar pasajes relevantes",description:"Encontrar los pasajes más relevantes en tus fuentes"},{label:"Encontrar trechos relevantes",description:"Encontrar os trechos mais relevantes nas fontes"},{label:"العثور على المقاطع ذات الصلة",description:"العثور على المقاطع الأكثر صلة في المصادر"}),
 "evidence-grounding":V({label:"原文溯源",description:"重要结论尽量回到你提供的原文证据"},{label:"Source grounding",description:"Tie important conclusions back to your supplied sources"},{label:"原文に基づく回答",description:"重要な結論を提供資料の根拠へ戻す"},{label:"원문 근거",description:"중요한 결론을 제공한 원문 근거와 연결"},{label:"Ancrage dans les sources",description:"Relier les conclusions importantes aux sources fournies"},{label:"Quellenbezug",description:"Wichtige Aussagen auf bereitgestellte Quellen zurückführen"},{label:"Fundamentar en fuentes",description:"Vincular conclusiones importantes con las fuentes aportadas"},{label:"Basear nas fontes",description:"Ligar conclusões importantes às fontes fornecidas"},{label:"الاستناد إلى المصدر",description:"ربط الاستنتاجات المهمة بالمصادر التي قدمتها"}),
 "structured-output":V({label:"结构化整理",description:"把结果整理成清单、表格、提纲或固定结构"},{label:"Structured output",description:"Organize results as lists, tables, outlines or schemas"},{label:"構造化整理",description:"結果をリスト、表、アウトラインなどに整理"},{label:"구조화 정리",description:"결과를 목록, 표, 개요 등의 구조로 정리"},{label:"Résultat structuré",description:"Organiser en listes, tableaux, plans ou schémas"},{label:"Strukturierte Ausgabe",description:"Ergebnisse als Listen, Tabellen oder Gliederungen ordnen"},{label:"Salida estructurada",description:"Organizar resultados en listas, tablas o esquemas"},{label:"Saída estruturada",description:"Organizar resultados em listas, tabelas ou esquemas"},{label:"تنظيم هيكلي",description:"تنظيم النتائج في قوائم أو جداول أو مخططات"}),
 "web-research":V({label:"网络研究",description:"需要最新资料时补充公开网页信息"},{label:"Web research",description:"Add fresh public web evidence when needed"},{label:"Web調査",description:"必要なとき最新の公開Web情報を補足"},{label:"웹 연구",description:"필요할 때 최신 공개 웹 자료를 보강"},{label:"Recherche web",description:"Ajouter des informations publiques récentes si nécessaire"},{label:"Web-Recherche",description:"Bei Bedarf aktuelle öffentliche Web-Quellen ergänzen"},{label:"Investigación web",description:"Añadir información pública reciente cuando haga falta"},{label:"Pesquisa na web",description:"Adicionar fontes públicas recentes quando necessário"},{label:"بحث على الويب",description:"إضافة معلومات عامة حديثة عند الحاجة"}),
 "browser-execution":V({label:"网页操作",description:"需要网页交互时再使用浏览器完成步骤"},{label:"Web actions",description:"Use browser interaction when a task truly needs it"},{label:"Web操作",description:"必要な場合だけブラウザ操作を使う"},{label:"웹 작업",description:"필요한 경우에만 브라우저 상호작용 사용"},{label:"Actions web",description:"Utiliser le navigateur seulement lorsque nécessaire"},{label:"Web-Aktionen",description:"Browser-Interaktion nur bei echtem Bedarf nutzen"},{label:"Acciones web",description:"Usar interacción del navegador solo cuando sea necesario"},{label:"Ações na web",description:"Usar interação no navegador apenas quando necessário"},{label:"إجراءات الويب",description:"استخدام تفاعل المتصفح فقط عند الحاجة"}),
 "multi-model-routing":V({label:"自动选择能力",description:"根据任务需要自动选择合适的智能能力"},{label:"Automatic capability choice",description:"Choose suitable intelligence capabilities for the task"},{label:"能力を自動選択",description:"タスクに合う知能機能を自動で選ぶ"},{label:"능력 자동 선택",description:"작업에 맞는 지능 기능을 자동 선택"},{label:"Choix automatique",description:"Choisir automatiquement les capacités adaptées"},{label:"Automatische Auswahl",description:"Passende Fähigkeiten automatisch auswählen"},{label:"Elección automática",description:"Elegir automáticamente las capacidades adecuadas"},{label:"Escolha automática",description:"Escolher automaticamente as capacidades adequadas"},{label:"اختيار القدرة تلقائيًا",description:"اختيار القدرات المناسبة للمهمة تلقائيًا"}),
 "workflow-orchestration":V({label:"多步骤处理",description:"把复杂任务拆成步骤并持续推进"},{label:"Multi-step work",description:"Break complex work into clear steps and continue reliably"},{label:"複数ステップ処理",description:"複雑な作業を段階に分けて進める"},{label:"다단계 처리",description:"복잡한 작업을 단계로 나누어 안정적으로 진행"},{label:"Travail en plusieurs étapes",description:"Découper les tâches complexes en étapes fiables"},{label:"Mehrstufige Arbeit",description:"Komplexe Aufgaben in klare Schritte zerlegen"},{label:"Trabajo por pasos",description:"Dividir tareas complejas en pasos claros"},{label:"Trabalho em etapas",description:"Dividir tarefas complexas em etapas claras"},{label:"عمل متعدد الخطوات",description:"تقسيم المهام المعقدة إلى خطوات واضحة"}),
 "observability":V({label:"任务进度与恢复",description:"保留执行状态，便于失败后继续"},{label:"Progress & recovery",description:"Keep execution state so work can continue after failures"},{label:"進捗と復元",description:"実行状態を保ち、失敗後も続けられるようにする"},{label:"진행 및 복구",description:"실행 상태를 보존해 실패 후 이어서 진행"},{label:"Progression et reprise",description:"Conserver l’état pour reprendre après un échec"},{label:"Fortschritt & Wiederaufnahme",description:"Ausführungsstatus für die Wiederaufnahme erhalten"},{label:"Progreso y recuperación",description:"Conservar el estado para continuar tras un fallo"},{label:"Progresso e recuperação",description:"Manter o estado para continuar após falhas"},{label:"التقدم والاستئناف",description:"حفظ حالة التنفيذ للمتابعة بعد الفشل"}),
 "multimodal-continuity":V({label:"人物与场景连续",description:"保持角色、服装、场景与参考的一致性"},{label:"Character & scene continuity",description:"Keep characters, wardrobe, scenes and references consistent"},{label:"人物・シーンの連続性",description:"人物、衣装、場面、参照の一貫性を保つ"},{label:"인물·장면 연속성",description:"인물, 의상, 장면, 참고 자료의 일관성 유지"},{label:"Continuité personnages/scènes",description:"Préserver personnages, tenues, scènes et références"},{label:"Figuren- & Szenenkontinuität",description:"Figuren, Kleidung, Szenen und Referenzen konsistent halten"},{label:"Continuidad de personajes y escenas",description:"Mantener personajes, vestuario, escenas y referencias"},{label:"Continuidade de personagens e cenas",description:"Manter personagens, figurino, cenas e referências"},{label:"استمرارية الشخصيات والمشاهد",description:"الحفاظ على اتساق الشخصيات والملابس والمشاهد والمراجع"}),
 "website-production":V({label:"完整网站构建",description:"从结构、页面到导出与部署准备一起完成"},{label:"Complete website build",description:"Build structure, pages, export and deployment readiness"},{label:"Webサイト一式を構築",description:"構成、ページ、書き出し、公開準備までまとめて作る"},{label:"완성형 웹사이트 구축",description:"구조, 페이지, 내보내기, 배포 준비까지 함께 구성"},{label:"Construction complète du site",description:"Créer structure, pages, export et préparation au déploiement"},{label:"Komplette Website erstellen",description:"Struktur, Seiten, Export und Deployment-Vorbereitung erstellen"},{label:"Construcción completa del sitio",description:"Crear estructura, páginas, exportación y preparación de despliegue"},{label:"Construção completa do site",description:"Criar estrutura, páginas, exportação e preparação para implantação"},{label:"بناء موقع متكامل",description:"إنشاء البنية والصفحات والتصدير والاستعداد للنشر"})
};
export const USER_SELECTABLE_SKILLS:Record<SasiMode,SasiSkillId[]>={drama:["multimodal-continuity","drama-script","drama-storyboard","drama-visual","drama-sound","observability"],website:["website-production","document-understanding","structured-output","workflow-orchestration"],book:["document-understanding","semantic-retrieval","evidence-grounding","teaching-practice","source-comparison","structured-output"],learning:["document-understanding","semantic-retrieval","evidence-grounding","teaching-practice","source-comparison","structured-output"],research:["document-understanding","semantic-retrieval","evidence-grounding","web-research","source-comparison","structured-output"]};
export function sasiSkillUi(mode:SasiMode,lang:LingxiLang){return USER_SELECTABLE_SKILLS[mode].filter(id=>Boolean(SASI_SKILLS[id])).map(id=>({id,...C[id][lang]}));}
