const { SUPPORTED, getLanguage, setLanguage } = require('../../utils/i18n')
const CURRENCIES=[{id:'CNY',label:'CNY ¥ 人民币'},{id:'USD',label:'USD $ 美元'}]
const KEY='lx_currency'
const TEXT={
 'zh-CN':{kicker:'账户设置',title:'常用偏好放在这里',subtitle:'语言、币种和账户常用入口都可以在这里调整。',language:'语言',currency:'支付币种',currencyNote:'CNY 与 USD 独立定价，不按实时汇率换算。',account:'账户与服务',notifications:'消息与公告',balance:'余额与充值',withdraw:'余额提现',privacy:'隐私政策',terms:'用户服务协议',release:'版本与更新',changedCny:'已切换人民币',changedUsd:'已切换美元'},
 en:{kicker:'Account settings',title:'Your everyday preferences',subtitle:'Language, currency and account shortcuts are kept here.',language:'Language',currency:'Payment currency',currencyNote:'CNY and USD use independent pricing, not live exchange-rate conversion.',account:'Account & services',notifications:'Notifications',balance:'Balance & top-up',withdraw:'Balance withdrawal',privacy:'Privacy',terms:'Terms',release:'Release & updates',changedCny:'Switched to CNY',changedUsd:'Switched to USD'},
 ja:{kicker:'アカウント設定',title:'よく使う設定をここに',subtitle:'言語、通貨、アカウント入口をまとめて調整できます。',language:'言語',currency:'支払い通貨',currencyNote:'CNY と USD は独立価格で、リアルタイム為替換算ではありません。',account:'アカウントとサービス',notifications:'通知',balance:'残高とチャージ',withdraw:'残高の出金',privacy:'プライバシー',terms:'利用規約',release:'更新',changedCny:'CNY に切替',changedUsd:'USD に切替'},
 ko:{kicker:'계정 설정',title:'자주 쓰는 설정',subtitle:'언어, 통화, 계정 바로가기를 여기서 조정하세요.',language:'언어',currency:'결제 통화',currencyNote:'CNY와 USD는 독립 가격이며 실시간 환율로 환산하지 않습니다.',account:'계정 및 서비스',notifications:'알림',balance:'잔액 및 충전',withdraw:'잔액 출금',privacy:'개인정보',terms:'이용약관',release:'업데이트',changedCny:'CNY로 전환',changedUsd:'USD로 전환'},
 fr:{kicker:'Paramètres du compte',title:'Vos préférences courantes',subtitle:'Langue, devise et accès du compte sont regroupés ici.',language:'Langue',currency:'Devise de paiement',currencyNote:'CNY et USD ont des tarifs indépendants, sans conversion en temps réel.',account:'Compte et services',notifications:'Notifications',balance:'Solde et recharge',withdraw:'Retrait du solde',privacy:'Confidentialité',terms:'Conditions',release:'Mises à jour',changedCny:'Passé en CNY',changedUsd:'Passé en USD'},
 de:{kicker:'Kontoeinstellungen',title:'Wichtige Einstellungen',subtitle:'Sprache, Währung und Kontozugänge an einem Ort.',language:'Sprache',currency:'Zahlungswährung',currencyNote:'CNY und USD haben unabhängige Preise ohne Live-Umrechnung.',account:'Konto & Dienste',notifications:'Mitteilungen',balance:'Guthaben & Aufladen',withdraw:'Guthaben auszahlen',privacy:'Datenschutz',terms:'Bedingungen',release:'Updates',changedCny:'CNY gewählt',changedUsd:'USD gewählt'},
 es:{kicker:'Ajustes de cuenta',title:'Tus preferencias habituales',subtitle:'Idioma, moneda y accesos de cuenta en un solo lugar.',language:'Idioma',currency:'Moneda de pago',currencyNote:'CNY y USD usan precios independientes, sin conversión en tiempo real.',account:'Cuenta y servicios',notifications:'Notificaciones',balance:'Saldo y recarga',withdraw:'Retirar saldo',privacy:'Privacidad',terms:'Términos',release:'Novedades',changedCny:'Cambiado a CNY',changedUsd:'Cambiado a USD'},
 pt:{kicker:'Configurações da conta',title:'Suas preferências',subtitle:'Idioma, moeda e atalhos da conta em um só lugar.',language:'Idioma',currency:'Moeda de pagamento',currencyNote:'CNY e USD têm preços independentes, sem conversão em tempo real.',account:'Conta e serviços',notifications:'Notificações',balance:'Saldo e recarga',withdraw:'Sacar saldo',privacy:'Privacidade',terms:'Termos',release:'Atualizações',changedCny:'Alterado para CNY',changedUsd:'Alterado para USD'},
 ar:{kicker:'إعدادات الحساب',title:'تفضيلاتك اليومية',subtitle:'اللغة والعملة وروابط الحساب في مكان واحد.',language:'اللغة',currency:'عملة الدفع',currencyNote:'تسعير CNY وUSD مستقل ولا يعتمد على سعر الصرف المباشر.',account:'الحساب والخدمات',notifications:'الإشعارات',balance:'الرصيد والشحن',withdraw:'سحب الرصيد',privacy:'الخصوصية',terms:'الشروط',release:'التحديثات',changedCny:'تم اختيار CNY',changedUsd:'تم اختيار USD'}
}
Page({
 data:{languages:SUPPORTED,languageIndex:0,currencies:CURRENCIES,currencyIndex:0,copy:TEXT['zh-CN']},
 onLoad(){this.refresh()},
 onShow(){this.refresh()},
 refresh(){const lang=getLanguage(),languageIndex=Math.max(0,SUPPORTED.findIndex(x=>x.id===lang));const saved=wx.getStorageSync(KEY)||'CNY',currencyIndex=Math.max(0,CURRENCIES.findIndex(x=>x.id===saved));this.setData({copy:TEXT[lang]||TEXT['zh-CN'],languageIndex,currencyIndex})},
 changeLanguage(e){const item=SUPPORTED[Number(e.detail.value)];if(!item)return;setLanguage(item.id);this.refresh()},
 changeCurrency(e){const item=CURRENCIES[Number(e.detail.value)];if(!item)return;wx.setStorageSync(KEY,item.id);this.setData({currencyIndex:Number(e.detail.value)});wx.showToast({title:item.id==='CNY'?this.data.copy.changedCny:this.data.copy.changedUsd,icon:'none'})},
 go(e){const path=e.currentTarget.dataset.path;if(!path)return;wx.navigateTo({url:`/pages/web/index?path=${encodeURIComponent(path)}&currency=${CURRENCIES[this.data.currencyIndex].id}`})},
 goNotifications(){wx.navigateTo({url:'/pages/notifications/index'})}
})
