import type {SeoLocale} from './global-seo';
import {getTool} from '@/lib/tools/registry';

type LocalText=Record<SeoLocale,string>;
const L=(zh:string,en:string,ja:string,ko:string,fr:string,de:string,es:string,pt:string,ar:string):LocalText=>({zh,en,ja,ko,fr,de,es,pt,ar});
export const FACT_LABELS={
 input:L('输入与输出','Input and output','入力と出力','입력과 출력','Entrée et sortie','Eingabe und Ausgabe','Entrada y salida','Entrada e saída','الإدخال والإخراج'),
 limits:L('使用前须知','Before you start','利用前の確認','시작 전 확인','Avant de commencer','Vor dem Start','Antes de empezar','Antes de começar','قبل البدء'),
 related:L('相关工具','Related tools','関連ツール','관련 도구','Outils associés','Ähnliche Tools','Herramientas relacionadas','Ferramentas relacionadas','أدوات ذات صلة'),
 products:L('全部产品','All products','すべての製品','모든 제품','Tous les produits','Alle Produkte','Todos los productos','Todos os produtos','جميع المنتجات'),
 sources:L('资料来源','Sources','情報源','자료 출처','Sources','Quellen','Fuentes','Fontes','المصادر'),
 review:L('检查结果，再保存需要的文件。','Review the result, then save the files you need.','結果を確認して必要なファイルを保存します。','결과를 확인하고 필요한 파일을 저장하세요.','Vérifiez le résultat, puis enregistrez les fichiers utiles.','Prüfe das Ergebnis und speichere die benötigten Dateien.','Revisa el resultado y guarda los archivos que necesites.','Confira o resultado e salve os arquivos necessários.','راجع النتيجة ثم احفظ الملفات التي تحتاجها.'),
 choose:L('选择文件或输入内容，按页面提示设置选项。','Choose files or enter content and set the options shown on the page.','ファイルまたは内容を入力し、画面の設定を確認します。','파일이나 내용을 입력하고 화면의 옵션을 설정하세요.','Choisissez les fichiers ou saisissez le contenu, puis réglez les options.','Wähle Dateien oder gib Inhalte ein und passe die Optionen an.','Elige archivos o introduce contenido y ajusta las opciones.','Escolha arquivos ou insira conteúdo e ajuste as opções.','اختر الملفات أو أدخل المحتوى واضبط الخيارات المتاحة.'),
 limitsGeneral:L('支持范围以工具中的格式、大小与选项为准。先保留原件；如需付费，确认费用后再执行。','Check supported formats, sizes and options in the tool. Keep originals; confirm any charge before paid processing.','対応形式・容量・設定はツール内で確認してください。原本を保管し、有料処理は料金確認後に実行します。','지원 형식·크기·옵션을 확인하세요. 원본을 보관하고 유료 처리는 요금 확인 후 실행하세요.','Vérifiez les formats, tailles et options acceptés. Gardez les originaux et confirmez le coût avant tout traitement payant.','Prüfe Formate, Größen und Optionen im Tool. Bewahre Originale auf und bestätige Kosten vor kostenpflichtiger Verarbeitung.','Comprueba formatos, tamaños y opciones. Conserva los originales y confirma el coste antes del procesamiento de pago.','Confira formatos, tamanhos e opções. Guarde os originais e confirme o custo antes do processamento pago.','تحقق من الصيغ والأحجام والخيارات. احتفظ بالأصول وأكد التكلفة قبل المعالجة المدفوعة.'),
};

const FACTS={
 image:L('处理照片或截图，调整格式、大小或画面后预览并保存图片。','Process photos or screenshots, adjust the format, size or image, then preview and save.','写真やスクリーンショットの形式・サイズ・画像を調整し、確認して保存します。','사진이나 스크린샷의 형식·크기·화면을 조정한 뒤 확인하고 저장합니다.','Modifiez le format, la taille ou le contenu visuel de photos et captures, puis prévisualisez et enregistrez.','Bearbeite Format, Größe oder Bildinhalt von Fotos und Screenshots, prüfe und speichere das Ergebnis.','Ajusta el formato, tamaño o imagen de fotos y capturas; revisa y guarda el resultado.','Ajuste formato, tamanho ou imagem de fotos e capturas; confira e salve o resultado.','عالج الصور أو لقطات الشاشة وعدّل الصيغة أو الحجم أو الصورة ثم عاين واحفظ.'),
 pdf:L('选择 PDF 或页面素材，按工具选项处理页序、内容或文件格式，检查预览后导出。','Choose a PDF or page material, use the page, content or format options, and check the preview before export.','PDFやページ素材を選び、ページ・内容・形式を設定し、プレビュー後に書き出します。','PDF 또는 페이지 자료를 선택하고 페이지·내용·형식 옵션을 조정한 뒤 미리보기를 확인하여 내보냅니다.','Choisissez un PDF ou des pages, réglez les options de pages, contenu ou format et vérifiez avant export.','Wähle PDF- oder Seitenmaterial, stelle Seiten-, Inhalts- oder Formatoptionen ein und prüfe die Vorschau vor dem Export.','Elige un PDF o material de páginas, ajusta páginas, contenido o formato y revisa antes de exportar.','Escolha um PDF ou material de páginas, ajuste páginas, conteúdo ou formato e confira antes de exportar.','اختر PDF أو مواد الصفحات واضبط خيارات الصفحات أو المحتوى أو الصيغة ثم تحقق قبل التصدير.'),
 text:L('输入或粘贴文字，按所选规则转换、整理或统计；可复制处理结果。','Enter or paste text to convert, organize or count it using the selected rules; copy the result.','文字を入力・貼り付けし、ルールに沿って変換・整理・集計して結果をコピーできます。','텍스트를 입력하거나 붙여 넣어 규칙에 따라 변환·정리·계산하고 결과를 복사합니다.','Saisissez ou collez du texte pour le convertir, organiser ou compter selon les règles choisies, puis copiez le résultat.','Gib Text ein, um ihn nach ausgewählten Regeln umzuwandeln, zu ordnen oder zu zählen, und kopiere das Ergebnis.','Introduce texto para convertirlo, ordenarlo o contarlo según las reglas elegidas y copia el resultado.','Insira texto para converter, organizar ou contar conforme as regras escolhidas e copie o resultado.','أدخل النص لتحويله أو ترتيبه أو إحصائه وفق القواعد المختارة ثم انسخ النتيجة.'),
 file:L('选择原始文件，查看检测或转换结果；转换后请检查内容与排版。','Select original files and inspect the detection or conversion result; check content and layout after conversion.','元ファイルを選び、検出・変換結果を確認します。変換後は内容とレイアウトを点検してください。','원본 파일을 선택하고 검사·변환 결과를 확인하세요. 변환 후 내용과 배치를 검토하세요.','Sélectionnez les fichiers originaux et vérifiez la détection ou la conversion, puis le contenu et la mise en page.','Wähle Originaldateien und prüfe Erkennungs- oder Konvertierungsergebnis sowie Inhalt und Layout.','Selecciona los archivos originales y revisa la detección o conversión, el contenido y el diseño.','Selecione os arquivos originais e confira a detecção ou conversão, o conteúdo e o layout.','اختر الملفات الأصلية وراجع نتيجة الكشف أو التحويل ثم تحقق من المحتوى والتنسيق.'),
 media:L('选择音频或视频，确认语言和处理选项，再检查文字、字幕或媒体结果。','Choose audio or video, confirm language and processing options, then review text, subtitles or media output.','音声・動画を選び、言語と設定を確認し、テキスト・字幕・メディア結果を点検します。','오디오나 영상을 선택하고 언어와 옵션을 확인한 뒤 텍스트·자막·미디어 결과를 검토하세요.','Choisissez un audio ou une vidéo, confirmez la langue et les options, puis vérifiez texte, sous-titres ou média.','Wähle Audio oder Video, bestätige Sprache und Optionen und prüfe Text, Untertitel oder Medienergebnis.','Elige audio o vídeo, confirma idioma y opciones, y revisa el texto, subtítulos o archivo multimedia.','Escolha áudio ou vídeo, confirme idioma e opções e revise texto, legendas ou mídia.','اختر صوتًا أو فيديو وأكد اللغة والخيارات ثم راجع النص أو الترجمة أو ملف الوسائط.'),
 subtitle:L('载入 SRT 或 VTT 字幕，检查文字与时间轴；按所选功能整理或翻译，再保存字幕。','Load SRT or VTT subtitles, check text and timestamps, edit or translate using the selected function, then save.','SRT・VTT字幕を読み込み、文章と時刻を確認し、編集・翻訳して保存します。','SRT 또는 VTT 자막을 불러와 텍스트와 시간을 확인하고 편집·번역한 뒤 저장하세요.','Chargez des sous-titres SRT ou VTT, vérifiez texte et horaires, modifiez ou traduisez puis enregistrez.','Lade SRT- oder VTT-Untertitel, prüfe Text und Zeiten, bearbeite oder übersetze und speichere.','Carga subtítulos SRT o VTT, revisa texto y tiempos, edita o traduce y guarda.','Carregue legendas SRT ou VTT, confira texto e tempos, edite ou traduza e salve.','حمّل ترجمة SRT أو VTT وراجع النص والتوقيت ثم حرّر أو ترجم واحفظ.'),
 food:L('拍照或搜索食物，确认每种食物与克数，查看热量、营养来源和下一餐搭配建议。','Add food photos or search foods, confirm each food and its weight, and see calories, nutrient sources and next-meal ideas.','写真や食品検索で食材と重量を確認し、カロリー・栄養の出典・次の食事の提案を見ます。','음식 사진이나 검색으로 음식과 무게를 확인하고 칼로리·영양 출처·다음 식사 제안을 확인하세요.','Ajoutez des photos ou recherchez les aliments, confirmez les quantités et consultez calories, sources et idées pour le prochain repas.','Füge Fotos hinzu oder suche Lebensmittel, bestätige Gewichte und sieh Kalorien, Nährwertquellen und Ideen für die nächste Mahlzeit.','Añade fotos o busca alimentos, confirma pesos y consulta calorías, fuentes y sugerencias para la siguiente comida.','Adicione fotos ou busque alimentos, confirme os pesos e veja calorias, fontes e sugestões para a próxima refeição.','أضف صور الطعام أو ابحث عنه وأكد الأوزان ثم راجع السعرات ومصادر التغذية وأفكار الوجبة التالية.'),
 mail:L('创建短期邮箱并查看来信，适合临时验证；不要用于重要账户或长期保存。','Create a temporary inbox and check incoming mail for short-term verification; avoid important accounts or long-term storage.','短期メールボックスで確認メールを受信できます。重要なアカウントや長期保管には使わないでください。','임시 메일함으로 단기 인증 메일을 확인하세요. 중요한 계정이나 장기 보관에는 사용하지 마세요.','Créez une boîte temporaire pour les vérifications ponctuelles, sans l’utiliser pour des comptes importants ou l’archivage.','Erstelle ein temporäres Postfach für kurzfristige Bestätigungen, nicht für wichtige Konten oder dauerhafte Aufbewahrung.','Crea un buzón temporal para verificaciones puntuales; evita cuentas importantes o almacenamiento duradero.','Crie uma caixa temporária para verificações pontuais; evite contas importantes ou armazenamento permanente.','أنشئ بريدًا مؤقتًا للتحقق قصير المدى ولا تستخدمه للحسابات المهمة أو التخزين الطويل.'),
 share:L('把文字或文件生成限时、限次访问的分享链接。到期后链接失效，仍须防范收件人复制或截屏。','Share text or files through a link with expiry and view limits. Expiry cannot prevent recipients from copying or taking screenshots.','文章・ファイルを期限や回数付きリンクで共有します。受信者によるコピーや撮影は防げません。','텍스트나 파일을 유효 기간·횟수 제한 링크로 공유합니다. 수신자의 복사나 캡처는 막을 수 없습니다.','Partagez textes ou fichiers par lien limité en durée et en vues. Cela n’empêche pas les copies ou captures par les destinataires.','Teile Text oder Dateien mit Ablaufzeit und Aufruflimit. Kopien oder Screenshots durch Empfänger lassen sich damit nicht verhindern.','Comparte texto o archivos con límites de tiempo y visitas. Esto no impide que el destinatario copie o capture el contenido.','Compartilhe texto ou arquivos com prazo e limite de visualizações. Isso não impede cópias ou capturas pelo destinatário.','شارك نصوصًا أو ملفات برابط محدود المدة والمشاهدات. لا يمنع ذلك المستلم من النسخ أو التقاط الشاشة.'),
 qr:L('生成二维码或读取已有二维码的文本与链接；打开链接前先检查地址与来源。','Generate a QR code or read text and links from one; check the destination and source before opening links.','QRコードを生成・読み取りできます。リンクを開く前に宛先と出所を確認してください。','QR 코드를 만들거나 텍스트·링크를 읽고 열기 전에 주소와 출처를 확인하세요.','Créez ou lisez un QR code ; vérifiez l’adresse et la source avant d’ouvrir les liens.','Erstelle oder lies QR-Codes und prüfe Zieladresse und Quelle vor dem Öffnen.','Genera o lee códigos QR y comprueba dirección y origen antes de abrir enlaces.','Gere ou leia códigos QR e confira destino e origem antes de abrir links.','أنشئ رمز QR أو اقرأ محتواه وتحقق من الوجهة والمصدر قبل فتح الروابط.'),
};
const FOOD_LIMIT=L('照片不能准确测量重量，也不能保证识别所有食物。请确认品种和做法；结果用于日常记录，不代替医疗建议。','Photos cannot measure exact weight or identify every food reliably. Confirm ingredients and preparation; results are for everyday tracking, not medical advice.','写真だけでは重量やすべての食品を正確に判断できません。食材・調理法を確認してください。日常記録用で、医療助言ではありません。','사진만으로 정확한 무게나 모든 음식을 판단할 수 없습니다. 재료와 조리법을 확인하세요. 일상 기록용이며 의료 조언이 아닙니다.','Une photo ne mesure pas le poids exact et ne reconnaît pas tous les aliments. Confirmez ingrédients et préparation ; ce suivi ne remplace pas un avis médical.','Fotos bestimmen weder das genaue Gewicht noch jedes Lebensmittel zuverlässig. Prüfe Zutaten und Zubereitung; die Ergebnisse ersetzen keine medizinische Beratung.','Una foto no mide el peso exacto ni reconoce todos los alimentos. Confirma ingredientes y preparación; no sustituye el consejo médico.','Fotos não medem o peso exato nem reconhecem todos os alimentos. Confirme ingredientes e preparo; não substitui orientação médica.','لا تقيس الصور الوزن بدقة ولا تتعرف على كل الأطعمة. أكد المكونات والتحضير؛ النتائج للتسجيل اليومي وليست نصيحة طبية.');

export function toolFacts(slug:string,locale:SeoLocale){
 const tool=getTool(slug);
 const group=slug==='food-calorie'?'food':slug==='temp-mail'?'mail':slug==='burn-after-read'?'share':slug.startsWith('subtitle-')?'subtitle':/^(video|audio)-/.test(slug)?'media':slug.startsWith('qr-')?'qr':tool?.category==='pdf'||/pdf/.test(slug)?'pdf':tool?.category==='image'||/image|photo|ocr/.test(slug)?'image':tool?.category==='utility'?'text':'file';
 return {summary:FACTS[group][locale],limits:slug==='food-calorie'?FOOD_LIMIT[locale]:FACT_LABELS.limitsGeneral[locale],formats:tool?.accept||'',related:tool?.related||[]};
}
