import type {SeoLocale,SeoTopic} from './global-seo';
type Copy=Record<SeoLocale,string>;
const L=(zh:string,en:string,ja:string,ko:string,fr:string,de:string,es:string,pt:string,ar:string):Copy=>({zh,en,ja,ko,fr,de,es,pt,ar});
export const SERVICE_FACTS:Record<SeoTopic,{target:string;description:Copy}>={
  'ai-short-drama-generator':{target:'/sasi/drama',description:L(
"把故事、角色、参考图和已有素材放进 SASI，建立短剧项目并继续生成剧本、分镜和视频。真正生成前会显示可用路线与费用；需要智能生成时可连接自己的智能服务。",
"Bring a story, characters, references and existing assets into SASI to build a short-drama project, then continue with scripts, storyboards and video. Available routes and prices are shown before generation; connect your own intelligence service when generation needs it.",
"物語・キャラクター・参考画像・既存素材をSASIに入れて短編ドラマのプロジェクトを作成し、脚本・絵コンテ・動画制作へ進めます。生成前に利用可能なルートと料金を表示し、必要に応じて自分のAIサービスを接続できます。",
"이야기, 캐릭터, 참고 이미지와 기존 자료를 SASI에 넣어 숏드라마 프로젝트를 만들고 대본·스토리보드·영상 제작을 이어갈 수 있습니다. 생성 전에 가능한 경로와 요금을 확인하며 필요한 경우 자신의 지능형 서비스를 연결합니다.",
"Ajoutez histoire, personnages, références et médias existants à SASI pour créer un projet de mini-série, puis poursuivre avec scénario, storyboard et vidéo. Les voies disponibles et les tarifs sont indiqués avant génération ; connectez votre propre service d’IA si nécessaire.",
"Füge Geschichte, Figuren, Referenzen und vorhandene Medien in SASI ein, erstelle ein Kurzdrama-Projekt und arbeite an Skript, Storyboard und Video weiter. Verfügbare Wege und Preise werden vor der Generierung angezeigt; bei Bedarf verbindest du deinen eigenen KI-Dienst.",
"Añade historia, personajes, referencias y material existente a SASI para crear un proyecto de minidrama y continuar con guion, storyboard y vídeo. Antes de generar se muestran las rutas disponibles y el precio; cuando haga falta puedes conectar tu propio servicio de IA.",
"Adicione história, personagens, referências e materiais existentes ao SASI para criar um projeto de minidrama e continuar com roteiro, storyboard e vídeo. As rotas disponíveis e os preços aparecem antes da geração; quando necessário, conecte seu próprio serviço de IA.",
"أضف القصة والشخصيات والمراجع والمواد الحالية إلى SASI لإنشاء مشروع دراما قصيرة ومتابعة النص واللوحات القصصية والفيديو. تظهر المسارات المتاحة والأسعار قبل التوليد، ويمكن ربط خدمة الذكاء الخاصة بك عند الحاجة."
)},
'book-to-ai-agent':{target:'/ai-knowledge',description:L('把书本内容整理成可检索资料，围绕原文提问、回看相关段落。回答应结合来源核对；在线问答取决于所连接的模型。','Organize book content into searchable sources, ask questions and return to relevant passages. Check answers against sources; online Q&A depends on the connected model.','本の内容を検索可能な資料に整理し、質問して関連箇所に戻れます。回答は出典で確認してください。オンライン回答は接続モデルに依存します。','책 내용을 검색 가능한 자료로 정리하고 질문하며 관련 문단을 확인하세요. 답변을 원문과 대조하세요. 온라인 답변은 연결 모델에 따라 달라집니다.','Organisez un livre en sources consultables, posez des questions et retrouvez les passages. Vérifiez les réponses dans les sources ; le dialogue en ligne dépend du modèle connecté.','Ordne Buchinhalte als durchsuchbare Quellen, stelle Fragen und kehre zu Textstellen zurück. Prüfe Antworten anhand der Quellen; Online-Antworten benötigen ein verbundenes Modell.','Organiza libros como fuentes consultables, pregunta y vuelve a los pasajes relevantes. Contrasta las respuestas con las fuentes; las respuestas online dependen del modelo conectado.','Organize livros como fontes pesquisáveis, faça perguntas e volte aos trechos relevantes. Confira respostas nas fontes; perguntas online dependem do modelo conectado.','نظّم محتوى الكتب كمصادر قابلة للبحث واطرح الأسئلة وعد إلى المقاطع ذات الصلة. تحقق من الإجابات بالمصادر؛ تعتمد الإجابة عبر الإنترنت على النموذج المتصل.')},
 'document-ai-agent':{target:'/ai-knowledge',description:L('集中导入与整理文档、笔记和资料，检索相关内容并追溯到原文。保留原文件，解析后核对文字、表格和来源。','Import and organize documents, notes and sources, retrieve relevant content and trace it to the original. Keep original files and review extracted text, tables and sources.','文書・メモ・資料を整理し、関連情報を検索して原文にたどれます。原本を保管し、抽出された文章・表・出典を確認してください。','문서·메모·자료를 모아 관련 내용을 검색하고 원문을 추적합니다. 원본을 보관하고 추출된 텍스트·표·출처를 검토하세요.','Importez documents, notes et sources, retrouvez les contenus pertinents et leur origine. Conservez les fichiers originaux et vérifiez textes, tableaux et sources extraits.','Importiere Dokumente, Notizen und Quellen, finde relevante Inhalte und verfolge sie zum Original zurück. Bewahre Originaldateien auf und prüfe extrahierte Texte, Tabellen und Quellen.','Importa documentos, notas y fuentes, recupera contenido relevante y rastrea el original. Conserva los archivos y revisa textos, tablas y fuentes extraídos.','Importe documentos, notas e fontes, encontre conteúdo relevante e rastreie o original. Guarde os arquivos e confira textos, tabelas e fontes extraídos.','استورد المستندات والملاحظات والمصادر ونظّمها للبحث والرجوع إلى الأصل. احتفظ بالملفات الأصلية وراجع النصوص والجداول والمصادر المستخرجة.')},
 'learning-ai-agent':{target:'/ai-learning',description:L('把教材、笔记与复习材料放在同一学习空间，检索知识点并结合原文提问。用自己的理解核对答案，记录仍需复习的内容。','Keep textbooks, notes and revision material in one study space. Retrieve topics and ask source-based questions; check answers and record what still needs review.','教科書・ノート・復習資料を一つにまとめ、原文に基づいて検索・質問します。回答を自分で確認し、復習が必要な点を記録します。','교재·노트·복습 자료를 한곳에 모으고 원문 기반으로 검색·질문하세요. 답변을 확인하고 복습할 내용을 기록하세요.','Réunissez cours, notes et révisions, retrouvez les notions et posez des questions fondées sur les sources. Vérifiez les réponses et notez les points à revoir.','Sammle Lehrbücher, Notizen und Lernmaterial an einem Ort. Suche Themen und stelle quellenbasierte Fragen; prüfe Antworten und halte Wiederholungsbedarf fest.','Reúne libros, notas y material de repaso. Busca temas y pregunta sobre las fuentes; revisa las respuestas y anota lo que necesitas repasar.','Reúna livros, notas e material de revisão. Busque temas e faça perguntas com base nas fontes; confira respostas e registre o que precisa revisar.','اجمع الكتب والملاحظات ومواد المراجعة في مساحة واحدة. ابحث عن الموضوعات واسأل بالاستناد إلى المصادر وراجع الإجابات وسجّل ما يحتاج إلى مراجعة.')},
 'research-ai-agent':{target:'/ai-research',description:L('整理论文、研究笔记与证据，围绕资料检索和提问。区分原文证据与模型解释；重要结论与引文须回到原文核实。','Organize papers, research notes and evidence for retrieval and questions. Distinguish source evidence from model interpretation; verify important conclusions and citations in the originals.','論文・研究ノート・証拠を整理して検索・質問します。原文の証拠とモデルの解釈を区別し、重要な結論・引用は原文で確認してください。','논문·연구 노트·근거를 정리하여 검색·질문합니다. 원문 근거와 모델 해석을 구분하고 중요한 결론·인용은 원문에서 검증하세요.','Organisez articles, notes et preuves. Distinguez les sources de l’interprétation du modèle et vérifiez les conclusions importantes et citations dans les originaux.','Ordne Fachartikel, Notizen und Belege. Unterscheide Quellenbelege von Modellinterpretationen und prüfe wichtige Schlussfolgerungen und Zitate im Original.','Organiza artículos, notas y evidencias. Distingue las fuentes de la interpretación del modelo y verifica conclusiones y citas importantes en los originales.','Organize artigos, notas e evidências. Diferencie fontes da interpretação do modelo e verifique conclusões e citações importantes nos originais.','نظّم الأوراق البحثية والملاحظات والأدلة للبحث والأسئلة. ميّز دليل المصدر عن تفسير النموذج وتحقق من الاستنتاجات والاقتباسات المهمة في الأصول.')},
  'ai-website-builder':{target:'/sasi/build',description:L(
"告诉 SASI 你想做的网站，加入品牌资料、图片、文档或代码，就能先生成可预览的网站起稿，并继续完善页面与内容。使用智能生成前会显示可用路线与费用，也可以连接自己的智能服务继续构建。",
"Tell SASI what website you want and add brand assets, images, documents or code. It can produce a previewable website draft and continue refining pages and content. Available routes and prices are shown before intelligent generation, and you can connect your own intelligence service to keep building.",
"作りたいサイトをSASIに伝え、ブランド資料・画像・文書・コードを追加すると、プレビュー可能な下書きを作成し、ページや内容を継続して整えられます。智能生成前に利用可能なルートと料金を表示し、自分のAIサービスを接続して続けることもできます。",
"원하는 웹사이트와 브랜드 자료, 이미지, 문서 또는 코드를 SASI에 넣으면 미리 볼 수 있는 사이트 초안을 만들고 페이지와 콘텐츠를 계속 다듬을 수 있습니다. 지능형 생성 전에 사용 가능한 경로와 요금을 표시하며 자신의 지능형 서비스를 연결해 계속 구축할 수 있습니다.",
"Décrivez le site souhaité à SASI et ajoutez éléments de marque, images, documents ou code. SASI crée une ébauche prévisualisable puis permet d’affiner pages et contenus. Les voies disponibles et les tarifs sont indiqués avant la génération intelligente, avec la possibilité de connecter votre propre service d’IA.",
"Beschreibe SASI die gewünschte Website und füge Markenmaterial, Bilder, Dokumente oder Code hinzu. SASI erstellt einen Vorschau-Entwurf und hilft beim weiteren Ausbau von Seiten und Inhalten. Verfügbare Wege und Preise werden vor der intelligenten Generierung angezeigt; dein eigener KI-Dienst kann verbunden werden.",
"Dile a SASI qué sitio quieres y añade materiales de marca, imágenes, documentos o código. SASI crea un borrador previsualizable y permite seguir perfeccionando páginas y contenido. Antes de la generación inteligente se muestran las rutas y el precio, y puedes conectar tu propio servicio de IA.",
"Diga ao SASI qual site deseja e adicione materiais de marca, imagens, documentos ou código. O SASI cria um rascunho visualizável e permite continuar aprimorando páginas e conteúdo. As rotas disponíveis e os preços aparecem antes da geração inteligente, e você pode conectar seu próprio serviço de IA.",
"أخبر SASI بالموقع الذي تريد إنشاءه وأضف مواد العلامة التجارية والصور والمستندات أو الشيفرة. ينشئ SASI مسودة قابلة للمعاينة ويمكن متابعة تحسين الصفحات والمحتوى. تظهر المسارات المتاحة والأسعار قبل التوليد الذكي، ويمكنك ربط خدمة الذكاء الخاصة بك للمتابعة."
)},
};
