"use client";
import {useCallback,useEffect,useState,useRef} from "react";
import {MEMORY_KINDS,type MemoryKind,type MemoryEvent} from "@/lib/sasi/project-memory";
const labels={goal:"项目目的",decision:"重要决定",constraint:"必须保留",character:"人物设定",experience:"发生过的事"};
export function SasiProjectMemory({projectId,lang}:{projectId:string;lang:"zh"|"en"}) {
  const [events,setEvents]=useState<MemoryEvent[]>([]),[kind,setKind]=useState<MemoryKind>("goal"),[text,setText]=useState(""),[subject,setSubject]=useState(""),[supersedes,setSupersedes]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const pending=useRef<{key:string;id:string}|null>(null);
  const zh=lang==="zh";
  const load=useCallback(async()=>{const r=await fetch(`/api/sasi/projects/${projectId}/memory`,{cache:"no-store"});if(!r.ok)throw Error("read");const data=await r.json();setEvents(data.events);},[projectId]);
  useEffect(()=>{setEvents([]);void load().catch(()=>setMessage(zh?"记忆暂时无法读取，请稍后重试。":"Memory is unavailable. Please retry."));},[load,zh]);
  const replaced=new Set(events.flatMap(e=>e.supersedes?[e.supersedes]:[]));
  async function save(){if(busy)return;setBusy(true);setMessage("");try{const key=JSON.stringify({kind,text,subject,supersedes});if(pending.current?.key!==key)pending.current={key,id:crypto.randomUUID()};const r=await fetch(`/api/sasi/projects/${projectId}/memory`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:pending.current.id,kind,text,subject,supersedes})});if(!r.ok)throw Error("save");await load();pending.current=null;setText("");setSubject("");setSupersedes(null);setMessage(zh?"已保存到这个项目，下次回来可以继续。":"Saved to this project for your next visit.");}catch{setMessage(zh?"没有确认保存成功，输入仍在，请重试。":"Save could not be confirmed. Your input is retained.");}finally{setBusy(false);}}
  async function remove(id:string){if(!window.confirm(zh?"删除这条记忆及其更正历史？":"Delete this memory and its revision history?"))return;setBusy(true);try{const r=await fetch(`/api/sasi/projects/${projectId}/memory?memoryId=${id}`,{method:"DELETE"});if(!r.ok)throw Error();await load();}catch{setMessage(zh?"删除未完成，请重试。":"Deletion failed. Please retry.");}finally{setBusy(false);}}
  return <section className="sasi-project-memory"><header><div><small>PROJECT MEMORY</small><h2>{zh?"让 SASI 记住这件事":"Keep this with your project"}</h2><p>{zh?"保存项目的目的、人物设定和重要决定。更正会保留来由；你也可以删除。":"Keep goals, character details and decisions. Revisions retain their history; you can delete them."}</p></div></header><div className="sasi-memory-form"><select aria-label={zh?"记忆类型":"Memory type"} value={kind} onChange={e=>setKind(e.target.value as MemoryKind)}>{MEMORY_KINDS.map(k=><option key={k} value={k}>{zh?labels[k]:k}</option>)}</select><input aria-label={zh?"相关人物或主题":"Person or topic"} placeholder={zh?"相关人物或主题（选填）":"Person or topic (optional)"} maxLength={80} value={subject} onChange={e=>setSubject(e.target.value)}/><textarea aria-label={zh?"要记住的内容":"Memory content"} maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder={zh?"例如：这个网站帮助独立创作者完成第一部短剧；必须保留现有登录与资料。":"For example: Help independent creators finish a first film; preserve existing login and assets."}/><button disabled={busy||text.trim().length<2} onClick={()=>void save()}>{busy?(zh?"正在保存…":"Saving…"):supersedes?(zh?"保存更正":"Save revision"):(zh?"记住这件事":"Save memory")}</button>{supersedes&&<button onClick={()=>{setSupersedes(null);setText("");}}>{zh?"取消更正":"Cancel revision"}</button>}</div><p role="status">{message}</p><div className="sasi-memory-list">{events.filter(e=>!replaced.has(e.id)).map(e=><article key={e.id}><small>{zh?labels[e.kind]:e.kind} · {e.subject} · {new Date(e.createdAt).toLocaleDateString(zh?"zh-CN":"en-US")}</small><p>{e.text}</p><button disabled={busy} onClick={()=>{setKind(e.kind);setText(e.text);setSubject(e.subject);setSupersedes(e.id);}}>{zh?"更正":"Revise"}</button><button disabled={busy} onClick={()=>void remove(e.id)}>{zh?"删除":"Delete"}</button></article>)}</div>{replaced.size>0&&<details><summary>{zh?"查看更正历史":"Revision history"}</summary>{events.filter(e=>replaced.has(e.id)).map(e=><p key={e.id}>{e.text}</p>)}</details>}</section>;
}
