"use client";

import { useEffect, useState } from "react";
import { useLingxiLang, type LingxiLang } from "@/lib/lingxi-i18n";

type Task={id:string;state:string;estimated_fen?:number;question?:string;output?:{answer?:string;truncated?:boolean;error?:string}};
type Copy=Record<LingxiLang,string>;
const c=(zh:string,en:string,ja:string,ko:string,fr:string,de:string,es:string,pt:string,ar:string):Copy=>({zh,en,ja,ko,fr,de,es,pt,ar});

const ERRORS:Record<string,Copy>={
 AUTH_REQUIRED:c("请先登录，再继续对话。","Sign in before continuing.","続ける前にログインしてください。","계속하려면 먼저 로그인하세요.","Connectez-vous avant de continuer.","Bitte zuerst anmelden.","Inicia sesión antes de continuar.","Entre na conta antes de continuar.","سجّل الدخول أولًا للمتابعة."),
 CONNECTION_REQUIRED:c("请先连接并验证火山 API。","Connect and verify the Volcengine API first.","先に Volcengine API を接続・検証してください。","먼저 Volcengine API를 연결하고 검증하세요.","Connectez et vérifiez d’abord l’API Volcengine.","Verbinden und prüfen Sie zuerst die Volcengine-API.","Conecta y verifica primero la API de Volcengine.","Conecte e verifique primeiro a API da Volcengine.","اربط واجهة Volcengine وتحقق منها أولًا."),
 MODEL_NOT_OPEN:c("密钥有效，但模型尚未开通。请在供应商控制台开通后重试。","The key is valid, but the model is not enabled. Enable it in the provider console and try again.","キーは有効ですがモデルが有効化されていません。プロバイダー側で有効化して再試行してください。","키는 유효하지만 모델이 활성화되지 않았습니다. 공급자 콘솔에서 활성화한 뒤 다시 시도하세요.","La clé est valide, mais le modèle n’est pas activé. Activez-le chez le fournisseur puis réessayez.","Der Schlüssel ist gültig, das Modell aber nicht aktiviert. Bitte beim Anbieter aktivieren und erneut versuchen.","La clave es válida, pero el modelo no está habilitado. Actívalo con el proveedor y vuelve a intentarlo.","A chave é válida, mas o modelo não está habilitado. Ative-o no provedor e tente novamente.","المفتاح صالح لكن النموذج غير مفعّل. فعّله لدى المزوّد ثم أعد المحاولة."),
 CONTEXT_LIMIT_START_NEW:c("这次对话已达到上下文上限，请开始新对话。历史仍保留在这里。","This conversation reached its context limit. Start a new chat; history stays here.","この会話はコンテキスト上限に達しました。新しい会話を開始してください。履歴は残ります。","이 대화는 컨텍스트 한도에 도달했습니다. 새 대화를 시작하세요. 기록은 유지됩니다.","Cette conversation a atteint sa limite de contexte. Commencez-en une nouvelle ; l’historique reste ici.","Diese Unterhaltung hat das Kontextlimit erreicht. Starten Sie einen neuen Chat; der Verlauf bleibt erhalten.","Esta conversación alcanzó el límite de contexto. Inicia una nueva; el historial se conserva.","Esta conversa atingiu o limite de contexto. Inicie uma nova; o histórico permanece.","وصلت هذه المحادثة إلى حد السياق. ابدأ محادثة جديدة وسيبقى السجل محفوظًا."),
 PRICE_REVIEW_REQUIRED:c("模型价格需要重新核验，暂不发起付费请求。","Model pricing needs review; no paid request was sent.","モデル価格の再確認が必要なため、有料リクエストは送信していません。","모델 가격을 다시 확인해야 하므로 유료 요청을 보내지 않았습니다.","Le tarif du modèle doit être revérifié ; aucune requête payante n’a été envoyée.","Der Modellpreis muss erneut geprüft werden; es wurde keine kostenpflichtige Anfrage gesendet.","El precio del modelo debe revisarse; no se envió ninguna solicitud de pago.","O preço do modelo precisa ser revisto; nenhuma solicitação paga foi enviada.","تحتاج أسعار النموذج إلى مراجعة؛ لم يتم إرسال طلب مدفوع."),
 RESULT_UNCERTAIN_DO_NOT_RETRY_AUTOMATICALLY:c("请求结果暂时无法确认，请先检查供应商用量记录，避免重复付费。","The result is uncertain. Check provider usage before retrying to avoid duplicate charges.","結果を確認できません。重複課金を避けるため再試行前に利用記録を確認してください。","결과를 확인할 수 없습니다. 중복 과금을 피하려면 재시도 전에 공급자 사용 기록을 확인하세요.","Le résultat est incertain. Vérifiez l’usage fournisseur avant de réessayer pour éviter un double débit.","Das Ergebnis ist unklar. Prüfen Sie vor einem neuen Versuch die Anbieter-Nutzung, um Doppelbelastungen zu vermeiden.","El resultado es incierto. Revisa el uso del proveedor antes de reintentar para evitar cargos duplicados.","O resultado é incerto. Verifique o uso no provedor antes de tentar novamente para evitar cobrança duplicada.","النتيجة غير مؤكدة. تحقق من سجل الاستخدام لدى المزوّد قبل إعادة المحاولة لتجنب الخصم المكرر."),
};

const UI={
 historyFail:c("历史暂时无法读取。","History is temporarily unavailable.","履歴を読み込めません。","기록을 불러올 수 없습니다.","L’historique est momentanément indisponible.","Verlauf vorübergehend nicht verfügbar.","El historial no está disponible temporalmente.","O histórico está temporariamente indisponível.","السجل غير متاح مؤقتًا."),
 offline:c("连接暂时不可用，请稍后重试。","Connection unavailable. Try again later.","接続できません。後でもう一度お試しください。","연결할 수 없습니다. 나중에 다시 시도하세요.","Connexion indisponible. Réessayez plus tard.","Verbindung nicht verfügbar. Bitte später erneut versuchen.","Conexión no disponible. Inténtalo más tarde.","Conexão indisponível. Tente novamente mais tarde.","الاتصال غير متاح. حاول لاحقًا."),
 title:c("从一个问题，到一个好想法。","From one question to a better idea.","ひとつの問いから、より良いアイデアへ。","하나의 질문에서 더 좋은 아이디어로.","D’une question à une meilleure idée.","Von einer Frage zu einer besseren Idee.","De una pregunta a una mejor idea.","De uma pergunta a uma ideia melhor.","من سؤال واحد إلى فكرة أفضل."),
 lead:c("解释知识、写剧本、讨论方案或编写代码。费用在发送前先显示预估。","Explain ideas, write scripts, discuss plans or code. Estimated cost is shown before sending.","知識の説明、脚本、企画相談、コード作成。送信前に費用見積もりを表示します。","지식 설명, 대본 작성, 기획 논의, 코드 작성. 전송 전에 예상 비용을 표시합니다.","Expliquez, écrivez des scripts, discutez de plans ou codez. Le coût estimé est affiché avant l’envoi.","Wissen erklären, Skripte schreiben, Pläne besprechen oder Code erstellen. Die Kostenschätzung erscheint vor dem Senden.","Explica ideas, escribe guiones, debate planes o programa. El coste estimado se muestra antes de enviar.","Explique ideias, escreva roteiros, discuta planos ou programe. O custo estimado aparece antes do envio.","اشرح الأفكار واكتب النصوص وناقش الخطط أو البرمجة. يظهر تقدير التكلفة قبل الإرسال."),
 chat:c("聊知识与创意","Knowledge & ideas","知識とアイデア","지식과 아이디어","Connaissances & idées","Wissen & Ideen","Conocimiento e ideas","Conhecimento e ideias","المعرفة والأفكار"),
 director:c("把故事变成分镜","Turn story into shots","物語を絵コンテへ","이야기를 장면으로","Transformer l’histoire en plans","Story in Einstellungen","Convertir historia en planos","Transformar história em cenas","حوّل القصة إلى لقطات"),
 placeholder:c("例如：把我的故事改成有冲突、有转折、能拍出来的短剧……","For example: turn my story into a short drama with conflict, turns and filmable scenes…","例：物語を、葛藤と転換があり撮影できる短編ドラマにして…","예: 내 이야기를 갈등과 반전이 있고 촬영 가능한 짧은 드라마로 바꿔줘…","Ex. : transforme mon histoire en court drama avec conflit, rebondissements et scènes filmables…","Zum Beispiel: Verwandle meine Geschichte in ein kurzes Drama mit Konflikt, Wendungen und filmbaren Szenen…","Ej.: convierte mi historia en un drama corto con conflicto, giros y escenas filmables…","Ex.: transforme minha história em um drama curto com conflito, viradas e cenas filmáveis…","مثال: حوّل قصتي إلى دراما قصيرة فيها صراع وتحولات ومشاهد قابلة للتصوير…"),
 newChat:c("新对话","New chat","新しい会話","새 대화","Nouveau chat","Neuer Chat","Nuevo chat","Nova conversa","محادثة جديدة"),
 continueNew:c("正在续聊 · 开始新对话","Continuing thread · Start new chat","続きの会話中 · 新しい会話","대화 이어가는 중 · 새 대화","Suite en cours · Nouveau chat","Fortsetzung · Neuer Chat","Continuando · Nuevo chat","Continuando · Nova conversa","متابعة المحادثة · ابدأ محادثة جديدة"),
 processing:c("处理中…","Processing…","処理中…","처리 중…","Traitement…","Verarbeitung…","Procesando…","Processando…","جارٍ المعالجة…"),
 quote:c("查看本次费用 →","View estimated cost →","今回の費用を見る →","예상 비용 보기 →","Voir le coût estimé →","Geschätzte Kosten →","Ver coste estimado →","Ver custo estimado →","عرض التكلفة التقديرية →"),
 agree:c("同意费用，发送","Accept cost & send","費用に同意して送信","비용 동의 후 전송","Accepter le coût et envoyer","Kosten akzeptieren & senden","Aceptar coste y enviar","Aceitar custo e enviar","وافق على التكلفة وأرسل"),
 waiting:c("等待费用确认","Waiting for cost confirmation","費用確認待ち","비용 확인 대기","En attente de confirmation du coût","Warten auf Kostenbestätigung","Esperando confirmación del coste","Aguardando confirmação do custo","بانتظار تأكيد التكلفة"),
 resultPending:c("结果待确认","Result pending","結果確認待ち","결과 확인 대기","Résultat en attente","Ergebnis ausstehend","Resultado pendiente","Resultado pendente","النتيجة قيد التأكيد"),
 unfinished:c("请求未完成","Request not completed","リクエスト未完了","요청 미완료","Requête non terminée","Anfrage nicht abgeschlossen","Solicitud no completada","Solicitação não concluída","لم يكتمل الطلب"),
 continue:c("接着这段聊 →","Continue this thread →","この続きから話す →","이 대화 이어가기 →","Continuer ce fil →","Diesen Thread fortsetzen →","Continuar este hilo →","Continuar esta conversa →","متابعة هذه المحادثة →"),
 manage:c("管理 API 连接","Manage API connections","API 接続を管理","API 연결 관리","Gérer les connexions API","API-Verbindungen verwalten","Gestionar conexiones API","Gerenciar conexões API","إدارة اتصالات API"),
};

export default function SasiChat(){
 const{lang}=useLingxiLang();
 const t=(x:Copy)=>x[lang];
 const[question,setQuestion]=useState("");const[mode,setMode]=useState<"chat"|"director">("chat");const[tasks,setTasks]=useState<Task[]>([]);const[previousId,setPreviousId]=useState("");const[quote,setQuote]=useState<Task|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");

 useEffect(()=>{const intent=window.sessionStorage.getItem("sasi-intent");if(intent){setQuestion(intent);window.sessionStorage.removeItem("sasi-intent")}},[]);
 useEffect(()=>{let alive=true;fetch("/api/sasi/byok/text",{cache:"no-store"}).then(async r=>({ok:r.ok,body:await r.json()})).then(({ok,body})=>{if(alive){if(ok)setTasks(body.tasks);else setNotice(t(ERRORS[body.error]??UI.historyFail))}}).catch(()=>alive&&setNotice(t(UI.offline)));return()=>{alive=false}},[lang]);

 async function send(action:"quote"|"confirm"){
  if(busy)return;setBusy(true);setNotice("");
  try{
   const response=await fetch("/api/sasi/byok/text",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action==="quote"?{action,question,mode,previousId:previousId||undefined}:{action,taskId:quote?.id,acceptSupplierBilling:true})});
   const body=await response.json();
   if(!response.ok)throw new Error(t(ERRORS[body.error]??c(`本次请求未完成（${body.error??response.status}）。`,`Request not completed (${body.error??response.status}).`,`リクエスト未完了（${body.error??response.status}）。`,`요청 미완료 (${body.error??response.status}).`,`Requête non terminée (${body.error??response.status}).`,`Anfrage nicht abgeschlossen (${body.error??response.status}).`,`Solicitud no completada (${body.error??response.status}).`,`Solicitação não concluída (${body.error??response.status}).`,`لم يكتمل الطلب (${body.error??response.status}).`)));
   if(action==="quote")setQuote(body.task);
   else{
    const task={...body.task,question};setTasks(rows=>[task,...rows.filter(row=>row.id!==task.id)]);setQuote(null);
    if(task.state==="succeeded"){setPreviousId(task.id);setQuestion("");if(body.historySaved===false)setNotice(c("回答已完成，但历史保存失败，请先复制保存这段回答。","Answer completed, but history could not be saved. Copy it now.","回答は完了しましたが履歴を保存できません。今コピーしてください。","답변은 완료됐지만 기록 저장에 실패했습니다. 지금 복사해 두세요.","Réponse terminée, mais l’historique n’a pas été enregistré. Copiez-la maintenant.","Antwort fertig, Verlauf konnte aber nicht gespeichert werden. Bitte jetzt kopieren.","Respuesta completada, pero no se guardó el historial. Cópiala ahora.","Resposta concluída, mas o histórico não foi salvo. Copie agora.","اكتملت الإجابة لكن تعذر حفظ السجل. انسخها الآن.")[lang])}
    else setNotice(c("任务已提交，请刷新历史查看结果；不要重复提交。","Task submitted. Refresh history for the result; do not submit twice.","タスクを送信しました。履歴を更新して結果を確認してください。重複送信しないでください。","작업이 제출되었습니다. 기록을 새로고침해 결과를 확인하세요. 중복 제출하지 마세요.","Tâche envoyée. Actualisez l’historique ; ne l’envoyez pas deux fois.","Aufgabe gesendet. Verlauf aktualisieren; nicht doppelt senden.","Tarea enviada. Actualiza el historial; no la envíes dos veces.","Tarefa enviada. Atualize o histórico; não envie duas vezes.","تم إرسال المهمة. حدّث السجل لرؤية النتيجة ولا ترسلها مرتين.")[lang]);
   }
  }catch(error){setNotice(error instanceof Error?error.message:c("请求未完成，请检查网络。","Request not completed. Check your connection.","リクエスト未完了です。ネットワークを確認してください。","요청이 완료되지 않았습니다. 네트워크를 확인하세요.","Requête non terminée. Vérifiez votre connexion.","Anfrage nicht abgeschlossen. Verbindung prüfen.","Solicitud no completada. Revisa la conexión.","Solicitação não concluída. Verifique a conexão.","لم يكتمل الطلب. تحقق من الاتصال.")[lang])}
  finally{setBusy(false)}
 }

 return <section className="mx-auto max-w-3xl">
  <p className="text-sm text-[#6d28d9]">SASI · {t(UI.chat)}</p><h1 className="mt-3 text-3xl font-semibold">{t(UI.title)}</h1>
  <p className="mt-4 leading-7 text-slate-600">{t(UI.lead)}</p>
  <div className="mt-6 rounded-3xl border border-[#ddd6fe] bg-white p-5">
   <div className="mb-3 flex gap-2" role="group" aria-label={t(UI.chat)}>{([["chat",UI.chat],["director",UI.director]] as const).map(([value,label])=><button key={value} type="button" aria-pressed={mode===value} disabled={busy} className={`rounded-full px-4 py-2 text-sm ${mode===value?"bg-[#6d28d9] text-white":"bg-slate-100 text-slate-700"}`} onClick={()=>{setMode(value);setQuote(null);setPreviousId("")}}>{t(label)}</button>)}</div>
   <textarea aria-label={t(UI.chat)} className="min-h-36 w-full resize-y rounded-xl p-3 text-base outline-[#a78bfa]" maxLength={12000} disabled={busy} value={question} onChange={e=>{setQuestion(e.target.value);setQuote(null)}} placeholder={t(UI.placeholder)}/>
   <div className="flex flex-wrap items-center justify-between gap-3"><button disabled={busy} className="text-sm text-slate-500" onClick={()=>{setPreviousId("");setQuote(null);setQuestion("")}}>{previousId?t(UI.continueNew):t(UI.newChat)}</button><button disabled={busy||!question.trim()} className="rounded-xl bg-[#6d28d9] px-5 py-3 text-white disabled:opacity-40" onClick={()=>void send("quote")}>{busy?t(UI.processing):t(UI.quote)}</button></div>
   {quote&&<div className="mt-4 rounded-xl bg-[#f5f3ff] p-4"><p>{c(`本次预估 ¥${((quote.estimated_fen??0)/100).toFixed(2)}，按实际 token 用量结算。`,`Estimated ¥${((quote.estimated_fen??0)/100).toFixed(2)}; final charge follows actual token usage.`,`見積 ¥${((quote.estimated_fen??0)/100).toFixed(2)}。実際の token 使用量で精算します。`,`예상 ¥${((quote.estimated_fen??0)/100).toFixed(2)}이며 실제 token 사용량으로 정산됩니다.`,`Estimation ¥${((quote.estimated_fen??0)/100).toFixed(2)} ; facturation selon les tokens réellement utilisés.`,`Geschätzt ¥${((quote.estimated_fen??0)/100).toFixed(2)}; abgerechnet nach tatsächlicher Token-Nutzung.`,`Estimado ¥${((quote.estimated_fen??0)/100).toFixed(2)}; se cobra según los tokens reales.`,`Estimativa ¥${((quote.estimated_fen??0)/100).toFixed(2)}; cobrança pelo uso real de tokens.`,`التقدير ¥${((quote.estimated_fen??0)/100).toFixed(2)}؛ وتتم المحاسبة حسب الاستخدام الفعلي للرموز.`)[lang]}</p><p className="mt-2 text-sm text-slate-600">{c("包含当前对话上下文；预估不是固定账单。","Includes current conversation context; the estimate is not a fixed bill.","現在の会話コンテキストを含みます。見積は固定請求ではありません。","현재 대화 컨텍스트가 포함되며 예상 금액은 고정 청구액이 아닙니다.","Inclut le contexte actuel ; l’estimation n’est pas une facture fixe.","Enthält den aktuellen Kontext; die Schätzung ist keine feste Rechnung.","Incluye el contexto actual; la estimación no es una factura fija.","Inclui o contexto atual; a estimativa não é uma cobrança fixa.","يشمل سياق المحادثة الحالي؛ والتقدير ليس فاتورة ثابتة.")[lang]}</p><button disabled={busy} className="mt-3 rounded-xl bg-[#6d28d9] px-5 py-3 text-white" onClick={()=>void send("confirm")}>{t(UI.agree)}</button></div>}
  </div>
  {notice&&<p role="status" className="mt-4 rounded-xl bg-[#fffbeb] p-4 text-[#78350f]">{notice}</p>}
  <p className="mt-4 text-sm leading-6 text-slate-500">{c("当前支持文本对话与连续追问，尚未连接实时搜索或自动执行工具。模型可能出错，重要信息请核实。","Text chat and follow-up questions are available. Live search and automatic tool execution are not connected yet. Models can be wrong; verify important information.","テキスト会話と継続質問に対応しています。リアルタイム検索と自動ツール実行は未接続です。重要情報は確認してください。","텍스트 대화와 연속 질문을 지원합니다. 실시간 검색과 자동 도구 실행은 아직 연결되지 않았습니다. 중요한 정보는 확인하세요.","Le chat texte et les questions de suivi sont disponibles. La recherche en direct et l’exécution automatique d’outils ne sont pas encore connectées. Vérifiez les informations importantes.","Textchat und Rückfragen sind verfügbar. Live-Suche und automatische Tool-Ausführung sind noch nicht verbunden. Wichtige Informationen bitte prüfen.","Hay chat de texto y preguntas de seguimiento. La búsqueda en vivo y la ejecución automática de herramientas aún no están conectadas. Verifica la información importante.","Chat de texto e perguntas de acompanhamento estão disponíveis. Busca ao vivo e execução automática de ferramentas ainda não estão conectadas. Verifique informações importantes.","تتوفر المحادثة النصية والأسئلة المتابعة. البحث المباشر والتنفيذ التلقائي للأدوات غير متصلين بعد. تحقق من المعلومات المهمة.")[lang]} <a className="ml-2 underline" href="/sasi/connections">{t(UI.manage)}</a></p>
  <div className="mt-8 space-y-5">{tasks.map(task=><article key={task.id} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="whitespace-pre-wrap font-medium">{task.question}</h2><p className="mt-4 whitespace-pre-wrap break-words leading-8">{task.output?.answer??(task.state==="quoted"?t(UI.waiting):task.output?.error?t(ERRORS[task.output.error]??UI.unfinished):t(UI.resultPending))}</p>{task.output?.truncated&&<p className="mt-2 text-sm text-[#b45309]">{c("本次输出已达到长度限制，可继续追问。","This output reached the length limit; you can continue with a follow-up.","出力が長さ上限に達しました。続けて質問できます。","출력이 길이 제한에 도달했습니다. 이어서 질문할 수 있습니다.","La sortie a atteint la limite de longueur ; vous pouvez poursuivre.","Die Ausgabe hat das Längenlimit erreicht; Sie können nachfragen.","La salida alcanzó el límite de longitud; puedes continuar preguntando.","A saída atingiu o limite de tamanho; você pode continuar perguntando.","وصلت الإجابة إلى حد الطول؛ يمكنك المتابعة بسؤال آخر.")[lang]}</p>}{task.state==="succeeded"&&<button className="mt-3 text-sm text-[#6d28d9]" disabled={busy} onClick={()=>{setPreviousId(task.id);setQuote(null)}}>{t(UI.continue)}</button>}</article>)}</div>
 </section>;
}
