import {test,expect,type Page} from 'playwright/test';
import {adminDashboardFixture as dashboard} from './admin-dashboard-fixture';
import {publicVisitPath} from '../../lib/analytics/public-visit';
const data={dashboard,stats:{channels:[],notices_pending:0},withdrawals:[],notices:[],notifyEmail:'business@example.com',emailConfigured:true};
async function mock(page:Page){await page.route('**/api/account/money-admin?*',r=>r.fulfill({json:data}));}
test('paid balance purchase, separate cash and currency are visible',async({page},info)=>{
 await mock(page);await page.goto('/account/money-admin?lang=zh');await expect(page.getByRole('tab')).toHaveCount(5);await expect(page.getByRole('tabpanel')).toContainText('¥21.30');await expect(page.getByRole('tabpanel')).toContainText('¥2.00');await expect(page.getByText('食物卡路里分析 · SASI 余额')).toBeVisible();await page.screenshot({path:info.outputPath('admin-overview.png')});await page.getByLabel('统计币种').selectOption('USD');await expect(page.getByRole('tabpanel')).toContainText('$8.00');await expect(page.getByRole('tabpanel')).not.toContainText('¥21.30');
 await page.getByRole('tab',{name:'所有订单',exact:true}).click();await page.getByText('订单详情',{exact:true}).click();await expect(page.getByRole('tabpanel')).toContainText('余额内部扣款，无新渠道交易');await expect(page.getByRole('tabpanel')).toContainText('2026/10/06 19:57');await page.screenshot({path:info.outputPath('admin-orders.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('orders filter and pagination request the server instead of truncating totals',async({page})=>{
 const urls:string[]=[];await page.route('**/api/account/money-admin?*',r=>{urls.push(r.request().url());return r.fulfill({json:data})});await page.goto('/account/money-admin');await page.getByRole('tab',{name:'所有订单',exact:true}).click();await page.getByRole('button',{name:'下一页'}).click();await expect.poll(()=>urls.some(u=>u.includes('orderPage=1'))).toBe(true);await page.getByLabel('订单支付方式').selectOption('sasi-balance');await expect.poll(()=>urls.some(u=>u.includes('provider=sasi-balance')&&u.includes('orderPage=0'))).toBe(true);await page.getByLabel('搜索订单或用户').fill('food-calorie');await page.getByRole('button',{name:'搜索',exact:true}).click();await expect.poll(()=>urls.some(u=>u.includes('search=food-calorie'))).toBe(true);
});
test('registration links to that users orders and traffic exposes daily/source data',async({page},info)=>{
 const urls:string[]=[];await page.route('**/api/account/money-admin?*',r=>{urls.push(r.request().url());return r.fulfill({json:data})});await page.goto('/account/money-admin');await page.getByRole('tab',{name:'用户注册',exact:true}).click();await expect(page.getByRole('tabpanel')).toContainText('已验证');await page.screenshot({path:info.outputPath('admin-users.png')});await page.getByRole('button',{name:'3 笔 · 查看'}).click();await expect.poll(()=>urls.some(u=>u.includes('search=user-1'))).toBe(true);await expect(page.getByRole('tab',{name:'所有订单'})).toHaveAttribute('aria-selected','true');await page.getByRole('tab',{name:'访问统计'}).click();await expect(page.getByRole('tabpanel')).toContainText('google.com');await page.getByLabel('访问统计时间').selectOption('7');await expect.poll(()=>urls.some(u=>u.includes('days=7'))).toBe(true);await page.getByText('查看每日明细',{exact:true}).click();await expect(page.getByRole('cell',{name:'2026-10-07',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('admin-visits.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('tab keyboard and access denial do not expose personal records',async({page})=>{
 await mock(page);await page.goto('/account/money-admin');await page.getByRole('tab',{name:'总览',exact:true}).focus();await page.keyboard.press('End');await expect(page.getByRole('tab',{name:'退款与提现'})).toBeFocused();await expect(page.getByRole('tabpanel')).toHaveCount(1);await page.unroute('**/api/account/money-admin?*');await page.route('**/api/account/money-admin?*',r=>r.fulfill({status:403,json:{error:'FORBIDDEN'}}));await page.reload();await expect(page.getByRole('alert').filter({hasText:'管理员邮箱'})).toContainText('管理员邮箱');await expect(page.getByRole('tabpanel')).toHaveCount(0);await expect(page.getByRole('link',{name:'前往登录'})).toHaveAttribute('href','/account?mode=signin');
});
test('public visit routes exclude private paths, identifiers and query content',()=>{
 for(const path of ['/account','/account/money-admin','/api/money/summary','/tools/admin','/tools/pay','/sasi/connections','/sasi?prompt=secret','/tools/result','/books/private-id','/tools/private%2Fid'])expect(publicVisitPath(path)).toBeNull();
 for(const path of ['/','/sasi','/tools/food-calorie','/en'])expect(publicVisitPath(path)).toBe(path);
});
test('real unauthenticated admin data request is denied',async({request})=>{const r=await request.get('/api/account/money-admin?days=30');expect([403,503]).toContain(r.status());const body=await r.json();expect(['FORBIDDEN','MONEY_ADMIN_UNAVAILABLE']).toContain(body.error);expect(body.dashboard).toBeUndefined();});
