import {test,expect} from 'playwright/test';
import {creationMethod} from '../../lib/sasi/creation-methods';
import {inferUnifiedSasiIntent} from '../../lib/sasi/core/unified-intent';
test('one natural-language router covers all public SASI capabilities',()=>{
 expect(inferUnifiedSasiIntent('帮我构建一个官网')).toBe('website');
 expect(inferUnifiedSasiIntent('生成一部100集短剧')).toBe('drama');
 expect(inferUnifiedSasiIntent('生成一张宇宙封面图')).toBe('image');
 expect(inferUnifiedSasiIntent('把这本书活化成可以对话的智能体')).toBe('book');
 expect(inferUnifiedSasiIntent('研究这些论文并给出证据')).toBe('research');
 expect(inferUnifiedSasiIntent('教我这一章并出练习题')).toBe('learning');
 expect(inferUnifiedSasiIntent('你好，聊聊天')).toBe('chat');
});
test('empty selections preserve automatic creative methods',()=>{expect(creationMethod('video',[]).ids).toEqual(expect.arrayContaining(['continuity','shots']));expect(creationMethod('website',[]).ids).toEqual(expect.arrayContaining(['website','mobile']));expect(creationMethod('image',[]).ids).toEqual(expect.arrayContaining(['image','continuity']));});
for(const lang of ['zh','en','ja','ko','fr','de','es','pt','ar'])test('one SASI composer and simple attachment menu '+lang,async({page})=>{await page.goto('/sasi?lang='+lang);await expect(page.locator('main textarea')).toHaveCount(1);await expect(page.locator('[data-sasi-task-toolbar]')).toHaveCount(0);await page.locator('button[aria-controls],button[aria-expanded]').filter({hasText:'＋'}).click();await expect(page.locator('main a[href="/sasi/connections"]')).toBeVisible();await expect(page.locator('main input[type="checkbox"]')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);});
for(const exhausted of [true,false])test('quota exhaustion is distinguished from service unavailability '+exhausted,async({page})=>{await page.route('**/api/sasi/experience/text',route=>route.fulfill({json:{state:'needs-connection',experienceExhausted:exhausted}}));await page.route('**/api/sasi/byok/text',route=>route.fulfill({status:409,json:{error:'CONNECTION_REQUIRED'}}));await page.goto('/sasi?mode=chat&lang=zh');await page.locator('textarea').fill('你好');await page.locator('textarea').press('Enter');if(exhausted)await expect(page.getByRole('status')).toContainText('今日免费额度已用完');else await expect(page.getByRole('status')).not.toContainText('今日免费额度已用完');await expect(page.locator('main a[href="/sasi/connections"]').last()).toBeVisible();});
test('missing video connection shows a direct action rather than quota exhaustion',async({page})=>{await page.route('**/api/sasi/projects',route=>route.fulfill({json:{project:{id:'88888888-8888-4888-8888-888888888888'}}}));await page.route('**/api/sasi/byok/video*',route=>route.fulfill({json:{connected:false,profiles:[],tasks:[]}}));await page.goto('/sasi?lang=zh');await page.locator('textarea').fill('生成20集短剧');await page.locator('textarea').press('Enter');await expect(page.locator('[data-sasi-task="drama"]')).toBeVisible();await expect(page.getByRole('status')).toContainText('生成视频需要连接支持视频生成的智能服务');await expect(page.getByRole('status')).not.toContainText('今日免费额度已用完');await page.locator('[data-sasi-task="drama"] button[aria-expanded]').click();await expect(page.locator('[data-sasi-task="drama"] [role="region"] input[type="checkbox"]')).toHaveCount(0);});
