import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Bi from "@/components/Bi";
import FaqSection, { type BilingualFaqItem } from "@/components/FaqSection";

const PRIVACY_FAQ: BilingualFaqItem[] = [
  {
    qZh: "灵犀场会出售我的出生信息或个人数据吗？", qEn: "Does Lingxi Field sell my birth information or personal data?",
    aZh: "不会。用户提交的信息仅用于提供对应的个人探索体验、保存记录以及优化服务。灵犀场不会出售用户数据，也不会将个人信息用于广告交易或其他无关用途。",
    aEn: "No. Information you submit is used only to provide your personal exploration experience, save your records, and improve the service. Lingxi Field does not sell user data, and does not use personal information for advertising transactions or other unrelated purposes.",
  },
  {
    qZh: "我可以删除自己的数据吗？", qEn: "Can I delete my own data?",
    aZh: "可以。用户可以通过账户功能管理自己的记录。如果希望删除账户或请求清除相关数据，可以发送邮件至 support@lingxifield.com，我们将在合理时间内处理。",
    aEn: "Yes. You can manage your own records through your account. If you'd like to delete your account or request that related data be cleared, email support@lingxifield.com and we will handle it within a reasonable time.",
  },
];

export const metadata = {
  title: "隐私政策 | 灵犀场 | Privacy Policy | Lingxi Field",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      <Nav />
      <main className="mx-auto max-w-3xl px-6 py-24">
        <div className="rounded-sm border border-white/10 bg-void-deep px-8 py-10 sm:px-12 sm:py-14">
        <h1 className="font-display text-4xl font-light text-bone">
          <Bi zh="隐私政策" en="Privacy Policy" />
        </h1>
        <p className="mt-2 text-sm text-bone-dim">
          <Bi zh="最后更新：2026年7月" en="Last updated: July 2026" />
        </p>

        <div className="mt-10 space-y-8 text-base leading-8 text-bone-dim">
          <section>
            <h2 className="font-display text-xl text-bone">
              <Bi zh="1. 我们收集的信息" en="1. Information We Collect" />
            </h2>
            <p className="mt-3">
              <Bi
                zh="为了提供灵犀场体验，我们可能收集：账户信息（例如邮箱地址，用于账户登录和身份验证）；探索数据（包括出生日期、出生时间（可选）、出生地点（可选）、用户主动填写的愿景、梦境记录、个人探索记录）；技术信息（包括浏览器类型、设备信息、页面访问记录，用于网站运行、安全维护和体验优化）。"
                en="To provide the Lingxi Field experience, we may collect: account information (such as your email address, used for login and identity verification); exploration data (including birth date, birth time (optional), birth place (optional), visions you choose to enter, dream journal entries, and your personal exploration records); and technical information (including browser type, device information, and page-visit records, used to run the site, maintain security, and improve the experience)."
              />
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-bone">
              <Bi zh="2. 信息用途" en="2. How We Use This Information" />
            </h2>
            <p className="mt-3">
              <Bi
                zh="我们使用信息用于：生成个人化体验内容；保存用户探索记录；提供账户服务；优化产品体验；提供客户支持。"
                en="We use information to: generate personalized experience content; save your exploration records; provide account services; improve the product experience; and provide customer support."
              />
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-bone">
              <Bi zh="3. 内容生成方式" en="3. How Content Is Generated" />
            </h2>
            <p className="mt-3">
              <Bi
                zh="部分体验内容会结合数据计算系统、智能生成技术、内容模型服务，生成个性化文字内容。用户提交的信息，仅用于生成对应体验内容。我们不会将用户数据用于训练第三方模型。"
                en="Some content is generated by combining a data-computation system, intelligent generation technology, and a content-model service to produce personalized text. Information you submit is used only to generate your corresponding experience content. We do not use your data to train third-party models."
              />
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-bone">
              <Bi zh="4. 数据存储与保护" en="4. Data Storage & Protection" />
            </h2>
            <p className="mt-3">
              <Bi
                zh="用户数据存储于 Supabase 数据服务系统。我们采用合理的数据安全措施，包括访问控制和安全策略，保护用户数据。"
                en="User data is stored on the Supabase data service. We use reasonable data-security measures, including access controls and security policies, to protect your data."
              />
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-bone">
              <Bi zh="5. 用户的数据权利" en="5. Your Data Rights" />
            </h2>
            <p className="mt-3">
              <Bi
                zh="用户可以：查看自己的数据；删除个人记录；请求注销账户；请求数据处理说明。如需帮助：support@lingxifield.com"
                en="You may: view your own data; delete personal records; request account closure; or request an explanation of how your data is processed. For help: support@lingxifield.com"
              />
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-bone">
              <Bi zh="6. 未成年人隐私" en="6. Children's Privacy" />
            </h2>
            <p className="mt-3">
              <Bi
                zh="灵犀场不主动收集儿童个人信息。如发现未成年人未经授权提交个人数据，我们会及时处理删除。"
                en="Lingxi Field does not knowingly collect personal information from children. If we discover that a minor has submitted personal data without authorization, we will promptly delete it."
              />
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-bone">
              <Bi zh="7. 跨境数据处理" en="7. Cross-Border Data Processing" />
            </h2>
            <p className="mt-3">
              <Bi
                zh="由于部分技术服务可能部署于不同地区，用户数据可能发生跨境处理。我们会要求合作服务商遵循合理的数据保护标准。"
                en="Because some technical services may be deployed in different regions, your data may be processed across borders. We require our service partners to follow reasonable data-protection standards."
              />
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-bone">
              <Bi zh="8. 联系我们" en="8. Contact Us" />
            </h2>
            <div className="mt-3 space-y-1 text-sm">
              <p>support@lingxifield.com</p>
              <p>business@lingxifield.com</p>
              <p>contact@lingxifield.com</p>
            </div>
          </section>
        </div>
        <div className="mt-16">
          <FaqSection items={PRIVACY_FAQ} />
        </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
