"use client";
import {BRAND_PUBLIC_COPY} from "@/lib/brand-public-copy";
import {PUBLIC_FEATURE_COPY} from "@/lib/public-feature-copy";
import Image from"next/image";
import Link from"next/link";
import{useLingxiLang,type LingxiLang}from"@/lib/lingxi-i18n";
import{productCatalogText}from"@/lib/product-catalog-i18n";
import{LINGXIFIELD_RELEASE}from"@/lib/release/version";

const channels=[["微信服务号","#wechat"],["小红书","https://xhslink.cn/m/8rig9AtdDvK"],["Bilibili","https://b23.tv/VhatqCq"],["抖音","https://v.douyin.com/WG4QmhbliNk"],["X","https://x.com/lingxifield?s=11"],["YouTube","https://youtube.com/@lingxifield?si=fJss8KQIAl8NDS9X"]]as const;

type FooterCopy={name:string;slogan:string;lead:string;tools:string;toolsBody:string;sasi:string;sasiBody:string;useful:string;account:string;orders:string;withdraw:string;refunds:string;connect:string;release:string};
const copy:Record<LingxiLang,FooterCopy>={
 zh:{name:"灵犀场 LINGXIFIELD｜SASI全球多模型智能创作平台",slogan:"100+在线实用工具＋SASI创作。",lead:"处理文件、整理资料，也把短剧、网站、书本、学习和科研创作继续推进。",tools:"100+在线实用工具",toolsBody:"PDF、图片、视频音频、文件表格、格式转换、二维码、安全识别、临时邮箱、阅后即焚与隐私工具。",sasi:"SASI 多模型创作",sasiBody:"短剧视频生成、网站构建、书本、学习、科研多模型创作；9国语言，支持 CNY/USD 与微信支付、支付宝、PayPal。",useful:"常用入口",account:"我的账户",orders:"订单与任务",withdraw:"余额提现",refunds:"退款说明",connect:"连接我的智能服务",release:"版本与更新"},
 en:{name:"LINGXIFIELD",slogan:"Work with files and sources.",lead:"Work with PDFs, images, video and text. Organize sources and ask questions about them. Processing details and prices are shown before use.",tools:"Practical tools",toolsBody:"Choose a PDF, image, video or text tool, follow the steps and save your file. See each tool for processing details and prices.",sasi:"Sources and questions",sasiBody:"Short video creation, static websites, books, study and research with SASI. Nine languages, CNY/USD, WeChat Pay, Alipay and PayPal.",useful:"Useful links",account:"My account",orders:"Orders & tasks",withdraw:"Withdraw balance",refunds:"Refunds",connect:"Creative connections",release:"Release notes"},
 ja:{name:"LINGXIFIELD",slogan:"ファイルを扱い、資料を整理。",lead:"PDF・画像・動画・テキストを扱い、資料を整理して原文について質問できます。処理方法と料金は利用前に確認できます。",tools:"実用ツール",toolsBody:"PDF・画像・動画・テキストのツールを選び、手順に沿って処理して保存します。処理方法と料金は各ツールで確認できます。",sasi:"資料と質問",sasiBody:"SASIで短編動画・静的サイト・本・学習・研究を制作。9言語、CNY/USD、WeChat Pay・Alipay・PayPalに対応。",useful:"よく使う入口",account:"アカウント",orders:"注文とタスク",withdraw:"残高を引き出す",refunds:"返金案内",connect:"制作サービス接続",release:"更新情報"},
 ko:{name:"LINGXIFIELD",slogan:"파일을 처리하고 자료를 정리하세요.",lead:"PDF·이미지·영상·텍스트를 처리하고 자료를 정리해 원문에 대해 질문하세요. 처리 방식과 요금은 사용 전에 확인할 수 있습니다.",tools:"실용 도구",toolsBody:"PDF·이미지·영상·텍스트 도구를 선택하고 안내에 따라 처리한 뒤 저장하세요. 처리 방식과 요금은 각 도구에서 확인하세요.",sasi:"자료와 질문",sasiBody:"SASI로 짧은 영상, 정적 웹사이트, 책, 학습, 연구를 만드세요. 9개 언어, CNY/USD, 위챗페이, 알리페이, PayPal을 지원합니다.",useful:"자주 쓰는 메뉴",account:"내 계정",orders:"주문 및 작업",withdraw:"잔액 출금",refunds:"환불 안내",connect:"창작 서비스 연결",release:"업데이트"},
 fr:{name:"LINGXIFIELD",slogan:"Traitez vos fichiers et organisez vos sources.",lead:"Traitez PDF, images, vidéos et textes. Organisez vos sources et posez des questions à leur sujet. Les modalités et tarifs sont indiqués avant utilisation.",tools:"Outils pratiques",toolsBody:"Choisissez un outil PDF, image, vidéo ou texte, suivez les étapes et enregistrez votre fichier. Consultez les modalités et tarifs sur sa page.",sasi:"Sources et questions",sasiBody:"SASI pour les vidéos courtes, sites statiques, livres, études et recherche. Neuf langues, CNY/USD, WeChat Pay, Alipay et PayPal.",useful:"Accès utiles",account:"Mon compte",orders:"Commandes et tâches",withdraw:"Retirer le solde",refunds:"Remboursements",connect:"Connexions de création",release:"Mises à jour"},
 de:{name:"LINGXIFIELD",slogan:"Dateien bearbeiten, Quellen ordnen.",lead:"Bearbeite PDFs, Bilder, Videos und Texte. Ordne Quellen und stelle Fragen dazu. Verarbeitung und Preise werden vor der Nutzung angezeigt.",tools:"Praktische Tools",toolsBody:"Wähle ein Tool für PDF, Bilder, Video oder Text, folge den Schritten und speichere die Datei. Verarbeitung und Preise stehen auf der Tool-Seite.",sasi:"Quellen und Fragen",sasiBody:"SASI für Kurzvideos, statische Websites, Bücher, Lernen und Forschung. Neun Sprachen, CNY/USD, WeChat Pay, Alipay und PayPal.",useful:"Nützliche Links",account:"Mein Konto",orders:"Bestellungen & Aufgaben",withdraw:"Guthaben auszahlen",refunds:"Rückerstattungen",connect:"Kreativdienste verbinden",release:"Aktualisierungen"},
 es:{name:"LINGXIFIELD",slogan:"Procesa archivos y organiza fuentes.",lead:"Trabaja con PDF, imágenes, vídeos y textos. Organiza fuentes y haz preguntas sobre ellas. El tratamiento y los precios se indican antes del uso.",tools:"Herramientas prácticas",toolsBody:"Elige una herramienta para PDF, imágenes, vídeo o texto, sigue los pasos y guarda el archivo. Consulta los detalles y precios en cada herramienta.",sasi:"Fuentes y preguntas",sasiBody:"SASI para vídeos cortos, sitios estáticos, libros, estudio e investigación. Nueve idiomas, CNY/USD, WeChat Pay, Alipay y PayPal.",useful:"Accesos útiles",account:"Mi cuenta",orders:"Pedidos y tareas",withdraw:"Retirar saldo",refunds:"Reembolsos",connect:"Conexiones de creación",release:"Actualizaciones"},
 pt:{name:"LINGXIFIELD",slogan:"Processe arquivos e organize fontes.",lead:"Trabalhe com PDF, imagens, vídeos e textos. Organize fontes e faça perguntas sobre elas. O processamento e os preços são informados antes do uso.",tools:"Ferramentas práticas",toolsBody:"Escolha uma ferramenta para PDF, imagens, vídeo ou texto, siga as etapas e salve o arquivo. Consulte os detalhes e preços na página da ferramenta.",sasi:"Fontes e perguntas",sasiBody:"SASI para vídeos curtos, sites estáticos, livros, estudo e pesquisa. Nove idiomas, CNY/USD, WeChat Pay, Alipay e PayPal.",useful:"Acessos úteis",account:"Minha conta",orders:"Pedidos e tarefas",withdraw:"Sacar saldo",refunds:"Reembolsos",connect:"Conexões de criação",release:"Atualizações"},
 ar:{name:"LINGXIFIELD",slogan:"عالج الملفات ونظّم المصادر.",lead:"عالج ملفات PDF والصور والفيديو والنصوص، ونظّم المصادر واطرح أسئلة عنها. تُعرض طريقة المعالجة والأسعار قبل الاستخدام.",tools:"أدوات عملية",toolsBody:"اختر أداة لملفات PDF أو الصور أو الفيديو أو النصوص، واتبع الخطوات واحفظ الملف. راجع طريقة المعالجة والأسعار في صفحة الأداة.",sasi:"المصادر والأسئلة",sasiBody:"SASI لإنشاء الفيديوهات القصيرة والمواقع الثابتة والكتب والدراسة والبحث. تسع لغات وCNY/USD والدفع عبر WeChat Pay وAlipay وPayPal.",useful:"روابط مفيدة",account:"حسابي",orders:"الطلبات والمهام",withdraw:"سحب الرصيد",refunds:"الاسترداد",connect:"اتصالات خدمات الإبداع",release:"التحديثات"}
};

export default function Footer(){
 const{t,lang}=useLingxiLang();const c=copy[lang]??copy.en;
 return <footer className="lx11-footer" id="wechat"><div className="lx11-footer-grid">
 <section className="lx11-footer-brand"><div className="lx11-footer-logo"><Image src="/images/lingxifield-logo.png" alt="" width={40} height={40}/><div><b>{BRAND_PUBLIC_COPY[lang].title}</b></div></div>
 <p className="lx11-footer-brand-lead"><b>{PUBLIC_FEATURE_COPY[lang].headline}</b></p>
 <p>{PUBLIC_FEATURE_COPY[lang].freeTools}</p>
 <div className="lx11-footer-capability"><p>{c.sasiBody}</p></div>
 <span>lingxifield.com · lingxifield.cn</span><span style={{opacity:.58,fontSize:12}}>v{LINGXIFIELD_RELEASE.website} · <Link href="/release">{c.release}</Link></span></section>
 <nav><b>{t("start")}</b><Link href="/products">{productCatalogText(lang,"title")}</Link><Link href="/tools">{t("tools")}</Link><Link href="/sasi">{t("studio")}</Link><Link href="/ai-knowledge">{t("books")}</Link><Link href="/ai-learning">{t("learning")}</Link><Link href="/ai-research">{t("research")}</Link><Link href="/ai-wallet">{t("wallet")}</Link></nav>
 <nav><b>{c.useful}</b><Link href="/account">{c.account}</Link><Link href="/account/orders">{c.orders}</Link><Link href="/account/withdrawals">{c.withdraw}</Link><Link href="/refunds">{c.refunds}</Link><Link href="/sasi/connections">{c.connect}</Link></nav>
 <section><b>{t("follow")}</b><div className="lx11-footer-social">{channels.map(([l,h])=>h.startsWith("#")?<a key={l} href={h}>{l}</a>:<a key={l} href={h} target="_blank" rel="noreferrer">{l} ↗</a>)}</div></section>
 <section className="lx11-footer-qrs"><div><Image src="/images/lingxifield-wechat-service-qr.jpg" alt="" width={74} height={74}/><span>{t("service")}</span></div><div><Image src="/images/miniapp-qrcode.png" alt="" width={74} height={74}/><span>{t("miniapp")}</span></div></section></div>
 <div className="lx11-footer-legal"><span>© {t("brandFull")}</span><Link href="/terms">{t("terms")}</Link><Link href="/privacy">{t("privacy")}</Link><Link href="/refunds">{t("refunds")}</Link><Link href="/legal/sasi">{t("sasiRules")}</Link><a href="https://beian.miit.gov.cn/" target="_blank" rel="noreferrer">湘ICP备2026031465号 ↗</a></div></footer>;
}
