"use client";
import Image from"next/image";
import Link from"next/link";
import{useLingxiLang,type LingxiLang}from"@/lib/lingxi-i18n";
import{productCatalogText}from"@/lib/product-catalog-i18n";
import{LINGXIFIELD_RELEASE}from"@/lib/release/version";

const channels=[["微信服务号","#wechat"],["小红书","https://xhslink.cn/m/8rig9AtdDvK"],["Bilibili","https://b23.tv/VhatqCq"],["抖音","https://v.douyin.com/WG4QmhbliNk"],["X","https://x.com/lingxifield?s=11"],["YouTube","https://youtube.com/@lingxifield?si=fJss8KQIAl8NDS9X"]]as const;

type FooterCopy={name:string;slogan:string;lead:string;origin:string;tools:string;toolsBody:string;sasi:string;sasiBody:string;useful:string;account:string;orders:string;withdraw:string;refunds:string;connect:string};
const copy:Record<LingxiLang,FooterCopy>={
 zh:{name:"灵犀场 LINGXIFIELD｜SASI全球多模型智能创作生态平台",slogan:"一键创造，一念即达。",lead:"一个让想法被理解、让问题被处理、让结果真正发生的场智能数字空间。",origin:"从一个文件、一张图片、一段视频、一餐饭，到一个还没理清的念头，都可以从灵犀场开始。",tools:"免费实用工具",toolsBody:"PDF、图片、视频、字幕、网页、表格、文件隐私与日常识别等高频需求，打开即可处理并得到结果。",sasi:"SASI 创作与构建",sasiBody:"从 AI 短剧、网站构建，到书本 SASI、学习 SASI、科研 SASI，把想法逐步构建成真正可以使用的结果。",useful:"常用入口",account:"我的账户",orders:"订单与任务",withdraw:"余额提现",refunds:"退款说明",connect:"创作连接"},
 en:{name:"LINGXIFIELD | SASI Intelligent Ecosystem",slogan:"Create in one click. Reach it in one thought.",lead:"An intelligent digital space where ideas are understood, problems are handled, and usable results actually happen.",origin:"From a file, image, video or meal to an idea that is not clear yet, you can start with LINGXIFIELD.",tools:"Free practical tools",toolsBody:"Handle PDFs, images, video, subtitles, webpages, spreadsheets, file privacy and everyday recognition tasks and get the result directly.",sasi:"SASI creation & building",sasiBody:"From AI short drama and website building to Book SASI, Learning SASI and Research SASI, turn ideas into results you can actually use.",useful:"Useful links",account:"My account",orders:"Orders & tasks",withdraw:"Withdraw balance",refunds:"Refunds",connect:"Creative connections"},
 ja:{name:"LINGXIFIELD｜SASI インテリジェント・エコシステム",slogan:"ワンクリックで創り、一念で届く。",lead:"アイデアを理解し、問題を処理し、使える結果まで進める知的デジタル空間です。",origin:"ファイル、画像、動画、食事、まだ整理できていない考えまで、LINGXIFIELD から始められます。",tools:"無料の実用ツール",toolsBody:"PDF、画像、動画、字幕、ウェブ、表計算、ファイルのプライバシー、日常認識を開いてすぐ処理できます。",sasi:"SASI 制作・構築",sasiBody:"AIショートドラマ、Web構築、Book SASI、学習SASI、研究SASIまで、アイデアを実際に使える結果へ育てます。",useful:"よく使う入口",account:"アカウント",orders:"注文とタスク",withdraw:"残高を引き出す",refunds:"返金案内",connect:"制作サービス接続"},
 ko:{name:"LINGXIFIELD｜SASI 지능형 생태계",slogan:"한 번의 클릭으로 만들고, 한 생각으로 닿습니다.",lead:"아이디어를 이해하고 문제를 처리해 실제로 사용할 수 있는 결과까지 이어가는 지능형 디지털 공간입니다.",origin:"파일, 이미지, 영상, 한 끼 식사, 아직 정리되지 않은 생각까지 LINGXIFIELD에서 시작할 수 있습니다.",tools:"무료 실용 도구",toolsBody:"PDF, 이미지, 영상, 자막, 웹, 표, 파일 개인정보와 일상 인식 작업을 열어서 바로 처리할 수 있습니다.",sasi:"SASI 창작과 구축",sasiBody:"AI 숏드라마, 웹사이트 구축, Book SASI, 학습 SASI, 연구 SASI까지 아이디어를 실제로 쓸 수 있는 결과로 만듭니다.",useful:"자주 쓰는 메뉴",account:"내 계정",orders:"주문 및 작업",withdraw:"잔액 출금",refunds:"환불 안내",connect:"창작 서비스 연결"},
 fr:{name:"LINGXIFIELD | Écosystème intelligent SASI",slogan:"Créez en un clic. Atteignez le résultat en une pensée.",lead:"Un espace numérique intelligent où les idées sont comprises, les problèmes traités et les résultats deviennent réellement utilisables.",origin:"D’un fichier, d’une image, d’une vidéo ou d’un repas à une idée encore floue, tout peut commencer dans LINGXIFIELD.",tools:"Outils pratiques gratuits",toolsBody:"Traitez PDF, images, vidéo, sous-titres, pages web, tableaux, confidentialité des fichiers et reconnaissance du quotidien.",sasi:"Création et construction SASI",sasiBody:"Mini-séries IA, création de sites, Book SASI, Learning SASI et Research SASI transforment les idées en résultats utilisables.",useful:"Accès utiles",account:"Mon compte",orders:"Commandes et tâches",withdraw:"Retirer le solde",refunds:"Remboursements",connect:"Connexions de création"},
 de:{name:"LINGXIFIELD | SASI Intelligentes Ökosystem",slogan:"Mit einem Klick erschaffen. Mit einem Gedanken ans Ziel.",lead:"Ein intelligenter digitaler Raum, in dem Ideen verstanden, Probleme bearbeitet und nutzbare Ergebnisse Wirklichkeit werden.",origin:"Von Datei, Bild, Video oder Mahlzeit bis zu einer noch ungeklärten Idee kann alles bei LINGXIFIELD beginnen.",tools:"Kostenlose praktische Tools",toolsBody:"PDF, Bilder, Video, Untertitel, Webseiten, Tabellen, Dateiprivatsphäre und alltägliche Erkennung direkt bearbeiten.",sasi:"SASI Kreation & Aufbau",sasiBody:"Von KI-Kurzdramen und Website-Bau bis Book SASI, Learning SASI und Research SASI werden Ideen zu nutzbaren Ergebnissen.",useful:"Nützliche Links",account:"Mein Konto",orders:"Bestellungen & Aufgaben",withdraw:"Guthaben auszahlen",refunds:"Rückerstattungen",connect:"Kreativdienste verbinden"},
 es:{name:"LINGXIFIELD | Ecosistema inteligente SASI",slogan:"Crea con un clic. Llega con una idea.",lead:"Un espacio digital inteligente donde las ideas se entienden, los problemas se resuelven y los resultados realmente suceden.",origin:"Desde un archivo, imagen, vídeo o comida hasta una idea aún sin ordenar, todo puede empezar en LINGXIFIELD.",tools:"Herramientas prácticas gratis",toolsBody:"Procesa PDF, imágenes, vídeo, subtítulos, páginas web, hojas de cálculo, privacidad de archivos y reconocimiento cotidiano.",sasi:"Creación y construcción SASI",sasiBody:"Desde minidramas con IA y creación de sitios hasta Book SASI, Learning SASI y Research SASI, convierte ideas en resultados utilizables.",useful:"Accesos útiles",account:"Mi cuenta",orders:"Pedidos y tareas",withdraw:"Retirar saldo",refunds:"Reembolsos",connect:"Conexiones de creación"},
 pt:{name:"LINGXIFIELD | Ecossistema inteligente SASI",slogan:"Crie em um clique. Chegue lá em um pensamento.",lead:"Um espaço digital inteligente onde ideias são compreendidas, problemas são tratados e resultados realmente acontecem.",origin:"De um arquivo, imagem, vídeo ou refeição a uma ideia ainda não organizada, tudo pode começar na LINGXIFIELD.",tools:"Ferramentas práticas grátis",toolsBody:"Processe PDF, imagens, vídeo, legendas, páginas web, planilhas, privacidade de arquivos e reconhecimento cotidiano.",sasi:"Criação e construção SASI",sasiBody:"De minidramas com IA e criação de sites a Book SASI, Learning SASI e Research SASI, transforme ideias em resultados utilizáveis.",useful:"Acessos úteis",account:"Minha conta",orders:"Pedidos e tarefas",withdraw:"Sacar saldo",refunds:"Reembolsos",connect:"Conexões de criação"},
 ar:{name:"LINGXIFIELD | منظومة SASI الذكية",slogan:"أنشئ بنقرة، واصل بفكرة.",lead:"مساحة رقمية ذكية تُفهم فيها الأفكار، وتُعالج المشكلات، وتتحول إلى نتائج قابلة للاستخدام.",origin:"من ملف أو صورة أو فيديو أو وجبة إلى فكرة لم تتضح بعد، يمكنك البدء من LINGXIFIELD.",tools:"أدوات عملية مجانية",toolsBody:"عالج PDF والصور والفيديو والترجمة والويب والجداول وخصوصية الملفات والتعرّف اليومي واحصل على النتيجة مباشرة.",sasi:"إنشاء وبناء SASI",sasiBody:"من الدراما القصيرة بالذكاء الاصطناعي وبناء المواقع إلى Book SASI وLearning SASI وResearch SASI، حوّل الأفكار إلى نتائج قابلة للاستخدام.",useful:"روابط مفيدة",account:"حسابي",orders:"الطلبات والمهام",withdraw:"سحب الرصيد",refunds:"الاسترداد",connect:"اتصالات خدمات الإبداع"}
};

export default function Footer(){
 const{t,lang}=useLingxiLang();const c=copy[lang]??copy.en;
 return <footer className="lx11-footer" id="wechat"><div className="lx11-footer-grid">
 <section className="lx11-footer-brand"><div className="lx11-footer-logo"><Image src="/images/lingxifield-logo.png" alt="" width={40} height={40}/><div><b>{c.name}</b><small>LINGXIFIELD</small></div></div>
 <p className="lx11-footer-brand-lead"><b>{c.slogan}</b></p><p>{c.lead}</p><p>{c.origin}</p>
 <div className="lx11-footer-capability"><b>{c.tools}</b><p>{c.toolsBody}</p></div>
 <div className="lx11-footer-capability"><b>{c.sasi}</b><p>{c.sasiBody}</p></div>
 <span>lingxifield.com · lingxifield.cn</span><span style={{opacity:.58,fontSize:12}}>v{LINGXIFIELD_RELEASE.website} · <Link href="/release">{lang==="zh"?"版本与更新":"Release"}</Link></span></section>
 <nav><b>{t("start")}</b><Link href="/products">{productCatalogText(lang,"title")}</Link><Link href="/tools">{t("tools")}</Link><Link href="/sasi">{t("studio")}</Link><Link href="/ai-knowledge">{t("books")}</Link><Link href="/ai-learning">{t("learning")}</Link><Link href="/ai-research">{t("research")}</Link><Link href="/ai-wallet">{t("wallet")}</Link></nav>
 <nav><b>{c.useful}</b><Link href="/account">{c.account}</Link><Link href="/account/orders">{c.orders}</Link><Link href="/account/withdrawals">{c.withdraw}</Link><Link href="/refunds">{c.refunds}</Link><Link href="/sasi/connections">{c.connect}</Link></nav>
 <section><b>{t("follow")}</b><div className="lx11-footer-social">{channels.map(([l,h])=>h.startsWith("#")?<a key={l} href={h}>{l}</a>:<a key={l} href={h} target="_blank" rel="noreferrer">{l} ↗</a>)}</div></section>
 <section className="lx11-footer-qrs"><div><Image src="/images/lingxifield-wechat-service-qr.jpg" alt="" width={74} height={74}/><span>{t("service")}</span></div><div><Image src="/images/miniapp-qrcode.png" alt="" width={74} height={74}/><span>{t("miniapp")}</span></div></section></div>
 <div className="lx11-footer-legal"><span>© {t("brandFull")}</span><Link href="/terms">{t("terms")}</Link><Link href="/privacy">{t("privacy")}</Link><Link href="/refunds">{t("refunds")}</Link><Link href="/legal/sasi">{t("sasiRules")}</Link><a href="https://beian.miit.gov.cn/" target="_blank" rel="noreferrer">湘ICP备2026031465号 ↗</a></div></footer>;
}
