"use client";
import {useCallback,useEffect,useState} from 'react';
import {useLingxiLang} from '@/lib/lingxi-i18n';
import {moneyText,moneyError,moneyNotice} from '@/lib/notifications/money-copy';
type Legacy={id:string;order_id:string;amount_fen:number;status:string;created_at:string};
export default function LegacyRefundMigrationPanel(){
 const{lang}=useLingxiLang();const[items,setItems]=useState<Legacy[]>([]),[busy,setBusy]=useState<string|null>(null),[msg,setMsg]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/account/withdrawals/legacy',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();setItems(d.items||[])}catch{setMsg(moneyText(lang,'unavailable'))}},[lang]);
 useEffect(()=>{void load()},[load]);
 async function migrate(x:Legacy){if(!confirm(moneyText(lang,'confirm')))return;setBusy(x.id);setMsg('');try{const r=await fetch('/api/account/withdrawals/legacy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requestId:x.id})});const d=await r.json();if(!r.ok){setMsg(moneyError(lang,d.error||''));return}setMsg(moneyText(lang,d.status==='completed'?'completed':d.status==='failed'?'failed':d.status==='requested'?'requested':'processing'));window.dispatchEvent(new Event('lingxi-money-updated'));await load()}catch{setMsg(moneyText(lang,'unavailable'))}finally{setBusy(null)}}
 async function cancel(x:Legacy){if(!confirm(moneyText(lang,'cancelConfirm')))return;setBusy(x.id);try{const r=await fetch('/api/account/withdrawals/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requestId:x.id,kind:'legacy'})}),b=await r.json();setMsg(r.ok?moneyText(lang,'cancelled'):moneyError(lang,b.error||''));window.dispatchEvent(new Event('lingxi-money-updated'));await load()}catch{setMsg(moneyText(lang,'unavailable'))}finally{setBusy(null)}}
 if(!items.length&&!msg)return null;
 return <section className="mt-8 space-y-4"><h2 className="text-xl font-semibold">{moneyText(lang,'legacyTitle')}</h2>{items.map(x=>{const c=moneyNotice(lang,'refund',x.status,'CNY',x.amount_fen,true);return <article id={`legacy-${x.id}`} key={x.id} className="scroll-mt-24 rounded-2xl border border-[var(--lx-line)] p-5"><b>{c.title}</b><p className="mt-3 text-sm leading-7">{c.body}</p><p className="mt-2 break-all text-xs text-[var(--lx-muted)]">{moneyText(lang,'reference')}: {x.id} · {new Date(x.created_at).toLocaleString(lang)}</p>{['requested','approved'].includes(x.status)&&<button className="mt-3 rounded-xl border border-[var(--lx-line)] px-4 py-2 disabled:opacity-50" disabled={busy!==null} onClick={()=>void migrate(x)}>{moneyText(lang,busy===x.id?'loading':'migrate')}</button>}{x.status==='requested'&&<button disabled={busy!==null} onClick={()=>void cancel(x)} className="ms-3 mt-3 rounded-xl border border-[var(--lx-line)] px-4 py-2 disabled:opacity-50">{moneyText(lang,'cancelRefund')}</button>}</article>})}{msg&&<p role="status">{msg}</p>}</section>;
}
