"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useMoneyAutoRefresh} from "@/lib/money/use-money-auto-refresh";
import {AdminData,adminDate,adminMoney,orderName,orderState,paymentName} from "@/lib/money/admin-dashboard-types";
import AdminRefundPanel from "@/components/money/AdminRefundPanel";
import s from "@/components/money/AdminDashboard.module.css";
const tabs=[['overview','总览'],['orders','所有订单'],['users','用户注册'],['visits','访问统计'],['refunds','退款与提现']] as const;
function Pager({page,total,onChange,loading}:{page:number;total:number;onChange:(page:number)=>void;loading:boolean}){return <div className={s.pager}><span>共 {total} 条 · 第 {page+1} / {Math.max(1,Math.ceil(total/25))} 页</span><button disabled={loading||page===0} onClick={()=>onChange(page-1)}>上一页</button><button disabled={loading||(page+1)*25>=total} onClick={()=>onChange(page+1)}>下一页</button></div>}
export default function MoneyAdminDashboard(){
 const[data,setData]=useState<AdminData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const[tab,setTab]=useState('overview'),[currency,setCurrency]=useState('CNY'),[days,setDays]=useState('30'),[search,setSearch]=useState(''),[draft,setDraft]=useState(''),[provider,setProvider]=useState('all'),[status,setStatus]=useState('all'),[orderPage,setOrderPage]=useState(0),[userPage,setUserPage]=useState(0);
 const request=useRef(0);
 const load=useCallback(async()=>{
  const serial=++request.current;setLoading(true);
  try{const q=new URLSearchParams({days,search,provider,status,orderPage:String(orderPage),userPage:String(userPage)}),r=await fetch('/api/account/money-admin?'+q,{cache:'no-store'});
   if(serial!==request.current)return;
   if(!r.ok){setData(null);setError(r.status===403?'请使用已验证的管理员邮箱登录后查看。':'暂时无法读取后台数据，请稍后刷新。');return}
   const body=await r.json();if(serial===request.current){setData(body);setError('')}
  }catch{if(serial===request.current)setError('暂时无法读取，请稍后刷新。')}finally{if(serial===request.current)setLoading(false)}
 },[days,search,provider,status,orderPage,userPage]);
 useEffect(()=>{const generation=request;void load();return()=>{generation.current++}},[load]);
 useMoneyAutoRefresh(load,Boolean(data?.withdrawals.some(w=>['requested','processing'].includes(w.status))),true);
 async function operate(action:string,id?:string){setBusy(true);setMessage('');try{const r=await fetch('/api/account/money-admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,id})}),b=await r.json();setMessage(!r.ok?'本次操作未完成，请刷新后核对。':action==='send-notices'?(b.configured?'邮件发送请求已处理，请查看发送记录。':'邮件服务尚未配置，申请仍保留在队列中。'):'已查询原渠道，请查看最新状态。');await load()}catch{setMessage('本次操作未完成，请刷新后核对。')}finally{setBusy(false)}}
 function searchSubmit(e:React.FormEvent){e.preventDefault();setSearch(draft.trim());setOrderPage(0);setUserPage(0)}
 const d=data?.dashboard,money=d?.summary.money.find(m=>m.currency===currency);
 const rankings=d?[{title:'热门页面',rows:d.traffic.pages.map(x=>({label:x.path,views:x.views}))},{title:'访问来源',rows:d.traffic.sources.map(x=>({label:x.source||'直接访问 / 站内访问',views:x.views}))},{title:'访问域名',rows:d.traffic.hosts.map(x=>({label:x.host,views:x.views}))},{title:'设备',rows:d.traffic.devices.map(x=>({label:x.device==='mobile'?'手机':'电脑',views:x.views}))}]:[];
 const peak=Math.max(1,...(d?.traffic.daily.map(x=>x.views)||[]));
 return <main className={s.page}><header className={s.header}><div><h1>管理后台</h1><p>资金、订单、用户与网站访问，一处查看。</p></div><button disabled={loading} onClick={()=>void load()}>{loading?'正在更新…':'刷新数据'}</button></header>
 {error&&<p role="alert" className={s.notice}>{error} <Link href="/account?mode=signin">前往登录</Link></p>}
 {!data&&!error&&<p className={s.empty} role="status">正在读取后台…</p>}
 {data&&d&&<><nav className={s.tabs} role="tablist" aria-label="后台栏目">{tabs.map(([id,label],index)=><button key={id} id={'tab-'+id} role="tab" tabIndex={tab===id?0:-1} aria-selected={tab===id} aria-controls={'panel-'+id} onClick={()=>setTab(id)} onKeyDown={e=>{const next=e.key==='ArrowRight'?(index+1)%tabs.length:e.key==='ArrowLeft'?(index+tabs.length-1)%tabs.length:e.key==='Home'?0:e.key==='End'?tabs.length-1:null;if(next!==null){e.preventDefault();setTab(tabs[next][0]);document.getElementById('tab-'+tabs[next][0])?.focus()}}}>{label}</button>)}</nav>
 <section id={'panel-'+tab} role="tabpanel" aria-labelledby={'tab-'+tab} aria-busy={loading}>
 {tab==='overview'&&<><div className={s.hero}><div className={s.heroTop}><h2>累计资金记录</h2><select aria-label="统计币种" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="CNY">CNY ¥ 人民币</option><option value="USD">USD $ 美元</option></select></div><div className={s.metrics}><article><p>渠道收款 · 含充值</p><strong>{adminMoney(currency,money?.cash_received??0)}</strong></article><article><p>其中：余额充值</p><strong>{adminMoney(currency,money?.topups??0)}</strong></article><article><p>余额支付订单</p><strong>{adminMoney(currency,money?.balance_orders??0)}</strong></article></div><p className={s.heroFoot}>渠道直接购买：{adminMoney(currency,money?.direct_sales??0)}。余额支付消耗此前充值，不会再次计入渠道收款。这里显示已支付订单记录，实际到账以支付渠道账单为准。</p></div>
 <div className={s.cards}><article className={s.card}><p>全部用户</p><strong>{d.summary.users}</strong><small>今日新注册 {d.summary.new_users_today} 人</small></article><article className={s.card}><p>全部订单</p><strong>{d.summary.orders}</strong><small>已支付 {d.summary.paid_orders} 笔</small></article><article className={s.card}><p>今日网站访问</p><strong>{d.traffic.today_views}</strong><small>公开页面的浏览次数</small></article></div>
 <div className={s.sectionTitle}><h2>后台动态</h2><span className={s.subtle}>最近 25 条 · 北京时间</span></div><div className={s.panel}>{d.activity.map(a=><div className={s.activity} key={a.kind+a.id}><div><p>{a.kind==='registration'?'新用户注册':orderName(a)+' · '+paymentName(a.provider)}</p><small>{a.email||'未提供邮箱'} · {adminDate(a.at)}</small>{a.kind==='payment'&&<small>订单 {a.id}</small>}</div><div>{a.kind==='payment'?<b>{adminMoney(a.currency,a.amount)}</b>:<span className={s.badge}>新用户</span>}</div></div>)}{!d.activity.length&&<p className={s.empty}>暂无动态</p>}</div><p className={s.muted}>余额消费和新注册在此显示；退款、提现邮件提醒可在对应栏目查看。</p></>}
 {(tab==='orders'||tab==='users')&&<><form className={s.toolbar} onSubmit={searchSubmit}><input aria-label="搜索订单或用户" placeholder={tab==='orders'?'搜索邮箱、订单编号或工具名称':'搜索用户邮箱或编号'} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={120}/><button type="submit">搜索</button>{search&&<button type="button" onClick={()=>{setDraft('');setSearch('');setOrderPage(0);setUserPage(0)}}>清除</button>}{tab==='orders'&&<><select aria-label="订单支付方式" value={provider} onChange={e=>{setProvider(e.target.value);setOrderPage(0)}}><option value="all">所有支付方式</option>{['sasi-balance','wechat','wechat_mini_virtual','alipay','paypal'].map(p=><option value={p} key={p}>{paymentName(p)}</option>)}</select><select aria-label="订单状态" value={status} onChange={e=>{setStatus(e.target.value);setOrderPage(0)}}><option value="all">所有订单状态</option>{['paid','pending','refunded','failed','cancelled'].map(v=><option key={v} value={v}>{orderState(v)}</option>)}</select></>}</form>
 {tab==='orders'?<><p className={s.muted}>包含所有用户的历史订单；金额按订单原币种显示。</p><div className={s.tableWrap}><table className={s.table}><thead><tr><th>创建时间</th><th>用户与购买内容</th><th>金额</th><th>支付路径</th><th>状态与详情</th></tr></thead><tbody>{d.orders.map(o=><tr key={o.id}><td>{adminDate(o.created_at)}</td><td>{o.email||'未提供邮箱'}<small>{orderName(o)}</small></td><td><b>{adminMoney(o.currency,o.amount)}</b><small>{o.currency==='UNKNOWN'?'币种待核对':o.currency}</small></td><td>{paymentName(o.provider)}<small>{o.provider==='sasi-balance'?'已充值余额 → 本次购买':o.is_topup?'支付渠道 → 账户余额':'支付渠道 → 本次购买'}</small></td><td><span className={s.badge} data-state={o.status}>{orderState(o.status)}</span><details><summary>订单详情</summary><p>订单编号：{o.id}</p><p>用户编号：{o.user_id}</p><p>支付时间：{adminDate(o.paid_at)}</p><p>渠道交易编号：{o.provider_payment_id||(o.provider==='sasi-balance'?'余额内部扣款，无新渠道交易':'尚未返回')}</p>{o.provider==='sasi-balance'&&<p>本次使用此前充值的余额，不产生新的微信、支付宝或银行入账。</p>}</details></td></tr>)}</tbody></table>{!d.orders.length&&<p className={s.empty}>没有匹配的订单</p>}</div><Pager page={orderPage} total={d.order_total} loading={loading} onChange={setOrderPage}/></>:<><p className={s.muted}>真实注册账户，按注册时间排序；匿名访客不列入注册用户。</p><div className={s.tableWrap}><table className={s.table}><thead><tr><th>用户邮箱</th><th>注册时间</th><th>最近登录</th><th>邮箱状态</th><th>订单</th></tr></thead><tbody>{d.users.map(u=><tr key={u.id}><td>{u.email||'未提供邮箱'}<small>{u.id}</small></td><td>{adminDate(u.created_at)}</td><td>{adminDate(u.last_sign_in_at)}</td><td><span className={s.badge}>{u.confirmed?'已验证':'待验证'}</span></td><td><button onClick={()=>{setTab('orders');setDraft(u.id);setSearch(u.id);setProvider('all');setStatus('all');setOrderPage(0)}}>{u.order_count} 笔 · 查看</button></td></tr>)}</tbody></table>{!d.users.length&&<p className={s.empty}>没有匹配的用户</p>}</div><Pager page={userPage} total={d.user_total} loading={loading} onChange={setUserPage}/></>}</>}
 {tab==='visits'&&<><div className={s.hero}><div className={s.heroTop}><h2>网站访问</h2><select aria-label="访问统计时间" value={days} onChange={e=>setDays(e.target.value)}><option value="7">最近 7 天</option><option value="30">最近 30 天</option><option value="90">最近 90 天</option></select></div><div className={s.metrics}><article><p>浏览次数</p><strong>{d.traffic.views}</strong></article><article><p>访问会话</p><strong>{d.traffic.sessions}</strong></article><article><p>今日浏览</p><strong>{d.traffic.today_views}</strong></article></div><p className={s.heroFoot}>{d.traffic.started_at?'开始记录：'+adminDate(d.traffic.started_at):'上线后开始记录，目前暂无访问数据。'} 仅统计公开页面；不记录提示词、账户页面或网址中的查询内容。尊重浏览器隐私设置，访问会话按日分开统计。</p></div>
 <div className={s.sectionTitle}><h2>每日访问趋势</h2><span className={s.subtle}>北京时间</span></div><div className={s.panel}><div className={s.chart} role="img" aria-label={'最近 '+days+' 天浏览次数 '+d.traffic.views}>{d.traffic.daily.map(v=><div key={v.day} className={s.bar} title={v.day+'：'+v.views+' 次浏览，'+v.sessions+' 次会话'}><span style={{height:Math.max(1,v.views/peak*100)+'%'}}/></div>)}</div><div className={s.chartDates}><span>{d.traffic.daily[0]?.day}</span><span>{d.traffic.daily.at(-1)?.day}</span></div></div>
 <div className={s.columns}>{rankings.map(r=><section key={r.title}><div className={s.sectionTitle}><h2>{r.title}</h2></div><div className={s.panel}>{r.rows.map(x=><div key={x.label} className={s.rank}><span>{x.label}</span><b>{x.views}</b></div>)}{!r.rows.length&&<p className={s.empty}>暂无数据</p>}</div></section>)}</div><details><summary className={s.sectionTitle}>查看每日明细</summary><div className={s.tableWrap}><table className={s.table}><thead><tr><th>日期</th><th>浏览次数</th><th>会话</th></tr></thead><tbody>{d.traffic.daily.map(v=><tr key={v.day}><td>{v.day}</td><td>{v.views}</td><td>{v.sessions}</td></tr>)}</tbody></table></div></details></>}
 {tab==='refunds'&&<AdminRefundPanel data={data} busy={busy} operate={operate}/>}</section></>}
 {message&&<p role="status" className={s.notice}>{message}</p>}</main>;
}
