"use client";
import {useCallback,useEffect,useState} from "react";
type Row={id:string;provider:string;currency:string;amount_minor:number;provider_currency:string;provider_amount_minor:number;status:string;failure_code:string|null;submission_confirmed_at:string|null;provider_refund_id:string|null;created_at:string};
type Channel={provider:string;provider_currency:string;active_count:number;pending_minor:number;funds_required_minor:number;awaiting_confirmation:number};
type Data={stats:{channels:Channel[];notices_pending:number};withdrawals:Row[];notices:{id:string;event_type:string;status:string;attempt_count:number;last_error:string|null}[];notifyEmail:string;emailConfigured:boolean};
const provider=(s:string)=>s==='wechat'?'微信支付':s==='alipay'?'支付宝':'PayPal';const amount=(c:string,n:number)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:c}).format(n/100);
function status(w:Row){if(w.status==='cancelled')return '已取消 · 余额已恢复';if(w.status==='completed')return '渠道已确认完成';if(w.failure_code==='PROVIDER_FUNDS_REQUIRED')return '需要补足商户资金';if(['PROVIDER_ACTION_REQUIRED','OPERATOR_REVIEW_REQUIRED'].includes(w.failure_code||''))return '需要人工处理';if(w.status==='requested'&&!w.submission_confirmed_at)return '待用户确认';if(['failed','rejected'].includes(w.status))return '未完成 · 余额已释放';return '正在确认退款结果';}
export default function MoneyAdminDashboard(){const[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[filter,setFilter]=useState('all');
 const load=useCallback(async()=>{try{const r=await fetch('/api/account/money-admin',{cache:'no-store'});if(!r.ok){setData(null);setError(r.status===403?'请使用管理员邮箱登录后查看。':'暂时无法读取资金数据，请稍后刷新。');return}setData(await r.json());setError('')}catch{setError('暂时无法读取，请稍后刷新。')}},[]);
 useEffect(()=>{void load();const t=setInterval(()=>void load(),30000);return()=>clearInterval(t)},[load]);
 async function operate(action:string,id?:string){setBusy(true);setMessage('');try{const r=await fetch('/api/account/money-admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,id})});const b=await r.json();setMessage(!r.ok?'本次操作未完成，请刷新后核对。':action==='send-notices'?(b.configured?'邮件发送请求已处理，请查看下方发送记录。':'邮件服务尚未配置，申请仍保留在通知队列中。'):'已查询原渠道，请查看最新状态。');await load()}catch{setMessage('本次操作未完成，请刷新后核对。')}finally{setBusy(false)}}
 return <main className="mx-auto max-w-6xl px-4 py-12 sm:px-8"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-[var(--lx-muted)]">商户运营</p><h1 className="mt-2 text-3xl font-semibold">资金管理</h1><p className="mt-3 text-sm text-[var(--lx-muted)]">统一查看提现、原路退款和需要你处理的申请。</p></div><button onClick={()=>void load()} className="rounded-xl border border-[var(--lx-line)] px-4 py-2">刷新数据</button></header>
 {error&&<p role="alert" className="mt-6 rounded-2xl border border-[var(--lx-line)] p-5">{error}</p>}
 {data&&<><div className="mt-6 rounded-2xl bg-[var(--lx-soft)] p-4 text-sm">提醒邮箱：{data.notifyEmail} · {data.emailConfigured?'邮件服务已配置':'邮件服务未配置'} · 待发送 {data.stats.notices_pending} 条<button disabled={busy} className="ms-4 underline disabled:opacity-40" onClick={()=>void operate('send-notices')}>重试发送提醒</button></div>
 <section className="mt-6 grid gap-4 md:grid-cols-3">{['wechat','alipay','paypal'].map(p=>{const c=data.stats.channels.find(x=>x.provider===p),currency=c?.provider_currency||(p==='paypal'?'USD':'CNY');return <article key={p} className="rounded-3xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-6"><h2 className="font-semibold">{provider(p)} · {currency}</h2><p className="mt-5 text-xs text-[var(--lx-muted)]">需要补资金的退款金额</p><strong className="mt-2 block text-3xl">{amount(currency,c?.funds_required_minor||0)}</strong><p className="mt-4 text-sm text-[var(--lx-muted)]">已确认待处理 {c?.active_count||0} 笔 · {amount(currency,c?.pending_minor||0)}</p><p className="mt-2 text-xs text-[var(--lx-faint)]">待用户确认 {c?.awaiting_confirmation||0} 笔</p></article>})}</section>
 <section className="mt-10"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">申请记录</h2><select aria-label="支付渠道" value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] px-3 py-2"><option value="all">所有渠道</option><option value="wechat">微信支付</option><option value="alipay">支付宝</option><option value="paypal">PayPal</option></select></div><div className="mt-4 space-y-3">{data.withdrawals.filter(w=>filter==='all'||w.provider===filter).map(w=><article key={w.id} className="rounded-2xl border border-[var(--lx-line)] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><b>{provider(w.provider)} · {amount(w.provider_currency,w.provider_amount_minor)}</b><span className="text-sm">{status(w)}</span></div><p className="mt-3 break-all text-xs text-[var(--lx-faint)]">申请编号：{w.id}</p>{w.currency!==w.provider_currency&&<p className="mt-2 text-xs">对应用户余额：{amount(w.currency,w.amount_minor)}</p>}{w.failure_code==='PROVIDER_FUNDS_REQUIRED'&&<p className="mt-3 text-sm">请先补足对应商户账户的退款资金，再继续原单处理。</p>}{w.submission_confirmed_at&&['requested','processing'].includes(w.status)&&<button disabled={busy} onClick={()=>void operate('retry',w.id)} className="mt-4 rounded-xl border border-[var(--lx-line)] px-4 py-2 disabled:opacity-40">查询并继续原单</button>}</article>)}{!data.withdrawals.length&&<p className="py-8 text-[var(--lx-muted)]">暂无申请。</p>}</div></section>
 <section className="mt-10"><h2 className="text-xl font-semibold">邮件提醒记录</h2><p className="mt-2 text-sm text-[var(--lx-muted)]">已发送表示邮件服务已受理；邮箱实际收件情况仍以收件箱为准。</p><div className="mt-4 space-y-2">{data.notices.map(n=><div key={n.id} className="flex flex-wrap justify-between gap-3 rounded-xl border border-[var(--lx-line)] px-4 py-3 text-sm"><span>{n.status==='sent'?'已发送':n.status==='failed'?'发送未完成，将重试':n.status==='sending'?'发送中':'等待发送'}</span><span>本轮尝试 {n.attempt_count} 次</span></div>)}{!data.notices.length&&<p className="py-4 text-[var(--lx-muted)]">暂无提醒记录。</p>}</div></section></>}{message&&<p role="status" className="mt-6 rounded-xl border border-[var(--lx-line)] p-4">{message}</p>}</main>;
}
