"use client";
import Link from"next/link";import{useEffect,useMemo,useRef,useState}from"react";import{useLingxiLang}from"@/lib/lingxi-i18n";import{accountText}from"@/lib/account-experience-i18n";import LingxiMiniIcon from"@/components/LingxiMiniIcon";
import {moneyText} from "@/lib/notifications/money-copy";
type Item={read?:boolean;eventKey?:string;id:string;kind:"announcement"|"payment"|"refund"|"withdrawal";createdAt:string;href?:string|null;amountRmb?:number|null;status?:string|null;version?:string;title?:string;body?:string};
export default function NotificationBell(){const{lang}=useLingxiLang();const t=(k:string,v?:Record<string,string|number>)=>accountText(lang,k,v);const[open,setOpen]=useState(false),[items,setItems]=useState<Item[]>([]),[seenAt,setSeenAt]=useState("");const ref=useRef<HTMLDivElement|null>(null);
async function load(){try{const r=await fetch(`/api/notifications?lang=${lang}`,{cache:"no-store"});if(r.ok){const d=await r.json();setItems(Array.isArray(d.items)?d.items:[])}}catch{}}
useEffect(()=>{setSeenAt(localStorage.getItem("lx-notifications-seen-at")||"");void load();const id=setInterval(load,60000);window.addEventListener('lingxi-money-updated',load);return()=>{clearInterval(id);window.removeEventListener('lingxi-money-updated',load)}},[lang]);
useEffect(()=>{const h=(e:MouseEvent)=>{if(open&&ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",h);return()=>document.removeEventListener("mousedown",h)},[open]);
const unread=useMemo(()=>items.filter(i=>i.read===false || (i.read==null&&(!seenAt||new Date(i.createdAt).getTime()>new Date(seenAt).getTime()))).length,[items,seenAt]);
function toggle(){const next=!open;setOpen(next);if(next){void fetch("/api/account/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventKeys:items.map(x=>x.eventKey||x.id)})}).then(r=>{if(r.ok)setItems(xs=>xs.map(x=>({...x,read:true})))}).catch(()=>{});const now=new Date().toISOString();localStorage.setItem("lx-notifications-seen-at",now);setSeenAt(now)}}
function copyFor(i:Item){return {title:i.title||t("notifications"),body:i.body||""}}
return <div className="lx11-notification-wrap" ref={ref}><button className="lx11-icon-btn lx11-bell" aria-label={t("notifications")} aria-expanded={open} onClick={toggle}><LingxiMiniIcon name="sparkles" size="tiny"/>{unread>0&&<span className="lx11-notification-count">{unread>9?"9+":unread}</span>}</button>{open&&<div className="lx11-notification-panel lx-notification-v201"><header><b>{t("notifications")}</b>{unread>0&&<span>{unread}</span>}</header>{items.length===0?<p className="lx11-notification-empty"><span aria-hidden="true">✓</span>{t("allCaughtUp")}</p>:<div className="lx11-notification-list">{items.slice(0,12).map(i=>{const c=copyFor(i);const body=<><strong>{c.title}</strong><p>{c.body}</p><small>{new Date(i.createdAt).toLocaleString(lang==="zh"?"zh-CN":lang)}</small></>;return i.href?<Link key={i.id} href={i.href} onClick={()=>setOpen(false)}>{body}</Link>:<article key={i.id}>{body}</article>})}</div>}<footer style={{padding:"10px 14px",borderTop:"1px solid rgba(0,0,0,.06)"}}><Link href="/account/notifications" onClick={()=>setOpen(false)} style={{fontSize:12}}>{moneyText(lang,"all")} →</Link></footer></div>}</div>}
