"use client";
import {createContext,useContext,type ReactNode} from 'react';
import {useLingxiLang,type LingxiLang} from '@/lib/lingxi-i18n';
import type {SasiEntryMode} from './SasiUnifiedLauncher';
type Row=Record<LingxiLang,string>;
const L=(zh:string,en:string,ja:string,ko:string,fr:string,de:string,es:string,pt:string,ar:string):Row=>({zh,en,ja,ko,fr,de,es,pt,ar});
const LABELS={chat:L('对话','Chat','対話','대화','Discussion','Chat','Conversar','Conversar','محادثة'),image:L('生成图片','Create image','画像生成','이미지 생성','Image','Bild erstellen','Crear imagen','Criar imagem','إنشاء صورة'),drama:L('生成视频','Create video','動画生成','동영상 생성','Vidéo','Video erstellen','Crear vídeo','Criar vídeo','إنشاء فيديو'),website:L('做网站','Build a website','サイト作成','웹사이트 만들기','Créer un site','Website erstellen','Crear un sitio','Criar um site','إنشاء موقع'),research:L('深度研究','Deep research','深い調査','심층 연구','Recherche approfondie','Tiefenrecherche','Investigación profunda','Pesquisa aprofundada','بحث متعمق'),book:L('读书与资料','Read sources','本と資料','책과 자료','Lire des sources','Quellen lesen','Leer fuentes','Ler fontes','قراءة المصادر'),learning:L('学习','Study','学習','학습','Étudier','Lernen','Estudiar','Estudar','التعلم')};
const HEADING=L('今天想做什么？','What would you like to do?','今日は何をしますか？','오늘 무엇을 하고 싶으세요?','Que souhaitez-vous faire ?','Was möchtest du machen?','¿Qué quieres hacer?','O que você quer fazer?','ماذا تريد أن تفعل؟');
const Context=createContext<{current:SasiEntryMode|null;select:(mode:SasiEntryMode)=>void}|null>(null);
export function SasiTaskNavigation({current,onSelect,children}:{current:SasiEntryMode|null;onSelect:(mode:SasiEntryMode)=>void;children:ReactNode}){return <Context.Provider value={{current,select:onSelect}}>{children}</Context.Provider>}
export function SasiWelcomeHeading(){const {lang}=useLingxiLang();return <h1 className="mb-7 text-center text-2xl font-semibold sm:text-3xl">{HEADING[lang]}</h1>}
export default function SasiTaskToolbar({current,onSelect,disabled=false}:{current?:SasiEntryMode|null;onSelect?:(mode:SasiEntryMode)=>void;disabled?:boolean}){const context=useContext(Context),{lang}=useLingxiLang(),selected=current===undefined?context?.current:current,choose=onSelect||context?.select;if(!choose)return null;return <div data-sasi-task-toolbar className="flex min-w-0 flex-wrap items-center gap-1.5 border-t border-[var(--lx-line)] pt-3"><div className="flex min-w-0 flex-wrap gap-1.5" role="toolbar" aria-label={HEADING[lang]}>{(Object.keys(LABELS) as SasiEntryMode[]).map(id=><button type="button" key={id} disabled={disabled} aria-pressed={selected===id} onClick={()=>choose(id)} className={'min-h-9 rounded-full px-3 py-1.5 text-xs transition disabled:opacity-40 '+(selected===id?'bg-blue-50 text-blue-700 ring-1 ring-blue-200 dark:bg-blue-950 dark:text-blue-200':'text-[var(--lx-muted)] hover:bg-[var(--lx-soft)]')}>{LABELS[id][lang]}</button>)}</div></div>}
