"use client";
import {useEffect,useMemo,useState} from "react";
type Ratio="1:1"|"16:9"|"9:16";type Style="editorial"|"poster"|"storyboard"|"abstract";
function art(body:any,name:string){return(body?.artifacts||[]).find((x:any)=>x?.name===name)?.value}
function save(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export default function SasiAutonomousImageStudio(){
 const[prompt,setPrompt]=useState("深夜地铁站，一个女孩看见对面站台上另一个自己。"),[ratio,setRatio]=useState<Ratio>("1:1"),[style,setStyle]=useState<Style>("editorial"),[svg,setSvg]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const url=useMemo(()=>svg?URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"})):"",[svg]);useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 async function generate(){if(busy||!prompt.trim())return;setBusy(true);setMessage("正在生成画面…");try{const r=await fetch("/api/sasi/autonomous",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"image",action:"render",input:{prompt,ratio,style}})});const b=await r.json().catch(()=>({}));if(!r.ok||!b.ok)throw new Error(b.error?.message||"这次没有生成完成。");const s=String(art(b,"lingxifield-sasi-image.svg")||"");if(!s.startsWith("<svg"))throw new Error("没有得到可用图片。");setSvg(s);setMessage("图片已经生成。基础生成不需要连接外部模型。")}catch(e){setMessage(e instanceof Error?e.message:"这次没有生成完成。")}finally{setBusy(false)}}
 async function png(){if(!url)return;const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext("2d");if(!ctx)return;ctx.drawImage(img,0,0);c.toBlob(b=>b&&save(b,"lingxifield-sasi-image.png"),"image/png")};img.src=url}
 return <section className="mx-auto max-w-5xl px-5 py-10"><div className="rounded-3xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-6 md:p-8">
  <p className="text-sm font-medium text-[var(--lx-accent)]">SASI · 自主图片</p><h1 className="mt-2 text-3xl font-semibold text-[var(--lx-ink)]">从一句描述，直接生成可以使用的视觉画面。</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--lx-muted)]">基础画面由灵犀场自己的程序生成能力完成，不依赖外部图片生成服务。适合封面、故事卡、概念图和信息视觉。写实人物与电影级新画面属于增强生成。</p>
  <textarea value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={1200} className="mt-7 min-h-40 w-full rounded-2xl border border-[var(--lx-line)] bg-[var(--lx-soft)] p-4 leading-7 text-[var(--lx-ink)] outline-none" placeholder="描述你想看到的画面"/>
  <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm text-[var(--lx-muted)]">画幅<select value={ratio} onChange={e=>setRatio(e.target.value as Ratio)} className="mt-2 block w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3 text-[var(--lx-ink)]"><option>1:1</option><option>16:9</option><option>9:16</option></select></label><label className="text-sm text-[var(--lx-muted)]">呈现方式<select value={style} onChange={e=>setStyle(e.target.value as Style)} className="mt-2 block w-full rounded-xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-3 text-[var(--lx-ink)]"><option value="editorial">信息视觉</option><option value="poster">海报</option><option value="storyboard">故事板</option><option value="abstract">抽象画面</option></select></label></div>
  <button onClick={()=>void generate()} disabled={busy||!prompt.trim()} className="mt-5 rounded-full bg-[var(--lx-ink)] px-6 py-3 text-sm font-medium text-[var(--lx-bg)] disabled:opacity-40">{busy?"正在生成…":"生成图片"}</button>{message&&<p className="mt-4 text-sm text-[var(--lx-muted)]">{message}</p>}
  {url&&<div className="mt-7"><img src={url} alt="SASI 生成结果" className="max-h-[72vh] w-full rounded-2xl bg-black object-contain"/><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>save(new Blob([svg],{type:"image/svg+xml"}),"lingxifield-sasi-image.svg")} className="rounded-full border border-[var(--lx-line)] px-4 py-2 text-sm">保存 SVG</button><button onClick={()=>void png()} className="rounded-full border border-[var(--lx-line)] px-4 py-2 text-sm">保存 PNG</button></div></div>}
 </div></section>
}
