"use client";
import {type FormEvent,useState} from "react";
import Link from "next/link";
import {useLingxiLang} from "@/lib/lingxi-i18n";
import LingxiMiniIcon,{type LingxiIconName} from "@/components/LingxiMiniIcon";
type Mode="drama"|"knowledge"|"research";
const cards=[
 {href:"/sasi/drama",zh:"AI短剧生成",en:"AI Drama",noteZh:"把故事、人物和素材继续推进到镜头与成片。",noteEn:"Move stories, characters and assets toward shots and delivery.",mark:"drama" as LingxiIconName},
 {href:"/ai-knowledge",zh:"书本 / 资料智能体",en:"Book & Document Agent",noteZh:"让书本、论文和资料变成可以持续追问、引用和回看的智能体。",noteEn:"Turn books, papers and files into an intelligence you can keep questioning.",mark:"book" as LingxiIconName},
 {href:"/ai-research",zh:"科研 SASI",en:"Research SASI",noteZh:"让问题、证据、比较与结论留在同一条研究脉络里。",noteEn:"Keep questions, evidence, comparison and conclusions in one research thread.",mark:"research" as LingxiIconName},
 {href:"/sasi/connections",zh:"模型与 API",en:"Models & APIs",noteZh:"把你已经在用的 AI 接进来，创作时不必来回切换。",noteEn:"Connect the AI services you already use and keep creation in one place.",mark:"connections" as LingxiIconName},
 {href:"/sasi/pricing",zh:"创作余额",en:"Creation Balance",noteZh:"按你习惯的币种充值，使用时再从对应余额结算。",noteEn:"Top up in your preferred currency and use the matching balance when creating.",mark:"wallet" as LingxiIconName},
] as const;
export default function SasiCommandCenter(){
 const{lang}=useLingxiLang(),zh=lang==="zh";const[mode,setMode]=useState<Mode>("drama"),[prompt,setPrompt]=useState("");
 function submit(e:FormEvent){e.preventDefault();const value=prompt.trim();if(value)sessionStorage.setItem("sasi-intent",value);location.assign(mode==="drama"?"/sasi/drama":mode==="knowledge"?"/ai-knowledge":"/ai-research")}
 return <main className="lx11-page lx-sasi-center"><div className="mx-auto max-w-6xl px-6 py-14 sm:py-20">
  <section className="max-w-3xl lx-sasi-hero"><div className="lx-sasi-hero-line"><LingxiMiniIcon name="sasi" size="title"/><p className="text-sm font-medium text-[var(--lx-faint)]">SASI · {zh?"AI 创作入口":"AI Creation"}</p></div><h1 className="mt-3 text-3xl font-semibold leading-tight text-[var(--lx-ink)] sm:text-4xl">{zh?"把一个还没成形的念头，继续推到真正发生。":"Move an unfinished idea toward something real."}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[var(--lx-muted)]">{zh?"先告诉 SASI 你现在想完成什么。灵犀场会沿着这个目标接住你的故事、资料和上下文，把下一步送到你面前。":"Tell SASI what you want to finish. LINGXIFIELD carries your story, sources and context forward and brings the next useful step to you."}</p></section>
  <section className="mt-10 rounded-3xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-5 sm:p-7 lx-sasi-prompt-panel"><form onSubmit={submit}><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={5} placeholder={zh?"例如：把这份小说做成 20 集竖屏短剧；或把这篇论文变成可以持续追问的研究智能体。":"Example: turn this novel into a 20-episode vertical drama, or this paper into a research agent."} className="w-full resize-none bg-transparent text-sm leading-7 text-[var(--lx-ink)] outline-none placeholder:text-[var(--lx-faint)]"/><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--lx-line)] pt-5"><div className="flex flex-wrap gap-2">{([["drama",zh?"AI短剧":"AI Drama"],["knowledge",zh?"资料智能体":"Document Agent"],["research",zh?"科研":"Research"]] as const).map(([id,label])=><button type="button" key={id} onClick={()=>setMode(id)} className={`rounded-full border px-4 py-2 text-sm ${mode===id?"border-[var(--lx-line-strong)] bg-[var(--lx-soft)] text-[var(--lx-ink)]":"border-[var(--lx-line)] text-[var(--lx-muted)]"}`}>{label}</button>)}</div><button className="rounded-xl bg-[var(--lx-ink)] px-5 py-3 text-sm font-semibold text-[var(--lx-bg)]">{zh?"让它开始 →":"Begin →"}</button></div></form></section>
  <section className="mt-12"><p className="text-sm text-[var(--lx-faint)]">{zh?"继续往哪里走":"Where to go next"}</p><h2 className="mt-2 text-2xl font-semibold text-[var(--lx-ink)]">{zh?"从你现在要解决的事进入。":"Enter from the work you need done now."}</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map(card=><Link key={card.href} href={card.href} className="group rounded-2xl border border-[var(--lx-line)] bg-[var(--lx-panel)] p-5 transition hover:border-[var(--lx-line-strong)] lx-sasi-entry-card"><div className="flex items-center justify-between"><LingxiMiniIcon name={card.mark} size="card"/><span className="text-sm text-[var(--lx-faint)]">→</span></div><h3 className="mt-5 text-base font-semibold text-[var(--lx-ink)]">{zh?card.zh:card.en}</h3><p className="mt-2 text-sm leading-6 text-[var(--lx-muted)]">{zh?card.noteZh:card.noteEn}</p></Link>)}</div></section>
 </div></main>
}
