import http from "node:http";import{createHmac,timingSafeEqual,randomUUID}from"node:crypto";
const PORT=Number(process.env.PORT||process.env.SASI_COMPUTE_PORT||8788),HOST=process.env.SASI_COMPUTE_HOST||"127.0.0.1",SECRET=(process.env.SASI_COMPUTE_WORKER_SECRET||"").trim(),PROTOCOL="1.0",MAX_BODY=2*1024*1024,MAX_SKEW=5*60_000,nonceCache=new Map();
if(SECRET.length<32)throw new Error("SASI_COMPUTE_WORKER_SECRET must be at least 32 characters");
function json(res,status,body){const data=JSON.stringify(body);res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","content-length":Buffer.byteLength(data)});res.end(data)}
function prune(now){for(const[n,t]of nonceCache)if(now-t>MAX_SKEW)nonceCache.delete(n);}
function verify(body,headers){const timestamp=String(headers["x-sasi-timestamp"]||""),nonce=String(headers["x-sasi-nonce"]||""),signature=String(headers["x-sasi-signature"]||""),now=Date.now(),ts=Number(timestamp);prune(now);if(!Number.isFinite(ts)||Math.abs(now-ts)>MAX_SKEW)return{ok:false,code:"CLOCK_SKEW"};if(!/^[0-9a-f-]{36}$/i.test(nonce)||nonceCache.has(nonce))return{ok:false,code:"REPLAY_REJECTED"};if(!/^[0-9a-f]{64}$/i.test(signature))return{ok:false,code:"SIGNATURE_INVALID"};const expected=createHmac("sha256",SECRET).update(`${timestamp}.${nonce}.${body}`).digest("hex"),a=Buffer.from(expected,"hex"),b=Buffer.from(signature,"hex");if(a.length!==b.length||!timingSafeEqual(a,b))return{ok:false,code:"SIGNATURE_INVALID"};nonceCache.set(nonce,now);return{ok:true};}
async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>MAX_BODY)throw new Error("BODY_TOO_LARGE");chunks.push(chunk)}return Buffer.concat(chunks).toString("utf8")}
function capabilities(){return[{id:"worker.echo",version:"1.0.0",runtime:"cpu",ready:true},{id:"image.generate.diffusion",version:"1.0.0",runtime:"gpu",ready:false,reason:"MODEL_NOT_CONFIGURED"},{id:"video.generate.model",version:"1.0.0",runtime:"gpu",ready:false,reason:"MODEL_NOT_CONFIGURED"}]}
const server=http.createServer(async(req,res)=>{try{if(req.method==="GET"&&req.url==="/health")return json(res,200,{ok:true,status:"ready",protocolVersion:PROTOCOL,workerId:process.env.SASI_WORKER_ID||"local",pid:process.pid,uptimeSec:Math.floor(process.uptime()),capabilities:capabilities().filter(x=>x.ready).length});if(req.method==="GET"&&req.url==="/capabilities")return json(res,200,{protocolVersion:PROTOCOL,capabilities:capabilities()});if(req.method==="POST"&&req.url==="/v1/tasks"){const raw=await body(req),auth=verify(raw,req.headers);if(!auth.ok)return json(res,401,{error:auth.code});let input;try{input=JSON.parse(raw)}catch{return json(res,400,{error:"INVALID_JSON"})}if(input?.protocolVersion!==PROTOCOL||typeof input?.requestId!=="string"||typeof input?.taskId!=="string"||typeof input?.nodeId!=="string"||typeof input?.capabilityId!=="string")return json(res,400,{error:"INVALID_TASK"});if(input.capabilityId!=="worker.echo")return json(res,409,{protocolVersion:PROTOCOL,requestId:input.requestId,taskId:input.taskId,nodeId:input.nodeId,status:"failed",artifacts:[],error:{code:"CAPABILITY_NOT_READY",message:"This compute capability is not configured on this worker."}});return json(res,200,{protocolVersion:PROTOCOL,requestId:input.requestId,taskId:input.taskId,nodeId:input.nodeId,status:"succeeded",artifacts:[{type:"json",name:"worker-echo.json",metadata:{workerRunId:randomUUID(),input:input.input}}],model:null,timings:{totalMs:0}})}return json(res,404,{error:"NOT_FOUND"})}catch(error){return json(res,500,{error:error instanceof Error?error.message:"WORKER_ERROR"})}});
server.listen(PORT,HOST,()=>console.log(`SASI_COMPUTE_WORKER_READY=http://${HOST}:${PORT}`));
