import type { LingxiLang } from "@/lib/lingxi-i18n";
import { NATIVE_V104K } from "@/lib/bi-native-v104k";
import { NATIVE_V104L } from "@/lib/bi-native-v104l";
import { NATIVE_V104M } from "@/lib/bi-native-v104m";
import { NATIVE_V104Q } from "@/lib/bi-native-v104q";
import { NATIVE_V104R } from "@/lib/bi-native-v104r";
import { NATIVE_V104T1 } from "@/lib/bi-native-v104t1";

type NativeRow = Partial<Record<LingxiLang,string>>;

const NATIVE:Record<string,NativeRow>={
  "你已连接至场域":{"ja": "フィールドに接続されています", "ko": "필드에 연결되어 있습니다", "fr": "Vous êtes connecté au champ", "de": "Sie sind mit dem Feld verbunden", "es": "Estás conectado al campo", "pt": "Você está conectado ao campo", "ar": "أنت متصل بالمجال"},
  "欢迎回来":{"ja": "おかえりなさい", "ko": "다시 오신 것을 환영합니다", "fr": "Bon retour", "de": "Willkommen zurück", "es": "Bienvenido de nuevo", "pt": "Bem-vindo de volta", "ar": "مرحبًا بعودتك"},
  "在这里回看自己的探索、练习与订单，让每一次理解都有可以继续的地方。":{"ja": "ここで探索・実践・注文を振り返り、得た理解の続きをいつでも始められます。", "ko": "여기에서 탐색, 수련, 주문을 돌아보고 배운 내용을 이어가세요.", "fr": "Retrouvez ici vos explorations, pratiques et commandes, et reprenez là où vous en étiez.", "de": "Sehen Sie hier Ihre Erkundungen, Übungen und Bestellungen wieder und machen Sie dort weiter, wo Sie aufgehört haben.", "es": "Revisa aquí tus exploraciones, prácticas y pedidos y continúa desde lo aprendido.", "pt": "Reveja aqui suas explorações, práticas e pedidos e continue a partir do que aprendeu.", "ar": "راجع هنا استكشافاتك وممارساتك وطلباتك وتابع من حيث وصلت."},
  "我的现实回路":{"ja": "私のリアリティ・ループ", "ko": "나의 현실 루프", "fr": "Ma boucle de réalité", "de": "Meine Realitätsschleife", "es": "Mi bucle de realidad", "pt": "Meu ciclo de realidade", "ar": "حلقة واقعي"},
  "回到意图、行动与复盘":{"ja": "意図・行動・振り返りへ戻る", "ko": "의도·행동·복기로 돌아가기", "fr": "Revenir aux intentions, actions et bilans", "de": "Zu Absichten, Handlungen und Reflexion zurückkehren", "es": "Volver a intención, acción y revisión", "pt": "Voltar à intenção, ação e revisão", "ar": "العودة إلى النية والفعل والمراجعة"},
  "我的完整档案":{"ja": "私の完全アーカイブ", "ko": "나의 전체 아카이브", "fr": "Mes archives complètes", "de": "Mein vollständiges Archiv", "es": "Mis archivos completos", "pt": "Meus arquivos completos", "ar": "أرشيفي الكامل"},
  "阅读报告，下载与回看":{"ja": "レポートを読み、ダウンロードして振り返る", "ko": "보고서를 읽고 다운로드해 다시 보기", "fr": "Lire, télécharger et revoir les rapports", "de": "Berichte lesen, herunterladen und erneut ansehen", "es": "Leer, descargar y revisar informes", "pt": "Ler, baixar e rever relatórios", "ar": "اقرأ التقارير ونزّلها وراجعها"},
  "我的修炼记录":{"ja": "私の実践記録", "ko": "나의 수련 기록", "fr": "Mon journal de pratique", "de": "Mein Übungsjournal", "es": "Mi diario de práctica", "pt": "Meu diário de prática", "ar": "سجل ممارستي"},
  "持续练习，记录真实感受":{"ja": "実践を続け、実感を記録する", "ko": "계속 수련하고 실제 감각을 기록하세요", "fr": "Continuer à pratiquer et noter le vécu réel", "de": "Weiter üben und echte Erfahrungen festhalten", "es": "Seguir practicando y registrar lo vivido", "pt": "Continuar praticando e registrar a experiência real", "ar": "واصل الممارسة وسجّل تجربتك الحقيقية"},
  "意识显化":{"ja": "意識の具現化", "ko": "의식 구현", "fr": "Manifestation", "de": "Manifestation", "es": "Manifestación", "pt": "Manifestação", "ar": "التجسيد"},
  "有效至 ":{"ja": "有効期限：", "ko": "유효 기간: ", "fr": "Actif jusqu’au ", "de": "Aktiv bis ", "es": "Activo hasta ", "pt": "Ativo até ", "ar": "ساري حتى "},
  "未订阅":{"ja": "未登録", "ko": "구독 안 함", "fr": "Non souscrit", "de": "Nicht abonniert", "es": "Sin suscripción", "pt": "Não assinado", "ar": "غير مشترك"},
  "修炼技术":{"ja": "実践", "ko": "수련 기술", "fr": "Pratiques", "de": "Praxis", "es": "Prácticas", "pt": "Práticas", "ar": "الممارسات"},
  "四项完整引导，免费开放 →":{"ja": "4つの完全ガイドを無料公開 →", "ko": "4가지 전체 가이드 무료 공개 →", "fr": "Quatre pratiques complètes, gratuites →", "de": "Vier vollständige Übungen, kostenlos →", "es": "Cuatro prácticas completas, gratis →", "pt": "Quatro práticas completas, grátis →", "ar": "أربع ممارسات كاملة ومجانية →"},
  "查看场域订单（订单号 · 金额 · 状态 · 有效期）→":{"ja": "フィールド注文を見る（番号・金額・状態・有効期限）→", "ko": "필드 주문 보기 (번호 · 금액 · 상태 · 유효기간) →", "fr": "Voir les commandes (n° · montant · statut · validité) →", "de": "Bestellungen ansehen (Nr. · Betrag · Status · Gültigkeit) →", "es": "Ver pedidos (n.º · importe · estado · validez) →", "pt": "Ver pedidos (nº · valor · status · validade) →", "ar": "عرض الطلبات (الرقم · المبلغ · الحالة · الصلاحية) →"},
  "进入灵犀场 SASI 工作台":{"ja": "LINGXIFIELD SASI スタジオへ", "ko": "LINGXIFIELD SASI 스튜디오로", "fr": "Entrer dans le studio LINGXIFIELD SASI", "de": "LINGXIFIELD SASI Studio öffnen", "es": "Entrar en LINGXIFIELD SASI", "pt": "Entrar no LINGXIFIELD SASI", "ar": "الدخول إلى استوديو LINGXIFIELD SASI"},
  "进入我的现实回路":{"ja": "私のリアリティ・ループへ", "ko": "나의 현실 루프로", "fr": "Entrer dans ma boucle de réalité", "de": "Meine Realitätsschleife öffnen", "es": "Entrar en mi bucle de realidad", "pt": "Entrar no meu ciclo de realidade", "ar": "الدخول إلى حلقة واقعي"},
  "购买 / 续期":{"ja": "購入 / 更新", "ko": "구매 / 갱신", "fr": "Acheter / Renouveler", "de": "Kaufen / Verlängern", "es": "Comprar / Renovar", "pt": "Comprar / Renovar", "ar": "شراء / تجديد"},
  "进入场域":{"ja": "フィールドへ", "ko": "필드 입장", "fr": "Entrer dans le champ", "de": "Das Feld betreten", "es": "Entrar en el campo", "pt": "Entrar no campo", "ar": "الدخول إلى المجال"},
  "连接到你的意识场":{"ja": "あなたの意識フィールドにつながる", "ko": "당신의 의식 필드에 연결하세요", "fr": "Connectez-vous à votre champ de conscience", "de": "Mit Ihrem Bewusstseinsfeld verbinden", "es": "Conecta con tu campo de conciencia", "pt": "Conecte-se ao seu campo de consciência", "ar": "اتصل بمجال وعيك"},
  "用邮箱和密码登录或注册。验证后，你的现实回路、练习记录与显化轨迹，将在云端安全同步。":{"ja": "メールとパスワードでログインまたは登録してください。認証後、リアリティ・ループ、実践記録、具現化の軌跡がクラウドで安全に同期されます。", "ko": "이메일과 비밀번호로 로그인하거나 가입하세요. 인증 후 현실 루프, 수련 기록, 구현 기록이 클라우드에 안전하게 동기화됩니다.", "fr": "Connectez-vous ou inscrivez-vous avec votre e-mail et votre mot de passe. Après vérification, votre boucle de réalité, vos pratiques et votre parcours de manifestation seront synchronisés de façon sécurisée dans le cloud.", "de": "Melden Sie sich mit E-Mail und Passwort an oder registrieren Sie sich. Nach der Bestätigung werden Realitätsschleife, Übungen und Manifestationsverlauf sicher in der Cloud synchronisiert.", "es": "Inicia sesión o regístrate con correo y contraseña. Tras la verificación, tu bucle de realidad, prácticas y recorrido de manifestación se sincronizarán de forma segura en la nube.", "pt": "Entre ou cadastre-se com e-mail e senha. Após a verificação, seu ciclo de realidade, práticas e trajetória de manifestação serão sincronizados com segurança na nuvem.", "ar": "سجّل الدخول أو أنشئ حسابًا بالبريد وكلمة المرور. بعد التحقق ستتم مزامنة حلقة الواقع وسجل الممارسة ومسار التجسيد بأمان في السحابة."},
  "找不到这个产品，请返回重试。":{"ja": "この商品が見つかりません。戻ってもう一度お試しください。", "ko": "상품을 찾을 수 없습니다. 돌아가서 다시 시도하세요.", "fr": "Produit introuvable. Revenez en arrière et réessayez.", "de": "Produkt nicht gefunden. Bitte zurückgehen und erneut versuchen.", "es": "No se encontró este producto. Vuelve e inténtalo de nuevo.", "pt": "Produto não encontrado. Volte e tente novamente.", "ar": "تعذر العثور على هذا المنتج. ارجع وحاول مرة أخرى."},
  "← 返回场域订单":{"ja": "← フィールド注文へ戻る", "ko": "← 필드 주문으로", "fr": "← Retour aux commandes", "de": "← Zurück zu den Bestellungen", "es": "← Volver a pedidos", "pt": "← Voltar aos pedidos", "ar": "← العودة إلى الطلبات"},
  "数字服务订单":{"ja": "デジタルサービス注文", "ko": "디지털 서비스 주문", "fr": "Commande de service numérique", "de": "Bestellung digitaler Dienstleistung", "es": "Pedido de servicio digital", "pt": "Pedido de serviço digital", "ar": "طلب خدمة رقمية"},
  "请确认软件服务、交付内容与金额，无误后再提交支付":{"ja": "ソフトウェアサービス、納品内容、金額を確認してから支払いを送信してください。", "ko": "소프트웨어 서비스, 제공 내용, 금액을 확인한 후 결제하세요.", "fr": "Vérifiez le service logiciel, le contenu livré et le montant avant de payer.", "de": "Prüfen Sie Softwaredienst, Lieferumfang und Betrag vor der Zahlung.", "es": "Confirma el servicio, la entrega y el importe antes de pagar.", "pt": "Confirme o serviço, a entrega e o valor antes de pagar.", "ar": "تحقق من الخدمة الرقمية ومحتوى التسليم والمبلغ قبل الدفع."},
  "正在确认访问权限……":{"ja": "アクセス権を確認しています…", "ko": "접근 권한 확인 중…", "fr": "Vérification de votre accès…", "de": "Zugriff wird geprüft…", "es": "Comprobando tu acceso…", "pt": "Verificando seu acesso…", "ar": "جارٍ التحقق من صلاحية الوصول…"},
  "数字服务订单号":{"ja": "デジタルサービス注文番号", "ko": "디지털 서비스 주문 번호", "fr": "N° de commande numérique", "de": "Nr. der digitalen Bestellung", "es": "N.º de pedido digital", "pt": "Nº do pedido digital", "ar": "رقم طلب الخدمة الرقمية"},
  "待支付":{"ja": "支払い待ち", "ko": "결제 대기", "fr": "En attente de paiement", "de": "Zahlung ausstehend", "es": "Pendiente de pago", "pt": "Aguardando pagamento", "ar": "بانتظار الدفع"},
  "对应内容":{"ja": "対象コンテンツ", "ko": "연결된 콘텐츠", "fr": "Contenu associé", "de": "Zugeordneter Inhalt", "es": "Contenido vinculado", "pt": "Conteúdo vinculado", "ar": "المحتوى المرتبط"},
  "永久有效，不设到期时间":{"ja": "永久アクセス・期限なし", "ko": "영구 이용 · 만료 없음", "fr": "Accès permanent, sans expiration", "de": "Dauerhafter Zugriff, kein Ablauf", "es": "Acceso permanente, sin caducidad", "pt": "Acesso permanente, sem validade", "ar": "وصول دائم بلا انتهاء"},
  "本次数字服务包含":{"ja": "このデジタルサービスに含まれるもの", "ko": "이번 디지털 서비스 포함 항목", "fr": "Ce service numérique comprend", "de": "Dieser digitale Dienst umfasst", "es": "Este servicio digital incluye", "pt": "Este serviço digital inclui", "ar": "تشمل هذه الخدمة الرقمية"},
  "连接账号":{"ja": "接続アカウント", "ko": "연결 계정", "fr": "Compte connecté", "de": "Verbundenes Konto", "es": "Cuenta conectada", "pt": "Conta conectada", "ar": "الحساب المتصل"},
  "应付总额":{"ja": "支払総額", "ko": "총 결제 금액", "fr": "Total à payer", "de": "Gesamtbetrag", "es": "Total a pagar", "pt": "Total a pagar", "ar": "الإجمالي المستحق"},
  "建议在手机浏览器打开本页并使用支付宝，跳转与回到报告的体验更顺畅；电脑端也可继续使用支付宝网页收银台。":{"ja": "モバイルブラウザでこのページを開き Alipay を使うと、決済とレポートへの復帰がよりスムーズです。PCでも Alipay のウェブ決済を利用できます。", "ko": "모바일 브라우저에서 이 페이지를 열고 Alipay를 사용하면 결제 후 보고서로 돌아오는 흐름이 더 자연스럽습니다. PC에서도 Alipay 웹 결제를 사용할 수 있습니다.", "fr": "Pour une redirection plus fluide, ouvrez cette page sur mobile et utilisez Alipay. Le paiement Alipay sur ordinateur reste disponible.", "de": "Für einen reibungslosen Ablauf öffnen Sie diese Seite am besten mobil und nutzen Alipay. Desktop-Checkout bleibt verfügbar.", "es": "Para una experiencia más fluida, abre esta página en el móvil y usa Alipay. El pago web en ordenador también sigue disponible.", "pt": "Para uma experiência mais fluida, abra esta página no celular e use Alipay. O checkout web no computador continua disponível.", "ar": "لتجربة أكثر سلاسة افتح الصفحة على الهاتف واستخدم Alipay. يظل الدفع عبر الويب على الكمبيوتر متاحًا."},
  "支付方式":{"ja": "支払い方法", "ko": "결제 방법", "fr": "Mode de paiement", "de": "Zahlungsart", "es": "Método de pago", "pt": "Forma de pagamento", "ar": "طريقة الدفع"},
  "正在唤起微信支付……如果没有自动弹出，请稍等或返回重试":{"ja": "WeChat Pay を開いています… 自動で表示されない場合は少し待つか、戻って再試行してください。", "ko": "WeChat Pay 여는 중… 자동으로 뜨지 않으면 잠시 기다리거나 돌아가 다시 시도하세요.", "fr": "Ouverture de WeChat Pay… si rien ne s’affiche, patientez ou revenez en arrière pour réessayer.", "de": "WeChat Pay wird geöffnet… falls nichts erscheint, kurz warten oder zurückgehen und erneut versuchen.", "es": "Abriendo WeChat Pay… si no aparece, espera un momento o vuelve e inténtalo de nuevo.", "pt": "Abrindo o WeChat Pay… se nada aparecer, aguarde ou volte e tente novamente.", "ar": "جارٍ فتح WeChat Pay… إذا لم يظهر تلقائيًا فانتظر قليلًا أو ارجع وحاول مجددًا."},
  "正在查询…":{"ja": "確認中…", "ko": "조회 중…", "fr": "Vérification…", "de": "Prüfung…", "es": "Comprobando…", "pt": "Verificando…", "ar": "جارٍ التحقق…"},
  "我已完成支付，帮我确认一下 →":{"ja": "支払い済みです。確認してください →", "ko": "결제를 완료했습니다. 확인해 주세요 →", "fr": "J’ai payé — vérifier maintenant →", "de": "Ich habe bezahlt — jetzt prüfen →", "es": "Ya he pagado — comprobar ahora →", "pt": "Já paguei — verificar agora →", "ar": "لقد دفعت — تحقّق الآن →"},
  "打开微信 · 扫一扫，完成支付后页面会自动跳转":{"ja": "WeChat を開いてスキャンしてください。支払い完了後、自動的に移動します。", "ko": "WeChat을 열고 스캔하세요. 결제 후 페이지가 자동으로 이동합니다.", "fr": "Ouvrez WeChat et scannez. La page changera automatiquement après le paiement.", "de": "WeChat öffnen und scannen. Nach der Zahlung wird automatisch weitergeleitet.", "es": "Abre WeChat y escanea. La página avanzará automáticamente tras el pago.", "pt": "Abra o WeChat e escaneie. A página avançará automaticamente após o pagamento.", "ar": "افتح WeChat وامسح الرمز، وستنتقل الصفحة تلقائيًا بعد الدفع."},
  "出于支付安全考虑，微信不支持保存二维码到相册后再扫描付款——如果当前设备不方便直接扫码，可以换一台手机、用它的微信直接扫这张二维码":{"ja": "安全上の理由から、WeChat は保存したQR画像からの支払いに対応していません。現在の端末で直接スキャンしづらい場合は、別のスマートフォンの WeChat でこのコードを直接スキャンしてください。", "ko": "결제 보안을 위해 WeChat은 저장한 QR 이미지를 앨범에서 스캔해 결제하는 방식을 지원하지 않습니다. 현재 기기에서 직접 스캔하기 어렵다면 다른 휴대폰의 WeChat으로 이 코드를 스캔하세요.", "fr": "Pour des raisons de sécurité, WeChat ne permet pas de payer en scannant un QR enregistré dans la galerie. Si cet appareil ne peut pas scanner directement, utilisez WeChat sur un autre téléphone.", "de": "Aus Sicherheitsgründen unterstützt WeChat keine Zahlung über einen aus der Galerie gescannten QR-Code. Nutzen Sie bei Bedarf WeChat auf einem anderen Telefon.", "es": "Por seguridad, WeChat no permite pagar escaneando un QR guardado en la galería. Si este dispositivo no puede escanearlo directamente, usa WeChat en otro teléfono.", "pt": "Por segurança, o WeChat não permite pagar lendo um QR salvo na galeria. Se este aparelho não puder escanear diretamente, use o WeChat em outro telefone.", "ar": "لأسباب أمنية لا يدعم WeChat الدفع بمسح رمز QR محفوظ من ألبوم الصور. إذا تعذر المسح المباشر على هذا الجهاز فاستخدم WeChat على هاتف آخر."},
  "支付完成":{"ja": "支払いが完了しました", "ko": "결제가 완료되었습니다", "fr": "Paiement effectué", "de": "Zahlung abgeschlossen", "es": "Pago completado", "pt": "Pagamento concluído", "ar": "اكتمل الدفع"},
  "正在带你去场域订单……":{"ja": "フィールド注文へ移動しています…", "ko": "필드 주문으로 이동 중…", "fr": "Redirection vers vos commandes…", "de": "Weiterleitung zu den Bestellungen…", "es": "Llevándote a tus pedidos…", "pt": "Levando você aos pedidos…", "ar": "جارٍ نقلك إلى الطلبات…"},
  "切换到 lingxifield.cn 继续 →":{"ja": "lingxifield.cn に切り替えて続ける →", "ko": "lingxifield.cn으로 전환해 계속 →", "fr": "Passer à lingxifield.cn →", "de": "Zu lingxifield.cn wechseln →", "es": "Cambiar a lingxifield.cn →", "pt": "Mudar para lingxifield.cn →", "ar": "الانتقال إلى lingxifield.cn →"},
  "重试":{"ja": "再試行", "ko": "다시 시도", "fr": "Réessayer", "de": "Erneut versuchen", "es": "Reintentar", "pt": "Tentar novamente", "ar": "إعادة المحاولة"},
  "场域精测":{"ja": "フィールド精密測定", "ko": "필드 정밀 분석", "fr": "Analyse fine du champ", "de": "Präzise Feldanalyse", "es": "Análisis preciso del campo", "pt": "Análise precisa do campo", "ar": "التحليل الدقيق للمجال"},
  "十个入口，同一场生命的回声":{"ja": "10の入口、ひとつの生命フィールドの響き", "ko": "열 개의 입구, 하나의 생명 필드의 울림", "fr": "Dix entrées, l’écho d’un même champ vivant", "de": "Zehn Zugänge, ein lebendiges Feld", "es": "Diez entradas, un mismo campo vivo", "pt": "Dez entradas, um mesmo campo vivo", "ar": "عشرة مداخل، وصدى مجال حياة واحد"},
  "选择此刻与你发生回应的入口。这里没有替你定义的结论，只有可以带回真实经历中、由你亲自确认的多维映照。":{"ja": "今あなたに応答する入口を選んでください。ここにあなたを定義する結論はありません。実体験に持ち帰り、自分で確かめられる多次元の映しだけがあります。", "ko": "지금 당신에게 응답하는 입구를 선택하세요. 당신을 대신 정의하는 결론이 아니라 실제 경험으로 가져가 직접 확인할 수 있는 다차원적 반영을 제공합니다.", "fr": "Choisissez l’entrée qui vous répond maintenant. Rien ici ne vous définit : chaque reflet revient à votre vécu pour être vérifié par vous.", "de": "Wählen Sie den Zugang, der jetzt auf Sie antwortet. Nichts hier definiert Sie; jede Spiegelung kehrt in Ihre gelebte Erfahrung zurück.", "es": "Elige la entrada que responde a ti ahora. Nada aquí te define; cada reflejo vuelve a tu experiencia para que tú lo confirmes.", "pt": "Escolha a entrada que responde a você agora. Nada aqui define você; cada reflexo volta à sua experiência para sua própria confirmação.", "ar": "اختر المدخل الذي يستجيب لك الآن. لا توجد هنا خلاصة تعرّفك بدلًا عنك؛ بل انعكاسات متعددة الأبعاد تعود بها إلى تجربتك لتتحقق منها بنفسك."},
  "双引擎 · 两种观察路径":{"ja": "デュアルエンジン · 2つの観察経路", "ko": "듀얼 엔진 · 두 가지 관찰 경로", "fr": "Double moteur · Deux voies d’observation", "de": "Doppelmotor · Zwei Beobachtungswege", "es": "Doble motor · Dos vías de observación", "pt": "Motor duplo · Dois caminhos de observação", "ar": "محركان · مساران للملاحظة"},
  "官网从天文、历法与时间坐标进入，展开相对稳定的生命结构；微信小程序从真实选择、行为情境与当下状态进入，通过灵犀场树突知识网络持续形成个人结构记录。两者独立计算，可以彼此映照，不混算，也不预测未来。":{"ja": "公式サイトは天文・暦・時間座標から比較的安定した生命構造を展開します。WeChatミニプログラムは実際の選択・行動状況・現在状態から入り、LINGXIFIELDの樹状知識ネットワークで個人構造の記録を蓄積します。両者は独立計算で、相互に照合できますが混合計算や未来予測はしません。", "ko": "웹사이트는 천문·역법·시간 좌표를 통해 비교적 안정적인 생명 구조를 펼칩니다. WeChat 미니프로그램은 실제 선택, 행동 상황, 현재 상태에서 시작해 LINGXIFIELD 수상돌기 지식 네트워크로 개인 구조 기록을 축적합니다. 두 경로는 독립적으로 계산되며 서로 비춰볼 수 있지만 혼합 계산이나 미래 예측은 하지 않습니다.", "fr": "Le site s’appuie sur les coordonnées astronomiques, calendaires et temporelles pour déployer une structure de vie relativement stable. Le mini-programme WeChat part des choix réels, des contextes comportementaux et de l’état présent, puis forme un historique personnel via le réseau dendritique de connaissances LINGXIFIELD. Les deux voies sont calculées séparément, peuvent se refléter mutuellement, sans être mélangées ni prédire l’avenir.", "de": "Die Website erschließt über Astronomie, Kalender und Zeitkoordinaten eine relativ stabile Lebensstruktur. Das WeChat-Mini-Programm beginnt bei realen Entscheidungen, Verhaltenssituationen und dem aktuellen Zustand und bildet über das dendritische LINGXIFIELD-Wissensnetz persönliche Strukturaufzeichnungen. Beide Wege werden getrennt berechnet, können sich gegenseitig spiegeln, werden aber nicht vermischt und sagen die Zukunft nicht voraus.", "es": "El sitio parte de coordenadas astronómicas, calendáricas y temporales para desplegar una estructura vital relativamente estable. El miniprograma de WeChat parte de decisiones reales, contextos de conducta y estado presente, y forma un registro estructural personal mediante la red dendrítica de conocimiento de LINGXIFIELD. Ambos se calculan por separado y pueden reflejarse entre sí, sin mezclarse ni predecir el futuro.", "pt": "O site parte de coordenadas astronômicas, calendáricas e temporais para revelar uma estrutura de vida relativamente estável. O mini programa do WeChat parte de escolhas reais, contextos de comportamento e estado presente, formando registros pessoais pela rede dendrítica de conhecimento do LINGXIFIELD. Os dois caminhos são calculados separadamente, podem se espelhar, sem misturar cálculos nem prever o futuro.", "ar": "يدخل الموقع عبر الإحداثيات الفلكية والتقويمية والزمنية ليعرض بنية حياة مستقرة نسبيًا. أما برنامج WeChat المصغر فينطلق من الاختيارات الواقعية والسياقات السلوكية والحالة الراهنة، ويكوّن سجلًا بنيويًا شخصيًا عبر شبكة المعرفة المتشعبة في LINGXIFIELD. يُحسب المساران بشكل مستقل ويمكن أن يعكسا بعضهما دون دمج الحسابات أو التنبؤ بالمستقبل."},
  "当你准备好，让一次清晰的愿景成为每天都能回到的现实练习":{"ja": "準備ができたら、ひとつの明確な願いを毎日戻れる現実の実践にしてください。", "ko": "준비가 되었다면 하나의 분명한 비전을 매일 돌아올 수 있는 현실적 실천으로 만드세요.", "fr": "Quand vous êtes prêt, faites d’une vision claire une pratique réelle à laquelle revenir chaque jour.", "de": "Wenn Sie bereit sind, machen Sie aus einer klaren Vision eine reale tägliche Praxis.", "es": "Cuando estés listo, convierte una visión clara en una práctica real a la que volver cada día.", "pt": "Quando estiver pronto, transforme uma visão clara em uma prática real para retornar todos os dias.", "ar": "عندما تكون مستعدًا، حوّل رؤية واضحة إلى ممارسة واقعية تعود إليها كل يوم."},
  "完整六章、今日书写、签到回看与灵犀场回应，会在你的个人空间中持续保存。":{"ja": "全6章、今日の記録、チェックイン履歴、フィールドからの応答は個人スペースに保存され続けます。", "ko": "전체 6개 장, 오늘의 기록, 체크인 내역, 필드 응답이 개인 공간에 계속 저장됩니다.", "fr": "Les six chapitres, l’écriture du jour, l’historique des retours et les réponses du champ restent enregistrés dans votre espace personnel.", "de": "Alle sechs Kapitel, heutige Einträge, Check-ins und Feldantworten bleiben in Ihrem persönlichen Bereich gespeichert.", "es": "Los seis capítulos, la escritura de hoy, el historial de revisiones y las respuestas del campo se guardan en tu espacio personal.", "pt": "Os seis capítulos, a escrita de hoje, o histórico de check-ins e as respostas do campo ficam salvos no seu espaço pessoal.", "ar": "تُحفظ الفصول الستة وكتابة اليوم وسجل المتابعة واستجابات المجال في مساحتك الشخصية."},
  "六段显化路径":{"ja": "6つの具現化ステップ", "ko": "6단계 구현 경로", "fr": "Parcours en six étapes", "de": "Sechs Manifestationsschritte", "es": "Ruta de seis pasos", "pt": "Caminho em seis etapas", "ar": "مسار من ست مراحل"},
  "今日执行卡":{"ja": "今日の実践カード", "ko": "오늘의 실행 카드", "fr": "Carte de pratique du jour", "de": "Heutige Praxiskarte", "es": "Tarjeta de práctica de hoy", "pt": "Cartão de prática de hoje", "ar": "بطاقة ممارسة اليوم"},
  "带回今日现实回路":{"ja": "今日のリアリティ・ループへ持ち込む", "ko": "오늘의 현실 루프로 가져가기", "fr": "L’intégrer à la boucle de réalité du jour", "de": "In die heutige Realitätsschleife übernehmen", "es": "Llevarlo al bucle de realidad de hoy", "pt": "Levar para o ciclo de realidade de hoje", "ar": "إدخاله في حلقة الواقع اليوم"},
  "进入本章":{"ja": "この章を開く", "ko": "이 장 열기", "fr": "Ouvrir ce chapitre", "de": "Kapitel öffnen", "es": "Abrir capítulo", "pt": "Abrir capítulo", "ar": "فتح هذا الفصل"},
  "继续这段练习":{"ja": "この実践を続ける", "ko": "이 수련 계속하기", "fr": "Continuer cette pratique", "de": "Diese Übung fortsetzen", "es": "Continuar esta práctica", "pt": "Continuar esta prática", "ar": "متابعة هذه الممارسة"},
};

export function resolveBiNative(zh:string|null,en:string|null,lang:LingxiLang){
  if(lang==="zh") return zh ?? undefined;
  if(lang==="en") return en ?? zh ?? undefined;
  if(!zh) return en ?? undefined;
  return NATIVE[zh]?.[lang] ?? NATIVE_V104K[zh]?.[lang] ?? NATIVE_V104L[zh]?.[lang] ?? NATIVE_V104M[zh]?.[lang] ?? NATIVE_V104Q[zh]?.[lang] ?? NATIVE_V104R[zh]?.[lang] ?? NATIVE_V104T1[zh]?.[lang] ?? en ?? zh ?? undefined;
}
