import type {LingxiLang} from "./lingxi-i18n";
type Category={title:string;body:string};
export const FOOTER_CATALOG:Record<LingxiLang,Category[]>={
 zh:[
 {title:"PDF",body:"编辑、合并、拆分、压缩、电子签名、盖章、骑缝章、水印、页码、转图片、转Excel、OCR、全文搜索、比较、脱敏、加密、解密、删批注、删元数据、页面整理、裁边、拆半、多页合一、图片转PDF。"},
 {title:"图片",body:"OCR、图片转文字、扫描件识别、去水印、批量去水印、压缩、改尺寸、翻译、AI证件照、证件照换底色、证件复印排版、长图拼接、JPG/PNG/WebP/HEIC/AVIF/SVG转换、清除EXIF。"},
 {title:"视频音频",body:"视频去水印、视频转文字、音频转文字、字幕翻译、字幕制作、视频配音、压缩、裁剪、提取音频、倒放、循环、定格、音频降噪。"},
 {title:"文件表格",body:"CSV/TSV转Excel、Excel转CSV、CSV转JSON、ICS/VCF转CSV、DOCX/PPTX/EPUB/ODT转TXT、JSON/XML格式化、文本对比、去重、字数统计、二维码生成识别、文件格式检测、MD5/SHA256、URL/Base64/JWT/时间戳/正则/进制转换。"},
 {title:"其他工具",body:"临时邮箱、阅后即焚、截图打码、隐私清理、卡路里识别。"}],
 en:[{title:"PDF",body:"Edit, merge, split, compress, sign and stamp. Add watermarks and page numbers, convert images and spreadsheets, recognize and search text, compare, redact, encrypt, remove annotations and document information, reorder and crop pages."},{title:"Images",body:"Extract and translate text, recognize scans, remove watermarks individually or in batches, compress and resize, prepare ID photos and copies, stitch images, convert JPG/PNG/WebP/HEIC/AVIF/SVG and remove EXIF."},{title:"Video and audio",body:"Remove video watermarks, transcribe, translate and create subtitles, dub, compress, trim, extract audio, reverse, loop, freeze frames and reduce audio noise."},{title:"Files and spreadsheets",body:"Convert CSV, TSV, Excel, JSON, ICS and VCF. Extract text from DOCX/PPTX/EPUB/ODT. Format JSON/XML, compare and deduplicate text, count words, create and read QR codes, identify file formats and use hashes, URL/Base64/JWT, timestamps, regex and number converters."},{title:"More tools",body:"Temporary email, self-destructing messages, screenshot redaction, privacy cleanup and calorie recognition."}],
 ja:[{title:"PDF",body:"編集、結合、分割、圧縮、署名、押印、割印、透かし、ページ番号。画像・Excel変換、文字認識、全文検索、比較、墨消し、暗号化、注釈・文書情報削除、ページ整理と切り抜き。"},{title:"画像",body:"文字認識・翻訳、スキャン読み取り、透かしの削除と一括処理、圧縮、サイズ変更、証明写真と背景変更、身分証コピーの配置、画像結合、JPG/PNG/WebP/HEIC/AVIF/SVG変換、EXIF削除。"},{title:"動画・音声",body:"動画の透かし削除、文字起こし、字幕翻訳・制作、吹き替え、圧縮、切り取り、音声抽出、逆再生、ループ、静止画、音声ノイズ除去。"},{title:"ファイル・表計算",body:"CSV/TSV/Excel/JSON/ICS/VCF変換、DOCX/PPTX/EPUB/ODTから文字抽出、JSON/XML整形、文章比較、重複削除、文字数、QRコード、形式判定、MD5/SHA256、URL/Base64/JWT、時刻、正規表現、基数変換。"},{title:"その他",body:"一時メール、自動消去メッセージ、スクリーンショットの墨消し、プライバシー情報削除、カロリー認識。"}],
 ko:[{title:"PDF",body:"편집, 병합, 분할, 압축, 서명, 도장, 간인, 워터마크, 페이지 번호. 이미지·Excel 변환, 문자 인식, 검색, 비교, 가림 처리, 암호화, 주석·문서 정보 삭제, 페이지 정리와 자르기."},{title:"이미지",body:"문자 인식·번역, 스캔 문서 인식, 워터마크 삭제·일괄 처리, 압축, 크기 조절, 증명사진·배경 변경, 신분증 사본 배치, 이미지 연결, JPG/PNG/WebP/HEIC/AVIF/SVG 변환, EXIF 삭제."},{title:"영상·오디오",body:"영상 워터마크 삭제, 받아쓰기, 자막 번역·제작, 더빙, 압축, 자르기, 오디오 추출, 역재생, 반복, 정지 화면, 오디오 잡음 제거."},{title:"파일·표",body:"CSV/TSV/Excel/JSON/ICS/VCF 변환, DOCX/PPTX/EPUB/ODT 텍스트 추출, JSON/XML 정리, 텍스트 비교, 중복 제거, 글자 수, QR 코드, 파일 형식 확인, MD5/SHA256, URL/Base64/JWT, 시간·정규식·진수 변환."},{title:"기타 도구",body:"임시 이메일, 자동 삭제 메시지, 스크린샷 가림 처리, 개인정보 정리, 칼로리 인식."}],
 fr:[{title:"PDF",body:"Modifier, fusionner, diviser, compresser, signer et tamponner. Filigranes, pagination, conversion d’images et de tableaux, OCR, recherche, comparaison, masquage, chiffrement, suppression d’annotations et d’informations, organisation et recadrage."},{title:"Images",body:"OCR, traduction, lecture de scans, suppression de filigranes et traitement par lots, compression, redimensionnement, photos d’identité et fonds, copies de pièces, assemblage, conversion JPG/PNG/WebP/HEIC/AVIF/SVG, suppression EXIF."},{title:"Vidéo et audio",body:"Retirer les filigranes vidéo, transcrire, traduire et créer les sous-titres, doubler, compresser, couper, extraire l’audio, inverser, répéter, figer une image et réduire le bruit."},{title:"Fichiers et tableaux",body:"Conversions CSV/TSV/Excel/JSON/ICS/VCF, extraction de texte DOCX/PPTX/EPUB/ODT, formatage JSON/XML, comparaison, dédoublonnage, comptage, codes QR, détection de formats, MD5/SHA256, URL/Base64/JWT, dates, expressions régulières et bases numériques."},{title:"Autres outils",body:"Courriel temporaire, messages éphémères, masquage de captures, nettoyage des informations privées et reconnaissance des calories."}],
 de:[{title:"PDF",body:"Bearbeiten, zusammenführen, teilen, komprimieren, signieren und stempeln. Wasserzeichen, Seitenzahlen, Bild- und Tabellenkonvertierung, OCR, Suche, Vergleich, Schwärzung, Verschlüsselung, Anmerkungen und Dokumentinformationen entfernen, Seiten ordnen und zuschneiden."},{title:"Bilder",body:"OCR, Übersetzung, Scans lesen, Wasserzeichen einzeln oder gesammelt entfernen, komprimieren, skalieren, Passbilder und Hintergründe, Ausweiskopien, Bilder verbinden, JPG/PNG/WebP/HEIC/AVIF/SVG konvertieren, EXIF entfernen."},{title:"Video und Audio",body:"Videowasserzeichen entfernen, transkribieren, Untertitel übersetzen und erstellen, vertonen, komprimieren, schneiden, Audio extrahieren, rückwärts abspielen, wiederholen, Standbilder und Rauschreduzierung."},{title:"Dateien und Tabellen",body:"CSV/TSV/Excel/JSON/ICS/VCF konvertieren, Text aus DOCX/PPTX/EPUB/ODT, JSON/XML formatieren, Texte vergleichen, Duplikate entfernen, Wörter zählen, QR-Codes, Dateitypen, MD5/SHA256, URL/Base64/JWT, Zeitstempel, Regex und Zahlensysteme."},{title:"Weitere Werkzeuge",body:"Temporäre E-Mail, selbstlöschende Nachrichten, Screenshots schwärzen, private Informationen entfernen und Kalorien erkennen."}],
 es:[{title:"PDF",body:"Editar, unir, dividir, comprimir, firmar y sellar. Marcas de agua, numeración, conversión de imágenes y tablas, OCR, búsqueda, comparación, censura, cifrado, eliminación de anotaciones e información, orden y recorte de páginas."},{title:"Imágenes",body:"OCR, traducción, reconocimiento de escaneos, eliminación de marcas de agua por lotes, compresión, tamaño, fotos de identidad y fondos, copias de documentos, unión, conversión JPG/PNG/WebP/HEIC/AVIF/SVG y eliminación de EXIF."},{title:"Vídeo y audio",body:"Eliminar marcas de agua, transcribir, traducir y crear subtítulos, doblar, comprimir, recortar, extraer audio, invertir, repetir, congelar fotogramas y reducir ruido."},{title:"Archivos y tablas",body:"Conversión CSV/TSV/Excel/JSON/ICS/VCF, texto de DOCX/PPTX/EPUB/ODT, formato JSON/XML, comparación, eliminación de duplicados, recuento, QR, identificación de formatos, MD5/SHA256, URL/Base64/JWT, fechas, expresiones regulares y bases numéricas."},{title:"Más herramientas",body:"Correo temporal, mensajes autodestructivos, censura de capturas, limpieza de información privada y reconocimiento de calorías."}],
 pt:[{title:"PDF",body:"Editar, juntar, dividir, comprimir, assinar e carimbar. Marcas d’água, numeração, conversão de imagens e tabelas, OCR, busca, comparação, ocultação, criptografia, remoção de anotações e informações, organização e recorte de páginas."},{title:"Imagens",body:"OCR, tradução, reconhecimento de digitalizações, remoção de marcas d’água em lote, compressão, tamanho, fotos de documento e fundos, cópias de documentos, união, conversão JPG/PNG/WebP/HEIC/AVIF/SVG e remoção de EXIF."},{title:"Vídeo e áudio",body:"Remover marcas d’água, transcrever, traduzir e criar legendas, dublar, comprimir, cortar, extrair áudio, inverter, repetir, congelar quadros e reduzir ruído."},{title:"Arquivos e tabelas",body:"Conversão CSV/TSV/Excel/JSON/ICS/VCF, texto de DOCX/PPTX/EPUB/ODT, formatação JSON/XML, comparação, remoção de duplicatas, contagem, QR, identificação de formatos, MD5/SHA256, URL/Base64/JWT, datas, expressões regulares e bases numéricas."},{title:"Mais ferramentas",body:"E-mail temporário, mensagens autodestrutivas, ocultação em capturas, limpeza de informações privadas e reconhecimento de calorias."}],
 ar:[{title:"PDF",body:"التحرير والدمج والتقسيم والضغط والتوقيع والختم. علامات مائية وأرقام صفحات، وتحويل الصور والجداول، والتعرف على النص والبحث والمقارنة والإخفاء والتشفير، وإزالة التعليقات ومعلومات المستند وترتيب الصفحات وقصها."},{title:"الصور",body:"التعرف على النص وترجمته وقراءة المستندات الممسوحة، وإزالة العلامات المائية على دفعات، والضغط وتغيير الحجم، وصور الهوية والخلفيات ونسخ الوثائق، ودمج الصور وتحويل JPG/PNG/WebP/HEIC/AVIF/SVG وإزالة EXIF."},{title:"الفيديو والصوت",body:"إزالة العلامات المائية من الفيديو، وتحويل الكلام إلى نص، وترجمة وإنشاء الترجمة النصية، والدبلجة والضغط والقص واستخراج الصوت والعكس والتكرار وتجميد الإطارات وتقليل الضوضاء."},{title:"الملفات والجداول",body:"تحويل CSV/TSV/Excel/JSON/ICS/VCF، واستخراج النص من DOCX/PPTX/EPUB/ODT، وتنسيق JSON/XML ومقارنة النصوص وإزالة التكرار والعد ورموز QR وتحديد الصيغ، وMD5/SHA256 وURL/Base64/JWT والتوقيت والتعبيرات النمطية وأنظمة الأعداد."},{title:"أدوات أخرى",body:"بريد مؤقت ورسائل ذاتية الحذف وإخفاء بيانات لقطات الشاشة وتنظيف المعلومات الخاصة والتعرف على السعرات."}],
};
