"use client";
import type {LingxiLang} from "@/lib/lingxi-i18n";
type D=Record<string,string>;
const zh:D={burnTitle:"阅后即焚",burnLead:"把不想长期留存的内容变成私密链接，对方无需登录。",mode:"销毁方式",once:"阅后即焚",onceD:"适合一次性私密内容。",timed:"定时焚毁",timedD:"到指定时间后自动失效。",limited:"限次焚毁",limitedD:"达到设定查看次数后失效。",fast:"极速焚毁",fastD:"打开后开始倒计时，适合密码、验证码和短消息。",valid:"链接有效期",views:"查看次数",timer:"阅读时间",m10:"10分钟",h1:"1小时",h24:"24小时",d3:"3天",d7:"7天",v1:"1次",v3:"3次",v5:"5次",s5:"5秒",s10:"10秒",s30:"30秒",s60:"60秒",generate:"生成私密链接",generating:"正在生成…",ready:"链接已生成",copy:"复制链接",copied:"已复制",share:"分享",email:"用邮件发送",hint:"可直接发到微信、短信、QQ、邮件或其他聊天工具。",privacy:"隐私说明",privacyD:"内容在设备上加密后再保存。网页无法承诺绝对防截屏。",recipient:"有人给你留了一条私密内容",recipientD:"确认现在方便阅读再打开。",open:"打开内容",opening:"正在打开…",gone:"内容已失效。",openErr:"无法打开。",handled:"按发送者设置展示",left:"后隐藏",tempTitle:"10分钟临时邮箱",tempLead:"临时接收验证码、注册确认和一次性邮件。无需注册，到期自动销毁。",tempStart:"点击即可生成一个临时收件地址。",tempGen:"生成临时邮箱",tempGening:"正在生成…",addr:"临时邮箱地址",copyMail:"复制邮箱",refresh:"刷新",extend:"延长10分钟",destroy:"销毁邮箱",inbox:"收件箱",auto:"自动刷新",waiting:"正在等待新邮件…",unavailable:"临时邮箱暂时不可用，请稍后再试。",code:"验证码",copyCode:"复制验证码",messages:"封邮件",expires:"剩余时间"};
const en:D={burnTitle:"Burn After Reading",burnLead:"Turn sensitive text into a private link. The recipient does not need an account.",mode:"Destruction mode",once:"Burn after reading",onceD:"Best for one-time private content.",timed:"Timed expiry",timedD:"Expires automatically at the chosen time.",limited:"View limit",limitedD:"Expires after the selected number of views.",fast:"Fast burn",fastD:"Starts a countdown after opening.",valid:"Link validity",views:"Views",timer:"Reading time",m10:"10 min",h1:"1 hour",h24:"24 hours",d3:"3 days",d7:"7 days",v1:"1 view",v3:"3 views",v5:"5 views",s5:"5 sec",s10:"10 sec",s30:"30 sec",s60:"60 sec",generate:"Create private link",generating:"Creating…",ready:"Link ready",copy:"Copy link",copied:"Copied",share:"Share",email:"Send by email",hint:"Send it through chat, SMS or email.",privacy:"Privacy",privacyD:"Content is encrypted on your device before storage. A web page cannot promise absolute screenshot prevention.",recipient:"You received private content",recipientD:"Open it only when you are ready.",open:"Open content",opening:"Opening…",gone:"Content is no longer available.",openErr:"Unable to open.",handled:"Shown under the sender’s rule",left:"until hidden",tempTitle:"10-Minute Temporary Email",tempLead:"Receive verification codes, sign-up confirmations and one-time messages. No sign-up required; the inbox expires automatically.",tempStart:"Generate a temporary inbox in one click.",tempGen:"Generate temporary email",tempGening:"Generating…",addr:"Temporary email address",copyMail:"Copy email",refresh:"Refresh",extend:"Add 10 minutes",destroy:"Destroy inbox",inbox:"Inbox",auto:"Auto refresh",waiting:"Waiting for new mail…",unavailable:"Temporary email is unavailable right now.",code:"Verification code",copyCode:"Copy code",messages:"messages",expires:"Time left"};
const map:Record<LingxiLang,D>={
 zh,en,
 ja:{...en,burnTitle:"閲覧後に消去",tempTitle:"10分間の一時メール",tempLead:"認証コード、登録確認、一時メールを受信します。登録不要で、期限が来ると自動削除されます。",tempGen:"一時メールを生成",inbox:"受信箱",refresh:"更新",extend:"10分延長",destroy:"受信箱を削除",waiting:"新しいメールを待っています…",code:"認証コード",copyCode:"コードをコピー"},
 ko:{...en,burnTitle:"읽은 후 삭제",tempTitle:"10분 임시 이메일",tempLead:"인증 코드, 가입 확인 및 일회성 메일을 받습니다. 가입 없이 사용하며 만료 시 자동 삭제됩니다.",tempGen:"임시 이메일 생성",inbox:"받은편지함",refresh:"새로고침",extend:"10분 연장",destroy:"받은편지함 삭제",waiting:"새 메일을 기다리는 중…",code:"인증 코드",copyCode:"코드 복사"},
 fr:{...en,burnTitle:"Lecture éphémère",tempTitle:"E-mail temporaire 10 minutes",tempLead:"Recevez des codes de vérification, confirmations d’inscription et messages ponctuels. Sans inscription, avec expiration automatique.",tempGen:"Générer un e-mail temporaire",inbox:"Boîte de réception",refresh:"Actualiser",extend:"+10 minutes",destroy:"Détruire la boîte",waiting:"En attente de nouveaux messages…",code:"Code de vérification",copyCode:"Copier le code"},
 de:{...en,burnTitle:"Nach dem Lesen löschen",tempTitle:"10-Minuten-E-Mail",tempLead:"Empfange Bestätigungscodes, Registrierungsbestätigungen und einmalige Nachrichten. Ohne Anmeldung, automatische Löschung.",tempGen:"Temporäre E-Mail erzeugen",inbox:"Posteingang",refresh:"Aktualisieren",extend:"+10 Minuten",destroy:"Posteingang löschen",waiting:"Warte auf neue E-Mails…",code:"Bestätigungscode",copyCode:"Code kopieren"},
 es:{...en,burnTitle:"Autodestrucción",tempTitle:"Correo temporal de 10 minutos",tempLead:"Recibe códigos de verificación, confirmaciones de registro y mensajes puntuales. Sin registro y con caducidad automática.",tempGen:"Generar correo temporal",inbox:"Bandeja",refresh:"Actualizar",extend:"+10 minutos",destroy:"Destruir bandeja",waiting:"Esperando nuevos correos…",code:"Código de verificación",copyCode:"Copiar código"},
 pt:{...en,burnTitle:"Apagar após leitura",tempTitle:"E-mail temporário de 10 minutos",tempLead:"Receba códigos de verificação, confirmações de cadastro e mensagens únicas. Sem cadastro, com expiração automática.",tempGen:"Gerar e-mail temporário",inbox:"Caixa de entrada",refresh:"Atualizar",extend:"+10 minutos",destroy:"Destruir caixa",waiting:"Aguardando novos e-mails…",code:"Código de verificação",copyCode:"Copiar código"},
 ar:{...en,burnTitle:"إتلاف بعد القراءة",tempTitle:"بريد مؤقت لمدة 10 دقائق",tempLead:"استقبل رموز التحقق ورسائل تأكيد التسجيل والرسائل المؤقتة. دون تسجيل، وينتهي تلقائياً.",tempGen:"إنشاء بريد مؤقت",inbox:"الوارد",refresh:"تحديث",extend:"إضافة 10 دقائق",destroy:"إتلاف الصندوق",waiting:"بانتظار رسائل جديدة…",code:"رمز التحقق",copyCode:"نسخ الرمز"}
};
export function privacyText(lang:LingxiLang,key:string){return map[lang]?.[key]??en[key]??key}
