"use client";
import type {LingxiLang} from "@/lib/lingxi-i18n";
type D=Record<string,string>;
const zh:D={burnTitle:"阅后即焚",burnLead:"把不想长期留存的文字或文件变成私密链接，对方无需登录。",mode:"销毁方式",once:"阅后即焚",onceD:"适合一次性私密内容。",timed:"定时焚毁",timedD:"到指定时间后自动失效。",limited:"限次焚毁",limitedD:"达到设定查看次数后失效。",fast:"极速焚毁",fastD:"打开后开始倒计时，适合密码、验证码和短消息。",valid:"链接有效期",views:"查看次数",timer:"阅读时间",m10:"10分钟",h1:"1小时",h24:"24小时",d3:"3天",d7:"7天",v1:"1次",v3:"3次",v5:"5次",s5:"5秒",s10:"10秒",s30:"30秒",s60:"60秒",generate:"生成私密链接",generating:"正在生成…",ready:"链接已生成",copy:"复制链接",copied:"已复制",share:"分享",email:"用邮件发送",hint:"可直接发到微信、短信、QQ、邮件或其他聊天工具。",privacy:"隐私说明",privacyD:"私密链接仅在设定条件内有效。",recipient:"有人给你留了一份私密内容",recipientD:"确认现在方便查看再打开。",open:"打开内容",opening:"正在打开…",gone:"内容已失效。",openErr:"暂时无法打开，请稍后重试。",openMissing:"这条链接没有完整带上查看信息。请让发送者重新复制完整链接再发送。",openBlocked:"当前内置浏览器没有完成安全验证。请从聊天菜单选择“在浏览器打开”，或让发送者重新分享最新链接。",handled:"按发送者设置展示",left:"后隐藏",addFiles:"添加附件",files:"附件",fileLimit:"最多20个文件，合计不超过2GB。",filePaid:"附件按本次文件总大小计费。",payUpload:"支付并上传",uploading:"正在上传…",download:"下载文件",tempTitle:"10分钟临时邮箱",tempLead:"即时生成临时邮箱，无需注册即可接收普通邮件、注册确认和验证码；收件箱自动刷新，可复制邮箱和验证码、手动刷新、延长10分钟或立即销毁。单个邮箱最长可延长至60分钟；登录后还可付费批量生成11–100个，并复制全部地址或导出CSV。",tempStart:"点击即可生成一个临时收件地址。",tempGen:"生成临时邮箱",tempGening:"正在生成…",addr:"临时邮箱地址",copyMail:"复制邮箱",refresh:"刷新",extend:"延长10分钟",destroy:"销毁邮箱",inbox:"收件箱",auto:"自动刷新",waiting:"正在等待新邮件…",unavailable:"临时邮箱暂时不可用，请稍后再试。",code:"验证码",copyCode:"复制验证码",messages:"封邮件",expires:"剩余时间"};
const en:D={burnTitle:"Burn After Reading",burnLead:"Turn text or files you do not want to keep into a private link. No recipient account required.",mode:"Destruction mode",once:"Burn after reading",onceD:"Best for one-time private content.",timed:"Timed expiry",timedD:"Expires automatically at the chosen time.",limited:"View limit",limitedD:"Expires after the selected number of views.",fast:"Fast burn",fastD:"Starts a countdown after opening.",valid:"Link validity",views:"Views",timer:"Reading time",m10:"10 min",h1:"1 hour",h24:"24 hours",d3:"3 days",d7:"7 days",v1:"1 view",v3:"3 views",v5:"5 views",s5:"5 sec",s10:"10 sec",s30:"30 sec",s60:"60 sec",generate:"Create private link",generating:"Creating…",ready:"Link ready",copy:"Copy link",copied:"Copied",share:"Share",email:"Send by email",hint:"Send it through chat, SMS or email.",privacy:"Privacy",privacyD:"The private link works only under the rules you choose.",recipient:"You received private content",recipientD:"Open it only when you are ready.",open:"Open content",opening:"Opening…",gone:"Content is no longer available.",openErr:"Unable to open right now. Try again shortly.",openMissing:"This link is incomplete. Ask the sender to copy and send the full link again.",openBlocked:"This in-app browser could not complete the secure check. Open it in your system browser, or ask the sender to share a fresh link.",handled:"Shown under the sender’s rule",left:"until hidden",addFiles:"Add files",files:"Files",fileLimit:"Up to 20 files, 2GB total.",filePaid:"Files are priced by total size for this share.",payUpload:"Pay and upload",uploading:"Uploading…",download:"Download",tempTitle:"10-Minute Temporary Email",tempLead:"Create a temporary inbox instantly without signing up. Receive regular mail, sign-up confirmations and verification codes; auto-refresh the inbox, copy the address and codes, refresh manually, add 10 minutes or destroy it instantly. One inbox can be extended up to 60 minutes; signed-in users can also generate 11–100 inboxes in a paid batch and copy or export them as CSV.",tempStart:"Generate a temporary inbox in one click.",tempGen:"Generate temporary email",tempGening:"Generating…",addr:"Temporary email address",copyMail:"Copy email",refresh:"Refresh",extend:"Add 10 minutes",destroy:"Destroy inbox",inbox:"Inbox",auto:"Auto refresh",waiting:"Waiting for new mail…",unavailable:"Temporary email is unavailable right now.",code:"Verification code",copyCode:"Copy code",messages:"messages",expires:"Time left"};
const map:Record<LingxiLang,D>={
 zh,en,
 ja:{...en,openMissing:"リンクが完全ではありません。送信者に完全なリンクをもう一度コピーして送ってもらってください。",openBlocked:"このアプリ内ブラウザでは安全確認を完了できません。システムブラウザで開くか、新しいリンクを共有してもらってください。",burnTitle:"閲覧後に消去",burnLead:"長期保存したくないテキストやファイルを非公開リンクで共有します。",addFiles:"ファイルを追加",fileLimit:"最大20ファイル、合計2GBまで。",payUpload:"支払ってアップロード",download:"ダウンロード",tempTitle:"10分間の一時メール",tempLead:"認証コード、登録確認、一時メールを受信します。登録不要で、期限が来ると自動削除されます。"},
 ko:{...en,openMissing:"링크가 완전하지 않습니다. 보낸 사람에게 전체 링크를 다시 복사해 보내 달라고 요청하세요.",openBlocked:"현재 앱 내 브라우저에서 안전 확인을 완료하지 못했습니다. 시스템 브라우저로 열거나 새 링크를 다시 받아 주세요.",burnTitle:"읽은 후 삭제",burnLead:"오래 보관하지 않을 텍스트나 파일을 비공개 링크로 공유합니다.",addFiles:"파일 추가",fileLimit:"최대 20개 파일, 총 2GB.",payUpload:"결제 후 업로드",download:"다운로드",tempTitle:"10분 임시 이메일"},
 fr:{...en,openMissing:"Ce lien est incomplet. Demandez à l’expéditeur de copier et renvoyer le lien complet.",openBlocked:"Ce navigateur intégré n’a pas pu terminer la vérification. Ouvrez le lien dans le navigateur du système ou demandez un nouveau lien.",burnTitle:"Lecture éphémère",burnLead:"Partagez du texte ou des fichiers via un lien privé à durée limitée.",addFiles:"Ajouter des fichiers",fileLimit:"20 fichiers maximum, 2 Go au total.",payUpload:"Payer et téléverser",download:"Télécharger",tempTitle:"E-mail temporaire 10 minutes"},
 de:{...en,openMissing:"Dieser Link ist unvollständig. Bitten Sie den Absender, den vollständigen Link erneut zu kopieren und zu senden.",openBlocked:"Dieser In-App-Browser konnte die Sicherheitsprüfung nicht abschließen. Öffnen Sie den Link im Systembrowser oder lassen Sie ihn neu teilen.",burnTitle:"Nach dem Lesen löschen",burnLead:"Teile Text oder Dateien über einen privaten, zeitlich begrenzten Link.",addFiles:"Dateien hinzufügen",fileLimit:"Bis zu 20 Dateien, insgesamt 2 GB.",payUpload:"Bezahlen und hochladen",download:"Herunterladen",tempTitle:"10-Minuten-E-Mail"},
 es:{...en,openMissing:"Este enlace está incompleto. Pide al remitente que copie y envíe de nuevo el enlace completo.",openBlocked:"Este navegador integrado no pudo completar la verificación. Ábrelo en el navegador del sistema o pide un enlace nuevo.",burnTitle:"Autodestrucción",burnLead:"Comparte texto o archivos mediante un enlace privado con caducidad.",addFiles:"Añadir archivos",fileLimit:"Hasta 20 archivos, 2 GB en total.",payUpload:"Pagar y subir",download:"Descargar",tempTitle:"Correo temporal de 10 minutos"},
 pt:{...en,openMissing:"Este link está incompleto. Peça ao remetente para copiar e enviar novamente o link completo.",openBlocked:"Este navegador interno não concluiu a verificação. Abra no navegador do sistema ou peça um novo link.",burnTitle:"Apagar após leitura",burnLead:"Compartilhe texto ou arquivos por um link privado com expiração.",addFiles:"Adicionar arquivos",fileLimit:"Até 20 arquivos, 2 GB no total.",payUpload:"Pagar e enviar",download:"Baixar",tempTitle:"E-mail temporário de 10 minutos"},
 ar:{...en,openMissing:"هذا الرابط غير مكتمل. اطلب من المرسل نسخ الرابط الكامل وإرساله مرة أخرى.",openBlocked:"تعذر على المتصفح داخل التطبيق إكمال التحقق. افتح الرابط في متصفح النظام أو اطلب رابطًا جديدًا.",burnTitle:"إتلاف بعد القراءة",burnLead:"شارك نصوصاً أو ملفات عبر رابط خاص محدود الصلاحية.",addFiles:"إضافة ملفات",fileLimit:"حتى 20 ملفاً بإجمالي 2 غيغابايت.",payUpload:"الدفع والرفع",download:"تنزيل",tempTitle:"بريد مؤقت لمدة 10 دقائق"}
};
export function privacyText(lang:LingxiLang,key:string){return map[lang]?.[key]??en[key]??key}
