import * as Astronomy from "astronomy-engine";
import { createHash } from "node:crypto";
import { analyzeCircularDirections, normalizeBearing, type CircularDirectionAnalysis } from "@/lib/stellar-trace-math";
import { type AncientTraceEnvelope, type LiuYaoCast } from "@/lib/stellar-trace/ancient";
import { calculatePersonTrace } from "@/lib/stellar-trace/person/orchestrator";

export type StellarTraceInput = { name:string; relationship?:string; birthDate:string; birthTime?:string; birthPlace?:string; lastContactAt:string; lastKnownPlace?:string; lastKnownLat:number|null; lastKnownLon:number|null; movementDirection?:string; context?:string; liuyaoCast?:LiuYaoCast|null };
type NineFieldPosition = { id:string; nameZh:string; longitude:number };
export type NineFieldSnapshot = { epoch:"birth"|"last-contact"|"current"; labelZh:string; observedAt:string; julianDay:number; fields:NineFieldPosition[] };
export type ExperimentalProjection = { id:"time-phase"|"inner-planet"|"outer-planet"|"contact-frame"; labelZh:string; bearing:number; sourceFieldIds:string[]; rawValues:number[]; projectionRuleId:string; projectionBasisZh:string };
export type TracePriority = { available:boolean; status:"converged"|"clustered"|"insufficient"; statusZh:string; primaryBearing:number; primaryDirectionZh:string; primarySector:[number,number]; secondaryBearing:number|null; secondaryDirectionZh:string|null; basisZh:string; conflictsZh:string[]; verificationZh:string[] };
export type StellarTraceResult = { version:"lingxifield-stellar-trace-v4"; generatedAt:string; lastKnown:{lat:number|null;lon:number|null}; snapshots:NineFieldSnapshot[]; experimentalAstronomyProjections:ExperimentalProjection[]; evidence:ExperimentalProjection[]; direction:CircularDirectionAnalysis; ancient:AncientTraceEnvelope; priority:TracePriority; distance:{status:"uncalibrated";rangeKm:null;sourceZh:string;explanationZh:string}; candidateRegions:Array<{bearingRange:[number,number];distanceRangeKm:[number,number]}>; candidateCenter:null; candidateZones:Array<{rank:number;labelZh:string;distanceRangeKm:[number,number];center:{lat:number;lon:number}|null;radiusKm:number;basisZh:string;verificationZh:string}>; environmentZh:string[]; artIndexes:[number,number]; modelBoundaryZh:string; safetyBoundaryZh:string };

const bodies:Array<{id:string;nameZh:string;body?:Astronomy.Body}>=[{id:"sun",nameZh:"太阳"},{id:"mercury",nameZh:"水星",body:"Mercury" as Astronomy.Body},{id:"venus",nameZh:"金星",body:"Venus" as Astronomy.Body},{id:"earth",nameZh:"地球",body:"Earth" as Astronomy.Body},{id:"mars",nameZh:"火星",body:"Mars" as Astronomy.Body},{id:"jupiter",nameZh:"木星",body:"Jupiter" as Astronomy.Body},{id:"saturn",nameZh:"土星",body:"Saturn" as Astronomy.Body},{id:"uranus",nameZh:"天王星",body:"Uranus" as Astronomy.Body},{id:"neptune",nameZh:"海王星",body:"Neptune" as Astronomy.Body}];
const movementBearings:Record<string,number>={"向北":0,"东北":45,"向东":90,"东南":135,"向南":180,"西南":225,"向西":270,"西北":315};
const round=(value:number,digits=3)=>Number(value.toFixed(digits));
const signedDelta=(to:number,from:number)=>((to-from+540)%360)-180;
const directionName=(bearing:number)=>["北","东北","东","东南","南","西南","西","西北"][Math.round(normalizeBearing(bearing)/45)%8];
function longitude(body:Astronomy.Body|undefined,at:Date){if(!body)return normalizeBearing(Astronomy.SunPosition(at).elon);const vector=Astronomy.HelioVector(body,at);return normalizeBearing(Math.atan2(vector.y,vector.x)*180/Math.PI)}
const snapshot=(epoch:NineFieldSnapshot["epoch"],labelZh:string,at:Date):NineFieldSnapshot=>({epoch,labelZh,observedAt:at.toISOString(),julianDay:round(Astronomy.MakeTime(at).ut+2451545,5),fields:bodies.map(item=>({id:item.id,nameZh:item.nameZh,longitude:round(longitude(item.body,at))}))});
const field=(s:NineFieldSnapshot,id:string)=>s.fields.find(item=>item.id===id)?.longitude??0;
function projection(id:ExperimentalProjection["id"],labelZh:string,sourceFieldIds:string[],rawValues:number[],projectionBasisZh:string):ExperimentalProjection{const analysis=analyzeCircularDirections(rawValues);return{id,labelZh,bearing:round(analysis.diagnosticMean??0,1),sourceFieldIds,rawValues:rawValues.map(value=>round(value)),projectionRuleId:`${id}-experimental-astronomy-v4`,projectionBasisZh}}
const parseMoment=(value:string)=>/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}$/.test(value)?new Date(`${value.replace(" ","T")}:00+08:00`):new Date(value);

export async function calculateStellarTrace(input:StellarTraceInput,now=new Date()):Promise<StellarTraceResult>{
  const birthMoment=new Date(`${input.birthDate}T${input.birthTime||"12:00"}:00+08:00`);const lastContact=parseMoment(input.lastContactAt);if(!Number.isFinite(birthMoment.getTime())||!Number.isFinite(lastContact.getTime())||lastContact>now)throw new Error("invalid trace time");
  const snapshots=[snapshot("birth","生时九域",birthMoment),snapshot("last-contact","最后有效联系九域",lastContact),snapshot("current","当前九域",now)];const[birth,contact,current]=snapshots;
  const experimentalAstronomyProjections:ExperimentalProjection[]=[projection("time-phase","时间相位投影",["sun","earth"],[signedDelta(field(contact,"sun"),field(birth,"sun")),signedDelta(field(current,"earth"),field(contact,"earth"))],"九域天文事实的实验投影；不进入奇门、六壬时法主向。"),projection("inner-planet","内行星变化投影",["mercury","venus","mars"],["mercury","venus","mars"].map(id=>signedDelta(field(current,id),field(contact,id))),"内行星角位移实验层；不冒充古籍规则。"),projection("outer-planet","外行星变化投影",["jupiter","saturn","uranus","neptune"],["jupiter","saturn","uranus","neptune"].map(id=>signedDelta(field(current,id),field(contact,id))),"外行星慢周期实验层；不代表现实位置。"),projection("contact-frame","联系时刻框架投影",["sun","mars","saturn"],[field(contact,"sun"),field(contact,"mars"),field(contact,"saturn")],"最后有效联系时刻的可复算天文框架。")];
  const direction=analyzeCircularDirections(experimentalAstronomyProjections.map(item=>item.bearing));const reportedMovementBearing=movementBearings[input.movementDirection||""]??null;
  const ancient=await calculatePersonTrace({targetKind:"person",subjectName:input.name,birthDate:input.birthDate,birthTime:input.birthTime||null,birthPlace:input.birthPlace||null,queryTime:now.toISOString(),lastContactAt:lastContact.toISOString(),lastKnownPlace:input.lastKnownPlace||null,lastKnownCoordinate:input.lastKnownLat!=null&&input.lastKnownLon!=null?{lat:input.lastKnownLat,lon:input.lastKnownLon,label:input.lastKnownPlace}:null,reportedMovementBearing,liuyaoCast:input.liuyaoCast??null});
  const primary=ancient.fused.primary;const coverage=ancient.results.filter(item=>item.status==="ok"||item.status==="partial").length;
  const priority:TracePriority=primary?{available:true,status:ancient.fused.qualified?"converged":"clustered",statusZh:ancient.fused.qualified?"双式方向收敛":`时法成向 ${coverage} / ${ancient.results.length}`,primaryBearing:round(primary.centerDeg,1),primaryDirectionZh:primary.labelZh,primarySector:primary.sector,secondaryBearing:ancient.fused.modes[1]?.centerDeg??null,secondaryDirectionZh:ancient.fused.modes[1]?directionName(ancient.fused.modes[1].centerDeg):null,basisZh:ancient.fused.rationaleZh,conflictsZh:ancient.results.flatMap(item=>item.warningsZh),verificationZh:[`由“${input.lastKnownPlace||"最后可证地点"}”起，按时法主向先核验近域出口与时序记录。`,ancient.realityValidation.noteZh,"现实记录若与候选方向相逆，两者并列保留，不改写时法结果。"]}:{available:false,status:"insufficient",statusZh:`时法成向 ${coverage} / ${ancient.results.length}`,primaryBearing:0,primaryDirectionZh:"未成主向",primarySector:[0,0],secondaryBearing:null,secondaryDirectionZh:null,basisZh:"当前没有两套同时成立的可复算时法方位。九域实验投影继续展示，但不得替代时法主向。",conflictsZh:ancient.results.flatMap(item=>item.warningsZh),verificationZh:[`先从“${input.lastKnownPlace||"最后可证地点"}”按现实接触链核验。`,ancient.realityValidation.noteZh,"保留已成单项方位，待另一套时法成向后再判断是否合参。"]};
  const seed=Number.parseInt(createHash("sha256").update(`${input.name}|${birthMoment.toISOString()}|${lastContact.toISOString()}`).digest("hex").slice(0,12),16);
  return{version:"lingxifield-stellar-trace-v4",generatedAt:now.toISOString(),lastKnown:{lat:input.lastKnownLat,lon:input.lastKnownLon},snapshots,experimentalAstronomyProjections,evidence:experimentalAstronomyProjections,direction,ancient,priority,distance:{status:"uncalibrated",rangeKm:null,sourceZh:"原典远近层尚未完成真实案例校准",explanationZh:"方向与距离分开判定；在古法里数未通过盲测校准前，不生成公里数、坐标中心或伪精度半径。"},candidateRegions:[],candidateCenter:null,candidateZones:[],environmentZh:input.context?["现实线索已进入核验层，不参与原典主向"]:["尚无补充现实线索"],artIndexes:[seed%60,(seed*17+23)%60],modelBoundaryZh:"九域天文事实层、原典推演层与现实核验层已经分离；用户填写的移动方向只改变现实核验，不改变原典合度。",safetyBoundaryZh:"本结果不读取设备、通信、GPS 或实时行踪，也不构成人员现实位置认定；涉及安全请立即使用警方、通信、交通与紧急救援渠道。"};
}
