import type {LingxiLang} from "@/lib/lingxi-i18n";
const KEYS=["tell","mine","drag","title","close","received","saved","number","lead","placeholder","add","limits","screenshot","sending","send","mail","badImages","write","login","failed"] as const;
const ROWS:Record<LingxiLang,readonly string[]>={
  "zh": [
    "告诉我们",
    "我的问题",
    "拖动这里移动",
    "告诉我们哪里没有按期待工作",
    "关闭",
    "已收到 ✓",
    "问题已保存，可在“我的问题”查看处理进度。",
    "编号：",
    "写下问题，也可以添加截图。当前页面和设备信息会随问题发送。",
    "例如：上传 PDF 后没有预览，或者无法下载文件。",
    "＋ 添加截图",
    "最多 4 张，每张不超过 5MB；支持拖放或粘贴。",
    "截图",
    "正在发送…",
    "发送给灵犀场",
    "也可以邮件联系",
    "请选择 PNG、JPG、WebP 或 GIF，每张不超过 5MB。",
    "请先写下发生了什么。",
    "请先登录，再发送问题和查看进度。",
    "这次没有发送成功，请重试或邮件联系。"
  ],
  "en": [
    "Tell us",
    "My requests",
    "Drag here to move",
    "Tell us what went wrong",
    "Close",
    "Received ✓",
    "Your request is saved. Check its progress in My requests.",
    "Reference:",
    "Describe the problem and add screenshots if helpful. Your current page and device details will be included.",
    "For example: no preview after uploading a PDF, or a file will not download.",
    "＋ Add screenshots",
    "Up to 4 images, 5MB each. You can drag or paste them here.",
    "Screenshot",
    "Sending…",
    "Send to LINGXIFIELD",
    "You can also email",
    "Choose PNG, JPG, WebP or GIF images, no larger than 5MB each.",
    "Please describe what happened.",
    "Sign in to send your request and follow its progress.",
    "Your request was not sent. Please retry or email us."
  ],
  "ja": [
    "お問い合わせ",
    "お問い合わせ履歴",
    "ここをドラッグして移動",
    "困ったことを教えてください",
    "閉じる",
    "受け付けました ✓",
    "お問い合わせを保存しました。履歴から対応状況を確認できます。",
    "受付番号：",
    "問題を書き、必要なら画像を追加してください。現在のページと端末情報も送信されます。",
    "例：PDFをアップロードしてもプレビューが出ない、ファイルをダウンロードできない。",
    "＋ 画像を追加",
    "最大4枚、各5MBまで。ドラッグや貼り付けもできます。",
    "画像",
    "送信中…",
    "LINGXIFIELDへ送信",
    "メールでもお問い合わせいただけます",
    "PNG、JPG、WebP、GIFの画像を選んでください。各5MBまでです。",
    "起きたことを書いてください。",
    "ログインして送信すると、対応状況を確認できます。",
    "送信できませんでした。再度お試しいただくか、メールでご連絡ください。"
  ],
  "ko": [
    "문의하기",
    "내 문의",
    "여기를 끌어 이동",
    "어떤 문제가 있었나요?",
    "닫기",
    "접수되었습니다 ✓",
    "문의가 저장되었습니다. 내 문의에서 처리 상황을 확인하세요.",
    "문의 번호:",
    "문제를 설명하고 필요하면 화면 사진을 추가하세요. 현재 페이지와 기기 정보도 함께 전송됩니다.",
    "예: PDF를 올려도 미리 보기가 없거나 파일을 내려받을 수 없습니다.",
    "＋ 화면 사진 추가",
    "최대 4장, 한 장당 5MB. 끌어 놓거나 붙여 넣을 수 있습니다.",
    "화면 사진",
    "전송 중…",
    "LINGXIFIELD에 보내기",
    "이메일로도 문의할 수 있습니다",
    "PNG, JPG, WebP 또는 GIF를 선택하세요. 한 장당 5MB 이하만 가능합니다.",
    "어떤 일이 있었는지 적어 주세요.",
    "로그인하면 문의를 보내고 처리 상황을 확인할 수 있습니다.",
    "전송하지 못했습니다. 다시 시도하거나 이메일로 문의하세요."
  ],
  "fr": [
    "Nous contacter",
    "Mes demandes",
    "Glissez ici pour déplacer",
    "Décrivez le problème rencontré",
    "Fermer",
    "Reçu ✓",
    "Votre demande est enregistrée. Suivez son traitement dans Mes demandes.",
    "Référence :",
    "Décrivez le problème et ajoutez des captures si nécessaire. La page actuelle et les informations de votre appareil seront incluses.",
    "Par exemple : aucun aperçu après avoir ajouté un PDF, ou impossible de télécharger un fichier.",
    "＋ Ajouter des captures",
    "4 images maximum, 5 Mo chacune. Glissez-les ou collez-les ici.",
    "Capture",
    "Envoi…",
    "Envoyer à LINGXIFIELD",
    "Vous pouvez aussi écrire par e-mail",
    "Choisissez des images PNG, JPG, WebP ou GIF de 5 Mo maximum chacune.",
    "Décrivez ce qui s’est passé.",
    "Connectez-vous pour envoyer votre demande et suivre son traitement.",
    "La demande n’a pas été envoyée. Réessayez ou contactez-nous par e-mail."
  ],
  "de": [
    "Kontakt aufnehmen",
    "Meine Anfragen",
    "Hier ziehen zum Verschieben",
    "Was hat nicht funktioniert?",
    "Schließen",
    "Erhalten ✓",
    "Ihre Anfrage wurde gespeichert. Verfolgen Sie den Fortschritt unter Meine Anfragen.",
    "Referenz:",
    "Beschreiben Sie das Problem und fügen Sie bei Bedarf Bildschirmfotos hinzu. Die aktuelle Seite und Geräteinformationen werden mitgesendet.",
    "Zum Beispiel: Keine Vorschau nach dem PDF-Upload oder eine Datei lässt sich nicht herunterladen.",
    "＋ Bildschirmfotos hinzufügen",
    "Bis zu 4 Bilder mit je 5 MB. Hier hineinziehen oder einfügen.",
    "Bildschirmfoto",
    "Wird gesendet…",
    "An LINGXIFIELD senden",
    "Sie können uns auch eine E-Mail senden",
    "Wählen Sie PNG, JPG, WebP oder GIF mit höchstens 5 MB pro Bild.",
    "Beschreiben Sie bitte, was passiert ist.",
    "Melden Sie sich an, um Ihre Anfrage zu senden und den Fortschritt zu verfolgen.",
    "Ihre Anfrage wurde nicht gesendet. Versuchen Sie es erneut oder schreiben Sie uns eine E-Mail."
  ],
  "es": [
    "Contacta con nosotros",
    "Mis consultas",
    "Arrastra aquí para mover",
    "Cuéntanos qué ocurrió",
    "Cerrar",
    "Recibido ✓",
    "Tu consulta está guardada. Puedes seguir su estado en Mis consultas.",
    "Referencia:",
    "Describe el problema y añade capturas si lo necesitas. Se incluirán la página actual y los datos de tu dispositivo.",
    "Por ejemplo: no aparece la vista previa del PDF o no se puede descargar un archivo.",
    "＋ Añadir capturas",
    "Hasta 4 imágenes de 5 MB cada una. Puedes arrastrarlas o pegarlas aquí.",
    "Captura",
    "Enviando…",
    "Enviar a LINGXIFIELD",
    "También puedes escribirnos por correo",
    "Elige imágenes PNG, JPG, WebP o GIF de hasta 5 MB cada una.",
    "Describe lo que ocurrió.",
    "Inicia sesión para enviar tu consulta y seguir su estado.",
    "No se ha enviado tu consulta. Inténtalo de nuevo o escríbenos por correo."
  ],
  "pt": [
    "Fale conosco",
    "Minhas solicitações",
    "Arraste aqui para mover",
    "Conte o que aconteceu",
    "Fechar",
    "Recebido ✓",
    "Sua solicitação foi salva. Acompanhe o andamento em Minhas solicitações.",
    "Referência:",
    "Descreva o problema e adicione capturas se necessário. A página atual e as informações do dispositivo serão incluídas.",
    "Exemplo: o PDF não mostra uma prévia ou não é possível baixar um arquivo.",
    "＋ Adicionar capturas",
    "Até 4 imagens de 5 MB cada. Você pode arrastar ou colar aqui.",
    "Captura",
    "Enviando…",
    "Enviar para LINGXIFIELD",
    "Você também pode entrar em contato por e-mail",
    "Escolha imagens PNG, JPG, WebP ou GIF de até 5 MB cada.",
    "Descreva o que aconteceu.",
    "Entre na sua conta para enviar a solicitação e acompanhar o andamento.",
    "Sua solicitação não foi enviada. Tente novamente ou entre em contato por e-mail."
  ],
  "ar": [
    "تواصل معنا",
    "طلباتي",
    "اسحب هنا للتحريك",
    "أخبرنا بما حدث",
    "إغلاق",
    "تم الاستلام ✓",
    "تم حفظ طلبك. يمكنك متابعة تقدمه في طلباتي.",
    "الرقم المرجعي:",
    "صف المشكلة وأضف صورًا للشاشة عند الحاجة. سيُرسل عنوان الصفحة الحالية ومعلومات الجهاز معها.",
    "مثال: لا تظهر معاينة بعد رفع ملف PDF، أو يتعذر تنزيل ملف.",
    "＋ أضف صورًا للشاشة",
    "حتى 4 صور، بحجم 5 ميغابايت لكل صورة. يمكنك سحبها أو لصقها هنا.",
    "صورة للشاشة",
    "جارٍ الإرسال…",
    "إرسال إلى LINGXIFIELD",
    "يمكنك أيضًا التواصل عبر البريد الإلكتروني",
    "اختر صور PNG أو JPG أو WebP أو GIF بحجم لا يتجاوز 5 ميغابايت لكل صورة.",
    "يرجى وصف ما حدث.",
    "سجّل الدخول لإرسال طلبك ومتابعة تقدمه.",
    "لم يُرسل طلبك. حاول مرة أخرى أو تواصل عبر البريد الإلكتروني."
  ]
};
export function supportCopy(lang:LingxiLang){return Object.fromEntries(KEYS.map((key,index)=>[key,ROWS[lang][index]])) as Record<typeof KEYS[number],string>}
