export type TarotCard = {
  index: number; // 0-77，直接对应 public/images/tarot/ 下的图片文件名（00.jpg~77.jpg）
  nameZh: string; nameEn: string;
  keywordsZh: string; keywordsEn: string;
  meaningZh: string; meaningEn: string;
  system: "archetype" | "domain" | "practice"; // 三大系统：灵魂原型/生命领域/修炼
  domain?: string; // 生命领域牌专属：爱与关系/财富创造/事业使命/命运周期/内在成长
};

// ────────────────────────────────────────────────────────────────────
// 灵犀量子塔罗 · 78张卡牌数据
// ────────────────────────────────────────────────────────────────────
// 这是小仙女自己设计的原创卡牌体系（《Lingxi Quantum Tarot》实施文档
// V1.0），不是传统塔罗——不用西方那套"愚者/魔术师/女祭司"的名字和
// 含义，是全新的78张：22张灵魂原型牌（对应人生最大的22个意识阶段）+
// 40张生命领域牌（爱与关系/财富创造/事业使命/命运周期/内在成长，
// 各8张）+ 16张修炼牌（对应灵犀场四大修炼技术，各4张）。
// 每张牌的"含义"这里写成一句解读，是从原始文档给的关键词/主题
// 扩展出来的，风格延续全站"具体、给方向、不说空话"的原则，不是
// 传统塔罗牌那种"预言"式断语。
export const TAROT_MAJOR_ARCANA: TarotCard[] = [
  // ── 第一系统：22张灵魂原型牌 ──────────────────────────────
  { index: 0, nameZh: "无限旅者", nameEn: "The Infinite Traveler", keywordsZh: "开始・信任・探索", keywordsEn: "Beginning · Trust · Exploration", meaningZh: "一段新的周期正在打开——不需要先看清全部的路，能相信自己愿意走出第一步，就已经是这张牌想说的全部。", meaningEn: "A new cycle is opening — you don't need to see the whole road first. Trusting yourself enough to take the first step is already the whole point of this card.", system: "archetype" },
  { index: 1, nameZh: "创造者", nameEn: "The Creator", keywordsZh: "创造・意念・显化", keywordsEn: "Creation · Intention · Manifestation", meaningZh: "你此刻的注意力放在哪里，就是在往哪个方向创造现实——今天值得留意，自己反复在想的那件事，究竟是在滋养什么。", meaningEn: "Wherever your attention goes right now is the reality you're actively creating — worth noticing what you keep dwelling on, and what it's actually feeding.", system: "archetype" },
  { index: 2, nameZh: "内在之眼", nameEn: "The Inner Eye", keywordsZh: "直觉・洞察・潜意识", keywordsEn: "Intuition · Insight · Subconscious", meaningZh: "在急着向外找答案之前，先看看自己已经隐约知道了什么——很多时候，答案不是缺失的，是被忽略了。", meaningEn: "Before rushing to look outward for an answer, check what you already half-know — often the answer isn't missing, it's just been overlooked.", system: "archetype" },
  { index: 3, nameZh: "生命之母", nameEn: "The Mother of Life", keywordsZh: "滋养・丰盛・创造", keywordsEn: "Nurture · Abundance · Creation", meaningZh: "丰盛不是先拥有很多，是先把自己照顾好——今天适合给自己一点滋养，而不是继续往外输出。", meaningEn: "Abundance doesn't start with having a lot — it starts with taking care of yourself first. Today favors receiving nourishment, not more outward giving.", system: "archetype" },
  { index: 4, nameZh: "秩序之王", nameEn: "The King of Order", keywordsZh: "结构・责任・稳定", keywordsEn: "Structure · Responsibility · Stability", meaningZh: "自由不是没有边界，是在自己搭好的结构里，反而能走得更远——今天适合把一件事的规则定清楚。", meaningEn: "Freedom isn't the absence of structure — the structures you build yourself are often what let you go further. Today favors setting clear rules for something.", system: "archetype" },
  { index: 5, nameZh: "古老智慧", nameEn: "Ancient Wisdom", keywordsZh: "传承・学习・真理", keywordsEn: "Lineage · Learning · Truth", meaningZh: "不是所有问题都需要自己从零想明白——今天适合去看看，前人在类似的处境里，是怎么走过来的。", meaningEn: "Not every question needs to be worked out from scratch — today favors looking at how others have navigated a similar situation before you.", system: "archetype" },
  { index: 6, nameZh: "灵魂连接", nameEn: "Soul Connection", keywordsZh: "爱情・选择・共鸣", keywordsEn: "Love · Choice · Resonance", meaningZh: "真正的连接，不是找到一个完美契合的人，是两个人都愿意在差异里，继续选择彼此。", meaningEn: "Real connection isn't finding someone who fits perfectly — it's two people continuing to choose each other across their differences.", system: "archetype" },
  { index: 7, nameZh: "命运之舟", nameEn: "The Vessel of Destiny", keywordsZh: "行动・方向・勇气", keywordsEn: "Action · Direction · Courage", meaningZh: "方向不是想出来的，是走出来的——今天适合先迈出那一步，路会在走的过程里变得更清楚。", meaningEn: "Direction isn't figured out by thinking — it's found by moving. Today favors taking the step; the path clarifies as you go.", system: "archetype" },
  { index: 8, nameZh: "内在力量", nameEn: "Inner Strength", keywordsZh: "勇气・驯服・平衡", keywordsEn: "Courage · Taming · Balance", meaningZh: "真正的力量不是压制住内心那股冲动的部分，是学会跟它相处——今天不用消灭什么，只需要平衡。", meaningEn: "Real strength isn't suppressing the wild part of yourself — it's learning to work with it. Today isn't about eliminating anything, just balance.", system: "archetype" },
  { index: 9, nameZh: "静默观察者", nameEn: "The Silent Observer", keywordsZh: "孤独・内省・智慧", keywordsEn: "Solitude · Introspection · Wisdom", meaningZh: "今天更适合往内走，而不是往外求——一个人安静待一会儿，可能比找人商量更有用。", meaningEn: "Today favors turning inward rather than seeking outside. A little quiet solitude may serve you better than asking around.", system: "archetype" },
  { index: 10, nameZh: "时间轮盘", nameEn: "The Wheel of Time", keywordsZh: "周期・转变・机会", keywordsEn: "Cycles · Change · Opportunity", meaningZh: "有些事情不在你的掌控范围里，这是提醒你放松抓握，而不是更用力去控制。", meaningEn: "Some things are genuinely outside your control right now — a reminder to loosen your grip rather than tighten it.", system: "archetype" },
  { index: 11, nameZh: "灵魂平衡", nameEn: "Soul Balance", keywordsZh: "因果・选择・公正", keywordsEn: "Cause & Effect · Choice · Fairness", meaningZh: "今天适合把话说清楚、把账算明白——公平不是别人给的，是你愿不愿意先诚实面对。", meaningEn: "Today favors saying things plainly and settling accounts clearly. Fairness starts with your own honesty first.", system: "archetype" },
  { index: 12, nameZh: "倒影世界", nameEn: "The Mirrored World", keywordsZh: "暂停・转换・觉察", keywordsEn: "Pause · Shift · Awareness", meaningZh: "换一个角度看同一件事，可能会看到完全不同的答案——暂停，有时候比继续推进更有用。", meaningEn: "Looking at the same thing from a different angle may reveal a different answer entirely. Pausing can serve you better than pushing on.", system: "archetype" },
  { index: 13, nameZh: "新生之门", nameEn: "The Gate of Rebirth", keywordsZh: "结束・重生・蜕变", keywordsEn: "Ending · Rebirth · Transformation", meaningZh: "一个阶段真正结束了，才能给下一个阶段腾出空间——今天适合正式跟某件事告别。", meaningEn: "A phase truly ending is what makes room for the next one. Today is a good day to formally let something go.", system: "archetype" },
  { index: 14, nameZh: "能量融合", nameEn: "Energy Fusion", keywordsZh: "平衡・调和・治愈", keywordsEn: "Balance · Harmony · Healing", meaningZh: "不需要走极端——把两个看起来矛盾的东西，慢慢调和在一起，比二选一更适合今天。", meaningEn: "No need for extremes today. Slowly blending two seemingly opposite things serves you better than picking one over the other.", system: "archetype" },
  { index: 15, nameZh: "阴影觉醒", nameEn: "Shadow Awakening", keywordsZh: "欲望・恐惧・阴影", keywordsEn: "Desire · Fear · Shadow", meaningZh: "诚实面对一个自己一直不太想承认的执念或习惯——看清它，是松开它的第一步。", meaningEn: "Being honest about a habit or attachment you haven't wanted to admit to. Seeing it clearly is the first step to loosening its grip.", system: "archetype" },
  { index: 16, nameZh: "觉醒之塔", nameEn: "The Tower of Awakening", keywordsZh: "突破・重构", keywordsEn: "Breakthrough · Rebuilding", meaningZh: "一个建立在不稳固基础上的东西正在松动——这不是惩罚，是重新建一个更结实的机会。", meaningEn: "Something built on shaky ground is coming loose — not a punishment, a chance to rebuild something sturdier.", system: "archetype" },
  { index: 17, nameZh: "星辰希望", nameEn: "Stellar Hope", keywordsZh: "信念・指引", keywordsEn: "Belief · Guidance", meaningZh: "经历过一段低谷之后的一点希望和平静，今天比较容易被感受到——允许自己相信事情会慢慢好起来。", meaningEn: "A little hope and calm after a hard stretch is easier to feel today. Let yourself believe things are slowly getting better.", system: "archetype" },
  { index: 18, nameZh: "潜意识之海", nameEn: "The Sea of the Subconscious", keywordsZh: "梦境・情绪・未知", keywordsEn: "Dreams · Emotion · The Unknown", meaningZh: "有些事情今天可能看不太清楚，感觉比逻辑更可靠一些——不确定的时候，先别急着下结论。", meaningEn: "Some things may not be fully clear today — instinct may serve better than logic. When uncertain, hold off on conclusions.", system: "archetype" },
  { index: 19, nameZh: "太阳意识", nameEn: "Solar Consciousness", keywordsZh: "生命力・光明", keywordsEn: "Vitality · Light", meaningZh: "清晰、活力、被看见的时刻——适合把一直藏着的东西，拿到阳光下让别人也看见。", meaningEn: "A moment of clarity, vitality, and being seen. Favors bringing something you've kept hidden out into the light.", system: "archetype" },
  { index: 20, nameZh: "灵魂召唤", nameEn: "Soul's Calling", keywordsZh: "觉醒・回归", keywordsEn: "Awakening · Return", meaningZh: "回头看一段过去，可能会有新的理解——不是为了评判自己，是为了带着这份理解往前走。", meaningEn: "Looking back at something past may bring new understanding — not to judge yourself, but to carry it forward.", system: "archetype" },
  { index: 21, nameZh: "宇宙完整", nameEn: "Cosmic Wholeness", keywordsZh: "完成・合一", keywordsEn: "Completion · Oneness", meaningZh: "一个完整的循环走到了收尾，值得停下来认可自己走过的这一程，再开始下一个。", meaningEn: "A full cycle is coming to a close — worth pausing to acknowledge how far you've come before starting the next one.", system: "archetype" },

  // ── 第二系统 A：爱与关系（8张） ──────────────────────────────
  { index: 22, nameZh: "灵魂相遇", nameEn: "Soul Encounter", keywordsZh: "为什么遇见这个人", keywordsEn: "Why you met this person", meaningZh: "两个人的相遇，往往不是巧合，是各自当下正在经历的课题，刚好能在对方身上照见。", meaningEn: "Meeting someone rarely is pure coincidence — it's often that whatever you're each working through can suddenly be seen in the other.", system: "domain", domain: "爱与关系" },
  { index: 23, nameZh: "镜像关系", nameEn: "Mirror Relationship", keywordsZh: "对方映照你的什么", keywordsEn: "What they reflect in you", meaningZh: "让你格外有反应的那部分，往往不只是关于对方——留意一下，是不是也在照见你自己的某一面。", meaningEn: "Whatever triggers a strong reaction in you often isn't only about them — worth noticing if it's also reflecting something in you.", system: "domain", domain: "爱与关系" },
  { index: 24, nameZh: "情感流动", nameEn: "Emotional Flow", keywordsZh: "爱的给予与接受", keywordsEn: "Giving and receiving love", meaningZh: "健康的关系，给和收要能双向流动——留意一下，你是不是更擅长其中一边，另一边一直没打开。", meaningEn: "A healthy connection needs love to flow both ways — notice if you're more practiced at one direction than the other.", system: "domain", domain: "爱与关系" },
  { index: 25, nameZh: "未完成连接", nameEn: "Unfinished Connection", keywordsZh: "过去关系影响", keywordsEn: "The influence of a past relationship", meaningZh: "一段过去的关系，如果还在影响现在的选择，值得诚实问自己：是没放下这个人，还是没放下当时的自己。", meaningEn: "If a past relationship still shapes your choices now, it's worth asking honestly: is it the person you haven't let go of, or who you were back then.", system: "domain", domain: "爱与关系" },
  { index: 26, nameZh: "心门开启", nameEn: "Heart Opening", keywordsZh: "进入亲密关系", keywordsEn: "Entering intimacy", meaningZh: "真正的靠近，需要先卸下一点防备——今天适合在一段关系里，多让对方看见一点真实的自己。", meaningEn: "Real closeness requires lowering the guard a little first. Today favors letting someone see a bit more of the real you.", system: "domain", domain: "爱与关系" },
  { index: 27, nameZh: "关系疗愈", nameEn: "Relationship Healing", keywordsZh: "修复伤痕", keywordsEn: "Repairing what hurt", meaningZh: "修复不是假装事情没发生过，是两个人都愿意，重新走一遍那段没说清楚的部分。", meaningEn: "Repair isn't pretending it didn't happen — it's both people willing to revisit the part that was never fully said.", system: "domain", domain: "爱与关系" },
  { index: 28, nameZh: "双向成长", nameEn: "Mutual Growth", keywordsZh: "共同进化", keywordsEn: "Evolving together", meaningZh: "好的关系不是两个人一直保持不变，是各自都在变得更好，还愿意留在同一条路上。", meaningEn: "A good relationship isn't two people staying the same — it's both growing and still choosing to walk the same road.", system: "domain", domain: "爱与关系" },
  { index: 29, nameZh: "永恒伙伴", nameEn: "Eternal Partner", keywordsZh: "长期关系结构", keywordsEn: "The structure of a lasting bond", meaningZh: "长久的关系靠的不是一直有激情，是搭建出一套两个人都认可、能反复回到的相处方式。", meaningEn: "What lasts isn't constant passion — it's building a way of being together that both people trust and can return to.", system: "domain", domain: "爱与关系" },

  // ── 第二系统 B：财富创造（8张） ──────────────────────────────
  { index: 30, nameZh: "财富入口", nameEn: "Wealth Gateway", keywordsZh: "财富入口", keywordsEn: "Where wealth enters", meaningZh: "机会常常不是从最显眼的地方进来的——今天适合留意那些看起来不起眼、但反复出现的信号。", meaningEn: "Opportunity rarely enters through the obvious door. Today favors noticing the small, recurring signal you've been dismissing.", system: "domain", domain: "财富创造" },
  { index: 31, nameZh: "价值交换", nameEn: "Value Exchange", keywordsZh: "价值交换", keywordsEn: "Fair exchange", meaningZh: "健康的财富流动，是双方都觉得划算——今天适合检查一下，有没有哪一段交换，只有你在付出。", meaningEn: "Healthy wealth flow feels fair to both sides. Today favors checking whether some exchange has only you giving.", system: "domain", domain: "财富创造" },
  { index: 32, nameZh: "创造之流", nameEn: "Flow of Creation", keywordsZh: "创造之流", keywordsEn: "The current of making", meaningZh: "钱常常跟着你真正投入的东西走，不是跟着你觉得「应该做」的东西——留意这两者有没有分岔。", meaningEn: "Money often follows what you're genuinely invested in, not what you think you \"should\" do. Notice where the two have split apart.", system: "domain", domain: "财富创造" },
  { index: 33, nameZh: "商业直觉", nameEn: "Business Instinct", keywordsZh: "商业直觉", keywordsEn: "Instinct for opportunity", meaningZh: "有时候数据还没到位，直觉已经先感觉到了方向——今天适合相信自己那份说不清但很坚定的判断。", meaningEn: "Sometimes the data isn't in yet but your gut already knows the direction. Today favors trusting that hard-to-explain certainty.", system: "domain", domain: "财富创造" },
  { index: 34, nameZh: "机会窗口", nameEn: "Window of Opportunity", keywordsZh: "机会窗口", keywordsEn: "A limited-time opening", meaningZh: "有些机会有一个自然的时间窗口——今天适合判断，这件事是可以慢慢来，还是需要现在就动。", meaningEn: "Some opportunities have a natural window. Today favors deciding whether this one can wait or needs action now.", system: "domain", domain: "财富创造" },
  { index: 35, nameZh: "财富阻碍", nameEn: "Wealth Blockage", keywordsZh: "财富阻碍", keywordsEn: "What's blocking the flow", meaningZh: "卡住财富的，很多时候不是能力不够，是某个自己都没意识到的「不配得」念头——今天适合诚实看一眼。", meaningEn: "What blocks wealth is often not lack of ability, but an unconscious sense of not deserving it. Today favors an honest look.", system: "domain", domain: "财富创造" },
  { index: 36, nameZh: "资源整合", nameEn: "Resource Integration", keywordsZh: "资源整合", keywordsEn: "Bringing pieces together", meaningZh: "你手上可能已经有足够的资源了，只是它们还没被摆到一起——今天适合盘点，而不是继续找新的。", meaningEn: "You may already have enough resources — they just haven't been arranged together yet. Today favors taking stock, not seeking more.", system: "domain", domain: "财富创造" },
  { index: 37, nameZh: "丰盛循环", nameEn: "Abundance Cycle", keywordsZh: "丰盛循环", keywordsEn: "The self-renewing cycle", meaningZh: "真正的丰盛是一个循环，不是一次性的收获——留意你有没有把接住的东西，再转出去一部分，让它继续流动。", meaningEn: "Real abundance is a cycle, not a one-time gain. Notice whether you're letting what you receive flow onward, not just accumulating it.", system: "domain", domain: "财富创造" },

  // ── 第二系统 C：事业使命（8张） ──────────────────────────────
  { index: 38, nameZh: "天赋启动", nameEn: "Gift Ignition", keywordsZh: "天赋启动", keywordsEn: "Activating your gift", meaningZh: "你做起来毫不费力、别人却觉得很厉害的那件事，往往就是天赋所在——它太自然了，容易被自己忽略。", meaningEn: "The thing that costs you no effort but impresses others is often your gift — it feels too natural, so it's easy to overlook.", system: "domain", domain: "事业使命" },
  { index: 39, nameZh: "使命方向", nameEn: "Direction of Purpose", keywordsZh: "使命方向", keywordsEn: "Where purpose points", meaningZh: "使命感不需要一开始就很宏大——今天适合从「哪件事让我做完之后觉得值得」这个具体感受出发去找方向。", meaningEn: "A sense of purpose doesn't need to start grand. Today favors starting from what leaves you feeling it was worth doing.", system: "domain", domain: "事业使命" },
  { index: 40, nameZh: "创造表达", nameEn: "Creative Expression", keywordsZh: "你的表达，是宇宙创造的延伸", keywordsEn: "Your expression is the extension of universal creation", meaningZh: "把想法留在脑子里和真的说出来/做出来，是完全不同的两件事——今天适合让内在的东西，有一个具体的出口。", meaningEn: "Keeping an idea in your head and actually expressing it are two different things. Today favors giving what's inside a concrete outlet.", system: "domain", domain: "事业使命" },
  { index: 41, nameZh: "领导力量", nameEn: "Leadership Power", keywordsZh: "领导力量", keywordsEn: "The power to lead", meaningZh: "真正的领导力，不是让所有人都听你的，是让大家因为信任你，愿意一起往同一个方向走。", meaningEn: "Real leadership isn't getting everyone to obey — it's earning enough trust that people choose to move in the same direction with you.", system: "domain", domain: "事业使命" },
  { index: 42, nameZh: "转型节点", nameEn: "Turning Point", keywordsZh: "转型节点", keywordsEn: "The point of transition", meaningZh: "职业路径上的转弯，往往发生在你已经做得足够熟练、却开始觉得不够满足的那个时刻——这不是矛盾，是信号。", meaningEn: "Career turns often happen exactly when you've gotten skilled but start feeling unfulfilled — that's not a contradiction, it's a signal.", system: "domain", domain: "事业使命" },
  { index: 43, nameZh: "长期积累", nameEn: "Long-Term Accumulation", keywordsZh: "长期积累", keywordsEn: "What compounds over time", meaningZh: "有些成果今天看不出差别，是因为它们本来就要靠时间才能显现——今天适合继续做那件「看不到即时回报」的事。", meaningEn: "Some results show no difference today simply because they need time to show at all. Today favors continuing the thing with no immediate payoff.", system: "domain", domain: "事业使命" },
  { index: 44, nameZh: "团队共振", nameEn: "Team Resonance", keywordsZh: "团队共振", keywordsEn: "When a team clicks", meaningZh: "一个团队真正开始有战斗力，往往不是因为每个人都很强，是因为彼此的强项刚好能互相补位。", meaningEn: "A team truly starts to work not because everyone is individually strong, but because their strengths happen to fill each other's gaps.", system: "domain", domain: "事业使命" },
  { index: 45, nameZh: "成果显化", nameEn: "Manifested Results", keywordsZh: "成果显化", keywordsEn: "Results becoming visible", meaningZh: "该出结果的阶段到了——今天适合把之前一直在做的事情，正式拿出来给别人看见。", meaningEn: "The results-showing phase has arrived. Today favors formally putting what you've been working on in front of others.", system: "domain", domain: "事业使命" },

  // ── 第二系统 D：命运周期（8张） ──────────────────────────────
  { index: 46, nameZh: "新周期", nameEn: "New Cycle", keywordsZh: "新周期", keywordsEn: "A fresh cycle begins", meaningZh: "一个新的阶段正在开始，还带着上一个阶段的余温——不用急着把过去清空，新旧可以并存一阵子。", meaningEn: "A new phase is beginning while the last one still lingers. No need to rush clearing the old — they can coexist for a while.", system: "domain", domain: "命运周期" },
  { index: 47, nameZh: "隐藏机会", nameEn: "Hidden Opportunity", keywordsZh: "隐藏机会", keywordsEn: "An opportunity in disguise", meaningZh: "有一件看起来不太顺利的事，里面可能藏着一个还没被看见的机会——值得多看它一眼，而不是急着放弃。", meaningEn: "Something that looks like it's going wrong may be hiding an opportunity not yet seen. Worth a second look before giving up on it.", system: "domain", domain: "命运周期" },
  { index: 48, nameZh: "命运转折", nameEn: "Fateful Turn", keywordsZh: "命运转折", keywordsEn: "A turning point", meaningZh: "一个不算小的转折可能正在靠近——它未必来得轰轰烈烈，也可能是一个安静的决定，事后才看出分量。", meaningEn: "A meaningful turn may be approaching — it may not arrive dramatically; it could be a quiet decision whose weight only becomes clear later.", system: "domain", domain: "命运周期" },
  { index: 49, nameZh: "等待时期", nameEn: "A Season of Waiting", keywordsZh: "等待时期", keywordsEn: "This is a waiting season", meaningZh: "不是所有阶段都需要用力推进——现在更像是一个需要耐心等待时机成熟的阶段，硬冲反而容易打乱节奏。", meaningEn: "Not every phase calls for pushing hard. This one is more about patiently letting timing ripen — forcing it risks throwing off the rhythm.", system: "domain", domain: "命运周期" },
  { index: 50, nameZh: "突破窗口", nameEn: "Breakthrough Window", keywordsZh: "突破窗口", keywordsEn: "A window for breakthrough", meaningZh: "一直卡住的地方，可能正好来到了能松动的时间点——今天适合再试一次之前放弃的那件事。", meaningEn: "Something long stuck may have just reached the point where it can move. Today favors trying again the thing you'd given up on.", system: "domain", domain: "命运周期" },
  { index: 51, nameZh: "旧模式结束", nameEn: "Old Pattern Ends", keywordsZh: "旧模式结束", keywordsEn: "An old pattern is ending", meaningZh: "一种反复出现的老模式，正走到它自然结束的时候——留意一下，这次你是不是真的准备好不再重复它了。", meaningEn: "A recurring old pattern is reaching its natural end. Notice whether you're actually ready this time not to repeat it.", system: "domain", domain: "命运周期" },
  { index: 52, nameZh: "新身份诞生", nameEn: "New Identity Born", keywordsZh: "新身份诞生", keywordsEn: "A new identity is born", meaningZh: "你正在成为一个跟过去不太一样的自己——这个转变可能还没被身边人完全注意到，但你自己已经感觉到了。", meaningEn: "You're becoming someone slightly different from who you were. Others may not have fully noticed yet, but you already feel it.", system: "domain", domain: "命运周期" },
  { index: 53, nameZh: "未来展开", nameEn: "The Future Unfolds", keywordsZh: "未来展开", keywordsEn: "The future is unfolding", meaningZh: "接下来的路不需要一次看到底——它会一段一段展开，走到那里，自然会看见下一步。", meaningEn: "The road ahead doesn't need to be seen all at once — it unfolds in stretches, and the next step becomes visible when you get there.", system: "domain", domain: "命运周期" },

  // ── 第二系统 E：内在成长（8张） ──────────────────────────────
  { index: 54, nameZh: "自我认识", nameEn: "Self-Knowledge", keywordsZh: "自我认识", keywordsEn: "Knowing yourself", meaningZh: "今天适合诚实地问自己一个问题，而不是急着找答案——有时候，问对问题本身就已经是进展。", meaningEn: "Today favors honestly asking yourself a question, not rushing to answer it. Sometimes asking the right question is already progress.", system: "domain", domain: "内在成长" },
  { index: 55, nameZh: "情绪释放", nameEn: "Emotional Release", keywordsZh: "情绪释放", keywordsEn: "Letting emotion move", meaningZh: "被压下去的情绪，不会自己消失，只会换个地方冒出来——今天适合给某种情绪一个正式的出口。", meaningEn: "Suppressed emotion doesn't vanish — it just resurfaces somewhere else. Today favors giving some feeling a real outlet.", system: "domain", domain: "内在成长" },
  { index: 56, nameZh: "内心稳定", nameEn: "Inner Stability", keywordsZh: "内心稳定", keywordsEn: "Steadiness within", meaningZh: "外面的事情不一定能控制，但今天可以练习——不管外面发生什么，先让自己有一个稳定的落脚点。", meaningEn: "You can't always control what's happening outside, but today you can practice having a steady place inside to stand on regardless.", system: "domain", domain: "内在成长" },
  { index: 57, nameZh: "信念重塑", nameEn: "Belief Reshaped", keywordsZh: "信念重塑", keywordsEn: "Reshaping a belief", meaningZh: "有一个你一直深信不疑的想法，可能已经不再适合现在的你——今天适合重新问一次，这个想法还成立吗。", meaningEn: "A belief you've long held may no longer fit who you are now. Today favors asking again whether it still holds true.", system: "domain", domain: "内在成长" },
  { index: 58, nameZh: "直觉开启", nameEn: "Intuition Opening", keywordsZh: "直觉开启", keywordsEn: "Intuition switching on", meaningZh: "有个念头一闪而过、你差点忽略了它——今天适合多给这类直觉一点空间，不用马上用逻辑去验证它。", meaningEn: "A flash of insight almost got dismissed. Today favors giving that intuition more room, without rushing to justify it logically.", system: "domain", domain: "内在成长" },
  { index: 59, nameZh: "能量恢复", nameEn: "Energy Recovery", keywordsZh: "能量恢复", keywordsEn: "Restoring energy", meaningZh: "不是所有的疲惫都要靠「再撑一下」解决——今天更适合的，是真正停下来，把消耗掉的补回来。", meaningEn: "Not all fatigue is solved by pushing through a little more. Today favors actually stopping and restoring what's been spent.", system: "domain", domain: "内在成长" },
  { index: 60, nameZh: "意识扩展", nameEn: "Expanded Consciousness", keywordsZh: "打破界限，超越局限，拥抱更广阔的真相与可能性", keywordsEn: "Break beyond boundaries, transcend limits, and embrace greater truths and possibilities", meaningZh: "你对自己/对某件事的理解，可能一直被一个没有明说的假设限制住了——今天适合去看看，假设之外还有什么可能。", meaningEn: "Your understanding of something may have been quietly limited by an unspoken assumption. Today favors looking beyond it.", system: "domain", domain: "内在成长" },
  { index: 61, nameZh: "自我超越", nameEn: "Self-Transcendence", keywordsZh: "自我超越", keywordsEn: "Rising above your old self", meaningZh: "超越不是变成一个完全不同的人，是带着现在拥有的一切，走到一个比过去更宽的位置上。", meaningEn: "Transcending yourself isn't becoming someone else — it's carrying everything you have now into a wider version of who you are.", system: "domain", domain: "内在成长" },

  // ── 第三系统：16张修炼牌 ──────────────────────────────
  { index: 62, nameZh: "宇宙呼吸", nameEn: "Cosmic Breath", keywordsZh: "连接生命节律", keywordsEn: "Connect Life Rhythm", meaningZh: "今天适合做一次量子息法——不用追求呼吸有多深，先感受到自己在呼吸，就已经是连接。", meaningEn: "Today favors a round of the Quantum Breath Method — not about how deep the breath is, just noticing you're breathing is already the connection.", system: "practice", domain: "量子息法" },
  { index: 63, nameZh: "光息循环", nameEn: "Cycle of Light Breath", keywordsZh: "能量恢复", keywordsEn: "Energy Recovery", meaningZh: "量子息法的呼吸循环，本身就是在给能量重新充电——觉得耗竭的时候，这是一个可以直接用的工具。", meaningEn: "The breath cycle in the Quantum Breath Method is itself a way of recharging. When depleted, this is a tool you can use directly.", system: "practice", domain: "量子息法" },
  { index: 64, nameZh: "心场扩展", nameEn: "Heart-Field Expansion", keywordsZh: "扩大觉察", keywordsEn: "Expanded Awareness", meaningZh: "觉察力不是天生固定的，是可以练出来的——量子息法练的正是这个，今天适合安排一次。", meaningEn: "Awareness isn't a fixed trait — it's trainable, and the Quantum Breath Method is exactly that training. Today favors a session.", system: "practice", domain: "量子息法" },
  { index: 65, nameZh: "静息归源", nameEn: "Stillness, Returning to Source", keywordsZh: "回归中心", keywordsEn: "Return to Center", meaningZh: "外面的事情再多，也可以练习先回到自己的中心——量子息法最后一步，就是在做这件事。", meaningEn: "No matter how much is happening outside, you can practice returning to your center first — the final step of the breath practice does exactly this.", system: "practice", domain: "量子息法" },
  { index: 66, nameZh: "心之太阳", nameEn: "Sun of the Heart", keywordsZh: "与宇宙同频", keywordsEn: "Align with the Cosmos", meaningZh: "上升心经练的是把心打开到更大的频率——今天适合花几分钟，感受一下这份打开的状态。", meaningEn: "The Ascending Heart Sutra trains opening the heart to a wider frequency. Today favors a few minutes feeling into that openness.", system: "practice", domain: "上升心经" },
  { index: 67, nameZh: "爱的升维", nameEn: "Love, Ascended", keywordsZh: "觉察当下", keywordsEn: "Awareness Now", meaningZh: "爱不只是一种情绪，也可以是一种觉察当下的方式——上升心经在练的，正是把爱变成一种在场的能力。", meaningEn: "Love isn't only an emotion — it can be a way of being present. Ascending Heart practice trains love as a form of presence.", system: "practice", domain: "上升心经" },
  { index: 68, nameZh: "内在光源", nameEn: "Inner Light Source", keywordsZh: "能量流动", keywordsEn: "Energy Flow", meaningZh: "光不需要从外面找——今天适合练一次上升心经，感受那份本来就在你身体里流动的能量。", meaningEn: "Light doesn't need to be found outside. Today favors an Ascending Heart session, feeling the energy already flowing within you.", system: "practice", domain: "上升心经" },
  { index: 69, nameZh: "无限慈悲", nameEn: "Infinite Compassion", keywordsZh: "深层呼吸", keywordsEn: "Deep Breathing", meaningZh: "慈悲不只是对别人，也包括对自己——今天适合把上升心经的这份柔软，先分一点给自己。", meaningEn: "Compassion isn't only for others — it includes yourself. Today favors directing some of that Ascending Heart softness inward first.", system: "practice", domain: "上升心经" },
  { index: 70, nameZh: "灵感火种", nameEn: "Spark of Inspiration", keywordsZh: "激活灵感", keywordsEn: "Inspire Inspiration", meaningZh: "直觉丹道练的是让灵感更容易被接住——今天适合把那些一闪而过的念头，随手记下来。", meaningEn: "The Intuitive Way trains catching inspiration more readily. Today favors jotting down the fleeting thoughts as they pass.", system: "practice", domain: "直觉丹道" },
  { index: 71, nameZh: "内丹觉醒", nameEn: "Inner Elixir Awakening", keywordsZh: "知识转化", keywordsEn: "Transform Knowledge", meaningZh: "学到的东西，只有真正转化成自己的理解，才算数——今天适合把最近学的一点东西，用自己的话重新说一遍。", meaningEn: "What you've learned only counts once it becomes your own understanding. Today favors re-explaining something recent in your own words.", system: "practice", domain: "直觉丹道" },
  { index: 72, nameZh: "意识凝聚", nameEn: "Consciousness Convergence", keywordsZh: "艺术流动", keywordsEn: "Flow of Art", meaningZh: "创造力需要一个具体的出口才能真正流动起来——今天适合做一件纯粹为了表达、不为了结果的小事。", meaningEn: "Creativity needs a concrete outlet to actually flow. Today favors doing something small purely for expression, not for outcome.", system: "practice", domain: "直觉丹道" },
  { index: 73, nameZh: "智慧流动", nameEn: "Flow of Wisdom", keywordsZh: "真诚表达", keywordsEn: "Express Authentically", meaningZh: "直觉丹道最后练的是让内在的东西，真诚地流出来——今天适合说一句你一直没说出口的真心话。", meaningEn: "The final stage of the Intuitive Way is letting what's inside flow out honestly. Today favors saying one true thing you've been holding back.", system: "practice", domain: "直觉丹道" },
  { index: 74, nameZh: "空性之门", nameEn: "Gate of Emptiness", keywordsZh: "清空杂念", keywordsEn: "Clear Distractions", meaningZh: "归零心诀第一步是清空——今天适合花几分钟，什么都不做，让脑子里的杂音先安静下来。", meaningEn: "The first step of Heart Reset is clearing out. Today favors a few minutes of doing nothing, letting the mental noise settle.", system: "practice", domain: "归零心诀" },
  { index: 75, nameZh: "放下旧我", nameEn: "Releasing the Old Self", keywordsZh: "回归当下", keywordsEn: "Return to the Present", meaningZh: "过去那个自己已经完成了它的使命——今天适合练一次归零心诀，把注意力带回到此刻。", meaningEn: "The self you used to be has served its purpose. Today favors a Heart Reset session, bringing attention back to now.", system: "practice", domain: "归零心诀" },
  { index: 76, nameZh: "回归纯净", nameEn: "Return to Purity", keywordsZh: "安住纯净", keywordsEn: "Abide in Purity", meaningZh: "不需要先把所有事情都处理完，才能感到干净——归零心诀练的，就是随时能回到这份纯净。", meaningEn: "You don't need everything resolved first to feel clear. Heart Reset trains returning to that clarity at any moment.", system: "practice", domain: "归零心诀" },
  { index: 77, nameZh: "无限可能", nameEn: "Infinite Possibilities", keywordsZh: "当心归于零，宇宙无界展开，所有路径同时存在，所有未来皆可选择", keywordsEn: "When the heart returns to zero, the universe unfolds without limits — all paths exist at once, all futures are yours to choose", meaningZh: "当心真正静下来，会发现能走的路，比自己以为的多得多——今天适合允许自己，看见不止一种可能。", meaningEn: "When the heart truly settles, you find there are far more paths available than you assumed. Today favors allowing more than one possibility.", system: "practice", domain: "归零心诀" },
];
