import type {LingxiLang} from '@/lib/lingxi-i18n';
const languages=['zh','en','ja','ko','fr','de','es','pt','ar'];
const rows:Record<string,string[]>={
 foodUnit:['种食物','foods','種類','종류','aliments','Lebensmittel','alimentos','alimentos','أنواع طعام'],
 imageUnit:['张图片','photos','枚','장','photos','Fotos','fotos','fotos','صور'],
 login:['请先登录，已确认的食物会保留。','Sign in first. Your confirmed foods are saved.','ログインしてください。確認した食品は保存されています。','먼저 로그인하세요. 확인한 음식은 저장되었습니다.','Connectez-vous. Vos aliments sont enregistrés.','Bitte anmelden. Die Auswahl ist gespeichert.','Inicia sesión. Los alimentos están guardados.','Entre na sua conta. Os alimentos estão salvos.','سجل الدخول أولًا. تم حفظ الأطعمة المؤكدة.'],
 pricing:['每天免费分析一张图片或进行一次自定义查询，两种方式共享一次机会。之后图片按张、自定义按不同食物种类计费：每单位 ¥2 或 $2。多张图片按总张数收费。每日 UTC 00:00 重置。','One photo analysis OR one custom query free daily, shared across both modes. Then ¥2 or $2 per photo or distinct food in custom queries. Batches cost the total number of photos. Resets at 00:00 UTC.','毎日、写真1枚または食品の手入力1回が無料（共通枠）。以降は写真1枚・食品1種類につき¥2または$2。複数写真は全枚数で計算。UTC 00:00更新。','매일 사진 1장 또는 직접 입력 조회 1회 무료(공유). 이후 사진당 또는 서로 다른 음식 종류당 ¥2 또는 $2. 여러 사진은 전체 장수로 계산. UTC 00:00 초기화.','Une photo OU une recherche manuelle gratuite par jour, quota partagé. Ensuite ¥2 ou $2 par photo ou aliment distinct. Les lots sont facturés au nombre total de photos. Remise à zéro à 00:00 UTC.','Täglich ein Foto ODER eine manuelle Abfrage kostenlos, gemeinsames Kontingent. Danach ¥2 oder $2 je Foto bzw. unterschiedlichem Lebensmittel. Bildserien nach Gesamtzahl. Zurücksetzung um 00:00 UTC.','Una foto O una consulta manual gratis al día, cupo compartido. Después ¥2 o $2 por foto o alimento distinto. Los lotes se cobran por el total de fotos. Reinicio a las 00:00 UTC.','Uma foto OU uma consulta manual grátis por dia, cota compartilhada. Depois ¥2 ou $2 por foto ou alimento distinto. Lotes cobrados pelo total de fotos. Reinício às 00:00 UTC.','صورة واحدة أو استعلام يدوي واحد مجانًا يوميًا بحصة مشتركة. بعدها ¥2 أو $2 لكل صورة أو نوع طعام مختلف. تُحسب الدفعات بعدد الصور الإجمالي. تتجدد الحصة الساعة 00:00 UTC.'],
 freeNow:['使用今日免费机会','Use today’s free analysis','本日の無料枠を使う','오늘 무료 분석 사용','Utiliser l’analyse gratuite','Heute kostenlos analysieren','Usar análisis gratuito','Usar análise grátis','استخدام التحليل المجاني اليوم'],
 ready:['食物已确认，查看本次价格','Foods confirmed · view price','食品を確認・価格を見る','음식 확인 · 가격 보기','Aliments confirmés · voir le prix','Auswahl bestätigt · Preis ansehen','Alimentos confirmados · ver precio','Alimentos confirmados · ver preço','تم تأكيد الأطعمة · عرض السعر'],
 saved:['上次的分析','Previous analysis','前回の分析','이전 분석','Analyse précédente','Vorherige Analyse','Análisis anterior','Análise anterior','التحليل السابق'],
 retry:['重新打开结果','Reopen result','結果を再表示','결과 다시 열기','Rouvrir le résultat','Ergebnis erneut öffnen','Volver a abrir resultado','Reabrir resultado','فتح النتيجة مجددًا'],
 used:['今日免费机会已使用，可确认价格后继续。','Today’s free analysis is used. Review the price to continue.','本日の無料枠は使用済みです。価格を確認して続行できます。','오늘 무료 분석을 사용했습니다. 가격 확인 후 계속하세요.','Analyse gratuite utilisée. Vérifiez le prix pour continuer.','Gratisanalyse heute genutzt. Preis prüfen und fortfahren.','Análisis gratuito usado. Revisa el precio para continuar.','Análise grátis usada. Confira o preço para continuar.','استُخدمت الحصة المجانية اليوم. راجع السعر للمتابعة.'],
 unavailable:['暂时无法完成，已保存本次分析，请重试。已支付的订单无需再付。','Unable to finish. Your analysis is saved; retry without paying again.','完了できません。分析は保存済みです。支払い済みの注文は再払い不要です。','완료하지 못했습니다. 분석은 저장됩니다. 결제한 주문은 다시 결제하지 마세요.','Analyse enregistrée. Réessayez sans payer à nouveau.','Analyse gespeichert. Erneut versuchen, nicht nochmals bezahlen.','Análisis guardado. Reintenta sin pagar de nuevo.','Análise salva. Tente novamente sem pagar outra vez.','حُفظ التحليل. أعد المحاولة دون الدفع مجددًا.'],
 expired:['这次分析已过期，请重新确认食物。','This analysis expired. Confirm your foods again.','期限切れです。食品を再確認してください。','분석이 만료되었습니다. 음식을 다시 확인하세요.','Analyse expirée. Confirmez les aliments à nouveau.','Analyse abgelaufen. Lebensmittel erneut bestätigen.','Análisis caducado. Confirma los alimentos de nuevo.','Análise expirada. Confirme os alimentos novamente.','انتهت صلاحية التحليل. أكد الأطعمة مجددًا.'],
 edit:['调整食物，开始新的分析','Edit foods for a new analysis','食品を変更して新しく分析','음식 수정 후 새 분석','Modifier pour une nouvelle analyse','Für neue Analyse bearbeiten','Editar para un nuevo análisis','Editar para nova análise','تعديل الأطعمة لتحليل جديد'],
};
export function foodBillingText(lang:LingxiLang,key:string){return rows[key]?.[languages.indexOf(lang)]||rows[key]?.[1]||key;}
