/* Display names only; never map these directly to nutrient records. */
export const FOOD_LABELS_ZH:Record<string,string>={
  "tacos": "墨西哥塔可",
  "chicken quesadilla": "鸡肉芝士夹饼",
  "falafel": "炸鹰嘴豆丸子",
  "ceviche": "酸橘汁腌鱼",
  "huevos rancheros": "墨西哥煎蛋",
  "cheese plate": "奶酪拼盘",
  "steak": "牛排",
  "beef tartare": "鞑靼牛肉",
  "filet mignon": "菲力牛排",
  "grilled salmon": "烤三文鱼",
  "apple pie": "苹果派",
  "baby back ribs": "烤猪肋排",
  "baklava": "巴克拉瓦酥点",
  "beef carpaccio": "意式生牛肉薄片",
  "beet salad": "甜菜沙拉",
  "beignets": "法式炸面团",
  "bibimbap": "韩式拌饭",
  "bread pudding": "面包布丁",
  "breakfast burrito": "早餐卷饼",
  "bruschetta": "意式烤面包",
  "caesar salad": "凯撒沙拉",
  "cannoli": "意式奶油卷",
  "caprese salad": "番茄芝士沙拉",
  "carrot cake": "胡萝卜蛋糕",
  "cheesecake": "芝士蛋糕",
  "chicken curry": "咖喱鸡",
  "chicken wings": "鸡翅",
  "chocolate cake": "巧克力蛋糕",
  "chocolate mousse": "巧克力慕斯",
  "churros": "西班牙油条",
  "clam chowder": "蛤蜊浓汤",
  "club sandwich": "总汇三明治",
  "crab cakes": "蟹肉饼",
  "creme brulee": "法式焦糖布丁",
  "croque madame": "法式煎蛋三明治",
  "cup cakes": "杯子蛋糕",
  "deviled eggs": "魔鬼蛋",
  "donuts": "甜甜圈",
  "dumplings": "饺子",
  "edamame": "毛豆",
  "eggs benedict": "班尼迪克蛋",
  "escargots": "法式焗蜗牛",
  "fish and chips": "炸鱼薯条",
  "foie gras": "鹅肝",
  "french fries": "薯条",
  "french onion soup": "法式洋葱汤",
  "french toast": "法式吐司",
  "fried calamari": "炸鱿鱼圈",
  "fried rice": "炒饭",
  "frozen yogurt": "冻酸奶",
  "garlic bread": "蒜香面包",
  "gnocchi": "意式土豆团子",
  "greek salad": "希腊沙拉",
  "grilled cheese sandwich": "烤芝士三明治",
  "guacamole": "牛油果酱",
  "gyoza": "日式煎饺",
  "hamburger": "汉堡",
  "hot and sour soup": "酸辣汤",
  "hot dog": "热狗",
  "hummus": "鹰嘴豆泥",
  "ice cream": "冰淇淋",
  "lasagna": "千层面",
  "lobster bisque": "龙虾浓汤",
  "lobster roll sandwich": "龙虾卷",
  "macaroni and cheese": "芝士通心粉",
  "macarons": "马卡龙",
  "miso soup": "味噌汤",
  "mussels": "贻贝",
  "nachos": "墨西哥玉米片",
  "omelette": "煎蛋卷",
  "onion rings": "洋葱圈",
  "oysters": "牡蛎",
  "pad thai": "泰式炒河粉",
  "paella": "西班牙海鲜饭",
  "pancakes": "美式松饼",
  "panna cotta": "意式奶冻",
  "peking duck": "北京烤鸭",
  "pho": "越南河粉",
  "pizza": "披萨",
  "pork chop": "猪排",
  "poutine": "肉汁芝士薯条",
  "prime rib": "烤牛肋排",
  "pulled pork sandwich": "手撕猪肉三明治",
  "ramen": "拉面",
  "ravioli": "意式饺子",
  "red velvet cake": "红丝绒蛋糕",
  "risotto": "意式烩饭",
  "samosa": "咖喱角",
  "sashimi": "刺身",
  "scallops": "扇贝",
  "seaweed salad": "海藻沙拉",
  "shrimp and grits": "虾配玉米粥",
  "spaghetti bolognese": "肉酱意面",
  "spaghetti carbonara": "培根蛋酱意面",
  "spring rolls": "春卷",
  "strawberry shortcake": "草莓奶油蛋糕",
  "sushi": "寿司",
  "takoyaki": "章鱼烧",
  "tiramisu": "提拉米苏",
  "tuna tartare": "金枪鱼鞑靼",
  "waffles": "华夫饼"
};
export function foodLabel(label:string,zh:boolean){return zh?(FOOD_LABELS_ZH[label]??label):label}
