import "server-only";
import crypto from"node:crypto";import{createAdminClient}from"@/lib/supabase/admin";import{decryptProviderKey,validByokProvider,type ByokProvider}from"@/lib/sasi/credential-vault";import{validateProviderBaseUrl}from"@/lib/sasi/gateway/ssrf-guard";
export type Capability="text.generate"|"text.reason"|"vision.understand"|"image.generate"|"image.edit"|"audio.transcribe"|"audio.synthesize"|"video.generate"|"text.embed"|"rerank";
export type CapabilityRequest={capability:Capability;input:string;model?:string;provider?:string;system?:string;temperature?:number;maxOutputTokens?:number;userId?:string|null};
export type CapabilityResult={ok:true;text?:string;data?:unknown;provider:string;model:string;usage?:Record<string,number>;requestId:string}|{ok:false;code:string;message:string;requestId:string};
type Conn={id:string;provider:ByokProvider;baseUrl:string;apiKey:string;model:string;displayName:string};
const env=(k:string)=>String(process.env[k]||"").trim(),rid=()=>crypto.randomUUID();
const defaults:Record<string,{base:string;model:string;key:string}>={openai:{base:"https://api.openai.com/v1",model:env("OPENAI_MODEL")||"gpt-5.6",key:env("OPENAI_API_KEY")},deepseek:{base:env("DEEPSEEK_BASE_URL")||"https://api.deepseek.com",model:env("DEEPSEEK_MODEL")||"deepseek-chat",key:env("DEEPSEEK_API_KEY")},xai:{base:env("XAI_BASE_URL")||"https://api.x.ai/v1",model:env("XAI_MODEL")||"grok-4",key:env("XAI_API_KEY")},openrouter:{base:"https://openrouter.ai/api/v1",model:env("OPENROUTER_MODEL")||"openai/gpt-5.6",key:env("OPENROUTER_API_KEY")}};
function safeBase(raw:string){const g=validateProviderBaseUrl(raw);if(!g.pass||!g.normalized)throw new Error("PROVIDER_URL_REJECTED");return g.normalized.replace(/\/$/,"")}
async function personal(userId:string):Promise<Conn[]>{const a=createAdminClient(),{data}=await a.from("sasi_provider_connections").select("id,provider,encrypted_credential,display_name,base_url,model_id,enabled").eq("user_id",userId).eq("enabled",true).order("updated_at",{ascending:false});const out:Conn[]=[];for(const x of data||[]){if(!validByokProvider(x.provider))continue;try{out.push({id:x.id,provider:x.provider,apiKey:decryptProviderKey(userId,x.provider,x.encrypted_credential),baseUrl:String(x.base_url||defaults[x.provider]?.base||""),model:String(x.model_id||defaults[x.provider]?.model||""),displayName:String(x.display_name||x.provider)})}catch{}}return out}
function site():Conn[]{return Object.entries(defaults).filter(([,x])=>x.key).map(([provider,x])=>({id:`site:${provider}`,provider:provider as ByokProvider,baseUrl:x.base,apiKey:x.key,model:x.model,displayName:provider}))}
async function openAI(c:Conn,r:CapabilityRequest,id:string):Promise<CapabilityResult>{if(!["text.generate","text.reason","vision.understand"].includes(r.capability))throw new Error("CAPABILITY_NOT_SUPPORTED");const base=safeBase(c.baseUrl),model=r.model||c.model;if(!model)throw new Error("MODEL_REQUIRED");const res=await fetch(`${base}/chat/completions`,{method:"POST",cache:"no-store",signal:AbortSignal.timeout(45000),headers:{authorization:`Bearer ${c.apiKey}`,"content-type":"application/json",...(c.provider==="openrouter"?{"HTTP-Referer":"https://lingxifield.com","X-OpenRouter-Title":"LINGXIFIELD"}:{})},body:JSON.stringify({model,messages:[...(r.system?[{role:"system",content:r.system}]:[]),{role:"user",content:r.input}],temperature:r.temperature,max_tokens:r.maxOutputTokens})});const b:any=await res.json().catch(()=>({}));if(!res.ok)throw new Error(`UPSTREAM_${res.status}`);return{ok:true,text:String(b?.choices?.[0]?.message?.content||""),provider:c.displayName,model,usage:b?.usage,requestId:id}}
export async function runCapability(r:CapabilityRequest):Promise<CapabilityResult>{const id=rid();if(!r.input?.trim())return{ok:false,code:"INVALID_REQUEST",message:"没有读到需要处理的内容。",requestId:id};const all=[...(r.userId?await personal(r.userId):[]),...site()],picked=r.provider?all.filter(x=>x.provider===r.provider||x.id===r.provider):all;if(!picked.length)return{ok:false,code:"NO_SERVICE_CONNECTED",message:"当前没有可用的智能服务连接。",requestId:id};for(const c of picked){try{return await openAI(c,r,id)}catch{continue}}return{ok:false,code:"ALL_CONNECTIONS_UNAVAILABLE",message:"当前连接暂时不可用，请稍后再试。",requestId:id}}
export async function connectionStatus(userId?:string|null){const mine=userId?await personal(userId):[];return[...mine,...site()].map(x=>({id:x.id,name:x.displayName,provider:x.provider,model:x.model,personal:!x.id.startsWith("site:"),available:true}))}
