import crypto from"node:crypto";
export type Capability="text.generate"|"text.reason"|"vision.understand"|"image.generate"|"image.edit"|"audio.transcribe"|"audio.synthesize"|"video.generate"|"embed"|"rerank";
export type GatewayRequest={capability:Capability;input:string;model?:string;provider?:string;system?:string;temperature?:number;maxOutputTokens?:number;metadata?:Record<string,unknown>};
export type GatewayResult={ok:true;text?:string;data?:unknown;provider:string;model:string;usage?:Record<string,number>;requestId:string}|{ok:false;code:string;message:string;requestId:string};
type Provider={id:string;kind:"openai-compatible"|"gemini";baseURL:string;apiKey?:string;defaultModel:string;capabilities:Capability[];headers?:Record<string,string>};
const ALL_TEXT:Capability[]=["text.generate","text.reason","vision.understand"];
const env=(k:string)=>String(process.env[k]||"").trim();
const REGISTRY:Provider[]=[
{id:"openai",kind:"openai-compatible",baseURL:"https://api.openai.com/v1",apiKey:env("OPENAI_API_KEY"),defaultModel:env("OPENAI_MODEL")||"gpt-5.6",capabilities:ALL_TEXT},
{id:"anthropic",kind:"openai-compatible",baseURL:env("ANTHROPIC_OPENAI_BASE_URL")||"https://api.anthropic.com/v1",apiKey:env("ANTHROPIC_API_KEY"),defaultModel:env("ANTHROPIC_MODEL")||"claude-sonnet-4-6",capabilities:ALL_TEXT},
{id:"deepseek",kind:"openai-compatible",baseURL:env("DEEPSEEK_BASE_URL")||"https://api.deepseek.com",apiKey:env("DEEPSEEK_API_KEY"),defaultModel:env("DEEPSEEK_MODEL")||"deepseek-chat",capabilities:ALL_TEXT},
{id:"xai",kind:"openai-compatible",baseURL:env("XAI_BASE_URL")||"https://api.x.ai/v1",apiKey:env("XAI_API_KEY"),defaultModel:env("XAI_MODEL")||"grok-4",capabilities:ALL_TEXT},
{id:"openrouter",kind:"openai-compatible",baseURL:"https://openrouter.ai/api/v1",apiKey:env("OPENROUTER_API_KEY"),defaultModel:env("OPENROUTER_MODEL")||"openai/gpt-5.6",capabilities:ALL_TEXT,headers:{"HTTP-Referer":"https://lingxifield.com","X-OpenRouter-Title":"LINGXIFIELD"}},
{id:"gemini",kind:"gemini",baseURL:"https://generativelanguage.googleapis.com/v1beta",apiKey:env("GEMINI_API_KEY"),defaultModel:env("GEMINI_MODEL")||"gemini-3.5-flash",capabilities:ALL_TEXT},
];
function requestId(){return crypto.randomUUID()}
function timeoutSignal(ms=45000){return AbortSignal.timeout(Math.max(1000,Math.min(ms,120000)))}
function safeBase(raw:string){const u=new URL(raw);if(u.protocol!=="https:")throw new Error("HTTPS_REQUIRED");const h=u.hostname.toLowerCase();if(h==="localhost"||h.endsWith(".local")||/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)||h==="::1")throw new Error("PRIVATE_NETWORK_BLOCKED");return u.origin+u.pathname.replace(/\/$/,"")}
function candidates(req:GatewayRequest){const configured=REGISTRY.filter(p=>p.apiKey&&p.capabilities.includes(req.capability));if(req.provider)return configured.filter(p=>p.id===req.provider);const pref=(env("LINGXIFIELD_PROVIDER_ORDER")||"openai,gemini,anthropic,deepseek,xai,openrouter").split(",").map(x=>x.trim());return configured.sort((a,b)=>pref.indexOf(a.id)-pref.indexOf(b.id))}
async function openAI(p:Provider,req:GatewayRequest,id:string):Promise<GatewayResult>{const base=safeBase(p.baseURL),model=req.model||p.defaultModel,r=await fetch(`${base}/chat/completions`,{method:"POST",signal:timeoutSignal(),headers:{authorization:`Bearer ${p.apiKey}`,"content-type":"application/json",...(p.headers||{})},body:JSON.stringify({model,messages:[...(req.system?[{role:"system",content:req.system}]:[]),{role:"user",content:req.input}],temperature:req.temperature,max_tokens:req.maxOutputTokens})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`UPSTREAM_${r.status}`);const text=String(b?.choices?.[0]?.message?.content||"");return{ok:true,text,provider:p.id,model,usage:b?.usage,requestId:id}}
async function gemini(p:Provider,req:GatewayRequest,id:string):Promise<GatewayResult>{const base=safeBase(p.baseURL),model=req.model||p.defaultModel,r=await fetch(`${base}/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",signal:timeoutSignal(),headers:{"x-goog-api-key":p.apiKey!,"content-type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:req.input}]}],...(req.system?{systemInstruction:{parts:[{text:req.system}]}}:{}),generationConfig:{temperature:req.temperature,maxOutputTokens:req.maxOutputTokens}})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`UPSTREAM_${r.status}`);const text=(b?.candidates?.[0]?.content?.parts||[]).map((x:any)=>x?.text||"").join("");return{ok:true,text,provider:p.id,model,usage:b?.usageMetadata,requestId:id}}
export async function runCapability(req:GatewayRequest):Promise<GatewayResult>{const id=requestId();if(!req?.capability||typeof req.input!=="string"||!req.input.trim())return{ok:false,code:"INVALID_REQUEST",message:"没有读到需要处理的内容。",requestId:id};const ps=candidates(req);if(!ps.length)return{ok:false,code:"NO_SERVICE_CONNECTED",message:"当前没有可用的智能服务连接。",requestId:id};let last="";for(const p of ps){try{return p.kind==="gemini"?await gemini(p,req,id):await openAI(p,req,id)}catch(e:any){last=String(e?.message||"UPSTREAM_FAILED");continue}}return{ok:false,code:"ALL_CONNECTIONS_UNAVAILABLE",message:"当前连接暂时不可用，请稍后再试。",requestId:id}}
export function gatewayStatus(){return REGISTRY.map(p=>({id:p.id,connected:Boolean(p.apiKey),capabilities:p.capabilities,model:p.defaultModel}))}
