import type {EngineDescriptor} from "./types";
import {LICENSE_REGISTRY as L} from "./license-registry";

const e=(x:EngineDescriptor)=>x;
export const ENGINE_CATALOG:EngineDescriptor[]=[
 e({id:"native-js",label:"Browser / Node native",domain:"utility",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["browser-native"],source:"runtime",capabilities:["text","json","encoding","hash","time","dedupe-lines","remove-empty-lines","url-codec","base64","file-compare","file-signature","csv","pptx-text","subtitle-parse","subtitle-shift","text-redact"]}),
 e({id:"browser-canvas",label:"Canvas / WebCodecs",domain:"image",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["browser-native"],source:"browser",capabilities:["image-decode","image-encode","resize","compress","preview","metadata-strip","svg-render","stitch","redact","crop","background-compose"]}),
 e({id:"sharp-libvips",label:"Sharp / libvips",domain:"image",privacy:"self-hosted",runtime:"node-module",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/lovell/sharp",capabilities:["image-convert","image-decode","image-encode","resize","compress","metadata","metadata-strip","avif","webp","jpeg","png"]}),
 e({id:"heic2any",label:"heic2any",domain:"image",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["mit"],source:"https://github.com/alexcorvi/heic2any",capabilities:["heic-decode","heif-decode"]}),
 e({id:"libheif",label:"libheif",domain:"image",privacy:"self-hosted",runtime:"node-command",licenseRisk:"review",license:L["libheif-review"],source:"https://github.com/strukturag/libheif",capabilities:["heic","heif","avif"],commandEnv:"LINGXI_LIBHEIF_BIN",defaultCommand:"heif-convert"}),
 e({id:"real-esrgan",label:"Real-ESRGAN",domain:"image",privacy:"self-hosted",runtime:"python",licenseRisk:"review",license:L["realesrgan-review"],source:"https://github.com/xinntao/Real-ESRGAN",capabilities:["upscale","restore","denoise"]}),
 e({id:"gfpgan",label:"GFPGAN",domain:"image",privacy:"self-hosted",runtime:"python",licenseRisk:"review",license:L["gfpgan-review"],source:"https://github.com/TencentARC/GFPGAN",capabilities:["face-restore"]}),
 e({id:"opencv",label:"OpenCV",domain:"vision",privacy:"self-hosted",runtime:"python",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/opencv/opencv",capabilities:["crop","perspective","inpaint","redact","tracking","document-detect","deskew","threshold"]}),
 e({id:"mediapipe",label:"MediaPipe",domain:"vision",privacy:"self-hosted",runtime:"python",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/google-ai-edge/mediapipe",capabilities:["face-detect","portrait-segmentation","landmarks"]}),
 e({id:"paddleocr",label:"PaddleOCR",domain:"vision",privacy:"self-hosted",runtime:"python",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/PaddlePaddle/PaddleOCR",capabilities:["ocr","layout","table","orientation","seal"]}),
 e({id:"tesseractjs",label:"Tesseract.js",domain:"vision",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/naptha/tesseract.js",capabilities:["ocr"]}),
 e({id:"pdfjs",label:"PDF.js",domain:"pdf",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/mozilla/pdf.js",capabilities:["pdf-parse","pdf-render","pdf-text","preview"]}),
 e({id:"pdflib",label:"pdf-lib",domain:"pdf",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["mit"],source:"https://github.com/Hopding/pdf-lib",capabilities:["pdf-build","merge","split","edit","sign","stamp","page-manage","metadata"]}),
 e({id:"qpdf",label:"qpdf",domain:"pdf",privacy:"self-hosted",runtime:"node-command",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/qpdf/qpdf",capabilities:["pdf-check","structure-optimize","linearize","repair","encrypt"],commandEnv:"LINGXI_QPDF_BIN",defaultCommand:"qpdf",versionArgs:["--version"]}),
 e({id:"pdfcpu",label:"pdfcpu",domain:"pdf",privacy:"self-hosted",runtime:"node-command",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/pdfcpu/pdfcpu",capabilities:["pdf-validate","optimize","merge","split","rotate","watermark","stamp","extract"],commandEnv:"LINGXI_PDFCPU_BIN",defaultCommand:"pdfcpu",versionArgs:["version"]}),
 e({id:"jszip",label:"JSZip",domain:"document",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["mit"],source:"https://github.com/Stuk/jszip",capabilities:["zip-read","pptx-text","archive"]}),
 e({id:"mammoth",label:"Mammoth",domain:"document",privacy:"self-hosted",runtime:"node-module",licenseRisk:"allow",license:L["bsd2"],source:"https://github.com/mwilliamson/mammoth.js",capabilities:["docx-to-html","docx-to-text"]}),
 e({id:"exceljs",label:"ExcelJS",domain:"document",privacy:"self-hosted",runtime:"node-module",licenseRisk:"allow",license:L["mit"],source:"https://github.com/exceljs/exceljs",capabilities:["xlsx-read","xlsx-write","csv","streaming-workbook"]}),
 e({id:"ffmpeg",label:"FFmpeg",domain:"media",privacy:"self-hosted",runtime:"node-command",licenseRisk:"review",license:L["ffmpeg-review"],source:"https://ffmpeg.org",capabilities:["transcode","trim","compress","extract-audio","mux","subtitle"],commandEnv:"LINGXI_FFMPEG_BIN",defaultCommand:"ffmpeg",versionArgs:["-version"]}),
 e({id:"whispercpp",label:"whisper.cpp",domain:"media",privacy:"self-hosted",runtime:"node-command",licenseRisk:"allow",license:L["mit"],source:"https://github.com/ggml-org/whisper.cpp",capabilities:["speech-to-text","timestamps"],commandEnv:"LINGXI_WHISPER_BIN",defaultCommand:"whisper-cli",versionArgs:["--help"]}),
 e({id:"faster-whisper",label:"faster-whisper",domain:"media",privacy:"self-hosted",runtime:"python",licenseRisk:"allow",license:L["mit"],source:"https://github.com/SYSTRAN/faster-whisper",capabilities:["speech-to-text","timestamps","batched-transcription"]}),
 e({id:"argos",label:"Argos Translate",domain:"media",privacy:"self-hosted",runtime:"python",licenseRisk:"allow",license:L["mit"],source:"https://github.com/argosopentech/argos-translate",capabilities:["offline-translation"]}),
 e({id:"kokoro",label:"Kokoro TTS",domain:"media",privacy:"self-hosted",runtime:"python",licenseRisk:"review",license:L["kokoro-review"],source:"https://github.com/hexgrad/kokoro",capabilities:["text-to-speech"]}),
 e({id:"readability",label:"Mozilla Readability",domain:"web",privacy:"self-hosted",runtime:"node-module",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/mozilla/readability",capabilities:["article-extract"]}),
 e({id:"dompurify",label:"DOMPurify",domain:"web",privacy:"self-hosted",runtime:"node-module",licenseRisk:"allow",license:L["apache2-or-mpl2"],source:"https://github.com/cure53/DOMPurify",capabilities:["sanitize-html"]}),
 e({id:"turndown",label:"Turndown",domain:"web",privacy:"self-hosted",runtime:"node-module",licenseRisk:"allow",license:L["mit"],source:"https://github.com/mixmark-io/turndown",capabilities:["html-to-markdown"]}),
 e({id:"gotenberg",label:"Gotenberg",domain:"document",privacy:"self-hosted",runtime:"http-service",licenseRisk:"review",license:L["gotenberg-review"],source:"https://github.com/gotenberg/gotenberg",capabilities:["url-to-pdf","html-to-pdf","office-to-pdf","screenshot"]}),
 e({id:"exiftool",label:"ExifTool",domain:"privacy",privacy:"self-hosted",runtime:"node-command",licenseRisk:"review",license:L["exiftool-review"],source:"https://github.com/exiftool/exiftool",capabilities:["metadata-inspect","metadata-remove"],commandEnv:"LINGXI_EXIFTOOL_BIN",defaultCommand:"exiftool",versionArgs:["-ver"]}),
 e({id:"opencc",label:"OpenCC",domain:"search",privacy:"self-hosted",runtime:"node-command",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/BYVoid/OpenCC",capabilities:["simplified-traditional-normalize"],commandEnv:"LINGXI_OPENCC_BIN",defaultCommand:"opencc",versionArgs:["--version"]}),
 e({id:"jieba",label:"jieba",domain:"search",privacy:"self-hosted",runtime:"python",licenseRisk:"allow",license:L["mit"],source:"https://github.com/fxsjy/jieba",capabilities:["chinese-tokenize","search-tokenize"]}),
 e({id:"tantivy",label:"Tantivy",domain:"search",privacy:"self-hosted",runtime:"node-command",licenseRisk:"allow",license:L["mit"],source:"https://github.com/quickwit-oss/tantivy",capabilities:["fulltext-index","bm25","tokenizers"]}),
 e({id:"usda-fdc",label:"USDA FoodData Central",domain:"nutrition",privacy:"first-party-db",runtime:"database",licenseRisk:"allow",license:L["usda-cc0"],source:"https://fdc.nal.usda.gov",capabilities:["food-search","macros","micronutrients","portions","branded-foods"]}),
 e({id:"nutrition5k",label:"Nutrition5k",domain:"nutrition",privacy:"self-hosted",runtime:"database",licenseRisk:"allow",license:L["nutrition5k"],source:"https://github.com/google-research-datasets/Nutrition5k",capabilities:["meal-images","ingredient-weight","nutrition-research"]}),
 e({id:"webcrypto",label:"Web Crypto",domain:"privacy",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["browser-native"],source:"browser",capabilities:["sha256","encryption","key-derivation"]}),
 e({id:"jsqr",label:"jsQR",domain:"vision",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["apache2"],source:"https://github.com/cozmo/jsQR",capabilities:["qr-decode"]}),
 e({id:"qrcode",label:"node-qrcode",domain:"utility",privacy:"local-browser",runtime:"browser",licenseRisk:"allow",license:L["mit"],source:"https://github.com/soldair/node-qrcode",capabilities:["qr-generate"]}),
];

export const BLOCKED_BY_DEFAULT=[
 {id:"ghostscript",reason:"AGPL/commercial dual-license family; require explicit commercial review."},
 {id:"mupdf-pymupdf",reason:"AGPL/commercial dual-license family; not accepted as default closed-service dependency."},
 {id:"ultralytics-yolo",reason:"AGPL/enterprise dual-license family; explicit license review required."},
];
export function engineById(id:string){return ENGINE_CATALOG.find(x=>x.id===id)}
