import "server-only";
import{createHmac,randomUUID,timingSafeEqual}from"node:crypto";
const MAX_CLOCK_SKEW_MS=5*60_000;
function env(name:string){return process.env[name]?.trim()??""}
function isLocal(host:string){return host==="localhost"||host==="127.0.0.1"||host==="::1"}
export function workerBaseUrl(){const raw=env("SASI_COMPUTE_WORKER_URL").replace(/\/$/,"");if(!raw)return"";const url=new URL(raw);if(url.username||url.password)throw new Error("SASI_WORKER_URL_CREDENTIALS_FORBIDDEN");if(url.protocol!=="https:"&&!isLocal(url.hostname))throw new Error("SASI_WORKER_HTTPS_REQUIRED");const allowed=new Set(env("SASI_COMPUTE_WORKER_ALLOWED_HOSTS").split(",").map((x:string)=>x.trim().toLowerCase()).filter(Boolean));if(!isLocal(url.hostname)&&allowed.size===0)throw new Error("SASI_WORKER_ALLOWLIST_REQUIRED");if(!isLocal(url.hostname)&&!allowed.has(url.hostname.toLowerCase()))throw new Error("SASI_WORKER_HOST_FORBIDDEN");return raw}
export function workerSecret(){const secret=env("SASI_COMPUTE_WORKER_SECRET");if(secret.length<32)throw new Error("SASI_WORKER_SECRET_TOO_SHORT");return secret}
export function signedWorkerHeaders(body:string,now=Date.now()){const timestamp=String(now),nonce=randomUUID(),payload=`${timestamp}.${nonce}.${body}`,signature=createHmac("sha256",workerSecret()).update(payload).digest("hex");return{"content-type":"application/json","x-sasi-timestamp":timestamp,"x-sasi-nonce":nonce,"x-sasi-signature":signature};}
export function verifyWorkerSignature(input:{body:string;timestamp:string;nonce:string;signature:string;now?:number}){const now=input.now??Date.now(),ts=Number(input.timestamp);if(!Number.isFinite(ts)||Math.abs(now-ts)>MAX_CLOCK_SKEW_MS)return false;if(!/^[0-9a-f-]{36}$/i.test(input.nonce)||!/^[0-9a-f]{64}$/i.test(input.signature))return false;const expected=createHmac("sha256",workerSecret()).update(`${input.timestamp}.${input.nonce}.${input.body}`).digest("hex"),a=Buffer.from(expected,"hex"),b=Buffer.from(input.signature,"hex");return a.length===b.length&&timingSafeEqual(a,b)}
