import type { LivingChapterSpec, ReportProductKey } from "./types";

const mk = (
  product:ReportProductKey,
  rows:Array<[string,string,string,string[],LivingChapterSpec["realityDomains"]]>
):LivingChapterSpec[] =>
  rows.map(([title,question,resolves,dims,domains],i)=>({
    id:`${product}-${String(i+1).padStart(2,"0")}`,
    product,titleZh:title,question,resolves,
    minIndependentContexts: 2,
    requiredDimensions: dims,
    optionalDimensions: [],
    realityDomains: domains,
  }));

export const LIVING_REPORT_SPECS:Record<ReportProductKey,LivingChapterSpec[]> = {
  "life-map": mk("life-map", [
    ["生命底色","无人催迫时，你自然如何活？","把“角色中的我”和“本来的我”分开。",["natural_state"],["daily","work"]],
    ["本源驱动","什么真正令你长期愿意投入？","区分真实驱动与恐惧、责任、惯性。",["drive"],["work","creation"]],
    ["感知门户","世界首先从哪里进入你？","知道你先看见什么，也知道自己容易漏看什么。",["perception"],["decision","relationship"]],
    ["判断成形","你如何从所见走到决定？","找到拖延、冲动或过度求证发生在哪一步。",["judgment"],["decision"]],
    ["行动脉络","一念如何真正落到现实？","找出“知道却没做”的断点。",["activation"],["work","creation"]],
    ["内外错位","现实角色在哪里违背你的自然节律？","识别长期耗损来自何种角色错位。",["role"],["work","relationship"]],
    ["承载之器","什么真正托得住你的能力？","辨认能做成事的现实底座。",["capacity"],["work","daily"]],
    ["未发之能","什么能力已有其根，却尚无其位？","找出被低估、未被现实调用的力量。",["latent"],["creation","work"]],
    ["生命张力","哪两股力量同时很强，却难以并行？","找到反复内耗的根轴。",["tension"],["decision","relationship"]],
    ["当前转轴","此刻动哪里，最可能牵动全局？","把改变集中在高杠杆处。",["pivot"],["daily","decision"]],
    ["第二生路","若旧角色不再要求你证明自己，会长出什么？","看见不是幻想，而是已有证据支持的第二路径。",["second_path"],["creation","work"]],
  ]),
  "relationship-deep": mk("relationship-deep", [
    ["相遇之因","二人为何会彼此识别？","看清吸引是共鸣、互补还是旧缺口。",["attraction"],["relationship"]],
    ["靠近之法","亲近如何真正发生？","知道双方用什么方式表达靠近。",["approach"],["relationship"]],
    ["依恋节律","谁追、谁退、何时换位？","看见关系最常重复的动力循环。",["attachment"],["relationship"]],
    ["需求暗线","真正所求与嘴上所说是否一致？","避免彼此都在给，却谁也没得到。",["need"],["relationship"]],
    ["表达错位","所给为何常非对方所受？","定位沟通失败的具体接口。",["expression"],["relationship"]],
    ["边界结构","近到何处会开始失己？","找到亲密与自主的适宜距离。",["boundary"],["boundary","relationship"]],
    ["冲突原点","争端真正保护的是什么？","把表面争吵还原到真实触发。",["conflict"],["relationship"]],
    ["修复能力","受伤以后能否重新相接？","区分道歉、停战与真正修复。",["repair"],["relationship"]],
    ["未说之事","什么长期存在却未进入语言？","让沉默中的需要获得可讨论位置。",["unsaid"],["relationship"]],
    ["关系代价","维系此缘正在牺牲什么？","核算关系真实成本。",["cost"],["relationship","work"]],
    ["关系去向","若结构不变，它自然会走向哪里？","给继续、重建或止步以现实条件。",["direction"],["relationship"]],
  ]),
  "relationship-business": mk("relationship-business", [
    ["结盟基础","何事足以使二人共事？","辨联盟是价值同向还是资源暂时相合。",["alliance"],["work","money"]],
    ["共同利益","双方所得是否真的同向？","提前发现未来最容易分裂的利益点。",["interest"],["money","work"]],
    ["权责结构","谁主何事，谁承何责？","消除权力模糊与责任漂移。",["role"],["work"]],
    ["决策主导","异议出现时决定如何形成？","建立能穿越分歧的决策机制。",["decision"],["decision","work"]],
    ["风险承担","成败由谁真正付代价？","防止收益共享、风险单边。",["risk"],["money","work"]],
    ["资源交换","人财时与能力如何互换？","看清贡献能否被公平计价。",["resource"],["money","work"]],
    ["信任形成","信任因何立、因何损？","从口头好感转到可验证合作。",["trust"],["work"]],
    ["利益冲突","钱、权、功劳冲突时如何处理？","提前识别最危险的破局点。",["conflict"],["money","work"]],
    ["危机站位","事急之时各守何位？","看见真正的共担与甩责。",["crisis"],["work"]],
    ["长期合作成本","这段合作久行所费为何？","判断赚钱是否仍值得继续。",["cost"],["money","work"]],
    ["继续·重组·退出","何时该留、该改、该止？","把感情判断变为治理条件。",["exit"],["decision","work"]],
  ]),
  "relationship-other": mk("relationship-other", [
    ["关系起点","此缘因何而生？","辨清真实连接与角色惯性。",["origin"],["relationship"]],
    ["角色位置","彼此默认扮演什么？","发现从未协商却长期承担的角色。",["role"],["relationship"]],
    ["自然距离","多近不伤，多远不失？","找到适宜距离而非强求更近。",["distance"],["relationship","boundary"]],
    ["给予与接收","所予是否被受，所需是否能得？","识别长期单向情感劳动。",["reciprocity"],["relationship"]],
    ["期待来源","期待来自当下还是旧关系？","拆掉“你应该懂”的隐性契约。",["expectation"],["relationship"]],
    ["边界摩擦","帮助何时越成代替承担？","分清关心与侵入。",["boundary"],["boundary","relationship"]],
    ["未尽之言","什么一直没有说完？","定位沉默留下的关系债。",["unsaid"],["relationship"]],
    ["关系惯性","为何明知无效仍重复？","找出旧互动的自运行机制。",["inertia"],["relationship"]],
    ["现实牵连","情分之外还牵着什么？","看清金钱、工作、家庭等真实约束。",["entanglement"],["money","work","relationship"]],
    ["可修复之处","哪里仍有真实可动空间？","避免把所有关系都写成“需要沟通”。",["repair"],["relationship"]],
    ["适宜距离","这段关系最健康的位置是什么？","允许疏、近、重构或结束。",["distance_fit"],["relationship","boundary"]],
  ]),
  "resilience": mk("resilience", [
    ["韧性源点","受冲时何力使你不散？","找到真正可靠的恢复资源。",["source"],["stress"]],
    ["压力初反应","压力初至，先动何处？","建立个人预警信号。",["initial"],["stress","daily"]],
    ["失衡顺序","系统怎样一步步失去可用性？","在崩溃前找到最早可截断处。",["imbalance"],["stress"]],
    ["恢复入口","什么能让第一点可用能量回来？","避免用意志硬拖。",["recovery"],["stress","daily"]],
    ["危机启动","真正低谷时靠什么重新起身？","找到重启而非强撑。",["rebound"],["stress"]],
    ["变化适应","旧计划失效后如何重新定向？","看见适应不是速度，而是换路不失向。",["adaptability"],["decision","stress"]],
    ["长期坚持","没有反馈时何物使你继续？","区分价值持续与惯性死撑。",["endurance"],["work","stress"]],
    ["稳定承载","复起之后能否真正站稳？","识别恢复后的二次崩落风险。",["stability"],["daily","stress"]],
    ["反弹代价","你每次‘撑回来’付了什么？","把隐性恢复成本算进人生。",["cost"],["stress","work"]],
    ["脆弱断点","哪一点一断，全局最易散？","锁定需要优先保护的支点。",["fragility"],["stress"]],
    ["再生路径","怎样回来最符合你，而非别人？","形成可重复的个人恢复路径。",["regeneration"],["daily","stress"]],
  ]),
  "romance": mk("romance", [
    ["吸引源","何处未经经营而自有吸引？","识别真实魅力来源。",["attraction"],["relationship"]],
    ["被看见的部分","别人最先接到你哪一面？","区分外显形象与真实本体。",["visibility"],["relationship"]],
    ["隐藏吸引力","何力已有却未显形？","找到未被使用的关系资本。",["hidden"],["relationship"]],
    ["主动与被动","好感如何发出，又如何接住？","识别关系信号错失。",["signal"],["relationship"]],
    ["靠近门槛","什么确认足以开门？","辨认过高或过低的进入阈值。",["threshold"],["relationship"]],
    ["筛选机制","什么是真标准，什么是防御？","减少用恐惧伪装成择偶标准。",["selection"],["relationship"]],
    ["重复对象","为何总被某一类人吸引？","看见重复不是命，是熟悉感在选人。",["repeat"],["relationship"]],
    ["暧昧结构","为何有情却迟迟不落地？","找出模糊关系维持的利益与恐惧。",["ambiguity"],["relationship"]],
    ["错配来源","相引为何不能相承？","定位感觉与现实适配断层。",["mismatch"],["relationship"]],
    ["关系进入条件","什么出现才算真正开始？","把化学反应转为现实关系条件。",["entry"],["relationship"]],
    ["磁场转轴","动哪一点会改变下一次选择？","找出重复模式真正可改之处。",["pivot"],["relationship"]],
  ]),
  "wealth": mk("wealth", [
    ["财富源点","钱最稳定从何处来？","找到可复用的价值源。",["source"],["money","work"]],
    ["价值发生","何事经你之手而增值？","让能力从自我评价变成可交换价值。",["value"],["money","creation"]],
    ["创造方式","价值怎样被做成结果？","识别最适合的创造路径。",["creation"],["work","creation"]],
    ["机会识别","何机可取，何机当舍？","避免把所有可能都当机会。",["opportunity"],["money","decision"]],
    ["资源调度","有限资源怎样依序入位？","找到规模前真正的瓶颈。",["resource"],["money","work"]],
    ["交换能力","你能否明确报价与谈条件？","识别价值创造到收入之间的断口。",["exchange"],["money"]],
    ["接收能力","所得增加后能否真正承住？","看见高收入后的不安、挥霍或过度扩张。",["receiving"],["money"]],
    ["风险方式","冒险何时成进，何时成耗？","建立与自身结构匹配的风险边界。",["risk"],["money","decision"]],
    ["财富泄口","所创之财从哪里无声流失？","定位钱真正漏掉的地方。",["leak"],["money"]],
    ["放大杠杆","何力可一次建立、反复生效？","从卖时间走向可积累结构。",["leverage"],["money","creation"]],
    ["下一阶段财富路径","下一年只建一套什么系统？","把愿望收束为可执行财富主轴。",["next"],["money","work"]],
  ]),
  "daily-tide": mk("daily-tide", [
    ["今日主潮","今日诸力总体向何处流？","先决定今天该进还是该收。",["main"],["daily"]],
    ["晨起之势","醒后第一股力如何？","避免上午误判全天。",["morning"],["daily"]],
    ["感知窗口","何时宜察而不急断？","选择适合收集信息的时段。",["perception"],["decision","daily"]],
    ["判断窗口","何时判断较明？","避免在急迫或疲惫中作不可逆决定。",["decision"],["decision","daily"]],
    ["行动窗口","何时一动最易成事？","把有限精力放在真正可推进处。",["action"],["daily","work"]],
    ["关系潮位","今天有多少余量给别人？","防止在低余量时过度承诺。",["relationship"],["relationship","daily"]],
    ["财富潮位","今天适合算、收、谈还是缓？","让金钱行动匹配当日状态。",["money"],["money","daily"]],
    ["压力潮位","今日哪里最易过载？","提前避开最可能耗散的接口。",["stress"],["stress","daily"]],
    ["宜进","今天哪一件事顺势可进？","只留一个真正值得推进的动作。",["advance"],["daily"]],
    ["宜止","什么再推只会加耗？","给停止以正当位置。",["pause"],["daily"]],
    ["今日归位","何事能令今日完整结束？","避免余波拖到明日。",["return"],["daily"]],
  ]),
  "life-mirror": mk("life-mirror", [
    ["镜中之事","事实到底发生了什么？","先把事实从解释中分出。",["fact"],["decision"]],
    ["显层问题","你嘴上在问什么？","把泛问题收成一个可处理命题。",["visible"],["decision"]],
    ["隐层牵引","真正让你放不下的是什么？","看见结果、关系、身份或控制的暗线。",["hidden"],["decision","relationship"]],
    ["重复之因","旧事为何借新境重来？","定位循环入口。",["repeat"],["relationship","decision"]],
    ["被忽略的事实","眼前有什么一直未计入？","把被情绪遮住的证据带回来。",["neglected"],["decision"]],
    ["情绪所护","这份情绪在保护什么？","把情绪从敌人变成线索。",["emotion"],["stress"]],
    ["关系投影","你看见的是对方，还是自己的旧经验？","减少读心与投射。",["projection"],["relationship"]],
    ["现实矛盾","哪两种需要不能同时满足？","找到真正两难。",["contradiction"],["decision"]],
    ["未见之路","惯性之外还有什么选择？","打开被恐惧排除的路径。",["unseen"],["decision"]],
    ["归还之物","什么责任本不属你？","卸下错误承担。",["return"],["boundary","relationship"]],
    ["镜后之门","下一步现实动作是什么？","让洞察离开脑内，进入生活。",["door"],["decision","daily"]],
  ]),
  "life-oracle": mk("life-oracle", [
    ["此问之心","你真正所求为何？","辨结果焦虑与真实问题。",["heart"],["decision"]],
    ["当下之象","此刻诸条件怎样聚合？","看清当前局面。",["image"],["decision"]],
    ["所处之位","事情进行到哪一步？","避免把起始当结果。",["position"],["decision"]],
    ["顺势","现有哪些真实支持？","找到可借之力。",["support"],["decision"]],
    ["逆势","现有哪些现实阻力？","知道哪里强行会耗。",["resistance"],["decision"]],
    ["所忧","真正怕失去什么？","让焦虑显出代价对象。",["fear"],["decision"]],
    ["所阻","外阻还是内守？","把可控与不可控分开。",["block"],["decision"]],
    ["未显之机","何机初萌而未成形？","识别早期信号，不把它写成确定未来。",["opening"],["decision"]],
    ["近时之变","什么最可能先变？","观察短期转折条件。",["change"],["decision"]],
    ["可行之事","今日真正能做什么？","给问题一个现实出口。",["action"],["daily","decision"]],
    ["签后之守","得言之后要守什么？","停止反复求证，回到现实。",["guard"],["daily","boundary"]],
  ]),
};
