export type ToolExperienceKind="document"|"image"|"video"|"audio"|"text"|"privacy"|"utility"|"food";
export type ToolExperience={kind:ToolExperienceKind;primary:string;working:string;result:string;advancedAfterUpload:boolean;localFirst:boolean};
export const TOOL_EXPERIENCE:Record<string,ToolExperience>={
"audio-transcription":{kind:"audio",primary:"上传音频",working:"正在整理文字…",result:"查看文字与字幕",advancedAfterUpload:true,localFirst:true},
"avif-to-jpg":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 JPG",advancedAfterUpload:false,localFirst:true},
"batch-image-watermark-remover":{kind:"image",primary:"批量上传图片",working:"正在处理图片…",result:"下载处理后的图片",advancedAfterUpload:true,localFirst:true},
"batch-image":{kind:"image",primary:"批量上传图片",working:"正在处理图片…",result:"下载全部结果",advancedAfterUpload:true,localFirst:true},
"burn-after-read":{kind:"privacy",primary:"添加内容",working:"正在创建临时链接…",result:"复制临时链接",advancedAfterUpload:true,localFirst:false},
"document-copy-layout":{kind:"document",primary:"上传证件图片",working:"正在排版…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"e-sign-pdf":{kind:"document",primary:"上传 PDF",working:"正在打开文件…",result:"下载签好的 PDF",advancedAfterUpload:true,localFirst:true},
"food-calorie":{kind:"food",primary:"上传图片",working:"正在识别食物…",result:"查看分析结果",advancedAfterUpload:true,localFirst:true},
"heic-local":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 JPG",advancedAfterUpload:false,localFirst:true},
"id-photo-ai":{kind:"image",primary:"上传照片",working:"正在制作证件照…",result:"下载证件照",advancedAfterUpload:true,localFirst:true},
"image-to-pdf-pro":{kind:"document",primary:"上传图片",working:"正在生成 PDF…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"image-watermark-remover":{kind:"image",primary:"上传图片",working:"正在处理图片…",result:"下载图片",advancedAfterUpload:true,localFirst:true},
"jpg-to-png":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 PNG",advancedAfterUpload:false,localFirst:true},
"long-image":{kind:"image",primary:"上传截图",working:"正在拼接…",result:"下载长图",advancedAfterUpload:true,localFirst:true},
"ocr":{kind:"document",primary:"上传图片或扫描件",working:"正在识别文字…",result:"复制或下载文字",advancedAfterUpload:true,localFirst:true},
"pdf-compress":{kind:"document",primary:"上传 PDF",working:"正在压缩…",result:"下载压缩后的 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-editor":{kind:"document",primary:"上传 PDF",working:"正在打开文件…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-merge-split":{kind:"document",primary:"上传 PDF",working:"正在处理页面…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-ocr":{kind:"document",primary:"上传 PDF",working:"正在识别文字…",result:"下载文字",advancedAfterUpload:true,localFirst:true},
"pdf-pages":{kind:"document",primary:"上传 PDF",working:"正在读取页面…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-redact":{kind:"document",primary:"上传 PDF",working:"正在处理文件…",result:"下载处理后的 PDF",advancedAfterUpload:true,localFirst:true},
"handwriting-ocr":{kind:"image",primary:"上传手写图片",working:"正在识别手写文字…",result:"复制或下载文字",advancedAfterUpload:true,localFirst:true},
"pdf-to-word":{kind:"document",primary:"上传 PDF",working:"正在转换 Word…",result:"下载 DOCX",advancedAfterUpload:true,localFirst:true},
"pdf-watermark":{kind:"document",primary:"上传 PDF",working:"正在添加水印…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-page-numbers":{kind:"document",primary:"上传 PDF",working:"正在添加页码…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-crop":{kind:"document",primary:"上传 PDF",working:"正在裁边…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-flatten":{kind:"document",primary:"上传 PDF",working:"正在扁平化…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-compare":{kind:"document",primary:"上传两个 PDF",working:"正在比较…",result:"下载差异",advancedAfterUpload:true,localFirst:true},
"pdf-to-text":{kind:"document",primary:"上传 PDF",working:"正在提取文字…",result:"下载 TXT",advancedAfterUpload:false,localFirst:true},
"pdf-to-markdown":{kind:"document",primary:"上传 PDF",working:"正在生成 Markdown…",result:"下载 Markdown",advancedAfterUpload:false,localFirst:true},
"pdf-to-jpg":{kind:"image",primary:"上传 PDF",working:"正在转换页面…",result:"下载图片",advancedAfterUpload:true,localFirst:true},
"png-to-jpg":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 JPG",advancedAfterUpload:false,localFirst:true},
"privacy-cleaner":{kind:"privacy",primary:"上传文件",working:"正在清理信息…",result:"下载清理后的文件",advancedAfterUpload:true,localFirst:true},
"qr-safe-reader":{kind:"utility",primary:"上传二维码图片",working:"正在读取…",result:"查看内容",advancedAfterUpload:false,localFirst:true},
"screenshot-redact":{kind:"image",primary:"上传截图",working:"正在处理截图…",result:"下载截图",advancedAfterUpload:true,localFirst:true},
"subtitle-tools":{kind:"video",primary:"上传字幕",working:"正在处理字幕…",result:"下载字幕",advancedAfterUpload:true,localFirst:true},
"subtitle-translate":{kind:"text",primary:"上传字幕",working:"正在翻译…",result:"下载翻译后的字幕",advancedAfterUpload:true,localFirst:false},
"svg-to-png":{kind:"image",primary:"上传 SVG",working:"正在转换…",result:"下载 PNG",advancedAfterUpload:true,localFirst:true},
"temp-mail":{kind:"privacy",primary:"创建临时邮箱",working:"正在准备邮箱…",result:"查看收到的邮件",advancedAfterUpload:false,localFirst:false},
"video-dubbing":{kind:"video",primary:"上传视频",working:"正在处理视频…",result:"下载配音视频",advancedAfterUpload:true,localFirst:false},
"video-toolkit":{kind:"video",primary:"上传视频",working:"正在处理视频…",result:"下载视频",advancedAfterUpload:true,localFirst:true},
"video-translate":{kind:"video",primary:"上传视频或添加公开链接",working:"正在翻译视频…",result:"下载翻译视频与字幕",advancedAfterUpload:true,localFirst:false},
"video-transcription":{kind:"video",primary:"上传视频",working:"正在整理文字…",result:"查看文字与字幕",advancedAfterUpload:true,localFirst:true},
"video-watermark-remover":{kind:"video",primary:"上传视频",working:"正在处理视频…",result:"下载视频",advancedAfterUpload:true,localFirst:true},
"webp-to-jpg":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 JPG",advancedAfterUpload:false,localFirst:true},

"pdf-overlay":{kind:"document",primary:"上传 PDF",working:"正在叠加页面…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-header-footer":{kind:"document",primary:"上传 PDF",working:"正在添加页眉页脚…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-bates-numbering":{kind:"document",primary:"上传 PDF",working:"正在添加编号…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-viewer-preferences":{kind:"document",primary:"上传 PDF",working:"正在保存打开方式…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},

"pdf-remove-annotations":{kind:"document",primary:"上传 PDF",working:"正在清除批注…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-grayscale":{kind:"document",primary:"上传 PDF",working:"正在转成黑白灰…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-page-size":{kind:"document",primary:"上传 PDF",working:"正在调整页面…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-metadata-editor":{kind:"document",primary:"上传 PDF",working:"正在保存文件信息…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},

"pdf-protect":{kind:"document",primary:"上传 PDF",working:"正在加密码…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-unlock":{kind:"document",primary:"上传 PDF",working:"正在解除保护…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-permissions":{kind:"document",primary:"上传 PDF",working:"正在保存权限…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-web-optimize":{kind:"document",primary:"上传 PDF",working:"正在优化打开速度…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},

"pdf-inspect":{kind:"document",primary:"上传 PDF",working:"正在检查…",result:"查看结果",advancedAfterUpload:true,localFirst:true},
"pdf-attachments":{kind:"document",primary:"上传 PDF",working:"正在读取附件…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-bookmarks":{kind:"document",primary:"上传 PDF",working:"正在读取书签…",result:"查看书签",advancedAfterUpload:true,localFirst:true},
};
export function toolExperience(id:string){return TOOL_EXPERIENCE[id]??null}
