export type ToolExperienceKind="document"|"image"|"video"|"audio"|"text"|"privacy"|"utility"|"food";
export type ToolExperience={kind:ToolExperienceKind;primary:string;working:string;result:string;advancedAfterUpload:boolean;localFirst:boolean};
export const TOOL_EXPERIENCE:Record<string,ToolExperience>={
"audio-transcription":{kind:"audio",primary:"上传音频",working:"正在整理文字…",result:"查看文字与字幕",advancedAfterUpload:true,localFirst:true},
"avif-to-jpg":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 JPG",advancedAfterUpload:false,localFirst:true},
"batch-image-watermark-remover":{kind:"image",primary:"批量上传图片",working:"正在处理图片…",result:"下载处理后的图片",advancedAfterUpload:true,localFirst:true},
"batch-image":{kind:"image",primary:"批量上传图片",working:"正在处理图片…",result:"下载全部结果",advancedAfterUpload:true,localFirst:true},
"burn-after-read":{kind:"privacy",primary:"添加内容",working:"正在创建临时链接…",result:"复制临时链接",advancedAfterUpload:true,localFirst:false},
"document-copy-layout":{kind:"document",primary:"上传证件图片",working:"正在排版…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"e-sign-pdf":{kind:"document",primary:"上传 PDF",working:"正在打开文件…",result:"下载签好的 PDF",advancedAfterUpload:true,localFirst:true},
"food-calorie":{kind:"food",primary:"上传图片",working:"正在识别食物…",result:"查看分析结果",advancedAfterUpload:true,localFirst:true},
"heic-local":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 JPG",advancedAfterUpload:false,localFirst:true},
"id-photo-ai":{kind:"image",primary:"上传照片",working:"正在制作证件照…",result:"下载证件照",advancedAfterUpload:true,localFirst:true},
"image-to-pdf-pro":{kind:"document",primary:"上传图片",working:"正在生成 PDF…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"image-watermark-remover":{kind:"image",primary:"上传图片",working:"正在处理图片…",result:"下载图片",advancedAfterUpload:true,localFirst:true},
"jpg-to-png":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 PNG",advancedAfterUpload:false,localFirst:true},
"long-image":{kind:"image",primary:"上传截图",working:"正在拼接…",result:"下载长图",advancedAfterUpload:true,localFirst:true},
"ocr":{kind:"document",primary:"上传图片或扫描件",working:"正在识别文字…",result:"复制或下载文字",advancedAfterUpload:true,localFirst:true},
"pdf-compress":{kind:"document",primary:"上传 PDF",working:"正在压缩…",result:"下载压缩后的 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-editor":{kind:"document",primary:"上传 PDF",working:"正在打开文件…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-merge-split":{kind:"document",primary:"上传 PDF",working:"正在处理页面…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-ocr":{kind:"document",primary:"上传 PDF",working:"正在识别文字…",result:"下载文字",advancedAfterUpload:true,localFirst:true},
"pdf-pages":{kind:"document",primary:"上传 PDF",working:"正在读取页面…",result:"下载 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-redact":{kind:"document",primary:"上传 PDF",working:"正在处理文件…",result:"下载处理后的 PDF",advancedAfterUpload:true,localFirst:true},
"pdf-to-jpg":{kind:"image",primary:"上传 PDF",working:"正在转换页面…",result:"下载图片",advancedAfterUpload:true,localFirst:true},
"png-to-jpg":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 JPG",advancedAfterUpload:false,localFirst:true},
"privacy-cleaner":{kind:"privacy",primary:"上传文件",working:"正在清理信息…",result:"下载清理后的文件",advancedAfterUpload:true,localFirst:true},
"qr-safe-reader":{kind:"utility",primary:"上传二维码图片",working:"正在读取…",result:"查看内容",advancedAfterUpload:false,localFirst:true},
"screenshot-redact":{kind:"image",primary:"上传截图",working:"正在处理截图…",result:"下载截图",advancedAfterUpload:true,localFirst:true},
"subtitle-tools":{kind:"video",primary:"上传字幕",working:"正在处理字幕…",result:"下载字幕",advancedAfterUpload:true,localFirst:true},
"subtitle-translate":{kind:"text",primary:"上传字幕",working:"正在翻译…",result:"下载翻译后的字幕",advancedAfterUpload:true,localFirst:false},
"svg-to-png":{kind:"image",primary:"上传 SVG",working:"正在转换…",result:"下载 PNG",advancedAfterUpload:true,localFirst:true},
"temp-mail":{kind:"privacy",primary:"创建临时邮箱",working:"正在准备邮箱…",result:"查看收到的邮件",advancedAfterUpload:false,localFirst:false},
"video-dubbing":{kind:"video",primary:"上传视频",working:"正在处理视频…",result:"下载配音视频",advancedAfterUpload:true,localFirst:false},
"video-toolkit":{kind:"video",primary:"上传视频",working:"正在处理视频…",result:"下载视频",advancedAfterUpload:true,localFirst:true},
"video-transcription":{kind:"video",primary:"上传视频",working:"正在整理文字…",result:"查看文字与字幕",advancedAfterUpload:true,localFirst:true},
"video-watermark-remover":{kind:"video",primary:"上传视频",working:"正在处理视频…",result:"下载视频",advancedAfterUpload:true,localFirst:true},
"webp-to-jpg":{kind:"image",primary:"上传图片",working:"正在转换…",result:"下载 JPG",advancedAfterUpload:false,localFirst:true},
};
export function toolExperience(id:string){return TOOL_EXPERIENCE[id]??null}
