import type {LingxiLang} from "@/lib/lingxi-i18n";
type T=Record<LingxiLang,string>;
const L=(zh:string,en:string,ja:string,ko:string,fr:string,de:string,es:string,pt:string,ar:string):T=>({zh,en,ja,ko,fr,de,es,pt,ar});

export type ToolDisplayCategory="all"|"pdf"|"image"|"media"|"subtitle"|"table"|"privacy"|"recognition"|"file";

const CATEGORIES:Record<ToolDisplayCategory,T>={
 all:L("全部","All","すべて","전체","Tout","Alle","Todo","Tudo","الكل"),
 pdf:L("PDF / 文档","PDF / Docs","PDF / 文書","PDF / 문서","PDF / Documents","PDF / Dokumente","PDF / Documentos","PDF / Documentos","PDF / المستندات"),
 image:L("图片","Images","画像","이미지","Images","Bilder","Imágenes","Imagens","الصور"),
 media:L("视频 / 音频","Video / Audio","動画 / 音声","영상 / 오디오","Vidéo / Audio","Video / Audio","Vídeo / Audio","Vídeo / Áudio","الفيديو / الصوت"),
 subtitle:L("字幕 / 语音","Subtitles / Voice","字幕 / 音声","자막 / 음성","Sous-titres / Voix","Untertitel / Sprache","Subtítulos / Voz","Legendas / Voz","الترجمة / الصوت"),
 table:L("表格 / 数据","Tables / Data","表 / データ","표 / 데이터","Tableaux / Données","Tabellen / Daten","Tablas / Datos","Tabelas / Dados","الجداول / البيانات"),
 privacy:L("隐私","Privacy","プライバシー","개인정보","Confidentialité","Datenschutz","Privacidad","Privacidade","الخصوصية"),
 recognition:L("识别 / 二维码","Recognition / QR","認識 / QR","인식 / QR","Reconnaissance / QR","Erkennung / QR","Reconocimiento / QR","Reconhecimento / QR","التعرّف / QR"),
 file:L("文本 / 文件","Text / Files","テキスト / ファイル","텍스트 / 파일","Texte / Fichiers","Text / Dateien","Texto / Archivos","Texto / Ficheiros","النصوص / الملفات"),
};
const HUB={
 kicker:L("实用工具","Practical tools","実用ツール","실용 도구","Outils pratiques","Praktische Werkzeuge","Herramientas prácticas","Ferramentas práticas","أدوات عملية"),
 title:L("要处理什么？","What needs to be handled?","何を処理しますか？","무엇을 처리할까요?","Que faut-il traiter ?","Was soll bearbeitet werden?","¿Qué hay que procesar?","O que precisa de ser tratado?","ما الذي يحتاج إلى معالجة؟"),
 search:L("搜索 PDF、图片、视频、字幕、表格……","Search PDF, images, video, subtitles, tables…","PDF、画像、動画、字幕、表を検索…","PDF, 이미지, 영상, 자막, 표 검색…","Rechercher PDF, images, vidéo, sous-titres, tableaux…","PDF, Bilder, Video, Untertitel, Tabellen suchen…","Buscar PDF, imágenes, vídeo, subtítulos, tablas…","Pesquisar PDF, imagens, vídeo, legendas, tabelas…","ابحث في PDF والصور والفيديو والترجمة والجداول…"),
 open:L("打开","Open","開く","열기","Ouvrir","Öffnen","Abrir","Abrir","فتح"),
};
const SUMMARY:Record<string,Partial<T>>={
 "temp-mail":L("即时生成临时邮箱，自动收信和识别验证码，可复制地址、刷新、续时、销毁；支持批量生成。","Create a temporary inbox instantly, receive mail and detect verification codes, copy the address, refresh, extend or destroy it; batch generation is supported.","一時メールをすぐ作成し、受信・認証コード検出・コピー・更新・延長・削除に対応。まとめて生成も可能。","임시 메일을 즉시 만들고 메일 수신·인증번호 감지·주소 복사·새로고침·연장·삭제를 지원하며 일괄 생성도 가능합니다.","Créez instantanément une boîte temporaire, recevez les e-mails et codes, copiez l’adresse, actualisez, prolongez ou détruisez la boîte ; génération par lot disponible.","Temporäres Postfach sofort erstellen, Mails und Codes empfangen, Adresse kopieren, aktualisieren, verlängern oder löschen; Stapelerstellung möglich.","Crea un correo temporal al instante, recibe mensajes y códigos, copia la dirección, actualiza, amplía o destruye el buzón; admite generación por lotes.","Crie um email temporário instantaneamente, receba mensagens e códigos, copie o endereço, atualize, prolongue ou destrua a caixa; suporta geração em lote.","إنشاء بريد مؤقت فورًا، واستقبال الرسائل ورموز التحقق، ونسخ العنوان والتحديث والتمديد والحذف؛ مع دعم الإنشاء الدفعي."),
 "burn-after-read":L("把文字或文件生成临时链接，可按阅读一次、到期时间、查看次数或倒计时自动失效。","Turn text or files into a temporary link that can expire after one read, at a set time, after a view limit or countdown.","テキストやファイルを一時リンクにし、1回閲覧・期限・閲覧回数・カウントダウンで失効。","텍스트나 파일을 임시 링크로 만들고 1회 열람·기한·조회 횟수·카운트다운에 따라 만료.","Transformez texte ou fichiers en lien temporaire expirant après lecture, à une date, après un nombre de vues ou un compte à rebours.","Text oder Dateien als temporären Link teilen, der nach Lesen, Zeit, Ansichten oder Countdown verfällt.","Convierte texto o archivos en un enlace temporal que caduca por lectura, tiempo, número de vistas o cuenta atrás.","Transforme texto ou ficheiros num link temporário que expira por leitura, tempo, visualizações ou contagem.","تحويل النصوص أو الملفات إلى رابط مؤقت ينتهي بعد القراءة أو الوقت أو عدد المشاهدات أو العد التنازلي."),
 "pdf-ocr":L("把扫描 PDF 变成可复制文字。","Turn scanned PDFs into copyable text.","スキャンPDFをコピー可能な文字に変換。","스캔 PDF를 복사 가능한 텍스트로 변환.","Transformez un PDF scanné en texte copiable.","Gescanntes PDF in kopierbaren Text umwandeln.","Convierte PDF escaneados en texto copiable.","Transforme PDF digitalizado em texto copiável.","تحويل PDF الممسوح إلى نص قابل للنسخ."),
 "ocr":L("提取图片里的文字。","Extract text from an image.","画像内の文字を抽出。","이미지 속 텍스트 추출.","Extrayez le texte d’une image.","Text aus einem Bild extrahieren.","Extrae texto de una imagen.","Extraia texto de uma imagem.","استخراج النص من الصورة."),
 "video-transcription":L("把视频里的声音变成文字。","Turn video speech into text.","動画の音声を文字に変換。","영상 음성을 텍스트로 변환.","Transformez la parole d’une vidéo en texte.","Videosprache in Text umwandeln.","Convierte el audio del vídeo en texto.","Transforme a fala do vídeo em texto.","تحويل صوت الفيديو إلى نص."),
 "audio-transcription":L("把录音变成文字。","Turn recordings into text.","録音を文字に変換。","녹음을 텍스트로 변환.","Transformez un enregistrement en texte.","Aufnahmen in Text umwandeln.","Convierte grabaciones en texto.","Transforme gravações em texto.","تحويل التسجيلات إلى نص."),
 "subtitle-translate":L("翻译字幕并保留时间轴。","Translate subtitles while keeping timing.","タイミングを保ったまま字幕を翻訳。","타임라인을 유지하며 자막 번역.","Traduisez les sous-titres en conservant le timing.","Untertitel mit Zeitachsen übersetzen.","Traduce subtítulos conservando los tiempos.","Traduza legendas mantendo a temporização.","ترجمة الترجمة النصية مع الحفاظ على التوقيت."),
 "privacy-cleaner":L("清除文件里的位置、设备等隐私信息。","Remove location, device and other private metadata.","位置・端末などの個人情報を削除。","위치·기기 등 개인정보 메타데이터 제거.","Supprimez les données privées comme la position ou l’appareil.","Standort-, Geräte- und andere private Metadaten entfernen.","Elimina ubicación, dispositivo y otros metadatos privados.","Remova localização, dispositivo e outros metadados privados.","إزالة معلومات الموقع والجهاز والبيانات الخاصة."),
 "screenshot-redact":L("遮住截图中的手机号、地址等敏感内容。","Hide phone numbers, addresses and other sensitive details in screenshots.","スクリーンショットの電話番号や住所などを隠す。","스크린샷의 전화번호·주소 등 민감정보 가리기.","Masquez les numéros, adresses et autres données sensibles.","Telefonnummern, Adressen und sensible Daten schwärzen.","Oculta teléfonos, direcciones y datos sensibles.","Oculte telefones, endereços e dados sensíveis.","إخفاء أرقام الهاتف والعناوين والبيانات الحساسة."),
 "pdf-redact":L("永久移除 PDF 中的敏感内容。","Permanently remove sensitive content from a PDF.","PDFの機密内容を完全に削除。","PDF의 민감한 내용을 영구 제거.","Supprimez définitivement les données sensibles d’un PDF.","Sensible Inhalte dauerhaft aus PDF entfernen.","Elimina permanentemente contenido sensible de un PDF.","Remova permanentemente conteúdo sensível de um PDF.","إزالة المحتوى الحساس من PDF بشكل دائم."),
 "id-photo-ai":L("一张照片生成标准证件照。","Create a standard ID photo from one photo.","1枚の写真から証明写真を作成。","사진 한 장으로 증명사진 생성.","Créez une photo d’identité standard à partir d’une photo.","Aus einem Foto ein Standard-Passfoto erstellen.","Crea una foto de identificación estándar a partir de una foto.","Crie uma foto de identificação padrão a partir de uma foto.","إنشاء صورة هوية قياسية من صورة واحدة."),
 "food-calorie":L("拍下食物，估算大致热量。","Estimate calories from a food photo.","食事写真からおおよそのカロリーを推定。","음식 사진으로 대략적인 칼로리 추정.","Estimez les calories à partir d’une photo du repas.","Kalorien aus einem Essensfoto schätzen.","Estima calorías a partir de una foto de comida.","Estime calorias a partir de uma foto de comida.","تقدير السعرات من صورة الطعام."),
 "file-type-detector":L("识别文件的真实格式。","Identify a file’s real format.","ファイルの実際の形式を確認。","파일의 실제 형식 확인.","Identifiez le vrai format d’un fichier.","Echtes Dateiformat erkennen.","Identifica el formato real de un archivo.","Identifique o formato real de um ficheiro.","التعرف على الصيغة الحقيقية للملف."),
 "file-compare":L("判断两个文件是否完全一致。","Check whether two files are identical.","2つのファイルが同一か確認。","두 파일이 완전히 같은지 확인.","Vérifiez si deux fichiers sont identiques.","Prüfen, ob zwei Dateien identisch sind.","Comprueba si dos archivos son idénticos.","Verifique se dois ficheiros são idênticos.","التحقق مما إذا كان ملفان متطابقين."),
 "qr-safe-reader":L("先查看二维码内容，再决定是否打开。","Inspect a QR code before opening it.","開く前にQRコードの内容を確認。","열기 전에 QR 코드 내용 확인.","Vérifiez le contenu du QR avant de l’ouvrir.","QR-Inhalt vor dem Öffnen prüfen.","Revisa el QR antes de abrirlo.","Verifique o QR antes de abrir.","فحص محتوى QR قبل فتحه.")
};
export const toolCategoryLabel=(lang:LingxiLang,key:ToolDisplayCategory)=>CATEGORIES[key][lang];
export const toolHubCopy=(lang:LingxiLang,key:keyof typeof HUB)=>HUB[key][lang];
export const toolSummary=(lang:LingxiLang,slug:string)=>SUMMARY[slug]?.[lang]||"";
