import type {LingxiLang} from "@/lib/lingxi-i18n";
type T=Record<LingxiLang,string>;
const L=(zh:string,en:string,ja:string,ko:string,fr:string,de:string,es:string,pt:string,ar:string):T=>({zh,en,ja,ko,fr,de,es,pt,ar});

export type ToolDisplayCategory="all"|"pdf"|"image"|"media"|"subtitle"|"table"|"privacy"|"recognition"|"file";

const CATEGORIES:Record<ToolDisplayCategory,T>={
 all:L("全部","All","すべて","전체","Tout","Alle","Todo","Tudo","الكل"),
 pdf:L("PDF / 文档","PDF / Docs","PDF / 文書","PDF / 문서","PDF / Documents","PDF / Dokumente","PDF / Documentos","PDF / Documentos","PDF / المستندات"),
 image:L("图片","Images","画像","이미지","Images","Bilder","Imágenes","Imagens","الصور"),
 media:L("视频 / 音频","Video / Audio","動画 / 音声","영상 / 오디오","Vidéo / Audio","Video / Audio","Vídeo / Audio","Vídeo / Áudio","الفيديو / الصوت"),
 subtitle:L("字幕 / 语音","Subtitles / Voice","字幕 / 音声","자막 / 음성","Sous-titres / Voix","Untertitel / Sprache","Subtítulos / Voz","Legendas / Voz","الترجمة / الصوت"),
 table:L("表格 / 数据","Tables / Data","表 / データ","표 / 데이터","Tableaux / Données","Tabellen / Daten","Tablas / Datos","Tabelas / Dados","الجداول / البيانات"),
 privacy:L("隐私","Privacy","プライバシー","개인정보","Confidentialité","Datenschutz","Privacidad","Privacidade","الخصوصية"),
 recognition:L("识别 / 二维码","Recognition / QR","認識 / QR","인식 / QR","Reconnaissance / QR","Erkennung / QR","Reconocimiento / QR","Reconhecimento / QR","التعرّف / QR"),
 file:L("文本 / 文件","Text / Files","テキスト / ファイル","텍스트 / 파일","Texte / Fichiers","Text / Dateien","Texto / Archivos","Texto / Ficheiros","النصوص / الملفات"),
};
const HUB={
 kicker:L("实用工具","Practical tools","実用ツール","실용 도구","Outils pratiques","Praktische Werkzeuge","Herramientas prácticas","Ferramentas práticas","أدوات عملية"),
 title:L("要处理什么？","What needs to be handled?","何を処理しますか？","무엇을 처리할까요?","Que faut-il traiter ?","Was soll bearbeitet werden?","¿Qué hay que procesar?","O que precisa de ser tratado?","ما الذي يحتاج إلى معالجة؟"),
 subtitle:L("PDF、图片、视频、字幕、表格、网页、隐私文件与日常识别，打开即可处理并得到结果。","PDFs, images, video, subtitles, tables, web content, private files and everyday recognition tools — open one and get the result.","PDF、画像、動画、字幕、表、Web、プライバシー文書、日常認識ツール。開いてすぐ処理できます。","PDF, 이미지, 영상, 자막, 표, 웹, 개인정보 파일과 일상 인식 도구를 바로 처리하세요.","PDF, images, vidéo, sous-titres, tableaux, web, fichiers privés et reconnaissance du quotidien : ouvrez l’outil et obtenez le résultat.","PDFs, Bilder, Videos, Untertitel, Tabellen, Webinhalte, private Dateien und Alltagserkennung direkt bearbeiten.","PDF, imágenes, vídeo, subtítulos, tablas, web, archivos privados y reconocimiento cotidiano, listos para usar.","PDF, imagens, vídeo, legendas, tabelas, web, ficheiros privados e reconhecimento do dia a dia, prontos a usar.","PDF والصور والفيديو والترجمة والجداول والويب والملفات الخاصة وأدوات التعرّف اليومية — افتح الأداة وابدأ مباشرة."),
 search:L("搜索 PDF、图片、视频、字幕、表格……","Search PDF, images, video, subtitles, tables…","PDF、画像、動画、字幕、表を検索…","PDF, 이미지, 영상, 자막, 표 검색…","Rechercher PDF, images, vidéo, sous-titres, tableaux…","PDF, Bilder, Video, Untertitel, Tabellen suchen…","Buscar PDF, imágenes, vídeo, subtítulos, tablas…","Pesquisar PDF, imagens, vídeo, legendas, tabelas…","ابحث في PDF والصور والفيديو والترجمة والجداول…"),
 open:L("打开","Open","開く","열기","Ouvrir","Öffnen","Abrir","Abrir","فتح"),
};
const SUMMARY:Record<string,Partial<T>>={
 "temp-mail":L("即时生成临时邮箱，自动收信和识别验证码，可复制地址、刷新、续时、销毁；支持批量生成。","Create a temporary inbox instantly, receive mail and detect verification codes, copy the address, refresh, extend or destroy it; batch generation is supported.","一時メールをすぐ作成し、受信・認証コード検出・コピー・更新・延長・削除に対応。まとめて生成も可能。","임시 메일을 즉시 만들고 메일 수신·인증번호 감지·주소 복사·새로고침·연장·삭제를 지원하며 일괄 생성도 가능합니다.","Créez instantanément une boîte temporaire, recevez les e-mails et codes, copiez l’adresse, actualisez, prolongez ou détruisez la boîte ; génération par lot disponible.","Temporäres Postfach sofort erstellen, Mails und Codes empfangen, Adresse kopieren, aktualisieren, verlängern oder löschen; Stapelerstellung möglich.","Crea un correo temporal al instante, recibe mensajes y códigos, copia la dirección, actualiza, amplía o destruye el buzón; admite generación por lotes.","Crie um email temporário instantaneamente, receba mensagens e códigos, copie o endereço, atualize, prolongue ou destrua a caixa; suporta geração em lote.","إنشاء بريد مؤقت فورًا، واستقبال الرسائل ورموز التحقق، ونسخ العنوان والتحديث والتمديد والحذف؛ مع دعم الإنشاء الدفعي."),
 "burn-after-read":L("把文字或文件生成临时链接，可按阅读一次、到期时间、查看次数或倒计时自动失效。","Turn text or files into a temporary link that can expire after one read, at a set time, after a view limit or countdown.","テキストやファイルを一時リンクにし、1回閲覧・期限・閲覧回数・カウントダウンで失効。","텍스트나 파일을 임시 링크로 만들고 1회 열람·기한·조회 횟수·카운트다운에 따라 만료.","Transformez texte ou fichiers en lien temporaire expirant après lecture, à une date, après un nombre de vues ou un compte à rebours.","Text oder Dateien als temporären Link teilen, der nach Lesen, Zeit, Ansichten oder Countdown verfällt.","Convierte texto o archivos en un enlace temporal que caduca por lectura, tiempo, número de vistas o cuenta atrás.","Transforme texto ou ficheiros num link temporário que expira por leitura, tempo, visualizações ou contagem.","تحويل النصوص أو الملفات إلى رابط مؤقت ينتهي بعد القراءة أو الوقت أو عدد المشاهدات أو العد التنازلي."),
 "pdf-ocr":L("把扫描 PDF 变成可复制文字。","Turn scanned PDFs into copyable text.","スキャンPDFをコピー可能な文字に変換。","스캔 PDF를 복사 가능한 텍스트로 변환.","Transformez un PDF scanné en texte copiable.","Gescanntes PDF in kopierbaren Text umwandeln.","Convierte PDF escaneados en texto copiable.","Transforme PDF digitalizado em texto copiável.","تحويل PDF الممسوح إلى نص قابل للنسخ."),
 "ocr":L("提取图片里的文字。","Extract text from an image.","画像内の文字を抽出。","이미지 속 텍스트 추출.","Extrayez le texte d’une image.","Text aus einem Bild extrahieren.","Extrae texto de una imagen.","Extraia texto de uma imagem.","استخراج النص من الصورة."),
 "video-transcription":L("把视频里的声音变成文字。","Turn video speech into text.","動画の音声を文字に変換。","영상 음성을 텍스트로 변환.","Transformez la parole d’une vidéo en texte.","Videosprache in Text umwandeln.","Convierte el audio del vídeo en texto.","Transforme a fala do vídeo em texto.","تحويل صوت الفيديو إلى نص."),
 "audio-transcription":L("把录音变成文字。","Turn recordings into text.","録音を文字に変換。","녹음을 텍스트로 변환.","Transformez un enregistrement en texte.","Aufnahmen in Text umwandeln.","Convierte grabaciones en texto.","Transforme gravações em texto.","تحويل التسجيلات إلى نص."),
 "subtitle-translate":L("翻译字幕并保留时间轴。","Translate subtitles while keeping timing.","タイミングを保ったまま字幕を翻訳。","타임라인을 유지하며 자막 번역.","Traduisez les sous-titres en conservant le timing.","Untertitel mit Zeitachsen übersetzen.","Traduce subtítulos conservando los tiempos.","Traduza legendas mantendo a temporização.","ترجمة الترجمة النصية مع الحفاظ على التوقيت."),
 "privacy-cleaner":L("清除文件里的位置、设备等隐私信息。","Remove location, device and other private metadata.","位置・端末などの個人情報を削除。","위치·기기 등 개인정보 메타데이터 제거.","Supprimez les données privées comme la position ou l’appareil.","Standort-, Geräte- und andere private Metadaten entfernen.","Elimina ubicación, dispositivo y otros metadatos privados.","Remova localização, dispositivo e outros metadados privados.","إزالة معلومات الموقع والجهاز والبيانات الخاصة."),
 "screenshot-redact":L("遮住截图中的手机号、地址等敏感内容。","Hide phone numbers, addresses and other sensitive details in screenshots.","スクリーンショットの電話番号や住所などを隠す。","스크린샷의 전화번호·주소 등 민감정보 가리기.","Masquez les numéros, adresses et autres données sensibles.","Telefonnummern, Adressen und sensible Daten schwärzen.","Oculta teléfonos, direcciones y datos sensibles.","Oculte telefones, endereços e dados sensíveis.","إخفاء أرقام الهاتف والعناوين والبيانات الحساسة."),
 "pdf-redact":L("永久移除 PDF 中的敏感内容。","Permanently remove sensitive content from a PDF.","PDFの機密内容を完全に削除。","PDF의 민감한 내용을 영구 제거.","Supprimez définitivement les données sensibles d’un PDF.","Sensible Inhalte dauerhaft aus PDF entfernen.","Elimina permanentemente contenido sensible de un PDF.","Remova permanentemente conteúdo sensível de um PDF.","إزالة المحتوى الحساس من PDF بشكل دائم."),
 "id-photo-ai":L("一张照片生成标准证件照。","Create a standard ID photo from one photo.","1枚の写真から証明写真を作成。","사진 한 장으로 증명사진 생성.","Créez une photo d’identité standard à partir d’une photo.","Aus einem Foto ein Standard-Passfoto erstellen.","Crea una foto de identificación estándar a partir de una foto.","Crie uma foto de identificação padrão a partir de uma foto.","إنشاء صورة هوية قياسية من صورة واحدة."),
 "food-calorie":L("拍下食物，估算大致热量。","Estimate calories from a food photo.","食事写真からおおよそのカロリーを推定。","음식 사진으로 대략적인 칼로리 추정.","Estimez les calories à partir d’une photo du repas.","Kalorien aus einem Essensfoto schätzen.","Estima calorías a partir de una foto de comida.","Estime calorias a partir de uma foto de comida.","تقدير السعرات من صورة الطعام."),
 "file-type-detector":L("识别文件的真实格式。","Identify a file’s real format.","ファイルの実際の形式を確認。","파일의 실제 형식 확인.","Identifiez le vrai format d’un fichier.","Echtes Dateiformat erkennen.","Identifica el formato real de un archivo.","Identifique o formato real de um ficheiro.","التعرف على الصيغة الحقيقية للملف."),
 "file-compare":L("判断两个文件是否完全一致。","Check whether two files are identical.","2つのファイルが同一か確認。","두 파일이 완전히 같은지 확인.","Vérifiez si deux fichiers sont identiques.","Prüfen, ob zwei Dateien identisch sind.","Comprueba si dos archivos son idénticos.","Verifique se dois ficheiros são idênticos.","التحقق مما إذا كان ملفان متطابقين."),
 "qr-safe-reader":L("先查看二维码内容，再决定是否打开。","Inspect a QR code before opening it.","開く前にQRコードの内容を確認。","열기 전에 QR 코드 내용 확인.","Vérifiez le contenu du QR avant de l’ouvrir.","QR-Inhalt vor dem Öffnen prüfen.","Revisa el QR antes de abrirlo.","Verifique o QR antes de abrir.","فحص محتوى QR قبل فتحه.")
};
export const toolCategoryLabel=(lang:LingxiLang,key:ToolDisplayCategory)=>CATEGORIES[key][lang];
export const toolHubCopy=(lang:LingxiLang,key:keyof typeof HUB)=>HUB[key][lang];
export const toolSummary=(lang:LingxiLang,slug:string)=>SUMMARY[slug]?.[lang]||"";

const GENERIC:Record<string,T>={
 image:L("转换、压缩、调整或整理图片。","Convert, compress, resize or organize images.","画像の変換・圧縮・サイズ調整・整理。","이미지 변환·압축·크기 조정·정리.","Convertir, compresser, redimensionner ou organiser les images.","Bilder konvertieren, komprimieren, skalieren oder ordnen.","Convierte, comprime, redimensiona u organiza imágenes.","Converta, comprima, redimensione ou organize imagens.","تحويل الصور وضغطها وتغيير حجمها وتنظيمها."),
 document:L("处理 PDF 与文档内容、页面或格式。","Handle PDF and document content, pages or formats.","PDFや文書の内容・ページ・形式を処理。","PDF와 문서의 내용·페이지·형식을 처리.","Traiter le contenu, les pages ou les formats PDF et documents.","PDF- und Dokumentinhalte, Seiten oder Formate bearbeiten.","Procesa contenido, páginas o formatos de PDF y documentos.","Processe conteúdo, páginas ou formatos de PDF e documentos.","معالجة محتوى PDF والمستندات وصفحاتها وصيغها."),
 video:L("处理视频内容、画面或声音。","Process video content, visuals or audio.","動画の内容・映像・音声を処理。","영상의 내용·화면·소리를 처리.","Traiter le contenu, l’image ou le son d’une vidéo.","Videoinhalt, Bild oder Ton bearbeiten.","Procesa contenido, imagen o audio de vídeo.","Processe conteúdo, imagem ou áudio de vídeo.","معالجة محتوى الفيديو والصورة والصوت."),
 audio:L("处理录音、语音或音轨。","Process recordings, speech or audio tracks.","録音・音声・音声トラックを処理。","녹음·음성·오디오 트랙을 처리.","Traiter enregistrements, voix ou pistes audio.","Aufnahmen, Sprache oder Audiospuren bearbeiten.","Procesa grabaciones, voz o pistas de audio.","Processe gravações, voz ou faixas de áudio.","معالجة التسجيلات والصوت والمسارات الصوتية."),
 privacy:L("清理、遮盖或临时分享敏感内容。","Clean, redact or temporarily share sensitive content.","機密内容の整理・秘匿・一時共有。","민감한 내용의 정리·가림·임시 공유.","Nettoyer, masquer ou partager temporairement des contenus sensibles.","Sensible Inhalte bereinigen, schwärzen oder vorübergehend teilen.","Limpia, oculta o comparte temporalmente contenido sensible.","Limpe, oculte ou partilhe temporariamente conteúdo sensível.","تنظيف المحتوى الحساس أو إخفاؤه أو مشاركته مؤقتًا."),
 utility:L("处理文本、文件或常用数据。","Handle text, files or everyday data.","テキスト・ファイル・日常データを処理。","텍스트·파일·일상 데이터를 처리.","Traiter textes, fichiers ou données courantes.","Text, Dateien oder Alltagsdaten bearbeiten.","Procesa texto, archivos o datos habituales.","Processe texto, ficheiros ou dados do dia a dia.","معالجة النصوص والملفات والبيانات اليومية."),
 ai:L("识别、生成或理解图片与媒体内容。","Recognize, generate or understand image and media content.","画像やメディアを認識・生成・理解。","이미지와 미디어를 인식·생성·이해.","Reconnaître, générer ou comprendre des images et médias.","Bild- und Medieninhalte erkennen, erzeugen oder verstehen.","Reconoce, genera o entiende contenido visual y multimedia.","Reconheça, gere ou compreenda imagens e multimédia.","التعرّف على الصور والوسائط أو إنشاؤها وفهمها."),
 qr:L("生成、识别或检查二维码内容。","Create, read or inspect QR code content.","QRコードの生成・読取・確認。","QR 코드 생성·인식·확인.","Créer, lire ou vérifier le contenu d’un QR code.","QR-Codes erstellen, lesen oder prüfen.","Crea, lee o revisa el contenido de códigos QR.","Crie, leia ou verifique conteúdo de códigos QR.","إنشاء رموز QR وقراءتها وفحص محتواها.")
};
const SIMPLE:Record<string,T>={
 "text-counter":L("统计文字、单词、字符、行数与字节。","Count words, characters, lines and bytes.","文字・単語・文字数・行数・バイト数を集計。","글자·단어·문자·줄·바이트 수를 계산.","Compter mots, caractères, lignes et octets.","Wörter, Zeichen, Zeilen und Bytes zählen.","Cuenta palabras, caracteres, líneas y bytes.","Conte palavras, caracteres, linhas e bytes.","حساب الكلمات والأحرف والأسطر والبايتات."),
 "remove-duplicate-lines":L("删除重复行，保留第一次出现的内容。","Remove duplicate lines and keep the first occurrence.","重複行を削除し、最初の内容を残します。","중복 줄을 제거하고 첫 항목을 유지합니다.","Supprimer les lignes en double en gardant la première.","Doppelte Zeilen entfernen und den ersten Eintrag behalten.","Elimina líneas duplicadas y conserva la primera.","Remove linhas duplicadas e mantém a primeira.","إزالة الأسطر المكررة مع الاحتفاظ بأول ظهور."),
 "remove-empty-lines":L("删除空行，只保留有内容的行。","Remove blank lines and keep lines with content.","空行を削除し、内容のある行だけ残します。","빈 줄을 제거하고 내용이 있는 줄만 유지합니다.","Supprimer les lignes vides et garder celles avec du contenu.","Leere Zeilen entfernen und Inhaltszeilen behalten.","Elimina líneas vacías y conserva las que tienen contenido.","Remove linhas vazias e mantém as linhas com conteúdo.","إزالة الأسطر الفارغة والاحتفاظ بالأسطر ذات المحتوى."),
 "url-encode-decode":L("编码或解码 URL 参数和中文字符。","Encode or decode URL parameters and text.","URLパラメータや文字列をエンコード・デコード。","URL 매개변수와 텍스트를 인코딩·디코딩.","Encoder ou décoder paramètres URL et texte.","URL-Parameter und Text kodieren oder dekodieren.","Codifica o decodifica parámetros URL y texto.","Codifique ou descodifique parâmetros URL e texto.","ترميز أو فك ترميز معلمات URL والنص."),
 "base64-encode-decode":L("在文本与 Base64 之间相互转换。","Convert between text and Base64.","テキストとBase64を相互変換。","텍스트와 Base64를 상호 변환.","Convertir entre texte et Base64.","Text und Base64 ineinander umwandeln.","Convierte entre texto y Base64.","Converta entre texto e Base64.","التحويل بين النص وBase64."),
 "png-to-jpg":L("把 PNG 转成 JPG。","Convert PNG to JPG.","PNGをJPGへ変換。","PNG를 JPG로 변환.","Convertir PNG en JPG.","PNG in JPG umwandeln.","Convierte PNG a JPG.","Converta PNG para JPG.","تحويل PNG إلى JPG."),
 "jpg-to-png":L("把 JPG / JPEG 转成 PNG。","Convert JPG / JPEG to PNG.","JPG / JPEGをPNGへ変換。","JPG / JPEG를 PNG로 변환.","Convertir JPG / JPEG en PNG.","JPG / JPEG in PNG umwandeln.","Convierte JPG / JPEG a PNG.","Converta JPG / JPEG para PNG.","تحويل JPG / JPEG إلى PNG."),
 "webp-to-jpg":L("把 WebP 转成 JPG 或 PNG。","Convert WebP to JPG or PNG.","WebPをJPGまたはPNGへ変換。","WebP를 JPG 또는 PNG로 변환.","Convertir WebP en JPG ou PNG.","WebP in JPG oder PNG umwandeln.","Convierte WebP a JPG o PNG.","Converta WebP para JPG ou PNG.","تحويل WebP إلى JPG أو PNG."),
 "compress-image":L("减小图片体积，并尽量保留清晰度。","Reduce image size while keeping useful quality.","画質を保ちながら画像容量を縮小。","화질을 유지하며 이미지 용량을 줄입니다.","Réduire la taille de l’image en conservant la qualité utile.","Bildgröße reduzieren und brauchbare Qualität erhalten.","Reduce el tamaño de la imagen manteniendo la calidad.","Reduza o tamanho da imagem mantendo a qualidade.","تقليل حجم الصورة مع الحفاظ على جودة مناسبة."),
 "resize-image":L("按像素修改图片宽高，可保持比例。","Change image width and height in pixels, with optional aspect ratio lock.","画像の幅と高さをピクセル指定で変更。","픽셀 단위로 이미지 너비와 높이를 변경.","Modifier largeur et hauteur de l’image en pixels.","Bildbreite und -höhe in Pixeln ändern.","Cambia el ancho y alto de la imagen en píxeles.","Altere largura e altura da imagem em píxeis.","تغيير عرض الصورة وارتفاعها بالبكسل."),
 "remove-exif":L("清除图片中的 GPS、设备和拍摄信息。","Remove GPS, device and capture metadata from images.","画像のGPS・端末・撮影情報を削除。","이미지의 GPS·기기·촬영 정보를 제거.","Supprimer GPS, appareil et métadonnées de prise de vue.","GPS-, Geräte- und Aufnahmedaten aus Bildern entfernen.","Elimina GPS, dispositivo y metadatos de captura.","Remova GPS, dispositivo e metadados de captura.","إزالة GPS ومعلومات الجهاز وبيانات التصوير."),
 "md5-sha256":L("生成 MD5 与 SHA256 校验值。","Generate MD5 and SHA256 checksums.","MD5とSHA256のチェック値を生成。","MD5와 SHA256 검사값을 생성.","Générer les empreintes MD5 et SHA256.","MD5- und SHA256-Prüfsummen erzeugen.","Genera comprobaciones MD5 y SHA256.","Gere verificações MD5 e SHA256.","إنشاء قيم MD5 وSHA256 للتحقق."),
 "xlsx-to-csv":L("把 Excel 工作表导出为 CSV。","Export Excel sheets as CSV.","ExcelシートをCSVへ書き出し。","Excel 시트를 CSV로 내보냅니다.","Exporter les feuilles Excel en CSV.","Excel-Blätter als CSV exportieren.","Exporta hojas de Excel a CSV.","Exporte folhas Excel para CSV.","تصدير أوراق Excel إلى CSV."),
 "csv-to-xlsx":L("把 CSV / TSV 转成 Excel 文件。","Convert CSV / TSV into Excel files.","CSV / TSVをExcelへ変換。","CSV / TSV를 Excel 파일로 변환.","Convertir CSV / TSV en fichiers Excel.","CSV / TSV in Excel-Dateien umwandeln.","Convierte CSV / TSV en archivos Excel.","Converta CSV / TSV em ficheiros Excel.","تحويل CSV / TSV إلى ملفات Excel."),
 "docx-to-txt":L("提取 DOCX 正文为 TXT。","Extract DOCX text to TXT.","DOCX本文をTXTへ抽出。","DOCX 본문을 TXT로 추출.","Extraire le texte DOCX en TXT.","DOCX-Text als TXT extrahieren.","Extrae texto DOCX a TXT.","Extraia texto DOCX para TXT.","استخراج نص DOCX إلى TXT."),
 "pptx-to-txt":L("提取 PPTX 幻灯片文字为 TXT。","Extract PPTX slide text to TXT.","PPTXスライド文字をTXTへ抽出。","PPTX 슬라이드 텍스트를 TXT로 추출.","Extraire le texte des diapositives PPTX en TXT.","PPTX-Folientext als TXT extrahieren.","Extrae texto de diapositivas PPTX a TXT.","Extraia texto dos slides PPTX para TXT.","استخراج نص شرائح PPTX إلى TXT."),
 "json-formatter":L("格式化、压缩并检查 JSON。","Format, minify and validate JSON.","JSONの整形・圧縮・確認。","JSON 서식·압축·검사를 수행.","Formater, minifier et vérifier le JSON.","JSON formatieren, minimieren und prüfen.","Formatea, minimiza y valida JSON.","Formate, compacte e valide JSON.","تنسيق JSON وضغطه والتحقق منه."),
 "timestamp-converter":L("在 Unix 时间戳与可读时间之间转换。","Convert between Unix timestamps and readable time.","Unixタイムスタンプと日時を相互変換。","Unix 타임스탬프와 읽을 수 있는 시간 변환.","Convertir horodatages Unix et dates lisibles.","Unix-Zeitstempel und lesbare Zeit umwandeln.","Convierte marcas Unix y fecha legible.","Converta timestamps Unix e hora legível.","التحويل بين توقيت Unix والوقت المقروء."),
 "qr-code-generator":L("把文本或链接生成二维码。","Create a QR code from text or a link.","テキストやURLからQRコードを生成。","텍스트나 링크로 QR 코드를 생성.","Créer un QR code à partir d’un texte ou lien.","QR-Code aus Text oder Link erstellen.","Crea un QR desde texto o enlace.","Crie QR a partir de texto ou link.","إنشاء QR من نص أو رابط."),
 "qr-code-reader":L("读取二维码里的文本或链接。","Read text or links from a QR code.","QRコード内の文字やURLを読取。","QR 코드의 텍스트나 링크를 읽습니다.","Lire le texte ou lien d’un QR code.","Text oder Links aus QR-Code lesen.","Lee texto o enlaces de un QR.","Leia texto ou links de um QR.","قراءة النص أو الرابط من رمز QR."),
 "merge-pdf":L("按顺序把多个 PDF 合成一个文件。","Merge multiple PDFs into one file in order.","複数PDFを順番に1つへ結合。","여러 PDF를 순서대로 하나로 합칩니다.","Fusionner plusieurs PDF en un seul dans l’ordre.","Mehrere PDFs in Reihenfolge zusammenführen.","Une varios PDF en un solo archivo y en orden.","Junte vários PDF num só ficheiro pela ordem.","دمج عدة ملفات PDF في ملف واحد بالترتيب."),
 "split-pdf":L("把 PDF 按页拆成独立文件。","Split a PDF into separate page files.","PDFをページごとのファイルに分割。","PDF를 페이지별 파일로 분할.","Diviser un PDF en fichiers page par page.","PDF in einzelne Seitendateien aufteilen.","Divide un PDF en archivos por página.","Divida PDF em ficheiros por página.","تقسيم PDF إلى ملفات منفصلة لكل صفحة."),
 "compress-pdf":L("减小扫描件和图片型 PDF 的体积。","Reduce the size of scanned and image-heavy PDFs.","スキャン・画像中心PDFの容量を縮小。","스캔·이미지 중심 PDF 용량을 줄입니다.","Réduire la taille des PDF scannés ou riches en images.","Gescanntes oder bildlastiges PDF verkleinern.","Reduce PDF escaneados o con muchas imágenes.","Reduza PDF digitalizados ou com muitas imagens.","تقليل حجم ملفات PDF الممسوحة أو الغنية بالصور."),
 "image-to-pdf":L("把多张图片按顺序生成一个 PDF。","Create one PDF from multiple images in order.","複数画像を順番に1つのPDFへ。","여러 이미지를 순서대로 하나의 PDF로 만듭니다.","Créer un PDF à partir de plusieurs images dans l’ordre.","Mehrere Bilder in Reihenfolge zu einem PDF zusammenstellen.","Crea un PDF con varias imágenes en orden.","Crie um PDF com várias imagens por ordem.","إنشاء PDF واحد من عدة صور بالترتيب."),
 "pdf-to-jpg":L("把 PDF 每一页导出为 JPG。","Export every PDF page as JPG.","PDF各ページをJPGへ書き出し。","PDF 각 페이지를 JPG로 내보냅니다.","Exporter chaque page PDF en JPG.","Jede PDF-Seite als JPG exportieren.","Exporta cada página PDF como JPG.","Exporte cada página PDF como JPG.","تصدير كل صفحة PDF بصيغة JPG.")
};
export const toolCardLine=(lang:LingxiLang,slug:string,kind:keyof typeof GENERIC,fallbackZh:string,fallbackEn:string)=>{
 const special=SUMMARY[slug]?.[lang]||SIMPLE[slug]?.[lang];
 if(special)return special;
 if(lang==="zh"&&fallbackZh)return fallbackZh.replace(/浏览器本地|本地完成|本地处理|文件不上传服务器|不上传服务器|不上传灵犀场服务器|全部在浏览器本地处理|，本地完成|，本地处理|。本地处理/g,"").replace(/s{2,}/g," ").trim();
 if(lang==="en"&&fallbackEn)return fallbackEn.replace(/entirely in your browser|locally in your browser|locally|local only|nothing is uploaded|without uploading it/gi,"").replace(/s{2,}/g," ").trim();
 return GENERIC[kind]?.[lang]||GENERIC.utility[lang];
};
