import type {LingxiLang} from "@/lib/lingxi-i18n";
type PdfCopy = Record<"upload"|"opening"|"unsupported"|"prev"|"next"|"page"|"rotate"|"edit"|"editHint"|"textPlaceholder"|"addText"|"addCover"|"addImage"|"stamp"|"stampHint"|"clear"|"seam"|"apply"|"range"|"rangeHint"|"invalid"|"preview"|"working"|"confirm"|"delete"|"ready",string>;
export const PDF_EDITOR_COPY = {
  "zh": {
    "upload": "选择文件",
    "opening": "正在打开文件…",
    "unsupported": "请改用 PDF 文件后重试。",
    "prev": "上一页",
    "next": "下一页",
    "page": "第",
    "rotate": "旋转当前页",
    "edit": "直接在页面上编辑",
    "editHint": "添加后即可在页面上看到效果，拖动可调整位置。",
    "textPlaceholder": "输入要添加的文字",
    "addText": "添加文字",
    "addCover": "添加遮盖",
    "addImage": "添加图片",
    "stamp": "签名 / 印章",
    "stampHint": "选择清晰的签名或印章图片，会自动去除白底和多余空白。",
    "clear": "清空当前页编辑",
    "seam": "骑缝章",
    "apply": "按选择页切分盖章",
    "range": "导出页码",
    "rangeHint": "例如 1-10,12；留空表示全部页面。",
    "invalid": "请填写有效页码，例如 1-3,5，且不要超过文件总页数。",
    "preview": "预览效果",
    "working": "正在处理…",
    "confirm": "保存文件",
    "delete": "删除",
    "ready": "预览"
  },
  "en": {
    "upload": "Choose file",
    "opening": "Opening file…",
    "unsupported": "Please try again with a PDF file.",
    "prev": "Previous",
    "next": "Next",
    "page": "Page",
    "rotate": "Rotate page",
    "edit": "Edit directly on the page",
    "editHint": "See changes on the page as you add them. Drag to reposition.",
    "textPlaceholder": "Text to add",
    "addText": "Add text",
    "addCover": "Add cover",
    "addImage": "Add image",
    "stamp": "Signature / stamp",
    "stampHint": "Choose a clear signature or stamp image. White backgrounds and empty margins are removed.",
    "clear": "Clear current page",
    "seam": "Cross-page stamp",
    "apply": "Slice across selected pages",
    "range": "Export pages",
    "rangeHint": "For example, 1-10,12. Leave blank for all pages.",
    "invalid": "Enter valid pages, such as 1-3,5, within the document’s page count.",
    "preview": "Preview",
    "working": "Working…",
    "confirm": "Save file",
    "delete": "Delete",
    "ready": "Preview"
  },
  "ja": {
    "upload": "ファイルを選択",
    "opening": "ファイルを開いています…",
    "unsupported": "PDFファイルでお試しください。",
    "prev": "前へ",
    "next": "次へ",
    "page": "ページ",
    "rotate": "ページを回転",
    "edit": "ページ上で編集",
    "editHint": "追加するとページに表示されます。ドラッグして位置を調整できます。",
    "textPlaceholder": "追加する文字",
    "addText": "文字を追加",
    "addCover": "白塗りを追加",
    "addImage": "画像を追加",
    "stamp": "署名画像 / 印章",
    "stampHint": "鮮明な署名や印鑑の画像を選んでください。白い背景や余白は自動で除きます。",
    "clear": "このページをクリア",
    "seam": "ページまたぎ印章",
    "apply": "選択ページに分割配置",
    "range": "出力ページ",
    "rangeHint": "例：1-10,12。空欄なら全ページです。",
    "invalid": "1-3,5のように、文書のページ数内で入力してください。",
    "preview": "プレビュー",
    "working": "処理中…",
    "confirm": "ファイルを保存",
    "delete": "削除",
    "ready": "プレビュー"
  },
  "ko": {
    "upload": "파일 선택",
    "opening": "파일을 여는 중…",
    "unsupported": "PDF 파일로 다시 시도하세요.",
    "prev": "이전",
    "next": "다음",
    "page": "페이지",
    "rotate": "페이지 회전",
    "edit": "페이지에서 바로 편집",
    "editHint": "추가한 항목을 바로 확인하고 드래그해 위치를 바꾸세요.",
    "textPlaceholder": "추가할 텍스트",
    "addText": "텍스트 추가",
    "addCover": "가림 추가",
    "addImage": "이미지 추가",
    "stamp": "서명 이미지 / 도장",
    "stampHint": "선명한 서명이나 도장 이미지를 선택하세요. 흰 배경과 여백을 자동으로 제거합니다.",
    "clear": "현재 페이지 지우기",
    "seam": "페이지 연결 도장",
    "apply": "선택 페이지에 분할 적용",
    "range": "내보낼 페이지",
    "rangeHint": "예: 1-10,12. 비워 두면 전체 페이지를 선택합니다.",
    "invalid": "문서의 총 페이지 수 내에서 1-3,5처럼 입력하세요.",
    "preview": "미리 보기",
    "working": "처리 중…",
    "confirm": "파일 저장",
    "delete": "삭제",
    "ready": "미리 보기"
  },
  "fr": {
    "upload": "Choisir un fichier",
    "opening": "Ouverture du fichier…",
    "unsupported": "Réessayez avec un fichier PDF.",
    "prev": "Précédent",
    "next": "Suivant",
    "page": "Page",
    "rotate": "Pivoter la page",
    "edit": "Modifier directement la page",
    "editHint": "Vos ajouts s’affichent sur la page. Faites-les glisser pour les déplacer.",
    "textPlaceholder": "Texte à ajouter",
    "addText": "Ajouter du texte",
    "addCover": "Ajouter un masque",
    "addImage": "Ajouter une image",
    "stamp": "Image de signature / cachet",
    "stampHint": "Choisissez une image nette. Le fond blanc et les marges vides sont retirés.",
    "clear": "Effacer cette page",
    "seam": "Cachet sur plusieurs pages",
    "apply": "Répartir sur les pages choisies",
    "range": "Pages à exporter",
    "rangeHint": "Exemple : 1-10,12. Laissez vide pour toutes les pages.",
    "invalid": "Saisissez des pages valides, par exemple 1-3,5, sans dépasser le nombre total.",
    "preview": "Aperçu",
    "working": "Traitement…",
    "confirm": "Enregistrer le fichier",
    "delete": "Supprimer",
    "ready": "Aperçu"
  },
  "de": {
    "upload": "Datei auswählen",
    "opening": "Datei wird geöffnet…",
    "unsupported": "Versuchen Sie es mit einer PDF-Datei.",
    "prev": "Zurück",
    "next": "Weiter",
    "page": "Seite",
    "rotate": "Seite drehen",
    "edit": "Direkt auf der Seite bearbeiten",
    "editHint": "Ergänzungen erscheinen direkt auf der Seite. Zum Verschieben ziehen.",
    "textPlaceholder": "Text hinzufügen",
    "addText": "Text hinzufügen",
    "addCover": "Abdeckung hinzufügen",
    "addImage": "Bild hinzufügen",
    "stamp": "Signaturbild / Stempel",
    "stampHint": "Wählen Sie ein klares Bild. Weißer Hintergrund und leere Ränder werden entfernt.",
    "clear": "Diese Seite leeren",
    "seam": "Seitenübergreifender Stempel",
    "apply": "Auf ausgewählte Seiten verteilen",
    "range": "Exportseiten",
    "rangeHint": "Beispiel: 1-10,12. Leer lassen für alle Seiten.",
    "invalid": "Geben Sie gültige Seiten wie 1-3,5 innerhalb der Seitenzahl ein.",
    "preview": "Vorschau",
    "working": "Wird verarbeitet…",
    "confirm": "Datei speichern",
    "delete": "Löschen",
    "ready": "Vorschau"
  },
  "es": {
    "upload": "Elegir archivo",
    "opening": "Abriendo archivo…",
    "unsupported": "Inténtalo de nuevo con un PDF.",
    "prev": "Anterior",
    "next": "Siguiente",
    "page": "Página",
    "rotate": "Girar página",
    "edit": "Editar directamente en la página",
    "editHint": "Los cambios aparecen en la página. Arrástralos para colocarlos.",
    "textPlaceholder": "Texto que quieres añadir",
    "addText": "Añadir texto",
    "addCover": "Añadir cobertura",
    "addImage": "Añadir imagen",
    "stamp": "Imagen de firma / sello",
    "stampHint": "Elige una imagen nítida. Se eliminan el fondo blanco y los márgenes vacíos.",
    "clear": "Limpiar esta página",
    "seam": "Sello entre páginas",
    "apply": "Dividir entre las páginas elegidas",
    "range": "Páginas a exportar",
    "rangeHint": "Por ejemplo: 1-10,12. Déjalo vacío para todas las páginas.",
    "invalid": "Introduce páginas válidas, como 1-3,5, sin superar el total.",
    "preview": "Vista previa",
    "working": "Procesando…",
    "confirm": "Guardar archivo",
    "delete": "Eliminar",
    "ready": "Vista previa"
  },
  "pt": {
    "upload": "Escolher arquivo",
    "opening": "Abrindo arquivo…",
    "unsupported": "Tente novamente com um arquivo PDF.",
    "prev": "Anterior",
    "next": "Próxima",
    "page": "Página",
    "rotate": "Girar página",
    "edit": "Editar diretamente na página",
    "editHint": "Os itens aparecem na página. Arraste para ajustar a posição.",
    "textPlaceholder": "Texto a adicionar",
    "addText": "Adicionar texto",
    "addCover": "Adicionar cobertura",
    "addImage": "Adicionar imagem",
    "stamp": "Imagem de assinatura / carimbo",
    "stampHint": "Escolha uma imagem nítida. O fundo branco e as margens vazias são removidos.",
    "clear": "Limpar esta página",
    "seam": "Carimbo entre páginas",
    "apply": "Dividir nas páginas escolhidas",
    "range": "Páginas para exportar",
    "rangeHint": "Exemplo: 1-10,12. Deixe em branco para todas as páginas.",
    "invalid": "Informe páginas válidas, como 1-3,5, sem exceder o total.",
    "preview": "Prévia",
    "working": "Processando…",
    "confirm": "Salvar arquivo",
    "delete": "Excluir",
    "ready": "Prévia"
  },
  "ar": {
    "upload": "اختيار ملف",
    "opening": "جارٍ فتح الملف…",
    "unsupported": "أعد المحاولة باستخدام ملف PDF.",
    "prev": "السابق",
    "next": "التالي",
    "page": "الصفحة",
    "rotate": "تدوير الصفحة",
    "edit": "التحرير مباشرة على الصفحة",
    "editHint": "تظهر الإضافات على الصفحة مباشرة. اسحبها لتغيير موضعها.",
    "textPlaceholder": "النص المراد إضافته",
    "addText": "إضافة نص",
    "addCover": "إضافة تغطية",
    "addImage": "إضافة صورة",
    "stamp": "صورة توقيع / ختم",
    "stampHint": "اختر صورة واضحة للتوقيع أو الختم. تُزال الخلفية البيضاء والهوامش الفارغة.",
    "clear": "مسح تعديلات الصفحة",
    "seam": "ختم ممتد بين الصفحات",
    "apply": "توزيعه على الصفحات المحددة",
    "range": "صفحات التصدير",
    "rangeHint": "مثل 1-10,12. اتركه فارغًا لاختيار جميع الصفحات.",
    "invalid": "أدخل صفحات صحيحة مثل 1-3,5 دون تجاوز عدد صفحات المستند.",
    "preview": "معاينة",
    "working": "جارٍ المعالجة…",
    "confirm": "حفظ الملف",
    "delete": "حذف",
    "ready": "معاينة"
  }
} satisfies Record<LingxiLang,PdfCopy>;
