import type {LingxiLang} from "@/lib/lingxi-i18n";

export const PLAIN_COPY = {
  "choose": {
    "zh": "选择文件",
    "en": "Choose file",
    "ja": "ファイルを選択",
    "ko": "파일 선택",
    "fr": "Choisir un fichier",
    "de": "Datei auswählen",
    "es": "Elegir archivo",
    "pt": "Escolher arquivo",
    "ar": "اختيار ملف"
  },
  "preview": {
    "zh": "预览效果",
    "en": "Preview",
    "ja": "プレビュー",
    "ko": "미리 보기",
    "fr": "Aperçu",
    "de": "Vorschau",
    "es": "Vista previa",
    "pt": "Prévia",
    "ar": "معاينة"
  },
  "save": {
    "zh": "保存文件",
    "en": "Save file",
    "ja": "ファイルを保存",
    "ko": "파일 저장",
    "fr": "Enregistrer le fichier",
    "de": "Datei speichern",
    "es": "Guardar archivo",
    "pt": "Salvar arquivo",
    "ar": "حفظ الملف"
  },
  "working": {
    "zh": "正在处理…",
    "en": "Working…",
    "ja": "処理中…",
    "ko": "처리 중…",
    "fr": "Traitement…",
    "de": "Wird verarbeitet…",
    "es": "Procesando…",
    "pt": "Processando…",
    "ar": "جارٍ المعالجة…"
  },
  "ready": {
    "zh": "处理完成，可以保存文件。",
    "en": "Ready. You can save the file.",
    "ja": "完了しました。ファイルを保存できます。",
    "ko": "완료되었습니다. 파일을 저장하세요.",
    "fr": "Terminé. Vous pouvez enregistrer le fichier.",
    "de": "Fertig. Die Datei kann gespeichert werden.",
    "es": "Listo. Ya puedes guardar el archivo.",
    "pt": "Pronto. Você pode salvar o arquivo.",
    "ar": "اكتملت المعالجة. يمكنك حفظ الملف."
  },
  "fileError": {
    "zh": "无法处理这个文件。请重新选择完整的文件，或换一个较小的文件重试。",
    "en": "This file could not be processed. Select the original file again or try a smaller file.",
    "ja": "このファイルを処理できません。元のファイルを選び直すか、小さいファイルでお試しください。",
    "ko": "파일을 처리하지 못했습니다. 원본 파일을 다시 선택하거나 더 작은 파일로 시도하세요.",
    "fr": "Impossible de traiter ce fichier. Sélectionnez à nouveau l’original ou essayez un fichier plus petit.",
    "de": "Diese Datei konnte nicht verarbeitet werden. Wählen Sie das Original erneut oder eine kleinere Datei.",
    "es": "No se pudo procesar el archivo. Selecciona el original otra vez o prueba uno más pequeño.",
    "pt": "Não foi possível processar o arquivo. Selecione o original novamente ou tente um arquivo menor.",
    "ar": "تعذرت معالجة الملف. اختر الملف الأصلي مجددًا أو جرّب ملفًا أصغر."
  },
  "pdfError": {
    "zh": "无法打开这个 PDF。请确认文件能正常打开；如有密码，请先解锁后重试。",
    "en": "This PDF could not be opened. Check that it opens correctly and unlock it first if it has a password.",
    "ja": "PDFを開けません。ファイルが正常に開くか確認し、パスワードがある場合は解除してお試しください。",
    "ko": "PDF를 열지 못했습니다. 정상적으로 열리는지 확인하고 암호가 있으면 해제한 뒤 다시 시도하세요.",
    "fr": "Impossible d’ouvrir ce PDF. Vérifiez qu’il s’ouvre correctement et retirez son mot de passe si nécessaire.",
    "de": "Die PDF konnte nicht geöffnet werden. Prüfen Sie die Datei und entfernen Sie gegebenenfalls den Passwortschutz.",
    "es": "No se pudo abrir el PDF. Comprueba que se abre correctamente y quita la contraseña si la tiene.",
    "pt": "Não foi possível abrir o PDF. Verifique se abre normalmente e remova a senha, se houver.",
    "ar": "تعذر فتح ملف PDF. تحقق من سلامة الملف وأزل كلمة المرور أولًا إن وجدت."
  },
  "previewError": {
    "zh": "预览没有完成。请减少所选页数后重试。",
    "en": "Preview could not finish. Select fewer pages and try again.",
    "ja": "プレビューできませんでした。ページ数を減らしてお試しください。",
    "ko": "미리 보기를 완료하지 못했습니다. 페이지 수를 줄여 다시 시도하세요.",
    "fr": "L’aperçu n’a pas abouti. Sélectionnez moins de pages et réessayez.",
    "de": "Die Vorschau konnte nicht erstellt werden. Wählen Sie weniger Seiten und versuchen Sie es erneut.",
    "es": "No se pudo mostrar la vista previa. Selecciona menos páginas e inténtalo de nuevo.",
    "pt": "A prévia não foi concluída. Selecione menos páginas e tente novamente.",
    "ar": "تعذرت المعاينة. اختر صفحات أقل ثم أعد المحاولة."
  },
  "imageError": {
    "zh": "无法添加这张图片。请换用 PNG 或 JPG 图片重试。",
    "en": "This image could not be added. Try a PNG or JPG image.",
    "ja": "画像を追加できません。PNGまたはJPGでお試しください。",
    "ko": "이미지를 추가하지 못했습니다. PNG 또는 JPG로 다시 시도하세요.",
    "fr": "Impossible d’ajouter cette image. Essayez une image PNG ou JPG.",
    "de": "Das Bild konnte nicht hinzugefügt werden. Versuchen Sie PNG oder JPG.",
    "es": "No se pudo añadir la imagen. Prueba con PNG o JPG.",
    "pt": "Não foi possível adicionar a imagem. Tente uma imagem PNG ou JPG.",
    "ar": "تعذرت إضافة الصورة. جرّب صورة PNG أو JPG."
  },
  "saveError": {
    "zh": "未能保存文件。请允许浏览器下载后重试。",
    "en": "The file could not be saved. Allow downloads in your browser and try again.",
    "ja": "保存できませんでした。ブラウザでダウンロードを許可してお試しください。",
    "ko": "파일을 저장하지 못했습니다. 브라우저에서 다운로드를 허용한 뒤 다시 시도하세요.",
    "fr": "Le fichier n’a pas pu être enregistré. Autorisez les téléchargements et réessayez.",
    "de": "Die Datei konnte nicht gespeichert werden. Erlauben Sie Downloads und versuchen Sie es erneut.",
    "es": "No se pudo guardar el archivo. Permite las descargas e inténtalo de nuevo.",
    "pt": "Não foi possível salvar o arquivo. Permita downloads no navegador e tente novamente.",
    "ar": "تعذر حفظ الملف. اسمح بالتنزيل في المتصفح ثم أعد المحاولة."
  },
  "draftSaved": {
    "zh": "当前任务已保存在此设备。",
    "en": "Your task is saved on this device.",
    "ja": "作業をこの端末に保存しました。",
    "ko": "현재 기기에 작업을 저장했습니다.",
    "fr": "Votre tâche est enregistrée sur cet appareil.",
    "de": "Die Aufgabe ist auf diesem Gerät gespeichert.",
    "es": "La tarea está guardada en este dispositivo.",
    "pt": "A tarefa foi salva neste dispositivo.",
    "ar": "تم حفظ المهمة على هذا الجهاز."
  },
  "draftSaving": {
    "zh": "正在保存任务…",
    "en": "Saving your task…",
    "ja": "作業を保存中…",
    "ko": "작업 저장 중…",
    "fr": "Enregistrement de la tâche…",
    "de": "Aufgabe wird gespeichert…",
    "es": "Guardando la tarea…",
    "pt": "Salvando a tarefa…",
    "ar": "جارٍ حفظ المهمة…"
  },
  "draftError": {
    "zh": "任务未能保存。请释放设备存储空间后重试，并暂时保持页面打开。",
    "en": "Your task could not be saved. Free up device storage and try again. Keep this page open for now.",
    "ja": "作業を保存できません。空き容量を増やしてお試しください。このページは開いたままにしてください。",
    "ko": "작업을 저장하지 못했습니다. 저장 공간을 확보한 뒤 다시 시도하세요. 이 페이지를 열어 두세요.",
    "fr": "La tâche n’a pas pu être enregistrée. Libérez de l’espace et réessayez. Gardez cette page ouverte.",
    "de": "Die Aufgabe konnte nicht gespeichert werden. Schaffen Sie Speicherplatz und versuchen Sie es erneut. Lassen Sie diese Seite geöffnet.",
    "es": "No se pudo guardar la tarea. Libera espacio e inténtalo de nuevo. Mantén esta página abierta.",
    "pt": "Não foi possível salvar a tarefa. Libere espaço e tente novamente. Mantenha esta página aberta.",
    "ar": "تعذر حفظ المهمة. أفرغ مساحة تخزين ثم أعد المحاولة. أبقِ هذه الصفحة مفتوحة."
  },
  "restoreError": {
    "zh": "无法恢复上次任务。请重新选择原文件后继续。",
    "en": "Your previous task could not be restored. Select the original file to continue.",
    "ja": "前の作業を復元できません。元のファイルを選び直してください。",
    "ko": "이전 작업을 복원하지 못했습니다. 원본 파일을 다시 선택하세요.",
    "fr": "Impossible de restaurer la tâche précédente. Sélectionnez le fichier d’origine.",
    "de": "Die letzte Aufgabe konnte nicht wiederhergestellt werden. Wählen Sie die Originaldatei.",
    "es": "No se pudo recuperar la tarea anterior. Selecciona el archivo original.",
    "pt": "Não foi possível restaurar a tarefa anterior. Selecione o arquivo original.",
    "ar": "تعذر استعادة المهمة السابقة. اختر الملف الأصلي للمتابعة."
  },
  "oneFile": {
    "zh": "请每次选择一个文件。",
    "en": "Choose one file at a time.",
    "ja": "ファイルは1つずつ選んでください。",
    "ko": "파일을 하나씩 선택하세요.",
    "fr": "Choisissez un fichier à la fois.",
    "de": "Wählen Sie jeweils eine Datei.",
    "es": "Elige un archivo cada vez.",
    "pt": "Escolha um arquivo por vez.",
    "ar": "اختر ملفًا واحدًا في كل مرة."
  },
  "fileLimit": {
    "zh": "一次最多选择 {count} 个文件，请减少后重试。",
    "en": "Choose up to {count} files at a time. Remove some and try again.",
    "ja": "一度に選べるのは{count}ファイルまでです。数を減らしてください。",
    "ko": "한 번에 {count}개까지 선택할 수 있습니다. 파일 수를 줄여 주세요.",
    "fr": "Choisissez au maximum {count} fichiers à la fois. Réduisez la sélection.",
    "de": "Wählen Sie höchstens {count} Dateien. Verringern Sie die Auswahl.",
    "es": "Elige hasta {count} archivos a la vez. Reduce la selección.",
    "pt": "Escolha até {count} arquivos por vez. Reduza a seleção.",
    "ar": "اختر حتى {count} ملفات في كل مرة. قلّل العدد ثم حاول مجددًا."
  },
  "pageCount": {
    "zh": "共 {count} 页",
    "en": "{count} pages",
    "ja": "{count}ページ",
    "ko": "{count}페이지",
    "fr": "{count} pages",
    "de": "{count} Seiten",
    "es": "{count} páginas",
    "pt": "{count} páginas",
    "ar": "{count} صفحات"
  },
  "page": {
    "zh": "第 {count} 页",
    "en": "Page {count}",
    "ja": "{count}ページ目",
    "ko": "{count}페이지",
    "fr": "Page {count}",
    "de": "Seite {count}",
    "es": "Página {count}",
    "pt": "Página {count}",
    "ar": "الصفحة {count}"
  },
  "exportCount": {
    "zh": "已选择 {count} 页",
    "en": "{count} pages selected",
    "ja": "{count}ページを選択中",
    "ko": "{count}페이지 선택됨",
    "fr": "{count} pages sélectionnées",
    "de": "{count} Seiten ausgewählt",
    "es": "{count} páginas seleccionadas",
    "pt": "{count} páginas selecionadas",
    "ar": "تم اختيار {count} صفحات"
  },
  "appliedCount": {
    "zh": "已添加到 {count} 页",
    "en": "Added to {count} pages",
    "ja": "{count}ページに追加しました",
    "ko": "{count}페이지에 추가됨",
    "fr": "Ajouté à {count} pages",
    "de": "Auf {count} Seiten eingefügt",
    "es": "Añadido a {count} páginas",
    "pt": "Adicionado a {count} páginas",
    "ar": "أُضيف إلى {count} صفحات"
  },
  "right": {
    "zh": "右侧",
    "en": "Right",
    "ja": "右",
    "ko": "오른쪽",
    "fr": "Droite",
    "de": "Rechts",
    "es": "Derecha",
    "pt": "Direita",
    "ar": "يمين"
  },
  "left": {
    "zh": "左侧",
    "en": "Left",
    "ja": "左",
    "ko": "왼쪽",
    "fr": "Gauche",
    "de": "Links",
    "es": "Izquierda",
    "pt": "Esquerda",
    "ar": "يسار"
  },
  "top": {
    "zh": "顶部",
    "en": "Top",
    "ja": "上",
    "ko": "위",
    "fr": "Haut",
    "de": "Oben",
    "es": "Arriba",
    "pt": "Acima",
    "ar": "أعلى"
  },
  "bottom": {
    "zh": "底部",
    "en": "Bottom",
    "ja": "下",
    "ko": "아래",
    "fr": "Bas",
    "de": "Unten",
    "es": "Abajo",
    "pt": "Abaixo",
    "ar": "أسفل"
  },
  "text": {
    "zh": "文字",
    "en": "Text",
    "ja": "文字",
    "ko": "텍스트",
    "fr": "Texte",
    "de": "Text",
    "es": "Texto",
    "pt": "Texto",
    "ar": "نص"
  },
  "cover": {
    "zh": "遮盖",
    "en": "Cover",
    "ja": "覆い",
    "ko": "가리기",
    "fr": "Masque",
    "de": "Abdeckung",
    "es": "Cobertura",
    "pt": "Cobertura",
    "ar": "غطاء"
  },
  "image": {
    "zh": "图片",
    "en": "Image",
    "ja": "画像",
    "ko": "이미지",
    "fr": "Image",
    "de": "Bild",
    "es": "Imagen",
    "pt": "Imagem",
    "ar": "صورة"
  },
  "x": {
    "zh": "水平位置",
    "en": "Horizontal position",
    "ja": "横位置",
    "ko": "가로 위치",
    "fr": "Position horizontale",
    "de": "Horizontale Position",
    "es": "Posición horizontal",
    "pt": "Posição horizontal",
    "ar": "الموضع الأفقي"
  },
  "y": {
    "zh": "垂直位置",
    "en": "Vertical position",
    "ja": "縦位置",
    "ko": "세로 위치",
    "fr": "Position verticale",
    "de": "Vertikale Position",
    "es": "Posición vertical",
    "pt": "Posição vertical",
    "ar": "الموضع العمودي"
  },
  "w": {
    "zh": "宽度",
    "en": "Width",
    "ja": "幅",
    "ko": "너비",
    "fr": "Largeur",
    "de": "Breite",
    "es": "Ancho",
    "pt": "Largura",
    "ar": "العرض"
  },
  "h": {
    "zh": "高度",
    "en": "Height",
    "ja": "高さ",
    "ko": "높이",
    "fr": "Hauteur",
    "de": "Höhe",
    "es": "Alto",
    "pt": "Altura",
    "ar": "الارتفاع"
  },
  "reorder": {
    "zh": "使用上下箭头调整页面顺序。",
    "en": "Use the arrows to reorder pages.",
    "ja": "上下の矢印でページの順序を変えられます。",
    "ko": "위아래 화살표로 페이지 순서를 바꾸세요.",
    "fr": "Utilisez les flèches pour réorganiser les pages.",
    "de": "Ändern Sie die Reihenfolge mit den Pfeilen.",
    "es": "Usa las flechas para ordenar las páginas.",
    "pt": "Use as setas para ordenar as páginas.",
    "ar": "استخدم الأسهم لتغيير ترتيب الصفحات."
  },
  "clearPages": {
    "zh": "清空页面",
    "en": "Clear pages",
    "ja": "ページをすべて削除",
    "ko": "페이지 비우기",
    "fr": "Vider les pages",
    "de": "Seiten leeren",
    "es": "Vaciar páginas",
    "pt": "Limpar páginas",
    "ar": "مسح الصفحات"
  },
  "up": {
    "zh": "上移",
    "en": "Move up",
    "ja": "上へ",
    "ko": "위로",
    "fr": "Monter",
    "de": "Nach oben",
    "es": "Subir",
    "pt": "Mover para cima",
    "ar": "تحريك لأعلى"
  },
  "down": {
    "zh": "下移",
    "en": "Move down",
    "ja": "下へ",
    "ko": "아래로",
    "fr": "Descendre",
    "de": "Nach unten",
    "es": "Bajar",
    "pt": "Mover para baixo",
    "ar": "تحريك لأسفل"
  },
  "rotate": {
    "zh": "旋转页面",
    "en": "Rotate page",
    "ja": "ページを回転",
    "ko": "페이지 회전",
    "fr": "Pivoter la page",
    "de": "Seite drehen",
    "es": "Girar página",
    "pt": "Girar página",
    "ar": "تدوير الصفحة"
  },
  "delete": {
    "zh": "删除",
    "en": "Delete",
    "ja": "削除",
    "ko": "삭제",
    "fr": "Supprimer",
    "de": "Löschen",
    "es": "Eliminar",
    "pt": "Excluir",
    "ar": "حذف"
  },
  "price": {
    "zh": "查看价格",
    "en": "View price",
    "ja": "料金を確認",
    "ko": "가격 보기",
    "fr": "Voir le prix",
    "de": "Preis ansehen",
    "es": "Ver precio",
    "pt": "Ver preço",
    "ar": "عرض السعر"
  },
  "paymentError": {
    "zh": "暂时无法打开付款，请稍后重试。",
    "en": "Payment could not be opened. Try again later.",
    "ja": "支払いを開けません。しばらくしてからお試しください。",
    "ko": "결제를 열지 못했습니다. 잠시 후 다시 시도하세요.",
    "fr": "Impossible d’ouvrir le paiement. Réessayez plus tard.",
    "de": "Die Zahlung kann gerade nicht geöffnet werden. Versuchen Sie es später erneut.",
    "es": "No se pudo abrir el pago. Inténtalo más tarde.",
    "pt": "Não foi possível abrir o pagamento. Tente novamente mais tarde.",
    "ar": "تعذر فتح الدفع. حاول لاحقًا."
  },
  "paymentStatus": {
    "zh": "暂时无法确认付款状态，请到订单中查看后继续。",
    "en": "Payment status is unavailable. Check your order before continuing.",
    "ja": "支払い状況を確認できません。注文を確認してから続けてください。",
    "ko": "결제 상태를 확인할 수 없습니다. 주문을 확인한 뒤 계속하세요.",
    "fr": "Statut du paiement indisponible. Vérifiez votre commande avant de continuer.",
    "de": "Zahlungsstatus nicht verfügbar. Prüfen Sie vor dem Fortfahren Ihre Bestellung.",
    "es": "No se puede consultar el pago. Revisa tu pedido antes de continuar.",
    "pt": "O status do pagamento está indisponível. Confira seu pedido antes de continuar.",
    "ar": "حالة الدفع غير متاحة. تحقق من طلبك قبل المتابعة."
  },
  "openingPayment": {
    "zh": "正在打开付款…",
    "en": "Opening payment…",
    "ja": "支払いを開いています…",
    "ko": "결제를 여는 중…",
    "fr": "Ouverture du paiement…",
    "de": "Zahlung wird geöffnet…",
    "es": "Abriendo el pago…",
    "pt": "Abrindo o pagamento…",
    "ar": "جارٍ فتح الدفع…"
  },
  "minute": {
    "zh": "分钟",
    "en": "minutes",
    "ja": "分",
    "ko": "분",
    "fr": "minutes",
    "de": "Minuten",
    "es": "minutos",
    "pt": "minutos",
    "ar": "دقائق"
  },
  "second": {
    "zh": "秒",
    "en": "seconds",
    "ja": "秒",
    "ko": "초",
    "fr": "secondes",
    "de": "Sekunden",
    "es": "segundos",
    "pt": "segundos",
    "ar": "ثوانٍ"
  },
  "file": {
    "zh": "文件",
    "en": "files",
    "ja": "ファイル",
    "ko": "파일",
    "fr": "fichiers",
    "de": "Dateien",
    "es": "archivos",
    "pt": "arquivos",
    "ar": "ملفات"
  },
  "email": {
    "zh": "邮箱",
    "en": "mailboxes",
    "ja": "メールボックス",
    "ko": "메일함",
    "fr": "boîtes mail",
    "de": "Postfächer",
    "es": "buzones",
    "pt": "caixas de e-mail",
    "ar": "صناديق بريد"
  },
  "use": {
    "zh": "次",
    "en": "uses",
    "ja": "回",
    "ko": "회",
    "fr": "utilisations",
    "de": "Nutzungen",
    "es": "usos",
    "pt": "usos",
    "ar": "مرات"
  },
  "food": {
    "zh": "种食物",
    "en": "foods",
    "ja": "食品",
    "ko": "음식",
    "fr": "aliments",
    "de": "Lebensmittel",
    "es": "alimentos",
    "pt": "alimentos",
    "ar": "أطعمة"
  },
  "files": {
    "zh": "文件数",
    "en": "Files",
    "ja": "ファイル数",
    "ko": "파일 수",
    "fr": "Fichiers",
    "de": "Dateien",
    "es": "Archivos",
    "pt": "Arquivos",
    "ar": "الملفات"
  },
  "pages": {
    "zh": "页数",
    "en": "Pages",
    "ja": "ページ数",
    "ko": "페이지 수",
    "fr": "Pages",
    "de": "Seiten",
    "es": "Páginas",
    "pt": "Páginas",
    "ar": "الصفحات"
  },
  "resultKB": {
    "zh": "文件大小（KB）",
    "en": "File size (KB)",
    "ja": "ファイルサイズ（KB）",
    "ko": "파일 크기(KB)",
    "fr": "Taille (Ko)",
    "de": "Dateigröße (KB)",
    "es": "Tamaño (KB)",
    "pt": "Tamanho (KB)",
    "ar": "حجم الملف (KB)"
  }
} satisfies Record<string,Record<LingxiLang,string>>;
export type PlainCopyKey = keyof typeof PLAIN_COPY;
export function plainText(lang:LingxiLang,key:PlainCopyKey,values:Record<string,string|number>={}){return Object.entries(values).reduce((s,[k,v])=>s.replaceAll("{"+k+"}",String(v)),PLAIN_COPY[key][lang]);}
export function plainMessage(lang:LingxiLang,message:string){if(message in PLAIN_COPY)return PLAIN_COPY[message as PlainCopyKey][lang];for(const row of Object.values(PLAIN_COPY)){if(Object.values(row).includes(message))return row[lang];}return message;}
