import type { ToolMeta } from "./types";

/**
 * 在线工具元数据中心。
 * 每个工具一条记录；页面 UI 与 SEO 从这里读，禁止各页复制一套文案。
 * 状态 live = 本仓库已实现本地处理；planned = 仅目录占位，不假装可用。
 */
export const TOOLS: ToolMeta[] = [
  ...[
    ["text-counter", "字数与字符统计", "Text Counter", "统计汉字、英文词、字符、行数与UTF-8字节。"],
    ["remove-duplicate-lines", "文本去重行", "Remove Duplicate Lines", "删除完全相同的重复行，保留首次出现的顺序与原始空格。"],
    ["remove-empty-lines", "删除空白行", "Remove Empty Lines", "去掉空行及只有空白的行，保留其他正文。"],
    ["url-encode-decode", "URL 编码解码", "URL Encode & Decode", "对单个URL参数进行百分号编码或解码，支持中文。"],
    ["base64-encode-decode", "Base64 编码解码", "Base64 Encode & Decode", "支持中文UTF-8文本的Base64转换；编码不等于加密。"],
  ].map(([slug, titleZh, titleEn, oneLinerZh]): ToolMeta => ({ slug, titleZh, titleEn, oneLinerZh, oneLinerEn: "Process text locally in your browser. Nothing is uploaded.", category: "utility", status: "live", localOnly: true, related: ["json-formatter", "text-counter"].filter(item => item !== slug) })),
  // —— 图片 · P0 ——
  {
    slug: "png-to-jpg",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "PNG 转 JPG",
    titleEn: "PNG to JPG",
    oneLinerZh: "浏览器本地把 PNG 转成 JPG，文件不上传服务器。",
    oneLinerEn: "Convert PNG to JPG entirely in your browser — nothing is uploaded.",
    accept: "image/png,.png",
    related: ["jpg-to-png", "compress-image", "webp-to-jpg"],
  },
  {
    slug: "jpg-to-png",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "JPG 转 PNG",
    titleEn: "JPG to PNG",
    oneLinerZh: "浏览器本地把 JPG/JPEG 转成 PNG。",
    oneLinerEn: "Convert JPG/JPEG to PNG entirely in your browser.",
    accept: "image/jpeg,.jpg,.jpeg",
    related: ["png-to-jpg", "compress-image"],
  },
  {
    slug: "webp-to-jpg",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "WebP 转 JPG / PNG",
    titleEn: "WebP to JPG / PNG",
    oneLinerZh: "把 WebP 转成更通用的 JPG 或 PNG，本地完成。",
    oneLinerEn: "Convert WebP to widely-supported JPG or PNG — local only.",
    accept: "image/webp,.webp",
    related: ["png-to-jpg", "compress-image"],
  },
  {
    slug: "compress-image",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "图片压缩",
    titleEn: "Compress Image",
    oneLinerZh: "降低图片体积，尽量保留观感。浏览器本地处理。",
    oneLinerEn: "Shrink image size while keeping visual quality. Local processing.",
    accept: "image/*,.jpg,.jpeg,.png,.webp",
    related: ["compress-image-to-100kb", "resize-image", "remove-exif"],
  },
  {
    slug: "compress-image-to-100kb",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "图片精确压缩到 100KB",
    titleEn: "Compress Image to 100KB",
    oneLinerZh: "自动逼近目标大小，尽量不超过 100KB，并保留尽可能高的质量。",
    oneLinerEn: "Automatically approach 100KB without exceeding it, keeping the highest possible quality.",
    accept: "image/*,.jpg,.jpeg,.png,.webp",
    related: ["compress-image-to-50kb", "compress-image-to-200kb", "compress-image"],
  },
  {
    slug: "compress-image-to-20kb",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "图片精确压缩到 20KB",
    titleEn: "Compress Image to 20KB",
    oneLinerZh: "报名照、头像等场景：自动压到约 20KB 以内。",
    oneLinerEn: "For avatars and form uploads: approach 20KB automatically.",
    accept: "image/*",
    related: ["compress-image-to-50kb", "compress-image-to-100kb"],
  },
  {
    slug: "compress-image-to-50kb",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "图片精确压缩到 50KB",
    titleEn: "Compress Image to 50KB",
    oneLinerZh: "自动逼近 50KB，不超限，尽量保质量。",
    oneLinerEn: "Approach 50KB without exceeding the limit.",
    accept: "image/*",
    related: ["compress-image-to-20kb", "compress-image-to-100kb"],
  },
  {
    slug: "compress-image-to-200kb",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "图片精确压缩到 200KB",
    titleEn: "Compress Image to 200KB",
    oneLinerZh: "自动逼近 200KB 上限。",
    oneLinerEn: "Approach a 200KB cap automatically.",
    accept: "image/*",
    related: ["compress-image-to-100kb", "compress-image-to-500kb"],
  },
  {
    slug: "compress-image-to-500kb",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "图片精确压缩到 500KB",
    titleEn: "Compress Image to 500KB",
    oneLinerZh: "自动逼近 500KB 上限。",
    oneLinerEn: "Approach a 500KB cap automatically.",
    accept: "image/*",
    related: ["compress-image-to-200kb", "compress-image"],
  },
  {
    slug: "resize-image",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "图片尺寸修改",
    titleEn: "Resize Image",
    oneLinerZh: "按像素改宽高，可保持比例。本地处理。",
    oneLinerEn: "Change width/height in pixels, optionally keep aspect ratio.",
    accept: "image/*",
    related: ["compress-image", "png-to-jpg"],
  },
  {
    slug: "remove-exif",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "清除图片 EXIF / 元数据",
    titleEn: "Remove Image EXIF / Metadata",
    oneLinerZh: "通过本地重编码去掉 GPS、设备、拍摄信息，保护隐私。",
    oneLinerEn: "Strip GPS, device and capture metadata by re-encoding locally.",
    accept: "image/*",
    related: ["compress-image", "file-type-detector"],
  },

  // —— 文件 / 工具 ——
  {
    slug: "file-type-detector",
    category: "file",
    status: "live",
    localOnly: true,
    titleZh: "文件真实格式检测",
    titleEn: "Real File Type Detector",
    oneLinerZh: "用 Magic Bytes 判断真实类型，不轻信扩展名。",
    oneLinerEn: "Detect real type via magic bytes — never trust the extension alone.",
    accept: "*/*",
    related: ["file-compare", "md5-sha256"],
  },
  {
    slug: "md5-sha256",
    category: "file",
    status: "live",
    localOnly: true,
    titleZh: "MD5 / SHA256 校验",
    titleEn: "MD5 / SHA256 Hash",
    oneLinerZh: "在浏览器计算文件哈希，用于校验完整性。",
    oneLinerEn: "Compute file hashes in the browser to verify integrity.",
    accept: "*/*",
    related: ["file-compare", "file-type-detector"],
  },
  {
    slug: "file-compare",
    category: "file",
    status: "live",
    localOnly: true,
    titleZh: "两个文件是否完全一致",
    titleEn: "Compare Two Files",
    oneLinerZh: "逐字节 / 哈希对比，判断两个文件是否一模一样。",
    oneLinerEn: "Byte-level / hash compare to see if two files are identical.",
    accept: "*/*",
    multiple: true,
    maxFiles: 2,
    related: ["md5-sha256", "file-type-detector"],
  },
  {
    slug: "xlsx-to-csv",
    category: "spreadsheet",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 Excel 转 CSV",
    titleEn: "LINGXIFIELD Excel to CSV",
    oneLinerZh: "批量把 XLSX 工作簿转成 CSV；多工作表会分别导出，全部在浏览器本地处理。",
    oneLinerEn: "Batch-convert XLSX workbooks to CSV. Multiple sheets are exported separately, entirely in your browser.",
    accept: ".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    multiple: true,
    maxFiles: 20,
    maxSizeMB: 80,
    related: ["csv-to-xlsx", "docx-to-txt", "file-type-detector"],
  },
  {
    slug: "csv-to-xlsx",
    category: "spreadsheet",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 CSV / TSV 转 Excel",
    titleEn: "LINGXIFIELD CSV / TSV to Excel",
    oneLinerZh: "批量把 CSV 或 TSV 转成标准 XLSX 文件，支持引号、逗号与换行字段，本地完成。",
    oneLinerEn: "Batch-convert CSV or TSV files to standard XLSX, including quoted fields, locally in your browser.",
    accept: ".csv,.tsv,text/csv,text/tab-separated-values",
    multiple: true,
    maxFiles: 30,
    maxSizeMB: 80,
    related: ["xlsx-to-csv", "docx-to-txt"],
  },
  {
    slug: "docx-to-txt",
    category: "file",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 DOCX 转 TXT",
    titleEn: "LINGXIFIELD DOCX to TXT",
    oneLinerZh: "批量提取 DOCX 正文为 TXT，不上传服务器，适合再进入书本、学习与科研工作区。",
    oneLinerEn: "Batch-extract DOCX text to TXT locally, ready for Book, Learning or Research workspaces.",
    accept: ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    multiple: true,
    maxFiles: 30,
    maxSizeMB: 80,
    related: ["xlsx-to-csv", "csv-to-xlsx", "file-type-detector"],
  },
  {
    slug: "pptx-to-txt",
    category: "file",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 PPTX 转 TXT",
    titleEn: "LINGXIFIELD PPTX to TXT",
    oneLinerZh: "批量提取 PowerPoint 幻灯片文字为 TXT，按页保留 Slide 标记，本地处理。",
    oneLinerEn: "Batch-extract PowerPoint slide text to TXT with slide markers, locally.",
    accept: ".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation",
    multiple: true,
    maxFiles: 30,
    maxSizeMB: 100,
    related: ["docx-to-txt", "xlsx-to-csv"],
  },
  {
    slug: "json-formatter",
    category: "utility",
    status: "live",
    localOnly: true,
    titleZh: "JSON 格式化 / 修复",
    titleEn: "JSON Format / Repair",
    oneLinerZh: "美化、压缩 JSON；常见语法错误给出可读说明。",
    oneLinerEn: "Pretty-print or minify JSON; explain common syntax errors.",
    related: ["timestamp-converter", "md5-sha256"],
  },
  {
    slug: "timestamp-converter",
    category: "utility",
    status: "live",
    localOnly: true,
    titleZh: "时间戳转换",
    titleEn: "Timestamp Converter",
    oneLinerZh: "Unix 秒/毫秒与可读时间互转，支持本地时区。",
    oneLinerEn: "Convert Unix seconds/ms ↔ human time in your local timezone.",
    related: ["json-formatter"],
  },
  {
    slug: "qr-code-generator",
    category: "qr",
    status: "live",
    localOnly: true,
    titleZh: "二维码生成",
    titleEn: "QR Code Generator",
    oneLinerZh: "输入链接或文本，本地生成二维码图片。",
    oneLinerEn: "Generate a QR image from text or a URL — locally.",
    related: ["qr-code-reader"],
  },

  // —— 规划中（诚实标注，不伪实现） ——
  {
    slug: "heic-to-jpg",
    category: "image",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 HEIC 转 JPG",
    titleEn: "LINGXIFIELD HEIC to JPG",
    oneLinerZh: "批量把 iPhone 常见 HEIC / HEIF 转成 JPG，浏览器本地完成。",
    oneLinerEn: "Batch-convert HEIC / HEIF photos to JPG entirely in your browser.",
    accept: ".heic,.heif,image/heic,image/heif",
    multiple: true,
    maxFiles: 30,
    maxSizeMB: 100,
    related: ["jpg-to-png", "compress-image", "remove-exif"],
  },
  {
    slug: "qr-code-reader",
    category: "qr",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场二维码读取",
    titleEn: "LINGXIFIELD QR Code Reader",
    oneLinerZh: "上传二维码图片，本地识别其中的文本或链接，不上传服务器。",
    oneLinerEn: "Decode text or URLs from a QR image locally without uploading it.",
    accept: "image/*,.jpg,.jpeg,.png,.webp",
    maxSizeMB: 40,
    related: ["qr-code-generator", "file-type-detector"],
  },
  {
    slug: "merge-pdf",
    category: "pdf",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 PDF 合并",
    titleEn: "LINGXIFIELD Merge PDF",
    oneLinerZh: "一次拖入多个 PDF，按选择顺序合并为一个文件，浏览器本地完成。",
    oneLinerEn: "Merge multiple PDFs in selection order entirely in your browser.",
    accept: ".pdf,application/pdf",
    multiple: true,
    maxFiles: 50,
    maxSizeMB: 150,
    related: ["split-pdf", "image-to-pdf", "pdf-to-jpg"],
  },
  {
    slug: "split-pdf",
    category: "pdf",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 PDF 拆分",
    titleEn: "LINGXIFIELD Split PDF",
    oneLinerZh: "把一个 PDF 按页拆成独立 PDF 文件，本地处理。",
    oneLinerEn: "Split one PDF into individual page PDFs locally in your browser.",
    accept: ".pdf,application/pdf",
    maxSizeMB: 150,
    related: ["merge-pdf", "pdf-to-jpg"],
  },
  {
    slug: "compress-pdf",
    category: "pdf",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 PDF 重建压缩",
    titleEn: "LINGXIFIELD Rebuild & Compress PDF",
    oneLinerZh: "适合扫描件与图片型 PDF：逐页重建并压缩图像。文字/矢量页会被栅格化，不属于无损压缩。",
    oneLinerEn: "Best for scanned/image PDFs: rebuild pages with compressed images. Text/vector pages are rasterized, so this is not lossless compression.",
    accept: ".pdf,application/pdf",
    maxSizeMB: 200,
    related: ["split-pdf", "merge-pdf", "pdf-to-jpg"],
  },
  {
    slug: "image-to-pdf",
    category: "pdf",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场图片转 PDF",
    titleEn: "LINGXIFIELD Images to PDF",
    oneLinerZh: "批量拖入图片，按顺序生成一个多页 PDF，本地完成。",
    oneLinerEn: "Turn multiple images into one ordered multi-page PDF locally.",
    accept: "image/*,.jpg,.jpeg,.png,.webp",
    multiple: true,
    maxFiles: 100,
    maxSizeMB: 80,
    related: ["merge-pdf", "pdf-to-jpg", "compress-image"],
  },
  {
    slug: "pdf-to-jpg",
    category: "pdf",
    status: "live",
    localOnly: true,
    titleZh: "灵犀场 PDF 转 JPG",
    titleEn: "LINGXIFIELD PDF to JPG",
    oneLinerZh: "把 PDF 每一页渲染成独立 JPG，浏览器本地完成。",
    oneLinerEn: "Render every PDF page to a separate JPG entirely in your browser.",
    accept: ".pdf,application/pdf",
    maxSizeMB: 150,
    related: ["split-pdf", "image-to-pdf", "merge-pdf"],
  },
];

export function getTool(slug: string): ToolMeta | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function liveTools() {
  return TOOLS.filter((t) => t.status === "live");
}

export function toolsByCategory() {
  const map = new Map<ToolMeta["category"], ToolMeta[]>();
  for (const t of TOOLS) {
    const list = map.get(t.category) || [];
    list.push(t);
    map.set(t.category, list);
  }
  return map;
}

export const CATEGORY_LABEL: Record<ToolMeta["category"], { zh: string; en: string }> = {
  image: { zh: "图片处理", en: "Images" },
  pdf: { zh: "PDF / 文档", en: "PDF" },
  file: { zh: "文件诊断", en: "Files" },
  spreadsheet: { zh: "表格 / Excel", en: "Spreadsheet / Excel" },
  utility: { zh: "开发者 / 通用", en: "Utilities" },
  qr: { zh: "二维码", en: "QR" },
  field: { zh: "场域小工具", en: "Field tools" },
};

/** Target size for precise compress routes */
export function targetBytesForSlug(slug: string): number | null {
  const m = slug.match(/compress-image-to-(\d+)kb/);
  if (!m) return null;
  return parseInt(m[1], 10) * 1024;
}
