import type {LingxiLang} from "@/lib/lingxi-i18n";

type K=
 |"subtitleLoad"|"subtitlePaste"|"subtitleShift"|"subtitleExportSrt"|"subtitleExportVtt"|"subtitleExportTxt"|"subtitleInvalid"
 |"remoteTitle"|"remoteLead"|"remoteRun"|"remoteRunning"|"remoteLoaded"|"remoteFailed"|"remoteRights"|"remoteFallback"
 |"batchImageLead"|"preparingMedia"|"download"|"textIntro"|"width"|"height"|"genericFileHint";

const C:Record<K,Record<LingxiLang,string>>={
 subtitleLoad:{zh:"选择 SRT 或 VTT 字幕",en:"Choose SRT or VTT subtitles",ja:"SRT または VTT 字幕を選択",ko:"SRT 또는 VTT 자막 선택",fr:"Choisir des sous-titres SRT ou VTT",de:"SRT- oder VTT-Untertitel wählen",es:"Elegir subtítulos SRT o VTT",pt:"Escolher legendas SRT ou VTT",ar:"اختر ترجمة SRT أو VTT"},
 subtitlePaste:{zh:"也可以直接粘贴字幕内容。",en:"You can also paste subtitle content directly.",ja:"字幕内容を直接貼り付けることもできます。",ko:"자막 내용을 직접 붙여넣을 수도 있습니다.",fr:"Vous pouvez aussi coller directement le contenu des sous-titres.",de:"Untertitel können auch direkt eingefügt werden.",es:"También puedes pegar directamente el contenido de los subtítulos.",pt:"Também pode colar diretamente o conteúdo das legendas.",ar:"يمكنك أيضًا لصق محتوى الترجمة مباشرة."},
 subtitleShift:{zh:"整体调整时间（毫秒）",en:"Shift all timing (milliseconds)",ja:"全体の時間を調整（ミリ秒）",ko:"전체 시간 조정(밀리초)",fr:"Décaler tous les temps (millisecondes)",de:"Gesamtes Timing verschieben (Millisekunden)",es:"Desplazar todos los tiempos (milisegundos)",pt:"Deslocar todos os tempos (milissegundos)",ar:"إزاحة جميع التوقيتات (مللي ثانية)"},
 subtitleExportSrt:{zh:"导出 SRT",en:"Export SRT",ja:"SRTを書き出す",ko:"SRT 내보내기",fr:"Exporter SRT",de:"SRT exportieren",es:"Exportar SRT",pt:"Exportar SRT",ar:"تصدير SRT"},
 subtitleExportVtt:{zh:"导出 VTT",en:"Export VTT",ja:"VTTを書き出す",ko:"VTT 내보내기",fr:"Exporter VTT",de:"VTT exportieren",es:"Exportar VTT",pt:"Exportar VTT",ar:"تصدير VTT"},
 subtitleExportTxt:{zh:"导出纯文字",en:"Export text",ja:"テキストを書き出す",ko:"텍스트 내보내기",fr:"Exporter le texte",de:"Text exportieren",es:"Exportar texto",pt:"Exportar texto",ar:"تصدير النص"},
 subtitleInvalid:{zh:"没有识别到有效字幕，请检查 SRT / VTT 格式。",en:"No valid subtitles were found. Check the SRT / VTT format.",ja:"有効な字幕を認識できませんでした。SRT / VTT 形式を確認してください。",ko:"유효한 자막을 찾지 못했습니다. SRT / VTT 형식을 확인하세요.",fr:"Aucun sous-titre valide détecté. Vérifiez le format SRT / VTT.",de:"Keine gültigen Untertitel erkannt. SRT-/VTT-Format prüfen.",es:"No se detectaron subtítulos válidos. Revisa el formato SRT / VTT.",pt:"Não foram encontradas legendas válidas. Verifique o formato SRT / VTT.",ar:"لم يتم العثور على ترجمة صالحة. تحقق من صيغة SRT / VTT."},
 remoteTitle:{zh:"从公开视频链接载入",en:"Load from a public media link",ja:"公開メディアリンクから読み込む",ko:"공개 미디어 링크에서 불러오기",fr:"Charger depuis un lien média public",de:"Von einem öffentlichen Medienlink laden",es:"Cargar desde un enlace multimedia público",pt:"Carregar a partir de um link multimédia público",ar:"التحميل من رابط وسائط عام"},
 remoteLead:{zh:"支持公开分享链接和媒体直链；一行一个，最多 20 条。",en:"Supports public share links and direct media links; one per line, up to 20.",ja:"公開共有リンクとメディア直リンクに対応。1行1件、最大20件。",ko:"공개 공유 링크와 미디어 직접 링크를 지원하며 한 줄에 하나씩 최대 20개까지 가능합니다.",fr:"Liens de partage publics et liens média directs pris en charge ; un par ligne, jusqu’à 20.",de:"Öffentliche Freigabelinks und direkte Medienlinks; ein Link pro Zeile, bis zu 20.",es:"Admite enlaces públicos compartidos y enlaces directos; uno por línea, hasta 20.",pt:"Suporta links públicos e links diretos de multimédia; um por linha, até 20.",ar:"يدعم روابط المشاركة العامة وروابط الوسائط المباشرة؛ رابط واحد في كل سطر، حتى 20."},
 remoteRun:{zh:"载入链接",en:"Load links",ja:"リンクを読み込む",ko:"링크 불러오기",fr:"Charger les liens",de:"Links laden",es:"Cargar enlaces",pt:"Carregar links",ar:"تحميل الروابط"},
 remoteRunning:{zh:"正在载入",en:"Loading",ja:"読み込み中",ko:"불러오는 중",fr:"Chargement",de:"Wird geladen",es:"Cargando",pt:"A carregar",ar:"جارٍ التحميل"},
 remoteLoaded:{zh:"已载入",en:"Loaded",ja:"読み込み済み",ko:"불러옴",fr:"Chargé",de:"Geladen",es:"Cargado",pt:"Carregado",ar:"تم التحميل"},
 remoteFailed:{zh:"未载入",en:"Not loaded",ja:"読み込めませんでした",ko:"불러오지 못함",fr:"Non chargé",de:"Nicht geladen",es:"No cargado",pt:"Não carregado",ar:"لم يتم التحميل"},
 remoteRights:{zh:"仅处理公开可访问且有权编辑的素材。需要登录或授权的内容，请使用原始文件。",en:"Use only publicly accessible media you are allowed to edit. For content requiring sign-in or authorization, use the original file.",ja:"公開アクセスでき、編集権限のある素材のみ使用してください。ログインや許可が必要な内容は元ファイルを使用してください。",ko:"공개 접근 가능하고 편집 권한이 있는 자료만 사용하세요. 로그인이나 권한이 필요한 콘텐츠는 원본 파일을 사용하세요.",fr:"Utilisez uniquement des médias publics que vous êtes autorisé à modifier. Pour les contenus nécessitant une connexion ou une autorisation, utilisez le fichier d’origine.",de:"Nur öffentlich zugängliche Medien verwenden, die Sie bearbeiten dürfen. Bei Anmelde- oder Zugriffsanforderungen die Originaldatei verwenden.",es:"Usa solo medios públicos que tengas derecho a editar. Si el contenido requiere inicio de sesión o autorización, usa el archivo original.",pt:"Use apenas conteúdos públicos que tenha direito de editar. Se exigir login ou autorização, use o ficheiro original.",ar:"استخدم فقط الوسائط العامة التي يحق لك تعديلها. إذا كان المحتوى يتطلب تسجيل دخول أو تفويضًا، فاستخدم الملف الأصلي."},
 remoteFallback:{zh:"这个链接暂时无法读取，请换用原始文件或可直接访问的媒体链接。",en:"This link cannot be read right now. Use the original file or a directly accessible media link.",ja:"このリンクは現在読み込めません。元ファイルまたは直接アクセスできるメディアリンクを使用してください。",ko:"이 링크는 현재 읽을 수 없습니다. 원본 파일이나 직접 접근 가능한 미디어 링크를 사용하세요.",fr:"Ce lien ne peut pas être lu pour le moment. Utilisez le fichier d’origine ou un lien média directement accessible.",de:"Dieser Link kann derzeit nicht gelesen werden. Verwenden Sie die Originaldatei oder einen direkt erreichbaren Medienlink.",es:"Este enlace no puede leerse ahora. Usa el archivo original o un enlace multimedia accesible directamente.",pt:"Este link não pode ser lido agora. Use o ficheiro original ou um link multimédia diretamente acessível.",ar:"لا يمكن قراءة هذا الرابط الآن. استخدم الملف الأصلي أو رابط وسائط يمكن الوصول إليه مباشرة."},
 batchImageLead:{zh:"批量调整尺寸、质量与格式，完成后下载 ZIP。",en:"Resize, adjust quality and convert formats in batch, then download a ZIP.",ja:"サイズ・品質・形式をまとめて調整し、ZIPでダウンロード。",ko:"크기·품질·형식을 일괄 조정한 뒤 ZIP으로 다운로드합니다.",fr:"Redimensionnez, ajustez la qualité et convertissez les formats en lot, puis téléchargez un ZIP.",de:"Größe, Qualität und Format stapelweise anpassen und anschließend als ZIP herunterladen.",es:"Ajusta tamaño, calidad y formato por lotes y descarga un ZIP.",pt:"Ajuste tamanho, qualidade e formato em lote e descarregue um ZIP.",ar:"اضبط الحجم والجودة والصيغة دفعة واحدة ثم نزّل ملف ZIP."},
 preparingMedia:{zh:"正在准备视频处理…",en:"Preparing video processing…",ja:"動画処理を準備中…",ko:"영상 처리를 준비 중…",fr:"Préparation du traitement vidéo…",de:"Videoverarbeitung wird vorbereitet…",es:"Preparando el procesamiento de vídeo…",pt:"A preparar o processamento de vídeo…",ar:"جارٍ تجهيز معالجة الفيديو…"},
 download:{zh:"下载",en:"Download",ja:"ダウンロード",ko:"다운로드",fr:"Télécharger",de:"Herunterladen",es:"Descargar",pt:"Baixar",ar:"تنزيل"},
 textIntro:{zh:"可直接统计、整理、编码或解码文本；处理前后的内容都会保留在页面中。",en:"Count, clean, encode or decode text directly; both input and result remain available on the page.",ja:"テキストの集計・整理・エンコード・デコードを直接行え、入力と結果はページ上に残ります。",ko:"텍스트 통계·정리·인코딩·디코딩을 바로 처리하며 입력과 결과를 페이지에서 함께 확인할 수 있습니다.",fr:"Comptez, nettoyez, encodez ou décodez le texte directement ; l’entrée et le résultat restent visibles sur la page.",de:"Text direkt zählen, bereinigen, kodieren oder dekodieren; Eingabe und Ergebnis bleiben auf der Seite sichtbar.",es:"Cuenta, limpia, codifica o decodifica texto directamente; la entrada y el resultado permanecen visibles.",pt:"Conte, limpe, codifique ou descodifique texto diretamente; a entrada e o resultado ficam visíveis.",ar:"احسب النص ونظّمه ورمّزه أو فك ترميزه مباشرة؛ يبقى الإدخال والنتيجة ظاهرين في الصفحة."},
 width:{zh:"宽度",en:"Width",ja:"幅",ko:"너비",fr:"Largeur",de:"Breite",es:"Ancho",pt:"Largura",ar:"العرض"},
 height:{zh:"高度",en:"Height",ja:"高さ",ko:"높이",fr:"Hauteur",de:"Höhe",es:"Alto",pt:"Altura",ar:"الارتفاع"},
 genericFileHint:{zh:"请检查文件格式、文件大小和内容是否完整，再重新处理。",en:"Check the file format, size and integrity, then try again.",ja:"ファイル形式・サイズ・内容が正常か確認して再試行してください。",ko:"파일 형식·크기·내용이 정상인지 확인한 뒤 다시 시도하세요.",fr:"Vérifiez le format, la taille et l’intégrité du fichier, puis réessayez.",de:"Dateiformat, Größe und Vollständigkeit prüfen und erneut versuchen.",es:"Comprueba el formato, tamaño e integridad del archivo y vuelve a intentarlo.",pt:"Verifique o formato, tamanho e integridade do ficheiro e tente novamente.",ar:"تحقق من صيغة الملف وحجمه وسلامته ثم أعد المحاولة."}
};

export function workbenchCopy(lang:LingxiLang,key:K){return C[key][lang]}
