import fs from"node:fs";
const R=(p)=>fs.readFileSync(p,"utf8"),ok=(n,v)=>{if(!v)throw new Error(n+"_FAILED");console.log(n+"=PASS")};
const mig=R("supabase/migrations/20260930003000_food_production_final_v17.sql");
const ui=R("components/tools/FoodCalorieWorkbench.tsx");
const sess=R("app/api/tools/food/session/route.ts");
const paid=R("app/api/tools/food/calculate/route.ts"),free=R("app/api/tools/food/free-calculate/route.ts"),manual=R("app/api/tools/food/manual-calculate/route.ts");
ok("SERVER_IMAGE_SHA256",sess.includes('createHash("sha256")')&&sess.includes("validImage"));
ok("IMAGE_BYTES_NOT_STORED",!sess.includes(".upload(")&&mig.includes("image_hashes"));
ok("SESSION_COUNT_BINDING",mig.includes("IMAGE_COUNT_MISMATCH"));
ok("SESSION_OWNER_BINDING",mig.includes("IMAGE_SESSION_OWNER_MISMATCH"));
ok("SESSION_INPUT_BINDING",mig.includes("IMAGE_SESSION_BINDING_MISMATCH"));
ok("SESSION_SINGLE_CONSUME",mig.includes("consumed_at is not null")&&mig.includes("claimed_at is not null"));
ok("ABUSE_GUARD_IPHASH_ASSUMPTION_REMOVED",!sess.includes("abuse.ipHash"));
ok("SESSION_CLIENT_CREATION",ui.includes("createFoodImageSession([file])")&&ui.includes("createFoodImageSession(files)"));
ok("PAID_SESSION_REQUIRED",paid.includes("sessionId")&&paid.includes("claim_food_image_session_v17")&&paid.includes("consume_food_image_session_v17"));
ok("FREE_SESSION_REQUIRED",free.includes("sessionId")&&free.includes("claim_food_image_session_v17")&&free.includes("consume_food_image_session_v17"));
ok("SESSION_RELEASE_ON_CALC_FAILURE",paid.includes("release_food_image_session_v17")&&free.includes("release_food_image_session_v17"));
ok("MANUAL_LOCAL_FREE_PATH",ui.includes('manual?"/api/tools/food/manual-calculate"')&&manual.includes("calculate_food_compact_v1")&&!manual.includes("recoverToolQuotePayment"));
ok("BATCH_QUANTITY_SESSION_BINDING",ui.includes("sessionId,photoCount:files.length,items"));
ok("I18N_TABLE_9_LANG",["name_en","name_zh","name_ja","name_ko","name_fr","name_de","name_es","name_pt","name_ar"].every(x=>mig.includes(x)));
ok("ARABIC_RTL",ui.includes('dir={lang==="ar"?"rtl":"ltr"}'));
for(const l of ["fr","de","es","pt","ar"])for(const k of ["balanced","proteinLight","fiberLight","carbHeavy","nextProtein","nextFiber","nextBalanced","nextVariety"])ok("UI_"+l.toUpperCase()+"_"+k,ui.includes(l+":{")&&ui.includes(k+":"));
const src=JSON.parse(R("fixtures/food-final/usda-5901-localization-source.json"));
ok("USDA_5901_SOURCE",src.length===5901);
console.log("FOOD_FINAL_R2_STATIC_GATE=PASS");
