import fs from"node:fs";
const R=(p)=>fs.readFileSync(p,"utf8"),ok=(n,v)=>{if(!v)throw new Error(n+"_FAILED");console.log(n+"=PASS")};
const mig=R("supabase/migrations/20260930003000_food_production_final_v17.sql");
const bound=R('supabase/migrations/20260930010000_food_production_closeout_v18.sql');
const ui=R("components/tools/FoodCalorieWorkbench.tsx");
const sess=R("app/api/tools/food/session/route.ts");
const paid=R("app/api/tools/food/calculate/route.ts"),free=R("app/api/tools/food/free-calculate/route.ts"),manual=R("app/api/tools/food/manual-calculate/route.ts");
ok("SERVER_IMAGE_SHA256",sess.includes('createHash("sha256")')&&sess.includes("validImage"));
ok("IMAGE_BYTES_NOT_STORED",!sess.includes(".upload(")&&mig.includes("image_hashes"));
ok("SESSION_COUNT_BINDING",mig.includes("IMAGE_COUNT_MISMATCH"));
ok("SESSION_OWNER_BINDING",mig.includes("IMAGE_SESSION_OWNER_MISMATCH"));
ok("SESSION_INPUT_BINDING",mig.includes("IMAGE_SESSION_BINDING_MISMATCH"));
ok("SESSION_SINGLE_CONSUME",mig.includes("consumed_at is not null")&&mig.includes("claimed_at is not null"));
ok("ABUSE_GUARD_IPHASH_ASSUMPTION_REMOVED",!sess.includes("abuse.ipHash"));
ok("SESSION_CLIENT_CREATION",ui.includes("createFoodImageSession(files)"));
ok("PAID_SESSION_REQUIRED",paid.includes('calculate_food_paid_bound_v18')&&bound.includes('food_calorie_image_sessions_v18')&&bound.includes('s.consumed_at is not null')&&bound.includes('s.account_id is distinct from p_user_id'));
ok("FREE_SESSION_REQUIRED",free.includes('calculate_food_daily_free_bound_v18')&&bound.includes('IMAGE_SESSION_INVALID'));
ok("SESSION_ATOMIC_CALCULATION",bound.includes('calculate_food_compact_v1')&&bound.includes('consumed_at=now()')&&bound.includes('raise exception'));
ok("MANUAL_LOCAL_FREE_PATH",ui.includes("calculateReferences(local)")&&ui.includes("/api/tools/food/manual-calculate")&&manual.includes("calculate_food_compact_v1")&&!manual.includes("recoverToolQuotePayment"));
ok("BATCH_QUANTITY_SESSION_BINDING",ui.includes("sessionId:session,photoCount:files.length,items"));
ok("I18N_TABLE_9_LANG",["name_en","name_zh","name_ja","name_ko","name_fr","name_de","name_es","name_pt","name_ar"].every(x=>mig.includes(x)));
ok("ARABIC_RTL",/dir=\{lang===['"]ar['"]\?['"]rtl['"]:['"]ltr['"]\}/.test(ui));
const copy=R('lib/tools/food/workbench-copy.ts');
for(const lang of ['zh','en','ja','ko','fr','de','es','pt','ar'])ok('UI_'+lang,copy.includes(lang+':{'));
const usda=JSON.parse(R('data/nutrition/reference-foods.json'));
const tfda=JSON.parse(R('data/nutrition/tfda-foods.json'));
ok('LICENSED_REFERENCE_DATA',usda.length>=13359&&tfda.length>=2127);
console.log('FOOD_SESSION_STATIC_GATE=PASS');
