import type {LingxiLang} from "@/lib/lingxi-i18n";
type K="kicker"|"title"|"lead"|"add"|"limit"|"ratio"|"start"|"working"|"stop"|"loading"|"processing"|"assembling"|"done"|"cancelled"|"invalidFiles"|"invalidVideo"|"clipFailed"|"mergeFailed"|"readFailed"|"download"|"disclose"|"up"|"down";
const en:Record<K,string>={kicker:"SASI · Video assembly",title:"Turn finished shots into one film.",lead:"Choose existing clips, reorder them, and export one MP4 locally. Audio is preserved and the selected frame is normalized in your browser.",add:"Add video clips",limit:"Local limit: 24 clips, 150MB total, 10 minutes. Keep this page open; the editing engine loads on first use.",ratio:"Output aspect ratio",start:"Assemble MP4",working:"Assembling…",stop:"Stop",loading:"Loading the local editing engine…",processing:"Preparing clip {i} / {n}…",assembling:"Clips are ready. Building the MP4…",done:"Assembled {n} clips. Save the result to your device.",cancelled:"Assembly stopped. Source videos are unchanged.",invalidFiles:"Choose MP4, MOV or WebM files; up to 24 clips and 150MB total.",invalidVideo:"Use valid video clips with a combined duration under 10 minutes.",clipFailed:"A clip could not be prepared. Shorten it or try another file.",mergeFailed:"The final film could not be assembled. Please retry.",readFailed:"The final film could not be read.",download:"Download film",disclose:"When generated media is used, keep the required generated-content disclosure when publishing.",up:"Move clip up",down:"Move clip down"};
const zh:Record<K,string>={...en,kicker:"SASI · 镜头合成",title:"镜头拍好了，一起变成片。",lead:"选择已有视频，调整顺序，在浏览器本机合成一个 MP4。保留原声，并统一到你选择的画幅。",add:"添加视频",limit:"本机上限：24 段、合计 150MB、总时长 10 分钟。请保持页面打开；首次使用会加载剪辑引擎。",ratio:"成片画幅",start:"一键合成 MP4",working:"正在合成…",stop:"停止",loading:"正在加载本地剪辑引擎…",processing:"正在整理第 {i} / {n} 个镜头…",assembling:"镜头已就绪，正在合成 MP4…",done:"已合成 {n} 个镜头，保存到你的设备即可。",cancelled:"已停止合成，原视频保持不变。",invalidFiles:"请选择 MP4、MOV 或 WebM；最多 24 段，合计 150MB。",invalidVideo:"请使用有效视频，合计时长需在 10 分钟以内。",clipFailed:"这个镜头没有处理完成，请缩短视频或更换文件后重试。",mergeFailed:"成片没有合成完成，请重试。",readFailed:"未能读取成片。",download:"下载成片",disclose:"使用生成素材发布时，请保留平台要求的生成内容标识。",up:"上移镜头",down:"下移镜头"};
const ja:Record<K,string>={...en,title:"完成したショットを一本の動画に。",lead:"既存クリップを並べ替え、ブラウザ内で MP4 に結合します。音声を保持し、選択した画面比率に統一します。",add:"動画を追加",ratio:"出力比率",start:"MP4 を結合",working:"結合中…",stop:"停止",download:"動画を保存"};
const ko:Record<K,string>={...en,title:"완성된 장면을 한 편의 영상으로.",lead:"기존 클립을 순서대로 정리하고 브라우저에서 하나의 MP4로 합칩니다. 원본 오디오는 유지됩니다.",add:"영상 추가",ratio:"출력 화면 비율",start:"MP4 합치기",working:"합치는 중…",stop:"중지",download:"완성본 저장"};
const fr:Record<K,string>={...en,title:"Assembler vos plans en un seul film.",lead:"Choisissez les clips, réordonnez-les et exportez un MP4 localement dans le navigateur. Le son est conservé.",add:"Ajouter des vidéos",ratio:"Format de sortie",start:"Assembler le MP4",working:"Assemblage…",stop:"Arrêter",download:"Télécharger le film"};
const de:Record<K,string>={...en,title:"Fertige Shots zu einem Film verbinden.",lead:"Clips auswählen, sortieren und lokal im Browser als MP4 exportieren. Der Originalton bleibt erhalten.",add:"Videos hinzufügen",ratio:"Ausgabeformat",start:"MP4 zusammensetzen",working:"Wird zusammengesetzt…",stop:"Stoppen",download:"Film herunterladen"};
const es:Record<K,string>={...en,title:"Convierte los planos terminados en una sola película.",lead:"Elige los clips, ordénalos y exporta un MP4 localmente en el navegador. Se conserva el audio.",add:"Añadir vídeos",ratio:"Formato de salida",start:"Montar MP4",working:"Montando…",stop:"Detener",download:"Descargar película"};
const pt:Record<K,string>={...en,title:"Junte as cenas prontas em um único filme.",lead:"Escolha os clipes, ajuste a ordem e exporte um MP4 localmente no navegador. O áudio é preservado.",add:"Adicionar vídeos",ratio:"Proporção de saída",start:"Montar MP4",working:"Montando…",stop:"Parar",download:"Baixar vídeo"};
const ar:Record<K,string>={...en,title:"حوّل اللقطات المكتملة إلى فيلم واحد.",lead:"اختر المقاطع ورتبها وصدّر ملف MP4 محليًا داخل المتصفح مع الحفاظ على الصوت.",add:"إضافة فيديوهات",ratio:"نسبة الإخراج",start:"تجميع MP4",working:"جارٍ التجميع…",stop:"إيقاف",download:"تنزيل الفيلم"};
const D:Record<LingxiLang,Record<K,string>>={zh,en,ja,ko,fr,de,es,pt,ar};
export function assemblerText(lang:LingxiLang,key:K,vars?:Record<string,string|number>){let s=(D[lang]??en)[key];for(const[k,v]of Object.entries(vars??{}))s=s.replaceAll(`{${k}}`,String(v));return s}
