import type {LingxiLang} from "@/lib/lingxi-i18n";
import type {ComposerKey} from "./composer-i18n";
export const COMPOSER_ACTION_COPY:Partial<Record<ComposerKey,Record<LingxiLang,string>>>={
  "websiteReadyWithService": {
    "zh": "已准备好。灵犀场费用预计 {price}，你连接的服务另行计费。确认后开始。",
    "en": "Ready. Estimated LINGXIFIELD fee: {price}; your connected service charges separately. Confirm to start.",
    "ja": "準備できました。LINGXIFIELD料金は概算{price}です。接続サービスの料金は別途かかります。確認して開始してください。",
    "ko": "준비됐습니다. LINGXIFIELD 예상 요금은 {price}이며 연결한 서비스 요금은 별도입니다. 확인 후 시작하세요.",
    "fr": "Prêt. Frais LINGXIFIELD estimés : {price} ; votre service facture séparément. Confirmez pour commencer.",
    "de": "Bereit. Geschätzte LINGXIFIELD-Gebühr: {price}; der verbundene Dienst berechnet separat. Zum Start bestätigen.",
    "es": "Listo. Coste estimado de LINGXIFIELD: {price}; el servicio conectado cobra aparte. Confirma para empezar.",
    "pt": "Pronto. Taxa estimada do LINGXIFIELD: {price}; o serviço conectado cobra separadamente. Confirme para iniciar.",
    "ar": "جاهز. رسوم LINGXIFIELD التقديرية {price}؛ خدمة الذكاء المرتبطة تحاسب بصورة منفصلة. أكّد للبدء."
  },
  "byokReady": {
    "zh": "已准备好。灵犀场费用预计 {price}，你连接的服务另行计费。确认后开始。",
    "en": "Ready. Estimated LINGXIFIELD fee: {price}; your connected service charges separately. Confirm to start.",
    "ja": "準備できました。LINGXIFIELD料金は概算{price}です。接続サービスの料金は別途かかります。確認して開始してください。",
    "ko": "준비됐습니다. LINGXIFIELD 예상 요금은 {price}이며 연결한 서비스 요금은 별도입니다. 확인 후 시작하세요.",
    "fr": "Prêt. Frais LINGXIFIELD estimés : {price} ; votre service facture séparément. Confirmez pour commencer.",
    "de": "Bereit. Geschätzte LINGXIFIELD-Gebühr: {price}; der verbundene Dienst berechnet separat. Zum Start bestätigen.",
    "es": "Listo. Coste estimado de LINGXIFIELD: {price}; el servicio conectado cobra aparte. Confirma para empezar.",
    "pt": "Pronto. Taxa estimada do LINGXIFIELD: {price}; o serviço conectado cobra separadamente. Confirme para iniciar.",
    "ar": "جاهز. رسوم LINGXIFIELD التقديرية {price}؛ خدمة الذكاء المرتبطة تحاسب بصورة منفصلة. أكّد للبدء."
  },
  "websiteDraftReady": {
    "zh": "已准备好，确认后开始生成。",
    "en": "Ready to generate after your confirmation.",
    "ja": "確認後に生成を開始できます。",
    "ko": "확인 후 생성을 시작할 수 있습니다.",
    "fr": "Prêt à générer après votre confirmation.",
    "de": "Nach deiner Bestätigung kann die Erstellung beginnen.",
    "es": "Listo para generar después de confirmar.",
    "pt": "Pronto para gerar após sua confirmação.",
    "ar": "جاهز للإنشاء بعد تأكيدك."
  },
  "managedReady": {
    "zh": "已准备好，确认后开始生成。",
    "en": "Ready to generate after your confirmation.",
    "ja": "確認後に生成を開始できます。",
    "ko": "확인 후 생성을 시작할 수 있습니다.",
    "fr": "Prêt à générer après votre confirmation.",
    "de": "Nach deiner Bestätigung kann die Erstellung beginnen.",
    "es": "Listo para generar después de confirmar.",
    "pt": "Pronto para gerar após sua confirmação.",
    "ar": "جاهز للإنشاء بعد تأكيدك."
  },
  "projectIdMissing": {
    "zh": "暂时无法完成，请稍后重试。",
    "en": "Unable to complete this right now. Please try again later.",
    "ja": "現在完了できません。後でもう一度お試しください。",
    "ko": "지금 완료할 수 없습니다. 잠시 후 다시 시도하세요.",
    "fr": "Impossible de terminer maintenant. Réessayez plus tard.",
    "de": "Derzeit nicht möglich. Bitte später erneut versuchen.",
    "es": "No se puede completar ahora. Inténtalo más tarde.",
    "pt": "Não é possível concluir agora. Tente mais tarde.",
    "ar": "تعذر الإكمال الآن. حاول لاحقًا."
  },
  "contextReadFailed": {
    "zh": "暂时无法完成，请稍后重试。",
    "en": "Unable to complete this right now. Please try again later.",
    "ja": "現在完了できません。後でもう一度お試しください。",
    "ko": "지금 완료할 수 없습니다. 잠시 후 다시 시도하세요.",
    "fr": "Impossible de terminer maintenant. Réessayez plus tard.",
    "de": "Derzeit nicht möglich. Bitte später erneut versuchen.",
    "es": "No se puede completar ahora. Inténtalo más tarde.",
    "pt": "Não é possível concluir agora. Tente mais tarde.",
    "ar": "تعذر الإكمال الآن. حاول لاحقًا."
  },
  "genericUnavailable": {
    "zh": "暂时无法完成，请稍后重试。",
    "en": "Unable to complete this right now. Please try again later.",
    "ja": "現在完了できません。後でもう一度お試しください。",
    "ko": "지금 완료할 수 없습니다. 잠시 후 다시 시도하세요.",
    "fr": "Impossible de terminer maintenant. Réessayez plus tard.",
    "de": "Derzeit nicht möglich. Bitte später erneut versuchen.",
    "es": "No se puede completar ahora. Inténtalo más tarde.",
    "pt": "Não é possível concluir agora. Tente mais tarde.",
    "ar": "تعذر الإكمال الآن. حاول لاحقًا."
  },
  "websiteStartFailed": {
    "zh": "暂时无法完成，请稍后重试。",
    "en": "Unable to complete this right now. Please try again later.",
    "ja": "現在完了できません。後でもう一度お試しください。",
    "ko": "지금 완료할 수 없습니다. 잠시 후 다시 시도하세요.",
    "fr": "Impossible de terminer maintenant. Réessayez plus tard.",
    "de": "Derzeit nicht möglich. Bitte später erneut versuchen.",
    "es": "No se puede completar ahora. Inténtalo más tarde.",
    "pt": "Não é possível concluir agora. Tente mais tarde.",
    "ar": "تعذر الإكمال الآن. حاول لاحقًا."
  },
  "videoStartFailed": {
    "zh": "暂时无法完成，请稍后重试。",
    "en": "Unable to complete this right now. Please try again later.",
    "ja": "現在完了できません。後でもう一度お試しください。",
    "ko": "지금 완료할 수 없습니다. 잠시 후 다시 시도하세요.",
    "fr": "Impossible de terminer maintenant. Réessayez plus tard.",
    "de": "Derzeit nicht möglich. Bitte später erneut versuchen.",
    "es": "No se puede completar ahora. Inténtalo más tarde.",
    "pt": "Não é possível concluir agora. Tente mais tarde.",
    "ar": "تعذر الإكمال الآن. حاول لاحقًا."
  },
  "supplierStartFailed": {
    "zh": "暂时无法完成，请稍后重试。",
    "en": "Unable to complete this right now. Please try again later.",
    "ja": "現在完了できません。後でもう一度お試しください。",
    "ko": "지금 완료할 수 없습니다. 잠시 후 다시 시도하세요.",
    "fr": "Impossible de terminer maintenant. Réessayez plus tard.",
    "de": "Derzeit nicht möglich. Bitte später erneut versuchen.",
    "es": "No se puede completar ahora. Inténtalo más tarde.",
    "pt": "Não é possível concluir agora. Tente mais tarde.",
    "ar": "تعذر الإكمال الآن. حاول لاحقًا."
  },
  "websiteBriefDefault": {
    "zh": "根据所附资料制作网站。",
    "en": "Create a website from the attached materials.",
    "ja": "添付資料に基づいてサイトを作成してください。",
    "ko": "첨부 자료를 바탕으로 웹사이트를 만드세요.",
    "fr": "Créez un site à partir des documents joints.",
    "de": "Erstelle eine Website aus den beigefügten Unterlagen.",
    "es": "Crea un sitio a partir de los materiales adjuntos.",
    "pt": "Crie um site a partir dos materiais anexados.",
    "ar": "أنشئ موقعًا من المواد المرفقة."
  },
  "websiteRouteUnavailable": {
    "zh": "当前无法生成，请检查已连接的服务，或稍后再试。",
    "en": "Generation is unavailable. Check your connected service or try again later.",
    "ja": "現在生成できません。接続サービスを確認するか、後で再試行してください。",
    "ko": "지금 생성할 수 없습니다. 연결한 서비스를 확인하거나 나중에 다시 시도하세요.",
    "fr": "Génération indisponible. Vérifiez le service connecté ou réessayez plus tard.",
    "de": "Erstellung nicht verfügbar. Verbundenen Dienst prüfen oder später erneut versuchen.",
    "es": "La generación no está disponible. Comprueba el servicio conectado o inténtalo más tarde.",
    "pt": "Geração indisponível. Verifique o serviço conectado ou tente mais tarde.",
    "ar": "الإنشاء غير متاح. تحقق من الخدمة المرتبطة أو حاول لاحقًا."
  },
  "noVideoRoute": {
    "zh": "当前无法生成，请检查已连接的服务，或稍后再试。",
    "en": "Generation is unavailable. Check your connected service or try again later.",
    "ja": "現在生成できません。接続サービスを確認するか、後で再試行してください。",
    "ko": "지금 생성할 수 없습니다. 연결한 서비스를 확인하거나 나중에 다시 시도하세요.",
    "fr": "Génération indisponible. Vérifiez le service connecté ou réessayez plus tard.",
    "de": "Erstellung nicht verfügbar. Verbundenen Dienst prüfen oder später erneut versuchen.",
    "es": "La generación no está disponible. Comprueba el servicio conectado o inténtalo más tarde.",
    "pt": "Geração indisponível. Verifique o serviço conectado ou tente mais tarde.",
    "ar": "الإنشاء غير متاح. تحقق من الخدمة المرتبطة أو حاول لاحقًا."
  },
  "rightsRequired": {
    "zh": "请先确认你有权使用这些素材。",
    "en": "Confirm that you have the right to use these materials.",
    "ja": "素材の使用権をご確認ください。",
    "ko": "이 자료를 사용할 권한을 확인하세요.",
    "fr": "Confirmez votre droit d’utiliser ces éléments.",
    "de": "Bestätige dein Nutzungsrecht an diesen Materialien.",
    "es": "Confirma que tienes derecho a usar estos materiales.",
    "pt": "Confirme que tem direito a usar estes materiais.",
    "ar": "أكد حقك في استخدام هذه المواد."
  },
  "ratioUnavailable": {
    "zh": "当前不支持 {value}，请选择可用的规格。",
    "en": "{value} is unavailable. Choose a supported option.",
    "ja": "現在{value}は利用できません。対応する設定を選択してください。",
    "ko": "현재 {value}를 지원하지 않습니다. 가능한 설정을 선택하세요.",
    "fr": "{value} est indisponible. Choisissez une option compatible.",
    "de": "{value} ist nicht verfügbar. Wähle eine unterstützte Einstellung.",
    "es": "{value} no está disponible. Elige una opción compatible.",
    "pt": "{value} não está disponível. Escolha uma opção compatível.",
    "ar": "الخيار {value} غير متاح. اختر إعدادًا مدعومًا."
  },
  "resolutionUnavailable": {
    "zh": "当前不支持 {value}，请选择可用的规格。",
    "en": "{value} is unavailable. Choose a supported option.",
    "ja": "現在{value}は利用できません。対応する設定を選択してください。",
    "ko": "현재 {value}를 지원하지 않습니다. 가능한 설정을 선택하세요.",
    "fr": "{value} est indisponible. Choisissez une option compatible.",
    "de": "{value} ist nicht verfügbar. Wähle eine unterstützte Einstellung.",
    "es": "{value} no está disponible. Elige una opción compatible.",
    "pt": "{value} não está disponível. Escolha uma opção compatível.",
    "ar": "الخيار {value} غير متاح. اختر إعدادًا مدعومًا."
  },
  "providerResolutionMismatch": {
    "zh": "当前不支持 {value}，请选择可用的规格。",
    "en": "{value} is unavailable. Choose a supported option.",
    "ja": "現在{value}は利用できません。対応する設定を選択してください。",
    "ko": "현재 {value}를 지원하지 않습니다. 가능한 설정을 선택하세요.",
    "fr": "{value} est indisponible. Choisissez une option compatible.",
    "de": "{value} ist nicht verfügbar. Wähle eine unterstützte Einstellung.",
    "es": "{value} no está disponible. Elige una opción compatible.",
    "pt": "{value} não está disponível. Escolha uma opção compatível.",
    "ar": "الخيار {value} غير متاح. اختر إعدادًا مدعومًا."
  },
  "ratioSaved": {
    "zh": "请选择当前可用的规格后继续。",
    "en": "Choose a supported option to continue.",
    "ja": "対応する設定を選択して続けてください。",
    "ko": "지원되는 설정을 선택하고 계속하세요.",
    "fr": "Choisissez une option compatible pour continuer.",
    "de": "Wähle zum Fortfahren eine unterstützte Einstellung.",
    "es": "Elige una opción compatible para continuar.",
    "pt": "Escolha uma opção compatível para continuar.",
    "ar": "اختر إعدادًا مدعومًا للمتابعة."
  },
  "resolutionSaved": {
    "zh": "请选择当前可用的规格后继续。",
    "en": "Choose a supported option to continue.",
    "ja": "対応する設定を選択して続けてください。",
    "ko": "지원되는 설정을 선택하고 계속하세요.",
    "fr": "Choisissez une option compatible pour continuer.",
    "de": "Wähle zum Fortfahren eine unterstützte Einstellung.",
    "es": "Elige una opción compatible para continuar.",
    "pt": "Escolha uma opção compatível para continuar.",
    "ar": "اختر إعدادًا مدعومًا للمتابعة."
  },
  "specMismatch": {
    "zh": "请选择当前可用的规格后继续。",
    "en": "Choose a supported option to continue.",
    "ja": "対応する設定を選択して続けてください。",
    "ko": "지원되는 설정을 선택하고 계속하세요.",
    "fr": "Choisissez une option compatible pour continuer.",
    "de": "Wähle zum Fortfahren eine unterstützte Einstellung.",
    "es": "Elige una opción compatible para continuar.",
    "pt": "Escolha uma opção compatível para continuar.",
    "ar": "اختر إعدادًا مدعومًا للمتابعة."
  },
  "starting": {
    "zh": "正在处理…",
    "en": "Working…",
    "ja": "処理中…",
    "ko": "처리 중…",
    "fr": "Traitement…",
    "de": "Wird bearbeitet…",
    "es": "Procesando…",
    "pt": "Processando…",
    "ar": "جارٍ المعالجة…"
  },
  "queued": {
    "zh": "正在处理…",
    "en": "Working…",
    "ja": "処理中…",
    "ko": "처리 중…",
    "fr": "Traitement…",
    "de": "Wird bearbeitet…",
    "es": "Procesando…",
    "pt": "Processando…",
    "ar": "جارٍ المعالجة…"
  },
  "generating": {
    "zh": "正在处理…",
    "en": "Working…",
    "ja": "処理中…",
    "ko": "처리 중…",
    "fr": "Traitement…",
    "de": "Wird bearbeitet…",
    "es": "Procesando…",
    "pt": "Processando…",
    "ar": "جارٍ المعالجة…"
  },
  "websiteGenerated": {
    "zh": "网站已生成，可以预览和下载。",
    "en": "Your website is ready to preview and download.",
    "ja": "サイトを生成しました。プレビューとダウンロードができます。",
    "ko": "웹사이트가 준비됐습니다. 미리 보고 다운로드하세요.",
    "fr": "Votre site est prêt à être prévisualisé et téléchargé.",
    "de": "Deine Website ist bereit zur Vorschau und zum Download.",
    "es": "Tu sitio está listo para revisar y descargar.",
    "pt": "Seu site está pronto para visualizar e baixar.",
    "ar": "موقعك جاهز للمعاينة والتنزيل."
  },
  "websiteDraftDone": {
    "zh": "网站已生成，可以预览和下载。",
    "en": "Your website is ready to preview and download.",
    "ja": "サイトを生成しました。プレビューとダウンロードができます。",
    "ko": "웹사이트가 준비됐습니다. 미리 보고 다운로드하세요.",
    "fr": "Votre site est prêt à être prévisualisé et téléchargé.",
    "de": "Deine Website ist bereit zur Vorschau und zum Download.",
    "es": "Tu sitio está listo para revisar y descargar.",
    "pt": "Seu site está pronto para visualizar e baixar.",
    "ar": "موقعك جاهز للمعاينة والتنزيل."
  },
  "taskSubmitted": {
    "zh": "请稍后在项目中查看进度。",
    "en": "Check the project progress again shortly.",
    "ja": "後でプロジェクトの進捗をご確認ください。",
    "ko": "잠시 후 프로젝트 진행 상황을 확인하세요.",
    "fr": "Consultez bientôt l’avancement du projet.",
    "de": "Prüfe in Kürze den Projektfortschritt.",
    "es": "Consulta el progreso del proyecto en unos momentos.",
    "pt": "Confira o progresso do projeto em instantes.",
    "ar": "تحقق من تقدم المشروع بعد قليل."
  },
  "progressUnavailable": {
    "zh": "请稍后在项目中查看进度。",
    "en": "Check the project progress again shortly.",
    "ja": "後でプロジェクトの進捗をご確認ください。",
    "ko": "잠시 후 프로젝트 진행 상황을 확인하세요.",
    "fr": "Consultez bientôt l’avancement du projet.",
    "de": "Prüfe in Kürze den Projektfortschritt.",
    "es": "Consulta el progreso del proyecto en unos momentos.",
    "pt": "Confira o progresso do projeto em instantes.",
    "ar": "تحقق من تقدم المشروع بعد قليل."
  },
  "videoChecking": {
    "zh": "请稍后在项目中查看进度。",
    "en": "Check the project progress again shortly.",
    "ja": "後でプロジェクトの進捗をご確認ください。",
    "ko": "잠시 후 프로젝트 진행 상황을 확인하세요.",
    "fr": "Consultez bientôt l’avancement du projet.",
    "de": "Prüfe in Kürze den Projektfortschritt.",
    "es": "Consulta el progreso del proyecto en unos momentos.",
    "pt": "Confira o progresso do projeto em instantes.",
    "ar": "تحقق من تقدم المشروع بعد قليل."
  },
  "supplierNeedsCheck": {
    "zh": "请稍后在项目中查看进度。",
    "en": "Check the project progress again shortly.",
    "ja": "後でプロジェクトの進捗をご確認ください。",
    "ko": "잠시 후 프로젝트 진행 상황을 확인하세요.",
    "fr": "Consultez bientôt l’avancement du projet.",
    "de": "Prüfe in Kürze den Projektfortschritt.",
    "es": "Consulta el progreso del proyecto en unos momentos.",
    "pt": "Confira o progresso do projeto em instantes.",
    "ar": "تحقق من تقدم المشروع بعد قليل."
  },
  "balanceLow": {
    "zh": "余额不足，请先充值。",
    "en": "Your balance is too low. Please top up first.",
    "ja": "残高が不足しています。先にチャージしてください。",
    "ko": "잔액이 부족합니다. 먼저 충전하세요.",
    "fr": "Solde insuffisant. Rechargez d’abord.",
    "de": "Guthaben reicht nicht aus. Bitte zuerst aufladen.",
    "es": "Saldo insuficiente. Recarga primero.",
    "pt": "Saldo insuficiente. Recarregue primeiro.",
    "ar": "الرصيد غير كافٍ. اشحن أولًا."
  },
  "videoDone": {
    "zh": "视频已完成。",
    "en": "Video completed.",
    "ja": "動画が完成しました。",
    "ko": "영상이 완성됐습니다.",
    "fr": "Vidéo terminée.",
    "de": "Video fertig.",
    "es": "Vídeo completado.",
    "pt": "Vídeo concluído.",
    "ar": "اكتمل الفيديو."
  },
  "videoFailed": {
    "zh": "未能生成视频，请检查服务后重试。",
    "en": "Video generation failed. Check the service before trying again.",
    "ja": "動画を生成できませんでした。サービスを確認してから再試行してください。",
    "ko": "영상을 생성하지 못했습니다. 서비스를 확인한 후 다시 시도하세요.",
    "fr": "Échec de la vidéo. Vérifiez le service avant de réessayer.",
    "de": "Videoerstellung fehlgeschlagen. Vor erneutem Versuch den Dienst prüfen.",
    "es": "Falló la generación del vídeo. Comprueba el servicio antes de reintentar.",
    "pt": "Falha ao gerar vídeo. Verifique o serviço antes de tentar novamente.",
    "ar": "فشل إنشاء الفيديو. تحقق من الخدمة قبل إعادة المحاولة."
  },
  "deliveryUnavailable": {
    "zh": "下载暂时不可用，请稍后再试。",
    "en": "Download is unavailable. Please try again later.",
    "ja": "現在ダウンロードできません。後で再試行してください。",
    "ko": "지금 다운로드할 수 없습니다. 나중에 다시 시도하세요.",
    "fr": "Téléchargement indisponible. Réessayez plus tard.",
    "de": "Download derzeit nicht verfügbar. Später erneut versuchen.",
    "es": "Descarga no disponible. Inténtalo más tarde.",
    "pt": "Download indisponível. Tente mais tarde.",
    "ar": "التنزيل غير متاح. حاول لاحقًا."
  },
  "websitePreview": {
    "zh": "网站预览",
    "en": "Website preview",
    "ja": "サイトのプレビュー",
    "ko": "웹사이트 미리보기",
    "fr": "Aperçu du site",
    "de": "Website-Vorschau",
    "es": "Vista previa del sitio",
    "pt": "Prévia do site",
    "ar": "معاينة الموقع"
  },
  "downloadWebsite": {
    "zh": "下载网站",
    "en": "Download website",
    "ja": "サイトをダウンロード",
    "ko": "웹사이트 다운로드",
    "fr": "Télécharger le site",
    "de": "Website herunterladen",
    "es": "Descargar sitio",
    "pt": "Baixar site",
    "ar": "تنزيل الموقع"
  },
  "pendingAdd": {
    "zh": "待添加",
    "en": "Pending",
    "ja": "追加待ち",
    "ko": "추가 대기",
    "fr": "En attente",
    "de": "Ausstehend",
    "es": "Pendiente",
    "pt": "Pendente",
    "ar": "قيد الانتظار"
  },
  "readme": {
    "zh": "灵犀场 SASI 网站。打开 index.html 浏览；发布前核对内容、链接和素材使用权。",
    "en": "LINGXIFIELD SASI website. Open index.html to view; check content, links and asset rights before publishing.",
    "ja": "LINGXIFIELD SASIサイト。index.htmlを開いて閲覧し、公開前に内容・リンク・素材の権利をご確認ください。",
    "ko": "LINGXIFIELD SASI 웹사이트. index.html을 열어 확인하고 게시 전 내용, 링크, 자료 권한을 검토하세요.",
    "fr": "Site LINGXIFIELD SASI. Ouvrez index.html ; vérifiez contenu, liens et droits avant publication.",
    "de": "LINGXIFIELD SASI-Website. index.html öffnen; vor Veröffentlichung Inhalte, Links und Nutzungsrechte prüfen.",
    "es": "Sitio LINGXIFIELD SASI. Abre index.html y revisa contenido, enlaces y derechos antes de publicar.",
    "pt": "Site LINGXIFIELD SASI. Abra index.html e confira conteúdo, links e direitos antes de publicar.",
    "ar": "موقع LINGXIFIELD SASI. افتح index.html وتحقق من المحتوى والروابط وحقوق المواد قبل النشر."
  }
};
