import type {LingxiLang} from '@/lib/lingxi-i18n';
const languages:LingxiLang[]=['zh','en','ja','ko','fr','de','es','pt','ar'];
const row=(...values:string[])=>Object.fromEntries(languages.map((key,i)=>[key,values[i]])) as Record<LingxiLang,string>;
export const CONNECTION_GROUPS:{id:'platforms'|'official'|'other';services:string[]}[]=[
 {id:'platforms',services:['volcengine','openrouter','aliyun']},
 {id:'official',services:['openai','xai','anthropic','gemini','deepseek','luma']},
 {id:'other',services:['compatible']}
];
const COPY={
 intro:row('选择你已有账户的服务。每个连接只使用该账户已开通的模型。','Choose a service you have an account with. Each connection uses models enabled for that account.','アカウントを持つサービスを選択してください。接続したアカウントで有効なモデルを利用します。','계정이 있는 서비스를 선택하세요. 해당 계정에서 활성화된 모델을 사용합니다.','Choisissez un service où vous avez un compte. Chaque connexion utilise les modèles activés sur ce compte.','Wähle einen Dienst, bei dem du ein Konto hast. Jede Verbindung nutzt die dort freigeschalteten Modelle.','Elige un servicio donde tengas una cuenta. Cada conexión utiliza los modelos habilitados en esa cuenta.','Escolha um serviço onde você tenha uma conta. Cada conexão usa os modelos habilitados nessa conta.','اختر خدمة لديك حساب فيها. يستخدم كل اتصال النماذج المفعّلة في ذلك الحساب.'),
 platforms:row('多模型平台','Multi-model platforms','マルチモデルプラットフォーム','멀티모델 플랫폼','Plateformes multimodèles','Plattformen mit mehreren Modellen','Plataformas multimodelo','Plataformas multimodelo','منصات متعددة النماذج'),
 official:row('模型官方服务','Model creators','モデルの公式サービス','모델 공식 서비스','Services officiels des modèles','Offizielle Modelldienste','Servicios oficiales de modelos','Serviços oficiais dos modelos','الخدمات الرسمية للنماذج'),
 other:row('其他智能服务','Other AI services','その他のAIサービス','기타 AI 서비스','Autres services IA','Weitere KI-Dienste','Otros servicios de IA','Outros serviços de IA','خدمات ذكاء اصطناعي أخرى'),
 otherName:row('添加其他服务','Add another service','別のサービスを追加','다른 서비스 추가','Ajouter un autre service','Weiteren Dienst hinzufügen','Añadir otro servicio','Adicionar outro serviço','إضافة خدمة أخرى'),
 choose:row('选择服务','Choose a service','サービスを選択','서비스 선택','Choisir un service','Dienst auswählen','Elegir servicio','Escolher serviço','اختيار خدمة'),
 settings:row('指定模型与服务地址（选填）','Model and service address (optional)','モデルとサービスURL（任意）','모델 및 서비스 주소 (선택)','Modèle et adresse du service (facultatif)','Modell und Dienstadresse (optional)','Modelo y dirección del servicio (opcional)','Modelo e endereço do serviço (opcional)','النموذج وعنوان الخدمة (اختياري)'),
 defaults:row('通常只需填写密钥。需要指定模型或使用其他地区的服务时，再填写这里。','Usually, only your key is needed. Fill these in to choose a model or a different service region.','通常はキーだけで接続できます。モデルや地域を指定する場合に入力してください。','보통 키만 입력하면 됩니다. 모델이나 서비스 지역을 지정할 때 입력하세요.','La clé suffit généralement. Remplissez ces champs pour choisir un modèle ou une autre région.','Meist genügt dein Schlüssel. Gib hier ein Modell oder eine andere Dienstregion an.','Normalmente basta con tu clave. Completa estos campos para elegir un modelo u otra región.','Normalmente, basta sua chave. Preencha para escolher um modelo ou outra região.','عادةً يكفي مفتاحك. املأ هذه الحقول لتحديد نموذج أو منطقة خدمة أخرى.'),
 automatic:row('自动选择','Automatic','自動選択','자동 선택','Automatique','Automatisch','Automático','Automático','تلقائي'),
 available:row('在灵犀场使用','Use in LINGXIFIELD','LINGXIFIELDで利用','LINGXIFIELD에서 사용','Utiliser dans LINGXIFIELD','In LINGXIFIELD nutzen','Usar en LINGXIFIELD','Usar no LINGXIFIELD','الاستخدام في LINGXIFIELD'),
 open:row('前往官网获取密钥','Get a key on the official site','公式サイトでキーを取得','공식 사이트에서 키 받기','Obtenir une clé sur le site officiel','Schlüssel auf der offiziellen Website erhalten','Obtener una clave en el sitio oficial','Obter uma chave no site oficial','الحصول على مفتاح من الموقع الرسمي'),
 billing:row('模型费用由所连接的服务收取，灵犀场的使用费在开始前显示。连接与支付币种分别选择。','Model costs are billed by the connected service. LINGXIFIELD fees appear before you start. Your service and payment currency are separate choices.','モデル料金は接続先サービスが請求します。LINGXIFIELDの料金は開始前に表示されます。サービスと支払通貨は別々に選べます。','모델 비용은 연결된 서비스가 청구합니다. LINGXIFIELD 이용료는 시작 전에 표시됩니다. 서비스와 결제 통화는 별도로 선택합니다.','Le service connecté facture les modèles. Les frais LINGXIFIELD sont affichés avant de commencer. Le service et la devise se choisissent séparément.','Modellkosten berechnet der verbundene Dienst. LINGXIFIELD-Gebühren siehst du vor dem Start. Dienst und Zahlungswährung wählst du getrennt.','El servicio conectado cobra los modelos. Las tarifas de LINGXIFIELD se muestran antes de empezar. Servicio y moneda se eligen por separado.','O serviço conectado cobra pelos modelos. As taxas do LINGXIFIELD aparecem antes de começar. Serviço e moeda são escolhas separadas.','تفرض الخدمة المتصلة رسوم النماذج. تظهر رسوم LINGXIFIELD قبل البدء. اختيار الخدمة وعملة الدفع منفصلان.'),
 platformDescription:row('一个账户可使用平台提供的多种模型。无需逐家注册，具体可用模型以你的账户为准。','Use multiple models through one platform account. Available models depend on your account.','1つのプラットフォームアカウントで複数のモデルを利用できます。利用可能なモデルはアカウントによります。','하나의 플랫폼 계정으로 여러 모델을 사용할 수 있습니다. 사용 가능한 모델은 계정에 따라 다릅니다.','Un compte de plateforme permet d’utiliser plusieurs modèles. Les modèles disponibles dépendent de votre compte.','Mit einem Plattformkonto nutzt du mehrere Modelle. Die verfügbaren Modelle hängen von deinem Konto ab.','Usa varios modelos con una cuenta de plataforma. Los modelos disponibles dependen de tu cuenta.','Use vários modelos com uma conta da plataforma. Os modelos disponíveis dependem da sua conta.','استخدم نماذج متعددة من حساب منصة واحد. تعتمد النماذج المتاحة على حسابك.'),
 officialDescription:row('直接连接这家服务的账户，使用它提供的模型。该密钥不能用于其他公司的服务。','Connect directly to this provider’s account and models. Its key cannot be used with other companies’ services.','この提供元のアカウントとモデルに直接接続します。キーは他社のサービスには使えません。','이 제공업체의 계정과 모델에 직접 연결합니다. 다른 회사의 서비스에는 이 키를 사용할 수 없습니다.','Connectez directement le compte et les modèles de ce fournisseur. La clé ne fonctionne pas chez d’autres fournisseurs.','Verbinde dein Konto direkt mit den Modellen dieses Anbieters. Der Schlüssel gilt nicht für andere Anbieter.','Conecta directamente la cuenta y los modelos de este proveedor. Su clave no funciona con otras empresas.','Conecte diretamente a conta e os modelos deste fornecedor. A chave não funciona em outras empresas.','اربط حساب هذا المزوّد ونماذجه مباشرةً. لا يعمل مفتاحه مع خدمات الشركات الأخرى.'),
 otherDescription:row('已有其他服务的密钥？填写它提供的地址和模型名称。支持与 OpenAI 调用方式兼容的文本服务。','Already have another service key? Enter its address and model name. OpenAI-compatible text services are supported.','別のサービスのキーをお持ちですか？サービスURLとモデル名を入力してください。OpenAI互換のテキストサービスに対応しています。','다른 서비스 키가 있나요? 주소와 모델 이름을 입력하세요. OpenAI 호환 텍스트 서비스를 지원합니다.','Vous avez une autre clé ? Saisissez l’adresse et le nom du modèle. Les services texte compatibles OpenAI sont pris en charge.','Du hast einen anderen Schlüssel? Gib Dienstadresse und Modellname ein. OpenAI-kompatible Textdienste werden unterstützt.','¿Tienes otra clave? Introduce la dirección y el nombre del modelo. Se admiten servicios de texto compatibles con OpenAI.','Já tem outra chave? Informe o endereço e o nome do modelo. Serviços de texto compatíveis com OpenAI são aceitos.','لديك مفتاح خدمة أخرى؟ أدخل عنوانها واسم النموذج. خدمات النص المتوافقة مع OpenAI مدعومة.'),
 text:row('对话、写作、网站构建、读书、学习与研究。','Chat, writing, websites, reading, learning and research.','対話、文章作成、サイト制作、読書、学習、調査。','대화, 글쓰기, 웹사이트 제작, 독서, 학습 및 연구.','Conversation, rédaction, sites web, lecture, apprentissage et recherche.','Chat, Schreiben, Websites, Lesen, Lernen und Recherche.','Conversación, escritura, sitios web, lectura, aprendizaje e investigación.','Conversa, escrita, sites, leitura, aprendizagem e pesquisa.','المحادثة والكتابة والمواقع والقراءة والتعلّم والبحث.'),
 video:row('视频与短剧生成。需在服务账户中开通视频模型。','Video and short drama generation. Enable a video model in your service account.','動画とショートドラマの生成。サービス側で動画モデルを有効にしてください。','영상 및 짧은 드라마 생성. 서비스 계정에서 영상 모델을 활성화하세요.','Création de vidéos et de courts épisodes. Activez un modèle vidéo sur votre compte.','Videos und Kurzdramen erstellen. Aktiviere ein Videomodell in deinem Dienstkonto.','Generación de vídeos y dramas cortos. Activa un modelo de vídeo en tu cuenta.','Geração de vídeos e dramas curtos. Ative um modelo de vídeo na sua conta.','إنشاء الفيديو والدراما القصيرة. فعّل نموذج فيديو في حساب الخدمة.'),
 image:row('图片生成。','Image generation.','画像生成。','이미지 생성.','Création d’images.','Bilder erstellen.','Generación de imágenes.','Geração de imagens.','إنشاء الصور.'),
 luma:row('暂不能在灵犀场生成作品，可前往 Luma 官网创作图片与视频。','Generation in LINGXIFIELD is not available yet. Create images and videos on Luma’s site.','LINGXIFIELD内の生成は未対応です。Lumaの公式サイトで画像と動画を作成できます。','LINGXIFIELD 내 생성은 아직 지원하지 않습니다. Luma 사이트에서 이미지와 영상을 만들 수 있습니다.','La création dans LINGXIFIELD n’est pas encore disponible. Créez vos images et vidéos sur le site Luma.','Erstellung in LINGXIFIELD ist noch nicht verfügbar. Erstelle Bilder und Videos auf Lumas Website.','La generación en LINGXIFIELD aún no está disponible. Crea imágenes y vídeos en el sitio de Luma.','A geração no LINGXIFIELD ainda não está disponível. Crie imagens e vídeos no site da Luma.','الإنشاء داخل LINGXIFIELD غير متاح بعد. أنشئ الصور والفيديو على موقع Luma.'),
};
export function connectionPageCopy(lang:LingxiLang){return Object.fromEntries(Object.entries(COPY).map(([key,value])=>[key,value[lang]])) as Record<keyof typeof COPY,string>}
const PRODUCTS:Record<string,string>={volcengine:'Doubao · Seedance · Seedream',openrouter:'OpenAI · Claude · Gemini · DeepSeek',aliyun:'Qwen · Wan',openai:'GPT · Sora',xai:'Grok · Imagine',anthropic:'Claude',gemini:'Gemini',deepseek:'DeepSeek',luma:'Dream Machine',compatible:'OpenAI-compatible'};
const SYMBOLS:Record<string,string>={volcengine:'火',openrouter:'OR',aliyun:'云',openai:'O',xai:'X',anthropic:'C',gemini:'G',deepseek:'D',luma:'L',compatible:'+'};
export function connectionServiceCopy(id:string,lang:LingxiLang){const c=connectionPageCopy(lang);return{
 symbol:SYMBOLS[id],products:PRODUCTS[id],description:id==='compatible'?c.otherDescription:CONNECTION_GROUPS[0].services.includes(id)?c.platformDescription:c.officialDescription,
 available:id==='luma'?c.luma:[c.text,...(id==='volcengine'?[c.image]:[]),...(['volcengine','aliyun','openai','xai'].includes(id)?[c.video]:[])].join(' ')
}}
