export type IntegrationKind = "language" | "coding" | "video" | "image" | "build";

export type SasiIntegration = {
  id:string; name:string; product:string; kind:IntegrationKind; region:"global"|"china";
  color:string; keyUrl:string; docsUrl:string; env:string; supports:string[];
  stepsZh:string[]; stepsEn:string[]; noteZh:string; noteEn:string;
};

export const SASI_INTEGRATIONS:SasiIntegration[] = [
  { id:"openai",name:"OpenAI",product:"GPT · Sora · Codex",kind:"language",region:"global",color:"#101010",keyUrl:"https://platform.openai.com/api-keys",docsUrl:"https://developers.openai.com/",env:"OPENAI_API_KEY",supports:["创意推理","剧本与分镜","图像与视频","产品构建"],stepsZh:["登录 OpenAI API Platform，而不是 ChatGPT 订阅页","创建 Project，并在 API Keys 中创建密钥","单独启用 API 账单与预算告警；ChatGPT 订阅不等于 API 额度","只把密钥保存到服务端加密保险箱，不粘贴到创作输入框"],stepsEn:["Sign in to the API Platform, not the ChatGPT subscription page","Create a Project and generate a key under API Keys","Enable API billing and budget alerts separately","Store the key only in a server-side encrypted vault"],noteZh:"从创意理解到剧本、分镜、视觉生成与产品代码，适合承担跨媒介创作主线。",noteEn:"A cross-media creation line for ideation, scripts, storyboards, visuals and product code." },
  { id:"xai",name:"xAI",product:"Grok · Imagine",kind:"video",region:"global",color:"#171717",keyUrl:"https://console.x.ai/",docsUrl:"https://docs.x.ai/",env:"XAI_API_KEY",supports:["实时创意","多模态推理","图像","视频"],stepsZh:["进入 xAI Console 并选择团队","在 API Keys 创建项目密钥","在 Billing 单独配置 API 付费；Grok 消费订阅通常不等于 API 余额","设置支出上限后再做一次低成本健康检查"],stepsEn:["Open xAI Console and choose the team","Create a project API key","Configure API billing separately from consumer subscriptions","Set a spend cap before a low-cost health check"],noteZh:"把实时信息、创意推演、图像与视频放进同一条探索链，适合快速扩展概念方向。",noteEn:"Unifies timely reasoning, visual ideation, images and video for rapid concept exploration." },
  { id:"anthropic",name:"Anthropic",product:"Claude",kind:"language",region:"global",color:"#d97757",keyUrl:"https://console.anthropic.com/settings/keys",docsUrl:"https://platform.claude.com/docs/en/manage-claude/authentication",env:"ANTHROPIC_API_KEY",supports:["长剧本","人物档案","结构审校","连续性"],stepsZh:["登录 Claude Console","在 Settings → API keys 创建密钥","配置 API 账单与工作区限额","按项目创建独立密钥，泄露后立即撤销轮换"],stepsEn:["Sign in to Claude Console","Create a key in Settings → API keys","Configure billing and workspace limits","Use project-scoped keys and rotate on exposure"],noteZh:"处理长剧本、人物档案与复杂资料，在结构审校、语气统一和连续性检查中保持上下文。",noteEn:"Handles long scripts and story bibles with strong structure, voice and continuity review." },
  { id:"luma",name:"Luma AI",product:"Dream Machine",kind:"video",region:"global",color:"#6d4aff",keyUrl:"https://platform.lumalabs.ai/",docsUrl:"https://docs.lumalabs.ai/docs/welcome",env:"LUMAAI_API_KEY",supports:["文生视频","图生视频","关键帧衔接","镜头运动"],stepsZh:["登录 Dream Machine API 平台","创建 API Key","阅读当前模型、队列与计价说明","先用短时长测试异步任务和回调"],stepsEn:["Sign in to the Dream Machine API platform","Create an API key","Review current models, queue behavior and pricing","Test asynchronous jobs with a short generation"],noteZh:"把静帧发展为有镜头运动和空间感的视频，适合关键帧衔接、氛围镜头与电影化预演。",noteEn:"Turns stills into spatial, cinematic motion for keyframe transitions and visual previsualization." },
  { id:"volcengine",name:"火山方舟",product:"Seedance · Seedream",kind:"video",region:"china",color:"#3855ff",keyUrl:"https://console.volcengine.com/ark/apiKey",docsUrl:"https://www.volcengine.com/docs/82379",env:"ARK_API_KEY",supports:["中文短剧","人物视觉","图像生成","视频镜头"],stepsZh:["完成火山引擎实名认证","进入方舟 API Key 管理并创建密钥","开通所需模型，确认预留金、按量或资源包规则","设置余额告警与失败停止线后再连接"],stepsEn:["Complete Volcengine identity verification","Create a key in Ark API Key Management","Enable the required model and confirm billing rules","Set balance alerts and a failure stop line"],noteZh:"面向中文创作的图像与视频生产线，适合短剧概念图、人物视觉、动态镜头与批量素材生成。",noteEn:"A Chinese-first image and video line for drama concepts, character visuals and production shots." },
  { id:"aliyun",name:"阿里云百炼",product:"Wan · Qwen",kind:"video",region:"china",color:"#ff6a00",keyUrl:"https://bailian.console.aliyun.com/?tab=model#/api-key",docsUrl:"https://help.aliyun.com/en/model-studio/get-api-key",env:"DASHSCOPE_API_KEY",supports:["中文理解","长文本规划","图像","视频"],stepsZh:["登录阿里云百炼控制台","选择地域后创建 API Key","确认代码使用同一地域的 endpoint","开通按量计费并设置费用预警"],stepsEn:["Open Alibaba Cloud Model Studio","Choose a region and create an API key","Use the endpoint matching that region","Enable usage billing and cost alerts"],noteZh:"融合中文语义理解、长文本规划与视觉生成，适合从故事设定推进到画面和视频方案。",noteEn:"Combines Chinese-language planning with image and video generation from story to visual plan." },
  { id:"tencent",name:"腾讯云",product:"MPS AIGC",kind:"video",region:"china",color:"#1677ff",keyUrl:"https://console.cloud.tencent.com/cam/capi",docsUrl:"https://cloud.tencent.com/document/product/266/126239",env:"TENCENT_SECRET_KEY",supports:["模型聚合","视频任务","媒资衔接","成片加工"],stepsZh:["完成腾讯云实名并开通 MPS","创建最小权限 CAM 子用户，不使用主账号密钥","为视频任务配置所需权限和回调地址","先验证单个模型，再开启智能路由"],stepsEn:["Complete verification and enable MPS","Create a least-privilege CAM sub-user","Configure task permissions and callbacks","Verify one model before smart routing"],noteZh:"适合把多种国内视频能力接入统一生产流程，集中处理任务提交、媒资衔接与成片加工。",noteEn:"Connects multiple video capabilities into one workflow for tasks, media handoff and finishing." },
  { id:"gemini",name:"Google",product:"Gemini",kind:"language",region:"global",color:"#4285f4",keyUrl:"https://aistudio.google.com/app/apikey",docsUrl:"https://ai.google.dev/gemini-api/docs/api-key",env:"GEMINI_API_KEY",supports:["多模态理解","长上下文","跨文件提炼","内容审校"],stepsZh:["进入 Google AI Studio","创建或选择 Google Cloud Project","生成 API Key 并限制可用 API","不要把浏览器端密钥提交到仓库"],stepsEn:["Open Google AI Studio","Create or select a Cloud project","Generate and restrict an API key","Never commit browser-exposed keys"],noteZh:"同时理解文字、图片、视频与长资料，适合跨文件提炼、素材问答、内容审校和方案对照。",noteEn:"Understands text, images, video and long context for synthesis, review and comparison." },
];

export const BUILD_CONNECTORS = [
  { id:"github",name:"GitHub",roleZh:"代码仓库",roleEn:"Source control",url:"https://github.com/settings/installations",docs:"https://docs.github.com/en/apps/using-github-apps/about-using-github-apps",stepsZh:["优先安装 GitHub App，而不是粘贴长期 PAT","只授权选定仓库，并坚持最小权限","写入、提交与部署前再次确认目标分支"],stepsEn:["Install a GitHub App instead of pasting a long-lived PAT","Authorize selected repositories with least privilege","Confirm the target branch before writes, commits or deployments"],status:"oauth-required" },
  { id:"vercel",name:"Vercel",roleZh:"预览与部署",roleEn:"Preview & deployment",url:"https://vercel.com/new",docs:"https://vercel.com/docs/git/vercel-for-github",stepsZh:["先连接 GitHub 中指定仓库","区分 Preview 与 Production 环境变量","首次生产发布必须显示域名、分支和变更摘要"],stepsEn:["Connect the intended GitHub repository","Separate Preview and Production environment variables","Show domain, branch and change summary before first production release"],status:"oauth-required" },
  { id:"supabase",name:"Supabase",roleZh:"数据库与存储",roleEn:"Database & storage",url:"https://supabase.com/dashboard",docs:"https://supabase.com/docs",stepsZh:["新建或选择项目","客户端只使用 anon key；service role 仅留服务端","先应用迁移和 RLS，再接真实用户数据"],stepsEn:["Create or select a project","Use only the anon key in clients; keep service role server-side","Apply migrations and RLS before connecting real user data"],status:"manual-setup" },
  { id:"cloudflare",name:"Cloudflare",roleZh:"域名与边缘服务",roleEn:"Domain & edge",url:"https://dash.cloudflare.com/",docs:"https://developers.cloudflare.com/",stepsZh:["选择明确的站点和账户","预览变更，不自动修改 DNS","缓存、R2 与 Workers 分开授权"],stepsEn:["Choose the exact site and account","Preview changes without automatic DNS mutation","Authorize cache, R2 and Workers separately"],status:"manual-setup" },
];

export const TRAINING_SOURCES = [
  { name:"灵犀场自有导演样本", license:"First-party / opt-in", state:"preferred", useZh:"自有剧本→分镜→审校数据；仅用户明确授权后进入训练集。",useEn:"First-party script-to-storyboard review data enters training only with explicit user consent.",url:"/legal/sasi" },
  { name:"Wikimedia Commons", license:"Per-file license", state:"verify", useZh:"图像与音视频逐素材核验署名、相同方式共享和其他条件。",useEn:"Verify attribution, share-alike and other conditions for every image, audio or video asset.",url:"https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia" },
  { name:"NASA Image and Video Library", license:"US government + exceptions", state:"verify", useZh:"适合宇宙视觉研究；需排除第三方版权、人物肖像、标识与暗示背书。",useEn:"Useful for space visual research after excluding third-party rights, likeness, marks and implied endorsement.",url:"https://www.nasa.gov/nasa-brand-center/images-and-media/" },
  { name:"Project Gutenberg", license:"Public domain in the US", state:"verify", useZh:"可提取经典叙事结构；上线地区仍需核验作品版权状态。",useEn:"Useful for classic narrative structures; verify copyright status in every launch region.",url:"https://www.gutenberg.org/policy/permission.html" },
  { name:"Blender Open Movies", license:"Project-specific Creative Commons", state:"verify", useZh:"可研究分镜、资产和镜头流程；必须遵守每个项目的许可与署名要求。",useEn:"Study storyboards, assets and shot workflows while following each project's license and attribution rules.",url:"https://studio.blender.org/films/" },
  { name:"YouTube-8M", license:"Features / research dataset", state:"research", useZh:"主要是特征与标签，不是可直接商用的原始视频训练仓。",useEn:"A research dataset of features and labels, not a commercially reusable raw-video library.",url:"https://research.google.com/youtube8m/" },
];
