export type IntegrationKind = "language" | "coding" | "video" | "image" | "build";

export type SasiIntegration = {
  id:string; name:string; product:string; kind:IntegrationKind; region:"global"|"china";
  color:string; keyUrl:string; docsUrl:string; env:string; supports:string[];
  stepsZh:string[]; stepsEn:string[]; noteZh:string; noteEn:string;
};

export const SASI_INTEGRATIONS:SasiIntegration[] = [
  { id:"openai",name:"OpenAI",product:"GPT · Sora · Codex",kind:"language",region:"global",color:"#101010",keyUrl:"https://platform.openai.com/api-keys",docsUrl:"https://developers.openai.com/",env:"OPENAI_API_KEY",supports:["导演推理","剧本","视频","编程智能体"],stepsZh:["登录 OpenAI API Platform，而不是 ChatGPT 订阅页","创建 Project，并在 API Keys 中创建密钥","单独启用 API 账单与预算告警；ChatGPT 订阅不等于 API 额度","只把密钥保存到服务端加密保险箱，不粘贴到创作输入框"],stepsEn:["Sign in to the API Platform, not the ChatGPT subscription page","Create a Project and generate a key under API Keys","Enable API billing and budget alerts separately","Store the key only in a server-side encrypted vault"],noteZh:"Codex 是 OpenAI 的编程智能体能力，不应伪装成独立视频供应商。",noteEn:"Codex is an OpenAI coding-agent capability, not a separate video provider." },
  { id:"xai",name:"xAI",product:"Grok · Imagine",kind:"video",region:"global",color:"#171717",keyUrl:"https://console.x.ai/",docsUrl:"https://docs.x.ai/",env:"XAI_API_KEY",supports:["创意推理","图片","视频"],stepsZh:["进入 xAI Console 并选择团队","在 API Keys 创建项目密钥","在 Billing 单独配置 API 付费；Grok 消费订阅通常不等于 API 余额","设置支出上限后再做一次低成本健康检查"],stepsEn:["Open xAI Console and choose the team","Create a project API key","Configure API billing separately from consumer subscriptions","Set a spend cap before a low-cost health check"],noteZh:"先完成 API 账单验证，再标记为可生产。",noteEn:"Verify API billing before production status." },
  { id:"anthropic",name:"Anthropic",product:"Claude",kind:"language",region:"global",color:"#d97757",keyUrl:"https://console.anthropic.com/settings/keys",docsUrl:"https://platform.claude.com/docs/en/manage-claude/authentication",env:"ANTHROPIC_API_KEY",supports:["编剧","长文档","审校"],stepsZh:["登录 Claude Console","在 Settings → API keys 创建密钥","配置 API 账单与工作区限额","按项目创建独立密钥，泄露后立即撤销轮换"],stepsEn:["Sign in to Claude Console","Create a key in Settings → API keys","Configure billing and workspace limits","Use project-scoped keys and rotate on exposure"],noteZh:"适合长剧本、导演审校和结构分析。",noteEn:"Useful for long scripts, directing review and structure." },
  { id:"luma",name:"Luma AI",product:"Dream Machine",kind:"video",region:"global",color:"#6d4aff",keyUrl:"https://platform.lumalabs.ai/",docsUrl:"https://docs.lumalabs.ai/docs/welcome",env:"LUMAAI_API_KEY",supports:["文生视频","图生视频","关键帧"],stepsZh:["登录 Dream Machine API 平台","创建 API Key","阅读当前模型、队列与计价说明","先用短时长测试异步任务和回调"],stepsEn:["Sign in to the Dream Machine API platform","Create an API key","Review current models, queue behavior and pricing","Test asynchronous jobs with a short generation"],noteZh:"网页会员与开发者 API 账单要分别确认。",noteEn:"Confirm developer API billing separately from web plans." },
  { id:"volcengine",name:"火山方舟",product:"Seedance · Seedream",kind:"video",region:"china",color:"#3855ff",keyUrl:"https://console.volcengine.com/ark/apiKey",docsUrl:"https://www.volcengine.com/docs/82379",env:"ARK_API_KEY",supports:["中文短剧","图片","视频"],stepsZh:["完成火山引擎实名认证","进入方舟 API Key 管理并创建密钥","开通所需模型，确认预留金、按量或资源包规则","设置余额告警与失败停止线后再连接"],stepsEn:["Complete Volcengine identity verification","Create a key in Ark API Key Management","Enable the required model and confirm billing rules","Set balance alerts and a failure stop line"],noteZh:"模型资源包可能互不通用；按具体购买页与官方规则核验。",noteEn:"Model resource packs may not be interchangeable; verify current terms." },
  { id:"aliyun",name:"阿里云百炼",product:"Wan · Qwen",kind:"video",region:"china",color:"#ff6a00",keyUrl:"https://bailian.console.aliyun.com/?tab=model#/api-key",docsUrl:"https://help.aliyun.com/en/model-studio/get-api-key",env:"DASHSCOPE_API_KEY",supports:["中文理解","图片","视频"],stepsZh:["登录阿里云百炼控制台","选择地域后创建 API Key","确认代码使用同一地域的 endpoint","开通按量计费并设置费用预警"],stepsEn:["Open Alibaba Cloud Model Studio","Choose a region and create an API key","Use the endpoint matching that region","Enable usage billing and cost alerts"],noteZh:"地域与 endpoint 必须一致。",noteEn:"The region and endpoint must match." },
  { id:"tencent",name:"腾讯云",product:"MPS AIGC",kind:"video",region:"china",color:"#1677ff",keyUrl:"https://console.cloud.tencent.com/cam/capi",docsUrl:"https://cloud.tencent.com/document/product/266/126239",env:"TENCENT_SECRET_KEY",supports:["混元","可灵","海螺","Vidu 聚合"],stepsZh:["完成腾讯云实名并开通 MPS","创建最小权限 CAM 子用户，不使用主账号密钥","为视频任务配置所需权限和回调地址","先验证单个模型，再开启智能路由"],stepsEn:["Complete verification and enable MPS","Create a least-privilege CAM sub-user","Configure task permissions and callbacks","Verify one model before smart routing"],noteZh:"聚合模型清单与价格会变化，提交订单前必须实时询价。",noteEn:"Aggregated model availability and pricing can change; quote before order." },
  { id:"gemini",name:"Google",product:"Gemini",kind:"language",region:"global",color:"#4285f4",keyUrl:"https://aistudio.google.com/app/apikey",docsUrl:"https://ai.google.dev/gemini-api/docs/api-key",env:"GEMINI_API_KEY",supports:["多模态理解","长上下文","审校"],stepsZh:["进入 Google AI Studio","创建或选择 Google Cloud Project","生成 API Key 并限制可用 API","不要把浏览器端密钥提交到仓库"],stepsEn:["Open Google AI Studio","Create or select a Cloud project","Generate and restrict an API key","Never commit browser-exposed keys"],noteZh:"可作为多模态理解与审校线路。",noteEn:"Useful for multimodal understanding and review." },
];

export const BUILD_CONNECTORS = [
  { id:"github",name:"GitHub",roleZh:"代码仓库",roleEn:"Source control",url:"https://github.com/settings/installations",docs:"https://docs.github.com/en/apps/using-github-apps/about-using-github-apps",stepsZh:["优先安装 GitHub App，而不是粘贴长期 PAT","只授权选定仓库，并坚持最小权限","写入、提交与部署前再次确认目标分支"],status:"oauth-required" },
  { id:"vercel",name:"Vercel",roleZh:"预览与部署",roleEn:"Preview & deployment",url:"https://vercel.com/new",docs:"https://vercel.com/docs/git/vercel-for-github",stepsZh:["先连接 GitHub 中指定仓库","区分 Preview 与 Production 环境变量","首次生产发布必须显示域名、分支和变更摘要"],status:"oauth-required" },
  { id:"supabase",name:"Supabase",roleZh:"数据库与存储",roleEn:"Database & storage",url:"https://supabase.com/dashboard",docs:"https://supabase.com/docs",stepsZh:["新建或选择项目","客户端只使用 anon key；service role 仅留服务端","先应用迁移和 RLS，再接真实用户数据"],status:"manual-setup" },
  { id:"cloudflare",name:"Cloudflare",roleZh:"域名与边缘服务",roleEn:"Domain & edge",url:"https://dash.cloudflare.com/",docs:"https://developers.cloudflare.com/",stepsZh:["选择明确的站点和账户","预览变更，不自动修改 DNS","缓存、R2 与 Workers 分开授权"],status:"manual-setup" },
];

export const TRAINING_SOURCES = [
  { name:"灵犀场自有导演样本", license:"First-party / opt-in", state:"preferred", useZh:"自有剧本→分镜→审校数据；仅用户明确授权后进入训练集。",url:"/legal/sasi" },
  { name:"Wikimedia Commons", license:"Per-file license", state:"verify", useZh:"图像与音视频逐素材核验署名、相同方式共享和其他条件。",url:"https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia" },
  { name:"NASA Image and Video Library", license:"US government + exceptions", state:"verify", useZh:"适合宇宙视觉研究；需排除第三方版权、人物肖像、标识与暗示背书。",url:"https://www.nasa.gov/nasa-brand-center/images-and-media/" },
  { name:"Project Gutenberg", license:"Public domain in the US", state:"verify", useZh:"可提取经典叙事结构；上线地区仍需核验作品版权状态。",url:"https://www.gutenberg.org/policy/permission.html" },
  { name:"Blender Open Movies", license:"Project-specific Creative Commons", state:"verify", useZh:"可研究分镜、资产和镜头流程；必须遵守每个项目的许可与署名要求。",url:"https://studio.blender.org/films/" },
  { name:"YouTube-8M", license:"Features / research dataset", state:"research", useZh:"主要是特征与标签，不是可直接商用的原始视频训练仓。",url:"https://research.google.com/youtube8m/" },
];
