import type {LingxiLang} from "@/lib/lingxi-i18n";
type K="title"|"lead"|"script"|"placeholder"|"parse"|"parsed"|"format"|"invalid"|"tooMany"|"service"|"noService"|"ratio"|"refs"|"rights"|"quote"|"quoted"|"whole"|"supplier"|"confirm"|"refresh"|"uncertain"|"openVideo"|"assemble"|"busy"|"failed"|"back";
const en:Record<K,string>={
 title:"Build a continuous multi-episode drama",lead:"Plan up to 60 shots locally, then quote and generate only when a verified creation service is connected.",
 script:"Episode plan",placeholder:"1 | 5 | The lead walks into the rain, camera slowly pushes in.",parse:"Organize shots",parsed:"Shots organized. Review them before requesting a price.",
 format:"One line per shot: episode | seconds | shot description",invalid:"Each line needs episode, seconds, and a shot description.",tooMany:"Provide 1–60 shots.",
 service:"Creation method",noService:"No verified video creation method is connected yet. You can still prepare the episode plan.",ratio:"Aspect ratio",refs:"Shared character / scene references",
 rights:"I have the right to use these materials and agree to required generated-content labeling.",quote:"See episode prices",quoted:"Prices saved. Confirm only the shots you want to generate.",
 whole:"Whole project estimate",supplier:"Actual charges are billed by the connected service.",confirm:"Confirm remaining shots",refresh:"Refresh progress",uncertain:"A task needs verification. Check the connected service before submitting more paid shots.",
 openVideo:"Open video",assemble:"Assemble finished clips into MP4",busy:"Working…",failed:"The request did not finish.",back:"Back to creation"
};
const zh:Record<K,string>={...en,title:"连续短剧，一次整理多集镜头",lead:"最多先在本机整理 60 个镜头；只有连接并验证可用的创作服务后，才会报价和生成。",script:"多集分镜",placeholder:"1 | 5 | 女主走进雨后的街道，镜头缓慢推进。",parse:"整理镜头",parsed:"镜头已经整理好，请检查后再获取价格。",format:"每行填写：集数 | 秒数 | 镜头描述",invalid:"每行都需要集数、秒数和镜头描述。",tooMany:"请提供 1–60 个镜头。",service:"生成方式",noService:"当前没有已验证的视频生成方式。你仍然可以先完成多集规划。",ratio:"画幅",refs:"共用角色／场景参考图",rights:"我拥有相关素材的使用权，并同意按要求标注生成内容。",quote:"查看每集费用",quoted:"价格已保存，只确认你准备生成的镜头。",whole:"整项预估",supplier:"实际费用由你连接的创作服务收取。",confirm:"确认剩余镜头",refresh:"查询本批进度",uncertain:"存在待核对任务，请先查看连接服务记录，不要继续重复付费提交。",openVideo:"打开视频",assemble:"把完成镜头合成 MP4",busy:"处理中…",failed:"这次请求没有完成。",back:"返回创作"};
const ja:Record<K,string>={...en,title:"連続ドラマを複数話まとめて構成",lead:"最大60ショットをローカルで整理し、確認済みの制作サービス接続後にのみ見積もり・生成します。",script:"複数話の絵コンテ",parse:"ショットを整理",service:"生成方法",noService:"確認済みの動画生成方法はまだありません。先に構成だけ作れます。",ratio:"画面比率",rights:"素材の利用権を保有し、必要な生成コンテンツ表示に同意します。",quote:"話ごとの料金を見る",confirm:"残りのショットを確認",refresh:"進捗を更新",assemble:"完成ショットを MP4 に結合",back:"制作へ戻る"};
const ko:Record<K,string>={...en,title:"여러 화의 연속 숏드라마 구성",lead:"최대 60개 장면을 로컬에서 먼저 정리하고, 검증된 제작 서비스가 연결된 경우에만 견적과 생성을 진행합니다.",script:"다화 장면 계획",parse:"장면 정리",service:"생성 방식",noService:"검증된 영상 생성 방식이 없습니다. 먼저 다화 구성을 준비할 수 있습니다.",ratio:"화면 비율",rights:"자료 사용 권한을 보유하고 필요한 생성 콘텐츠 표시에 동의합니다.",quote:"회차별 비용 보기",confirm:"남은 장면 확인",refresh:"진행 상황 새로고침",assemble:"완성 장면을 MP4로 합치기",back:"창작으로 돌아가기"};
const fr:Record<K,string>={...en,title:"Construire une série continue en plusieurs épisodes",lead:"Organisez jusqu’à 60 plans localement. Le devis et la génération ne commencent qu’après connexion d’un service vérifié.",script:"Plan multi-épisodes",parse:"Organiser les plans",service:"Mode de création",noService:"Aucun service vidéo vérifié n’est connecté. Vous pouvez néanmoins préparer la série.",ratio:"Format",rights:"Je possède les droits d’utilisation des éléments et j’accepte le marquage requis.",quote:"Voir le prix par épisode",confirm:"Confirmer les plans restants",refresh:"Actualiser la progression",assemble:"Assembler les plans en MP4",back:"Retour à la création"};
const de:Record<K,string>={...en,title:"Eine fortlaufende Serie mit mehreren Episoden erstellen",lead:"Bis zu 60 Shots lokal planen; Angebot und Generierung erst nach Verbindung eines verifizierten Dienstes.",script:"Mehrteiliger Shot-Plan",parse:"Shots ordnen",service:"Erstellungsart",noService:"Noch kein verifizierter Videodienst verbunden. Die Planung ist trotzdem möglich.",ratio:"Seitenverhältnis",rights:"Ich besitze die Nutzungsrechte und stimme der erforderlichen Kennzeichnung zu.",quote:"Preise je Episode",confirm:"Restliche Shots bestätigen",refresh:"Fortschritt aktualisieren",assemble:"Fertige Shots zu MP4 verbinden",back:"Zurück zur Erstellung"};
const es:Record<K,string>={...en,title:"Crear una serie continua de varios episodios",lead:"Organiza hasta 60 planos de forma local. Solo se cotiza y genera cuando hay un servicio verificado conectado.",script:"Plan de episodios",parse:"Organizar planos",service:"Método de creación",noService:"No hay un servicio de vídeo verificado conectado. Puedes preparar el plan igualmente.",ratio:"Relación de aspecto",rights:"Tengo derechos para usar estos materiales y acepto el etiquetado requerido.",quote:"Ver precios por episodio",confirm:"Confirmar planos restantes",refresh:"Actualizar progreso",assemble:"Unir planos terminados en MP4",back:"Volver a creación"};
const pt:Record<K,string>={...en,title:"Criar uma série contínua com vários episódios",lead:"Organize até 60 cenas localmente. O orçamento e a geração só começam com um serviço verificado conectado.",script:"Plano de episódios",parse:"Organizar cenas",service:"Forma de criação",noService:"Nenhum serviço de vídeo verificado está conectado. Você ainda pode preparar o plano.",ratio:"Proporção",rights:"Tenho direito de usar estes materiais e aceito a rotulagem exigida.",quote:"Ver preços por episódio",confirm:"Confirmar cenas restantes",refresh:"Atualizar progresso",assemble:"Juntar cenas em MP4",back:"Voltar à criação"};
const ar:Record<K,string>={...en,title:"إنشاء سلسلة درامية متصلة متعددة الحلقات",lead:"نظّم حتى 60 لقطة محليًا، ولا يبدأ التسعير أو الإنشاء إلا بعد ربط خدمة موثقة.",script:"خطة الحلقات",parse:"تنظيم اللقطات",service:"طريقة الإنشاء",noService:"لا توجد خدمة فيديو موثقة متصلة بعد، لكن يمكنك إعداد الخطة أولًا.",ratio:"نسبة العرض",rights:"أملك حق استخدام هذه المواد وأوافق على الوسم المطلوب للمحتوى المُنشأ.",quote:"عرض سعر كل حلقة",confirm:"تأكيد اللقطات المتبقية",refresh:"تحديث التقدم",assemble:"دمج اللقطات في MP4",back:"العودة إلى الإنشاء"};
const D:Record<LingxiLang,Record<K,string>>={zh,en,ja,ko,fr,de,es,pt,ar};
export function seriesText(lang:LingxiLang,key:K){return (D[lang]??en)[key]}
