-- LINGXIFIELD remote migration history mirror
-- version: 20260929081900
-- name: nutrition_import_session_v10
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
