-- LINGXIFIELD remote migration history mirror
-- version: 20261001232529
-- name: food_analysis_billing_v19
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
