-- LINGXIFIELD remote migration history mirror
-- version: 20261001050049
-- name: withdrawal_variable_collision_fix
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
