-- LINGXIFIELD remote migration history mirror
-- version: 20260930060103
-- name: release_20260930_2_food_region_resolver_announcement
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
