-- LINGXIFIELD remote migration history mirror
-- version: 20260922042640
-- name: secure_tool_fulfillment_v5
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
