-- LINGXIFIELD remote migration history mirror
-- version: 20260930043305
-- name: sasi_living_intelligence_20260930
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
