-- LINGXIFIELD remote migration history mirror
-- version: 20260929131057
-- name: food_production_atomic_session_v17
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
