-- LINGXIFIELD remote migration history mirror
-- version: 20260929134547
-- name: food_production_closeout_v18_safe
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
