-- LINGXIFIELD remote migration history mirror
-- version: 20260919234449
-- name: sasi_large_asset_uploads
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
