-- LINGXIFIELD remote migration history mirror
-- version: 20261002231527
-- name: unified_sasi_balance_pricing_v49
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
