-- LINGXIFIELD remote migration history mirror
-- version: 20260929081656
-- name: global_food_production_master_v9_import
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
