-- LINGXIFIELD remote migration history mirror
-- version: 20260930052720
-- name: move_pg_trgm_to_extensions_20260930
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
