-- LINGXIFIELD remote migration history mirror
-- version: 20260924151848
-- name: paypal_usd_order_currency_convergence_v14514
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
