-- LINGXIFIELD remote migration history mirror
-- version: 20260922043645
-- name: tool_paid_jobs_v6
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
