-- LINGXIFIELD remote migration history mirror
-- version: 20261001052329
-- name: withdrawal_principal_hold_guard
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
