-- LINGXIFIELD remote migration history mirror
-- version: 20260928084451
-- name: sasi_v5_quality_learning_foundation
-- This version is already applied in production Supabase migration history.
-- This marker restores Git/Supabase timestamp parity. It intentionally performs no DDL.
-- Canonical production schema remains the source of truth for this historical entry.
