"use client";

import { FormEvent, useRef, useState } from "react";
import type { StellarTraceResult } from "@/lib/stellar-trace";
import { PublicationCopy, PublicationLabel, PublicationPage } from "@/app/mini-report/PublicationPage";
import { ALL_REPORT_PDF_ART } from "@/lib/report-art-registry";

const art=(index:number)=>ALL_REPORT_PDF_ART[index%ALL_REPORT_PDF_ART.length].src;
const levelZh={divergent:"发散",weak:"弱收敛",moderate:"中等收敛",strong:"较强收敛",high:"高度收敛"} as const;

function CircularConvergence({result}:{result:StellarTraceResult}){
  const size=260,center=130,radius=92;
  const point=(bearing:number,r=radius)=>{const angle=(bearing-90)*Math.PI/180;return{x:center+Math.cos(angle)*r,y:center+Math.sin(angle)*r}};
  return <div className="mt-5 grid items-center gap-4 sm:grid-cols-[280px_1fr]">
    <svg viewBox="0 0 260 260" className="mx-auto w-full max-w-[260px]" role="img" aria-label="四层方向圆周分布图">
      <circle cx={center} cy={center} r={radius} fill="rgba(255,255,255,.2)" stroke="#6a8f89" strokeWidth="1.5"/>
      {[0,90,180,270].map(value=>{const p=point(value);return <g key={value}><line x1={center} y1={center} x2={p.x} y2={p.y} stroke="rgba(67,78,96,.18)"/><text x={p.x} y={p.y+(value===0? -7:value===180?14:4)} textAnchor="middle" fontSize="10" fill="#696473">{value}°</text></g>})}
      {result.evidence.map((item,index)=>{const p=point(item.bearing);return <g key={item.id}><line x1={center} y1={center} x2={p.x} y2={p.y} stroke={["#557f79","#8a6e9f","#b48362","#586d9f"][index]} strokeWidth="2"/><circle cx={p.x} cy={p.y} r="5" fill={["#557f79","#8a6e9f","#b48362","#586d9f"][index]}/></g>})}
      <text x={center} y={center-4} textAnchor="middle" fontSize="22" fill="#302941">R={result.direction.resultantLength.toFixed(3)}</text>
      <text x={center} y={center+18} textAnchor="middle" fontSize="12" fill="#696473">{result.direction.qualified?levelZh[result.direction.level]:"方位未获资格"}</text>
    </svg>
    <div className="space-y-2 text-[13px] leading-6 text-[#454151]">
      {result.evidence.map(item=><div key={item.id} className="flex items-start justify-between gap-4 border-b border-[#4c4966]/10 pb-2"><span>{item.labelZh}</span><strong>{item.bearing}° · {item.relativeRangeBand}</strong></div>)}
      {result.direction.modes.length>0&&<div className="pt-2 text-[12px] leading-5 text-[#696473]"><strong className="text-[#557f79]">方向簇（仅描述分布）</strong>{result.direction.modes.slice(0,2).map((mode,index)=><p key={`${mode.center}-${index}`} className="mt-1">{index===0?"主簇":"次簇"} {mode.center}° · {Math.round(mode.mass*100)}% 证据量 · 簇内 R={mode.resultantLength.toFixed(3)}</p>)}</div>}
    </div>
  </div>;
}

export default function StellarTraceExperience({unlocked=false}:{unlocked?:boolean}){
  const[result,setResult]=useState<StellarTraceResult|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[exporting,setExporting]=useState(false);const resultRef=useRef<HTMLDivElement>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");setResult(null);const form=new FormData(event.currentTarget);try{const response=await fetch("/api/stellar-trace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(form.entries()),consent:form.get("consent")==="on"})});const data=await response.json();if(!response.ok)throw new Error(data.error||"星迹暂未形成");setResult(data);requestAnimationFrame(()=>document.getElementById("stellar-result")?.scrollIntoView({behavior:"smooth"}))}catch(reason){setError(reason instanceof Error?reason.message:"星迹暂未形成")}finally{setLoading(false)}}
  const summary=result?`灵犀场星迹 · 万里追踪\n方位状态：${levelZh[result.direction.level]}\n圆周集中度：R=${result.direction.resultantLength.toFixed(3)}\n${result.direction.qualified&&result.direction.sector?`合格方向扇区：${result.direction.sector[0]}°—${result.direction.sector[1]}°`:`当前不足以形成主候选方位。`}\n距离状态：未校准，不输出公里数。\n候选坐标：未形成。\n\n${result.modelBoundaryZh}\n${result.safetyBoundaryZh}`:"";
  async function copy(){if(summary)await navigator.clipboard.writeText(summary)}
  async function downloadPdf(){if(!resultRef.current||!result)return;setExporting(true);setError("");try{const{exportPublicationPagesPdf}=await import("@/lib/pdf-export");await exportPublicationPagesPdf({containerRef:resultRef.current,fileName:"灵犀场星迹-万里追踪-研究档案.pdf"})}catch(reason){setError(reason instanceof Error?reason.message:"PDF 未能生成")}finally{setExporting(false)}}
  async function saveImage(){const page=resultRef.current?.querySelector<HTMLElement>(".lx-pdf-page");if(!page)return;const{default:html2canvas}=await import("html2canvas");const canvas=await html2canvas(page,{scale:2,useCORS:true,backgroundColor:"#eef0f6"});const link=document.createElement("a");link.download="灵犀场星迹-方向资格检验.png";link.href=canvas.toDataURL("image/png");link.click()}
  return <main className="min-h-screen bg-[radial-gradient(circle_at_14%_8%,rgba(121,96,186,.34),transparent_30%),radial-gradient(circle_at_86%_22%,rgba(40,155,168,.25),transparent_34%),#07112d] px-4 py-14 text-bone sm:px-6">
    <section className="mx-auto max-w-5xl"><p className="text-xs uppercase tracking-[.34em] text-lattice">LINGXI STELLAR TRACE · RESEARCH FIELD</p><h1 className="mt-5 font-display text-4xl font-light sm:text-6xl">灵犀场星迹 · 万里追踪</h1><p className="mt-4 font-display text-xl text-lattice">循时而索迹，先验其方，再论其位。</p><p className="mt-7 max-w-3xl text-sm leading-8 text-bone-dim">九域天文位置是可复算的事实层；四层方向是实验投影层。系统先检验四层是否真正收敛，方向不合格便停止，不制造主方向、公里数或候选坐标。</p><div className="mt-6 border-l border-amber/60 bg-white/[.035] px-5 py-4 text-xs leading-6 text-bone-dim">研究版本不读取设备、通信、GPS 或实时行踪。涉及失联、走失、威胁或人身安全，请先报警并使用可核验的通信、交通和救援渠道。</div></section>
    {!unlocked&&<section className="mx-auto mt-12 max-w-5xl border border-amber/35 bg-amber/[.05] p-7 text-center backdrop-blur-xl sm:p-10"><p className="text-xs tracking-[.28em] text-amber">RESEARCH ARCHIVE · ¥688</p><h2 className="mt-4 font-display text-3xl">星迹研究权益尚未开启</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-bone-dim">网页与微信小程序共享同一项长期权益。当前研究版坚持证据停止门：不能成立的方向、距离与坐标不会被生成。</p><a href="/account" className="mt-7 inline-flex border border-amber/55 px-7 py-3 text-sm tracking-wider text-amber">登录或查看我的权益</a></section>}
    {unlocked&&<form onSubmit={submit} className="mx-auto mt-12 grid max-w-5xl gap-5 border border-white/10 bg-white/[.045] p-5 backdrop-blur-xl sm:grid-cols-2 sm:p-8">
      <label className="text-xs tracking-wider text-bone-dim">寻踪对象姓名<input required name="name" maxLength={40} className="mt-2 w-full border border-white/15 bg-void/50 px-4 py-3 text-base text-bone outline-none focus:border-lattice"/></label><label className="text-xs tracking-wider text-bone-dim">真实出生日期<input required type="date" name="birthDate" className="mt-2 w-full border border-white/15 bg-void/50 px-4 py-3 text-base text-bone outline-none focus:border-lattice"/></label><label className="text-xs tracking-wider text-bone-dim">出生时间（若知）<input type="time" name="birthTime" className="mt-2 w-full border border-white/15 bg-void/50 px-4 py-3 text-base text-bone outline-none focus:border-lattice"/></label><label className="text-xs tracking-wider text-bone-dim">最后有效联系时间<input required type="datetime-local" name="lastContactAt" className="mt-2 w-full border border-white/15 bg-void/50 px-4 py-3 text-base text-bone outline-none focus:border-lattice"/></label><label className="text-xs tracking-wider text-bone-dim">最后已知纬度<input required type="number" step="0.0001" min="-90" max="90" name="lastKnownLat" placeholder="31.2304" className="mt-2 w-full border border-white/15 bg-void/50 px-4 py-3 text-base text-bone outline-none focus:border-lattice"/></label><label className="text-xs tracking-wider text-bone-dim">最后已知经度<input required type="number" step="0.0001" min="-180" max="180" name="lastKnownLon" placeholder="121.4737" className="mt-2 w-full border border-white/15 bg-void/50 px-4 py-3 text-base text-bone outline-none focus:border-lattice"/></label><label className="text-xs tracking-wider text-bone-dim sm:col-span-2">最后一次有效信息（选填）<textarea name="context" maxLength={500} rows={3} className="mt-2 w-full resize-none border border-white/15 bg-void/50 px-4 py-3 text-base leading-7 text-bone outline-none focus:border-lattice"/></label><label className="flex items-start gap-3 text-xs leading-6 text-bone-dim sm:col-span-2"><input required type="checkbox" name="consent" className="mt-1"/><span>我确认有权使用所填资料，并理解结果不得用于跟踪、骚扰、监控或替代警方与救援定位。</span></label><button disabled={loading} className="border border-lattice/60 bg-lattice/10 px-6 py-4 text-sm tracking-[.22em] text-lattice disabled:opacity-50 sm:col-span-2">{loading?"九域正在合参…":"展开方向资格检验"}</button>{error&&<p className="text-center text-sm text-rose-300 sm:col-span-2">{error}</p>}
    </form>}
    {result&&<section id="stellar-result" className="mx-auto mt-16 max-w-[794px] scroll-mt-8"><div ref={resultRef} className="space-y-7">
      <PublicationPage index={1} total={2} eyebrow="NINE-FIELD ASTRONOMICAL FRAME" title="方向资格检验" art={art(result.artIndexes[0])} layout="cover"><PublicationLabel>FOUR-LAYER EVIDENCE · CIRCULAR CONVERGENCE</PublicationLabel><p className="mt-4 font-display text-[34px] leading-tight text-[#557f79]">{result.direction.qualified?levelZh[result.direction.level]:"方位未收敛"}</p><PublicationCopy>圆周集中度 R = {result.direction.resultantLength.toFixed(3)}，离散度 = {result.direction.circularDispersion.toFixed(3)}。{result.direction.qualified&&result.direction.sector?`方向通过资格门，扇区为 ${result.direction.sector[0]}°—${result.direction.sector[1]}°。`:`数学均值仅保留作审计，不作为主候选方向。`}</PublicationCopy><CircularConvergence result={result}/></PublicationPage>
      <PublicationPage index={2} total={2} eyebrow="EVIDENCE TRACE · OUTPUT BOUNDARY" title="证据链与停止条件" art={art(result.artIndexes[1])} layout="full"><PublicationLabel>九域事实层 ≠ 四层投影层</PublicationLabel><div className="mt-4 grid grid-cols-3 gap-2">{result.snapshots.map(s=><div key={s.epoch} className="border border-[#4c4966]/15 bg-white/25 p-3"><p className="text-[12px] font-semibold text-[#557f79]">{s.labelZh}</p><p className="mt-1 text-[11px] text-[#696473]">JD {s.julianDay}</p></div>)}</div><div className="mt-5 space-y-3">{result.evidence.map(item=><div key={item.id} className="border-l-2 border-[#557f79]/45 pl-3"><p className="text-[13px] font-semibold">{item.labelZh} · {item.projectionRuleId}</p><p className="mt-1 text-[12px] leading-5 text-[#565162]">{item.projectionBasisZh}</p><p className="mt-1 text-[12px] text-[#7b5f55]">距离映射：{item.relativeRangeBand}；公里规则未校准</p></div>)}</div><div className="mt-5 border border-[#8b6759]/25 bg-[#fff8f1]/55 p-4"><p className="font-display text-xl text-[#6f5147]">未形成候选坐标区域</p><p className="mt-2 text-[13px] leading-6">P50 / P75 / P90 均保持 Missing。{result.distance.explanationZh}</p></div><p className="mt-4 border-t border-[#4c4966]/15 pt-3 text-[11px] leading-5 text-[#696473]">{result.modelBoundaryZh}<br/>{result.safetyBoundaryZh}</p></PublicationPage>
    </div><div className="mt-7 grid gap-3 sm:grid-cols-3"><button onClick={copy} className="border border-lattice/45 py-3 text-xs tracking-widest2 text-lattice">复制结果</button><button onClick={saveImage} className="border border-lattice/45 py-3 text-xs tracking-widest2 text-lattice">保存图片</button><button onClick={downloadPdf} disabled={exporting} className="border border-lattice/45 py-3 text-xs tracking-widest2 text-lattice disabled:opacity-50">{exporting?"正在生成…":"下载 2 页研究 PDF"}</button></div></section>}
  </main>;
}
