import {ENGINE_CATALOG} from "../catalog";import type {EngineProbe} from "../types";import {commandFor,runCommand} from "./command";
function firstLine(s:string){return s.split(/\r?\n/).map(x=>x.trim()).find(Boolean)?.slice(0,240)||"unknown"}
async function probePythonModule(id:string,module:string):Promise<EngineProbe>{const started=Date.now();const py=process.env.LINGXI_PYTHON_BIN||"python";try{const code=`import ${module} as m; print(getattr(m,'__version__','installed'))`;const r=await runCommand(py,["-c",code],{timeoutMs:8000,acceptCodes:[0]});return{id,available:true,version:firstLine(r.stdout),latencyMs:Date.now()-started,runtime:"python"}}catch(e){return{id,available:false,reason:e instanceof Error?e.message:String(e),latencyMs:Date.now()-started,runtime:"python"}}}
async function probeNodeModule(id:string,module:string):Promise<EngineProbe>{const started=Date.now();try{const r=await runCommand(process.execPath,["-e",`import('${module}').then(()=>console.log('installed')).catch(e=>{console.error(e.message);process.exit(2)})`],{timeoutMs:8000});return{id,available:true,version:firstLine(r.stdout),latencyMs:Date.now()-started,runtime:"node-module"}}catch(e){return{id,available:false,reason:e instanceof Error?e.message:String(e),latencyMs:Date.now()-started,runtime:"node-module"}}}
export async function probeEngine(id:string):Promise<EngineProbe>{const d=ENGINE_CATALOG.find(x=>x.id===id);if(!d)return{id,available:false,reason:"UNKNOWN_ENGINE"};if(d.runtime==="browser"||d.runtime==="database")return{id,available:true,version:"built-in",runtime:d.runtime};
 const pyMap:Record<string,string>={paddleocr:"paddleocr",opencv:"cv2",mediapipe:"mediapipe","faster-whisper":"faster_whisper",argos:"argostranslate",kokoro:"kokoro",jieba:"jieba","real-esrgan":"realesrgan",gfpgan:"gfpgan"};if(pyMap[id])return probePythonModule(id,pyMap[id]);
 const nodeMap:Record<string,string>={"sharp-libvips":"sharp",mammoth:"mammoth",exceljs:"exceljs",readability:"@mozilla/readability",dompurify:"dompurify",turndown:"turndown"};if(nodeMap[id])return probeNodeModule(id,nodeMap[id]);
 if(d.runtime==="http-service"){const base=process.env.LINGXI_GOTENBERG_URL;if(!base)return{id,available:false,reason:"LINGXI_GOTENBERG_URL_NOT_SET",runtime:d.runtime};try{const c=new AbortController();const t=setTimeout(()=>c.abort(),3000);const r=await fetch(base.replace(/\/$/,"")+"/health",{signal:c.signal});clearTimeout(t);return{id,available:r.ok,version:r.headers.get("x-gotenberg-version")||undefined,reason:r.ok?undefined:`HTTP_${r.status}`,runtime:d.runtime}}catch(e){return{id,available:false,reason:e instanceof Error?e.message:String(e),runtime:d.runtime}}
 }
 const command=commandFor(d.commandEnv,d.defaultCommand);if(!command)return{id,available:false,reason:"COMMAND_NOT_CONFIGURED",runtime:d.runtime};try{const r=await runCommand(command,d.versionArgs||["--version"],{timeoutMs:8000,acceptCodes:[0,1]});return{id,available:true,version:firstLine(r.stdout||r.stderr),latencyMs:r.elapsedMs,runtime:d.runtime}}catch(e){return{id,available:false,reason:e instanceof Error?e.message:String(e),runtime:d.runtime};}}
export async function probeAllServerEngines(){const ids=ENGINE_CATALOG.filter(x=>x.runtime!=="browser"&&x.runtime!=="database").map(x=>x.id);const out:EngineProbe[]=[];for(const id of ids)out.push(await probeEngine(id));return out;}
