"use client";
import {useState} from "react";
import {AdminData,Withdrawal,adminMoney,paymentName,adminDate} from "@/lib/money/admin-dashboard-types";
import s from "./AdminDashboard.module.css";
function state(w:Withdrawal){if(w.status==='cancelled')return '已取消 · 余额已恢复';if(w.status==='completed')return '渠道已确认完成';if(w.failure_code==='PROVIDER_FUNDS_REQUIRED')return '需要补足商户资金';if(['PROVIDER_ACTION_REQUIRED','OPERATOR_REVIEW_REQUIRED'].includes(w.failure_code||''))return '需要人工处理';if(w.status==='requested'&&!w.submission_confirmed_at)return '待用户确认';if(['failed','rejected'].includes(w.status))return '未完成 · 余额已释放';return '正在确认退款结果';}
export default function AdminRefundPanel({data,busy,operate}:{data:AdminData;busy:boolean;operate:(action:string,id?:string)=>Promise<void>}){
 const[filter,setFilter]=useState('all');
 return <><div className={s.notice}>提醒邮箱：{data.notifyEmail} · {data.emailConfigured?'邮件服务已配置':'邮件服务未配置'} · 待发送 {data.stats.notices_pending} 条 <button disabled={busy} onClick={()=>void operate('send-notices')}>重试发送提醒</button></div>
 <div className={s.cards}>{['wechat','alipay','paypal'].map(p=>{const c=data.stats.channels.find(x=>x.provider===p),currency=c?.provider_currency||(p==='paypal'?'USD':'CNY');return <article key={p} className={s.card}><h3>{paymentName(p)}</h3><p>需要补资金的退款金额</p><strong>{adminMoney(currency,(c?.funds_required_minor||0)/100)}</strong><p>已确认待处理 {c?.active_count||0} 笔 · {adminMoney(currency,(c?.pending_minor||0)/100)}</p><small>待用户确认 {c?.awaiting_confirmation||0} 笔</small></article>})}</div>
 <div className={s.sectionTitle}><h2>退款与提现申请</h2><select aria-label="退款渠道" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">所有渠道</option><option value="wechat">微信支付</option><option value="alipay">支付宝</option><option value="paypal">PayPal</option></select></div><p className={s.muted}>最近 100 条申请。查询操作会继续处理原申请。</p>
 <div className={s.tableWrap}><table className={s.table}><thead><tr><th>提交时间</th><th>渠道与金额</th><th>处理状态</th><th>申请详情</th></tr></thead><tbody>{data.withdrawals.filter(w=>filter==='all'||w.provider===filter).map(w=><tr key={w.id}><td>{adminDate(w.created_at)}</td><td><b>{adminMoney(w.provider_currency,w.provider_amount_minor/100)}</b><small>{paymentName(w.provider)}</small></td><td>{state(w)}</td><td><details><summary>查看详情</summary><p>申请编号：{w.id}</p><p>渠道退款编号：{w.provider_refund_id||'等待渠道返回'}</p>{w.currency!==w.provider_currency&&<p>对应余额：{adminMoney(w.currency,w.amount_minor/100)}</p>}{w.failure_code==='PROVIDER_FUNDS_REQUIRED'&&<p>请先补足对应商户账户的退款资金。</p>}</details>{w.submission_confirmed_at&&['requested','processing'].includes(w.status)&&<button disabled={busy} onClick={()=>void operate('retry',w.id)}>查询并继续原单</button>}</td></tr>)}</tbody></table>{!data.withdrawals.length&&<p className={s.empty}>暂无申请</p>}</div>
 <div className={s.sectionTitle}><h2>邮件提醒记录</h2></div><p className={s.muted}>已发送表示邮件服务已受理，实际收件情况以收件箱为准。</p><div className={s.panel}>{data.notices.map(n=><div className={s.activity} key={n.id}><span>{n.status==='sent'?'已发送':n.status==='failed'?'发送未完成，将重试':n.status==='sending'?'发送中':'等待发送'}</span><small>本轮尝试 {n.attempt_count} 次</small></div>)}{!data.notices.length&&<p className={s.empty}>暂无邮件记录</p>}</div></>;
}
